Repository JesusFilm/core, pull requests merged in 2021-09, with the labels that each got.

#18 Storybook controls
  apps/journeys/src/components/JourneysThemeProvider/theme.ts
  apps/journeys/src/components/blocks/RadioOption/RadioOption.spec.tsx
  apps/journeys/src/components/blocks/RadioOption/RadioOption.stories.tsx
  apps/journeys/src/components/blocks/RadioOption/RadioOption.tsx
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.spec.tsx
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.stories.tsx
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.tsx
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestions.stories.tsx
  apps/journeys/src/types.ts
Labels: question, component

#19 Connect Gateway to Journeys
  .env
  apps/api-gateway/schema.graphql
  apps/api-gateway/src/environments/environment.prod.ts
  apps/api-gateway/src/environments/environment.ts
  apps/api-gateway/src/environments/types.ts
  apps/api-gateway/src/main.ts
  apps/api-gateway/supergraph.yml
  apps/api-journeys/prisma/seed.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/main.ts
  apps/api-journeys/src/modules/block/__generated__/types.ts
  apps/api-journeys/src/modules/block/index.spec.ts
  apps/api-journeys/src/modules/block/index.ts
  apps/journeys/.env.development
  apps/journeys/.env.production
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/apollo.config.js
  apps/journeys/pages/[id].tsx
  apps/journeys/pages/[slug].tsx
  apps/journeys/src/components/BlockRenderer/BlockRenderer.spec.tsx
  apps/journeys/src/components/BlockRenderer/BlockRenderer.tsx
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/Conductor/conductorSlice.spec.ts
  apps/journeys/src/components/Conductor/conductorSlice.ts
  apps/journeys/src/components/blocks/RadioOption/RadioOption.spec.tsx
  apps/journeys/src/components/blocks/RadioOption/RadioOption.stories.tsx
  apps/journeys/src/components/blocks/RadioOption/RadioOption.tsx
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.spec.tsx
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.stories.tsx
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.tsx
  apps/journeys/src/components/blocks/Step/Step.spec.tsx
  apps/journeys/src/components/blocks/Step/Step.tsx
  apps/journeys/src/components/blocks/Video/Video.spec.tsx
  apps/journeys/src/components/blocks/Video/Video.tsx
  apps/journeys/src/data/index.ts
  apps/journeys/src/libs/client/client.ts
  apps/journeys/src/libs/client/index.ts
  apps/journeys/src/libs/transformer/transformer.spec.ts
  apps/journeys/src/libs/transformer/transformer.ts
  apps/journeys/src/types.ts
  package-lock.json
  package.json
  workspace.json
Labels: enhancement

#30 Video-Component
  apps/api-gateway/schema.graphql
  apps/api-journeys/prisma/seed.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/modules/block/__generated__/types.ts
  apps/api-journeys/src/modules/block/index.spec.ts
  apps/api-journeys/src/modules/block/index.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/pages/[journeyId].tsx
  apps/journeys/src/components/BlockRenderer/BlockRenderer.spec.tsx
  apps/journeys/src/components/blocks/Video/Video.spec.tsx
  apps/journeys/src/components/blocks/Video/Video.stories.tsx
  apps/journeys/src/components/blocks/Video/Video.tsx
  package-lock.json
  package.json
Labels: component

#46 add responses and signup block
  apps/api-gateway/schema.graphql
  apps/api-journeys/codegen.yml
  apps/api-journeys/prisma/migrations/20210921212316_create_responses/migration.sql
  apps/api-journeys/prisma/migrations/20210923013533_add_signup_block_type/migration.sql
  apps/api-journeys/prisma/migrations/20210923020041_add_type_to_response/migration.sql
  apps/api-journeys/prisma/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/modules/application/index.ts
  apps/api-journeys/src/modules/block/__generated__/types.ts
  apps/api-journeys/src/modules/block/index.spec.ts
  apps/api-journeys/src/modules/block/index.ts
  apps/api-journeys/src/modules/response/__generated__/types.ts
  apps/api-journeys/src/modules/response/index.spec.ts
  apps/api-journeys/src/modules/response/index.ts
  apps/api-journeys/types.d.ts
Labels: enhancement

#47 Responses frontend
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/RadioQuestionResponseCreate.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/src/components/BlockRenderer/BlockRenderer.tsx
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.spec.tsx
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.stories.tsx
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.tsx
  apps/journeys/src/components/blocks/RadioQuestion/index.ts
Labels: enhancement

#52 change theme to themeName
  apps/api-gateway/schema.graphql
  apps/api-journeys/prisma/migrations/20210926224332_change_theme_to_theme_name_on_journey/migration.sql
  apps/api-journeys/prisma/schema.prisma
  apps/api-journeys/prisma/seed.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/modules/block/__generated__/types.ts
  apps/api-journeys/src/modules/block/index.spec.ts
  apps/api-journeys/src/modules/journey/__generated__/types.ts
  apps/api-journeys/src/modules/journey/index.spec.ts
  apps/api-journeys/src/modules/journey/index.ts
Labels: enhancement

#54 add themeName and themeMode to journeys
  apps/api-gateway/schema.graphql
  apps/api-journeys/prisma/migrations/20210927192249_add_theme_mode_on_journey/migration.sql
  apps/api-journeys/prisma/schema.prisma
  apps/api-journeys/prisma/seed.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/modules/block/index.spec.ts
  apps/api-journeys/src/modules/journey/__generated__/types.ts
  apps/api-journeys/src/modules/journey/index.spec.ts
  apps/api-journeys/src/modules/journey/index.ts
Labels: enhancement

#51 JourneyProgress
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/JourneyProgress/JourneyProgress.spec.tsx
  apps/journeys/src/components/JourneyProgress/JourneyProgress.stories.tsx
  apps/journeys/src/components/JourneyProgress/JourneyProgress.tsx
  apps/journeys/src/components/JourneyProgress/index.ts
  apps/journeys/src/libs/client/cache/blocks.ts
Labels: component

#27 Typography
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/TypographyFields.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/pages/[journeyId].tsx
  apps/journeys/src/components/blocks/Typography/Typography.spec.tsx
  apps/journeys/src/components/blocks/Typography/Typography.stories.tsx
  apps/journeys/src/components/blocks/Typography/Typography.tsx
  apps/journeys/src/components/blocks/Typography/index.ts
  apps/journeys/src/components/blocks/Typography/typographyFields.ts
  libs/shared/ui/__generated__/globalTypes.ts
  libs/shared/ui/src/libs/themes/base/theme.stories.tsx
  libs/shared/ui/src/libs/themes/base/theme.ts
  libs/shared/ui/src/libs/themes/base/tokens/components.ts
  libs/shared/ui/src/libs/themes/base/tokens/typography.ts
Labels: component

#61 change spacing to 4
  apps/journeys/src/components/blocks/Typography/Typography.stories.tsx
  libs/shared/ui/src/libs/themes/base/theme.stories.tsx
  libs/shared/ui/src/libs/themes/base/tokens/components.ts
  libs/shared/ui/src/libs/themes/base/tokens/spacing.ts
Labels: enhancement

#57 Conductor to use Swiper JS
  apps/journeys/pages/[journeyId].tsx
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/JourneyProgress/JourneyProgress.tsx
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.tsx
  apps/journeys/src/components/blocks/Video/Video.tsx
  package-lock.json
  package.json
Labels: enhancement

#63 change signup to signUp
  apps/api-gateway/schema.graphql
  apps/api-journeys/codegen.yml
  apps/api-journeys/prisma/migrations/20210930223731_change_signup_to_sign_up/migration.sql
  apps/api-journeys/prisma/schema.prisma
  apps/api-journeys/prisma/seed.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/modules/block/__generated__/types.ts
  apps/api-journeys/src/modules/block/index.spec.ts
  apps/api-journeys/src/modules/block/index.ts
  apps/api-journeys/src/modules/response/__generated__/types.ts
  apps/api-journeys/src/modules/response/index.spec.ts
  apps/api-journeys/src/modules/response/index.ts
  apps/journeys/__generated__/GetJourney.ts
Labels: bug, backend
