Repository JesusFilm/core, pull requests merged in 2021-10, with the labels that each got.

#42 Image
  .storybook/preview.js
  apps/api-gateway/schema.graphql
  apps/api-journeys/codegen.yml
  apps/api-journeys/prisma/migrations/20210928032549_add_image_block/migration.sql
  apps/api-journeys/prisma/migrations/20210930235324_nx_prisma/migration.sql
  apps/api-journeys/prisma/schema.prisma
  apps/api-journeys/prisma/seed.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/modules/block/__generated__/types.ts
  apps/api-journeys/src/modules/block/index.spec.ts
  apps/api-journeys/src/modules/block/index.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/ImageFields.ts
  apps/journeys/next.config.js
  apps/journeys/pages/[journeyId].tsx
  apps/journeys/src/components/BlockRenderer/BlockRenderer.spec.tsx
  apps/journeys/src/components/BlockRenderer/BlockRenderer.tsx
  apps/journeys/src/components/blocks/Card/Card.spec.tsx
  apps/journeys/src/components/blocks/Card/Card.stories.tsx
  apps/journeys/src/components/blocks/Card/Card.tsx
  apps/journeys/src/components/blocks/Image/Image.spec.tsx
  apps/journeys/src/components/blocks/Image/Image.stories.tsx
  apps/journeys/src/components/blocks/Image/Image.tsx
  apps/journeys/src/components/blocks/Image/imageFields.ts
  apps/journeys/src/components/blocks/Image/index.ts
  apps/journeys/src/components/blocks/index.ts
  libs/shared/ui/src/libs/themes/base/tokens/components.ts
  package-lock.json
  package.json
Labels: component, needs ui review

#31 Button
  apps/api-journeys/prisma/seed.ts
  apps/journeys/__generated__/ActionFields.ts
  apps/journeys/__generated__/ButtonFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/pages/[journeyId].tsx
  apps/journeys/src/components/BlockRenderer/BlockRenderer.spec.tsx
  apps/journeys/src/components/BlockRenderer/BlockRenderer.tsx
  apps/journeys/src/components/Icon/Icon.spec.tsx
  apps/journeys/src/components/Icon/Icon.stories.tsx
  apps/journeys/src/components/Icon/Icon.tsx
  apps/journeys/src/components/Icon/index.ts
  apps/journeys/src/components/blocks/Button/Button.spec.tsx
  apps/journeys/src/components/blocks/Button/Button.stories.tsx
  apps/journeys/src/components/blocks/Button/Button.tsx
  apps/journeys/src/components/blocks/Button/buttonFields.ts
  apps/journeys/src/components/blocks/Button/index.ts
  apps/journeys/src/components/blocks/Card/Card.stories.tsx
  apps/journeys/src/components/blocks/RadioOption/RadioOption.tsx
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.stories.tsx
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.tsx
  apps/journeys/src/components/blocks/index.ts
  apps/journeys/src/libs/action/actionFields.ts
  apps/journeys/src/libs/action/handleAction.ts
  apps/journeys/src/libs/action/index.ts
  apps/journeys/src/libs/client/cache/blocks.ts
  libs/shared/ui/README.md
  libs/shared/ui/__generated__/globalTypes.ts
  libs/shared/ui/src/libs/themes/base/theme.ts
  libs/shared/ui/src/libs/themes/base/tokens/colors.ts
  libs/shared/ui/src/libs/themes/base/tokens/components.ts
  libs/shared/ui/src/libs/themes/base/tokens/spacing.ts
  package-lock.json
Labels: component

#65 move fields from journeyId page to file in blocks
  apps/journeys/__generated__/CardFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/RadioOptionFields.ts
  apps/journeys/__generated__/RadioQuestionFields.ts
  apps/journeys/__generated__/StepFields.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/journeys/pages/[journeyId].tsx
  apps/journeys/src/components/blocks/Card/cardFields.ts
  apps/journeys/src/components/blocks/Card/index.ts
  apps/journeys/src/components/blocks/RadioOption/index.ts
  apps/journeys/src/components/blocks/RadioOption/radioOptionFields.ts
  apps/journeys/src/components/blocks/RadioQuestion/index.ts
  apps/journeys/src/components/blocks/RadioQuestion/radioQuestionFields.ts
  apps/journeys/src/components/blocks/Step/index.ts
  apps/journeys/src/components/blocks/Step/stepFields.ts
  apps/journeys/src/components/blocks/Video/index.ts
  apps/journeys/src/components/blocks/Video/videoFields.ts
  apps/journeys/src/components/blocks/index.ts
Labels: enhancement

#66 provide uuid as a di prop for RadioQuestion
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.spec.tsx
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.stories.tsx
  apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.tsx
Labels: enhancement

#36 SignUp
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/SignUpFields.ts
  apps/journeys/__generated__/SignUpResponseCreate.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/pages/[journeyId].tsx
  apps/journeys/src/components/BlockRenderer/BlockRenderer.spec.tsx
  apps/journeys/src/components/BlockRenderer/BlockRenderer.tsx
  apps/journeys/src/components/blocks/SignUp/SignUp.spec.tsx
  apps/journeys/src/components/blocks/SignUp/SignUp.stories.tsx
  apps/journeys/src/components/blocks/SignUp/SignUp.tsx
  apps/journeys/src/components/blocks/SignUp/TextField/TextField.spec.tsx
  apps/journeys/src/components/blocks/SignUp/TextField/TextField.stories.tsx
  apps/journeys/src/components/blocks/SignUp/TextField/TextField.tsx
  apps/journeys/src/components/blocks/SignUp/TextField/index.ts
  apps/journeys/src/components/blocks/SignUp/index.ts
  apps/journeys/src/components/blocks/SignUp/signUpFields.ts
  apps/journeys/src/components/blocks/index.ts
  libs/shared/ui/src/libs/themes/base/tokens/colors.ts
  libs/shared/ui/src/libs/themes/base/tokens/components.ts
  package-lock.json
  package.json
Labels: component

#69 Simplify Resolvers
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/modules/block/index.spec.ts
  apps/api-journeys/src/modules/block/index.ts
  apps/api-journeys/src/modules/response/index.spec.ts
  apps/api-journeys/src/modules/response/index.ts
Labels: enhancement

#98 add isActiveBlockOrDescendant function
  apps/journeys/src/libs/client/cache/blocks.spec.ts
  apps/journeys/src/libs/client/cache/blocks.ts
Labels: enhancement, frontend
