Repository JesusFilm/core, pull requests merged in 2021-11, with the labels that each got.

#96 Social media sharing
  apps/api-gateway/schema.graphql
  apps/api-journeys/codegen.yml
  apps/api-journeys/prisma/migrations/20211026000058_add_primary_image_block_to_journey/migration.sql
  apps/api-journeys/prisma/schema.prisma
  apps/api-journeys/prisma/seed.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/modules/block/block.ts
  apps/api-journeys/src/modules/button/button.spec.ts
  apps/api-journeys/src/modules/card/card.spec.ts
  apps/api-journeys/src/modules/image/__generated__/types.ts
  apps/api-journeys/src/modules/image/image.spec.ts
  apps/api-journeys/src/modules/image/image.ts
  apps/api-journeys/src/modules/journey/__generated__/types.ts
  apps/api-journeys/src/modules/journey/journey.spec.ts
  apps/api-journeys/src/modules/journey/journey.ts
  apps/api-journeys/src/modules/radioQuestion/radioQuestion.spec.ts
  apps/api-journeys/src/modules/signUp/signUp.spec.ts
  apps/api-journeys/src/modules/step/step.spec.ts
  apps/api-journeys/src/modules/typography/typography.spec.ts
  apps/api-journeys/src/modules/video/video.spec.ts
  apps/journeys-e2e/cypress.json
  apps/journeys-e2e/project.json
  apps/journeys-e2e/src/integration/[journeyId].spec.ts
  apps/journeys-e2e/src/integration/app.spec.ts
  apps/journeys-e2e/src/support/app.po.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/pages/[journeyId].tsx
  apps/journeys/project.json
  package-lock.json
  package.json
Labels: enhancement, backend, frontend

#91 Card update
  apps/journeys/__generated__/CardFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/ImageFields.ts
  apps/journeys/src/components/BlockRenderer/BlockRenderer.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/blocks/Card/Card.spec.tsx
  apps/journeys/src/components/blocks/Card/Card.stories.tsx
  apps/journeys/src/components/blocks/Card/Card.tsx
  apps/journeys/src/components/blocks/Card/ImageCover/ImageCover.tsx
  apps/journeys/src/components/blocks/Card/ImageCover/index.ts
  apps/journeys/src/components/blocks/Card/cardFields.ts
  apps/journeys/src/components/blocks/Card/index.ts
  apps/journeys/src/components/blocks/Image/Image.spec.tsx
  apps/journeys/src/components/blocks/Image/Image.stories.tsx
  apps/journeys/src/components/blocks/Image/Image.tsx
  apps/journeys/src/components/blocks/Image/imageFields.ts
  apps/journeys/src/components/blocks/Typography/Typography.stories.tsx
  apps/journeys/src/libs/storybook/containers.tsx
  libs/shared/ui/src/libs/storybook/decorators.tsx
Labels: enhancement, frontend

#101 navigate to journey action
  apps/journeys/src/components/blocks/Button/Button.spec.tsx
  apps/journeys/src/components/blocks/Button/Button.tsx
  apps/journeys/src/components/blocks/RadioOption/RadioOption.spec.tsx
  apps/journeys/src/components/blocks/RadioOption/RadioOption.tsx
  apps/journeys/src/components/blocks/SignUp/SignUp.spec.tsx
  apps/journeys/src/components/blocks/SignUp/SignUp.tsx
  apps/journeys/src/libs/action/handleAction.spec.ts
  apps/journeys/src/libs/action/handleAction.ts
Labels: enhancement, frontend

#102 Add slug to journey
  apps/api-gateway/schema.graphql
  apps/api-journeys/prisma/migrations/20211101211353_add_slug_to_journeys/migration.sql
  apps/api-journeys/prisma/schema.prisma
  apps/api-journeys/prisma/seed.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/modules/button/button.spec.ts
  apps/api-journeys/src/modules/card/card.spec.ts
  apps/api-journeys/src/modules/gridContainer/gridContainer.spec.ts
  apps/api-journeys/src/modules/gridItem/gridItem.spec.ts
  apps/api-journeys/src/modules/image/image.spec.ts
  apps/api-journeys/src/modules/journey/__generated__/types.ts
  apps/api-journeys/src/modules/journey/journey.spec.ts
  apps/api-journeys/src/modules/journey/journey.ts
  apps/api-journeys/src/modules/radioQuestion/radioQuestion.spec.ts
  apps/api-journeys/src/modules/signUp/signUp.spec.ts
  apps/api-journeys/src/modules/step/step.spec.ts
  apps/api-journeys/src/modules/typography/typography.spec.ts
  apps/api-journeys/src/modules/video/video.spec.ts
  apps/journeys-e2e/src/integration/[journeySlug].spec.ts
  apps/journeys/__generated__/GetJourneys.ts
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/pages/index.tsx
  package-lock.json
  package.json
Labels: backend, frontend

#106 Add journey to navigate to journey action
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/modules/journey/__generated__/types.ts
  apps/api-journeys/src/modules/journey/journey.spec.ts
  apps/api-journeys/src/modules/journey/journey.ts
  apps/journeys/__generated__/ActionFields.ts
  apps/journeys/__generated__/ButtonFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/RadioOptionFields.ts
  apps/journeys/__generated__/SignUpFields.ts
  apps/journeys/src/libs/action/actionFields.ts
  apps/journeys/src/libs/action/handleAction.spec.ts
  apps/journeys/src/libs/action/handleAction.ts
Labels: enhancement, backend, frontend

#105 change api-journey to journeys
  CONTRIBUTING.md
Labels: documentation

#107 handle slug not unique error
  apps/api-journeys/src/modules/journey/journey.spec.ts
  apps/api-journeys/src/modules/journey/journey.ts
Labels: bug

#90 Video Player Extensions
  apps/api-gateway/schema.graphql
  apps/api-journeys/codegen.yml
  apps/api-journeys/prisma/migrations/20211102025942_add_video_trigger_block_to_block/migration.sql
  apps/api-journeys/prisma/schema.prisma
  apps/api-journeys/prisma/seed.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/application/application.ts
  apps/api-journeys/src/modules/index.ts
  apps/api-journeys/src/modules/video/__generated__/types.ts
  apps/api-journeys/src/modules/video/video.spec.ts
  apps/api-journeys/src/modules/video/video.ts
  apps/api-journeys/src/modules/videoTrigger/__generated__/types.ts
  apps/api-journeys/src/modules/videoTrigger/index.ts
  apps/api-journeys/src/modules/videoTrigger/videoTrigger.spec.ts
  apps/api-journeys/src/modules/videoTrigger/videoTrigger.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/journeys/__generated__/VideoResponseCreate.ts
  apps/journeys/__generated__/VideoTriggerFields.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/src/components/BlockRenderer/BlockRenderer.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/journeys/src/components/Conductor/data.ts
  apps/journeys/src/components/blocks/Video/Video.spec.tsx
  apps/journeys/src/components/blocks/Video/Video.stories.tsx
  apps/journeys/src/components/blocks/Video/Video.tsx
  apps/journeys/src/components/blocks/Video/VideoTrigger/VideoTrigger.tsx
  apps/journeys/src/components/blocks/Video/VideoTrigger/index.ts
  apps/journeys/src/components/blocks/Video/VideoTrigger/videoTriggerFields.ts
  apps/journeys/src/components/blocks/Video/index.ts
  apps/journeys/src/components/blocks/Video/videoFields.ts
  apps/journeys/src/components/blocks/index.ts
Labels: enhancement, backend, frontend

#109 Add posterBlockId to VideoBlock
  apps/api-gateway/schema.graphql
  apps/api-journeys/prisma/seed.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/modules/video/__generated__/types.ts
  apps/api-journeys/src/modules/video/video.spec.ts
  apps/api-journeys/src/modules/video/video.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/journeys/src/components/BlockRenderer/BlockRenderer.spec.tsx
  apps/journeys/src/components/Conductor/data.ts
  apps/journeys/src/components/blocks/Video/Video.spec.tsx
  apps/journeys/src/components/blocks/Video/Video.stories.tsx
  apps/journeys/src/components/blocks/Video/Video.tsx
  apps/journeys/src/components/blocks/Video/videoFields.ts
Labels: frontend

#111 use arc.gt urls on frontend
  apps/api-journeys/src/modules/video/video.spec.ts
  apps/api-journeys/src/modules/video/video.ts
  apps/journeys/src/components/BlockRenderer/BlockRenderer.spec.tsx
  apps/journeys/src/components/Conductor/data.ts
  apps/journeys/src/components/blocks/Video/Video.spec.tsx
  apps/journeys/src/components/blocks/Video/Video.stories.tsx
  apps/journeys/src/components/blocks/Video/Video.tsx
Labels: backend, frontend

#110 Video background
  apps/journeys/src/components/blocks/Card/Card.spec.tsx
  apps/journeys/src/components/blocks/Card/Card.stories.tsx
  apps/journeys/src/components/blocks/Card/Card.tsx
  apps/journeys/src/components/blocks/Card/Cover/Cover.tsx
  apps/journeys/src/components/blocks/Card/Cover/index.ts
  apps/journeys/src/components/blocks/Card/ImageCover/index.ts
  apps/journeys/src/components/blocks/Card/index.ts
Labels: enhancement, frontend

#113 handle start at on card video cover
  apps/journeys/src/components/blocks/Card/Cover/Cover.tsx
  apps/journeys/src/components/blocks/Video/Video.tsx
Labels: bug, frontend

#95 First Journey:NUA
  apps/api-journeys/prisma/factories/index.ts
  apps/api-journeys/prisma/factories/nua1.ts
  apps/api-journeys/prisma/factories/nua2.ts
  apps/api-journeys/prisma/factories/nua9.ts
  apps/api-journeys/prisma/factories/nuaEp8.ts
  apps/api-journeys/prisma/seed.ts
Labels: enhancement, backend

#116 Implement new icons introduced in NUA
  apps/api-gateway/schema.graphql
  apps/api-journeys/prisma/factories/nua1.ts
  apps/api-journeys/prisma/factories/nua2.ts
  apps/api-journeys/prisma/factories/nua9.ts
  apps/api-journeys/prisma/factories/nuaEp8.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/modules/button/button.spec.ts
  apps/api-journeys/src/modules/icon/__generated__/types.ts
  apps/api-journeys/src/modules/icon/icon.ts
  apps/api-journeys/src/modules/signUp/signUp.spec.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/src/components/Conductor/data.ts
  apps/journeys/src/components/Icon/Icon.spec.tsx
  apps/journeys/src/components/Icon/Icon.stories.tsx
  apps/journeys/src/components/Icon/Icon.tsx
  apps/journeys/src/components/blocks/Button/Button.spec.tsx
  apps/journeys/src/components/blocks/Button/Button.stories.tsx
  apps/journeys/src/components/blocks/Card/Card.stories.tsx
  apps/journeys/src/components/blocks/GridContainer/GridContainer.stories.tsx
  apps/journeys/src/components/blocks/GridItem/GridItem.stories.tsx
  apps/journeys/src/components/blocks/SignUp/SignUp.stories.tsx
Labels: enhancement

#112 update typography
  apps/journeys/pages/_document.tsx
  apps/journeys/src/components/blocks/Typography/Typography.spec.tsx
  apps/journeys/src/components/blocks/Typography/Typography.stories.tsx
  apps/journeys/src/components/blocks/Typography/Typography.tsx
  apps/journeys/src/components/blocks/Typography/index.ts
  libs/shared/ui/src/libs/themes/base/tokens/typography.ts
Labels: bug, frontend

#118 Render by step
  apps/journeys-e2e/cypress.json
  apps/journeys-e2e/src/integration/[journeySlug].spec.ts
  apps/journeys-e2e/src/integration/[journeySlug]/fact-or-fiction.spec.ts
  apps/journeys-e2e/src/integration/[journeySlug]/what-about-the-resurrection.spec.ts
  apps/journeys-e2e/src/integration/app.spec.ts
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/blocks/Video/Video.tsx
  apps/journeys/src/components/blocks/Video/VideoTrigger/VideoTrigger.tsx
  apps/journeys/src/libs/client/cache/blocks.ts
Labels: frontend

#130 journeys UI exports
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/VideoTrigger/VideoTrigger.tsx
  libs/journeys/ui/src/components/Video/VideoTrigger/index.ts
  libs/journeys/ui/src/components/Video/index.ts
  libs/journeys/ui/src/components/index.ts
  libs/journeys/ui/src/index.ts
  libs/journeys/ui/src/libs/index.ts
  libs/journeys/ui/src/libs/transformer/index.ts
  libs/journeys/ui/src/libs/transformer/transformer.spec.ts
  libs/journeys/ui/src/libs/transformer/transformer.ts
Labels: frontend, journeys-ui

#121 Add publishedAt and createdAt props on Journey model
  apps/api-gateway/schema.graphql
  apps/api-journeys/prisma/factories/nua1.ts
  apps/api-journeys/prisma/factories/nua2.ts
  apps/api-journeys/prisma/factories/nua9.ts
  apps/api-journeys/prisma/factories/nuaEp8.ts
  apps/api-journeys/prisma/migrations/20211116003138_add_created_and_published_date_to_journey/migration.sql
  apps/api-journeys/prisma/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/modules/button/button.spec.ts
  apps/api-journeys/src/modules/card/card.spec.ts
  apps/api-journeys/src/modules/dateTime/__generated__/types.ts
  apps/api-journeys/src/modules/dateTime/dateTime.spec.ts
  apps/api-journeys/src/modules/dateTime/dateTime.ts
  apps/api-journeys/src/modules/dateTime/index.ts
  apps/api-journeys/src/modules/gridContainer/gridContainer.spec.ts
  apps/api-journeys/src/modules/gridItem/gridItem.spec.ts
  apps/api-journeys/src/modules/image/image.spec.ts
  apps/api-journeys/src/modules/index.ts
  apps/api-journeys/src/modules/journey/__generated__/types.ts
  apps/api-journeys/src/modules/journey/journey.spec.ts
  apps/api-journeys/src/modules/journey/journey.ts
  apps/api-journeys/src/modules/radioQuestion/radioQuestion.spec.ts
  apps/api-journeys/src/modules/signUp/signUp.spec.ts
  apps/api-journeys/src/modules/step/step.spec.ts
  apps/api-journeys/src/modules/typography/typography.spec.ts
  apps/api-journeys/src/modules/video/video.spec.ts
  apps/api-journeys/src/modules/videoTrigger/videoTrigger.spec.ts
  apps/journeys/__generated__/GetJourney.ts
Labels: enhancement, backend

#131 use block fields
  libs/journeys/ui/src/components/Button/__generated__/ButtonFields.ts
  libs/journeys/ui/src/components/Button/buttonFields.ts
  libs/journeys/ui/src/components/Button/index.ts
  libs/journeys/ui/src/components/Card/__generated__/CardFields.ts
  libs/journeys/ui/src/components/Card/index.ts
  libs/journeys/ui/src/components/GridContainer/GridItem/index.ts
  libs/journeys/ui/src/components/GridContainer/__generated__/GridContainerFields.ts
  libs/journeys/ui/src/components/GridContainer/index.ts
  libs/journeys/ui/src/components/Image/index.ts
  libs/journeys/ui/src/components/RadioQuestion/RadioOption/index.ts
  libs/journeys/ui/src/components/RadioQuestion/RadioOption/radioOptionFields.ts
  libs/journeys/ui/src/components/RadioQuestion/__generated__/RadioQuestionResponseCreate.ts
  libs/journeys/ui/src/components/RadioQuestion/index.ts
  libs/journeys/ui/src/components/SignUp/__generated__/SignUpFields.ts
  libs/journeys/ui/src/components/SignUp/__generated__/SignUpResponseCreate.ts
  libs/journeys/ui/src/components/SignUp/index.ts
  libs/journeys/ui/src/components/SignUp/signUpFields.ts
  libs/journeys/ui/src/components/Step/index.ts
  libs/journeys/ui/src/components/Typography/__generated__/TypographyFields.ts
  libs/journeys/ui/src/components/Typography/index.ts
  libs/journeys/ui/src/components/Video/VideoTrigger/index.ts
  libs/journeys/ui/src/components/Video/VideoTrigger/videoTriggerFields.ts
  libs/journeys/ui/src/components/Video/__generated__/VideoResponseCreate.ts
  libs/journeys/ui/src/components/Video/index.ts
  libs/journeys/ui/src/components/index.ts
  libs/journeys/ui/src/index.ts
  libs/journeys/ui/src/libs/action/index.ts
  libs/journeys/ui/src/libs/index.ts
  libs/journeys/ui/src/libs/transformer/__generated__/BlockFields.ts
  libs/journeys/ui/src/libs/transformer/__generated__/GetJourney.ts
  libs/journeys/ui/src/libs/transformer/blockFields.ts
  libs/journeys/ui/src/libs/transformer/index.ts
  libs/journeys/ui/src/libs/transformer/journeyFields.ts
  libs/journeys/ui/src/libs/transformer/transformer.ts
Labels: bug, journeys-ui

#133 Add instruction for journeys-admin set up to CONTRIBUTING
  CONTRIBUTING.md
Labels: documentation

#138 C4/ Make JourneyStatus required on Journeys
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/types.ts
  apps/api-journeys/src/modules/journey/journey.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys/__generated__/GetJourneys.ts
  apps/journeys/__generated__/globalTypes.ts
Labels: backend

#139 add storybook emotion alias override
  .storybook/main.js
  libs/shared/ui/src/components/ThemeProvider/ThemeProvider.tsx
Labels: bug, frontend
