Repository JesusFilm/core, pull requests merged in 2022-10, with the labels that each got.

#907 feat: selecting video property flow
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/SourceEmpty/SourceEmpty.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/SourceEmpty/index.ts
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/SourceFromLocal/SourceFromLocal.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/SourceFromLocal/index.ts
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/SourceFromYouTube/SourceFromYouTube.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/SourceFromYouTube/index.ts
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.tsx
Labels: effort: 2, priority: now, type: feat

#930 fix: remove text response block flag
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/BlocksTab.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/BlocksTab.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/BlocksTab.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
Labels: effort: 2, type: fix, priority: soon

#915 fix: access templates
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/ContactSupport/ContactSupport.spec.tsx
  apps/journeys-admin/src/components/ContactSupport/ContactSupport.stories.tsx
  apps/journeys-admin/src/components/ContactSupport/ContactSupport.tsx
  apps/journeys-admin/src/components/ContactSupport/index.ts
  apps/journeys-admin/src/components/JourneyList/JourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
  apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.spec.tsx
  apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.stories.tsx
  apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.tsx
  apps/journeys-admin/src/components/TemplateList/TemplatesList.spec.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: 2day, type: fix, effort: 3

#926 fix: youtube video clean up
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.stories.tsx
  apps/journeys/src/libs/testData/storyData.ts
  libs/journeys/ui/src/components/Card/Card.stories.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: type: fix, priority: now, effort: 1

#932 fix: video update mutation
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Labels: type: fix, priority: now, effort: 1

#935 fix: high res youtube image
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Labels: effort: 2, type: fix, priority: now

#927 fix: changing video providers
  apps/journeys-admin/next.config.js
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.spec.tsx
  apps/journeys/next.config.js
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: effort: 2, type: fix, priority: now

#938 fix: image covering video when playing
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: type: fix, priority: now, effort: 1

#937 fix: card delete causing crash
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.tsx
Labels: type: fix, priority: soon, effort: 1

#916 feat: template analytics
  apps/journeys-admin/src/components/JourneyView/JourneyViewFab/JourneyViewFab.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyViewFab/JourneyViewFab.tsx
Labels: effort: 3, priority: now, type: feat

#933 test: update journey-ui vr
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attribute/Attribute.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextField/TextField.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextField/TextField.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextField/TextField.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextField/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewImageButton/NewImageButton.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewRadioQuestionButton/NewRadioQuestion.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewSignUpButton/NewSignUpButton.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewTextResponseButton/NewTextResponseButton.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewTypographyButton/NewTypographyButton.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewVideoButton/NewVideoButton.stories.tsx
  libs/journeys/ui/src/components/Button/Button.stories.tsx
  libs/journeys/ui/src/components/Card/Card.stories.tsx
  libs/journeys/ui/src/components/GridContainer/GridContainer.stories.tsx
  libs/journeys/ui/src/components/GridItem/GridItem.stories.tsx
  libs/journeys/ui/src/components/Icon/Icon.stories.tsx
  libs/journeys/ui/src/components/Image/Image.stories.tsx
  libs/journeys/ui/src/components/RadioOption/RadioOption.stories.tsx
  libs/journeys/ui/src/components/RadioOption/RadioOption.tsx
  libs/journeys/ui/src/components/RadioOption/index.ts
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.stories.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.stories.tsx
  libs/journeys/ui/src/components/TextField/TextField.spec.tsx
  libs/journeys/ui/src/components/TextField/TextField.stories.tsx
  libs/journeys/ui/src/components/TextField/TextField.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.stories.tsx
  libs/journeys/ui/src/components/Typography/Typography.stories.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
Labels: type: test, effort: 3, priority: soon

#944 feat: rtl language check
  libs/shared/ui/src/libs/rtl/index.ts
  libs/shared/ui/src/libs/rtl/rtl.spec.tsx
  libs/shared/ui/src/libs/rtl/rtl.ts
Labels: priority: 2day, effort: 2, type: feat

#945 fix: add journey field locales
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/GetTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/Language/Language.spec.tsx
  apps/journeys-admin/src/components/JourneyView/data.ts
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/JourneyProvider.spec.tsx
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/journeyFields.tsx
Labels: type: fix, priority: soon, effort: 1

#946 fix: add journey rtl check
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
  libs/journeys/ui/src/libs/rtl/index.ts
  libs/journeys/ui/src/libs/rtl/rtl.spec.tsx
  libs/journeys/ui/src/libs/rtl/rtl.ts
Labels: priority: 2day, effort: 2, type: fix

#949 feat: add rtl to core from material ui
  apps/journeys/pages/_app.tsx
  apps/journeys/pages/_document.tsx
  build-storybook.log
  libs/shared/ui/src/libs/createEmotionCache/createEmotionCache.ts
  package-lock.json
  package.json
Labels: effort: 3, priority: soon, type: feat

#942 fix: label cannot be set to space character
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/Label/Label.tsx
Labels: priority: 2day, type: fix, effort: 1

#957 refactor: rtl function naming
  libs/journeys/ui/src/libs/rtl/index.ts
  libs/journeys/ui/src/libs/rtl/rtl.spec.tsx
  libs/journeys/ui/src/libs/rtl/rtl.ts
  libs/shared/ui/src/libs/rtl/index.ts
  libs/shared/ui/src/libs/rtl/rtl.spec.tsx
  libs/shared/ui/src/libs/rtl/rtl.ts
Labels: priority: 2day, effort: 1, type: refactor

#955 fix: add rtl to stories
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/pages/_app.tsx
  apps/journeys/pages/_document.tsx
  libs/shared/ui/src/components/ThemeDecorator/ThemeDecorator.tsx
  libs/shared/ui/src/components/ThemeProvider/ThemeProvider.tsx
  libs/shared/ui/src/libs/sharedUiConfig/sharedUiConfig.tsx
  libs/shared/ui/src/libs/themes/base/theme.stories.tsx
Labels: type: fix, effort: 3, priority: now

#958 fix: add language to NavigateToJourneyAction
  apps/journeys-admin/__generated__/ActionFields.ts
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/ButtonBlockCreate.ts
  apps/journeys-admin/__generated__/ButtonFields.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockCreate.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockUpdate.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/GetTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/RadioOptionFields.ts
  apps/journeys-admin/__generated__/RadioQuestionBlockCreate.ts
  apps/journeys-admin/__generated__/SignUpBlockCreate.ts
  apps/journeys-admin/__generated__/SignUpFields.ts
  apps/journeys-admin/__generated__/TextResponseBlockCreate.ts
  apps/journeys-admin/__generated__/TextResponseFields.ts
  apps/journeys-admin/__generated__/VideoBlockCreate.ts
  apps/journeys-admin/__generated__/VideoBlockUpdate.ts
  apps/journeys-admin/__generated__/VideoFields.ts
  apps/journeys-admin/__generated__/VideoTriggerFields.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/data.ts
  apps/journeys/__generated__/ActionFields.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/ButtonFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/RadioOptionFields.ts
  apps/journeys/__generated__/SignUpFields.ts
  apps/journeys/__generated__/TextResponseFields.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/journeys/__generated__/VideoTriggerFields.ts
  apps/watch-admin/__generated__/ActionFields.ts
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/ButtonFields.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/RadioOptionFields.ts
  apps/watch-admin/__generated__/SignUpFields.ts
  apps/watch-admin/__generated__/TextResponseFields.ts
  apps/watch-admin/__generated__/VideoFields.ts
  apps/watch-admin/__generated__/VideoTriggerFields.ts
  apps/watch/__generated__/ActionFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/ButtonFields.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/RadioOptionFields.ts
  apps/watch/__generated__/SignUpFields.ts
  apps/watch/__generated__/TextResponseFields.ts
  apps/watch/__generated__/VideoFields.ts
  apps/watch/__generated__/VideoTriggerFields.ts
  libs/journeys/ui/src/components/Button/__generated__/ButtonFields.ts
  libs/journeys/ui/src/components/RadioOption/__generated__/RadioOptionFields.ts
  libs/journeys/ui/src/components/SignUp/__generated__/SignUpFields.ts
  libs/journeys/ui/src/components/TextResponse/__generated__/TextResponseFields.ts
  libs/journeys/ui/src/components/Video/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/VideoTrigger/__generated__/VideoTriggerFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/action/__generated__/ActionFields.ts
  libs/journeys/ui/src/libs/action/action.spec.ts
  libs/journeys/ui/src/libs/action/actionFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
Labels: effort: 2, type: fix, priority: now

#952 feat: add timestamp to events
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/button/button.graphql
  apps/api-journeys/src/app/modules/event/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/button/button.resolver.ts
  apps/api-journeys/src/app/modules/event/event.graphql
  apps/api-journeys/src/app/modules/event/journey/journey.graphql
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.graphql
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.ts
  apps/api-journeys/src/app/modules/event/signUp/signUp.graphql
  apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.ts
  apps/api-journeys/src/app/modules/event/step/step.graphql
  apps/api-journeys/src/app/modules/event/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/step/step.resolver.ts
  apps/api-journeys/src/app/modules/event/template/template.graphql
  apps/api-journeys/src/app/modules/event/template/template.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/template/template.resolver.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.graphql
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.ts
  apps/api-journeys/src/app/modules/event/video/video.graphql
  apps/api-journeys/src/app/modules/event/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/video/video.resolver.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#954 fix: conductor rtl
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  build-storybook.log
  libs/journeys/ui/src/libs/action/action.spec.ts
  libs/journeys/ui/src/libs/action/action.ts
  libs/journeys/ui/src/libs/rtl/rtl.ts
Labels: type: fix, effort: 3, priority: soon

#961 fix: storybook emotion cache
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/pages/_document.tsx
  apps/journeys/pages/_app.tsx
  apps/journeys/pages/_document.tsx
  apps/watch-admin/pages/_app.tsx
  apps/watch-admin/pages/_document.tsx
  apps/watch/pages/_app.tsx
  apps/watch/pages/_document.tsx
  libs/shared/ui/src/components/ThemeDecorator/ThemeDecorator.tsx
  libs/shared/ui/src/libs/createEmotionCache/createEmotionCache.ts
Labels: effort: 2, type: fix, priority: now

#959 feat: add infracost config
  infracost.yaml
Labels: priority: now, type: feat, effort: 1

#967 fix: launch darkly to run identify every time
  libs/shared/ui/src/libs/getLaunchDarklyClient/getLaunchDarklyClient.ts
Labels: type: fix, priority: now, effort: 1

#965 feat: multichoice rtl
  libs/journeys/ui/src/components/RadioOption/RadioOption.stories.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#966 feat: textfield rtl
  libs/journeys/ui/src/components/SignUp/SignUp.stories.tsx
  libs/journeys/ui/src/components/TextField/TextField.stories.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#968 fix: card rtl
  libs/journeys/ui/src/components/Card/Card.stories.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContentOverlay/ContentOverlay.tsx
Labels: priority: 2day, effort: 2, type: fix

#981 fix: youtube videos not playing
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: type: fix, effort: 3, priority: now

#974 fix: add new icons
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/icon/icon.graphql
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/Icon/Icon.tsx
Labels: type: fix, priority: soon, effort: 1

#975 fix: add new icons for rtl use
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Icon/Icon.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Icon/Icon.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponse.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.stories.tsx
  libs/journeys/ui/src/components/Icon/Icon.stories.tsx
  libs/journeys/ui/src/components/Icon/Icon.tsx
Labels: type: fix, priority: soon, effort: 1

#985 refactor: themes to get theme
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ColorDisplayIcon/ColorDisplayIcon.spec.tsx
  apps/watch/src/components/ThemeProvider/ThemeProvider.stories.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/shared/ui/src/components/ThemeDecorator/ThemeDecorator.tsx
  libs/shared/ui/src/components/ThemeProvider/ThemeProvider.spec.tsx
  libs/shared/ui/src/components/ThemeProvider/ThemeProvider.tsx
  libs/shared/ui/src/libs/themes/base/theme.stories.tsx
  libs/shared/ui/src/libs/themes/index.ts
Labels: priority: now, effort: 1, type: refactor

#971 fix: typography rtl
  .storybook/preview-head.html
  apps/journeys-admin/pages/_document.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateAction/NavigateAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateAction/NavigateAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToBlockAction/NavigateToBlockAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToBlockAction/NavigateToBlockAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/NextCard.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/pages/_app.tsx
  apps/journeys/pages/_document.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  libs/journeys/ui/src/components/Button/Button.stories.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Icon/Icon.tsx
  libs/journeys/ui/src/components/TextField/TextField.stories.tsx
  libs/journeys/ui/src/components/Typography/Typography.stories.tsx
  libs/journeys/ui/src/libs/action/action.ts
  libs/journeys/ui/src/libs/rtl/rtl.spec.tsx
  libs/journeys/ui/src/libs/rtl/rtl.ts
  libs/shared/ui/src/components/ThemeDecorator/ThemeDecorator.tsx
  libs/shared/ui/src/components/ThemeProvider/ThemeProvider.spec.tsx
  libs/shared/ui/src/components/ThemeProvider/ThemeProvider.tsx
  libs/shared/ui/src/libs/sharedUiConfig/sharedUiConfig.tsx
  libs/shared/ui/src/libs/themes/base/theme.ts
  libs/shared/ui/src/libs/themes/base/tokens/typography.ts
  libs/shared/ui/src/libs/themes/index.ts
Labels: type: fix, effort: 3, priority: soon

#987 fix: update urdu typography
  .storybook/preview-head.html
  apps/journeys/pages/_document.tsx
  libs/shared/ui/src/libs/themes/base/tokens/typography.ts
Labels: type: fix, priority: now, effort: 1

#984 feat: add visitors to api-journeys
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/seed.ts
  apps/api-journeys/db/seeds/jfpTeam.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/member/member.module.ts
  apps/api-journeys/src/app/modules/member/member.service.spec.ts
  apps/api-journeys/src/app/modules/member/member.service.ts
  apps/api-journeys/src/app/modules/team/team.module.ts
  apps/api-journeys/src/app/modules/team/team.service.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.ts
  apps/api-journeys/src/app/modules/visitor/visitor.graphql
  apps/api-journeys/src/app/modules/visitor/visitor.module.ts
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.ts
  apps/api-journeys/src/app/modules/visitor/visitor.service.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.service.ts
  libs/nest/database/src/lib/BaseService.ts
  package-lock.json
  package.json
Labels: effort: 8, priority: now, type: feat, on stage

#986 feat: add visitor query and visitor update mutation to api-journeys
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/visitor/visitor.graphql
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.ts
Labels: effort: 3, priority: now, type: feat, on stage

#991 fix: set key on seed for visitors and members
  apps/api-journeys/db/seeds/jfpTeam.ts
Labels: type: fix, priority: now, effort: 1

#998 fix: canvas styling
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Cards/Cards.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/NextCard.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/FramePortal/FramePortal.spec.tsx
  apps/journeys-admin/src/components/FramePortal/FramePortal.stories.tsx
  apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/EmbedJourneyDialog/EmbedCardPreview/EmbedCardPreview.tsx
Labels: type: fix, effort: 3, priority: now

#990 feat: deprecate events fields
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/button/button.graphql
  apps/api-journeys/src/app/modules/event/event.graphql
  apps/api-journeys/src/app/modules/event/journey/journey.graphql
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.graphql
  apps/api-journeys/src/app/modules/event/signUp/signUp.graphql
  apps/api-journeys/src/app/modules/event/step/step.graphql
  apps/api-journeys/src/app/modules/event/template/template.graphql
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.graphql
  apps/api-journeys/src/app/modules/event/video/video.graphql
Labels: effort: 2, priority: now, type: feat, on stage

#947 feat: create visitor report page structure
  apps/journeys-admin/next.config.js
  apps/journeys-admin/pages/reports/journeys.tsx
  apps/journeys-admin/pages/reports/visitors.tsx
  apps/journeys-admin/pages/reports/visitors/[visitorId].tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: priority: soon, type: feat, effort: 1

#988 feat: stage deployment process docs
  apps/docs/docs/04-engineering-practices/01-stage-deployment-process/index.md
  apps/docs/docs/04-engineering-practices/01-stage-deployment-process/stage-branch-merge-bot-attempting.png
  apps/docs/docs/04-engineering-practices/01-stage-deployment-process/stage-branch-merge-bot-conflict.png
  apps/docs/docs/04-engineering-practices/_category_.json
Labels: priority: now, type: feat, effort: 1

#999 feat: remove use of deprecated events fields
  apps/journeys-admin/__generated__/RadioQuestionSubmissionEventCreate.ts
  apps/journeys-admin/__generated__/SignUpSubmissionEventCreate.ts
  apps/journeys-admin/__generated__/TextResponseSubmissionEventCreate.ts
  apps/journeys-admin/__generated__/VideoProgressEventCreate.ts
  apps/journeys/__generated__/RadioQuestionSubmissionEventCreate.ts
  apps/journeys/__generated__/SignUpSubmissionEventCreate.ts
  apps/journeys/__generated__/TextResponseSubmissionEventCreate.ts
  apps/journeys/__generated__/VideoProgressEventCreate.ts
  apps/watch-admin/__generated__/RadioQuestionSubmissionEventCreate.ts
  apps/watch-admin/__generated__/SignUpSubmissionEventCreate.ts
  apps/watch-admin/__generated__/TextResponseSubmissionEventCreate.ts
  apps/watch-admin/__generated__/VideoProgressEventCreate.ts
  apps/watch/__generated__/RadioQuestionSubmissionEventCreate.ts
  apps/watch/__generated__/SignUpSubmissionEventCreate.ts
  apps/watch/__generated__/TextResponseSubmissionEventCreate.ts
  apps/watch/__generated__/VideoProgressEventCreate.ts
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.stories.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/RadioQuestion/__generated__/RadioQuestionSubmissionEventCreate.ts
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.stories.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/SignUp/__generated__/SignUpSubmissionEventCreate.ts
  libs/journeys/ui/src/components/TextResponse/TextResponse.spec.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.stories.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
  libs/journeys/ui/src/components/TextResponse/__generated__/TextResponseSubmissionEventCreate.ts
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.spec.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.tsx
  libs/journeys/ui/src/components/VideoEvents/__generated__/VideoProgressEventCreate.ts
Labels: effort: 2, priority: now, type: feat

#1000 feat: remove deprecated events fields
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/button/button.graphql
  apps/api-journeys/src/app/modules/event/event.graphql
  apps/api-journeys/src/app/modules/event/event.module.ts
  apps/api-journeys/src/app/modules/event/journey/journey.graphql
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.graphql
  apps/api-journeys/src/app/modules/event/signUp/signUp.graphql
  apps/api-journeys/src/app/modules/event/step/step.graphql
  apps/api-journeys/src/app/modules/event/template/template.graphql
  apps/api-journeys/src/app/modules/event/template/template.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/template/template.resolver.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.graphql
  apps/api-journeys/src/app/modules/event/video/video.graphql
Labels: effort: 3, priority: now, type: feat

#1005 refactor: move dialog to shared-ui
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DeleteJourneyDialog/DeleteJourneyDialog.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/RestoreJourneyDialog/RestoreJourneyDialog.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/TrashJourneyDialog/TrashJourneyDialog.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/SlugDialog/SlugDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/LanguageDialog/LanguageDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/TitleDescriptionDialog/TitleDescriptionDialog.tsx
  apps/journeys-admin/src/components/TemplateList/ActiveTemplates/ActiveTemplates.tsx
  apps/journeys-admin/src/components/TemplateList/ArchivedTemplates/ArchivedTemplates.tsx
  apps/journeys-admin/src/components/TemplateList/TrashedTemplates/TrashedTemplates.tsx
  libs/shared/ui/src/components/Dialog/Dialog.spec.tsx
  libs/shared/ui/src/components/Dialog/Dialog.stories.tsx
  libs/shared/ui/src/components/Dialog/Dialog.tsx
  libs/shared/ui/src/components/Dialog/index.ts
Labels: priority: 2day, effort: 1, type: refactor

#1003 fix: watch page wrapper
  apps/watch/pages/[...slug].tsx
  apps/watch/pages/countries/[...slug].tsx
  apps/watch/pages/countries/index.tsx
  apps/watch/pages/index.tsx
  apps/watch/pages/videos/[...tag].tsx
  apps/watch/src/components/Header/Header.spec.tsx
  apps/watch/src/components/Header/Header.stories.tsx
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Header/index.ts
  apps/watch/src/components/PageWrapper/PageWrapper.spec.tsx
  apps/watch/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/watch/src/components/PageWrapper/PageWrapper.tsx
Labels: effort: 2, type: fix, priority: soon

#1007 refactor: watch existing components
  apps/watch/__generated__/GetCountries.ts
  apps/watch/__generated__/GetCountry.ts
  apps/watch/pages/[...slug].tsx
  apps/watch/pages/countries/[...slug].tsx
  apps/watch/pages/countries/index.tsx
  apps/watch/pages/index.tsx
  apps/watch/src/components/Countries/Countries.tsx
  apps/watch/src/components/Countries/Map.tsx
  apps/watch/src/components/Video/VideoCard/VideoCard.tsx
  apps/watch/src/components/Video/index.ts
  apps/watch/src/components/Videos/VideoInfo/VideoInfo.tsx
  apps/watch/src/components/Videos/VideoList/List/VideoListList.spec.tsx
  apps/watch/src/components/Videos/VideoList/List/VideoListList.tsx
  apps/watch/src/components/Videos/VideoList/VideoList.tsx
  apps/watch/src/components/Videos/Videos.spec.tsx
  apps/watch/src/components/Videos/Videos.stories.tsx
  apps/watch/src/components/Videos/Videos.tsx
  apps/watch/src/components/Videos/VideosCarousel/VideosCarousel.tsx
  apps/watch/src/components/Videos/VideosGrid/VideosGrid.spec.tsx
  apps/watch/src/components/Videos/VideosGrid/VideosGrid.tsx
  apps/watch/src/components/Videos/index.ts
  apps/watch/src/components/Videos/testData.ts
  apps/watch/src/libs/countries/countries.graphql.ts
Labels: priority: 2day, effort: 2, type: refactor

#1004 fix: update watch theme
  .storybook/main.js
  .storybook/preview-head.html
  apps/journeys-admin/src/components/Editor/ControlPanel/ColorDisplayIcon/ColorDisplayIcon.spec.tsx
  apps/watch/pages/[...slug].tsx
  apps/watch/pages/_app.tsx
  apps/watch/pages/index.tsx
  apps/watch/pages/videos/[...tag].tsx
  apps/watch/src/components/Footer/Footer.tsx
  apps/watch/src/components/Header/Header.stories.tsx
  apps/watch/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/watch/src/components/ThemeProvider/ThemeProvider.stories.tsx
  apps/watch/src/components/ThemeProvider/ThemeProvider.tsx
  apps/watch/src/components/ThemeProvider/index.ts
  apps/watch/src/components/Video/VideoCard/VideoCard.tsx
  apps/watch/src/components/Videos/VideosGrid/VideosGrid.tsx
  apps/watch/src/libs/storybook/config.tsx
  apps/watch/src/libs/storybook/containers.tsx
  apps/watch/src/libs/storybook/index.ts
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/shared/ui/src/components/ThemeDecorator/ThemeDecorator.tsx
  libs/shared/ui/src/libs/sharedUiConfig/sharedUiConfig.tsx
  libs/shared/ui/src/libs/themes/index.ts
  libs/shared/ui/src/libs/themes/website/theme.ts
  libs/shared/ui/src/libs/themes/website/tokens/colors.stories.tsx
  libs/shared/ui/src/libs/themes/website/tokens/colors.ts
  libs/shared/ui/src/libs/themes/website/tokens/components.stories.tsx
  libs/shared/ui/src/libs/themes/website/tokens/components.ts
  libs/shared/ui/src/libs/themes/website/tokens/typography.stories.tsx
  libs/shared/ui/src/libs/themes/website/tokens/typography.ts
Labels: priority: 2day, effort: 5, type: fix
