Repository JesusFilm/core, pull requests merged in 2022-07, with the labels that each got.

#749 fix: change vr image in card preview
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateAction/NavigateAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToBlockAction/NavigateToBlockAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/data.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/data.ts
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/UserMenu.stories.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
Labels: type: fix, priority: soon, effort: 1

#721 feat: add archive delete chip to journey card
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/StatusChip/StatusChip.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/StatusChip/StatusChip.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/StatusChip/StatusChip.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/StatusChip/index.ts
  apps/journeys-admin/src/components/JourneyList/journeyListData.ts
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/JourneyDetails.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/JourneyDetails.tsx
  apps/journeys-admin/src/components/JourneyView/data.ts
Labels: effort: 5, priority: soon, type: feat

#745 fix: journey duplication title revision
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/journey/journey.service.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.service.ts
Labels: priority: 2day, effort: 2, type: fix, on stage

#750 fix: add css to head tag on ssr
  apps/journeys-admin/pages/_document.tsx
  apps/watch-admin/pages/_document.tsx
  apps/watch/pages/_document.tsx
Labels: type: fix, priority: now, effort: 1

#751 fix: add stage branch validation
  validate-branch-name.config.js
Labels: type: fix, priority: now, effort: 1, type: ci

#694 feat: block duplication ui
  apps/journeys-admin/__generated__/BlockDuplicate.ts
  apps/journeys-admin/__generated__/DuplicatedBlock.ts
  apps/journeys-admin/src/components/DuplicateBlock/DuplicateBlock.spec.tsx
  apps/journeys-admin/src/components/DuplicateBlock/DuplicateBlock.tsx
  apps/journeys-admin/src/components/DuplicateBlock/index.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx
Labels: priority: 2day, effort: 2, type: feat, on stage

#746 feat: add single full report
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/reports.tsx
  apps/journeys-admin/src/components/DynamicPowerBiReport/Report/Report.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
  libs/shared/ui/src/components/FlagsProvider/FlagsProvider.spec.tsx
Labels: effort: 3, priority: soon, type: feat

#739 fix: journey button to go to id instead of slug
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.spec.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.tsx
Labels: type: fix, priority: now, effort: 1, on stage

#752 fix: remove apollo client cache ssr
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/pages/_app.tsx
  apps/journeys/pages/index.tsx
  apps/journeys/project.json
  apps/journeys/src/libs/apolloClient/apolloClient.ts
  apps/journeys/src/libs/apolloClient/index.ts
Labels: type: fix, effort: 3, priority: now, on stage

#753 chore: use env for journeys url on journeys-admin
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.tsx
Labels: priority: now, effort: 1, type: chore, on stage

#754 fix: duplicate journey title, find difference between titles
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: priority: 2day, effort: 2, type: fix, on stage

#737 feat: add multiple summary report
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
  apps/journeys-admin/src/components/MultipleSummaryReport/MultipleSummaryReport.spec.tsx
  apps/journeys-admin/src/components/MultipleSummaryReport/MultipleSummaryReport.stories.tsx
  apps/journeys-admin/src/components/MultipleSummaryReport/MultipleSummaryReport.tsx
  apps/journeys-admin/src/components/MultipleSummaryReport/index.ts
Labels: effort: 3, priority: soon, type: feat

#744 feat: add single summary report
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
  libs/shared/ui/src/components/CopyTextField/CopyTextField.spec.tsx
  libs/shared/ui/src/components/CopyTextField/CopyTextField.tsx
Labels: effort: 2, priority: soon, type: feat, on stage

#730 feat: duplicate journeys ui
  apps/journeys-admin/__generated__/DuplicatedJourney.ts
  apps/journeys-admin/__generated__/JourneyDuplicate.ts
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem.tsx/DuplicateJourneyMenuItem.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem.tsx/DuplicateJourneyMenuItem.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem.tsx/Index.ts
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.tsx
Labels: priority: 2day, effort: 3, type: feat

#761 fix: add polyfill to storybook
  .storybook/main.js
  package-lock.json
  package.json
Labels: type: fix, priority: now, effort: 1

#765 fix: batch events broken by conflict resolution
  apps/journeys-admin/src/components/JourneyList/JourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.spec.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.stories.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.spec.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.stories.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/StatusTabPanel.spec.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/StatusTabPanel.stories.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/StatusTabPanel.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.spec.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.stories.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.tsx
Labels: type: fix, priority: now, effort: 1

#764 fix: firefox cardlist margin
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
Labels: type: fix, priority: soon, effort: 1

#719 fix: save inline edit block on outside click
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/useOnClickOutside/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/useOnClickOutside/useOnClickOutside.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/useOnClickOutside/useOnClickOutside.tsx
Labels: effort: 2, type: fix, priority: soon

#767 fix: video thumbnail
  apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.tsx
Labels: type: fix, priority: soon, effort: 1

#768 fix: selected step in editor context
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: effort: 2, type: fix, priority: soon

#770 fix: reorder typography properties
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
Labels: type: fix, priority: soon, effort: 1

#772 fix: card reselection on change
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: type: fix, priority: now, effort: 1

#771 fix: journey sort order
  apps/journeys-admin/src/components/JourneyList/JourneySort/utils/sortJourneys.spec.ts
  apps/journeys-admin/src/components/JourneyList/JourneySort/utils/sortJourneys.ts
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.spec.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.spec.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.spec.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.tsx
Labels: type: fix, priority: soon, effort: 1

#775 fix: link tests using env failing on development
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
Labels: effort: 2, type: fix, priority: soon

#773 fix: selected step from journey view
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: type: fix, effort: 3, priority: soon

#778 fix: unwanted report re renders
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/reports.tsx
  apps/journeys-admin/src/components/DynamicPowerBiReport/DyanmicPowerBiReport.spec.tsx
  apps/journeys-admin/src/components/DynamicPowerBiReport/DynamicPowerBiReport.tsx
  apps/journeys-admin/src/components/DynamicPowerBiReport/index.ts
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/StatusTabPanel.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/MultipleSummaryReport/MultipleSummaryReport.tsx
Labels: type: fix, priority: soon, effort: 1

#781 refactor: layout calculations from js to css
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/StatusTabPanel.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
Labels: type: fix, priority: soon, effort: 1

#782 fix: next card property title and remove action
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.tsx
Labels: effort: 2, type: fix, priority: soon

#776 fix: scrolls to the duplicated journey
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/utils/getDuplicated.spec.ts
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/utils/getDuplicatedJourney.ts
Labels: effort: 2, type: fix, priority: soon

#769 feat: replace video url with language
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockCreate.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockUpdate.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/VideoBlockCreate.ts
  apps/journeys-admin/__generated__/VideoBlockUpdate.ts
  apps/journeys-admin/__generated__/VideoFields.ts
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/VideoFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.stories.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.spec.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/journeys/ui/src/components/Video/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/Video/videoFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
Labels: priority: 2day, effort: 3, type: feat

#786 fix: breaking backend tests
  apps/api-journeys/src/app/modules/block/image/image.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
Labels: type: fix, effort: 3, priority: now

#785 feat: extend journey with template field
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
Labels: priority: soon, type: feat, effort: 1, on stage

#787 feat: add publisher role to user
  apps/api-gateway/schema.graphql
  apps/api-users/schema.graphql
  apps/api-users/src/app/__generated__/graphql.ts
  apps/api-users/src/app/modules/user/user.graphql
  apps/api-users/src/app/modules/user/user.resolver.spec.ts
Labels: priority: now, type: feat, effort: 1, on stage

#742 fix: card not rendering after drag
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
Labels: type: fix, effort: 3, priority: soon

#789 refactor: publisher role
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/seed.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/modules/userRole/userRole.graphql
  apps/api-journeys/src/app/modules/userRole/userRole.module.ts
  apps/api-journeys/src/app/modules/userRole/userRole.resolver.spec.ts
  apps/api-journeys/src/app/modules/userRole/userRole.resolver.ts
  apps/api-journeys/src/app/modules/userRole/userRole.service.spec.ts
  apps/api-journeys/src/app/modules/userRole/userRole.service.ts
  apps/api-users/schema.graphql
  apps/api-users/src/app/__generated__/graphql.ts
  apps/api-users/src/app/modules/user/user.graphql
  apps/api-users/src/app/modules/user/user.resolver.spec.ts
Labels: effort: 5, priority: soon, type: refactor, on stage

#791 feat: add templates page
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
Labels: priority: soon, type: feat, effort: 1

#795 refactor: template field
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
Labels: priority: now, effort: 1, type: refactor

#796 fix: make drafts previewable
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: type: fix, priority: soon, effort: 1

#799 feat: extend journey duplicate with template
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: priority: soon, type: feat, effort: 1
