Repository JesusFilm/core, pull requests merged in 2022-02, with the labels that each got.

#238 Add edit button to journey view
  apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  libs/shared/ui/src/components/CopyTextField/CopyTextField.tsx
Labels: bug

#244 Gateway Deployment fix
  .github/workflows/api-deploy.yml
  .github/workflows/api-gateway-worker.yml
Labels: bug, backend

#252 add ToggleButtonGroup component
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/ToggleButtonGroup/ToggleButtonGroup.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/ToggleButtonGroup/ToggleButtonGroup.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/ToggleButtonGroup/ToggleButtonGroup.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/ToggleButtonGroup/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Align/Align.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Align/Align.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Align/Align.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Color/Color.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Color/Color.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Color/Color.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Variant/Variant.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Variant/Variant.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Variant/Variant.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/StyledToggleButton/StyledToggleButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/StyledToggleButton/index.ts
Labels: component, journeys-admin

#253 Card Editing - Card Layout
  apps/journeys-admin/__generated__/CardBlockLayoutUpdate.ts
  apps/journeys-admin/__generated__/CardBlockThemeModeUpdate.ts
  apps/journeys-admin/__generated__/CardBlockUpdate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/public/card-layout-contained.svg
  apps/journeys-admin/public/card-layout-expanded.svg
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.tsx
Labels: frontend, journeys-admin, feature branch

#257 fix story config overrides
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/ThemeProvider/admin/theme.stories.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/shared/ui/src/components/CopyTextField/CopyTextField.stories.tsx
  libs/shared/ui/src/libs/themes/base/theme.stories.tsx
Labels: bug, frontend

#254 Card Editing - Card Styling
  apps/journeys-admin/__generated__/CardBlockThemeUpdate.ts
  apps/journeys-admin/public/card-style-dark.svg
  apps/journeys-admin/public/card-style-light.svg
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.tsx
Labels: frontend, journeys-admin, feature branch

#259 change import method for material ui
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Button/Button.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/RadioOption/RadioOption.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.stories.tsx
Labels: bug

#258 regenerate types
  .github/workflows/main.yml
  apps/journeys-admin/__generated__/BlockOrderUpdate.ts
  apps/journeys-admin/__generated__/CardBlockThemeUpdate.ts
  apps/journeys-admin/__generated__/CardBlockUpdate.ts
  apps/journeys-admin/__generated__/TypographyBlockUpdate.ts
  apps/journeys-admin/__generated__/VideoBlockCreate.ts
  apps/journeys-admin/project.json
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/GridFields.ts
  apps/journeys/__generated__/ImageFields.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/project.json
  libs/journeys/ui/project.json
  libs/shared/ui/__generated__/globalTypes.ts
  libs/shared/ui/project.json
  libs/shared/ui/src/components/ThemeProvider/ThemeProvider.spec.tsx
  libs/shared/ui/src/components/ThemeProvider/ThemeProvider.tsx
  libs/shared/ui/src/libs/storybook/decorators.tsx
  tools/scripts/check-git-status.sh
Labels: enhancement

#275 add commit linting
  .github/workflows/main.yml
  .husky/commit-msg
  commitlint.config.js
  package-lock.json
  package.json
Labels: priority: now, type: feature, effort: 1

#276 add pull request template
  .github/pull_request_template.md
Labels: priority: now, type: feature, effort: 1

#278 chore: add branch naming
  .github/workflows/main.yml
  tools/scripts/check-git-branch-name.sh
Labels: priority: now, effort: 1, type: chore

#279 chore: add danger
  .github/workflows/main.yml
  dangerfile.ts
  package-lock.json
  package.json
  tools/scripts/check-git-branch-name.sh
Labels: priority: now, effort: 1, type: chore

#274 add stage & main tags to images
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-worker.yml
Labels: type: feature

#272 fix: add branch to worker deployment
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-deploy.yml
Labels: type: fix, priority: now, effort: 1

#266 feature: typename check for action
  apps/api-journeys/src/app/modules/action/action.module.ts
  apps/api-journeys/src/app/modules/action/action.resolver.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.ts
Labels: effort: 3, priority: now, type: feature

#284 fix: add branch to api-deploy
  .github/workflows/api-deploy.yml
Labels: type: fix, priority: now, effort: 1

#268 feature: videos can be displayed across the fullsize of the card
  apps/api-journeys/db/seeds/nua1.ts
  apps/api-journeys/db/seeds/nua2.ts
  apps/api-journeys/db/seeds/nua8.ts
  apps/api-journeys/db/seeds/nua9.ts
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/VideoBlockCreate.ts
  apps/journeys-admin/__generated__/VideoFields.ts
  apps/journeys-admin/__generated__/VideoResponseCreate.ts
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewVideoButton/NewVideoButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewVideoButton/NewVideoButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/journeys/__generated__/VideoResponseCreate.ts
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.stories.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/Video/__generated__/VideoResponseCreate.ts
  libs/journeys/ui/src/components/Video/videoFields.ts
  libs/journeys/ui/src/libs/transformer/__generated__/BlockFields.ts
Labels: priority: soon, type: feature, effort: 1

#286 fix: replace ref with ref_name in github actions
  .github/workflows/api-deploy.yml
  .github/workflows/api-gateway-worker.yml
Labels: type: fix, priority: now, effort: 1

#288 fix: docker push all images for deployment
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-worker.yml
Labels: type: fix, priority: soon, effort: 1

#295 fix: icon display and seed data
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/seeds/nua1.ts
  apps/api-journeys/db/seeds/nua2.ts
  apps/api-journeys/db/seeds/nua8.ts
  apps/api-journeys/db/seeds/nua9.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/button/button.graphql
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/libs/apolloClient/cache.ts
  apps/journeys/src/libs/client/cache/cache.ts
Labels: priority: 2day, type: fix, effort: 1

#296 feature: add SignUpBlockUpdate
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.graphql
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: priority: 2day, type: feature, effort: 1

#298 feature: adding card block
  apps/api-journeys/src/app/modules/block/card/card.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/card/card.resolver.ts
  apps/api-journeys/src/app/modules/block/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/step/step.resolver.ts
  apps/journeys-admin/__generated__/StepAndCardBlockCreate.ts
  apps/journeys-admin/pages/journeys/[journeySlug]/edit.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Editor.tsx
  apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.spec.tsx
  apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.tsx
Labels: effort: 3, priority: soon, type: feature

#303 feature: add automatic slug creation to journey
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: priority: 2day, effort: 5, type: feature

#297 feature: NewButtonButton
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/button/button.graphql
  apps/api-journeys/src/app/modules/block/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/button/button.resolver.ts
  apps/journeys-admin/__generated__/ButtonBlockCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/BlocksTab.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/BlocksTab.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
Labels: effort: 2, priority: now, type: feature

#304 fix: use journey theme for card
  apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.stories.tsx
Labels: type: fix, effort: 3, priority: now

#299 feature: adding journey
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/image/image.graphql
  apps/api-journeys/src/app/modules/block/image/image.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/image/image.resolver.ts
  apps/journeys-admin/__generated__/JourneyCreate.ts
  apps/journeys-admin/__generated__/NewJourney.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.spec.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.stories.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/index.ts
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
Labels: effort: 3, priority: soon, type: feature

#301 fix: parentOrder test warnings
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewImageButton/NewImageButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewRadioQuestionButton/NewRadioQuestionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewVideoButton/NewVideoButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
Labels: type: fix, effort: 1

#307 fix: block reorder ids as _keys
  apps/api-journeys/src/app/modules/block/block.resolver.ts
  libs/nest/database/src/lib/base.service.spec.ts
  libs/nest/database/src/lib/base.service.ts
Labels: effort: 2, type: fix, priority: now

#300 fix: Add parentBlockId to action in api-journeys
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/action/action.graphql
  apps/api-journeys/src/app/modules/action/action.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.module.ts
  apps/api-journeys/src/app/modules/block/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/button/button.resolver.ts
  apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.ts
  apps/api-journeys/src/app/modules/block/videoTrigger/videoTrigger.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/videoTrigger/videoTrigger.resolver.ts
Labels: priority: 2day, effort: 2, type: fix, dependencies

#306 fix: parentBlockId on action frontend
  apps/api-journeys/src/app/modules/block/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.spec.ts
  apps/journeys-admin/__generated__/ActionFields.ts
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/ButtonBlockCreate.ts
  apps/journeys-admin/__generated__/ButtonFields.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/RadioOptionFields.ts
  apps/journeys-admin/__generated__/RadioQuestionBlockCreate.ts
  apps/journeys-admin/__generated__/SignUpBlockCreate.ts
  apps/journeys-admin/__generated__/SignUpFields.ts
  apps/journeys-admin/__generated__/VideoTriggerFields.ts
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Button/Button.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Button/Button.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/RadioOption/RadioOption.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/RadioOption/RadioOption.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/FramePortal/FramePortal.stories.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/data.ts
  apps/journeys-admin/src/components/JourneyView/data.ts
  apps/journeys-admin/src/libs/apolloClient/cache.ts
  apps/journeys/__generated__/ActionFields.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/ButtonFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/RadioOptionFields.ts
  apps/journeys/__generated__/SignUpFields.ts
  apps/journeys/__generated__/VideoTriggerFields.ts
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/journeys/src/libs/client/cache/cache.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/__generated__/ButtonFields.ts
  libs/journeys/ui/src/components/RadioQuestion/RadioOption/RadioOption.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioOption/__generated__/RadioOptionFields.ts
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.stories.tsx
  libs/journeys/ui/src/components/SignUp/__generated__/SignUpFields.ts
  libs/journeys/ui/src/components/Video/VideoTrigger/__generated__/VideoTriggerFields.ts
  libs/journeys/ui/src/libs/action/__generated__/ActionFields.ts
  libs/journeys/ui/src/libs/action/actionFields.ts
  libs/journeys/ui/src/libs/action/handleAction.spec.ts
  libs/journeys/ui/src/libs/transformer/__generated__/BlockFields.ts
Labels: effort: 2, type: fix, priority: soon

#310 chore: update storybook and add interactions
  .storybook/main.js
  libs/journeys/ui/src/components/Card/Card.stories.tsx
  package-lock.json
  package.json
Labels: priority: soon, effort: 1, type: chore, dependencies

#309 fix: remove action api, fix keyFields error
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/action/action.graphql
  apps/api-journeys/src/app/modules/action/action.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/action.resolver.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.ts
  apps/api-journeys/src/app/modules/block/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.spec.ts
Labels: priority: 2day, effort: 2, type: fix

#313 fix: fix updateAction return type
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/action/action.graphql
Labels: priority: 2day, type: fix, effort: 1

#314 fix: added parentBlock id into the action API
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.ts
Labels: type: fix, priority: now, effort: 1
