Repository JesusFilm/core, pull requests merged in 2022-09, with the labels that each got.

#850 feat: add docs site
  .gitignore
  .prettierignore
  CONTRIBUTING.md
  README.md
  apps/docs/.eslintrc.json
  apps/docs/babel.config.js
  apps/docs/blog/2022-09-01-first-post.mdx
  apps/docs/blog/authors.yml
  apps/docs/docs/01-welcome.md
  apps/docs/docs/02-getting-started/01-development-environment.md
  apps/docs/docs/02-getting-started/02-environment-variables.md
  apps/docs/docs/02-getting-started/03-microservice-databases.md
  apps/docs/docs/02-getting-started/04-running-projects.md
  apps/docs/docs/02-getting-started/_category_.json
  apps/docs/docs/03-basics/01-architecture-concepts.md
  apps/docs/docs/03-basics/02-backend/01-general.md
  apps/docs/docs/03-basics/02-backend/_category_.json
  apps/docs/docs/03-basics/03-frontend/01-general.md
  apps/docs/docs/03-basics/03-frontend/_category_.json
  apps/docs/docs/03-basics/_category_.json
  apps/docs/docusaurus.config.js
  apps/docs/project.json
  apps/docs/sidebars.js
  apps/docs/src/components/FeatureList/FeatureList.module.css
  apps/docs/src/components/FeatureList/FeatureList.tsx
  apps/docs/src/components/FeatureList/index.ts
  apps/docs/src/css/custom.css
  apps/docs/src/pages/index.module.css
  apps/docs/src/pages/index.tsx
  apps/docs/static/img/favicon.png
  apps/docs/static/img/logo.svg
  apps/docs/static/img/square.png
  apps/docs/tsconfig.json
  package-lock.json
  package.json
  workspace.json
Labels: priority: now, type: docs, effort: 1

#857 refactor: pages paths for templates
  apps/journeys-admin/pages/publisher/[journeyId].tsx
  apps/journeys-admin/pages/publisher/[journeyId]/edit.tsx
  apps/journeys-admin/pages/publisher/index.tsx
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
Labels: priority: now, effort: 1, type: refactor

#806 feat: template list/card
  apps/journeys-admin/__generated__/GetPublishedTemplates.ts
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/index.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
  apps/journeys-admin/src/components/TemplateCard/TemplateCard.spec.tsx
  apps/journeys-admin/src/components/TemplateCard/TemplateCard.stories.tsx
  apps/journeys-admin/src/components/TemplateCard/TemplateCard.tsx
  apps/journeys-admin/src/components/TemplateCard/index.ts
  apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.spec.tsx
  apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.stories.tsx
  apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.tsx
  apps/journeys-admin/src/components/TemplateLibrary/TemplateListData.ts
  apps/journeys-admin/src/components/TemplateLibrary/index.ts
Labels: effort: 8, priority: soon, type: feat

#841 fix: journeylink to be used in journeyview
  apps/journeys-admin/src/components/JourneyView/JourneyLink/EmbedJourneyDialog/EmbedCardPreview/EmbedCardPreview.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/EmbedJourneyDialog/EmbedCardPreview/index.ts
  apps/journeys-admin/src/components/JourneyView/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/EmbedJourneyDialog/index.ts
  apps/journeys-admin/src/components/JourneyView/JourneyLink/JourneyLink.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/JourneyLink.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/JourneyLink.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/SlugDialog/SlugDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/SlugDialog/SlugDialog.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/SlugDialog/SlugDialog.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/SlugDialog/index.ts
  apps/journeys-admin/src/components/JourneyView/JourneyLink/index.ts
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: now, effort: 1

#854 feat: templates page
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/TitleDescription.tsx
Labels: priority: now, type: feat, effort: 1

#856 chore: use turbosnap for chromatic
  .github/workflows/main.yml
  .storybook/main.js
  package.json
Labels: effort: 2, type: fix, priority: now, type: chore, type: ci

#827 refactor: journey tabs to common
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/index.ts
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/utils/getDuplicated.spec.ts
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/utils/getDuplicatedJourney.ts
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/index.ts
  apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/index.ts
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/index.ts
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/StatusTabPanel.spec.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/StatusTabPanel.stories.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/index.ts
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/index.ts
  apps/journeys-admin/src/components/StatusTabPanel/StatusTabPanel.spec.tsx
  apps/journeys-admin/src/components/StatusTabPanel/StatusTabPanel.stories.tsx
  apps/journeys-admin/src/components/StatusTabPanel/StatusTabPanel.tsx
  apps/journeys-admin/src/components/StatusTabPanel/index.ts
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: effort: 5, priority: soon, type: refactor

#861 refactor: nav menu item select
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.tsx
Labels: priority: now, effort: 1, type: refactor

#860 feat: templates journeyid page
  apps/journeys-admin/__generated__/GetTemplate.ts
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, type: feat, effort: 1

#826 fix: publish only available to journey owners and publishers if template
  apps/journeys-admin/src/components/AccessDialog/ApproveUser/ApproveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/PromoteUser/PromoteUser.tsx
  apps/journeys-admin/src/components/AccessDialog/RemoveUser/RemoveUser.tsx
  apps/journeys-admin/src/components/DuplicateBlock/DuplicateBlock.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/ArchiveJourney/ArchiveJourney.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/index.ts
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/MenuItem/MenuItem.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/MenuItem/MenuItem.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/TrashMenu/TrashMenu.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyListMenu/JourneyListMenu.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/CreateTemplateMenuItem/CreateTemplateMenuItem.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
  apps/journeys-admin/src/components/MenuItem/MenuItem.spec.tsx
  apps/journeys-admin/src/components/MenuItem/MenuItem.stories.tsx
  apps/journeys-admin/src/components/MenuItem/MenuItem.tsx
  apps/journeys-admin/src/components/MenuItem/index.ts
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/UserMenu.tsx
Labels: priority: 2day, effort: 2, type: fix

#828 feat: convert bigquery etl to cronjob
  resources/kube/arangodb-bigquery-etl/Dockerfile
  resources/kube/arangodb-bigquery-etl/arangodb-bigquery-etl-cron.yaml
  resources/kube/arangodb-bigquery-etl/arangodb-bigquery-etl-deployment.yaml
  resources/kube/arangodb-bigquery-etl/bqexport.sh
  resources/kube/doppler-secret/doppler-secret.yaml
Labels: priority: 2day, effort: 3, type: feat

#866 fix: redirect url of create template
  apps/journeys-admin/src/components/JourneyView/Menu/CreateTemplateMenuItem/CreateTemplateMenuItem.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/CreateTemplateMenuItem/CreateTemplateMenuItem.tsx
Labels: type: fix, priority: now, effort: 1

#858 docs: update welcome
  README.md
  apps/docs/docs/01-welcome.md
  apps/docs/docs/02-getting-started/01-development-environment.mdx
  apps/docs/docs/02-getting-started/02-environment-variables.md
  apps/docs/docs/02-getting-started/02-environment-variables.mdx
  apps/docs/docs/02-getting-started/03-microservice-databases.md
  apps/docs/docs/02-getting-started/03-microservice-databases.mdx
  apps/docs/docs/02-getting-started/04-running-projects.md
  apps/docs/docs/02-getting-started/04-running-projects.mdx
  apps/docs/docs/03-basics/02-backend/01-general.md
  apps/docs/docs/03-basics/02-backend/02-extensions.md
  apps/docs/docs/03-basics/02-backend/_category_.json
  apps/docs/docs/03-basics/03-frontend/_category_.json
  apps/docs/src/components/FeatureList/FeatureList.tsx
  apps/docs/src/pages/index.tsx
Labels: priority: now, type: docs, effort: 1

#865 build: feature branch naming
  validate-branch-name.config.js
Labels: priority: now, effort: 1, type: build

#867 fix: remove user id and user journey check
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/journey/journey.service.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#843 feat: date and preview
  apps/journeys-admin/src/components/JourneyView/DatePreview/DatePreview.spec.tsx
  apps/journeys-admin/src/components/JourneyView/DatePreview/DatePreview.stories.tsx
  apps/journeys-admin/src/components/JourneyView/DatePreview/DatePreview.tsx
  apps/journeys-admin/src/components/JourneyView/DatePreview/index.ts
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/TitleDescription.tsx
Labels: type: fix, priority: now, effort: 1

#869 feat: date and preview
  apps/journeys-admin/src/components/JourneyView/DatePreview/DatePreview.spec.tsx
  apps/journeys-admin/src/components/JourneyView/DatePreview/DatePreview.stories.tsx
  apps/journeys-admin/src/components/JourneyView/DatePreview/DatePreview.tsx
  apps/journeys-admin/src/components/JourneyView/DatePreview/index.ts
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/TitleDescription.tsx
Labels: priority: now, type: feat, effort: 1

#842 feat: journey view social image
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/SocialImage/SocialImage.spec.tsx
  apps/journeys-admin/src/components/JourneyView/SocialImage/SocialImage.stories.tsx
  apps/journeys-admin/src/components/JourneyView/SocialImage/SocialImage.tsx
  apps/journeys-admin/src/components/JourneyView/SocialImage/index.ts
Labels: priority: now, type: feat, effort: 1

#849 feat: journey view fab
  apps/journeys-admin/__generated__/ConvertTemplate.ts
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyViewFab/JourneyViewFab.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyViewFab/JourneyViewFab.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyViewFab/JourneyViewFab.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyViewFab/index.ts
Labels: effort: 2, priority: now, type: feat

#875 feat: add aria selected to nav listitem
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.tsx
Labels: priority: now, type: feat, effort: 1

#851 feat: journey view language
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/JourneyDetails.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/JourneyDetails.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/JourneyDetails.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/Language/Language.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/Language/Language.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/Language/Language.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/Language/index.ts
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/TitleDescription.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: now, type: feat

#878 refactor: journey lists loading cards
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.tsx
Labels: priority: soon, effort: 1, type: refactor

#876 fix: redirect issues
  apps/journeys-admin/pages/publisher/[journeyId]/edit.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
Labels: type: fix, priority: now, effort: 1

#877 fix: publisher page access
  apps/journeys-admin/__generated__/GetPublisher.ts
  apps/journeys-admin/pages/publisher/[journeyId].tsx
  apps/journeys-admin/pages/publisher/[journeyId]/edit.tsx
  apps/journeys-admin/src/components/AccessDenied/AccessDenied.spec.tsx
  apps/journeys-admin/src/components/AccessDenied/AccessDenied.tsx
  apps/journeys-admin/src/components/AccessDenied/index.ts
  apps/journeys-admin/src/components/JourneyInvite/JourneyInvite.tsx
  apps/journeys-admin/src/components/PublisherInvite/PublisherInvite.spec.tsx
  apps/journeys-admin/src/components/PublisherInvite/PublisherInvite.stories.tsx
  apps/journeys-admin/src/components/PublisherInvite/PublisherInvite.tsx
  apps/journeys-admin/src/components/PublisherInvite/index.ts
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: now, effort: 1

#880 feat: add video url to video block
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/video/video.graphql
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockCreate.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockUpdate.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/VideoBlockCreate.ts
  apps/journeys-admin/__generated__/VideoBlockUpdate.ts
  apps/journeys-admin/__generated__/VideoFields.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/VideoFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/Video/__generated__/VideoFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
Labels: priority: now, type: feat, effort: 1

#883 fix: status chip style
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/StatusChip/StatusChip.tsx
Labels: priority: soon, effort: 1, type: refactor

#885 feat: textfield block model
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/textField/textField.graphql
  apps/journeys-admin/__generated__/ActionDelete.ts
  apps/journeys-admin/__generated__/BlockDelete.ts
  apps/journeys-admin/__generated__/BlockDeleteForBackgroundImage.ts
  apps/journeys-admin/__generated__/BlockDeleteForBackgroundVideo.ts
  apps/journeys-admin/__generated__/BlockDeleteForPosterImage.ts
  apps/journeys-admin/__generated__/BlockDeletePrimaryImage.ts
  apps/journeys-admin/__generated__/BlockDuplicate.ts
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/BlockOrderUpdate.ts
  apps/journeys-admin/__generated__/DuplicatedBlock.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/NewBlock.ts
  apps/journeys-admin/__generated__/StepsOrderUpdate.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
Labels: priority: 2day, effort: 2, type: feat

#887 feat: textfield api mutations
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/block.module.ts
  apps/api-journeys/src/app/modules/block/textField/textField.graphql
  apps/api-journeys/src/app/modules/block/textField/textField.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/textField/textField.resolver.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#886 ci: remove dependency on test for vr
  .github/workflows/main.yml
Labels: priority: now, effort: 1, type: ci

#889 fix: placeholder image
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/SocialImage/SocialImage.tsx
Labels: type: fix, priority: now, effort: 1

#888 feat: video source and youtube values
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/video/video.graphql
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockCreate.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockUpdate.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/VideoBlockCreate.ts
  apps/journeys-admin/__generated__/VideoBlockUpdate.ts
  apps/journeys-admin/__generated__/VideoFields.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/VideoFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/Video/__generated__/VideoFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
Labels: breaking, effort: 3, priority: now, type: feat

#884 fix: template redirect and access issues
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/pages/publisher/[journeyId].tsx
  apps/journeys-admin/pages/publisher/[journeyId]/edit.tsx
  apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
  apps/journeys-admin/src/libs/apolloClient/index.ts
Labels: type: fix, effort: 3, priority: now

#814 feat: add admin template list
  apps/journeys-admin/__generated__/GetActivePublisherTemplates.ts
  apps/journeys-admin/__generated__/GetArchivedPublisherTemplates.ts
  apps/journeys-admin/__generated__/GetTrashedPublisherTemplates.ts
  apps/journeys-admin/pages/publisher/index.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneySort/utils/sortJourneys.ts
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/TemplateCard/TemplateCard.spec.tsx
  apps/journeys-admin/src/components/TemplateCard/TemplateCard.stories.tsx
  apps/journeys-admin/src/components/TemplateCard/TemplateCard.tsx
  apps/journeys-admin/src/components/TemplateLibrary/TemplateListData.ts
  apps/journeys-admin/src/components/TemplateList/ActiveTemplates/ActiveTemplates.spec.tsx
  apps/journeys-admin/src/components/TemplateList/ActiveTemplates/ActiveTemplates.stories.tsx
  apps/journeys-admin/src/components/TemplateList/ActiveTemplates/ActiveTemplates.tsx
  apps/journeys-admin/src/components/TemplateList/ActiveTemplates/index.ts
  apps/journeys-admin/src/components/TemplateList/ArchivedTemplates/ArchivedTemplates.spec.tsx
  apps/journeys-admin/src/components/TemplateList/ArchivedTemplates/ArchivedTemplates.stories.tsx
  apps/journeys-admin/src/components/TemplateList/ArchivedTemplates/ArchivedTemplates.tsx
  apps/journeys-admin/src/components/TemplateList/ArchivedTemplates/index.ts
  apps/journeys-admin/src/components/TemplateList/TemplateList.stories.tsx
  apps/journeys-admin/src/components/TemplateList/TemplateList.tsx
  apps/journeys-admin/src/components/TemplateList/TemplatesList.spec.tsx
  apps/journeys-admin/src/components/TemplateList/TrashedTemplates/TrashedTemplates.spec.tsx
  apps/journeys-admin/src/components/TemplateList/TrashedTemplates/TrashedTemplates.stories.tsx
  apps/journeys-admin/src/components/TemplateList/TrashedTemplates/TrashedTemplates.tsx
  apps/journeys-admin/src/components/TemplateList/TrashedTemplates/index.ts
  apps/journeys-admin/src/components/TemplateList/index.ts
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: effort: 8, priority: soon, type: feat

#890 feat: textfield submission event
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/event.module.ts
  apps/api-journeys/src/app/modules/event/textField/textField.graphql
  apps/api-journeys/src/app/modules/event/textField/textField.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/textField/textField.resolver.ts
Labels: priority: 2day, effort: 2, type: feat, on stage

#891 fix: rename text field block to text response block
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/block.module.ts
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.graphql
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.ts
  apps/api-journeys/src/app/modules/event/event.module.ts
  apps/api-journeys/src/app/modules/event/textField/textField.graphql
  apps/api-journeys/src/app/modules/event/textField/textField.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.graphql
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.ts
  apps/journeys-admin/__generated__/ActionDelete.ts
  apps/journeys-admin/__generated__/BlockDelete.ts
  apps/journeys-admin/__generated__/BlockDeleteForBackgroundImage.ts
  apps/journeys-admin/__generated__/BlockDeleteForBackgroundVideo.ts
  apps/journeys-admin/__generated__/BlockDeleteForPosterImage.ts
  apps/journeys-admin/__generated__/BlockDeletePrimaryImage.ts
  apps/journeys-admin/__generated__/BlockDuplicate.ts
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/BlockOrderUpdate.ts
  apps/journeys-admin/__generated__/DuplicatedBlock.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/NewBlock.ts
  apps/journeys-admin/__generated__/StepsOrderUpdate.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
Labels: priority: 2day, effort: 2, type: fix

#894 feat: make text field common
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/SignUp/TextField/TextField.stories.tsx
  libs/journeys/ui/src/components/StoryCard/StoryCard.tsx
  libs/journeys/ui/src/components/TextField/TextField.spec.tsx
  libs/journeys/ui/src/components/TextField/TextField.stories.tsx
  libs/journeys/ui/src/components/TextField/TextField.tsx
  libs/journeys/ui/src/components/TextField/index.ts
Labels: effort: 2, type: fix, priority: soon

#896 fix: remodel text response
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.graphql
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.graphql
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.spec.ts
Labels: priority: 2day, type: fix, effort: 1

#899 fix: text response minRows
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.graphql
Labels: type: fix, priority: now, effort: 1, on stage

#882 feat: videojs youtube
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockCreate.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockUpdate.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/VideoBlockCreate.ts
  apps/journeys-admin/__generated__/VideoBlockUpdate.ts
  apps/journeys-admin/__generated__/VideoFields.ts
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/src/libs/testData/storyData.ts
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/VideoFields.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/VideoFields.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.stories.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.spec.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/Video/videoFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
  package-lock.json
  package.json
Labels: effort: 3, priority: soon, type: feat

#855 feat: styled firebase auth
  apps/journeys-admin/src/components/SignIn/SignIn.tsx
  apps/watch-admin/src/components/SignIn/SignIn.tsx
  libs/shared/ui/src/components/StyledFirebaseAuth/StyledFirebaseAuth.tsx
  libs/shared/ui/src/components/StyledFirebaseAuth/index.ts
  package-lock.json
  package.json
Labels: effort: 2, priority: soon, type: feat

#908 fix: msw prettier error
  .prettierignore
  .storybook/static/mockServiceWorker.js
Labels: type: fix, priority: now, effort: 1

#898 feat: text response block
  .storybook/preview.js
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/TextResponseFields.ts
  apps/journeys-admin/__generated__/TextResponseSubmissionEventCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/libs/apolloClient/cache.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/TextResponseFields.ts
  apps/journeys/__generated__/TextResponseSubmissionEventCreate.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx
  apps/journeys/src/libs/apolloClient/cache/cache.ts
  apps/journeys/src/libs/testData/storyData.ts
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/TextResponseFields.ts
  apps/watch-admin/__generated__/TextResponseSubmissionEventCreate.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/TextResponseFields.ts
  apps/watch/__generated__/TextResponseSubmissionEventCreate.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
  libs/journeys/ui/src/components/TextField/TextField.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.spec.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.stories.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
  libs/journeys/ui/src/components/TextResponse/__generated__/TextResponseFields.ts
  libs/journeys/ui/src/components/TextResponse/__generated__/TextResponseSubmissionEventCreate.ts
  libs/journeys/ui/src/components/TextResponse/index.ts
  libs/journeys/ui/src/components/TextResponse/textResponseFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
  libs/journeys/ui/src/libs/block/blockFields.ts
Labels: priority: 2day, effort: 3, type: feat

#909 ci: prevent VR on dependabot branch
  .github/workflows/main.yml
Labels: priority: now, effort: 1, type: ci

#910 ci: vr ignore translation files
  .github/workflows/main.yml
Labels: priority: now, effort: 1, type: ci

#911 feat: update journey admin mutation guards
  apps/api-journeys/src/app/lib/roleGuard/roleGuard.ts
  apps/api-journeys/src/app/modules/action/action.resolver.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.ts
  apps/api-journeys/src/app/modules/block/block.resolver.ts
  apps/api-journeys/src/app/modules/block/button/button.resolver.ts
  apps/api-journeys/src/app/modules/block/card/card.resolver.ts
  apps/api-journeys/src/app/modules/block/icon/icon.resolver.ts
  apps/api-journeys/src/app/modules/block/image/image.resolver.ts
  apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.ts
  apps/api-journeys/src/app/modules/block/step/step.resolver.ts
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.ts
  apps/api-journeys/src/app/modules/block/typography/typography.resolver.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Labels: effort: 2, priority: now, type: feat, on stage

#912 fix: back link on template view pages
  apps/journeys-admin/pages/publisher/[journeyId].tsx
  apps/journeys-admin/pages/templates/[journeyId].tsx
Labels: type: fix, priority: soon, effort: 1

#913 fix: preview button opens link in a new tab
  apps/journeys-admin/src/components/JourneyView/DatePreview/DatePreview.spec.tsx
  apps/journeys-admin/src/components/JourneyView/DatePreview/DatePreview.tsx
Labels: type: fix, priority: soon, effort: 1

#914 refactor: nav menu item selection
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/publisher/[journeyId].tsx
  apps/journeys-admin/pages/publisher/[journeyId]/edit.tsx
  apps/journeys-admin/pages/publisher/index.tsx
  apps/journeys-admin/pages/reports.tsx
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
Labels: effort: 2, priority: soon, type: refactor

#903 fix: select first property
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Button/Button.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Button/Button.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Image.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Image.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/RadioOption/RadioOption.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/RadioOption/RadioOption.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/index.ts
Labels: type: fix, priority: soon, effort: 1

#893 feat: add text response property button and sidepannel
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextField/TextField.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextField/TextField.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextField/TextField.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextField/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponse.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponse.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponse.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/index.ts
Labels: effort: 2, priority: soon, type: feat

#904 fix: inline edit text response submit button
  apps/api-journeys/db/seeds/nua1.ts
  apps/journeys-admin/__generated__/TextResponseBlockUpdateContent.ts
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TextResponseEdit/index.ts
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
Labels: type: fix, effort: 3, priority: soon

#917 fix: add text response block type to action
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.ts
Labels: type: fix, priority: soon, effort: 1

#918 fix: update action component for text response (front end)
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
Labels: type: fix, priority: soon, effort: 1

#919 fix: templates edit seo title
  apps/journeys-admin/pages/publisher/[journeyId]/edit.tsx
Labels: priority: 2day, type: fix, effort: 1

#921 fix: remove template duplicate from template card
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.tsx
Labels: priority: 2day, effort: 2, type: fix

#862 fix: drawer z index
  apps/journeys-admin/src/components/Editor/Drawer/Drawer.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Drawer.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.tsx
Labels: type: fix, priority: soon, effort: 1

#905 feat: add edit TextResponse fields
  apps/journeys-admin/__generated__/TextResponseHintUpdate.ts
  apps/journeys-admin/__generated__/TextResponseLabelUpdate.ts
  apps/journeys-admin/__generated__/TextResponseMinRowsUpdate.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/ToggleButtonGroup/ToggleButtonGroup.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/ToggleButtonGroup/ToggleButtonGroup.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/ToggleButtonGroup/ToggleButtonGroup.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponse.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/Hint/Hint.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/Hint/Hint.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/Hint/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/Label/Label.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/Label/Label.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/Label/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/MinRows/MinRows.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/MinRows/MinRows.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/MinRows/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/TextResponseFields.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/TextResponseFields.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/TextResponseFields.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/index.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: soon, type: feat

#922 fix: control panel label and hint layout shift
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.tsx
  libs/journeys/ui/src/components/TextField/TextField.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, type: fix, priority: soon

#879 fix: update embed preview and conductor styling
  apps/journeys-admin/src/components/JourneyView/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.tsx
  apps/journeys/pages/embed/test/[journeySlug].tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
Labels: type: fix, effort: 3, priority: soon

#923 fix: remove report flag
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/reports.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/JourneyLink.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/JourneyLink.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/JourneyLink.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/TemplateList/TemplateList.stories.tsx
  libs/shared/ui/src/components/FlagsProvider/FlagsProvider.spec.tsx
Labels: type: fix, effort: 3, priority: soon

#881 feat: add back button to access requested
  apps/journeys-admin/src/components/AccessDenied/AccessDenied.spec.tsx
  apps/journeys-admin/src/components/AccessDenied/AccessDenied.tsx
Labels: priority: soon, type: feat, effort: 1

#928 fix: video block update without video id
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
  libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
Labels: type: fix, priority: now, effort: 1, on stage

#929 fix: refresh form when changing blocks
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/LinkAction/LinkAction.tsx
Labels: priority: 2day, effort: 2, type: fix
