Repository JesusFilm/core, pull requests merged in 2022-11, with the labels that each got.

#1011 feat: adding DataGrid package
  package-lock.json
  package.json
Labels: priority: 2day, type: feat, effort: 1

#1012 refactor: watch hero
  apps/watch/__generated__/GetLanguage.ts
  apps/watch/__generated__/GetVideo.ts
  apps/watch/__generated__/GetVideoSiblings.ts
  apps/watch/__generated__/GetVideoTag.ts
  apps/watch/pages/[...slug].tsx
  apps/watch/pages/index.tsx
  apps/watch/pages/videos/[...tag].tsx
  apps/watch/pages/videos/index.tsx
  apps/watch/src/components/Hero/HomeHero/HomeHero.tsx
  apps/watch/src/components/Hero/SimpleHero/SimpleHero.tsx
  apps/watch/src/components/Hero/VideoHero/VideoHero.tsx
  apps/watch/src/components/Hero/index.ts
Labels: effort: 3, priority: soon, type: refactor

#1015 ci: vr test ignore full rebuilds
  .github/workflows/main.yml
  .storybook/main.js
Labels: priority: now, effort: 1, type: ci

#1018 refactor: use onClose instead of handleClose
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DeleteJourneyDialog/DeleteJourneyDialog.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/RestoreJourneyDialog/RestoreJourneyDialog.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/TrashJourneyDialog/TrashJourneyDialog.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/SlugDialog/SlugDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/LanguageDialog/LanguageDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/TitleDescriptionDialog/TitleDescriptionDialog.tsx
  apps/journeys-admin/src/components/TemplateList/ActiveTemplates/ActiveTemplates.tsx
  apps/journeys-admin/src/components/TemplateList/ArchivedTemplates/ArchivedTemplates.tsx
  apps/journeys-admin/src/components/TemplateList/TrashedTemplates/TrashedTemplates.tsx
  libs/shared/ui/src/components/Dialog/Dialog.spec.tsx
  libs/shared/ui/src/components/Dialog/Dialog.stories.tsx
  libs/shared/ui/src/components/Dialog/Dialog.tsx
Labels: priority: 2day, effort: 1, type: refactor

#1009 fix: watch header
  .github/workflows/main.yml
  apps/watch/public/header-logo.svg
  apps/watch/public/taskbar-icon.svg
  apps/watch/src/components/Footer/Footer.tsx
  apps/watch/src/components/Header/Header.stories.tsx
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.spec.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/index.ts
Labels: effort: 2, type: fix, priority: soon

#1016 fix: watch footer
  apps/watch/pages/[...slug].tsx
  apps/watch/pages/index.tsx
  apps/watch/public/images/cru-logo.svg
  apps/watch/public/images/jf-logo.svg
  apps/watch/src/components/Footer/Footer.spec.tsx
  apps/watch/src/components/Footer/Footer.stories.tsx
  apps/watch/src/components/Footer/Footer.tsx
  apps/watch/src/components/Footer/FooterLink/FooterLink.spec.tsx
  apps/watch/src/components/Footer/FooterLink/FooterLink.tsx
  apps/watch/src/components/Footer/FooterLink/index.ts
  apps/watch/src/components/Footer/FooterLinks/FooterLinks.spec.tsx
  apps/watch/src/components/Footer/FooterLinks/FooterLinks.tsx
  apps/watch/src/components/Footer/FooterLinks/index.ts
  apps/watch/src/components/Footer/FooterLogos/FooterLogos.spec.tsx
  apps/watch/src/components/Footer/FooterLogos/FooterLogos.tsx
  apps/watch/src/components/Footer/FooterLogos/index.ts
  apps/watch/src/components/Footer/FooterSocials/FooterSocials.spec.tsx
  apps/watch/src/components/Footer/FooterSocials/FooterSocials.tsx
  apps/watch/src/components/Footer/FooterSocials/index.ts
  apps/watch/src/components/Footer/index.ts
Labels: effort: 2, type: fix, priority: soon

#1017 feat: events query
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/button/button.graphql
  apps/api-journeys/src/app/modules/event/event.graphql
  apps/api-journeys/src/app/modules/event/event.module.ts
  apps/api-journeys/src/app/modules/event/event.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/event.resolver.ts
  apps/api-journeys/src/app/modules/event/event.service.spec.ts
  apps/api-journeys/src/app/modules/event/event.service.ts
  apps/api-journeys/src/app/modules/event/journey/journey.graphql
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.graphql
  apps/api-journeys/src/app/modules/event/signUp/signUp.graphql
  apps/api-journeys/src/app/modules/event/step/step.graphql
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.graphql
  apps/api-journeys/src/app/modules/event/video/video.graphql
  apps/api-journeys/src/app/modules/event/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/video/video.resolver.ts
  apps/api-journeys/src/app/modules/visitor/visitor.graphql
  apps/api-journeys/src/app/modules/visitor/visitor.module.ts
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.ts
Labels: effort: 5, priority: soon, type: feat, on stage

#1008 feat: add emojis to visitor status
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/visitor/visitor.graphql
Labels: priority: now, type: feat, effort: 1, on stage

#970 feat: update events resolvers
  apps/api-gateway/schema.graphql
  apps/api-gateway/src/main.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
  apps/api-journeys/src/app/modules/event/button/button.graphql
  apps/api-journeys/src/app/modules/event/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/button/button.resolver.ts
  apps/api-journeys/src/app/modules/event/event.module.ts
  apps/api-journeys/src/app/modules/event/event.service.spec.ts
  apps/api-journeys/src/app/modules/event/event.service.ts
  apps/api-journeys/src/app/modules/event/journey/journey.graphql
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.graphql
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.ts
  apps/api-journeys/src/app/modules/event/signUp/signUp.graphql
  apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.ts
  apps/api-journeys/src/app/modules/event/step/step.graphql
  apps/api-journeys/src/app/modules/event/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/step/step.resolver.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.graphql
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.ts
  apps/api-journeys/src/app/modules/event/video/video.graphql
  apps/api-journeys/src/app/modules/event/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/video/video.resolver.ts
  apps/api-journeys/src/app/modules/visitor/visitor.module.ts
  apps/api-journeys/src/app/modules/visitor/visitor.service.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.service.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/nest/decorators/src/lib/CurrentIPAddress/CurrentIPAddress.ts
  libs/nest/decorators/src/lib/CurrentIPAddress/index.ts
  libs/nest/decorators/src/lib/CurrentUserAgent/CurrentUserAgent.ts
  libs/nest/decorators/src/lib/CurrentUserAgent/index.ts
Labels: priority: now, effort: 13, type: feat, on stage

#1006 feat: add new user events
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/button/button.graphql
  apps/api-journeys/src/app/modules/event/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/button/button.resolver.ts
  apps/api-journeys/src/app/modules/event/event.module.ts
  apps/api-journeys/src/app/modules/event/step/step.graphql
  apps/api-journeys/src/app/modules/event/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/step/step.resolver.ts
Labels: effort: 3, priority: now, type: feat, on stage

#1027 refactor: reports pages for journeys and visitors
  apps/journeys-admin/next.config.js
  apps/journeys-admin/pages/reports/journeys.tsx
  apps/journeys-admin/pages/reports/visitors.tsx
  apps/journeys-admin/pages/reports/visitors/[visitorId].tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: priority: now, effort: 1, type: refactor

#1002 feat: add submit listener
  libs/shared/ui/src/components/SubmitListener/SubmitListener.spec.tsx
  libs/shared/ui/src/components/SubmitListener/SubmitListener.stories.tsx
  libs/shared/ui/src/components/SubmitListener/SubmitListener.tsx
  libs/shared/ui/src/components/SubmitListener/index.ts
Labels: priority: now, type: feat, effort: 1

#1028 refactor: visitor change messenger network to message platform
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/visitor/visitor.graphql
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.spec.ts
Labels: priority: now, effort: 1, type: refactor

#1030 refactor: change to chat open event
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/button/button.graphql
  apps/api-journeys/src/app/modules/event/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/button/button.resolver.ts
  apps/api-journeys/src/app/modules/event/event.module.ts
  apps/api-journeys/src/app/modules/visitor/visitor.graphql
Labels: priority: now, effort: 1, type: refactor

#1025 feat: api-videos ids filter
  apps/api-gateway/schema.graphql
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#1024 feat: update events frontend mutations
  apps/journeys-admin/__generated__/ChatOpenEventCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/ChatOpenEventCreate.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/watch-admin/__generated__/ChatOpenEventCreate.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/ChatOpenEventCreate.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Button/__generated__/ChatOpenEventCreate.ts
  libs/journeys/ui/src/components/Button/findChatPlatform/findChatPlatform.spec.ts
  libs/journeys/ui/src/components/Button/findChatPlatform/findChatPlatform.ts
  libs/journeys/ui/src/components/Button/findChatPlatform/index.ts
  libs/journeys/ui/src/components/RadioOption/RadioOption.spec.tsx
  libs/journeys/ui/src/components/RadioOption/RadioOption.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.spec.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.spec.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.tsx
Labels: effort: 5, priority: soon, type: feat, on stage

#1033 fix: add key as id to get all by visitor id
  apps/api-journeys/src/app/modules/event/event.service.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1029 feat: visitor info page with details and journey tabs
  apps/journeys-admin/__generated__/GetVisitor.ts
  apps/journeys-admin/__generated__/GetVisitorEvents.ts
  apps/journeys-admin/__generated__/VisitorUpdate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/i18next-parser.config.js
  apps/journeys-admin/pages/reports/visitors/[visitorId].tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetail.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetail.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetailForm/VisitorDetailForm.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetailForm/VisitorDetailForm.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetailForm/VisitorDetailForm.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetailForm/VisitorDetailFormData.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetailForm/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorInfo.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorInfo.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorInfo.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorInfoProvider/VisitorInfoProvider.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorInfoProvider/VisitorInfoProvider.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorInfoProvider/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyDrawer/VisitorJourneyDrawer.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyDrawer/VisitorJourneyDrawer.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyDrawer/VisitorJourneyDrawer.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyDrawer/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyList/VisitorJourneyList.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyList/VisitorJourneyList.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyList/VisitorJourneyList.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyList/VisitorJourneyListData.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyList/VisitorJourneyListItem/VisitorJourneyListItem.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyList/VisitorJourneyListItem/VisitorJourneyListItem.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyList/VisitorJourneyListItem/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyList/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimeline.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimeline.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimeline.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimelineItem/GenericEvent/GenericEvent.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimelineItem/GenericEvent/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimelineItem/VisitorJourneyTimelineItem.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimelineItem/VisitorJourneyTimelineItem.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimelineItem/VisitorJourneyTimelineItem.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimelineItem/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/index.ts
  apps/journeys-admin/src/components/VisitorInfo/index.ts
  apps/journeys-admin/src/components/VisitorInfo/messagePlatformToLabel.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/messagePlatformToLabel.ts
  apps/journeys-admin/src/components/VisitorInfo/transformVisitorEvents.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/transformVisitorEvents.ts
  apps/journeys-admin/src/components/VisitorInfo/videoBlockSourceToLabel.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/videoBlockSourceToLabel.ts
  libs/journeys/ui/i18next-parser.config.js
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/libs-journeys-ui.json
  libs/locales/en/translation.json
Labels: priority: now, effort: 13, type: feat, on stage

#1035 feat: api videos by id
  apps/api-gateway/schema.graphql
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
Labels: effort: 2, priority: now, type: feat, on stage

#1019 feat: create share dialog
  apps/watch/pages/[...slug].tsx
  apps/watch/pages/_app.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.tsx
  apps/watch/src/components/ShareDialog/index.ts
  apps/watch/src/libs/storybook/config.tsx
Labels: effort: 3, priority: soon, type: feat

#963 feat: remove arangodb
  resources/kube/arangodb/arangodb-deployment.yaml
  resources/kube/arangodb/arangodb-service.yaml
  resources/kube/arangodb/arangodb-stage-deployment.yaml
  resources/kube/arangodb/arangodb-stage-service.yaml
  resources/kube/arangodb/deploy.sh
Labels: priority: 2day, type: feat, effort: 1

#1023 fix: home hero
  apps/watch/public/images/jesus-header.png
  apps/watch/public/images/jesus-header.svg
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Hero/HomeHero/HomeHero.spec.tsx
  apps/watch/src/components/Hero/HomeHero/HomeHero.stories.tsx
  apps/watch/src/components/Hero/HomeHero/HomeHero.tsx
  apps/watch/src/components/Hero/HomeHero/index.ts
  apps/watch/src/components/Hero/index.ts
  libs/shared/ui/src/libs/themes/website/theme.ts
  libs/shared/ui/src/libs/themes/website/tokens/typography.ts
Labels: effort: 2, type: fix, priority: soon

#1038 fix: remove unused endpoint
  apps/api-gateway/schema.graphql
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
Labels: priority: 2day, type: fix, effort: 1, on stage

#1037 fix: add xxl breakpoint
  apps/watch/src/components/PageWrapper/PageWrapper.tsx
  libs/shared/ui/src/libs/themes/base/theme.stories.tsx
  libs/shared/ui/src/libs/themes/base/tokens/breakpoints.ts
  libs/shared/ui/src/libs/useBreakpoints/useBreakpoints.ts
Labels: effort: 2, type: fix, priority: soon

#1041 docs: migrate wiki to docs site
  apps/docs/docs/04-engineering-practices/01-workflow/_category_.json
  apps/docs/docs/04-engineering-practices/01-workflow/atlantis-comment.png
  apps/docs/docs/04-engineering-practices/01-workflow/index.md
  apps/docs/docs/04-engineering-practices/01-workflow/infracost-comment.png
  apps/docs/docs/04-engineering-practices/01-workflow/pull-request-comment.png
  apps/docs/docs/04-engineering-practices/01-workflow/pull-request-deleted.png
  apps/docs/docs/04-engineering-practices/01-workflow/pull-request-example.png
  apps/docs/docs/04-engineering-practices/01-workflow/pull-request-merge.png
  apps/docs/docs/04-engineering-practices/01-workflow/vercel-comment.png
  apps/docs/docs/04-engineering-practices/02-deployment/index.md
  apps/docs/docs/04-engineering-practices/02-deployment/stage-branch-merge-bot-attempting.png
  apps/docs/docs/04-engineering-practices/02-deployment/stage-branch-merge-bot-conflict.png
  apps/docs/docs/04-engineering-practices/03-internationalization.md
Labels: priority: now, type: docs, effort: 1

#1039 feat: postgres development env
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/post-create-command.sh
Labels: priority: 2day, effort: 2, type: feat

#1022 feat: watch home video grid
  apps/watch/__generated__/GetHomeVideo.ts
  apps/watch/pages/index.tsx
  apps/watch/src/components/HomeVideos/Card/HomeVideoCard.spec.tsx
  apps/watch/src/components/HomeVideos/Card/HomeVideoCard.stories.tsx
  apps/watch/src/components/HomeVideos/Card/HomeVideoCard.tsx
  apps/watch/src/components/HomeVideos/Card/index.ts
  apps/watch/src/components/HomeVideos/HomeVideos.spec.tsx
  apps/watch/src/components/HomeVideos/HomeVideos.stories.tsx
  apps/watch/src/components/HomeVideos/HomeVideos.tsx
  apps/watch/src/components/HomeVideos/index.ts
  apps/watch/src/components/HomeVideos/testData.ts
Labels: effort: 5, priority: soon, type: feat

#1050 ci: use turbosnap on main
  .github/workflows/main.yml
Labels: effort: 2, priority: now, type: ci

#1042 docs: migrate handbook to docs site
  apps/docs/docs/05-team/01-code-of-conduct.md
  apps/docs/docs/05-team/02-our-team-is-you.md
  apps/docs/docs/05-team/03-what-we-stand-for.md
  apps/docs/docs/05-team/04-where-we-work.md
  apps/docs/docs/05-team/05-how-we-work.md
  apps/docs/docs/05-team/06-getting-started.md
  apps/docs/docs/05-team/06-making-a-career/01-titles-for-engineers.md
  apps/docs/docs/05-team/06-making-a-career/02-titles-for-designers.md
  apps/docs/docs/05-team/06-making-a-career/index.md
  apps/docs/docs/05-team/06-making-a-career/performance-plan-process.md
  apps/docs/docs/05-team/07-our-habits.md
  apps/docs/docs/05-team/08-our-responsibilities.md
  apps/docs/docs/05-team/09-international-travel-guide.md
  apps/docs/docs/05-team/index.md
Labels: priority: now, type: docs, effort: 1

#1051 docs: add quick links
  apps/docs/docs/06-quick-links.md
Labels: priority: now, type: docs, effort: 1

#1052 feat: intro text
  apps/watch/pages/index.tsx
  apps/watch/src/components/IntroText/IntroText.spec.tsx
  apps/watch/src/components/IntroText/IntroText.stories.tsx
  apps/watch/src/components/IntroText/IntroText.tsx
  apps/watch/src/components/IntroText/index.ts
Labels: effort: 2, priority: now, type: feat

#941 style: updated button variant and aligned to center
  apps/journeys-admin/src/components/AccessDenied/AccessDenied.tsx
Labels: priority: 2day, effort: 1, type: style

#934 fix: small video library design updates
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/VideoFromLocal.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/YouTubeDetails/YouTubeDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoSearch/VideoSearch.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoSearch/VideoSearch.tsx
Labels: type: fix, priority: soon, effort: 1

#1057 docs: dev environment fix
  apps/docs/docs/02-getting-started/01-development-environment.mdx
Labels: effort: 3, type: docs, priority: soon

#1055 ci: hotfix ignore main build if multiple ancestor builds
  .github/workflows/main.yml
  tools/scripts/check-git-diff.sh
Labels: effort: 2, priority: now, type: ci

#1061 fix: video block schema
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Labels: type: fix, priority: now, effort: 1

#1058 fix: primary image block edited on other journeys
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: type: fix, effort: 3, priority: now

#1053 docs: frontend
  apps/docs/docs/03-basics/03-frontend/02-component-library/component-hierarchy.png
  apps/docs/docs/03-basics/03-frontend/02-component-library/component-types.png
  apps/docs/docs/03-basics/03-frontend/02-component-library/index.md
  apps/docs/docs/03-basics/03-frontend/02-component-library/other-components.png
  apps/docs/docs/03-basics/03-frontend/03-theming/all-components.png
  apps/docs/docs/03-basics/03-frontend/03-theming/index.md
  apps/docs/docs/03-basics/03-frontend/04-storybook/index.md
  apps/docs/docs/03-basics/03-frontend/04-storybook/when-to-write-stories.png
  apps/docs/docs/03-basics/03-frontend/05-visual-testing/component-types.png
  apps/docs/docs/03-basics/03-frontend/05-visual-testing/index.md
  apps/docs/docs/03-basics/03-frontend/05-visual-testing/turbosnap.png
  apps/docs/docs/03-basics/03-frontend/05-visual-testing/when-to-write-stories.png
Labels: effort: 3, type: docs, priority: soon

#1068 ci: fix chromatic untraced
  .github/workflows/main.yml
  package-lock.json
  package.json
Labels: priority: now, effort: 1, type: ci

#1065 docs: add in about story naming
  apps/docs/docs/03-basics/03-frontend/04-storybook/index.md
Labels: priority: 2day, type: docs, effort: 1

#1071 ci: vr fetch depth, remove redundant step
  .github/workflows/main.yml
Labels: priority: now, effort: 1, type: ci

#1073 ci: build only affected libraries so full rebuilds have less impact
  .github/workflows/main.yml
Labels: priority: now, effort: 1, type: ci

#1063 fix: add objectFit to video block
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/video/video.graphql
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: effort: 5, type: fix, priority: now

#1059 feat: aws vpn
  apps/api-gateway/infrastructure/.terraform.lock.hcl
  infrastructure/modules/aws/main.tf
  infrastructure/modules/aws/vpn/data.tf
  infrastructure/modules/aws/vpn/main.tf
  infrastructure/modules/aws/vpn/variables.tf
Labels: effort: 5, priority: soon, type: feat

#1075 ci: fix untraced value
  .github/workflows/main.yml
Labels: priority: now, effort: 1, type: ci

#1079 fix: update cypress request dependency
  package-lock.json
Labels: type: fix, priority: now, effort: 1

#1081 fix: update study questions type to match graphQL
  apps/api-gateway/schema.graphql
  apps/api-videos/db/seed.ts
  apps/watch/__generated__/GetVideo.ts
  apps/watch/pages/[...slug].tsx
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
  libs/nest/decorators/src/lib/TranslationField/TranslationField.spec.ts
  libs/nest/decorators/src/lib/TranslationField/TranslationField.ts
Labels: priority: 2day, effort: 2, type: fix, on stage

#1085 fix: visitor list pagination
  apps/api-journeys/src/app/modules/visitor/visitor.service.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.service.ts
Labels: effort: 2, type: fix, priority: now

#1086 feat: style mui autocomplete & other textfields
  libs/shared/ui/src/libs/themes/website/tokens/components.stories.tsx
  libs/shared/ui/src/libs/themes/website/tokens/components.tsx
Labels: effort: 2, priority: soon, type: feat

#1095 feat: add label to api-video
  apps/api-gateway/schema.graphql
  apps/api-videos/db/seed.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  apps/arangodb-bigquery-etl/bqexport.sh
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
Labels: effort: 3, priority: now, type: feat, on stage

#1100 feat: remove tags
  apps/api-gateway/schema.graphql
  apps/api-videos/db/seed.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/app.module.ts
  apps/api-videos/src/app/modules/tag/tag.graphql
  apps/api-videos/src/app/modules/tag/tag.module.ts
  apps/api-videos/src/app/modules/tag/tag.resolver.spec.ts
  apps/api-videos/src/app/modules/tag/tag.resolver.ts
  apps/api-videos/src/app/modules/tag/tag.service.spec.ts
  apps/api-videos/src/app/modules/tag/tag.service.ts
  apps/api-videos/src/app/modules/tag/testData.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  apps/arangodb-bigquery-etl/bqexport.sh
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
  apps/watch/src/libs/client/cache/cache.ts
  apps/watch/src/libs/routeParser/routeParser.spec.ts
  apps/watch/src/libs/routeParser/routeParser.ts
Labels: effort: 2, priority: now, type: feat, on stage

#1101 fix: breakpoints on sm
  libs/shared/ui/src/libs/themes/base/theme.stories.tsx
  libs/shared/ui/src/libs/themes/base/tokens/breakpoints.ts
Labels: effort: 2, type: fix, priority: soon

#1097 feat: api videos children
  apps/api-gateway/schema.graphql
  apps/api-videos/db/seed.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
Labels: effort: 3, priority: now, type: feat, on stage
