Repository JesusFilm/core, pull requests merged in 2022-12, with the labels that each got.

#1104 fix: intemediate episodeIds fix
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1106 fix: oom children search
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
Labels: type: fix, effort: 3, priority: now, on stage

#1108 feat: remove episodes from video api
  apps/api-gateway/schema.graphql
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  apps/arangodb-bigquery-etl/bqexport.sh
Labels: effort: 2, priority: now, type: feat, on stage

#1102 fix: icon in shared dialog
  libs/shared/ui/src/components/Dialog/Dialog.spec.tsx
  libs/shared/ui/src/components/Dialog/Dialog.stories.tsx
  libs/shared/ui/src/components/Dialog/Dialog.tsx
Labels: type: fix, priority: now, effort: 1

#1110 feat: remove video.type from frontend
  apps/watch/__generated__/GetHomeVideo.ts
  apps/watch/__generated__/GetVideo.ts
  apps/watch/__generated__/GetVideoSiblings.ts
  apps/watch/__generated__/GetVideos.ts
  apps/watch/pages/[...slug].tsx
  apps/watch/pages/index.tsx
  apps/watch/src/components/Hero/VideoHero/VideoHero.tsx
  apps/watch/src/components/HomeVideos/Card/HomeVideoCard.tsx
  apps/watch/src/components/HomeVideos/testData.ts
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.tsx
  apps/watch/src/components/Video/VideoCard/VideoCard.tsx
  apps/watch/src/components/Videos/Videos.tsx
  apps/watch/src/components/Videos/testData.ts
Labels: effort: 2, priority: now, type: feat

#1111 feat: remove type from api videos
  apps/api-gateway/schema.graphql
  apps/api-videos/db/seed.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  apps/arangodb-bigquery-etl/bqexport.sh
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
Labels: effort: 2, priority: now, type: feat, on stage

#1114 feat: final api-video changes
  apps/api-gateway/schema.graphql
  apps/api-videos/db/seed.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
Labels: priority: now, type: feat, effort: 1, on stage

#1083 feat: new api video data
  apps/watch/__generated__/GetHomeVideo.ts
  apps/watch/__generated__/GetVideo.ts
  apps/watch/__generated__/GetVideoSiblings.ts
  apps/watch/__generated__/GetVideos.ts
  apps/watch/pages/[...slug].tsx
  apps/watch/pages/index.tsx
  apps/watch/src/components/HomeVideos/Card/HomeVideoCard.spec.tsx
  apps/watch/src/components/HomeVideos/Card/HomeVideoCard.stories.tsx
  apps/watch/src/components/HomeVideos/Card/HomeVideoCard.tsx
  apps/watch/src/components/HomeVideos/HomeVideos.spec.tsx
  apps/watch/src/components/HomeVideos/HomeVideos.stories.tsx
  apps/watch/src/components/HomeVideos/HomeVideos.tsx
  apps/watch/src/components/HomeVideos/index.ts
  apps/watch/src/components/HomeVideos/testData.ts
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
  apps/watch/src/components/Videos/Videos.tsx
  apps/watch/src/components/Videos/testData.ts
  apps/watch/src/libs/client/cache/cache.ts
Labels: effort: 8, priority: soon, type: feat

#1112 chore: add slug to videos and variants on api-videos
  apps/api-videos/db/seed.ts
  apps/api-videos/src/libs/arclight/arclight.spec.ts
  apps/api-videos/src/libs/arclight/arclight.ts
  apps/api-videos/src/libs/arclight/index.ts
  apps/api-videos/src/libs/slugify/index.ts
  apps/api-videos/src/libs/slugify/slugify.spec.ts
  apps/api-videos/src/libs/slugify/slugify.ts
Labels: priority: now, effort: 13, type: chore

#1087 refactor: get video by slug API
  apps/api-gateway/schema.graphql
  apps/api-videos/db/seed.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  apps/api-videos/src/app/modules/videoVariant/videoVariant.graphql
  apps/api-videos/src/libs/arclight/arclight.spec.ts
  apps/api-videos/src/libs/arclight/arclight.ts
  apps/watch/__generated__/GetHomeVideo.ts
  apps/watch/__generated__/GetVideo.ts
  apps/watch/__generated__/GetVideoSiblings.ts
  apps/watch/__generated__/GetVideos.ts
  apps/watch/pages/[...slug].tsx
  apps/watch/pages/index.tsx
  apps/watch/src/components/HomeVideos/Card/HomeVideoCard.spec.tsx
  apps/watch/src/components/HomeVideos/Card/HomeVideoCard.tsx
  apps/watch/src/components/HomeVideos/testData.ts
  apps/watch/src/components/Video/VideoCard/VideoCard.tsx
  apps/watch/src/components/Videos/Videos.tsx
  apps/watch/src/components/Videos/testData.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#1116 fix: api video seed
  apps/api-videos/src/libs/arclight/arclight.spec.ts
  apps/api-videos/src/libs/arclight/arclight.ts
Labels: effort: 2, type: fix, priority: now, on stage

#1117 feat: variant slug nav
  apps/watch/__generated__/GetHomeVideo.ts
  apps/watch/__generated__/GetVideo.ts
  apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
  apps/watch/__generated__/GetVideoContent.ts
  apps/watch/__generated__/GetVideoSiblings.ts
  apps/watch/__generated__/GetVideos.ts
  apps/watch/__generated__/VideoChildFields.ts
  apps/watch/__generated__/VideoContentFields.ts
  apps/watch/pages/[...slug].tsx
  apps/watch/pages/[part1]/[part2].tsx
  apps/watch/pages/[part1]/[part2]/[part3].tsx
  apps/watch/pages/index.tsx
  apps/watch/src/components/Hero/SimpleHero/SimpleHero.tsx
  apps/watch/src/components/Hero/VideoHero/VideoHero.tsx
  apps/watch/src/components/HomeVideos/Card/HomeVideoCard.spec.tsx
  apps/watch/src/components/HomeVideos/Card/HomeVideoCard.stories.tsx
  apps/watch/src/components/HomeVideos/Card/HomeVideoCard.tsx
  apps/watch/src/components/HomeVideos/HomeVideos.spec.tsx
  apps/watch/src/components/HomeVideos/HomeVideos.stories.tsx
  apps/watch/src/components/HomeVideos/HomeVideos.tsx
  apps/watch/src/components/HomeVideos/testData.ts
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.tsx
  apps/watch/src/components/Video/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideoContainer/VideoContainer.stories.tsx
  apps/watch/src/components/VideoContainer/VideoContainer.tsx
  apps/watch/src/components/VideoContainer/VideoContainter.spec.tsx
  apps/watch/src/components/VideoContainer/index.ts
  apps/watch/src/components/Videos/Videos.tsx
  apps/watch/src/components/Videos/VideosCarousel/VideosCarousel.tsx
  apps/watch/src/components/Videos/VideosGrid/VideosGrid.tsx
  apps/watch/src/components/Videos/testData.ts
  apps/watch/src/libs/videoChildFields.ts
  apps/watch/src/libs/videoContentFields.ts
Labels: priority: now, effort: 13, type: refactor

#1119 refactor: split out container and content pages
  apps/watch/pages/[part1]/[part2].tsx
  apps/watch/pages/[part1]/[part2]/[part3].tsx
  apps/watch/src/components/PageWrapper/PageWrapper.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.tsx
  apps/watch/src/components/VideoContainer/VideoContainer.stories.tsx
  apps/watch/src/components/VideoContainer/VideoContainer.tsx
  apps/watch/src/components/VideoContainer/VideoContainter.spec.tsx
  apps/watch/src/components/VideoContainer/index.ts
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.spec.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.stories.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
  apps/watch/src/components/VideoContainerPage/index.ts
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  apps/watch/src/components/VideoContentPage/index.ts
Labels: priority: 2day, effort: 2, type: refactor

#1122 refactor: home page refactor
  apps/watch/__generated__/GetHomeVideo.ts
  apps/watch/pages/[part1]/[part2]/[part3].tsx
  apps/watch/pages/index.tsx
  apps/watch/src/components/Footer/Footer.tsx
  apps/watch/src/components/Hero/index.ts
  apps/watch/src/components/HomePage/HomeHero/HomeHero.spec.tsx
  apps/watch/src/components/HomePage/HomeHero/HomeHero.stories.tsx
  apps/watch/src/components/HomePage/HomeHero/HomeHero.tsx
  apps/watch/src/components/HomePage/HomeHero/index.ts
  apps/watch/src/components/HomePage/HomePage.stories.tsx
  apps/watch/src/components/HomePage/HomePage.tsx
  apps/watch/src/components/HomePage/HomeVideos/Card/HomeVideoCard.spec.tsx
  apps/watch/src/components/HomePage/HomeVideos/Card/HomeVideoCard.stories.tsx
  apps/watch/src/components/HomePage/HomeVideos/Card/HomeVideoCard.tsx
  apps/watch/src/components/HomePage/HomeVideos/Card/index.ts
  apps/watch/src/components/HomePage/HomeVideos/HomeVideos.spec.tsx
  apps/watch/src/components/HomePage/HomeVideos/HomeVideos.stories.tsx
  apps/watch/src/components/HomePage/HomeVideos/HomeVideos.tsx
  apps/watch/src/components/HomePage/HomeVideos/index.ts
  apps/watch/src/components/HomePage/index.ts
  apps/watch/src/components/HomeVideos/HomeVideos.tsx
  apps/watch/src/components/IntroText/IntroText.spec.tsx
  apps/watch/src/components/IntroText/IntroText.stories.tsx
  apps/watch/src/components/IntroText/IntroText.tsx
  apps/watch/src/components/IntroText/index.ts
Labels: effort: 3, priority: soon, type: refactor

#1115 fix: change feedback label and hint max length
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/Hint/Hint.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/Hint/Hint.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/Label/Label.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/Label/Label.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#1084 feat: add collection hero
  apps/watch/public/grain-texture.svg
  apps/watch/src/components/Hero/SimpleHero/SimpleHero.tsx
  apps/watch/src/components/Hero/VideoHero/index.ts
  apps/watch/src/components/Hero/index.ts
  apps/watch/src/components/HeroOverlay/HeroOverlay.stories.tsx
  apps/watch/src/components/HeroOverlay/HeroOverlay.tsx
  apps/watch/src/components/HeroOverlay/index.ts
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.spec.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.stories.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/index.ts
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.spec.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
Labels: effort: 2, priority: soon, type: feat

#1124 feat: get all video language variants api
  apps/api-gateway/schema.graphql
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.module.ts
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
Labels: priority: now, type: feat, effort: 1, on stage

#1127 fix: hero story paths
  apps/watch/src/components/HeroOverlay/HeroOverlay.stories.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.stories.tsx
Labels: type: fix, priority: soon, effort: 1

#1130 feat: create video context
  apps/watch/pages/[part1]/[part2].tsx
  apps/watch/pages/[part1]/[part2]/[part3].tsx
  apps/watch/src/components/Hero/VideoHero/VideoHero.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.spec.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.stories.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  apps/watch/src/libs/videoContext/VideoContext.spec.tsx
  apps/watch/src/libs/videoContext/VideoContext.tsx
  apps/watch/src/libs/videoContext/index.ts
Labels: priority: 2day, effort: 2, type: feat

#1090 feat: collection description component
  apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.spec.tsx
  apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.stories.tsx
  apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.tsx
  apps/watch/src/components/VideoContainerPage/ContainerDescription/index.ts
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.spec.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
Labels: effort: 2, priority: soon, type: feat

#1126 feat: videos page
  apps/watch/pages/videos.tsx
  apps/watch/public/images/videos-hero.png
  apps/watch/src/components/Videos/Videos.spec.tsx
  apps/watch/src/components/Videos/index.ts
  apps/watch/src/components/VideosGrid/VideosGrid.spec.tsx
  apps/watch/src/components/VideosGrid/VideosGrid.tsx
  apps/watch/src/components/VideosPage/Hero/VideosHero.tsx
  apps/watch/src/components/VideosPage/Hero/index.ts
  apps/watch/src/components/VideosPage/SubHero/VideosSubHero.tsx
  apps/watch/src/components/VideosPage/SubHero/index.ts
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.stories.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
  apps/watch/src/components/VideosPage/index.ts
Labels: effort: 2, priority: soon, type: feat

#1139 feat: watch videos preload
  apps/watch/pages/_app.tsx
  apps/watch/pages/videos.tsx
  apps/watch/src/components/VideosPage/SubHero/VideosSubHero.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
  apps/watch/src/libs/client/client.ts
  apps/watch/src/libs/client/index.ts
Labels: effort: 5, priority: soon, type: feat, on stage

#1140 test: add test video content
  apps/watch/src/components/VideoContentPage/VideoContent/VideoContent.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoContent/VideoContent.tsx
Labels: type: test, priority: soon, effort: 1

#1135 feat: container hero opens share dialog
  apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.spec.tsx
  apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.stories.tsx
  apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.spec.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.stories.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
Labels: priority: soon, type: feat, effort: 1

#1113 fix: remove nullable video from query
  apps/api-gateway/schema.graphql
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/journeys-admin/__generated__/GetVideo.ts
  apps/journeys-admin/__generated__/GetVideoVariantLanguages.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
  apps/watch/__generated__/GetHomeVideo.ts
  apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
  apps/watch/__generated__/GetVideoContent.ts
Labels: effort: 2, type: fix, priority: now

#1141 fix: only show seo title and description
  apps/journeys/pages/[journeySlug].tsx
Labels: type: fix, priority: now, effort: 1

#1142 feat: add ids filter to videos api
  apps/api-gateway/schema.graphql
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
Labels: effort: 2, priority: now, type: feat, on stage

#1147 refactor: use single query for watch home
  apps/api-videos/db/seed.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  apps/watch/__generated__/GetHomeVideos.ts
  apps/watch/pages/index.tsx
  apps/watch/src/components/HomePage/HomeVideos/HomeVideos.tsx
  package-lock.json
  package.json
Labels: priority: now, effort: 1, type: refactor, on stage

#1078 feat: ecs complete deployment
  .github/vpn/main.ovpn
  .github/vpn/stage.ovpn
  .github/workflows/api-deploy-prod.yml
  .github/workflows/api-deploy-stage.yml
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-prod-worker.yml
  .github/workflows/api-gateway-stage-worker.yml
  apps/api-gateway/infrastructure/locals.tf
  apps/api-gateway/infrastructure/variables.tf
  apps/api-gateway/supergraph-main-ecs.yml
  apps/api-gateway/supergraph-stage-ecs.yml
  apps/api-journeys/infrastructure/locals.tf
  apps/api-journeys/infrastructure/variables.tf
  apps/api-languages/infrastructure/locals.tf
  apps/api-languages/infrastructure/variables.tf
  apps/api-users/infrastructure/locals.tf
  apps/api-users/infrastructure/variables.tf
  apps/api-videos/infrastructure/locals.tf
  apps/api-videos/infrastructure/variables.tf
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/data.tf
  infrastructure/environments/stage/main.tf
  infrastructure/main.tf
  infrastructure/modules/aws/alb/outputs.tf
  infrastructure/modules/aws/ecs-task/main.tf
  infrastructure/modules/aws/ecs-task/terraform.tf
  infrastructure/modules/aws/ecs-task/variables.tf
  infrastructure/modules/aws/iam/main.tf
  infrastructure/modules/aws/locals.tf
  infrastructure/modules/aws/main.tf
  infrastructure/modules/aws/outputs.tf
  infrastructure/modules/aws/variables.tf
Labels: effort: 3, priority: soon, type: feat, on stage

#1150 fix: home grid to match designs
  apps/watch/next.config.js
  apps/watch/pages/_app.tsx
  apps/watch/pages/index.tsx
  apps/watch/public/fonts/fonts.css
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx
  apps/watch/src/components/HomePage/HomeVideos/Card/HomeVideoCard.spec.tsx
  apps/watch/src/components/HomePage/HomeVideos/Card/HomeVideoCard.tsx
  apps/watch/src/components/HomePage/HomeVideos/Card/index.ts
  apps/watch/src/components/HomePage/HomeVideos/HomeVideos.tsx
  libs/shared/ui/src/libs/timeFormat/timeFormat.ts
Labels: type: fix, priority: now, effort: 1

#1144 feat: api videos subtitle filter
  apps/api-gateway/schema.graphql
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
Labels: effort: 5, priority: soon, type: feat, on stage

#1128 refactor: move language select to shared ui
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLanguage/VideoLanguage.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLanguage/VideoLanguage.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/LanguageDialog/LanguageDialog.tsx
  apps/journeys-admin/src/components/LanguageSelect/LanguageSelect.tsx
  apps/journeys-admin/src/components/LanguageSelect/index.ts
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.spec.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.stories.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/index.ts
  libs/shared/ui/src/libs/themes/base/tokens/components.stories.tsx
  libs/shared/ui/src/libs/themes/website/tokens/components.stories.tsx
  libs/shared/ui/src/libs/themes/website/tokens/components.tsx
Labels: effort: 3, priority: soon, type: refactor

#1145 fix: label for nested collections
  apps/watch/src/components/HomePage/HomeVideos/Card/HomeVideoCard.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.spec.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.stories.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
  apps/watch/src/libs/utils/getLabelDetails/getLabelDetails.spec.ts
  apps/watch/src/libs/utils/getLabelDetails/getLabelDetails.ts
Labels: effort: 2, type: fix, priority: soon

#1118 feat: collections video grid
  apps/watch/pages/[part1]/[part2].tsx
  apps/watch/src/components/HomePage/HomePage.stories.tsx
  apps/watch/src/components/HomePage/HomePage.tsx
  apps/watch/src/components/HomePage/HomeVideos/Card/HomeVideoCard.spec.tsx
  apps/watch/src/components/HomePage/HomeVideos/Card/HomeVideoCard.stories.tsx
  apps/watch/src/components/HomePage/HomeVideos/Card/HomeVideoCard.tsx
  apps/watch/src/components/HomePage/HomeVideos/Card/index.ts
  apps/watch/src/components/HomePage/HomeVideos/HomeVideos.spec.tsx
  apps/watch/src/components/HomePage/HomeVideos/HomeVideos.stories.tsx
  apps/watch/src/components/HomePage/HomeVideos/HomeVideos.tsx
  apps/watch/src/components/HomePage/HomeVideos/index.ts
  apps/watch/src/components/VideoCard/VideoCard.spec.tsx
  apps/watch/src/components/VideoCard/VideoCard.stories.tsx
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideoCard/index.ts
  apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.stories.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.spec.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.stories.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
  apps/watch/src/components/VideoGrid/VideoGrid.spec.tsx
  apps/watch/src/components/VideoGrid/VideoGrid.stories.tsx
  apps/watch/src/components/VideoGrid/VideoGrid.tsx
  apps/watch/src/components/VideoGrid/index.ts
  apps/watch/src/components/VideosGrid/VideosGrid.spec.tsx
  apps/watch/src/components/VideosGrid/VideosGrid.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
  apps/watch/src/libs/utils/getLabelDetails/getLabelDetails.spec.ts
  apps/watch/src/libs/utils/getLabelDetails/getLabelDetails.ts
  libs/shared/ui/src/libs/timeFormat/timeFormat.spec.ts
Labels: effort: 5, priority: soon, type: feat

#1107 feat: watch download
  apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
  apps/watch/__generated__/GetVideoContent.ts
  apps/watch/__generated__/VideoContentFields.ts
  apps/watch/__generated__/globalTypes.ts
  apps/watch/src/components/DownloadDialog/DownloadDialog.spec.tsx
  apps/watch/src/components/DownloadDialog/DownloadDialog.stories.tsx
  apps/watch/src/components/DownloadDialog/DownloadDialog.tsx
  apps/watch/src/components/DownloadDialog/index.ts
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  apps/watch/src/components/Videos/testData.ts
  apps/watch/src/libs/videoContentFields.ts
  apps/watch/src/libs/videoContext/VideoContext.spec.tsx
  libs/shared/ui/src/libs/themes/website/tokens/colors.ts
  libs/shared/ui/src/libs/themes/website/tokens/components.stories.tsx
  package-lock.json
  package.json
Labels: effort: 3, priority: soon, type: feat

#1096 feat: video hero overlay
  apps/watch/public/images/hero-texture.svg
  apps/watch/src/components/Hero/VideoHero/VideoHero.tsx
  apps/watch/src/components/Hero/index.ts
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/index.ts
  apps/watch/src/components/VideoContentPage/VideoHero/index.ts
Labels: effort: 2, priority: soon, type: feat

#1151 fix: home page optimizations
  apps/watch/pages/_app.tsx
  apps/watch/public/images/jesus-header.jpg
  apps/watch/public/images/jesus-header.svg
  apps/watch/src/components/Footer/Footer.tsx
  apps/watch/src/components/HomePage/HomeHero/HomeHero.spec.tsx
  apps/watch/src/components/HomePage/HomeHero/HomeHero.tsx
  apps/watch/src/components/HomePage/HomePage.tsx
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
  libs/shared/ui/src/libs/themes/website/tokens/colors.ts
Labels: type: fix, priority: now, effort: 1

#1093 feat: watch/api page
  apps/watch/__generated__/GetVideo.ts
  apps/watch/pages/api/jf/watch.html/[videoId]/[languageId].ts
Labels: effort: 5, priority: now, type: feat

#1155 fix: load and spacing on collections
  apps/watch/src/components/VideosPage/Hero/VideosHero.tsx
  apps/watch/src/components/VideosPage/SubHero/VideosSubHero.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
Labels: type: fix, priority: now, effort: 1

#1152 feat: homepage header for all videos page
  apps/watch/src/components/HomePage/HomePage.tsx
  apps/watch/src/components/HomePage/SeeAllVideos/SeeAllVideos.spec.tsx
  apps/watch/src/components/HomePage/SeeAllVideos/SeeAllVideos.stories.tsx
  apps/watch/src/components/HomePage/SeeAllVideos/SeeAllVideos.tsx
  apps/watch/src/components/HomePage/SeeAllVideos/index.ts
Labels: effort: 2, priority: soon, type: feat

#1143 feat: video hero player
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/index.ts
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
  libs/shared/ui/src/libs/timeFormat/timeFormat.spec.ts
  libs/shared/ui/src/libs/timeFormat/timeFormat.ts
Labels: effort: 5, priority: soon, type: feat

#1156 fix: home background, header and description
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx
  apps/watch/src/components/HomePage/HomeHero/HomeHero.tsx
  apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.tsx
  apps/watch/src/components/VideoContentPage/VideoContent/VideoContent.tsx
Labels: type: fix, priority: now, effort: 1

#1157 fix: remove shared process cache
  apps/watch/pages/[part1]/[part2].tsx
  apps/watch/pages/[part1]/[part2]/[part3].tsx
  apps/watch/pages/_app.tsx
  apps/watch/pages/api/jf/watch.html/[videoId]/[languageId].ts
  apps/watch/pages/index.tsx
  apps/watch/pages/videos.tsx
  apps/watch/src/libs/apolloClient/apolloClient.ts
  apps/watch/src/libs/apolloClient/cache.ts
  apps/watch/src/libs/apolloClient/index.ts
  apps/watch/src/libs/client/cache/cache.ts
  apps/watch/src/libs/client/cache/index.ts
  apps/watch/src/libs/client/client.ts
  apps/watch/src/libs/client/index.ts
Labels: type: fix, priority: now, effort: 1

#1163 fix: watch lighthouse performance above 90
  apps/watch/next-env.d.ts
  apps/watch/next.config.js
  apps/watch/pages/_app.tsx
  apps/watch/public/grain-texture.svg
  apps/watch/public/images/cru-logo.png
  apps/watch/public/images/grain-texture.svg
  apps/watch/public/images/hero-texture.svg
  apps/watch/public/images/jesus-footer.png
  apps/watch/public/images/jf-logo@2x.png
  apps/watch/src/components/Footer/FooterLinks/FooterLinks.tsx
  apps/watch/src/components/HeroOverlay/HeroOverlay.tsx
  apps/watch/src/components/HomePage/HomeHero/HomeHero.tsx
  apps/watch/src/components/HomePage/HomePage.tsx
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.tsx
  package-lock.json
Labels: type: fix, priority: now, effort: 1

#1164 refactor: watch reduce first load shared js to 112 kb
  apps/journeys-admin/pages/_app.tsx
  apps/journeys/pages/_app.tsx
  apps/watch-admin/pages/_app.tsx
  apps/watch-admin/pages/index.tsx
  apps/watch-admin/src/libs/apolloClient/apolloClient.ts
  apps/watch-admin/src/libs/apolloClient/index.ts
  apps/watch/next.config.js
  apps/watch/pages/[part1]/[part2].tsx
  apps/watch/pages/[part1]/[part2]/[part3].tsx
  apps/watch/pages/_app.tsx
  apps/watch/pages/videos.tsx
  apps/watch/src/components/VideoContainerPage/index.ts
  apps/watch/src/components/VideoContentPage/index.ts
  apps/watch/src/libs/apolloClient/apolloClient.ts
  package-lock.json
  package.json
Labels: type: fix, priority: now, effort: 1

#1131 feat: common video carousel
  .storybook/main.js
  .storybook/preview-head.html
  apps/watch/pages/_app.tsx
  apps/watch/public/styles/carousel.css
  apps/watch/public/styles/swiper-js.css
  apps/watch/src/components/Video/CarouselItem/CarouselItem.tsx
  apps/watch/src/components/Video/CarouselItem/index.ts
  apps/watch/src/components/Video/index.ts
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  apps/watch/src/components/Videos/VideosCarousel/VideosCarousel.tsx
  apps/watch/src/components/VideosCarousel/VideosCarousel.spec.tsx
  apps/watch/src/components/VideosCarousel/VideosCarousel.stories.tsx
  apps/watch/src/components/VideosCarousel/VideosCarousel.tsx
  apps/watch/src/components/VideosCarousel/VideosCarouselNavButton/VideosCarouselNavButton.stories.tsx
  apps/watch/src/components/VideosCarousel/VideosCarouselNavButton/VideosCarouselNavButton.tsx
  apps/watch/src/components/VideosCarousel/index.ts
  package-lock.json
  package.json
Labels: effort: 3, priority: soon, type: feat

#1082 fix: facebook/twitter cards not displaying
  apps/journeys/pages/_app.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  libs/locales/en/apps-journeys.json
Labels: type: fix, effort: 3, priority: soon

#1168 fix: video card hide slug link when video is series
  apps/watch/src/components/VideoCard/VideoCard.spec.tsx
  apps/watch/src/components/VideoCard/VideoCard.tsx
Labels: type: fix, priority: now, effort: 1

#1167 feat: fullscreen on watch now targets dom not video player
  apps/watch/pages/_app.tsx
  apps/watch/public/styles/video-js.css
  apps/watch/setupTests.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.tsx
  package-lock.json
  package.json
Labels: priority: now, type: feat, effort: 1

#1165 feat: tos modal
  apps/watch/src/components/DownloadDialog/DownloadDialog.spec.tsx
  apps/watch/src/components/DownloadDialog/DownloadDialog.tsx
  apps/watch/src/components/DownloadDialog/TermsOfUseModal/TermsOfUseModal.stories.tsx
  apps/watch/src/components/DownloadDialog/TermsOfUseModal/TermsOfUseModal.tsx
Labels: effort: 2, priority: soon, type: feat

#1171 feat: download button
  apps/watch/src/components/ShareButton/ShareButton.spec.tsx
  apps/watch/src/components/ShareButton/ShareButton.stories.tsx
  apps/watch/src/components/ShareButton/ShareButton.tsx
  apps/watch/src/components/ShareButton/index.ts
  apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.tsx
  apps/watch/src/components/VideoContainerPage/ShareButton/ShareButton.spec.tsx
  apps/watch/src/components/VideoContentPage/DownloadButton/DownloadButton.spec.tsx
  apps/watch/src/components/VideoContentPage/DownloadButton/DownloadButton.stories.tsx
  apps/watch/src/components/VideoContentPage/DownloadButton/DownloadButton.tsx
  apps/watch/src/components/VideoContentPage/DownloadButton/index.ts
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
Labels: effort: 3, priority: soon, type: feat

#1178 feat: hide pointer, page header, and controls after inactivity
  apps/watch/src/components/Header/Header.spec.tsx
  apps/watch/src/components/Header/Header.stories.tsx
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.spec.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx
  apps/watch/src/components/PageWrapper/PageWrapper.spec.tsx
  apps/watch/src/components/PageWrapper/PageWrapper.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
Labels: type: fix, priority: now, effort: 1

#1105 feat: audio modal
  apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
  apps/watch/__generated__/GetVideoContent.ts
  apps/watch/__generated__/VideoContentFields.ts
  apps/watch/src/components/AudioDialog/AudioLanguageDialog.spec.tsx
  apps/watch/src/components/AudioDialog/AudioLanguageDialog.stories.tsx
  apps/watch/src/components/AudioDialog/AudioLanguageDialog.tsx
  apps/watch/src/components/AudioDialog/index.ts
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
  apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.spec.tsx
  apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.tsx
  apps/watch/src/components/VideoContentPage/AudioLanguageButton/index.ts
  apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.tsx
  apps/watch/src/components/Videos/testData.ts
  apps/watch/src/libs/videoContentFields.ts
  apps/watch/src/libs/videoContext/VideoContext.spec.tsx
Labels: effort: 3, priority: now, type: feat

#1180 fix: audio dialog language null check
  apps/watch/src/components/AudioDialog/AudioLanguageDialog.tsx
  apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.tsx
Labels: type: fix, priority: now, effort: 1

#1134 fix: change the copy of journey-delete-dialog message
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/TrashJourneyDialog/TrashJourneyDialog.tsx
Labels: effort: 5, type: fix, priority: soon

#1136 fix: difficulties editing text
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
Labels: effort: 5, type: fix, priority: soon

#1179 fix: added chapter variant
  apps/watch/src/components/VideoCard/VideoCard.stories.tsx
Labels: priority: 2day, type: fix, effort: 1

#1060 docs: add instructions for services setup
  apps/docs/docs/05-team/06-getting-started.md
Labels: type: docs, priority: soon, effort: 1

#1109 feat: lang switch
  apps/watch/__generated__/GetHomeVideos.ts
  apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
  apps/watch/__generated__/GetVideoContent.ts
  apps/watch/__generated__/GetVideos.ts
  apps/watch/__generated__/VideoChildFields.ts
  apps/watch/__generated__/VideoContentFields.ts
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.spec.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.stories.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.tsx
  apps/watch/src/components/SubtitleDialog/index.ts
  apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
  apps/watch/src/components/Videos/testData.ts
  apps/watch/src/libs/videoChildFields.ts
  apps/watch/src/libs/videoContentFields.ts
  apps/watch/src/libs/videoContext/VideoContext.spec.tsx
Labels: effort: 3, priority: soon, type: feat

#1080 docs: setting goals
  apps/docs/docs/05-team/06-making-a-career/setting-goals.md
Labels: effort: 2, type: docs, priority: soon

#1181 feat: cache pages at build time
  apps/watch/next.config.js
  apps/watch/pages/[part1]/[part2].tsx
  apps/watch/pages/[part1]/[part2]/[part3].tsx
  apps/watch/pages/index.tsx
  apps/watch/pages/videos.tsx
  apps/watch/src/libs/apolloClient/apolloClient.ts
Labels: priority: now, type: feat, effort: 1

#1182 fix: label details
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.tsx
  apps/watch/src/libs/utils/getLabelDetails/getLabelDetails.spec.ts
  apps/watch/src/libs/utils/getLabelDetails/getLabelDetails.ts
Labels: priority: 2day, effort: 2, type: fix

#1177 feat: video content carousel
  apps/watch/public/styles/swiper-js.css
  apps/watch/src/components/VideoCard/VideoCard.spec.tsx
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/index.ts
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
  apps/watch/src/components/VideosCarousel/VideosCarousel.spec.tsx
  apps/watch/src/components/VideosCarousel/VideosCarousel.stories.tsx
  apps/watch/src/components/VideosCarousel/VideosCarousel.tsx
  apps/watch/src/components/VideosCarousel/VideosCarouselNavButton/VideosCarouselNavButton.tsx
  apps/watch/src/libs/utils/getLabelDetails/getLabelDetails.spec.ts
  apps/watch/src/libs/utils/getLabelDetails/getLabelDetails.ts
Labels: priority: 2day, effort: 3, type: feat

#1064 fix: clear video
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.tsx
Labels: effort: 5, type: fix, priority: now

#1189 fix: controls on android and loading icon
  apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
Labels: effort: 2, type: fix, priority: now

#1192 feat: overlay buttons
  apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.spec.tsx
  apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.tsx
Labels: effort: 2, priority: now, type: feat

#1190 fix: videos content carousel
  apps/watch/public/styles/swiper-js.css
  apps/watch/src/components/Video/CarouselItem/CarouselItem.tsx
  apps/watch/src/components/Video/CarouselItem/index.ts
  apps/watch/src/components/Video/VideoCard/VideoCard.tsx
  apps/watch/src/components/Video/index.ts
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  apps/watch/src/components/VideosCarousel/VideosCarousel.tsx
Labels: priority: 2day, effort: 2, type: fix

#1098 fix: responsive typography
  libs/shared/ui/src/libs/themes/website/theme.ts
  libs/shared/ui/src/libs/themes/website/tokens/typography.ts
Labels: priority: 2day, effort: 2, type: fix

#1191 feat: increase api-video container cpu and mem
  apps/api-videos/infrastructure/locals.tf
Labels: priority: now, type: feat, effort: 1

#1153 feat: all videos language filter
  apps/watch/__generated__/GetLanguages.ts
  apps/watch/pages/videos.tsx
  apps/watch/src/components/VideosPage/CurrentFilters/CurrentFilters.spec.tsx
  apps/watch/src/components/VideosPage/CurrentFilters/CurrentFilters.stories.tsx
  apps/watch/src/components/VideosPage/CurrentFilters/CurrentFilters.tsx
  apps/watch/src/components/VideosPage/CurrentFilters/index.ts
  apps/watch/src/components/VideosPage/LanguagesFilter/LanguagesFilter.spec.tsx
  apps/watch/src/components/VideosPage/LanguagesFilter/LanguagesFilter.stories.tsx
  apps/watch/src/components/VideosPage/LanguagesFilter/LanguagesFilter.tsx
  apps/watch/src/components/VideosPage/LanguagesFilter/index.ts
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
  apps/watch/src/components/VideosPage/testData.ts
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/index.ts
  package-lock.json
  package.json
Labels: effort: 3, priority: soon, type: feat

#1193 feat: getstaticprops languages
  apps/watch/pages/videos.tsx
Labels: priority: now, type: feat, effort: 1
