Repository JesusFilm/core, pull requests merged in 2022-08, with the labels that each got.

#798 fix: journeys language overflow
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockCreate.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockUpdate.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetVideoVariantLanguages.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/VideoBlockCreate.ts
  apps/journeys-admin/__generated__/VideoBlockUpdate.ts
  apps/journeys-admin/__generated__/VideoFields.ts
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/VideoFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.stories.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.spec.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/journeys/ui/src/components/Video/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/Video/videoFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
Labels: type: fix, effort: 3, priority: now

#792 feat: create template events
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/event.module.ts
  apps/api-journeys/src/app/modules/event/template/template.graphql
  apps/api-journeys/src/app/modules/event/template/template.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/template/template.resolver.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#800 feat: fetch public templates
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.service.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.service.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#805 fix: extend role guard
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/lib/roleGuard/roleGuard.spec.ts
  apps/api-journeys/src/app/lib/roleGuard/roleGuard.ts
  apps/api-journeys/src/app/modules/action/action.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.module.ts
  apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/card/card.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/gridContainer/gridContainer.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/gridItem/gridItem.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/icon/icon.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/image/image.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/typography/typography.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/videoTrigger/videoTrigger.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: type: fix, effort: 13, priority: soon

#807 fix: handling blockId duplication
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
Labels: type: fix, priority: now, effort: 1

#808 fix: fetch public templates
  apps/api-journeys/src/app/modules/journey/journey.service.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.service.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#802 feat: fetch publisher templates
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/journey/journey.service.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.service.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#803 feat: add user journey remove all
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.graphql
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.ts
  libs/nest/database/src/lib/BaseService.ts
Labels: effort: 3, priority: soon, type: feat

#794 feat: create journeyTemplate - makes a journey a template or not
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: effort: 5, priority: soon, type: feat, on stage

#810 fix: admin journey query
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: effort: 2, type: fix, priority: now

#812 fix: publisher templates fetch
  apps/api-journeys/src/app/modules/journey/journey.service.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.service.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#818 fix: window external link
  libs/journeys/ui/src/libs/action/action.spec.ts
  libs/journeys/ui/src/libs/action/action.ts
Labels: type: fix, priority: now, effort: 1

#819 style: add two new jsx rules
  .eslintrc.json
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.spec.tsx
  apps/journeys-admin/src/components/Dialog/Dialog.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateAction/NavigateAction.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attribute/Attribute.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Icon/Color/Color.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Icon/Icon.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/Swatch/Swatch.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Conditions/Conditions.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLanguage/VideoLanguage.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/ArchiveJourney/ArchiveJourney.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DeleteJourneyDialog/DeleteJourneyDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/RestoreJourneyDialog/RestoreJourneyDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/TrashJourneyDialog/TrashJourneyDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneySort/JourneySort.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneySort/JourneySort.stories.tsx
  apps/journeys-admin/src/components/LanguageSelect/LanguageSelect.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/UserMenu.spec.tsx
  apps/journeys-admin/src/components/SignIn/SignIn.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/watch-admin/src/components/PageWrapper/PageWrapper.tsx
  apps/watch-admin/src/components/SignIn/SignIn.tsx
  apps/watch/src/components/PageWrapper/PageWrapper.tsx
  apps/watch/src/components/ThemeProvider/ThemeProvider.stories.tsx
  apps/watch/src/components/Videos/VideoList/Card/VideoListCard.tsx
  apps/watch/src/components/Videos/VideoList/Grid/VideoListGrid.spec.tsx
  apps/watch/src/components/Videos/VideoList/List/VideoListList.spec.tsx
  apps/watch/src/components/Videos/VideoList/List/VideoListList.tsx
  libs/journeys/ui/src/components/Button/Button.stories.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Icon/Icon.stories.tsx
  libs/journeys/ui/src/components/Icon/Icon.tsx
  libs/journeys/ui/src/components/Image/Image.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/Typography/Typography.stories.tsx
  libs/journeys/ui/src/components/Typography/Typography.tsx
  libs/shared/ui/src/components/CopyTextField/CopyTextField.spec.tsx
  libs/shared/ui/src/libs/themes/base/theme.stories.tsx
Labels: priority: now, effort: 1, type: style

#820 refactor: properties components
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/AccessControl/AccessControl.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/AccessControl/AccessControl.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/AccessControl/index.ts
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/EmbedJourneyDialog/EmbedCardPreview/EmbedCardPreview.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/EmbedJourneyDialog/EmbedCardPreview/index.ts
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/EmbedJourneyDialog/index.ts
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/JourneyLink.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/JourneyLink.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/SlugDialog/SlugDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/SlugDialog/SlugDialog.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/SlugDialog/SlugDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/SlugDialog/index.ts
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/index.ts
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, effort: 1, type: refactor

#822 fix: journey template roleguard argument
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: type: fix, priority: now, effort: 1

#821 fix: journey null case
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/utils/getDuplicatedJourney.ts
Labels: type: fix, priority: soon, effort: 1

#813 feat: journey to template
  apps/journeys-admin/__generated__/CreateTemplate.ts
  apps/journeys-admin/__generated__/DuplicateJourney.ts
  apps/journeys-admin/__generated__/GetRole.ts
  apps/journeys-admin/__generated__/RemoveUserJourney.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/__generated__/journeyTemplate.ts
  apps/journeys-admin/src/components/JourneyView/Menu/CreateTemplateMenuItem/CreateTemplateMenuItem.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/CreateTemplateMenuItem/CreateTemplateMenuItem.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/CreateTemplateMenuItem/index.ts
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
Labels: effort: 2, priority: now, type: feat

#790 feat: add single journey report filter
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/src/components/DynamicPowerBiReport/Report/Report.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.spec.tsx
Labels: effort: 2, priority: soon, type: feat

#834 fix: role guard logic
  apps/api-journeys/src/app/lib/roleGuard/roleGuard.ts
Labels: type: fix, priority: now, effort: 1

#836 fix: mutations to do a roleguard publisher check
  apps/api-journeys/src/app/modules/action/action.resolver.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.ts
  apps/api-journeys/src/app/modules/block/block.resolver.ts
  apps/api-journeys/src/app/modules/block/button/button.resolver.ts
  apps/api-journeys/src/app/modules/block/card/card.resolver.ts
  apps/api-journeys/src/app/modules/block/icon/icon.resolver.ts
  apps/api-journeys/src/app/modules/block/image/image.resolver.ts
  apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.ts
  apps/api-journeys/src/app/modules/block/step/step.resolver.ts
  apps/api-journeys/src/app/modules/block/typography/typography.resolver.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Labels: type: fix, priority: now, effort: 1

#835 fix: fetch journey.template, userJourney.role and userRole.userId
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetRole.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
  apps/journeys-admin/src/components/JourneyView/data.ts
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/libs/JourneyProvider/JourneyProvider.spec.tsx
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/journeyFields.tsx
Labels: priority: 2day, effort: 2, type: fix

#838 fix: editor journey settings link
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
Labels: type: fix, priority: soon, effort: 1

#829 refactor: nav menu icons
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.spec.tsx
Labels: priority: soon, effort: 1, type: refactor
