Repository JesusFilm/core, pull requests merged in 2022-01, with the labels that each got.

#159 Feature: Single Journey Page
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/JourneyDescUpdate.ts
  apps/journeys-admin/__generated__/JourneyPublish.ts
  apps/journeys-admin/__generated__/JourneyTitleUpdate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/journeys/[journeySlug].tsx
  apps/journeys-admin/src/components/InviteUserModal/InviteUserModal.stories.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/data.ts
  apps/journeys-admin/src/components/JourneyView/CardView/index.ts
  apps/journeys-admin/src/components/JourneyView/Context/Context.tsx
  apps/journeys-admin/src/components/JourneyView/Context/index.ts
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Alert/Alert.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Alert/Alert.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Alert/index.ts
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/index.ts
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/index.ts
  apps/journeys-admin/src/components/JourneyView/Menu/index.ts
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/JourneyDetails.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/JourneyDetails.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/index.ts
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/index.ts
  apps/journeys-admin/src/components/JourneyView/ShareSection/ShareSection.spec.tsx
  apps/journeys-admin/src/components/JourneyView/ShareSection/ShareSection.stories.tsx
  apps/journeys-admin/src/components/JourneyView/ShareSection/ShareSection.tsx
  apps/journeys-admin/src/components/JourneyView/ShareSection/index.ts
  apps/journeys-admin/src/components/JourneyView/data.ts
  apps/journeys-admin/src/components/JourneyView/index.ts
  apps/journeys-admin/src/components/JourneysAppBar/JourneysAppBar.spec.tsx
  apps/journeys-admin/src/components/JourneysAppBar/JourneysAppBar.stories.tsx
  apps/journeys-admin/src/components/JourneysAppBar/JourneysAppBar.tsx
  apps/journeys-admin/src/components/ThemeProvider/admin/tokens/colors.ts
  apps/journeys-admin/src/components/ThemeProvider/admin/tokens/components.ts
  apps/journeys-admin/src/components/index.ts
  apps/journeys-admin/src/libs/storybook/config.tsx
  libs/shared/ui/src/libs/themes/base/tokens/breakpoints.ts
Labels: feature branch

#180 fix response collection creation
  apps/api-journeys/db/seed.ts
Labels: bug

#173 Arangodb cloud deploy
  .devcontainer/docker-compose.yml
  .devcontainer/post-create-command.sh
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-deploy.yml
  .github/workflows/api-gateway-worker.yml
  .gitignore
  .kube/config
  .vscode/settings.json
  apps/api-gateway/.env.example
  apps/api-gateway/Dockerfile
  apps/api-gateway/project.json
  apps/api-gateway/src/environments/environment.prod.ts
  apps/api-gateway/supergraph-main.yml
  apps/api-gateway/supergraph-stage.yml
  apps/api-journeys/.env.example
  apps/api-journeys/Dockerfile
  apps/api-journeys/db/db.ts
  apps/api-journeys/db/seed.ts
  apps/api-journeys/db/seeds/nua1.ts
  apps/api-journeys/db/seeds/nua2.ts
  apps/api-journeys/db/seeds/nua8.ts
  apps/api-journeys/db/seeds/nua9.ts
  apps/api-journeys/project.json
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/main.ts
  apps/api-users/.env.example
  apps/api-users/Dockerfile
  apps/api-users/db/db.ts
  apps/api-users/db/seed.ts
  apps/api-users/project.json
  apps/api-users/src/app/app.module.ts
  apps/api-users/src/main.ts
  libs/nest/database/src/lib/database.providers.ts
  libs/nest/database/tsconfig.json
  package-lock.json
  package.json
  resources/kube/api/api-gateway-main-deployment.yaml
  resources/kube/api/api-gateway-stage-deployment.yaml
  resources/kube/api/api-journeys-main-deployment.yaml
  resources/kube/api/api-journeys-stage-deployment.yaml
  resources/kube/api/api-users-main-deployment.yaml
  resources/kube/api/api-users-stage-deployment.yaml
  resources/kube/api/deploy-main.sh
  resources/kube/api/deploy-stage.sh
  resources/kube/arangodb/arangodb-deployment.yaml
  resources/kube/arangodb/deploy.sh
  resources/kube/aws-auth-cm.yaml
  resources/kube/dashboard/admin-user.yaml
  resources/kube/dashboard/deploy.sh
  resources/kube/ssl/alb-ingress-controller.yaml
  resources/kube/ssl/alb-rbac-role.yaml
  resources/kube/ssl/deploy.sh
  resources/kube/ssl/external-dns.yaml
Labels: enhancement, backend

#175 Fix flakey UI tests
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/journeys/src/components/blocks/Card/Card.stories.tsx
  libs/journeys/ui/src/components/Card/Card.stories.tsx
Labels: enhancement

#181 add version to githubworkflow
  .github/workflows/api-deploy.yml
Labels: bug

#179 Run VR test only if lint, build, test passing
  .github/workflows/main.yml
Labels: enhancement, tool

#184 speed up journey load time
  apps/journeys/__generated__/GetJourneySlugs.ts
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/pages/index.tsx
Labels: journeys

#188 move user journey seed and remove double awaits
  apps/api-journeys/db/seed.ts
  apps/api-users/db/seed.ts
Labels: invalid

#127 Access Avatars component
  apps/journeys-admin/__generated__/GetJourneys.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/journeys/index.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/AccessAvatars/AccessAvatars.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/AccessAvatars/AccessAvatars.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/AccessAvatars/AccessAvatars.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/AccessAvatars/data.ts
  apps/journeys-admin/src/components/JourneyList/JourneyCard/AccessAvatars/index.ts
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
  apps/journeys-admin/src/components/JourneyList/journeyListData.ts
Labels: component, journeys-admin

#186 fix UserJourney user object
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.graphql
  apps/api-users/schema.graphql
  apps/api-users/src/app/__generated__/graphql.ts
  apps/api-users/src/app/modules/user/user.graphql
  apps/api-users/src/app/modules/user/user.resolver.spec.ts
  apps/api-users/src/app/modules/user/user.resolver.ts
  apps/api-users/src/app/modules/user/user.service.spec.ts
  apps/api-users/src/app/modules/user/user.service.ts
Labels: bug

#199 update block update resolvers
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/lib/roleGuard/roleGuard.ts
  apps/api-journeys/src/app/modules/block/block.graphql
  apps/api-journeys/src/app/modules/block/button/button.graphql
  apps/api-journeys/src/app/modules/block/card/card.graphql
  apps/api-journeys/src/app/modules/block/card/card.resolvers.spec.ts
  apps/api-journeys/src/app/modules/block/card/card.resolvers.ts
  apps/api-journeys/src/app/modules/block/gridContainer/gridContainer.graphql
  apps/api-journeys/src/app/modules/block/gridItem/gridItem.graphql
  apps/api-journeys/src/app/modules/block/image/image.graphql
  apps/api-journeys/src/app/modules/block/image/image.resolvers.spec.ts
  apps/api-journeys/src/app/modules/block/image/image.resolvers.ts
  apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.graphql
  apps/api-journeys/src/app/modules/block/signUp/signUp.graphql
  apps/api-journeys/src/app/modules/block/step/step.graphql
  apps/api-journeys/src/app/modules/block/step/step.resolvers.spec.ts
  apps/api-journeys/src/app/modules/block/step/step.resolvers.ts
  apps/api-journeys/src/app/modules/block/typography/typography.graphql
  apps/api-journeys/src/app/modules/block/video/video.graphql
  apps/api-journeys/src/app/modules/block/video/video.resolvers.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolvers.ts
  apps/api-journeys/src/app/modules/block/videoTrigger/videoTrigger.graphql
  apps/journeys/next-env.d.ts
Labels: feature branch

#193 Attributes for typography block
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Button/Button.tsx
Labels: frontend

#218 add pageWrapper and favicon
  apps/journeys-admin/pages/_document.tsx
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/journeys/[journeySlug].tsx
  apps/journeys-admin/pages/journeys/[journeySlug]/edit.tsx
  apps/journeys-admin/public/.gitkeep
  apps/journeys-admin/public/android-chrome-192x192.png
  apps/journeys-admin/public/android-chrome-512x512.png
  apps/journeys-admin/public/apple-touch-icon.png
  apps/journeys-admin/public/favicon-16x16.png
  apps/journeys-admin/public/favicon.ico
  apps/journeys-admin/public/site.webmanifest
  apps/journeys-admin/public/taskbar-icon.svg
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.tsx
  apps/journeys-admin/src/components/Editor/TopBar/TopBar.spec.tsx
  apps/journeys-admin/src/components/Editor/TopBar/TopBar.stories.tsx
  apps/journeys-admin/src/components/Editor/TopBar/TopBar.tsx
  apps/journeys-admin/src/components/Editor/TopBar/index.ts
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.tsx
  apps/journeys-admin/src/components/JourneysAppBar/JourneysAppBar.spec.tsx
  apps/journeys-admin/src/components/JourneysAppBar/JourneysAppBar.stories.tsx
  apps/journeys-admin/src/components/JourneysAppBar/JourneysAppBar.tsx
  apps/journeys-admin/src/components/JourneysAppBar/index.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
  apps/journeys-admin/src/components/PageWrapper/index.tsx
Labels: journeys-admin

#224 fix journeys build
  .eslintrc.json
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/pages/_document.tsx
  apps/journeys/public/android-chrome-192x192.png
  apps/journeys/public/android-chrome-512x512.png
  apps/journeys/public/apple-touch-icon.png
  apps/journeys/public/favicon-16x16.png
  apps/journeys/public/favicon.ico
  apps/journeys/public/site.webmanifest
  package-lock.json
  package.json
Labels: bug, journeys

#223 add useEditor
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attribute/Attribute.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Drawer.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Image/Image.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioOption/RadioOption.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/Typography/Typography.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/index.ts
  libs/journeys/ui/src/libs/context/EditorContext.tsx
  libs/journeys/ui/src/libs/context/index.ts
  libs/journeys/ui/src/libs/index.ts
Labels: enhancement

#230 SetStepsAction should set selectedStep and SelectedBlock
  libs/journeys/ui/src/libs/context/EditorContext.spec.tsx
  libs/journeys/ui/src/libs/context/EditorContext.tsx
Labels: bug, journeys-ui

#231 fix block aql query
  apps/api-journeys/src/app/modules/block/block.service.ts
Labels: bug, backend

#232 hide menu on click in AccessDialog
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/components/AccessDialog/ApproveUser/ApproveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/ApproveUser/ApproveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/PromoteUser/PromoteUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/PromoteUser/PromoteUser.tsx
  apps/journeys-admin/src/components/AccessDialog/RemoveUser/RemoveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/RemoveUser/RemoveUser.tsx
Labels: bug, journeys-admin

#236 Add access avatars to journey view
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.spec.tsx
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.stories.tsx
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.tsx
  apps/journeys-admin/src/components/AccessAvatars/data.ts
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.tsx
  apps/journeys-admin/src/components/JourneyView/data.ts
Labels: enhancement

#237 CopyTextField component
  .storybook/main.js
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.tsx
  apps/journeys-admin/src/components/JourneyView/ShareSection/ShareSection.spec.tsx
  apps/journeys-admin/src/components/JourneyView/ShareSection/ShareSection.stories.tsx
  apps/journeys-admin/src/components/JourneyView/ShareSection/ShareSection.tsx
  apps/journeys-admin/src/components/JourneyView/ShareSection/index.ts
  libs/shared/ui/src/components/CopyTextField/CopyTextField.spec.tsx
  libs/shared/ui/src/components/CopyTextField/CopyTextField.stories.tsx
  libs/shared/ui/src/components/CopyTextField/CopyTextField.tsx
  libs/shared/ui/src/components/CopyTextField/index.ts
  libs/shared/ui/src/index.ts
Labels: component
