Repository JesusFilm/core, pull requests merged in 2022-05, with the labels that each got.

#551 ci: run chromatic on affected projects only
  .github/workflows/main.yml
  .storybook/main.js
Labels: effort: 2, priority: now, type: ci

#501 refactor: error message for title and description dialog
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.tsx
Labels: priority: soon, effort: 1, type: refactor

#528 fix: title and description form reset
  .github/workflows/main.yml
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.tsx
Labels: effort: 2, type: fix, priority: soon

#553 feat: add step response
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/response/response.module.ts
  apps/api-journeys/src/app/modules/response/step/step.graphql
  apps/api-journeys/src/app/modules/response/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/response/step/step.resolver.ts
Labels: priority: soon, type: feat, effort: 1

#486 feat: bigquery export
  .github/workflows/etl-deploy.yml
  resources/kube/arangodb-bigquery-etl/Dockerfile
  resources/kube/arangodb-bigquery-etl/arangodb-bigquery-etl-deployment.yaml
  resources/kube/arangodb-bigquery-etl/bqexport.sh
Labels: priority: 2day, effort: 13, type: feat

#554 refactor: remove fields, added userId
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/response/step/step.graphql
  apps/api-journeys/src/app/modules/response/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/response/step/step.resolver.ts
Labels: priority: soon, effort: 1, type: refactor

#555 fix: journey progress at bottom on desktop
  apps/journeys/src/components/Conductor/Conductor.tsx
Labels: type: fix, priority: now, effort: 1

#556 fix: bigquery export
  .github/workflows/etl-deploy.yml
Labels: type: fix, priority: now, effort: 1

#552 fix: style to change on newly created cards
  apps/journeys-admin/__generated__/CardBlockThemeModeUpdate.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.tsx
Labels: type: fix, priority: soon, effort: 1

#557 fix: disable preview mode when journeys not published
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.tsx
Labels: type: fix, priority: soon, effort: 1

#561 feat: docker and act
  .devcontainer/devcontainer.json
  .devcontainer/post-create-command.sh
Labels: priority: 2day, type: feat, effort: 1

#564 fix: initial card background image parentOrder
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.spec.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.tsx
Labels: type: fix, priority: soon, effort: 1

#559 refactor: response to event
  .storybook/main.js
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/seed.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/modules/event/event.graphql
  apps/api-journeys/src/app/modules/event/event.module.ts
  apps/api-journeys/src/app/modules/event/event.resolver.ts
  apps/api-journeys/src/app/modules/event/event.service.ts
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.graphql
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.ts
  apps/api-journeys/src/app/modules/event/signUp/signUp.graphql
  apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.ts
  apps/api-journeys/src/app/modules/event/step/step.graphql
  apps/api-journeys/src/app/modules/event/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/step/step.resolver.ts
  apps/api-journeys/src/app/modules/event/video/video.graphql
  apps/api-journeys/src/app/modules/event/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/video/video.resolver.ts
  apps/api-journeys/src/app/modules/response/radioQuestion/radioQuestion.graphql
  apps/api-journeys/src/app/modules/response/response.graphql
  apps/api-journeys/src/app/modules/response/signUp/signUp.graphql
  apps/api-journeys/src/app/modules/response/step/step.graphql
  apps/api-journeys/src/app/modules/response/video/video.graphql
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
Labels: effort: 5, priority: now, type: refactor

#563 fix: add emotion cache
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/pages/_document.tsx
  apps/journeys/pages/_app.tsx
  apps/journeys/pages/_document.tsx
  apps/watch-admin/pages/_app.tsx
  apps/watch-admin/pages/_document.tsx
  apps/watch/pages/_app.tsx
  apps/watch/pages/_document.tsx
  libs/shared/ui/src/index.ts
  libs/shared/ui/src/libs/emotion/cache.ts
Labels: effort: 5, type: fix, priority: now

#565 fix: add kubectl version
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-worker.yml
  .github/workflows/etl-deploy.yml
Labels: type: fix, priority: now, effort: 1

#560 fix: bigquery export
  .github/workflows/etl-deploy.yml
  resources/kube/arangodb-bigquery-etl/Dockerfile
Labels: type: fix, priority: now, effort: 1

#562 fix: card background video display
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
Labels: effort: 2, type: fix, priority: soon

#566 fix: arango collection creation
  apps/api-journeys/db/seed.ts
  apps/api-languages/db/seed.ts
  apps/api-users/db/seed.ts
  apps/api-videos/db/seed.ts
Labels: effort: 2, type: fix, priority: now

#574 fix: show all languages
  apps/journeys-admin/src/components/LanguageSelect/LanguageSelect.tsx
Labels: type: fix, priority: now, effort: 1

#576 refactor: video response to event
  apps/journeys-admin/__generated__/VideoPlayEventCreate.ts
  apps/journeys-admin/__generated__/VideoResponseCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/VideoPlayEventCreate.ts
  apps/journeys/__generated__/VideoResponseCreate.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/VideoPlayEventCreate.ts
  apps/watch-admin/__generated__/VideoResponseCreate.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/VideoPlayEventCreate.ts
  apps/watch/__generated__/VideoResponseCreate.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/__generated__/VideoPlayEventCreate.ts
  libs/journeys/ui/src/components/Video/__generated__/VideoResponseCreate.ts
  libs/journeys/ui/src/components/Video/index.ts
Labels: priority: soon, effort: 1, type: refactor

#577 fix: rotation card dimensions
  .storybook/main.js
  apps/journeys/src/components/Conductor/Conductor.tsx
  package-lock.json
  package.json
Labels: priority: 2day, type: fix, effort: 1

#572 feat: countries with maps
  apps/api-gateway/schema.graphql
  apps/api-languages/schema.graphql
  apps/api-languages/src/app/__generated__/graphql.ts
  apps/api-languages/src/app/modules/country/country.graphql
  apps/api-languages/src/app/modules/language/language.graphql
  apps/api-languages/src/app/modules/language/language.resolver.ts
  apps/api-languages/src/app/modules/language/language.service.spec.ts
  apps/api-languages/src/app/modules/language/language.service.ts
  apps/watch/__generated__/GetCountries.ts
  apps/watch/__generated__/GetCountry.ts
  apps/watch/next-env.d.ts
  apps/watch/next.config.js
  apps/watch/pages/[...slug].tsx
  apps/watch/pages/countries/[...slug].tsx
  apps/watch/pages/countries/index.tsx
  apps/watch/pages/index.tsx
  apps/watch/src/components/Countries/Countries.tsx
  apps/watch/src/components/Countries/Map.tsx
  apps/watch/src/libs/countries/countries.graphql.ts
  apps/watch/src/libs/languageContext/LanguageContext.spec.tsx
  apps/watch/src/libs/languageContext/LanguageContext.tsx
  apps/watch/src/libs/languageContext/baseLanguages.ts
  package-lock.json
  package.json
  resources/kube/arangodb-bigquery-etl/bqexport.sh
  tools/scripts/codegen.sh
  tools/scripts/generate-graphql.sh
Labels: priority: 2day, effort: 5, type: feat

#575 feat: add journey view event
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/event.module.ts
  apps/api-journeys/src/app/modules/event/journey/journey.graphql
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.ts
Labels: priority: soon, type: feat, effort: 1

#571 feat: add button click event - backend
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/button/button.graphql
  apps/api-journeys/src/app/modules/event/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/button/button.resolver.ts
  apps/api-journeys/src/app/modules/event/event.module.ts
Labels: priority: soon, type: feat, effort: 1

#583 feat: additional translation
  apps/api-gateway/schema.graphql
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/watch/__generated__/GetCountries.ts
  apps/watch/__generated__/GetCountry.ts
  apps/watch/__generated__/GetLanguage.ts
  apps/watch/__generated__/GetVideo.ts
  apps/watch/__generated__/GetVideoSiblings.ts
  apps/watch/__generated__/GetVideoTag.ts
  apps/watch/__generated__/GetVideos.ts
  apps/watch/pages/[...slug].tsx
  apps/watch/pages/countries/[...slug].tsx
  apps/watch/pages/index.tsx
  apps/watch/src/components/Videos/VideoList/Card/VideoListCard.tsx
  apps/watch/src/components/Videos/VideoList/List/VideoListList.tsx
  apps/watch/src/components/Videos/VideoList/VideoList.spec.tsx
  apps/watch/src/components/Videos/VideoList/VideoList.tsx
  apps/watch/src/components/Videos/VideoList/testData.ts
  apps/watch/src/libs/countries/countries.graphql.ts
  libs/nest/decorators/src/lib/TranslationField/TranslationField.spec.ts
  libs/nest/decorators/src/lib/TranslationField/TranslationField.ts
Labels: effort: 5, priority: soon, type: feat

#581 refactor: deprecate coverblockid field on card mutations
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/card/card.graphql
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: priority: soon, effort: 1, type: refactor

#579 fix: deprecate heading and description in radioquestionblock
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/seeds/nua1.ts
  apps/api-journeys/db/seeds/nua2.ts
  apps/api-journeys/db/seeds/nua8.ts
  apps/api-journeys/db/seeds/nua9.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.graphql
  apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.ts
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/RadioQuestionBlockCreate.ts
  apps/journeys-admin/__generated__/RadioQuestionFields.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/data.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/data.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/RadioQuestionFields.ts
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/RadioQuestionFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/RadioQuestionFields.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.stories.tsx
  libs/journeys/ui/src/components/RadioQuestion/__generated__/RadioQuestionFields.ts
  libs/journeys/ui/src/components/RadioQuestion/radioQuestionFields.ts
  libs/journeys/ui/src/libs/searchBlocks/searchBlocks.spec.ts
  libs/journeys/ui/src/libs/transformer/__generated__/BlockFields.ts
  libs/journeys/ui/src/libs/transformer/transformer.spec.ts
Labels: type: fix, priority: soon, effort: 1

#587 fix: update journey fields type
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/context/__generated__/JourneyFields.ts
Labels: type: fix, priority: now, effort: 1

#589 perf: memoize blurImage on ImageBlock
  libs/journeys/ui/src/components/Image/Image.tsx
Labels: priority: 2day, effort: 1, type: perf

#593 fix: radio question create
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewImageButton/NewImageButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewRadioQuestionButton/NewRadioQuestion.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewRadioQuestionButton/NewRadioQuestionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewRadioQuestionButton/NewRadioQuestionButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewSignUpButton/NewSignUpButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewTypographyButton/NewTypographyButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewVideoButton/NewVideoButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
Labels: priority: 2day, type: fix, effort: 1

#592 chore: add doppler
  .devcontainer/Dockerfile
  .devcontainer/docker-compose.yml
  .devcontainer/post-create-command.sh
  .github/workflows/main.yml
  CONTRIBUTING.md
  apps/journeys-admin/.env.development
  apps/journeys-admin/.env.example
  apps/journeys-admin/.env.production
  apps/journeys-admin/project.json
  apps/journeys-admin/src/libs/firebaseClient/initAuth.ts
  apps/journeys/.env.development
  apps/journeys/.env.example
  apps/journeys/.env.production
  apps/journeys/pages/api/revalidate.ts
  apps/journeys/project.json
  apps/journeys/src/libs/firebaseClient/firebaseClient.ts
Labels: priority: now, effort: 13, type: feat

#568 feat: add stepViewEvent to step block
  apps/journeys-admin/__generated__/StepViewEventCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/FramePortal/FramePortal.stories.tsx
  apps/journeys/__generated__/StepViewEventCreate.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/StepViewEventCreate.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/StepViewEventCreate.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/components/Step/__generated__/StepViewEventCreate.ts
Labels: effort: 2, priority: soon, type: feat

#569 refactor: radio question response to event
  apps/journeys-admin/__generated__/RadioQuestionResponseCreate.ts
  apps/journeys-admin/__generated__/RadioQuestionSubmissionEventCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/RadioQuestionResponseCreate.ts
  apps/journeys/__generated__/RadioQuestionSubmissionEventCreate.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/RadioQuestionResponseCreate.ts
  apps/watch-admin/__generated__/RadioQuestionSubmissionEventCreate.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/RadioQuestionResponseCreate.ts
  apps/watch/__generated__/RadioQuestionSubmissionEventCreate.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/RadioQuestion/RadioOption/RadioOption.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.stories.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/RadioQuestion/__generated__/RadioQuestionResponseCreate.ts
  libs/journeys/ui/src/components/RadioQuestion/__generated__/RadioQuestionSubmissionEventCreate.ts
  libs/journeys/ui/src/components/RadioQuestion/index.ts
Labels: effort: 3, priority: soon, type: refactor

#573 feat: add click event on button click - frontend
  apps/journeys-admin/__generated__/ButtonClickEventCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/ButtonClickEventCreate.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/pages/[journeySlug].tsx
  apps/watch-admin/__generated__/ButtonClickEventCreate.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/ButtonClickEventCreate.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.stories.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Button/__generated__/ButtonClickEventCreate.ts
  libs/journeys/ui/src/components/GridContainer/GridContainer.stories.tsx
  libs/journeys/ui/src/components/GridContainer/GridItem/GridItem.stories.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/libs/context/JourneyContext.tsx
Labels: priority: soon, type: feat, effort: 1

#600 feat: add doppler to watch
  .github/workflows/main.yml
  apps/watch-admin/.env.development
  apps/watch-admin/.env.example
  apps/watch-admin/.env.production
  apps/watch-admin/project.json
  apps/watch-admin/src/libs/firebaseClient/initAuth.ts
  apps/watch/.env.development
  apps/watch/.env.example
  apps/watch/.env.production
  apps/watch/project.json
  apps/watch/src/libs/firebaseClient/firebaseClient.ts
Labels: priority: now, type: feat, effort: 1

#570 refactor signup response to event
  apps/journeys-admin/__generated__/SignUpResponseCreate.ts
  apps/journeys-admin/__generated__/SignUpSubmissionEventCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
  apps/journeys/__generated__/SignUpResponseCreate.ts
  apps/journeys/__generated__/SignUpSubmissionEventCreate.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/pages/_app.tsx
  apps/watch-admin/__generated__/SignUpResponseCreate.ts
  apps/watch-admin/__generated__/SignUpSubmissionEventCreate.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/SignUpResponseCreate.ts
  apps/watch/__generated__/SignUpSubmissionEventCreate.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.stories.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/SignUp/__generated__/SignUpResponseCreate.ts
  libs/journeys/ui/src/components/SignUp/__generated__/SignUpSubmissionEventCreate.ts
Labels: effort: 3, priority: soon, type: refactor

#591 feat: journey view event
  apps/journeys/__generated__/JourneyViewEventCreate.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
Labels: priority: soon, type: feat, effort: 1

#601 docs: fix fetch command
  .github/workflows/main.yml
  CONTRIBUTING.md
Labels: priority: now, type: docs, effort: 1

#605 fix: firebase private key should not store in multiline format
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .github/workflows/main.yml
  apps/api-gateway/.env.example
  apps/api-gateway/project.json
  apps/api-journeys/.env.example
  apps/api-journeys/project.json
  apps/api-languages/.env.example
  apps/api-languages/project.json
  apps/api-users/.env.example
  apps/api-users/project.json
  apps/api-videos/.env.example
  apps/api-videos/project.json
  apps/journeys-admin/project.json
  apps/journeys-admin/src/libs/firebaseClient/initAuth.ts
  apps/journeys/project.json
  apps/watch-admin/project.json
  apps/watch-admin/src/libs/firebaseClient/initAuth.ts
  apps/watch/project.json
Labels: type: fix, priority: now, effort: 1

#603 refactor: video event api
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/event.module.ts
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.ts
  apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.ts
  apps/api-journeys/src/app/modules/event/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/step/step.resolver.ts
  apps/api-journeys/src/app/modules/event/video/video.graphql
  apps/api-journeys/src/app/modules/event/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/video/video.resolver.ts
  apps/journeys-admin/__generated__/VideoPlayEventCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/VideoPlayEventCreate.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/VideoPlayEventCreate.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/VideoPlayEventCreate.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/Video/__generated__/VideoPlayEventCreate.ts
Labels: effort: 3, priority: now, type: refactor

#607 refactor: extract video events
  apps/journeys-admin/__generated__/VideoCompleteEventCreate.ts
  apps/journeys-admin/__generated__/VideoPauseEventCreate.ts
  apps/journeys-admin/__generated__/VideoPlayEventCreate.ts
  apps/journeys-admin/__generated__/VideoStartEventCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/VideoCompleteEventCreate.ts
  apps/journeys/__generated__/VideoPauseEventCreate.ts
  apps/journeys/__generated__/VideoPlayEventCreate.ts
  apps/journeys/__generated__/VideoStartEventCreate.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/VideoCompleteEventCreate.ts
  apps/watch-admin/__generated__/VideoPauseEventCreate.ts
  apps/watch-admin/__generated__/VideoPlayEventCreate.ts
  apps/watch-admin/__generated__/VideoStartEventCreate.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/VideoCompleteEventCreate.ts
  apps/watch/__generated__/VideoPauseEventCreate.ts
  apps/watch/__generated__/VideoPlayEventCreate.ts
  apps/watch/__generated__/VideoStartEventCreate.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/VideoEvents/VideoEvents.spec.tsx
  libs/journeys/ui/src/components/Video/VideoEvents/VideoEvents.tsx
  libs/journeys/ui/src/components/Video/VideoEvents/__generated__/VideoCompleteEventCreate.ts
  libs/journeys/ui/src/components/Video/VideoEvents/__generated__/VideoPauseEventCreate.ts
  libs/journeys/ui/src/components/Video/VideoEvents/__generated__/VideoPlayEventCreate.ts
  libs/journeys/ui/src/components/Video/VideoEvents/__generated__/VideoStartEventCreate.ts
  libs/journeys/ui/src/components/Video/VideoEvents/index.ts
  libs/journeys/ui/src/components/Video/index.ts
Labels: effort: 3, priority: soon, type: refactor

#608 feat: video expand collapse events
  apps/journeys-admin/__generated__/VideoCollapseEventCreate.ts
  apps/journeys-admin/__generated__/VideoExpandEventCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/VideoCollapseEventCreate.ts
  apps/journeys/__generated__/VideoExpandEventCreate.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/VideoCollapseEventCreate.ts
  apps/watch-admin/__generated__/VideoExpandEventCreate.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/VideoCollapseEventCreate.ts
  apps/watch/__generated__/VideoExpandEventCreate.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/Video/VideoEvents/VideoEvents.spec.tsx
  libs/journeys/ui/src/components/Video/VideoEvents/VideoEvents.tsx
  libs/journeys/ui/src/components/Video/VideoEvents/__generated__/VideoCollapseEventCreate.ts
  libs/journeys/ui/src/components/Video/VideoEvents/__generated__/VideoExpandEventCreate.ts
Labels: effort: 2, priority: soon, type: feat

#610 fix: add good commit to fix command lint
  .github/workflows/main.yml
Labels: type: fix, priority: now, effort: 1

#613 fix: endat to pause video when no action
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: type: fix, priority: soon, effort: 1

#621 refactor: video position to float
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/video/video.graphql
Labels: priority: now, effort: 1, type: refactor

#619 fix: set default video action
  apps/journeys-admin/__generated__/UpdateVideoBlockNextStep.ts
  apps/journeys-admin/__generated__/VideoBlockSetDefaultAction.ts
  apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.tsx
Labels: type: fix, effort: 3, priority: soon

#625 chore: add imageshack as image source
  apps/journeys-admin/next.config.js
  apps/journeys/next.config.js
Labels: priority: now, effort: 1, type: chore

#617 fix: canvas to only render current card
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
Labels: type: fix, effort: 3, priority: soon

#626 fix: stop re-render on auth
  apps/api-gateway/src/main.ts
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/pages/_app.tsx
  apps/journeys/pages/index.tsx
  apps/journeys/src/libs/apolloClient/apolloClient.ts
  apps/journeys/src/libs/apolloClient/cache/cache.ts
  apps/journeys/src/libs/apolloClient/cache/index.ts
  apps/journeys/src/libs/apolloClient/index.ts
  apps/journeys/src/libs/client/client.ts
  apps/journeys/src/libs/client/index.ts
Labels: type: fix, priority: now, effort: 1

#631 fix: add cors to gateway
  apps/api-gateway/src/environments/environment.prod.ts
  apps/api-gateway/src/environments/environment.ts
  apps/api-gateway/src/environments/types.ts
  apps/api-gateway/src/main.ts
  package-lock.json
  package.json
Labels: type: fix, priority: now, effort: 1

#629 refactor: complete event to end at
  apps/journeys-admin/__generated__/VideoProgressEventCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/VideoProgressEventCreate.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/VideoProgressEventCreate.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/VideoProgressEventCreate.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/VideoEvents/VideoEvents.spec.tsx
  libs/journeys/ui/src/components/Video/VideoEvents/VideoEvents.tsx
  libs/journeys/ui/src/components/Video/VideoEvents/__generated__/VideoProgressEventCreate.ts
Labels: priority: now, effort: 1, type: refactor

#634 chore: add react gtm module dependency
  package-lock.json
  package.json
Labels: priority: now, effort: 1, type: chore, dependencies

#633 feat: add ga custom events
  apps/journeys/pages/_app.tsx
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/components/Video/VideoEvents/VideoEvents.spec.tsx
  libs/journeys/ui/src/components/Video/VideoEvents/VideoEvents.tsx
Labels: effort: 3, priority: now, type: feat

#630 fix: blurimage calculation
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Image/Image.spec.tsx
  libs/journeys/ui/src/components/Image/Image.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/libs/blurImage/blurImage.spec.ts
  libs/journeys/ui/src/libs/blurImage/blurImage.ts
Labels: effort: 2, type: fix, priority: soon

#616 chore: remove deprecated fields
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/seed.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/modules/event/video/video.graphql
  apps/api-journeys/src/app/modules/response/radioQuestion/radioQuestion.graphql
  apps/api-journeys/src/app/modules/response/radioQuestion/radioQuestion.resolver.spec.ts
  apps/api-journeys/src/app/modules/response/radioQuestion/radioQuestion.resolver.ts
  apps/api-journeys/src/app/modules/response/response.graphql
  apps/api-journeys/src/app/modules/response/response.module.ts
  apps/api-journeys/src/app/modules/response/response.resolver.ts
  apps/api-journeys/src/app/modules/response/response.service.ts
  apps/api-journeys/src/app/modules/response/signUp/signUp.graphql
  apps/api-journeys/src/app/modules/response/signUp/signUp.resolver.spec.ts
  apps/api-journeys/src/app/modules/response/signUp/signUp.resolver.ts
  apps/api-journeys/src/app/modules/response/step/step.graphql
  apps/api-journeys/src/app/modules/response/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/response/step/step.resolver.ts
  apps/api-journeys/src/app/modules/response/video/video.graphql
  apps/api-journeys/src/app/modules/response/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/response/video/video.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
Labels: priority: 2day, effort: 5, type: chore

#640 feat: send title on journey view to ga
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
Labels: priority: soon, type: feat, effort: 1

#642 feat: prevent users from creating journeys unless invited
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
Labels: effort: 2, priority: now, type: feat

#644 feat: add step name to step event
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.tsx
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/index.ts
  libs/journeys/ui/src/libs/getStepHeading/getStepHeading.spec.ts
  libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
  libs/journeys/ui/src/libs/getStepHeading/index.ts
  libs/journeys/ui/src/libs/index.ts
Labels: effort: 2, priority: soon, type: feat

#645 fix: video position type
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/modules/event/video/video.graphql
  apps/api-journeys/src/app/modules/event/video/video.resolver.spec.ts
Labels: type: fix, priority: now, effort: 1

#590 fix: arangodb bigquery export secret
  resources/kube/arangodb-bigquery-etl/arangodb-bigquery-etl-deployment.yaml
  resources/kube/arangodb-bigquery-etl/bqexport.sh
Labels: priority: 2day, effort: 2, type: fix

#651 feat: i18n for jf-core repo
  .github/workflows/crowdin.yml
  .github/workflows/main.yml
  apps/journeys/i18next-parser.config.js
  apps/journeys/next-i18next.config.js
  apps/journeys/next.config.js
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/pages/_app.tsx
  apps/journeys/pages/index.tsx
  apps/journeys/project.json
  crowdin.yml
  i18next-parser.config.base.js
  libs/journeys/ui/i18next-parser.config.js
  libs/journeys/ui/project.json
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  locales/en/apps-journeys.json
  locales/en/common.json
  locales/en/libs-journeys-ui.json
  package-lock.json
  package.json
Labels: priority: now, effort: 13, type: feat

#657 fix: update crowdin pr format
  .github/workflows/crowdin.yml
Labels: type: fix, priority: now, effort: 1

#659 fix: update crowdin branch name
  .github/workflows/crowdin.yml
Labels: type: fix, priority: now, effort: 1

#649 feat: send step name to ga
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.tsx
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/libs/getStepHeading/getStepHeading.spec.ts
  libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
Labels: effort: 3, priority: soon, type: feat

#646 feat: add heading to page title
  libs/journeys/ui/src/components/Step/Step.tsx
Labels: priority: now, type: feat, effort: 1

#653 feat: add events to bigquery
  resources/kube/arangodb-bigquery-etl/Dockerfile
  resources/kube/arangodb-bigquery-etl/bqexport.sh
Labels: priority: now, type: feat, effort: 1

#650 feat: add video name and id to video events
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/VideoEvents/VideoEvents.spec.tsx
  libs/journeys/ui/src/components/Video/VideoEvents/VideoEvents.tsx
Labels: priority: soon, type: feat, effort: 1

#663 chore: move locales to lib
  .prettierignore
  apps/journeys/next-i18next.config.js
  apps/journeys/project.json
  crowdin.yml
  i18next-parser.config.base.js
  libs/journeys/ui/project.json
  libs/locales/af/apps-journeys.json
  libs/locales/af/common.json
  libs/locales/af/libs-journeys-ui.json
  libs/locales/en/apps-journeys.json
  libs/locales/en/common.json
  libs/locales/en/libs-journeys-ui.json
  libs/locales/mi/apps-journeys.json
  libs/locales/mi/common.json
  libs/locales/mi/libs-journeys-ui.json
  libs/locales/project.json
  nx.json
  workspace.json
Labels: type: fix, priority: now, effort: 1

#661 feat: watch styling part 1
  apps/watch/__generated__/GetVideo.ts
  apps/watch/pages/[...slug].tsx
  apps/watch/pages/_app.tsx
  apps/watch/pages/countries/index.tsx
  apps/watch/pages/index.tsx
  apps/watch/pages/videos/[...tag].tsx
  apps/watch/public/favicon-16x16.png
  apps/watch/public/favicon-32x32.png
  apps/watch/public/favicon.ico
  apps/watch/public/fonts/ApercuBold.otf
  apps/watch/public/fonts/ApercuRegular.otf
  apps/watch/public/fonts/apercu_bold.eot
  apps/watch/public/fonts/apercu_bold.svg
  apps/watch/public/fonts/apercu_bold.ttf
  apps/watch/public/fonts/apercu_bold.woff
  apps/watch/public/fonts/apercu_bold.woff2
  apps/watch/public/fonts/apercu_light.eot
  apps/watch/public/fonts/apercu_light.svg
  apps/watch/public/fonts/apercu_light.ttf
  apps/watch/public/fonts/apercu_light.woff
  apps/watch/public/fonts/apercu_light.woff2
  apps/watch/public/fonts/apercu_regular.svg
  apps/watch/public/fonts/apercu_regular.ttf
  apps/watch/public/fonts/apercu_regular.woff
  apps/watch/public/fonts/apercu_regular.woff2
  apps/watch/public/fonts/fonts.css
  apps/watch/public/icons/facebook.svg
  apps/watch/public/icons/instagram.svg
  apps/watch/public/icons/twitter.svg
  apps/watch/public/icons/youtube.svg
  apps/watch/public/images/cru-logo.png
  apps/watch/public/images/jesus-footer.png
  apps/watch/public/images/jesus-header.png
  apps/watch/public/images/jf-logo@2x.png
  apps/watch/public/styles/carousel.css
  apps/watch/public/styles/video-js.css
  apps/watch/public/taskbar-icon.svg
  apps/watch/src/components/Footer/Footer.tsx
  apps/watch/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/watch/src/components/PageWrapper/PageWrapper.tsx
  apps/watch/src/components/ThemeProvider/ThemeProvider.stories.tsx
  apps/watch/src/components/ThemeProvider/ThemeProvider.tsx
  apps/watch/src/components/ThemeProvider/index.ts
  apps/watch/src/components/Videos/VideoList/Card/VideoListCard.tsx
  apps/watch/src/components/Videos/VideoList/Carousel/VideoListCarousel.tsx
  apps/watch/src/components/Videos/VideoList/Grid/VideoListGrid.tsx
  apps/watch/src/libs/storybook/containers.tsx
Labels: effort: 13, priority: soon, type: feat

#668 feat: add i18n to journeys admin
  apps/journeys-admin/i18next-parser.config.js
  apps/journeys-admin/next-i18next.config.js
  apps/journeys-admin/next.config.js
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/journeys/[journeySlug].tsx
  apps/journeys-admin/pages/journeys/[journeySlug]/edit.tsx
  apps/journeys-admin/pages/users/sign-in.tsx
  apps/journeys-admin/project.json
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, type: feat, effort: 1

#671 fix: copy locales on build
  .gitignore
  apps/journeys-admin/next-i18next.config.js
  apps/journeys-admin/project.json
  libs/locales/project.json
  workspace.json
Labels: type: fix, priority: now, effort: 1

#674 fix: admins build target
  apps/journeys-admin/project.json
Labels: type: fix, priority: now, effort: 1
