Repository JesusFilm/core, pull requests merged in 2022-06, with the labels that each got.

#678 fix: copy locales to journeys build
  apps/journeys/next-i18next.config.js
  apps/journeys/project.json
Labels: type: fix, priority: now, effort: 1

#673 fix: tidy up test warnings
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/data.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/Swatch/Swatch.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/data.ts
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/SignUp/TextField/TextField.tsx
Labels: type: test, effort: 3, priority: soon

#682 fix: update step order on step delete
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/utils/getSelected.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/utils/getSelected.ts
Labels: type: fix, priority: now, effort: 1

#677 fix: step order on delete
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
Labels: effort: 2, type: fix, priority: now

#637 fix: flakey vr tests
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateAction/NavigateAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToBlockAction/NavigateToBlockAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/UserMenu.stories.tsx
Labels: effort: 2, type: fix, priority: soon

#670 fix: get step heading logic
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.tsx
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/libs/getStepHeading/getStepHeading.spec.ts
  libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
  libs/locales/en/translation.json
Labels: type: fix, effort: 3, priority: now

#684 fix: new kubernetes cluster deployment
  .kube/config
  resources/kube/api/api-gateway-main-deployment.yaml
  resources/kube/api/api-gateway-stage-deployment.yaml
  resources/kube/api/api-journeys-main-deployment.yaml
  resources/kube/api/api-journeys-stage-deployment.yaml
  resources/kube/api/api-languages-main-deployment.yaml
  resources/kube/api/api-languages-stage-deployment.yaml
  resources/kube/api/api-users-main-deployment.yaml
  resources/kube/api/api-users-stage-deployment.yaml
  resources/kube/api/api-videos-main-deployment.yaml
  resources/kube/api/api-videos-stage-deployment.yaml
  resources/kube/arangodb-bigquery-etl/arangodb-bigquery-etl-deployment.yaml
  resources/kube/arangodb/arangodb-deployment.yaml
  resources/kube/aws-auth-cm.yaml
  resources/kube/dashboard/admin-user.yaml
  resources/kube/ssl/alb-ingress-controller.yaml
  resources/kube/ssl/external-dns.yaml
Labels: type: fix, priority: now, effort: 13

#667 feat: edit slug dialog
  apps/journeys-admin/__generated__/JourneySlugUpdate.ts
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/SlugDialog/SlugDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/SlugDialog/SlugDialog.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/SlugDialog/SlugDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/SlugDialog/index.ts
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: effort: 2, priority: now, type: feat

#688 chore: bump google gax from 2.28.1 to 2.30.5
  package-lock.json
Labels: priority: now, effort: 1, type: chore

#687 feat: new journey statuses
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/journey/journey.service.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.service.ts
  apps/journeys-admin/__generated__/JourneyPublish.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/nest/database/src/lib/base.service.ts
Labels: effort: 5, priority: soon, type: feat

#662 feat: terms and conditions and privacy policy links
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/Footer/Footer.spec.tsx
  apps/journeys/src/components/Footer/Footer.tsx
  apps/journeys/src/components/Footer/index.ts
  libs/locales/en/apps-journeys.json
  libs/shared/ui/src/libs/themes/base/tokens/colors.ts
  libs/shared/ui/src/libs/themes/base/tokens/components.ts
  tools/scripts/check-git-status.sh
Labels: priority: soon, type: feat, effort: 1

#698 fix: video block default action
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Labels: type: fix, priority: now, effort: 1

#702 fix: More accurately type getSiblingsInternal return type
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
Labels: priority: 2day, type: fix, effort: 1

#695 fix: current nextblockid logic
  apps/api-journeys/db/seeds/nua1.ts
  apps/api-journeys/db/seeds/nua2.ts
  apps/api-journeys/db/seeds/nua8.ts
  apps/api-journeys/db/seeds/nua9.ts
  apps/journeys-admin/__generated__/StepBlockNextBlockIdUpdate.ts
  apps/journeys-admin/__generated__/VideoBlockSetDefaultAction.ts
  apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Cards/Cards.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/JourneyProgress/JourneyProgress.spec.tsx
  apps/journeys/src/components/JourneyProgress/JourneyProgress.tsx
  libs/journeys/ui/src/libs/useBlocks/blocks.ts
Labels: effort: 5, type: fix, priority: soon

#707 feat: Add step card in specific order
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/step/step.graphql
  apps/api-journeys/src/app/modules/block/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/step/step.resolver.ts
  apps/journeys-admin/__generated__/StepAndCardBlockCreate.ts
  apps/journeys-admin/__generated__/StepBlock.ts
  apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
  apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx
Labels: effort: 8, priority: soon, type: feat

#709 fix: remove console log
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
Labels: type: fix, priority: now, effort: 1

#708 docs: updating commit lint
  .github/workflows/main.yml
Labels: priority: now, type: docs, effort: 1

#712 fix: missing add button on overview
  apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx
Labels: type: fix, priority: soon, effort: 1

#720 chore: add commitlint config to pr title
  dangerfile.ts
Labels: priority: now, effort: 1, type: chore

#704 feat: add launch darkly and flags provider
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/journeys/[journeySlug].tsx
  apps/journeys-admin/pages/journeys/[journeySlug]/edit.tsx
  libs/shared/ui/src/components/FlagsProvider/FlagsProvider.spec.tsx
  libs/shared/ui/src/components/FlagsProvider/FlagsProvider.tsx
  libs/shared/ui/src/components/FlagsProvider/index.ts
  libs/shared/ui/src/libs/getLaunchDarklyClient/getLaunchDarklyClient.ts
  libs/shared/ui/src/libs/getLaunchDarklyClient/index.ts
  package-lock.json
  package.json
Labels: effort: 5, priority: now, type: feat

#705 feat: block duplication api
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/block.graphql
  apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.resolver.ts
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/StepAndCardBlockCreate.ts
  apps/journeys-admin/__generated__/StepBlockDefaultNextBlockUpdate.ts
  apps/journeys-admin/__generated__/StepBlockNextBlockUpdate.ts
  apps/journeys-admin/__generated__/StepFields.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/StepFields.ts
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/StepFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/StepFields.ts
  libs/journeys/ui/src/components/Step/__generated__/StepFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
Labels: effort: 3, priority: soon, type: feat

#706 feat: stage db server resources
  resources/kube/arangodb/arangodb-stage-deployment.yaml
  resources/kube/arangodb/arangodb-stage-service.yaml
Labels: priority: 2day, type: feat, effort: 1

#722 fix: launchdarkly json
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/journeys/[journeySlug].tsx
  apps/journeys-admin/pages/journeys/[journeySlug]/edit.tsx
Labels: type: fix, priority: now, effort: 1

#693 feat: embed power bi report and admin journeys report endpoint
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  libs/nest/powerBi/.babelrc
  libs/nest/powerBi/.eslintrc.json
  libs/nest/powerBi/README.md
  libs/nest/powerBi/jest.config.js
  libs/nest/powerBi/project.json
  libs/nest/powerBi/src/lib/config.ts
  libs/nest/powerBi/src/lib/getPowerBiAccessToken/getPowerBiAccessToken.spec.ts
  libs/nest/powerBi/src/lib/getPowerBiAccessToken/getPowerBiAccessToken.ts
  libs/nest/powerBi/src/lib/getPowerBiAccessToken/index.ts
  libs/nest/powerBi/src/lib/getPowerBiEmbed/getPowerBiEmbed.spec.ts
  libs/nest/powerBi/src/lib/getPowerBiEmbed/getPowerBiEmbed.ts
  libs/nest/powerBi/src/lib/getPowerBiEmbed/index.ts
  libs/nest/powerBi/tsconfig.json
  libs/nest/powerBi/tsconfig.lib.json
  libs/nest/powerBi/tsconfig.spec.json
  package-lock.json
  package.json
  tsconfig.base.json
  workspace.json
Labels: effort: 13, priority: soon, type: feat

#724 feat: validate branch name
  .github/workflows/main.yml
  .husky/pre-commit
  dangerfile.ts
  package-lock.json
  package.json
  validate-branch-name.config.js
Labels: priority: now, type: feat, effort: 1

#726 fix: only check branch name on pr
  .github/workflows/main.yml
Labels: type: fix, priority: now, effort: 1

#701 feat: new journey statuses 2
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/lib/roleGuard/roleGuard.spec.ts
  apps/api-journeys/src/app/lib/roleGuard/roleGuard.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/journey/journey.service.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.service.ts
  apps/journeys-admin/__generated__/JourneyPublish.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/nest/database/src/lib/BaseService.ts
Labels: effort: 5, priority: soon, type: feat

#680 fix: events import schema
  resources/kube/arangodb-bigquery-etl/Dockerfile
  resources/kube/arangodb-bigquery-etl/bqexport.sh
Labels: type: fix, effort: 13, priority: soon

#729 feat: add merge bot config
  .github/merge-bot.yml
Labels: priority: now, type: feat, effort: 1, on stage

#731 feat: add doppler to kubernetes
  resources/kube/api/api-gateway-main-deployment.yaml
  resources/kube/api/api-gateway-stage-deployment.yaml
  resources/kube/api/api-journeys-main-deployment.yaml
  resources/kube/api/api-journeys-stage-deployment.yaml
  resources/kube/api/api-languages-main-deployment.yaml
  resources/kube/api/api-languages-stage-deployment.yaml
  resources/kube/api/api-users-main-deployment.yaml
  resources/kube/api/api-users-stage-deployment.yaml
  resources/kube/api/api-videos-main-deployment.yaml
  resources/kube/api/api-videos-stage-deployment.yaml
  resources/kube/doppler-secret/doppler-secret.yaml
Labels: effort: 3, priority: now, type: feat, on stage

#732 chore: update api-gateway cors
  apps/api-gateway/src/environments/environment.prod.ts
Labels: priority: now, effort: 1, type: chore, on stage

#725 refactor: use journey id instead of slug on journeys-admin
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.spec.tsx
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.stories.tsx
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/components/JourneyInvite/JourneyInvite.spec.tsx
  apps/journeys-admin/src/components/JourneyInvite/JourneyInvite.stories.tsx
  apps/journeys-admin/src/components/JourneyInvite/JourneyInvite.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.tsx
Labels: effort: 8, priority: now, type: refactor, on stage

#727 feat: journey duplication api
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/journey/journey.service.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.service.ts
Labels: priority: 2day, effort: 3, type: feat

#714 feat: localhost cors
  apps/api-gateway/src/environments/environment.prod.ts
Labels: priority: now, type: feat, effort: 1, on stage

#734 fix: allow dependabot branch name
  validate-branch-name.config.js
Labels: type: fix, priority: now, effort: 1

#736 feat: add analytics button
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.stories.tsx
Labels: effort: 2, priority: soon, type: feat

#741 feat: archive and trash tabs
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/journeys-admin/__generated__/GetArchivedJourneys.ts
  apps/journeys-admin/__generated__/GetTrashedJourneys.ts
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.spec.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.stories.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/index.ts
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/StatusTabPanel.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.spec.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.stories.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.tsx
  apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/index.ts
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: effort: 5, priority: soon, type: feat
