Repository JesusFilm/core, pull requests merged in 2022-03, with the labels that each got.

#320 fix: refactored editor provider
  apps/journeys-admin/pages/journeys/[journeySlug]/edit.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.tsx
  apps/journeys-admin/src/components/Editor/JourneyEdit/JourneyEdit.tsx
  apps/journeys-admin/src/components/Editor/JourneyEdit/index.ts
Labels: priority: 2day, effort: 2, type: fix

#318 fix: Set Icons on Button and SignUp update
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/seeds/nua1.ts
  apps/api-journeys/db/seeds/nua2.ts
  apps/api-journeys/db/seeds/nua8.ts
  apps/api-journeys/db/seeds/nua9.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/block.module.ts
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
  apps/api-journeys/src/app/modules/block/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/button/button.resolver.ts
  apps/api-journeys/src/app/modules/block/icon/icon.graphql
  apps/api-journeys/src/app/modules/block/icon/icon.resolver.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.graphql
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/Icon/Icon.spec.tsx
  libs/journeys/ui/src/components/Icon/Icon.tsx
Labels: priority: 2day, type: fix, effort: 3

#308 feature: background image on cards
  apps/journeys-admin/__generated__/BlockDeleteForBackgroundImage.ts
  apps/journeys-admin/__generated__/CardBlockBackgroundImageUpdate.ts
  apps/journeys-admin/__generated__/CardBlockImageBlockCreate.ts
  apps/journeys-admin/__generated__/CardBlockImageBlockUpdate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.tsx
  package-lock.json
Labels: effort: 8, priority: soon, type: feature

#319 fix: Create SignUp and Button with Icons
  apps/journeys-admin/__generated__/ButtonBlockCreate.ts
  apps/journeys-admin/__generated__/SignUpBlockCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewSignUpButton/NewSignUpButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewSignUpButton/NewSignUpButton.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewSignUpButton/NewSignUpButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  libs/journeys/ui/src/index.ts
  libs/journeys/ui/src/libs/index.ts
  libs/journeys/ui/src/libs/transformer/index.ts
Labels: type: fix, effort: 3, priority: soon

#325 fix: make iconName nullable
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/seeds/nua1.ts
  apps/api-journeys/db/seeds/nua2.ts
  apps/api-journeys/db/seeds/nua8.ts
  apps/api-journeys/db/seeds/nua9.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/icon/icon.graphql
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/ButtonBlockCreate.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/IconFields.ts
  apps/journeys-admin/__generated__/SignUpBlockCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewSignUpButton/NewSignUpButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewSignUpButton/NewSignUpButton.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewSignUpButton/NewSignUpButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/IconFields.ts
  apps/journeys/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/Icon/Icon.spec.tsx
  libs/journeys/ui/src/components/Icon/Icon.tsx
  libs/journeys/ui/src/components/Icon/__generated__/IconFields.ts
  libs/journeys/ui/src/libs/transformer/__generated__/BlockFields.ts
Labels: effort: 2, type: fix, priority: soon

#324 fix: Inline editing fab
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/AddFab/AddFab.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/AddFab/AddFab.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/AddFab/AddFab.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/AddFab/index.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Fab/Fab.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Fab/Fab.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Fab/Fab.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Fab/index.tsx
  libs/journeys/ui/src/components/Typography/Typography.tsx
  libs/journeys/ui/src/index.ts
  libs/journeys/ui/src/libs/context/EditorContext.spec.tsx
  libs/journeys/ui/src/libs/context/EditorContext.tsx
  libs/journeys/ui/src/libs/context/index.ts
  libs/journeys/ui/src/libs/index.ts
Labels: type: fix, effort: 3, priority: soon

#312 feature: Add toggle lock status to Step
  apps/journeys-admin/__generated__/StepBlockLockUpdate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/ToggleOption/ToggleOption.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/ToggleOption/ToggleOption.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/ToggleOption/ToggleOption.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/ToggleOption/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/NextCard.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/NextCard.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/NextCard.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.tsx
Labels: effort: 5, priority: now, type: feature

#322 feature: background video
  apps/journeys-admin/__generated__/BlockDeleteForBackgroundVideo.ts
  apps/journeys-admin/__generated__/CardBlockBackgroundVideoUpdate.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockCreate.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockUpdate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/VideoBlockEditorSource.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/VideoBlockEditorSource.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/index.ts
  apps/journeys-admin/src/libs/timeFormat/index.ts
  apps/journeys-admin/src/libs/timeFormat/timeFormat.spec.ts
  apps/journeys-admin/src/libs/timeFormat/timeFormat.ts
  libs/journeys/ui/src/components/Card/Cover/Cover.tsx
  package-lock.json
  package.json
Labels: priority: 2day, effort: 13, type: feature

#326 feature: edit icons
  apps/journeys-admin/__generated__/IconBlockColorUpdate.ts
  apps/journeys-admin/__generated__/IconBlockNameUpdate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Icon/Color/Color.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Icon/Color/Color.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Icon/Color/Color.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Icon/Color/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Icon/Icon.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Icon/Icon.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Icon/Icon.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Icon/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Button/Button.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Button/Button.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ColorDisplayIcon/ColorDisplayIcon.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ColorDisplayIcon/ColorDisplayIcon.tsx
Labels: priority: 2day, effort: 3, type: feature

#331 fix: blockDelete
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/modules/block/block.graphql
  apps/api-journeys/src/app/modules/block/block.resolver.ts
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
  apps/journeys-admin/__generated__/BlockDeleteForBackgroundImage.ts
  apps/journeys-admin/__generated__/BlockDeleteForBackgroundVideo.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.tsx
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.ts
Labels: effort: 2, breaking, type: fix, priority: now

#333 fix: switch back to edit fab when selecting another block
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Image/Image.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioOption/RadioOption.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: priority: 2day, effort: 2, type: fix

#330 feature: edit signup icon
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
Labels: priority: soon, type: feature, effort: 1

#332 feat: Inline edit button
  apps/journeys-admin/__generated__/ButtonBlockUpdateContent.ts
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
Labels: effort: 2, priority: soon, type: feature

#328 feature: InlineEditWrapper and TypographyEdit component
  apps/journeys-admin/__generated__/TypographyBlockUpdateContent.ts
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/index.ts
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
  libs/journeys/ui/src/components/BlockRenderer/index.ts
  libs/journeys/ui/src/components/Card/Cover/Cover.tsx
  libs/journeys/ui/src/components/Typography/Typography.spec.tsx
  libs/journeys/ui/src/components/Typography/Typography.tsx
  libs/journeys/ui/src/components/index.ts
  libs/journeys/ui/src/index.ts
Labels: priority: 2day, effort: 3, type: feature

#337 fix: Update signUp icon test
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.spec.tsx
Labels: type: fix, priority: soon, effort: 1

#317 feature: edit button actions
  apps/journeys-admin/__generated__/ActionDelete.ts
  apps/journeys-admin/__generated__/GetJourneyNames.ts
  apps/journeys-admin/__generated__/LinkActionUpdate.ts
  apps/journeys-admin/__generated__/NavigateActionUpdate.ts
  apps/journeys-admin/__generated__/NavigateToBlockActionUpdate.ts
  apps/journeys-admin/__generated__/NavigateToJourneyActionUpdate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/LinkAction/LinkAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/LinkAction/LinkAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/LinkAction/LinkAction.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/LinkAction/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateAction/NavigateAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateAction/NavigateAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateAction/NavigateAction.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateAction/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToBlockAction/NavigateToBlockAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToBlockAction/NavigateToBlockAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToBlockAction/NavigateToBlockAction.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToBlockAction/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/data.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Button/Button.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Button/Button.tsx
  apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx
  apps/journeys-admin/src/libs/apolloClient/cache.ts
  apps/journeys/src/libs/client/cache/cache.ts
Labels: priority: 2day, effort: 5, type: feature

#336 feature: Actions edit, signUp
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.tsx
Labels: priority: soon, type: feature, effort: 1

#340 feature: create api-languages
  .eslintrc.json
  .gitignore
  apps/api-gateway/project.json
  apps/api-gateway/schema.graphql
  apps/api-gateway/supergraph.yml
  apps/api-languages/.env.example
  apps/api-languages/.eslintrc.json
  apps/api-languages/Dockerfile
  apps/api-languages/db/db.ts
  apps/api-languages/db/seed.ts
  apps/api-languages/index.ts
  apps/api-languages/jest.config.js
  apps/api-languages/project.json
  apps/api-languages/schema.graphql
  apps/api-languages/src/app/.gitkeep
  apps/api-languages/src/app/__generated__/graphql.ts
  apps/api-languages/src/app/app.module.ts
  apps/api-languages/src/app/modules/language/language.graphql
  apps/api-languages/src/app/modules/language/language.module.ts
  apps/api-languages/src/app/modules/language/language.resolver.spec.ts
  apps/api-languages/src/app/modules/language/language.resolver.ts
  apps/api-languages/src/app/modules/language/language.service.spec.ts
  apps/api-languages/src/app/modules/language/language.service.ts
  apps/api-languages/src/app/modules/translation/translation.graphql
  apps/api-languages/src/app/modules/translation/translation.module.ts
  apps/api-languages/src/app/modules/translation/translation.resolver.spec.ts
  apps/api-languages/src/app/modules/translation/translation.resolver.ts
  apps/api-languages/src/assets/.gitkeep
  apps/api-languages/src/environments/environment.prod.ts
  apps/api-languages/src/environments/environment.ts
  apps/api-languages/src/generate-typings.ts
  apps/api-languages/src/main.ts
  apps/api-languages/tsconfig.app.json
  apps/api-languages/tsconfig.json
  apps/api-languages/tsconfig.spec.json
  libs/nest/decorators/src/lib/TranslationField/TranslationField.spec.ts
  libs/nest/decorators/src/lib/TranslationField/TranslationField.ts
  libs/nest/decorators/src/lib/TranslationField/index.ts
  libs/nest/decorators/src/lib/decorators.ts
  workspace.json
Labels: effort: 8, priority: now, type: feature

#335 feature: Actions edit, radioOption
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/RadioOption/RadioOption.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/RadioOption/RadioOption.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Drawer.tsx
Labels: priority: soon, type: feature, effort: 1

#345 feature: image block edit
  apps/journeys-admin/__generated__/ImageBlockUpdate.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Image.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Image.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Image.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/index.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
Labels: effort: 2, priority: soon, type: feature

#350 fix: filter parent order null
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
Labels: type: fix, priority: soon, effort: 1

#334 feature: add SignUp inline editing
  apps/journeys-admin/__generated__/SignUpBlockUpdateContent.ts
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/SignUpEdit/index.ts
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
Labels: effort: 2, priority: soon, type: feature

#347 feature: set next card
  apps/journeys-admin/__generated__/StepBlockDefaultNextBlockUpdate.ts
  apps/journeys-admin/__generated__/StepBlockNextBlockUpdate.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Cards/Cards.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Cards/Cards.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Cards/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Conditions/Conditions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Conditions/Conditions.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Conditions/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/NextCard.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/NextCard.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/NextCard.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.tsx
Labels: effort: 3, priority: soon, type: feature

#344 feature: video block
  apps/journeys-admin/__generated__/VideoBlockUpdate.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/index.ts
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
Labels: effort: 2, priority: soon, type: feature

#352 fix: blockDelete null parentBlockId
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/block.graphql
  apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.resolver.ts
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
Labels: type: fix, priority: soon, effort: 1

#355 style: match commitlint, pr branch and title
  dangerfile.ts
Labels: priority: now, effort: 1, type: style

#356 fix: Center selected card on Horizontal Select
  apps/journeys-admin/setupTests.tsx
  apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx
Labels: type: fix, priority: soon, effort: 1

#358 ci: add arclight api key
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-deploy.yml
Labels: priority: now, effort: 1, type: ci

#359 ci: split danger into its own workflow
  .github/workflows/danger.yml
  .github/workflows/main.yml
Labels: priority: now, effort: 1, type: ci

#362 fix: languages endpoint needs platform parameter
  apps/api-videos/db/seed.ts
Labels: priority: now, effort: 1, type: ci

#289 chore: add dependabot config
  .github/dependabot.yml
Labels: priority: 2day, effort: 1, type: chore

#323 feat: language filter drawer for video library
  apps/journeys-admin/__generated__/GetLanguages.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/LanguageFilter/Drawer/Drawer.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/LanguageFilter/Drawer/Drawer.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/LanguageFilter/Drawer/Drawer.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/LanguageFilter/Drawer/index.ts
Labels: effort: 3, priority: soon, type: feat

#367 fix: journeys-admin linting
  apps/journeys-admin/__generated__/GetLanguages.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/LanguageFilter/Drawer/Drawer.tsx
Labels: priority: now, effort: 1, type: style

#368 fix: github action conditionals
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-worker.yml
Labels: type: fix, priority: now, effort: 1

#361 feat: single video endpoint
  apps/api-gateway/project.json
  apps/api-gateway/schema.graphql
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
Labels: effort: 2, priority: now, type: feat

#369 ci: danger to check existing reviews too
  dangerfile.ts
Labels: priority: now, effort: 1, type: ci

#370 fix: version lock winston-cloudwatch
  package-lock.json
  package.json
Labels: type: fix, priority: now, effort: 1, dependencies

#371 fix: supergraph endpoint
  apps/api-gateway/supergraph-main.yml
  apps/api-gateway/supergraph-stage.yml
Labels: type: fix, priority: now, effort: 1

#353 fix: disable background video autoplay & mute
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
Labels: priority: 2day, type: fix, effort: 1

#357 chore: fix test case warnings
  apps/journeys-admin/setupTests.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Button/Size/Size.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/RadioOption/RadioOption.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.spec.tsx
  libs/journeys/ui/src/components/Image/Image.tsx
Labels: priority: 2day, effort: 1, type: chore

#364 fix: add bottom margin to radio question
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.stories.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
Labels: type: fix, priority: soon, effort: 1

#354 chore: update nest apollo
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/generate-typings.ts
  apps/api-languages/src/app/app.module.ts
  apps/api-languages/src/generate-typings.ts
  apps/api-users/src/app/app.module.ts
  apps/api-users/src/generate-typings.ts
  apps/api-videos/src/app/app.module.ts
  apps/api-videos/src/generate-typings.ts
  package-lock.json
  package.json
Labels: priority: 2day, effort: 2, type: chore

#379 fix: resolved warnings from journeys-admin specs
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.tsx
Labels: type: fix, priority: soon, effort: 1

#363 fix: update node to v16
  .devcontainer/Dockerfile
  .devcontainer/docker-compose.yml
  .github/workflows/danger.yml
  .github/workflows/main.yml
  apps/api-gateway/Dockerfile
  apps/api-journeys/Dockerfile
  apps/api-languages/Dockerfile
  apps/api-users/Dockerfile
  apps/api-videos/Dockerfile
  dangerfile.ts
  package-lock.json
Labels: priority: 2day, type: fix, effort: 1, dependencies

#349 fix: image speed
  apps/api-journeys/Dockerfile
  apps/api-journeys/src/app/modules/block/image/image.resolver.ts
  package-lock.json
  package.json
Labels: priority: 2day, effort: 2, type: fix

#374 feat: delete block ui
  apps/journeys-admin/__generated__/BlockDelete.ts
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/pages/journeys/[journeySlug]/edit.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteDialog/DeleteDialog.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteDialog/DeleteDialogue.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteDialog/DeleteDialogue.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteDialog/index.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/index.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/utils/getSelected.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/utils/getSelected.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/index.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/index.ts
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/data.ts
  libs/journeys/ui/src/index.ts
  libs/journeys/ui/src/libs/context/EditorContext.tsx
  libs/journeys/ui/src/libs/context/index.ts
  libs/journeys/ui/src/libs/index.ts
Labels: effort: 5, priority: soon, type: feat

#387 fix: remove keyasid from resolver
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.ts
Labels: type: fix, priority: now, effort: 1

#392 fix: conditions description
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Conditions/Conditions.tsx
Labels: type: fix, priority: soon, effort: 1

#390 fix: allow not found journey
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/journeys/pages/[journeySlug].tsx
Labels: type: fix, effort: 3, priority: now

#351 chore: self-closing eslint rule
  .eslintrc.json
  .github/workflows/main.yml
  apps/api-journeys/src/app/lib/roleGuard/roleGuard.spec.ts
  apps/api-journeys/src/app/modules/block/image/image.resolver.ts
  apps/journeys-admin/.eslintrc.json
  apps/journeys-admin/index.d.ts
  apps/journeys-admin/next.config.js
  apps/journeys-admin/setupTests.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Image.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.ts
  apps/journeys/.eslintrc.json
  apps/journeys/index.d.ts
  apps/journeys/next.config.js
  libs/journeys/ui/.eslintrc.json
  libs/journeys/ui/src/components/Button/Button.stories.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Image/Image.spec.tsx
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/libs/useBlocks/blocks.ts
  libs/shared/ui/src/libs/storybook/decorators.tsx
  libs/shared/ui/src/libs/themes/base/theme.stories.tsx
  libs/shared/util-graphql/src/lib/schemaBuilder/schemaBuilder.ts
Labels: priority: 2day, effort: 1, type: chore

#381 refactor: last child on card and typography input styling
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Card/Cover/Cover.tsx
  libs/journeys/ui/src/components/GridContainer/GridContainer.tsx
  libs/journeys/ui/src/components/GridContainer/GridItem/GridItem.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/Typography/Typography.tsx
  libs/journeys/ui/src/libs/storybook/containers.tsx
  libs/shared/ui/src/libs/themes/base/tokens/components.ts
Labels: effort: 2, priority: soon, type: refactor

#389 chore: k8s update
  .github/workflows/api-gateway-worker.yml
  apps/api-gateway/supergraph-main.yml
  apps/api-gateway/supergraph-stage.yml
  resources/kube/api/api-gateway-main-deployment.yaml
  resources/kube/api/api-gateway-main-service.yaml
  resources/kube/api/api-gateway-stage-deployment.yaml
  resources/kube/api/api-gateway-stage-service.yaml
  resources/kube/api/api-journeys-main-deployment.yaml
  resources/kube/api/api-journeys-main-service.yaml
  resources/kube/api/api-journeys-stage-deployment.yaml
  resources/kube/api/api-journeys-stage-service.yaml
  resources/kube/api/api-users-main-deployment.yaml
  resources/kube/api/api-users-main-service.yaml
  resources/kube/api/api-users-stage-deployment.yaml
  resources/kube/api/api-users-stage-service.yaml
  resources/kube/api/deploy-main.sh
  resources/kube/api/deploy-stage.sh
  resources/kube/arangodb/arangodb-deployment.yaml
  resources/kube/arangodb/arangodb-service.yaml
  resources/kube/arangodb/deploy.sh
  resources/kube/storage/storageclass.yaml
Labels: priority: 2day, breaking, effort: 3, type: build

#393 fix: typo
  .github/workflows/api-gateway-worker.yml
Labels: type: fix, priority: now, effort: 1

#396 feat: link access button
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.tsx
Labels: priority: soon, type: feat, effort: 1

#395 refactor: correct reversed card layout
  apps/journeys-admin/public/card-layout-contained.svg
  apps/journeys-admin/public/card-layout-expanded.svg
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.tsx
Labels: priority: soon, effort: 1, type: refactor

#398 refactor: removed extra divider
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
Labels: priority: soon, effort: 1, type: refactor

#400 fix: sibling for block delete
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
Labels: type: fix, priority: now, effort: 1

#401 fix: clears url on delete
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
Labels: type: fix, priority: soon, effort: 1

#399 style: background video
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/components/ThemeProvider/admin/tokens/typography.ts
Labels: priority: soon, effort: 1, type: style

#407 chore: cleanup chromatic configs, simplify
  .storybook/preview.js
  CONTRIBUTING.md
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attribute/Attribute.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Icon/Color/Color.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/NextCard.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/ThemeProvider/admin/theme.stories.tsx
  apps/journeys-admin/src/libs/storybook/config.tsx
  apps/journeys/src/libs/storybook/config.tsx
  libs/journeys/ui/src/libs/storybook/config.tsx
  libs/shared/ui/src/components/CopyTextField/CopyTextField.stories.tsx
  libs/shared/ui/src/index.ts
  libs/shared/ui/src/libs/storybook/config.tsx
  libs/shared/ui/src/libs/themes/base/theme.stories.tsx
Labels: effort: 2, priority: now, type: docs, type: chore

#402 fix: image tab stays open when background image is deleted
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
Labels: type: fix, priority: soon, effort: 1

#404 fix: flakey navigateToBlockAction spec
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToBlockAction/NavigateToBlockAction.spec.tsx
Labels: type: fix, priority: soon, effort: 1

#408 fix: slow test timeout
  apps/journeys-admin/setupTests.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.spec.tsx
  apps/journeys/setupTests.ts
Labels: effort: 2, type: fix, priority: soon

#409 feat: fix link action
  libs/journeys/ui/src/libs/action/handleAction.spec.ts
  libs/journeys/ui/src/libs/action/handleAction.ts
Labels: type: fix, priority: soon, effort: 1

#411 fix: button margin-top - match storybook to production
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
  apps/journeys/src/libs/storybook/containers.tsx
  apps/journeys/src/libs/storybook/index.ts
  libs/journeys/ui/src/components/Button/Button.stories.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Card/Cover/Cover.tsx
  libs/journeys/ui/src/components/GridContainer/GridContainer.tsx
  libs/journeys/ui/src/components/GridContainer/GridItem/GridItem.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioOption/RadioOption.tsx
  libs/journeys/ui/src/libs/storybook/containers.tsx
  libs/shared/ui/src/libs/themes/base/tokens/components.ts
Labels: priority: 2day, effort: 2, type: fix

#403 refactor: selectable wrapper
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/index.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Image/Image.spec.tsx
  libs/journeys/ui/src/components/Image/Image.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioOption/RadioOption.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioOption/RadioOption.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/Typography/Typography.spec.tsx
  libs/journeys/ui/src/components/Typography/Typography.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: effort: 3, priority: soon, type: refactor

#410 feat: inline edit radio option
  apps/journeys-admin/__generated__/RadioOptionBlockUpdateContent.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/index.ts
  libs/journeys/ui/src/components/RadioQuestion/RadioOption/RadioOption.tsx
Labels: effort: 2, priority: soon, type: feat

#416 fix: journeys edit dialogs
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.tsx
Labels: type: fix, priority: soon, effort: 1

#422 chore: update base image to typescript-node 16-bullseye
  .devcontainer/Dockerfile
Labels: priority: now, effort: 1, type: chore

#423 chore: download rover from github on m1
  tools/scripts/install-rover.sh
Labels: priority: now, effort: 1, type: chore

#427 fix: api deploy worker to compare previous head
  .github/workflows/api-deploy-worker.yml
  apps/api-journeys/db/seed.ts
  apps/api-languages/db/seed.ts
  apps/api-users/db/seed.ts
  apps/api-videos/db/seed.ts
Labels: priority: 2day, type: fix, effort: 1

#430 fix: affected scripts for app seed and apps
  .github/workflows/api-deploy-worker.yml
  apps/api-journeys/db/seed.ts
  apps/api-languages/db/seed.ts
  apps/api-users/db/seed.ts
  apps/api-videos/db/seed.ts
Labels: type: fix, priority: now, effort: 1

#431 ci: use cache npm
  .github/workflows/danger.yml
  .github/workflows/main.yml
Labels: priority: 2day, effort: 1, type: ci

#412 fix: editor access
  apps/journeys-admin/__generated__/GetCurrentUser.ts
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
Labels: type: fix, effort: 3, priority: soon

#434 refactor: edit redirect link
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.tsx
Labels: priority: soon, effort: 1, type: refactor

#413 feat: inline edit radio question
  apps/journeys-admin/__generated__/RadioQuestionBlockUpdateContent.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditInput/InlineEditInput.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditInput/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioOption/RadioOption.stories.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.stories.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
Labels: effort: 2, priority: soon, type: feat, type: style

#438 chore: add execution to post create command
  .devcontainer/post-create-command.sh
Labels: priority: now, effort: 1, type: chore

#441 fix: revert arango to 3.8.6
  .devcontainer/docker-compose.yml
Labels: type: fix, effort: 3, priority: now

#442 feat: watch routing
  apps/watch/next.config.js
  apps/watch/pages/[...slug].tsx
  apps/watch/pages/index.tsx
  apps/watch/pages/videos/[...tag].tsx
  apps/watch/pages/videos/index.tsx
  apps/watch/src/components/Videos/VideoInfo/VideoInfo.tsx
  apps/watch/src/components/Videos/Videos.tsx
  apps/watch/src/libs/routeParser/routeParser.spec.ts
  apps/watch/src/libs/routeParser/routeParser.ts
Labels: effort: 3, priority: soon, type: feat
