Repository JesusFilm/core, pull requests merged in 2022-04, with the labels that each got.

#444 fix: disable video if no language
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Labels: type: fix, priority: now, effort: 1

#426 build: environment variable setup
  apps/api-journeys/.env.example
  apps/api-users/.env
  apps/api-users/.env.example
  apps/journeys/.env.example
  apps/watch/.env.example
Labels: priority: 2day, effort: 1, type: build

#448 chore: update material imports
  .eslintrc.json
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Icon/Icon.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Image.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Cards/Cards.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Conditions/Conditions.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/NextCard.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Drawer.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/VideoBlockEditorSource.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/LanguageFilter/Drawer/Drawer.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/JourneyDetails.tsx
  apps/watch-admin/src/components/PageWrapper/PageWrapper.tsx
  apps/watch/src/components/Videos/VideoList/Card/VideoListCard.tsx
  apps/watch/src/components/Videos/VideoList/Carousel/VideoListCarousel.tsx
  apps/watch/src/components/Videos/VideoList/Grid/VideoListGrid.tsx
  apps/watch/src/components/Videos/VideoList/List/VideoListList.tsx
  libs/journeys/ui/src/components/Icon/Icon.stories.tsx
  libs/journeys/ui/src/components/Icon/Icon.tsx
  libs/shared/ui/src/libs/themes/base/theme.stories.tsx
  libs/shared/ui/src/libs/themes/base/tokens/breakpoints.ts
Labels: priority: 2day, effort: 1, type: chore

#454 fix: journeys-admin letter spacing
  apps/journeys-admin/src/components/ThemeProvider/admin/tokens/typography.ts
Labels: type: fix, priority: now, effort: 1

#378 feat: video details
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  apps/journeys-admin/__generated__/GetVideo.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/VideoBlockEditorSource.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/VideoBlockEditorSource.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/index.ts
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/index.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoList.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoListData.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoListItem/VideoListItem.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoListItem/VideoListItem.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoListItem/VideoListItem.tsx
  apps/journeys-admin/src/components/ThemeProvider/admin/tokens/components.ts
Labels: effort: 3, priority: now, type: feat

#433 feat: common dialog component
  .storybook/preview-head.html
  apps/journeys-admin/pages/_document.tsx
  apps/journeys-admin/src/components/Dialog/Dialog.spec.tsx
  apps/journeys-admin/src/components/Dialog/Dialog.stories.tsx
  apps/journeys-admin/src/components/Dialog/Dialog.tsx
  apps/journeys-admin/src/components/Dialog/index.ts
  apps/journeys-admin/src/components/ThemeProvider/admin/tokens/typography.ts
Labels: effort: 2, priority: now, type: feat

#457 fix: change page to offset
  apps/api-gateway/schema.graphql
  apps/api-languages/schema.graphql
  apps/api-languages/src/app/__generated__/graphql.ts
  apps/api-languages/src/app/modules/language/language.graphql
  apps/api-languages/src/app/modules/language/language.resolver.ts
  apps/api-languages/src/app/modules/language/language.service.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
Labels: breaking, type: fix, priority: now, effort: 1

#443 fix: sign up button loading state
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.stories.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/test/ApolloLoadingProvider.tsx
Labels: type: fix, priority: soon, effort: 1

#452 feat: link new card to previous card
  apps/journeys-admin/__generated__/StepBlockNextBlockIdUpdate.ts
  apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
Labels: priority: soon, type: feat, effort: 1

#459 chore: add storybook jest
  package-lock.json
  package.json
Labels: priority: now, effort: 1, type: chore

#462 fix: button/radioOption/sign up link actions triggering onClick in admin
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.tsx
Labels: effort: 2, type: fix, priority: soon

#380 feat: video search
  apps/journeys-admin/__generated__/GetVideo.ts
  apps/journeys-admin/__generated__/GetVideos.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoList.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoList.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoList.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoListData.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoListItem/VideoListItem.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoSearch/VideoSearch.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoSearch/VideoSearch.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoSearch/VideoSearch.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoSearch/index.ts
  apps/journeys-admin/src/libs/apolloClient/cache.ts
Labels: priority: now, type: feat, effort: 1

#451 feat: api videos playlist
  apps/api-gateway/schema.graphql
  apps/api-videos/db/seed.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  apps/api-videos/src/app/modules/videoVariant/videoVariant.graphql
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockCreate.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockUpdate.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetVideo.ts
  apps/journeys-admin/__generated__/VideoBlockCreate.ts
  apps/journeys-admin/__generated__/VideoBlockUpdate.ts
  apps/journeys-admin/__generated__/VideoFields.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.tsx
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/VideoFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/GetVideos.ts
  apps/watch/__generated__/VideoFields.ts
  apps/watch/__generated__/globalTypes.ts
  apps/watch/pages/index.tsx
  apps/watch/src/components/Videos/VideoList/Card/VideoListCard.tsx
  apps/watch/src/components/Videos/VideoList/VideoList.spec.tsx
  apps/watch/src/components/Videos/VideoList/VideoList.tsx
  apps/watch/src/components/Videos/VideoList/testData.ts
  apps/watch/src/components/Videos/Videos.tsx
  apps/watch/src/libs/client/cache/cache.ts
  libs/journeys/ui/src/components/Video/__generated__/VideoFields.ts
  libs/journeys/ui/src/libs/transformer/__generated__/BlockFields.ts
Labels: effort: 8, priority: soon, type: feat

#417 feat: add radio option button
  apps/journeys-admin/__generated__/RadioOptionBlockCreate.ts
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/index.ts
  libs/journeys/ui/src/components/RadioQuestion/RadioOption/RadioOption.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioOption/index.ts
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/index.ts
  libs/journeys/ui/src/index.ts
Labels: priority: 2day, effort: 2, type: feat

#467 fix: watch admin api
  apps/watch-admin/.env.production
  apps/watch-admin/pages/api/login.tsx
  apps/watch-admin/pages/api/logout.tsx
  apps/watch-admin/public/site.webmanifest
  apps/watch-admin/setupTests.tsx
  apps/watch-admin/src/libs/apolloClient/cache.ts
  apps/watch-admin/tsconfig.json
Labels: type: fix, priority: soon, effort: 1

#468 feat: api-video tags
  apps/api-gateway/schema.graphql
  apps/api-videos/db/seed.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/app.module.ts
  apps/api-videos/src/app/modules/tag/tag.graphql
  apps/api-videos/src/app/modules/tag/tag.module.ts
  apps/api-videos/src/app/modules/tag/tag.resolver.spec.ts
  apps/api-videos/src/app/modules/tag/tag.resolver.ts
  apps/api-videos/src/app/modules/tag/tag.service.spec.ts
  apps/api-videos/src/app/modules/tag/tag.service.ts
  apps/api-videos/src/app/modules/tag/testData.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/GetVideoTag.ts
  apps/watch/__generated__/globalTypes.ts
  apps/watch/pages/index.tsx
Labels: effort: 8, priority: soon, type: feat

#465 fix: fade previous slide
  apps/journeys/src/components/Conductor/Conductor.tsx
Labels: type: fix, priority: now, effort: 1

#471 fix: stop admin video playing
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.spec.tsx
  libs/journeys/ui/src/components/Card/Cover/Cover.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: effort: 5, type: fix, priority: now

#470 feat: added social title and description
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: priority: soon, type: feat, effort: 1

#476 feat: add seo fields to journey
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
Labels: type: fix, priority: now, effort: 1

#473 refactor: extract out blurImage to reuse in video and image
  libs/journeys/ui/src/components/Card/Cover/Cover.tsx
  libs/journeys/ui/src/index.ts
  libs/journeys/ui/src/libs/blurImage/blurImage.spec.ts
  libs/journeys/ui/src/libs/blurImage/blurImage.ts
  libs/journeys/ui/src/libs/blurImage/index.ts
  libs/journeys/ui/src/libs/index.ts
Labels: priority: 2day, effort: 1, type: refactor

#450 fix: typography delete when content is empty
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/index.ts
Labels: effort: 2, type: fix, priority: soon

#475 feat: Additional api videos fields
  apps/api-gateway/schema.graphql
  apps/api-videos/db/seed.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
Labels: effort: 2, priority: soon, type: feat

#458 fix: removed video controls unless in fullscreen
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: effort: 2, type: fix, priority: soon

#478 feat: replace mui alert for notistack for title and description dialog
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.tsx
Labels: priority: soon, type: feat, effort: 1

#482 fix: allow autoplay on safari
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: type: fix, priority: now, effort: 1

#435 docs: added and refactored contributing for new api projects
  CONTRIBUTING.md
Labels: type: docs, priority: soon, effort: 1

#385 feat: video feedback
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.tsx
Labels: priority: 2day, effort: 2, type: feat

#384 feat: image feedback
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.tsx
Labels: priority: 2day, effort: 2, type: feat

#474 feat: Add placeholder blur to image
  libs/journeys/ui/src/components/Card/Card.stories.tsx
  libs/journeys/ui/src/components/Card/Cover/Cover.tsx
  libs/journeys/ui/src/components/Image/Image.spec.tsx
  libs/journeys/ui/src/components/Image/Image.stories.tsx
  libs/journeys/ui/src/components/Image/Image.tsx
  libs/journeys/ui/src/libs/blurImage/blurImage.spec.ts
  libs/journeys/ui/src/libs/blurImage/blurImage.ts
Labels: priority: 2day, effort: 2, type: feat

#487 docs: pr naming
  CONTRIBUTING.md
Labels: priority: now, type: docs, effort: 1

#489 fix: update commitlint version
  .github/workflows/main.yml
Labels: type: fix, priority: now, effort: 1

#425 fix: background color selection and change
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/PaletteColorPicker/PaletteColorPicker.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/PaletteColorPicker/PaletteColorPicker.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/PaletteColorPicker/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/Swatch/Swatch.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/Swatch/Swatch.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/Swatch/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.tsx
Labels: type: test, priority: 2day, type: fix, effort: 3, type: refactor

#491 fix: restrain card hight on mobile landscape
  apps/journeys/src/components/Conductor/Conductor.tsx
Labels: effort: 2, type: fix, priority: now

#483 fix: navigation drawer
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/journeys/[journeySlug].tsx
  apps/journeys-admin/pages/journeys/[journeySlug]/edit.tsx
  apps/journeys-admin/public/nextsteps-title.svg
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/UserMenu.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/UserMenu.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/UserMenu.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/index.ts
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/index.ts
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
  apps/watch-admin/src/components/PageWrapper/PageWrapper.stories.tsx
Labels: effort: 5, type: fix, priority: soon

#481 fix: add native controls to video
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: type: fix, priority: soon, effort: 1

#490 feat: show video title
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockCreate.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockUpdate.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/VideoBlockCreate.ts
  apps/journeys-admin/__generated__/VideoBlockUpdate.ts
  apps/journeys-admin/__generated__/VideoFields.ts
  apps/journeys-admin/setupTests.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/VideoFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.stories.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/journeys/ui/src/components/Video/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/Video/videoFields.ts
  libs/journeys/ui/src/libs/transformer/__generated__/BlockFields.ts
Labels: priority: now, type: feat, effort: 1

#492 feat: show video image
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockCreate.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockUpdate.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/VideoBlockCreate.ts
  apps/journeys-admin/__generated__/VideoBlockUpdate.ts
  apps/journeys-admin/__generated__/VideoFields.ts
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/VideoFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.stories.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/journeys/ui/src/components/Video/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/Video/videoFields.ts
  libs/journeys/ui/src/libs/transformer/__generated__/BlockFields.ts
Labels: priority: now, type: feat, effort: 1

#495 feat: add google tag manager to journeys projects
  apps/journeys-admin/.env.example
  apps/journeys-admin/pages/_app.tsx
  apps/journeys/.env.example
  apps/journeys/pages/_app.tsx
  package-lock.json
  package.json
Labels: effort: 3, priority: now, type: feat

#493 fix: hide journey progress bar
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
Labels: effort: 2, type: fix, priority: now

#497 fix: blurImage returns undefiend when creating new imageBlock
  libs/journeys/ui/src/libs/blurImage/blurImage.spec.ts
  libs/journeys/ui/src/libs/blurImage/blurImage.ts
Labels: type: fix, priority: now, effort: 1

#498 fix: apollo reload client on token change
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
  apps/journeys-admin/src/libs/apolloClient/index.ts
Labels: effort: 5, type: fix, priority: now

#485 feat: add social drawer
  apps/journeys-admin/__generated__/BlockDeletePrimaryImage.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/JourneyPrimaryImageUpdate.ts
  apps/journeys-admin/__generated__/JourneySeoDescriptionUpdate.ts
  apps/journeys-admin/__generated__/JourneySeoTitleUpdate.ts
  apps/journeys-admin/__generated__/PrimaryImageBlockCreate.ts
  apps/journeys-admin/__generated__/PrimaryImageBlockUpdate.ts
  apps/journeys-admin/pages/journeys/[journeySlug].tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/DescriptionEdit/DescriptionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/DescriptionEdit/DescriptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.stories.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/TitleEdit/TitleEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/TitleEdit/TitleEdit.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/data.ts
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys-admin/src/libs/context/JourneyContext.spec.tsx
Labels: effort: 8, priority: now, type: feat

#494 feat: social share
  apps/journeys-admin/__generated__/GetJourneys.ts
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/DescriptionEdit/DescriptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.stories.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/TitleEdit/TitleEdit.tsx
  apps/journeys-admin/src/components/JourneyList/journeyListData.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/pages/[journeySlug].tsx
Labels: effort: 2, priority: now, type: feat

#502 refactor: journey language field
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/seeds/nua1.ts
  apps/api-journeys/db/seeds/nua2.ts
  apps/api-journeys/db/seeds/nua8.ts
  apps/api-journeys/db/seeds/nua9.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/journey/journey.service.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.service.spec.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetJourneys.ts
  apps/journeys-admin/__generated__/JourneyCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/journeys/[journeySlug].tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.spec.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.stories.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
  apps/journeys-admin/src/components/JourneyList/journeyListData.ts
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/JourneyDetails.tsx
  apps/journeys-admin/src/components/JourneyView/data.ts
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys-admin/src/libs/context/JourneyContext.spec.tsx
Labels: breaking, effort: 3, priority: now, type: refactor

#505 fix: publish should update status and snackbar
  apps/journeys-admin/__generated__/JourneyPublish.ts
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Alert/Alert.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Alert/Alert.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Alert/index.ts
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
Labels: type: fix, effort: 3, priority: now

#506 fix: no language resolve reference
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.service.spec.ts
  apps/api-languages/src/app/modules/language/language.resolver.spec.ts
  apps/api-languages/src/app/modules/language/language.resolver.ts
Labels: type: fix, priority: now, effort: 1

#484 feat: video poster blur
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.stories.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Card/Cover/ContentOverlay/ContentOverlay.tsx
  libs/journeys/ui/src/components/Card/Cover/ContentOverlay/index.ts
  libs/journeys/ui/src/components/Card/Cover/Cover.tsx
  libs/journeys/ui/src/components/Image/Image.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/libs/blurImage/blurImage.spec.ts
  libs/shared/ui/src/components/CopyTextField/CopyTextField.spec.tsx
  libs/shared/ui/src/components/NextImage/NextImage.spec.tsx
  libs/shared/ui/src/components/NextImage/NextImage.tsx
  libs/shared/ui/src/components/NextImage/index.ts
  libs/shared/ui/src/index.ts
Labels: priority: 2day, effort: 5, type: fix

#511 feat: add dd-rum-agent
  apps/journeys-admin/.env.example
  apps/journeys-admin/pages/_app.tsx
  apps/journeys/.env.example
  apps/journeys/pages/_app.tsx
  package-lock.json
  package.json
Labels: effort: 2, priority: now, type: feat

#512 feat: prod source maps
  apps/journeys-admin/next.config.js
  apps/journeys/next.config.js
Labels: priority: now, type: feat, effort: 1

#513 fix: cover should allow for missing image block
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Card/Cover/Cover.tsx
Labels: type: fix, priority: now, effort: 1

#507 fix: value in copy text field
  libs/shared/ui/src/components/CopyTextField/CopyTextField.spec.tsx
  libs/shared/ui/src/components/CopyTextField/CopyTextField.tsx
Labels: type: fix, priority: now, effort: 1

#510 fix: social share
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/DescriptionEdit/DescriptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/TitleEdit/TitleEdit.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  apps/journeys/.env.example
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/pages/[journeySlug].tsx
Labels: effort: 2, type: fix, priority: soon

#503 fix: video aspect ratio
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: effort: 2, type: fix, priority: soon

#516 fix: og url
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.spec.tsx
  apps/journeys/pages/[journeySlug].tsx
Labels: type: fix, priority: now, effort: 1

#504 fix: cardBlock sets null parentOrder on coverBlocks
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/card/card.graphql
  apps/api-journeys/src/app/modules/block/image/image.graphql
  apps/api-journeys/src/app/modules/block/image/image.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/image/image.resolver.ts
  apps/api-journeys/src/app/modules/block/video/video.graphql
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: priority: 2day, effort: 2, type: fix

#515 fix: move blocks update all api
  apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.resolver.ts
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
Labels: priority: 2day, effort: 2, type: fix

#518 fix: background media mutations
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.tsx
Labels: priority: 2day, effort: 2, type: fix

#519 fix: removed grid and updated radio question label
  apps/api-journeys/db/seeds/nua1.ts
  apps/api-journeys/db/seeds/nua2.ts
  apps/api-journeys/db/seeds/nua8.ts
  apps/api-journeys/db/seeds/nua9.ts
Labels: type: fix, priority: now, effort: 1

#517 feat: featured journeys
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/seeds/nua1.ts
  apps/api-journeys/db/seeds/nua2.ts
  apps/api-journeys/db/seeds/nua8.ts
  apps/api-journeys/db/seeds/nua9.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/journey/journey.service.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.service.ts
Labels: priority: now, type: feat, effort: 1

#520 feat: show featured on journeys list
  apps/journeys/pages/index.tsx
Labels: priority: 2day, type: feat, effort: 1

#524 fix: cache blurImage url
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Card/Cover/Cover.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: priority: now, effort: 1, type: perf

#525 fix: add action to video block
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/video/video.graphql
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Labels: type: fix, priority: soon, effort: 1

#521 feat: watch front end languages
  apps/watch/next.config.js
Labels: priority: soon, type: feat, effort: 1

#526 fix: create card background as cover
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.tsx
Labels: priority: 2day, type: fix, effort: 1

#523 feat: image loading state
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.tsx
Labels: effort: 5, priority: soon, type: feat

#522 fix: add radio question typography
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewRadioQuestionButton/NewRadioQuestionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewRadioQuestionButton/NewRadioQuestionButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewTypographyButton/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
Labels: type: fix, priority: soon, effort: 1

#531 fix: add fonts to iframe preview
  apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
Labels: type: fix, priority: now, effort: 1

#533 fix: add fonts to iframe preview vr update
  apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
Labels: type: fix, priority: now, effort: 1

#529 fix: update action field in video
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/action/action.resolver.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.ts
  apps/api-journeys/src/app/modules/block/video/video.graphql
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Labels: type: fix, priority: now, effort: 1

#527 fix: radio question remove inbuilt question and description - frontend
  apps/journeys-admin/__generated__/RadioQuestionBlockUpdateContent.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/data.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/data.ts
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.stories.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/index.ts
  libs/journeys/ui/src/index.ts
Labels: priority: 2day, type: fix, effort: 3

#500 feat: episode api and display
  apps/api-gateway/schema.graphql
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  apps/watch/__generated__/GetVideo.ts
  apps/watch/__generated__/GetVideoSiblings.ts
  apps/watch/pages/[...slug].tsx
  apps/watch/src/components/Videos/VideoList/List/VideoListList.tsx
Labels: priority: 2day, effort: 5, type: feat

#469 feat: add-page-titebar
  apps/watch-admin/src/components/PageWrapper/PageWrapper.tsx
  apps/watch/__generated__/GetVideoTag.ts
  apps/watch/jest.config.js
  apps/watch/pages/_document.tsx
  apps/watch/pages/index.tsx
  apps/watch/public/taskbar-icon.svg
  apps/watch/setupTests.ts
  apps/watch/setupTests.tsx
  apps/watch/src/components/PageWrapper/PageWrapper.spec.tsx
  apps/watch/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/watch/src/components/PageWrapper/PageWrapper.tsx
  apps/watch/src/components/PageWrapper/index.tsx
  apps/watch/src/components/Videos/VideoList/Grid/VideoListGrid.tsx
  apps/watch/src/components/Videos/VideoList/VideoList.spec.tsx
  apps/watch/src/components/Videos/VideoList/VideoList.tsx
  apps/watch/src/libs/client/cache/cache.ts
  apps/watch/tsconfig.json
Labels: priority: soon, type: feat, effort: 1

#534 fix: end at field for video
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockCreate.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockUpdate.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/VideoBlockCreate.ts
  apps/journeys-admin/__generated__/VideoBlockUpdate.ts
  apps/journeys-admin/__generated__/VideoFields.ts
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToBlockAction/NavigateToBlockAction.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/VideoFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.stories.tsx
  libs/journeys/ui/src/components/Card/Cover/Cover.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/VideoTrigger/VideoTrigger.tsx
  libs/journeys/ui/src/components/Video/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/Video/videoFields.ts
  libs/journeys/ui/src/libs/transformer/__generated__/BlockFields.ts
Labels: type: fix, effort: 3, priority: now

#535 feat: add cache invalidation when previewing
  apps/journeys-admin/.env.example
  apps/journeys-admin/pages/api/preview.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  apps/journeys/.env.example
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/pages/api/revalidate.ts
  apps/journeys/pages/index.tsx
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/JourneyProgress/JourneyProgress.spec.tsx
  apps/journeys/src/libs/client/cache/cache.ts
  apps/journeys/src/libs/client/client.ts
  apps/journeys/src/libs/client/index.ts
  apps/journeys/test/testingLibrary.tsx
  package-lock.json
  package.json
Labels: effort: 5, priority: now, type: feat

#537 fix: card background cover display
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
  libs/journeys/ui/src/components/Card/Card.stories.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Card/Cover/ContentOverlay/ContentOverlay.tsx
  libs/journeys/ui/src/components/Card/Cover/Cover.tsx
Labels: priority: 2day, effort: 2, type: fix

#540 fix: where headers were set after sent to client
  apps/journeys-admin/pages/api/preview.ts
Labels: type: fix, priority: now, effort: 1

#542 fix: update preview icons and href, update tests
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
Labels: effort: 2, type: fix, priority: now

#543 feat: preview return error state
  apps/journeys-admin/pages/api/preview.ts
Labels: type: fix, priority: now, effort: 1

#544 fix: use access token not secret
  apps/journeys/pages/api/revalidate.ts
Labels: type: fix, priority: now, effort: 1

#538 feat: multi language permalink
  apps/api-gateway/schema.graphql
  apps/api-videos/db/seed.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  apps/watch/__generated__/GetVideo.ts
  apps/watch/__generated__/GetVideoSiblings.ts
  apps/watch/__generated__/GetVideos.ts
  apps/watch/pages/[...slug].tsx
  apps/watch/src/components/Videos/VideoList/Card/VideoListCard.tsx
  apps/watch/src/components/Videos/VideoList/List/VideoListList.tsx
  apps/watch/src/components/Videos/VideoList/VideoList.tsx
  apps/watch/src/components/Videos/VideoList/testData.ts
Labels: priority: 2day, effort: 3, type: feat

#536 feat: save image on paste
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
Labels: priority: soon, type: feat, effort: 1

#532 feat: added loading state to poster image
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.tsx
Labels: effort: 3, priority: soon, type: feat

#541 fix: video duration as default value for endat
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoList.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoListItem/VideoListItem.tsx
Labels: effort: 2, type: fix, priority: soon

#548 fix: video playing in next card properties
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
Labels: type: fix, priority: soon, effort: 1
