Repository JesusFilm/core, pull requests merged in 2023-01, with the labels that each got.

#1202 fix: gateway cors jesusfilm
  apps/api-gateway/src/environments/environment.prod.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1203 feat: gateway jesusfilm cors 2
  apps/api-gateway/src/environments/environment.prod.ts
Labels: priority: now, type: feat, effort: 1

#1196 chore: bump firebase-admin
  package-lock.json
  package.json
Labels: priority: 2day, effort: 1, type: chore, on stage

#1194 feat: service sizing
  apps/api-gateway/infrastructure/locals.tf
  apps/api-journeys/infrastructure/locals.tf
  apps/api-languages/infrastructure/locals.tf
  infrastructure/environments/stage/data.tf
Labels: priority: 2day, effort: 2, type: feat

#1195 ci: update github base actions
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-prod-worker.yml
  .github/workflows/api-gateway-stage-worker.yml
  .github/workflows/crowdin.yml
  .github/workflows/danger.yml
  .github/workflows/etl-deploy.yml
  .github/workflows/main.yml
Labels: priority: 2day, effort: 2, type: ci

#1197 chore: bump rover
  .devcontainer/post-create-command.sh
  .github/workflows/api-gateway-prod-worker.yml
  .github/workflows/api-gateway-stage-worker.yml
  apps/api-gateway/schema.graphql
  tools/scripts/install-rover.sh
Labels: priority: 2day, effort: 1, type: chore, on stage

#1199 feat: delete stage k8s
  resources/kube/api/api-gateway-stage-deployment.yaml
  resources/kube/api/api-gateway-stage-service.yaml
  resources/kube/api/api-journeys-stage-deployment.yaml
  resources/kube/api/api-journeys-stage-service.yaml
  resources/kube/api/api-languages-stage-deployment.yaml
  resources/kube/api/api-languages-stage-service.yaml
  resources/kube/api/api-users-stage-deployment.yaml
  resources/kube/api/api-users-stage-service.yaml
  resources/kube/api/api-videos-stage-deployment.yaml
  resources/kube/api/api-videos-stage-service.yaml
Labels: priority: 2day, type: feat, effort: 1

#1207 chore: add source maps to prod watch
  apps/watch/next.config.js
Labels: priority: now, effort: 1, type: chore

#1210 fix: render title only on feature films
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
Labels: type: fix, priority: soon, effort: 1

#1214 refactor: update featured lumo collections
  apps/watch/pages/index.tsx
Labels: priority: soon, effort: 1, type: refactor

#1209 refactor: remove use location state
  apps/watch/src/components/VideosPage/CurrentFilters/CurrentFilters.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
  package-lock.json
  package.json
Labels: priority: soon, effort: 1, type: refactor

#1219 fix: delete background image
  apps/journeys-admin/__generated__/CardBlockBackgroundImageUpdate.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
Labels: type: fix, priority: soon, effort: 1

#1224 feat: variant languages count
  apps/api-gateway/schema.graphql
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
Labels: effort: 2, priority: now, type: feat

#1211 fix: render videojs on play button click
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/index.ts
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoPlayer.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/index.ts
Labels: type: fix, effort: 3, priority: soon

#1218 feat: subtitle count field
  apps/api-gateway/schema.graphql
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/videoVariant/videoVariant.graphql
  apps/api-videos/src/app/modules/videoVariant/videoVariant.resolver.spec.ts
  apps/api-videos/src/app/modules/videoVariant/videoVariant.resolver.ts
Labels: priority: now, type: feat, effort: 1

#1220 fix: 500 server error on adding background image
  apps/api-journeys/src/app/modules/block/image/image.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/image/image.resolver.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#1213 fix: video card loading when changing languages
  apps/watch/src/components/VideosPage/VideosPage.tsx
Labels: type: fix, priority: soon, effort: 1

#1223 feat: add children count
  apps/api-gateway/schema.graphql
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
Labels: priority: now, type: feat, effort: 1

#1232 fix: refactor to use one apollo provider
  apps/watch/pages/_app.tsx
  apps/watch/pages/videos.tsx
Labels: priority: 2day, type: fix, effort: 1

#1231 feat: add datadog aws integration
  infrastructure/.terraform.lock.hcl
  infrastructure/main.tf
  infrastructure/modules/aws/datadog/data.tf
  infrastructure/modules/aws/datadog/datadog.tf
  infrastructure/modules/aws/datadog/main.tf
  infrastructure/modules/aws/ecs-task/main.tf
Labels: priority: now, type: feat, effort: 1

#1206 chore: bump nx
  .storybook/static/mockServiceWorker.js
  apps/api-gateway/project.json
  apps/api-journeys/project.json
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-languages/db/seed.ts
  apps/api-languages/project.json
  apps/api-languages/src/app/__generated__/graphql.ts
  apps/api-users/project.json
  apps/api-users/src/app/__generated__/graphql.ts
  apps/api-videos/project.json
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/utils/getSelected.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.tsx
  apps/journeys-admin/src/components/JourneyInvite/JourneyInvite.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/journeyListData.ts
  apps/journeys-admin/src/components/TemplateList/TemplateList.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyList/VisitorJourneyListItem/VisitorJourneyListItem.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.tsx
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.stories.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
  libs/apollo/logging/src/lib/apolloWinstonLoggingPlugin/apolloWinstonLoggingPlugin.ts
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/nest/database/src/lib/mock.ts
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.tsx
  libs/shared/ui/src/components/ThemeDecorator/ThemeDecorator.tsx
  libs/shared/ui/src/libs/createEmotionCache/createEmotionCache.ts
  package-lock.json
  package.json
  tsconfig.base.json
Labels: priority: soon, effort: 1, type: chore

#1235 feat: nofollow for social links
  apps/watch/src/components/Footer/FooterLink/FooterLink.tsx
  apps/watch/src/components/Footer/FooterSocials/FooterSocials.tsx
Labels: priority: soon, type: feat, effort: 1

#1233 refactor: get children for grid
  apps/watch/__generated__/GetVideoChildren.ts
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.spec.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.stories.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
Labels: effort: 2, priority: soon, type: refactor

#1212 feat: better ecs task restart
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-prod-worker.yml
  .github/workflows/api-gateway-stage-worker.yml
Labels: priority: soon, type: feat, effort: 1, on stage

#1208 feat: update home hero styling
  apps/watch/src/components/HomePage/HomeHero/HomeHero.tsx
Labels: priority: soon, type: feat, effort: 1

#1236 refactor: renamed allvideos title
  apps/watch/src/components/VideosPage/Hero/VideosHero.tsx
Labels: priority: soon, effort: 1, type: refactor

#1230 feat: video children count
  apps/watch/__generated__/GetHomeVideos.ts
  apps/watch/__generated__/GetVideoChildren.ts
  apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
  apps/watch/__generated__/GetVideoContent.ts
  apps/watch/__generated__/GetVideos.ts
  apps/watch/__generated__/VideoChildFields.ts
  apps/watch/__generated__/VideoContentFields.ts
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.tsx
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
  apps/watch/src/components/Videos/testData.ts
  apps/watch/src/libs/videoChildFields.ts
  apps/watch/src/libs/videoContentFields.ts
  apps/watch/src/libs/videoContext/VideoContext.spec.tsx
Labels: priority: 2day, effort: 3, type: feat, type: perf

#1239 feat: datadog logging for all subgraph apis
  .devcontainer/post-create-command.sh
  Procfile
  apps/api-gateway/project.json
  apps/api-journeys/project.json
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/generate-typings.ts
  apps/api-journeys/src/main.ts
  apps/api-languages/project.json
  apps/api-languages/src/app/app.module.ts
  apps/api-languages/src/generate-typings.ts
  apps/api-languages/src/main.ts
  apps/api-users/project.json
  apps/api-users/src/app/app.module.ts
  apps/api-users/src/generate-typings.ts
  apps/api-users/src/main.ts
  apps/api-videos/project.json
  apps/api-videos/src/app/app.module.ts
  apps/api-videos/src/generate-typings.ts
  apps/api-videos/src/main.ts
  apps/docs/docs/02-getting-started/04-running-projects.mdx
  apps/docs/docs/06-quick-links.md
  apps/journeys-admin/project.json
  apps/journeys/project.json
  apps/watch-admin/project.json
  apps/watch/next.config.js
  apps/watch/project.json
  libs/nest/common/.babelrc
  libs/nest/common/.eslintrc.json
  libs/nest/common/README.md
  libs/nest/common/jest.config.js
  libs/nest/common/project.json
  libs/nest/common/src/lib/tracer/index.ts
  libs/nest/common/src/lib/tracer/tracer.spec.ts
  libs/nest/common/src/lib/tracer/tracer.ts
  libs/nest/common/tsconfig.json
  libs/nest/common/tsconfig.lib.json
  libs/nest/common/tsconfig.spec.json
  package-lock.json
  package.json
  tsconfig.base.json
  workspace.json
Labels: priority: now, type: feat, effort: 1, on stage

#1243 fix: port assignment
  apps/api-journeys/src/main.ts
  apps/api-languages/src/main.ts
  apps/api-users/src/main.ts
  apps/api-videos/src/main.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1242 fix: typo in git deployment
  .github/workflows/api-deploy-worker.yml
Labels: type: fix, priority: now, effort: 1

#1246 feat: test data generator for watch
  apps/watch/__generated__/GetVideosForTestData.ts
  apps/watch/project.json
  apps/watch/src/components/AudioDialog/AudioLanguageDialog.spec.tsx
  apps/watch/src/components/AudioDialog/AudioLanguageDialog.stories.tsx
  apps/watch/src/components/DownloadDialog/DownloadDialog.spec.tsx
  apps/watch/src/components/DownloadDialog/DownloadDialog.stories.tsx
  apps/watch/src/components/HomePage/HomePage.stories.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.spec.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.stories.tsx
  apps/watch/src/components/VideoCard/VideoCard.spec.tsx
  apps/watch/src/components/VideoCard/VideoCard.stories.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.stories.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.stories.tsx
  apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContent/VideoContent.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContent/VideoContent.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.spec.tsx
  apps/watch/src/components/VideoGrid/VideoGrid.spec.tsx
  apps/watch/src/components/VideoGrid/VideoGrid.stories.tsx
  apps/watch/src/components/Videos/__generated__/testData.ts
  apps/watch/src/components/Videos/testData.generator.ts
  apps/watch/src/components/Videos/testData.ts
  apps/watch/src/components/VideosCarousel/VideosCarousel.spec.tsx
  apps/watch/src/components/VideosCarousel/VideosCarousel.stories.tsx
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.stories.tsx
  apps/watch/src/libs/apolloClient/apolloClient.ts
  apps/watch/src/libs/videoContext/VideoContext.spec.tsx
  package-lock.json
  package.json
Labels: priority: now, type: feat, effort: 1

#1241 refactor: remove subtitle from video children
  .prettierignore
  apps/watch/__generated__/GetHomeVideos.ts
  apps/watch/__generated__/GetVideoChildren.ts
  apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
  apps/watch/__generated__/GetVideoContent.ts
  apps/watch/__generated__/GetVideos.ts
  apps/watch/__generated__/GetVideosForTestData.ts
  apps/watch/__generated__/VideoChildFields.ts
  apps/watch/__generated__/VideoContentFields.ts
  apps/watch/src/components/AudioDialog/AudioLanguageDialog.spec.tsx
  apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.spec.tsx
  apps/watch/src/components/Videos/__generated__/testData.ts
  apps/watch/src/components/Videos/testData.generator.ts
  apps/watch/src/libs/videoChildFields.ts
Labels: priority: soon, effort: 1, type: refactor

#1225 fix: variant languages count front end
  apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
  apps/watch/__generated__/GetVideoContent.ts
  apps/watch/__generated__/GetVideosForTestData.ts
  apps/watch/__generated__/VideoContentFields.ts
  apps/watch/src/components/AudioDialog/AudioLanguageDialog.tsx
  apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
  apps/watch/src/components/Videos/__generated__/testData.ts
  apps/watch/src/libs/videoContentFields.ts
  apps/watch/src/libs/videoContext/VideoContext.spec.tsx
Labels: type: fix, priority: now, effort: 1

#1227 fix: remove variant languages slug
  apps/watch/__generated__/GetLanguagesSlug.ts
  apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
  apps/watch/__generated__/GetVideoContent.ts
  apps/watch/__generated__/GetVideosForTestData.ts
  apps/watch/__generated__/VideoContentFields.ts
  apps/watch/src/components/AudioDialog/AudioLanguageDialog.tsx
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.spec.tsx
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.stories.tsx
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.tsx
  apps/watch/src/components/AudioLanguageDialog/index.ts
  apps/watch/src/components/AudioLanguageDialog/testData.ts
  apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.spec.tsx
  apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.spec.tsx
  apps/watch/src/components/Videos/__generated__/testData.ts
  apps/watch/src/libs/apolloClient/apolloClient.ts
  apps/watch/src/libs/videoContentFields.ts
  apps/watch/src/libs/videoContext/VideoContext.spec.tsx
Labels: effort: 2, type: fix, priority: soon

#1228 feat: use subtitle count field on VideoControls
  apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
  apps/watch/__generated__/GetVideoContent.ts
  apps/watch/__generated__/GetVideosForTestData.ts
  apps/watch/__generated__/VideoContentFields.ts
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
  apps/watch/src/components/Videos/__generated__/testData.ts
  apps/watch/src/libs/videoContentFields.ts
  apps/watch/src/libs/videoContext/VideoContext.spec.tsx
Labels: effort: 2, priority: soon, type: feat

#1217 feat: managed federation
  .github/workflows/api-deploy-prod.yml
  .github/workflows/api-deploy-stage.yml
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-prod-worker.yml
  .github/workflows/api-gateway-stage-worker.yml
  apps/api-gateway/src/environments/environment.prod.ts
  apps/api-gateway/supergraph-main-ecs.yml
  apps/api-gateway/supergraph-main.yml
  apps/api-gateway/supergraph-stage-ecs.yml
  apps/api-gateway/supergraph-stage.yml
Labels: priority: 2day, effort: 5, type: feat, on stage

#1245 fix: remove subtitle from video content fields
  apps/watch/__generated__/GetSubtitles.ts
  apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
  apps/watch/__generated__/GetVideoContent.ts
  apps/watch/__generated__/GetVideosForTestData.ts
  apps/watch/__generated__/VideoContentFields.ts
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.spec.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.stories.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.tsx
  apps/watch/src/components/SubtitleDialog/testData.ts
  apps/watch/src/components/VideoContentPage/VideoContentPage.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
  apps/watch/src/components/Videos/__generated__/testData.ts
  apps/watch/src/libs/videoContentFields.ts
  apps/watch/src/libs/videoContext/VideoContext.spec.tsx
Labels: effort: 2, type: fix, priority: soon

#1249 fix: ecs restart typo
  .github/workflows/api-gateway-prod-worker.yml
Labels: type: fix, priority: now, effort: 1

#1255 feat: github deploy cleanup
  .github/workflows/api-deploy-prod.yml
  .github/workflows/api-deploy-stage.yml
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-prod-worker.yml
  .github/workflows/api-gateway-stage-worker.yml
Labels: effort: 2, priority: soon, type: feat, on stage

#1256 feat: remove kubernetes
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .gitignore
  .kube/config
  apps/arangodb-s3-backup/Dockerfile
  apps/arangodb-s3-backup/README.md
  apps/arangodb-s3-backup/backup.sh
  resources/kube/api/api-gateway-main-deployment.yaml
  resources/kube/api/api-gateway-main-service.yaml
  resources/kube/api/api-journeys-main-deployment.yaml
  resources/kube/api/api-journeys-main-service.yaml
  resources/kube/api/api-languages-main-deployment.yaml
  resources/kube/api/api-languages-main-service.yaml
  resources/kube/api/api-users-main-deployment.yaml
  resources/kube/api/api-users-main-service.yaml
  resources/kube/api/api-videos-main-deployment.yaml
  resources/kube/api/api-videos-main-service.yaml
  resources/kube/arangodb-bigquery-etl/arangodb-bigquery-etl-cron.yaml
  resources/kube/aws-auth-cm.yaml
  resources/kube/dashboard/admin-user.yaml
  resources/kube/dashboard/deploy.sh
  resources/kube/doppler-secret/doppler-secret.yaml
  resources/kube/ssl/alb-ingress-controller.yaml
  resources/kube/ssl/alb-rbac-role.yaml
  resources/kube/ssl/deploy.sh
  resources/kube/ssl/external-dns.yaml
  resources/kube/storage/storageclass.yaml
Labels: priority: soon, type: feat, effort: 1

#1247 feat: ecs arango bigquery etl
  .github/workflows/etl-deploy.yml
  apps/arangodb-bigquery-etl/Dockerfile
  apps/arangodb-bigquery-etl/bqexport.sh
  apps/arangodb-bigquery-etl/infrastructure/main.tf
  apps/arangodb-bigquery-etl/infrastructure/variables.tf
  infrastructure/environments/prod/data.tf
  infrastructure/environments/prod/main.tf
  infrastructure/modules/aws/ecs-scheduled-task/data.tf
  infrastructure/modules/aws/ecs-scheduled-task/main.tf
  infrastructure/modules/aws/ecs-scheduled-task/outputs.tf
  infrastructure/modules/aws/ecs-scheduled-task/terraform.tf
  infrastructure/modules/aws/ecs-scheduled-task/variables.tf
  infrastructure/modules/aws/ecs/outputs.tf
Labels: effort: 5, priority: soon, type: feat

#1258 feat: remove vpns
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/main.tf
  infrastructure/modules/aws/main.tf
  infrastructure/modules/aws/variables.tf
Labels: priority: soon, type: feat, effort: 1

#1264 fix: datadog
  apps/api-gateway/Dockerfile
  apps/api-journeys/Dockerfile
  apps/api-languages/Dockerfile
  apps/api-users/Dockerfile
  apps/api-videos/Dockerfile
Labels: type: fix, priority: now, effort: 1, on stage

#1266 revert: 1136 difficulties editing text
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
Labels: effort: 3, priority: now, type: revert, on stage

#1267 chore: mui bump 5.8.7
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLanguage/VideoLanguage.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/LanguageDialog/LanguageDialog.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.spec.tsx
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.spec.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.spec.tsx
  apps/watch/src/components/VideosPage/LanguagesFilter/LanguagesFilter.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.spec.tsx
  package-lock.json
  package.json
Labels: priority: 2day, effort: 2, type: chore, on stage

#1272 chore: change text in dialog to say manage access
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
Labels: priority: soon, effort: 1, type: chore

#1269 chore: remove x-data-grid
  package-lock.json
  package.json
Labels: priority: soon, effort: 1, type: chore, on stage

#1271 chore: remove winston
  apps/api-gateway/infrastructure/locals.tf
  apps/api-gateway/src/main.ts
  libs/apollo/logging/.babelrc
  libs/apollo/logging/.eslintrc.json
  libs/apollo/logging/README.md
  libs/apollo/logging/jest.config.js
  libs/apollo/logging/project.json
  libs/apollo/logging/src/lib/apolloWinstonLoggingPlugin/apolloWinstonLoggingPlugin.ts
  libs/apollo/logging/src/lib/apolloWinstonLoggingPlugin/index.ts
  libs/apollo/logging/tsconfig.json
  libs/apollo/logging/tsconfig.lib.json
  libs/apollo/logging/tsconfig.spec.json
  package-lock.json
  package.json
  tsconfig.base.json
  workspace.json
Labels: priority: 2day, effort: 1, type: chore, on stage

#1282 fix: graphql generation and cors vercel error with router
  apps/api-gateway/project.json
  apps/api-gateway/router.prod.yaml
Labels: type: fix, priority: now, effort: 1, on stage

#1278 feat: prod url redirects
  apps/journeys-admin/src/libs/firebaseClient/initAuth.ts
Labels: type: fix, priority: soon, effort: 1

#1283 chore: reduce number of prs being made automatically
  .github/dependabot.yml
  .github/workflows/crowdin.yml
Labels: priority: now, effort: 1, type: chore

#1284 chore: update graphql types
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-languages/src/app/__generated__/graphql.ts
  apps/api-users/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/__generated__/graphql.ts
Labels: priority: soon, effort: 1, type: chore

#1274 refactor: access dialog
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/ApproveUser/ApproveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/ApproveUser/ApproveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/ApproveUser/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/PromoteUser/PromoteUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/PromoteUser/PromoteUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/PromoteUser/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/RemoveUser/RemoveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/RemoveUser/RemoveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/RemoveUser/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/UserJourneyItem.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/UserJourneyItem.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyList.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyList.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/index.ts
Labels: effort: 3, priority: soon, type: refactor

#1288 feat: image library
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/index.ts
Labels: priority: soon, type: feat, effort: 1
