Repository JesusFilm/core, pull requests merged in 2023-07, with the labels that each got.

#1649 feat: host list tile component
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostListItem/HostListItem.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostListItem/HostListItem.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostListItem/HostListItem.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostListItem/index.ts
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.stories.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.tsx
Labels: effort: 5, priority: soon, type: feat

#1669 fix: api media deployment
  apps/api-media/Dockerfile
Labels: type: fix, priority: now, effort: 1, on stage

#1660 feat: create user team invite endpoints
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20230704223529_20230704223527/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/lib/casl/__generated__/prismaSubjects.ts
  apps/api-journeys/src/app/lib/casl/caslFactory.ts
  apps/api-journeys/src/app/modules/userTeam/userTeam.resolver.spec.ts
  apps/api-journeys/src/app/modules/userTeam/userTeam.resolver.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.graphql
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.module.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.resolver.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.spec.ts
Labels: effort: 13, priority: soon, type: feat

#1674 fix: global reports flag
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
Labels: type: fix, priority: now, effort: 1

#1680 fix: use static preview url on pull requests
  .github/workflows/app-deploy.yml
  apps/docs/project.json
  apps/journeys-admin/project.json
  apps/journeys/project.json
  apps/watch/project.json
  package-lock.json
  package.json
Labels: type: fix, priority: now, effort: 1

#1681 feat: add more analytics info
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
Labels: priority: soon, type: feat, effort: 1

#1685 feat: local dev device config
  .vscode/settings.json
Labels: priority: now, type: feat, effort: 1

#1690 docs: replace a non working link in docs with help text
  apps/docs/docs/05-team/04-where-we-work.md
Labels: priority: 2day, type: docs, effort: 1

#1696 feat: maintenance mode
  apps/journeys-admin/middleware.ts
  apps/journeys-admin/pages/maintenance.tsx
  libs/locales/en/apps-journeys-admin.json
  package-lock.json
  package.json
Labels: priority: now, type: feat, effort: 1

#1698 ci: add coverage reports to github actions
  .github/workflows/main.yml
  apps/api-journeys/jest.config.js
  apps/api-journeys/project.json
  apps/api-languages/jest.config.js
  apps/api-languages/project.json
  apps/api-media/jest.config.js
  apps/api-media/project.json
  apps/api-tags/jest.config.js
  apps/api-tags/project.json
  apps/api-users/jest.config.js
  apps/api-users/project.json
  apps/api-videos/jest.config.js
  apps/api-videos/project.json
  apps/journeys-admin/jest.config.js
  apps/journeys-admin/project.json
  apps/journeys/jest.config.js
  apps/journeys/project.json
  apps/watch-admin/jest.config.js
  apps/watch-admin/project.json
  apps/watch/jest.config.js
  apps/watch/project.json
  libs/journeys/ui/jest.config.js
  libs/journeys/ui/project.json
  libs/nest/common/jest.config.js
  libs/nest/common/project.json
  libs/nest/database/jest.config.js
  libs/nest/database/project.json
  libs/nest/decorators/jest.config.js
  libs/nest/decorators/project.json
  libs/nest/gqlAuthGuard/jest.config.js
  libs/nest/gqlAuthGuard/project.json
  libs/nest/powerBi/jest.config.js
  libs/nest/powerBi/project.json
  libs/shared/ui/jest.config.js
  libs/shared/ui/project.json
Labels: effort: 2, priority: now, type: feat, type: ci

#1702 feat: remove arango
  apps/api-journeys/db/Dockerfile
  apps/api-journeys/db/db.ts
  apps/api-journeys/db/seed.ts
  apps/api-journeys/db/seeds/psMigrate.ts
  apps/api-journeys/infrastructure/locals.tf
  apps/api-journeys/infrastructure/main.tf
  apps/api-media/db/Dockerfile
  apps/api-media/db/db.ts
  apps/api-media/db/seed.ts
  apps/api-media/db/seeds/psMigrate.ts
  apps/api-media/infrastructure/locals.tf
  apps/api-media/infrastructure/main.tf
  apps/api-media/project.json
  apps/api-tags/db/Dockerfile
  apps/api-users/db/Dockerfile
  apps/api-users/db/db.ts
  apps/api-users/db/seed.ts
  apps/api-users/infrastructure/locals.tf
  apps/api-users/infrastructure/main.tf
  apps/api-users/project.json
Labels: priority: 2day, effort: 2, type: feat, on stage

#1705 feat: tf update
  infrastructure/modules/aws/aurora/main.tf
  infrastructure/modules/aws/main.tf
Labels: priority: now, type: feat, effort: 1

#1706 fix: next block
  apps/api-journeys/db/migrations/20230718233012_20230718233010/migration.sql
  apps/api-journeys/db/schema.prisma
Labels: type: fix, priority: now, effort: 1, on stage

#1703 fix: journey duplicate next action
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: effort: 2, type: fix, priority: now, on stage

#1694 fix: add guest filter to userTeam resolver
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/userTeam/userTeam.graphql
  apps/api-journeys/src/app/modules/userTeam/userTeam.resolver.spec.ts
  apps/api-journeys/src/app/modules/userTeam/userTeam.resolver.ts
Labels: effort: 5, type: fix, priority: soon, on stage

#1707 fix: background video bug
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
Labels: effort: 2, type: fix, priority: soon

#1658 feat: custom video controls
  apps/docs/docs/06-product/01-next-steps/01-video-player.md
  apps/docs/docs/06-product/01-next-steps/custom-controls.png
  apps/docs/docs/06-product/01-next-steps/index.md
  apps/docs/docs/06-product/index.md
  apps/journeys/src/components/Conductor/Conductor.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.spec.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/Video/VideoControls/index.ts
  libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
  libs/journeys/ui/src/libs/block/block.ts
Labels: effort: 5, type: fix, priority: soon

#1695 fix: optimise admin ttfb
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/pages/publisher/[journeyId].tsx
  apps/journeys-admin/pages/publisher/[journeyId]/edit.tsx
  apps/journeys-admin/pages/publisher/index.tsx
  apps/journeys-admin/pages/reports/journeys.tsx
  apps/journeys-admin/pages/reports/visitors.tsx
  apps/journeys-admin/pages/reports/visitors/[visitorId].tsx
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/libs/initAndAuthApp/index.ts
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.spec.tsx
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.ts
Labels: type: fix, effort: 3, priority: soon

#1710 fix: video wrapper
  apps/journeys/src/components/EmbeddedPreview/VideoWrapper/VideoWrapper.spec.tsx
  apps/journeys/src/components/EmbeddedPreview/VideoWrapper/VideoWrapper.tsx
  apps/journeys/src/libs/testData/storyData.ts
Labels: type: fix, priority: soon, effort: 1

#1697 refactor: visitor list use auto refetch
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
Labels: priority: soon, effort: 1, type: refactor

#1714 fix: new nua video ids
  apps/api-journeys/db/seeds/nua1.ts
  apps/api-journeys/db/seeds/nua2.ts
  apps/api-journeys/db/seeds/nua8.ts
  apps/api-journeys/db/seeds/nua9.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#1683 fix: dynamically load blocks and videojs
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.spec.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
Labels: effort: 2, type: fix, priority: soon

#1663 feat: native share
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx
  apps/journeys/pages/_app.tsx
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.stories.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.tsx
  libs/journeys/ui/index.d.ts
  libs/journeys/ui/jest.config.js
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/FooterButtonList.spec.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/FooterButtonList.stories.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/FooterButtonList.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareButton.spec.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareButton.stories.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareButton.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareDialog/ShareDialog.spec.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareDialog/ShareDialog.stories.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareDialog/ShareDialog.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareDialog/index.ts
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/index.ts
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/StyledFooterButton/StyledFooterButton.spec.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/StyledFooterButton/StyledFooterButton.stories.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/StyledFooterButton/StyledFooterButton.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/StyledFooterButton/index.ts
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/index.ts
  libs/journeys/ui/src/components/StepFooter/StepFooter.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.stories.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
  libs/locales/en/libs-journeys-ui.json
  libs/shared/ui/src/components/icons/FacebookLogo.tsx
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/TwitterLogo.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: effort: 3, priority: soon, type: feat

#1678 feat: api languages postgres
  .vscode/settings.json
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-languages/.prisma-generate.env
  apps/api-languages/Dockerfile
  apps/api-languages/db/Dockerfile
  apps/api-languages/db/db.ts
  apps/api-languages/db/migrations/20230720001320_20230720001318/migration.sql
  apps/api-languages/db/migrations/migration_lock.toml
  apps/api-languages/db/schema.prisma
  apps/api-languages/db/seed.ts
  apps/api-languages/infrastructure/locals.tf
  apps/api-languages/infrastructure/main.tf
  apps/api-languages/infrastructure/variables.tf
  apps/api-languages/project.json
  apps/api-languages/schema.graphql
  apps/api-languages/src/app/__generated__/graphql.ts
  apps/api-languages/src/app/app.module.ts
  apps/api-languages/src/app/lib/prisma.service.ts
  apps/api-languages/src/app/modules/country/country.graphql
  apps/api-languages/src/app/modules/country/country.module.ts
  apps/api-languages/src/app/modules/country/country.resolver.spec.ts
  apps/api-languages/src/app/modules/country/country.resolver.ts
  apps/api-languages/src/app/modules/country/country.service.spec.ts
  apps/api-languages/src/app/modules/country/country.service.ts
  apps/api-languages/src/app/modules/language/language.module.ts
  apps/api-languages/src/app/modules/language/language.resolver.spec.ts
  apps/api-languages/src/app/modules/language/language.resolver.ts
  apps/api-languages/src/app/modules/language/language.service.spec.ts
  apps/api-languages/src/app/modules/language/language.service.ts
  apps/arangodb-bigquery-etl/bqexport.sh
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/main.tf
  package-lock.json
  package.json
Labels: priority: 2day, effort: 8, type: feat, on stage

#1712 fix: video language cache
  apps/journeys-admin/src/libs/apolloClient/cache.ts
  apps/journeys/src/libs/apolloClient/cache/cache.ts
Labels: type: fix, priority: soon, effort: 1

#1717 feat: discovery journeys seed data
  apps/api-journeys/db/seed.ts
  apps/api-journeys/db/seeds/feedback.ts
  apps/api-journeys/db/seeds/howTo.ts
  apps/api-journeys/db/seeds/vision.ts
Labels: priority: soon, type: feat, effort: 1

#1704 fix: embed video playback
  apps/docs/docs/06-product/01-next-steps/01-video-player.md
  apps/journeys/pages/embed/test/[journeySlug].tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
Labels: priority: 2day, effort: 2, type: fix

#1716 fix: access dialog to be useable outside of single journey page
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/AddUserSection.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/AddUserSection.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/AddUserSection.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserList.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserList.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/ApproveUser/ApproveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/ApproveUser/ApproveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/RemoveUser/RemoveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/RemoveUser/RemoveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/UserListItem.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/UserListItem.tsx
Labels: type: fix, effort: 3, priority: soon

#1721 fix: visitor endpoints to use acls
  apps/api-journeys/db/migrations/20230721193632_20230721193621/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/src/app/lib/casl/caslFactory/caslFactory.spec.ts
  apps/api-journeys/src/app/lib/casl/caslFactory/caslFactory.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.acl.spec.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.acl.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.module.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.resolver.spec.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.resolver.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.service.ts
  apps/api-journeys/src/app/modules/visitor/visitor.acl.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.acl.ts
  apps/api-journeys/src/app/modules/visitor/visitor.module.ts
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.ts
  apps/api-journeys/src/app/modules/visitor/visitor.service.ts
Labels: effort: 2, type: fix, priority: now, on stage

#1589 feat: reaction button
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/FooterButtonList.spec.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/FooterButtonList.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ReactionButton/ReactionButton.spec.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ReactionButton/ReactionButton.stories.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ReactionButton/ReactionButton.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ReactionButton/index.ts
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/StyledFooterButton/StyledFooterButton.tsx
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/ThumbsDown.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: effort: 2, priority: soon, type: feat

#1719 fix: share button
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/FooterButtonList.spec.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/FooterButtonList.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareButton.spec.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareDialog/ShareDialog.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/StyledFooterButton/StyledFooterButton.spec.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/shared/ui/src/components/Dialog/Dialog.tsx
Labels: type: fix, priority: soon, effort: 1

#1731 fix: journey nua order last as first
  apps/api-journeys/db/seed.ts
Labels: type: fix, priority: now, effort: 1

#1738 fix: request access screen
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/src/components/JourneyInvite/JourneyInvite.spec.tsx
  apps/journeys-admin/src/components/JourneyInvite/JourneyInvite.stories.tsx
  apps/journeys-admin/src/components/JourneyInvite/JourneyInvite.tsx
Labels: type: fix, priority: soon, effort: 1

#1739 fix: add loading to videoblockeditorposterlibrary
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.tsx
Labels: type: fix, priority: soon, effort: 1

#1740 fix: dynamic load language dialog
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/Language/Language.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/Language/Language.tsx
Labels: type: fix, priority: soon, effort: 1

#1743 fix: removed default opened at
  apps/api-journeys/db/migrations/20230728004724_20230728004722/migration.sql
  apps/api-journeys/db/schema.prisma
Labels: type: fix, priority: now, effort: 1, on stage

#1742 fix: add team prop to journey
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: type: fix, priority: soon, effort: 1

#1699 feat: going back through journey
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.spec.tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
  apps/journeys/src/components/Conductor/NavigationButton/index.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/RadioOption/RadioOption.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.spec.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.spec.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.spec.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.tsx
  libs/journeys/ui/src/libs/block/block.spec.ts
  libs/journeys/ui/src/libs/block/block.ts
  libs/journeys/ui/src/libs/block/index.ts
  libs/shared/ui/src/components/icons/ChevronLeft.tsx
  libs/shared/ui/src/components/icons/ChevronRight.tsx
Labels: effort: 3, priority: soon, type: feat

#1735 fix: journey ids call
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#1744 fix: get journey to be called in ssrprops
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
Labels: effort: 2, type: fix, priority: soon

#1746 refactor: add journey.teams to journeys, journeys-ui and journeys-admin
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/GetTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/src/components/Editor/ActionDetails/data.ts
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.stories.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/data.ts
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch/__generated__/JourneyFields.ts
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.spec.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.spec.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.stories.tsx
  libs/journeys/ui/src/components/StepFooter/HostTitleLocation/HostTitleLocation.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.stories.tsx
  libs/journeys/ui/src/libs/JourneyProvider/JourneyProvider.spec.tsx
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/journeyFields.tsx
  libs/journeys/ui/src/libs/rtl/rtl.spec.tsx
Labels: effort: 2, type: fix, priority: soon, type: refactor

#1748 revert: "fix: get journey to be called in ssrprops"
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
Labels: type: fix, priority: now, effort: 1

#1750 fix: vercel deploy
  apps/docs/project.json
  apps/journeys-admin/project.json
  apps/journeys/project.json
  apps/watch/project.json
Labels: type: fix, priority: now, effort: 1

#1736 fix: custom background video cant add blocks
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#1751 fix: locked step navigation no longer blocked
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/libs/block/block.spec.ts
  libs/journeys/ui/src/libs/block/block.ts
Labels: priority: 2day, effort: 2, type: fix

#1737 fix: reduce onboarding journey api calls
  apps/journeys-admin/__generated__/GetOnboardingJourneys.ts
  apps/journeys-admin/__generated__/GetOnboardingTemplate.ts
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/OnboardingPanelContent.spec.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/OnboardingPanelContent.stories.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/OnboardingPanelContent.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/data.ts
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.spec.tsx
Labels: type: fix, effort: 3, priority: soon

#1754 fix: navigation on last card if nextBlockId
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.spec.tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
Labels: effort: 2, type: fix, priority: now
