Repository JesusFilm/core, pull requests merged in 2023-12, with the labels that each got.

#2103 refactor: onboarding to dynamic
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/src/components/MediaListItem/MediaListItem.tsx
  apps/journeys-admin/src/components/OnboardingPanel/CreateJourneyButton/CreateJourneyButton.tsx
  apps/journeys-admin/src/components/OnboardingPanel/CreateJourneyButton/index.ts
  apps/journeys-admin/src/components/OnboardingPanel/OnboardingList/OnboardingList.tsx
  apps/journeys-admin/src/components/OnboardingPanel/OnboardingList/index.ts
  apps/journeys-admin/src/components/OnboardingPanel/OnboardingListLoading/OnboardingListLoading.tsx
  apps/journeys-admin/src/components/OnboardingPanel/OnboardingListLoading/index.ts
  apps/journeys-admin/src/components/OnboardingPanel/OnboardingPanel.spec.tsx
  apps/journeys-admin/src/components/OnboardingPanel/OnboardingPanel.stories.tsx
  apps/journeys-admin/src/components/OnboardingPanel/OnboardingPanel.tsx
  apps/journeys-admin/src/components/OnboardingPanel/data.ts
  apps/journeys-admin/src/components/OnboardingPanel/index.ts
  apps/journeys-admin/src/components/OnboardingPanelContent/OnboardingPanelContent.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/index.ts
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.spec.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, effort: 1, type: refactor

#2096 fix: focus state for accessibility in templates
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.tsx
  apps/journeys-admin/src/components/TemplateGallery/data.ts
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
Labels: type: fix, priority: soon, effort: 1

#2102 fix: audience autocomplete tags stay on one line
  apps/journeys-admin/src/components/TemplateGallery/TagsFilter/TagsFilter.tsx
Labels: type: fix, priority: soon, effort: 1

#2101 fix: template gallery default filter english
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
Labels: type: fix, priority: soon, effort: 1

#2107 fix: template carousel horizontal cls
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.spec.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
Labels: effort: 8, type: fix, priority: soon

#2114 refactor: navigation drawer
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.spec.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/index.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/ImpersonateDialog/ImpersonateDialog.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/ImpersonateDialog/ImpersonateDialog.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/ImpersonateDialog/ImpersonateDialog.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/ImpersonateDialog/index.ts
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/index.ts
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserNavigation.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserNavigation.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/index.ts
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/index.ts
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
  apps/journeys-admin/src/components/PageWrapper/utils/getJourneyTooltip/getJourneyTooltip.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/utils/getJourneyTooltip/getJourneyTooltip.ts
  apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
  apps/journeys-admin/src/libs/useUserRoleSuspenseQuery/index.ts
  apps/journeys-admin/src/libs/useUserRoleSuspenseQuery/useUserRoleSuspenseQuery.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, effort: 1, type: refactor

#2116 perf: add image sizes and fix loading state
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
Labels: effort: 8, priority: soon, type: perf

#2117 refactor: apollo cache queries during ssr and push to client
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/DiscoveryJourneys/DiscoveryJourneys.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/DiscoveryJourneys/DiscoveryJourneys.stories.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/DiscoveryJourneys/DiscoveryJourneys.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/DiscoveryJourneys/EmbedJourney/EmbedJourney.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/DiscoveryJourneys/EmbedJourney/EmbedJourney.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/DiscoveryJourneys/EmbedJourney/index.ts
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/DiscoveryJourneys/index.ts
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardText/JourneyCardText.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/LoadingJourneyList/LoadingJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.tsx
  apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.ts
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, effort: 1, type: refactor

#2012 chore: swiper bump
  .github/workflows/main.yml
  .storybook/preview.js
  apps/__mocks__/swiper/css.ts
  apps/__mocks__/swiper/modules.tsx
  apps/__mocks__/swiper/react.tsx
  apps/docs-e2e/src/e2e/docs.spec.ts-snapshots/home-page-chrome-desktop-linux.png
  apps/journeys-admin/jest.config.ts
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/public/swiper-pagination-override.css
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/SocialPreview/SocialPreview.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPreview.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TemplateTags.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  apps/journeys/jest.config.ts
  apps/journeys/pages/_app.tsx
  apps/journeys/pages/embed/[journeySlug].tsx
  apps/journeys/pages/index.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/watch-e2e/src/e2e/feature-film.spec.ts
  apps/watch-e2e/src/e2e/feature-film.spec.ts-snapshots/before-video-firefox-linux.png
  apps/watch-e2e/src/e2e/feature-film.spec.ts-snapshots/ff-landing-page-firefox-linux.png
  apps/watch-e2e/src/e2e/feature-film.spec.ts-snapshots/ff-navigated-page-firefox-linux.png
  apps/watch/jest.config.ts
  apps/watch/pages/_app.tsx
  apps/watch/src/components/VideoCarousel/VideoCarousel.tsx
  libs/journeys/ui/src/libs/blurImage/blurImage.spec.ts
  libs/shared/ui/src/components/ThemeDecorator/ThemeDecorator.tsx
  libs/shared/ui/src/libs/createEmotionCache/createEmotionCache.ts
  package-lock.json
  package.json
Labels: priority: 2day, effort: 2, type: chore

#2124 chore: changed drop down arrow to chevron
  apps/journeys-admin/src/components/TemplateGallery/TagsFilter/TagsFilter.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagsFilter/TagsFilter.tsx
Labels: priority: soon, effort: 1, type: style

#2105 feat: formblock api
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20231204000022_20231204000020/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/lib/json/json.graphql
  apps/api-journeys/src/app/modules/action/action.resolver.ts
  apps/api-journeys/src/app/modules/action/emailAction/emailAction.resolver.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToJourneyAction/navigateToJourneyAction.resolver.ts
  apps/api-journeys/src/app/modules/block/block.graphql
  apps/api-journeys/src/app/modules/block/block.module.ts
  apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.resolver.ts
  apps/api-journeys/src/app/modules/block/form/form.graphql
  apps/api-journeys/src/app/modules/block/form/form.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/form/form.resolver.ts
  apps/api-journeys/src/app/modules/block/form/validateFormCredentials/index.ts
  apps/api-journeys/src/app/modules/block/form/validateFormCredentials/validateFormCredentials.spec.ts
  apps/api-journeys/src/app/modules/block/form/validateFormCredentials/validateFormCredentials.ts
  apps/journeys-admin/__generated__/ActionDelete.ts
  apps/journeys-admin/__generated__/BlockDelete.ts
  apps/journeys-admin/__generated__/BlockDeleteForBackgroundImage.ts
  apps/journeys-admin/__generated__/BlockDeleteForBackgroundVideo.ts
  apps/journeys-admin/__generated__/BlockDeleteForCoverImage.ts
  apps/journeys-admin/__generated__/BlockDeleteForPosterImage.ts
  apps/journeys-admin/__generated__/BlockDuplicate.ts
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/BlockOrderUpdate.ts
  apps/journeys-admin/__generated__/DuplicatedBlock.ts
  apps/journeys-admin/__generated__/GetAdminJourney.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/JourneyImageBlockDelete.ts
  apps/journeys-admin/__generated__/NewBlock.ts
  apps/journeys-admin/__generated__/StepsOrderUpdate.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#2119 perf: run journeys query in ssr for templates
  apps/journeys-admin/pages/publisher/index.tsx
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/setupTests.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.spec.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateFooter/TemplateFooter.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateFooter/TemplateFooter.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPreview.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TemplateTags.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/SocialImage/SocialImage.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.tsx
  apps/journeys-admin/src/libs/apolloClient/cache.ts
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.ts
  apps/journeys-admin/src/libs/useTagsQuery/useTagsQuery.ts
Labels: effort: 5, priority: soon, type: perf

#2125 feat: form block
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/FormFields.ts
  apps/journeys-admin/__generated__/GetAdminJourney.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/src/libs/apolloClient/cache.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/FormFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/src/libs/apolloClient/cache/cache.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/FormFields.ts
  apps/watch/__generated__/JourneyFields.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Form/Form.spec.tsx
  libs/journeys/ui/src/components/Form/Form.tsx
  libs/journeys/ui/src/components/Form/__generated__/FormFields.ts
  libs/journeys/ui/src/components/Form/formFields.ts
  libs/journeys/ui/src/components/Form/index.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
  libs/journeys/ui/src/libs/block/blockFields.ts
  libs/locales/en/libs-journeys-ui.json
Labels: priority: soon, type: feat, effort: 1

#2098 feat: next ecs STAGE
  .github/workflows/app-deploy.yml
  .github/workflows/ecs-frontend-deploy-prod.yml
  .github/workflows/ecs-frontend-deploy-stage.yml
  .github/workflows/ecs-frontend-deploy-worker.yml
  apps/journeys-admin/Dockerfile
  apps/journeys-admin/infrastructure/locals.tf
  apps/journeys-admin/infrastructure/main.tf
  apps/journeys-admin/infrastructure/variables.tf
  apps/journeys-admin/next-i18next.config.js
  apps/journeys-admin/pages/api/health.tsx
  infrastructure/.terraform.lock.hcl
  infrastructure/environments/prod/data.tf
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/data.tf
  infrastructure/environments/stage/main.tf
  infrastructure/modules/aws/ec2-bastion/main.tf
  infrastructure/modules/aws/ecs-task/main.tf
  infrastructure/modules/aws/ecs-task/variables.tf
  package-lock.json
  package.json
Labels: effort: 8, priority: soon, type: feat, on stage

#2128 fix: github deploy
  .github/workflows/ecs-frontend-deploy-worker.yml
Labels: type: fix, priority: now, effort: 1, on stage

#2126 perf: dynamic side panels
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
Labels: effort: 5, priority: soon, type: perf

#2110 refactor: helpScout widget
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts-snapshots/home-page-chrome-desktop-linux.png
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
Labels: effort: 2, priority: soon, type: refactor

#2111 refactor: formium form
  apps/journeys-admin/src/components/OnboardingForm/OnboardingForm.spec.tsx
  apps/journeys-admin/src/components/OnboardingForm/OnboardingForm.tsx
  libs/shared/ui/src/components/FormiumForm/FormiumForm.spec.tsx
  libs/shared/ui/src/components/FormiumForm/FormiumForm.tsx
  libs/shared/ui/src/components/FormiumForm/FormiumProvider/FormiumProvider.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/Header/Header.spec.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/Header/Header.tsx
Labels: effort: 3, priority: soon, type: refactor

#2127 perf: add prefetch
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/src/components/AccessDenied/AccessDenied.tsx
  apps/journeys-admin/src/components/OnboardingPanel/OnboardingPanel.tsx
  apps/journeys-admin/src/components/PageWrapper/MainPanelHeader/MainPanelHeader.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserNavigation.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
Labels: priority: now, effort: 1, type: perf

#2129 perf: videos dialogs code split
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoListItem/VideoListItem.tsx
  apps/journeys-admin/src/components/StatusTabPanel/StatusTabPanel.tsx
  libs/shared/ui/src/components/TabPanel/TabPanel.tsx
Labels: effort: 3, priority: soon, type: perf

#2134 perf: dynamically load everything in editor except panels
  .vscode/settings.json
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageMenuItem.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/JourneyEdit/JourneyEdit.tsx
  apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  libs/locales/en/apps-journeys-admin.json
  package-lock.json
  package.json
Labels: priority: now, effort: 1, type: perf

#2138 fix: update tab panel unmount logic
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/StatusTabPanel/StatusTabPanel.tsx
  libs/shared/ui/src/components/TabPanel/TabPanel.tsx
Labels: type: fix, priority: now, effort: 1

#2139 feat: add launch darkly
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.spec.tsx
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.ts
  libs/shared/ui/src/components/FlagsProvider/FlagsProvider.spec.tsx
  libs/shared/ui/src/components/FlagsProvider/FlagsProvider.tsx
  libs/shared/ui/src/components/FlagsProvider/index.ts
  libs/shared/ui/src/libs/getLaunchDarklyClient/getLaunchDarklyClient.ts
  libs/shared/ui/src/libs/getLaunchDarklyClient/index.ts
  package-lock.json
  package.json
Labels: priority: soon, type: feat, effort: 1

#2135 perf: remove swiper from editor
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, effort: 1, type: perf

#2118 feat: help scout message via url
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageMenuItem.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageMenuItem.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/Properties/JourneyLink/JourneyLink.spec.tsx
  apps/journeys-admin/src/components/Editor/Properties/JourneyLink/JourneyLink.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.spec.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.spec.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.spec.tsx
  apps/journeys-admin/src/libs/setBeaconPageViewed/index.ts
  apps/journeys-admin/src/libs/setBeaconPageViewed/setBeaconPageViewed.ts
Labels: priority: soon, type: feat, effort: 1

#2131 feat: admin form block
  apps/journeys-admin/__generated__/FormBlockCreate.ts
  apps/journeys-admin/__generated__/FormBlockUpdateCredentials.ts
  apps/journeys-admin/__generated__/GetFormBlock.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/FormWrapper/FormWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/FormWrapper/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/ApiTokenTextField/ApiTokenTextField.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/ApiTokenTextField/ApiTokenTextField.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/ApiTokenTextField/ApiTokenTextField.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/ApiTokenTextField/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/Credentials.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/Credentials.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/Credentials.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/FormSlugSelect/FormSlug.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/FormSlugSelect/FormSlugSelect.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/FormSlugSelect/FormSlugSelect.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/FormSlugSelect/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/ProjectIdSelect/ProjectIdSelect.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/ProjectIdSelect/ProjectIdSelect.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/ProjectIdSelect/ProjectdSelect.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/ProjectIdSelect/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Form.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Form.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Form.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/BlocksTab.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/BlocksTab.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewFormButton/NewFormButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewFormButton/NewFormButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewFormButton/index.ts
  apps/journeys-admin/src/components/TextFieldForm/TextFieldForm.tsx
  libs/journeys/ui/src/components/Form/Form.spec.tsx
  libs/journeys/ui/src/components/Form/Form.stories.tsx
  libs/journeys/ui/src/components/Form/Form.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/FormiumForm/FormiumForm.tsx
Labels: effort: 3, priority: soon, type: feat

#2133 feat: prefill help scout search and user info
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.tsx
  apps/journeys-admin/src/components/Editor/ImageSource/ImageSource.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageSource/ImageSource.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
  apps/journeys-admin/src/libs/setBeaconPageViewed/setBeaconPageViewed.ts
Labels: effort: 2, priority: soon, type: feat

#2049 fix: add autoplay into embed iframe
  apps/journeys-admin/src/components/Editor/Properties/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.tsx
Labels: effort: 5, type: fix, priority: soon

#2144 fix: embed tests
  apps/journeys-admin/src/components/Editor/Properties/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.spec.tsx
Labels: type: fix, priority: soon, effort: 1

#2150 feat: formblock token backend check
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/form/form.graphql
  apps/api-journeys/src/app/modules/block/form/form.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/form/form.resolver.ts
Labels: priority: soon, type: feat, effort: 1, on stage

#2152 feat: add oembed
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/pages/api/oembed.ts
Labels: priority: now, type: feat, effort: 1, on stage

#2136 perf: images drawers code split
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostAvatarsButton/HostAvatarsButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Image.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Image.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/ImageEdit/ImageEdit.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx
  apps/journeys-admin/src/components/Editor/ImageSource/ImageSource.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.tsx
Labels: effort: 2, priority: soon, type: perf

#2154 refactor: api token exists not nullable
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/form/form.graphql
Labels: type: fix, priority: soon, effort: 1, on stage

#2143 feat: card preview to screenshot
  apps/journeys/pages/[journeySlug]/[stepId].tsx
  apps/journeys/src/components/VideoWrapperPaused/VideoWrapperPaused.spec.tsx
  apps/journeys/src/components/VideoWrapperPaused/VideoWrapperPaused.tsx
  apps/journeys/src/components/VideoWrapperPaused/index.ts
Labels: effort: 8, priority: soon, type: feat

#2155 fix: teams onboarding
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/UserTeamList/UserTeamList.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
Labels: priority: 2day, effort: 2, type: fix

#2151 fix: form block widths
  apps/journeys-admin/src/components/OnboardingForm/OnboardingForm.tsx
  libs/shared/ui/src/components/FormiumForm/wrappers/ElementsWrapper/ElementsWrapper.tsx
Labels: type: fix, priority: soon, effort: 1

#2160 refactor: formium components style
  apps/journeys-admin/src/components/Editor/Canvas/FormWrapper/FormWrapper.tsx
  apps/journeys-admin/src/components/OnboardingForm/OnboardingForm.tsx
  libs/journeys/ui/src/components/Form/Form.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/FormControl/FormControl.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/NextButton/NextButton.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/RadioGroup/RadioGroup.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/SubmitButton/SubmitButton.tsx
  libs/shared/ui/src/components/FormiumForm/wrappers/FooterWrapper/FooterWrapper.tsx
Labels: priority: soon, effort: 1, type: style

#2130 refactor: move helpscout button
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts-snapshots/home-page-chrome-desktop-linux.png
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
Labels: effort: 2, priority: now, type: refactor

#2146 feat: formblock api token field improvements
  apps/journeys-admin/__generated__/FormBlockUpdateCredentials.ts
  apps/journeys-admin/__generated__/GetFormBlock.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/ApiTokenTextField/ApiTokenTextField.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/ApiTokenTextField/ApiTokenTextField.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/ApiTokenTextField/ApiTokenTextField.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/Credentials.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/Credentials.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/FormSlugSelect/FormSlugSelect.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/ProjectIdSelect/ProjectIdSelect.spec.tsx
  apps/journeys-admin/src/components/TextFieldForm/TextFieldForm.tsx
Labels: effort: 3, priority: soon, type: feat

#2153 feat: analytics on toolbar
  apps/journeys-admin/src/components/Editor/EditToolbar/Analytics/Analytics.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Analytics/Analytics.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Analytics/index.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/DuplicateBlock/DuplicateBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DuplicateBlock/DuplicateBlock.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DuplicateBlock/index.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/ReportMenuItem/ReportMenuItem.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/ReportMenuItem/ReportMenuItem.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/ReportMenuItem/index.ts
Labels: priority: soon, type: feat, effort: 1

#2164 fix: missing secret
  .github/workflows/ecs-frontend-deploy-worker.yml
Labels: type: fix, priority: now, effort: 1

#2165 fix: dynamic tests
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostAvatarsButton/HostAvatarsButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageSource/ImageSource.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoList.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoListItem/VideoListItem.spec.tsx
Labels: priority: 2day, type: fix, effort: 1

#2166 feat: message queue architecture
  .devcontainer/docker-compose.yml
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/main.tf
  infrastructure/modules/aws/elasticache/main.tf
  infrastructure/modules/aws/elasticache/variables.tf
Labels: priority: soon, type: feat, effort: 1

#2158 feat: playwright user seed
  apps/api-journeys/db/seed.ts
  apps/api-journeys/db/seeds/playwrightUserAccess.ts
  apps/api-journeys/infrastructure/locals.tf
Labels: effort: 3, priority: soon, type: feat, on stage

#2161 fix: copy to team
  apps/journeys-admin/src/components/Team/CopyToTeamDialog/CopyToTeamDialog.spec.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamDialog/CopyToTeamDialog.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.spec.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.spec.tsx
Labels: effort: 2, type: fix, priority: soon

#2170 fix: redis devcontainer
  .devcontainer/docker-compose.yml
Labels: type: fix, priority: now, effort: 1
