Repository JesusFilm/core, pull requests merged in 2023-10, with the labels that each got.

#1929 fix: update api-tags seed
  apps/api-tags/db/seed.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#1934 fix: apollo video cache
  apps/journeys-admin/src/libs/apolloClient/cache.ts
  apps/journeys/src/libs/apolloClient/cache/cache.ts
Labels: type: fix, effort: 3, priority: now

#1923 feat: api-journeys index upgrade
  apps/api-journeys/db/migrations/20230927012734_20230927012733/migration.sql
  apps/api-journeys/db/schema.prisma
Labels: effort: 8, priority: soon, type: feat, on stage

#1932 fix: mobile mute icon correctly shows muted on first video
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
Labels: type: fix, priority: soon, effort: 1

#1908 fix: default editor card list theme
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
Labels: type: fix, priority: soon, effort: 1

#1935 feat: api video indexes
  apps/api-videos/db/migrations/20231003012617_20231003012616/migration.sql
  apps/api-videos/db/schema.prisma
Labels: effort: 2, priority: soon, type: feat, on stage

#1919 refactor: add onboarding page wrapper
  apps/journeys-admin/pages/teams/new.tsx
  apps/journeys-admin/pages/users/terms-and-conditions.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.stories.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/index.ts
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.spec.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: soon, type: refactor

#1916 feat: most relevant templates
  apps/journeys-admin/src/components/TemplateSections/MostRelevantTemplates/MostRelevantTemplates.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/MostRelevantTemplates/MostRelevantTemplates.tsx
  apps/journeys-admin/src/components/TemplateSections/MostRelevantTemplates/index.ts
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#1939 fix: duplicate invocation
  apps/api-journeys/src/app/lib/casl/caslGuard.ts
  apps/api-journeys/src/app/lib/prismaErrors.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/userRole/userRole.service.spec.ts
  apps/api-journeys/src/app/modules/userRole/userRole.service.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1938 feat: journey profile form filled at
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20231005014457_20231005014455/migration.sql
  apps/api-journeys/db/migrations/20231005015235_20231005015233/migration.sql
  apps/api-journeys/db/migrations/20231005031136_20231005031134/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.graphql
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.spec.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.ts
Labels: priority: now, type: feat, effort: 1, on stage

#1925 refactor: template settings dialog
  apps/journeys-admin/__generated__/JourneyFeature.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettings.spec.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettings.stories.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettings.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/FeaturedCheckbox/FeaturedCheckbox.spec.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/FeaturedCheckbox/FeaturedCheckbox.stories.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/FeaturedCheckbox/FeaturedCheckbox.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/FeaturedCheckbox/index.ts
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/TemplateSettingsDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/TemplateSettingsDialog.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/index.ts
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/index.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/FeaturedCheckbox/FeaturedCheckbox.spec.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/FeaturedCheckbox/FeaturedCheckbox.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/TitleDescription.spec.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/TitleDescriptionDialog/TitleDescriptionDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/TitleDescriptionDialog/TitleDescriptionDialog.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/TitleDescriptionDialog/index.ts
  apps/journeys-admin/src/components/JourneyView/TitleDescription/index.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 5, priority: soon, type: refactor

#1905 feat: strategy section
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
  apps/journeys-admin/src/components/TemplateView/StrategySection/StrategySection.spec.tsx
  apps/journeys-admin/src/components/TemplateView/StrategySection/StrategySection.stories.tsx
  apps/journeys-admin/src/components/TemplateView/StrategySection/StrategySection.tsx
  apps/journeys-admin/src/components/TemplateView/StrategySection/index.ts
  apps/journeys-admin/src/components/TemplateView/TempateView.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.spec.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#1930 test: add critical tests to watch-e2e
  .github/workflows/e2e-tests.yml
  apps/docs-e2e/src/e2e/docs.spec.ts-snapshots/home-page-chrome-desktop-linux.png
  apps/docs-e2e/src/e2e/docs.spec.ts-snapshots/home-page-chrome-mobile-linux.png
  apps/watch-e2e/playwright.config.ts
  apps/watch-e2e/src/e2e/chapter.spec.ts
  apps/watch-e2e/src/e2e/chapter.spec.ts-snapshots/after-video-firefox-linux.png
  apps/watch-e2e/src/e2e/chapter.spec.ts-snapshots/before-video-firefox-linux.png
  apps/watch-e2e/src/e2e/chapter.spec.ts-snapshots/home-page-firefox-linux.png
  apps/watch-e2e/src/e2e/feature-film.spec.ts
  apps/watch-e2e/src/e2e/feature-film.spec.ts-snapshots/after-video-firefox-linux.png
  apps/watch-e2e/src/e2e/feature-film.spec.ts-snapshots/before-video-firefox-linux.png
  apps/watch-e2e/src/e2e/feature-film.spec.ts-snapshots/ff-landing-page-firefox-linux.png
  apps/watch-e2e/src/e2e/feature-film.spec.ts-snapshots/ff-navigated-page-firefox-linux.png
  apps/watch-e2e/src/e2e/filters.spec.ts
  apps/watch-e2e/src/e2e/filters.spec.ts-snapshots/filters-list-firefox-linux.png
  apps/watch-e2e/src/e2e/filters.spec.ts-snapshots/see-all-landing-firefox-linux.png
  apps/watch-e2e/src/e2e/watch.spec.ts-snapshots/after-video-chrome-desktop-linux.png
  apps/watch-e2e/src/e2e/watch.spec.ts-snapshots/after-video-chrome-mobile-linux.png
  apps/watch-e2e/src/e2e/watch.spec.ts-snapshots/before-video-chrome-desktop-linux.png
  apps/watch-e2e/src/e2e/watch.spec.ts-snapshots/before-video-chrome-mobile-linux.png
  apps/watch-e2e/src/e2e/watch.spec.ts-snapshots/home-page-chrome-desktop-linux.png
  apps/watch-e2e/src/e2e/watch.spec.ts-snapshots/home-page-chrome-mobile-linux.png
Labels: type: test, priority: 2day, effort: 8

#1887 docs: add how to videos for playwright
  apps/docs/docs/03-basics/04-e2e-testing/01-core-concepts.md
  apps/docs/docs/03-basics/04-e2e-testing/02-write-tests.mdx
  apps/docs/docs/03-basics/04-e2e-testing/03-run-debug-tests.mdx
  apps/docs/docs/03-basics/04-e2e-testing/04-view-test-results.mdx
  apps/docs/docs/03-basics/04-e2e-testing/_category_.json
Labels: type: test, priority: 2day, effort: 3, type: docs

#1926 feat: category templates
  apps/journeys-admin/__generated__/GetTags.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/TemplateSections/CategoryTemplates/CategoryTemplates.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/CategoryTemplates/CategoryTemplates.tsx
  apps/journeys-admin/src/components/TemplateSections/CategoryTemplates/index.ts
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
  apps/journeys-admin/src/libs/useTagsQuery/index.ts
  apps/journeys-admin/src/libs/useTagsQuery/useTagsQuery.spec.tsx
  apps/journeys-admin/src/libs/useTagsQuery/useTagsQuery.ts
Labels: priority: soon, type: feat, effort: 1

#1924 feat: create journey from template button
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/users/terms-and-conditions.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamDialog/CopyToTeamDialog.spec.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamDialog/CopyToTeamDialog.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.spec.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.spec.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.spec.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.tsx
  apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.spec.tsx
  apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.ts
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.ts
Labels: priority: 2day, effort: 3, type: feat, on stage

#1941 fix: main body panel background color
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelBody/MainPanelBody.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelBody/MainPanelBody.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.tsx
Labels: effort: 2, type: fix, priority: now

#1933 feat: handle formium hidden fields
  libs/shared/ui/src/components/FormiumForm/FormiumForm.tsx
  libs/shared/ui/src/components/FormiumForm/Header/Header.tsx
Labels: priority: soon, type: feat, effort: 1

#1931 feat: style formium components
  libs/shared/ui/src/components/FormiumForm/Button/Button.tsx
  libs/shared/ui/src/components/FormiumForm/Button/index.ts
  libs/shared/ui/src/components/FormiumForm/Checkbox/Checkbox.tsx
  libs/shared/ui/src/components/FormiumForm/ElementsWrapper/ElementsWrapper.tsx
  libs/shared/ui/src/components/FormiumForm/FieldWrapper/FieldWrapper.tsx
  libs/shared/ui/src/components/FormiumForm/FieldWrapper/index.ts
  libs/shared/ui/src/components/FormiumForm/FooterWrapper/FooterWrapper.tsx
  libs/shared/ui/src/components/FormiumForm/FormControl/FormControl.tsx
  libs/shared/ui/src/components/FormiumForm/FormiumForm.stories.tsx
  libs/shared/ui/src/components/FormiumForm/FormiumForm.tsx
  libs/shared/ui/src/components/FormiumForm/Header/Header.tsx
  libs/shared/ui/src/components/FormiumForm/NextButton/NextButton.tsx
  libs/shared/ui/src/components/FormiumForm/NextButton/index.ts
  libs/shared/ui/src/components/FormiumForm/PageWrapper/PageWrapper.tsx
  libs/shared/ui/src/components/FormiumForm/PreviousButton/PreviousButton.tsx
  libs/shared/ui/src/components/FormiumForm/PreviousButton/index.ts
  libs/shared/ui/src/components/FormiumForm/RadioGroup/RadioGroup.tsx
  libs/shared/ui/src/components/FormiumForm/SubmitButton/SubmitButton.spec.tsx
  libs/shared/ui/src/components/FormiumForm/SubmitButton/SubmitButton.tsx
  libs/shared/ui/src/components/FormiumForm/SubmitButton/index.ts
  libs/shared/ui/src/components/FormiumForm/TextInput/TextInput.tsx
  libs/shared/ui/src/components/FormiumForm/Textarea/Textarea.tsx
Labels: effort: 3, priority: soon, type: feat

#1943 fix: show hosted by and chat widget on expanded embed
  apps/journeys-admin/src/libs/firebaseClient/initAuth.ts
  apps/journeys/pages/embed/test/[journeySlug].tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.stories.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
  libs/journeys/ui/src/libs/allowedHost/allowedHost.spec.ts
  libs/journeys/ui/src/libs/allowedHost/allowedHost.ts
  libs/journeys/ui/src/libs/allowedHost/index.ts
Labels: type: fix, priority: now, effort: 1

#1913 feat: strategy slug update form
  apps/journeys-admin/__generated__/JourneySettingsUpdate.ts
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/AboutTabPanel/AboutTabPanel.spec.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/AboutTabPanel/AboutTabPanel.stories.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/AboutTabPanel/AboutTabPanel.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/AboutTabPanel/index.ts
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/TemplateSettingsDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/TemplateSettingsDialog.tsx
  apps/journeys-admin/src/components/StrategySection/StrategySection.spec.tsx
  apps/journeys-admin/src/components/StrategySection/StrategySection.stories.tsx
  apps/journeys-admin/src/components/StrategySection/StrategySection.tsx
  apps/journeys-admin/src/components/StrategySection/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplateView.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  apps/journeys-admin/src/libs/useJourneyUpdateMutation/index.ts
  apps/journeys-admin/src/libs/useJourneyUpdateMutation/useJourneyUpdateMutation.spec.tsx
  apps/journeys-admin/src/libs/useJourneyUpdateMutation/useJourneyUpdateMutation.ts
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/Presentation1.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: effort: 5, priority: soon, type: feat

#1947 refactor: redirect params
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/pages/publisher/[journeyId].tsx
  apps/journeys-admin/pages/publisher/[journeyId]/edit.tsx
  apps/journeys-admin/pages/publisher/index.tsx
  apps/journeys-admin/pages/reports/journeys.tsx
  apps/journeys-admin/pages/reports/visitors.tsx
  apps/journeys-admin/pages/reports/visitors/[visitorId].tsx
  apps/journeys-admin/pages/teams/new.tsx
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/pages/users/terms-and-conditions.tsx
  apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.spec.tsx
  apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.ts
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.spec.tsx
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.ts
Labels: priority: now, effort: 1, type: refactor

#1892 feat: template gallery card
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.spec.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.stories.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/index.ts
  apps/journeys-admin/src/components/TemplateSections/CategoryTemplates/CategoryTemplates.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/FeaturedAndNewTemplates/FeaturedAndNewTemplates.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/MostRelevantTemplates/MostRelevantTemplates.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.stories.tsx
  apps/journeys-admin/src/components/ThemeProvider/admin/tokens/components.ts
  apps/journeys-admin/src/components/ThemeProvider/admin/tokens/typography.ts
  apps/journeys-admin/src/libs/abbreviateLanguageName/abbreviateLangaugeName.spec.tsx
  apps/journeys-admin/src/libs/abbreviateLanguageName/abbreviateLanguageName.ts
  apps/journeys-admin/src/libs/abbreviateLanguageName/index.ts
  apps/journeys-admin/src/libs/useJourneysQuery/useJourneysQuery.spec.tsx
  apps/journeys-admin/src/libs/useJourneysQuery/useJourneysQuery.ts
Labels: priority: soon, type: feat, effort: 1

#1875 fix: videojs resolution
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/CloudflareDetails/CloudflareDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/YouTubeDetails/YouTubeDetails.tsx
  apps/journeys/src/components/EmbeddedPreview/VideoWrapper/VideoWrapper.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoPlayer.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.spec.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.spec.tsx
  libs/shared/ui/src/libs/defaultVideoJsOptions/defaultVideoJsOptions.spec.ts
  libs/shared/ui/src/libs/defaultVideoJsOptions/defaultVideoJsOptions.ts
  libs/shared/ui/src/libs/defaultVideoJsOptions/index.ts
Labels: effort: 2, type: fix, priority: soon

#1888 feat: form page
  apps/journeys-admin/__generated__/GetJourneyProfileAndTeams.ts
  apps/journeys-admin/__generated__/JourneyProfileOnboardingFormComplete.ts
  apps/journeys-admin/pages/onboarding-form.tsx
  apps/journeys-admin/src/components/OnboardingForm/OnboardingForm.spec.tsx
  apps/journeys-admin/src/components/OnboardingForm/OnboardingForm.stories.tsx
  apps/journeys-admin/src/components/OnboardingForm/OnboardingForm.tsx
  apps/journeys-admin/src/components/OnboardingForm/index.ts
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.spec.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.tsx
  apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.spec.tsx
  apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.ts
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/.eslintrc.json
  libs/shared/ui/src/components/FormiumForm/FormiumForm.spec.tsx
  libs/shared/ui/src/components/FormiumForm/FormiumForm.stories.tsx
  libs/shared/ui/src/components/FormiumForm/FormiumForm.tsx
  libs/shared/ui/src/components/FormiumForm/FormiumProvider/FormiumProvider.tsx
  libs/shared/ui/src/components/FormiumForm/FormiumProvider/index.ts
  libs/shared/ui/src/components/FormiumForm/SubmitButton/SubmitButton.spec.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/Checkbox/Checkbox.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/Checkbox/index.ts
  libs/shared/ui/src/components/FormiumForm/formComponents/FormControl/FormControl.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/FormControl/index.ts
  libs/shared/ui/src/components/FormiumForm/formComponents/Header/Header.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/Header/index.ts
  libs/shared/ui/src/components/FormiumForm/formComponents/NextButton/NextButton.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/NextButton/index.ts
  libs/shared/ui/src/components/FormiumForm/formComponents/PreviousButton/PreviousButton.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/PreviousButton/index.ts
  libs/shared/ui/src/components/FormiumForm/formComponents/RadioGroup/RadioGroup.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/RadioGroup/index.ts
  libs/shared/ui/src/components/FormiumForm/formComponents/SubmitButton/SubmitButton.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/SubmitButton/index.ts
  libs/shared/ui/src/components/FormiumForm/formComponents/TextInput/TextInput.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/TextInput/index.ts
  libs/shared/ui/src/components/FormiumForm/formComponents/Textarea/Textarea.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/Textarea/index.ts
  libs/shared/ui/src/components/FormiumForm/wrappers/ElementsWrapper/ElementsWrapper.tsx
  libs/shared/ui/src/components/FormiumForm/wrappers/ElementsWrapper/index.ts
  libs/shared/ui/src/components/FormiumForm/wrappers/FieldWrapper/FieldWrapper.tsx
  libs/shared/ui/src/components/FormiumForm/wrappers/FieldWrapper/index.ts
  libs/shared/ui/src/components/FormiumForm/wrappers/FooterWrapper/FooterWrapper.tsx
  libs/shared/ui/src/components/FormiumForm/wrappers/FooterWrapper/index.ts
  libs/shared/ui/src/components/FormiumForm/wrappers/PageWrapper/PageWrapper.tsx
  libs/shared/ui/src/components/FormiumForm/wrappers/PageWrapper/index.ts
  libs/shared/ui/src/components/ThemeDecorator/ThemeDecorator.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
  libs/shared/ui/src/libs/themes/website/tokens/typography.stories.tsx
Labels: effort: 5, priority: soon, type: feat

#1918 fix: video mobile resolution
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.spec.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: type: fix, effort: 3, priority: now

#1950 feat: template sections
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
  apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.tsx
  apps/journeys-admin/src/components/TemplateSections/CategoryTemplates/CategoryTemplates.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/CategoryTemplates/CategoryTemplates.tsx
  apps/journeys-admin/src/components/TemplateSections/CategoryTemplates/index.ts
  apps/journeys-admin/src/components/TemplateSections/FeaturedAndNewTemplates/FeaturedAndNewTemplates.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/FeaturedAndNewTemplates/FeaturedAndNewTemplates.tsx
  apps/journeys-admin/src/components/TemplateSections/FeaturedAndNewTemplates/index.ts
  apps/journeys-admin/src/components/TemplateSections/MostRelevantTemplates/MostRelevantTemplates.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/MostRelevantTemplates/MostRelevantTemplates.tsx
  apps/journeys-admin/src/components/TemplateSections/MostRelevantTemplates/index.ts
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.stories.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
  apps/journeys-admin/src/libs/useJourneysQuery/useJourneysQuery.spec.tsx
  apps/journeys-admin/src/libs/useJourneysQuery/useJourneysQuery.ts
Labels: priority: now, type: feat, effort: 1

#1948 feat: template cards preview
  apps/journeys-admin/src/components/StrategySection/StrategySection.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/data.ts
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplateView.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 5, priority: soon, type: feat

#1949 feat: preview template button
  apps/journeys-admin/src/components/TemplateView/PreviewTemplateButton/PreviewTemplateButton.spec.tsx
  apps/journeys-admin/src/components/TemplateView/PreviewTemplateButton/PreviewTemplateButton.tsx
  apps/journeys-admin/src/components/TemplateView/PreviewTemplateButton/index.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: soon, type: feat

#1952 feat: template footer
  apps/journeys-admin/src/components/TemplateView/TemplateFooter/TemplateFooter.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateFooter/TemplateFooter.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateFooter/TemplateFooter.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateFooter/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#1946 feat: template carousel
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelBody/MainPanelBody.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelBody/MainPanelBody.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.stories.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/NavButton/NavButton.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/NavButton/index.ts
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.stories.tsx
Labels: effort: 3, priority: soon, type: feat

#1954 feat: template related templates
  apps/journeys-admin/__generated__/GetAdminJourney.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/src/components/Editor/ActionDetails/data.ts
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.stories.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/data.ts
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys-admin/src/libs/useJourneyQuery/useJourneyQuery.spec.tsx
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.stories.tsx
  apps/watch/__generated__/JourneyFields.ts
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.spec.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.spec.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.stories.tsx
  libs/journeys/ui/src/components/StepFooter/HostTitleLocation/HostTitleLocation.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.stories.tsx
  libs/journeys/ui/src/libs/JourneyProvider/JourneyProvider.spec.tsx
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/journeyFields.tsx
  libs/journeys/ui/src/libs/rtl/rtl.spec.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 5, priority: soon, type: feat

#1953 feat: template view header
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/src/components/JourneyView/SocialImage/SocialImage.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/PreviewTemplateButton/PreviewTemplateButton.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/PreviewTemplateButton/PreviewTemplateButton.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/PreviewTemplateButton/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateEditButton/TemplateEditButton.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateEditButton/TemplateEditButton.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateEditButton/TemplateEditButton.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateEditButton/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/index.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: soon, type: feat

#1951 fix: 100vh videos in ios
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: type: fix, priority: now, effort: 1

#1878 test: post slack notification if watch or journeys or journeys-admin goes down
  .github/workflows/journeys-admin-monitoring.yml
  .github/workflows/journeys-monitoring.yml
  .github/workflows/watch-monitoring.yml
  apps/journeys-admin-e2e/src/monitoring/monitor.spec.ts
  apps/journeys-e2e/src/monitoring/monitor.spec.ts
  apps/watch-e2e/src/monitoring/monitor.spec.ts
Labels: priority: 2day, effort: 5, type: ci

#1958 fix: template view layout
  apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
  apps/journeys-admin/src/components/JourneyView/SocialImage/SocialImage.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettings.spec.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettings.tsx
  apps/journeys-admin/src/components/StrategySection/StrategySection.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.tsx
Labels: effort: 5, type: fix, priority: soon

#1879 feat: team public team
  apps/journeys-admin/__generated__/GetAdminJourney.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetLastActiveTeamIdAndTeams.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/TeamCreate.ts
  apps/journeys-admin/__generated__/TeamUpdate.ts
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.spec.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamDialog/CopyToTeamDialog.stories.tsx
  apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.stories.tsx
  apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.tsx
  apps/journeys-admin/src/components/Team/TeamCreateForm/TeamCreateForm.spec.tsx
  apps/journeys-admin/src/components/Team/TeamCreateForm/TeamCreateForm.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageWrapper/TeamManageWrapper.spec.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.spec.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.stories.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.spec.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.stories.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
  apps/journeys-admin/src/components/Team/TeamProvider/TeamProvider.spec.tsx
  apps/journeys-admin/src/components/Team/TeamProvider/TeamProvider.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.spec.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.stories.tsx
  apps/journeys-admin/src/components/Team/TeamUpdateDialog/TeamUpdateDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamUpdateDialog/TeamUpdateDialog.stories.tsx
  apps/journeys-admin/src/components/Team/TeamUpdateDialog/TeamUpdateDialog.tsx
  apps/journeys-admin/src/components/Team/UserTeamInviteForm/UserTeamInviteForm.spec.tsx
  apps/journeys-admin/src/components/VisitorsList/VisitorList.spec.tsx
  apps/journeys-admin/src/libs/useTeamCreateMutation/useTeamCreateMutation.tsx
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/watch/__generated__/JourneyFields.ts
  libs/journeys/ui/src/components/StepFooter/StepFooter.stories.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.spec.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
  libs/journeys/ui/src/components/StepHeader/__generated__/GetJourneyTeam.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/journeyFields.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: effort: 5, priority: soon, type: feat

#1960 fix: display empty title on team creation
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
Labels: type: fix, priority: now, effort: 1

#1963 feat: remove navigate to journey action
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
Labels: effort: 2, priority: now, type: feat

#1964 feat: filter journeys via language ids
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: priority: now, type: feat, effort: 1

#1966 fix: add languageid to variant in get videos query
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/VideoFromLocal.tsx
Labels: effort: 5, type: fix, priority: now

#1967 fix: simplify swiper
  apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.tsx
Labels: priority: soon, type: feat, effort: 1

#1962 fix: template carousel
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/NavButton/NavButton.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
Labels: effort: 2, type: fix, priority: soon

#1968 feat: templates tag filtering
  apps/journeys-admin/src/components/TemplateGallery/TagsFilter/TagsFilter.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagsFilter/TagsFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagsFilter/index.ts
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
  apps/journeys-admin/src/components/TemplateGallery/data.ts
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/NavButton/NavButton.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.tsx
  apps/journeys-admin/src/libs/useTagsQuery/useTagsQuery.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: now, type: feat

#1969 fix: templates page logout
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/UserMenu/UserMenu.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/UserMenu/UserMenu.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, type: fix, priority: soon

#1965 feat: language filter
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.tsx
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/LanguageFilter.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/LanguageFilter.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/LanguageFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/LanguageFilterDialog/LanguageFilterDialog.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/LanguageFilterDialog/LanguageFilterDialog.tsx
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/LanguageFilterDialog/index.ts
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/index.ts
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
  apps/journeys-admin/src/components/TemplateGallery/data.ts
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.stories.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: now, type: feat, on stage

#1970 ci: add deploy status
  .github/workflows/app-deploy.yml
Labels: priority: now, effort: 1, type: ci

#1971 ci: run monitoring every 10 mins
  .github/workflows/journeys-admin-monitoring.yml
  .github/workflows/journeys-monitoring.yml
  .github/workflows/watch-monitoring.yml
Labels: priority: soon, effort: 1, type: ci

#1975 chore: add loading state to templates library
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/LanguageFilter.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/LanguageFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagsFilter/TagsFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/data.ts
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.stories.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
Labels: priority: now, effort: 1, type: chore

#1979 fix: remove mousewheel scroll
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.tsx
Labels: type: fix, priority: soon, effort: 1

#1893 feat: single tag group autocomplete component
  apps/journeys-admin/__generated__/JourneySettingsUpdate.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.stories.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/CategoriesTabPanel/CategoriesTabPanel.spec.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/CategoriesTabPanel/CategoriesTabPanel.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/CategoriesTabPanel/index.ts
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/FeaturedCheckbox/FeaturedCheckbox.spec.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/FeaturedCheckbox/FeaturedCheckbox.stories.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/FeaturedCheckbox/FeaturedCheckbox.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/TemplateSettingsDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/TemplateSettingsDialog.stories.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/TemplateSettingsDialog.tsx
  apps/journeys-admin/src/components/TagAutocomplete/TagAutocomplete.spec.tsx
  apps/journeys-admin/src/components/TagAutocomplete/TagAutocomplete.stories.tsx
  apps/journeys-admin/src/components/TagAutocomplete/TagAutocomplete.tsx
  apps/journeys-admin/src/components/TagAutocomplete/index.ts
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.tsx
  apps/journeys-admin/src/libs/useJourneyUpdateMutation/useJourneyUpdateMutation.spec.tsx
  apps/journeys-admin/src/libs/useJourneyUpdateMutation/useJourneyUpdateMutation.ts
  apps/watch/src/components/VideoContentPage/VideoHeading/VideoHeading.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 8, priority: soon, type: feat

#1980 fix: template view styling
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.tsx
Labels: type: fix, priority: soon, effort: 1

#1981 feat: add impersonation api
  apps/api-gateway/schema.graphql
  apps/api-users/db/migrations/20231023191936_20231023191932/migration.sql
  apps/api-users/db/migrations/20231023192029_20231023192028/migration.sql
  apps/api-users/db/schema.prisma
  apps/api-users/schema.graphql
  apps/api-users/src/app/__generated__/graphql.ts
  apps/api-users/src/app/modules/user/user.graphql
  apps/api-users/src/app/modules/user/user.resolver.spec.ts
  apps/api-users/src/app/modules/user/user.resolver.ts
  libs/nest/common/src/lib/firebaseClient/firebaseClient.ts
  libs/nest/common/src/lib/firebaseClient/index.ts
Labels: priority: now, type: feat, effort: 1, on stage

#1983 feat: add impersonation to journeys-admin
  apps/journeys-admin/__generated__/GetMe.ts
  apps/journeys-admin/__generated__/UserImpersonate.ts
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/ImpersonateDialog/ImpersonateDialog.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/ImpersonateDialog/ImpersonateDialog.stories.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/ImpersonateDialog/ImpersonateDialog.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/ImpersonateDialog/index.ts
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/UserMenu/UserMenu.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/UserMenu/UserMenu.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/UserMenu.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/UserMenu.stories.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, type: feat, effort: 1

#1977 fix: navigation button
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.tsx
Labels: type: fix, priority: now, effort: 1

#1984 fix: journey tag table
  apps/api-journeys/db/migrations/20230920224119_20230920224113/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/src/app/lib/casl/__generated__/prismaSubjects.ts
  apps/api-journeys/src/app/modules/host/host.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: priority: 2day, effort: 2, type: fix

#1956 feat: template view tags
  apps/journeys-admin/src/components/TemplateView/TemplateTags/ParentTagIcon/ParentTagIcon.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/ParentTagIcon/ParentTagIcon.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/ParentTagIcon/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TagItem/TagItem.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TagItem/TagItem.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TagItem/TagItem.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TagItem/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TemplateTags.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TemplateTags.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TemplateTags.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/data.ts
  apps/journeys-admin/src/components/TemplateView/TemplateTags/getSortedTags/getSortedTags.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/getSortedTags/getSortedTags.ts
  apps/journeys-admin/src/components/TemplateView/TemplateTags/getSortedTags/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplateTags/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplateView.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  libs/shared/ui/src/components/icons/Calendar4.tsx
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/SmileyNeutral.tsx
  libs/shared/ui/src/components/icons/Tag.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: effort: 3, priority: soon, type: feat

#1985 fix: journey preview disable logic
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.tsx
Labels: type: fix, priority: soon, effort: 1

#1974 refactor: api hook naming
  apps/journeys-admin/pages/teams/new.tsx
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostAvatarsButton/HostAvatarsButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostAvatarsButton/HostAvatarsButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostLocationFieldForm/HostLocationFieldForm.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostLocationFieldForm/HostLocationFieldForm.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostTitleFieldForm/HostTitleFieldForm.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostTitleFieldForm/HostTitleFieldForm.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostSidePanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostSidePanel.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostSidePanel.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/AddJourneyButton/AddJourneyButton.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/AddJourneyButton/AddJourneyButton.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/OnboardingPanelContent.spec.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/OnboardingPanelContent.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageDialog.stories.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageWrapper/TeamManageWrapper.spec.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageWrapper/TeamManageWrapper.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.spec.tsx
  apps/journeys-admin/src/components/Team/UserTeamInviteForm/UserTeamInviteForm.spec.tsx
  apps/journeys-admin/src/libs/useCurrentUser/index.ts
  apps/journeys-admin/src/libs/useCurrentUserLazyQuery/index.ts
  apps/journeys-admin/src/libs/useCurrentUserLazyQuery/useCurrentUser.spec.tsx
  apps/journeys-admin/src/libs/useCurrentUserLazyQuery/useCurrentUserLazyQuery.ts
  apps/journeys-admin/src/libs/useHostUpdate/index.ts
  apps/journeys-admin/src/libs/useHostUpdateMutation/index.ts
  apps/journeys-admin/src/libs/useHostUpdateMutation/useHostUpdateMutation.spec.tsx
  apps/journeys-admin/src/libs/useHostUpdateMutation/useHostUpdateMutation.ts
  apps/journeys-admin/src/libs/useJourneyCreate/index.ts
  apps/journeys-admin/src/libs/useJourneyCreateMutation/index.ts
  apps/journeys-admin/src/libs/useJourneyCreateMutation/useJourneyCreateMutation.spec.tsx
  apps/journeys-admin/src/libs/useJourneyCreateMutation/useJourneyCreateMutation.ts
Labels: priority: 2day, effort: 1, type: refactor

#1988 fix: journey tag update
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: priority: 2day, effort: 2, type: fix, on stage

#1973 refactor: update props interface naming
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.tsx
  apps/journeys-admin/src/components/DiscoveryJourneys/EmbedJourney/EmbedJourney.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/ChatOption.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Details/Details.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Summary/Summary.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/CopyMenuItem/CopyMenuItem.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageMenuItem.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/ReportMenuItem/ReportMenuItem.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActivePriorityList.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardInfo/JourneyCardInfo.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardText/JourneyCardText.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/JourneyVisitorsList.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardDetails/VisitorCardDetails.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardHeader/VisitorCardHeader.tsx
  apps/journeys-admin/src/components/ReportsNavigation/NavigationButton/NavigationButton.tsx
  apps/journeys-admin/src/components/ReportsNavigation/ReportsNavigation.tsx
  apps/journeys-admin/src/components/VisitorInfo/DetailsForm/ChatButton/ChatButton.tsx
  apps/journeys-admin/src/components/VisitorInfo/DetailsForm/DetailsForm.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetails/VisitorDetails.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorInfo.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/CompactEvent/CompactEvent.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/EventsCard.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/GenericEvent/GenericEvent.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/TimelineEvent/TimelineEvent.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/TimelineEvent/TimelineEvent.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/VisitorJourneysList.tsx
  apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.ts
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.ts
  apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareDialog/ShareDialog.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/StyledFooterButton/StyledFooterButton.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
  libs/shared/ui/src/components/icons/CenterCheck/CenterCheck.tsx
Labels: priority: 2day, effort: 1, type: refactor

#1986 feat: use languages query
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageDialog/LanguageDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageDialog/LanguageDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageDialog/LanguageDialog.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageDialog/index.ts
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/LanguageFilter.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/LanguageFilter.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/LanguageFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/data.ts
  apps/journeys-admin/src/libs/useLanguagesQuery/index.ts
  apps/journeys-admin/src/libs/useLanguagesQuery/useLanguagesQuery.spec.tsx
  apps/journeys-admin/src/libs/useLanguagesQuery/useLanguagesQuery.ts
Labels: priority: soon, type: feat, effort: 1

#1961 feat: loader skeletons
  apps/journeys-admin/src/components/JourneyView/SocialImage/SocialImage.spec.tsx
  apps/journeys-admin/src/components/JourneyView/SocialImage/SocialImage.stories.tsx
  apps/journeys-admin/src/components/JourneyView/SocialImage/SocialImage.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.spec.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateFooter/TemplateFooter.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateFooter/TemplateFooter.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.tsx
Labels: priority: soon, type: feat, effort: 1

#1976 fix: iphone viewport on rotation
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.tsx
  apps/journeys/pages/embed/test/[journeySlug].tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: effort: 2, type: fix, priority: soon

#1987 fix: update most relevant and tag section logic
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
Labels: priority: 2day, effort: 2, type: fix

#1994 fix: hide most relevant heading if no match
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
Labels: priority: 2day, type: fix, effort: 1

#1993 fix: enable free mode
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.tsx
Labels: type: fix, priority: soon, effort: 1

#1936 test: add data ids to journeys ui
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.stories.tsx
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.spec.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.spec.tsx
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.tsx
  libs/journeys/ui/src/components/Card/OverlayContent/OverlayContent.tsx
  libs/journeys/ui/src/components/Image/Image.tsx
  libs/journeys/ui/src/components/RadioOption/RadioOption.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/FooterButtonList.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ReactionButton/ReactionButton.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareButton.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareDialog/ShareDialog.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.spec.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.tsx
  libs/journeys/ui/src/components/StepFooter/HostTitleLocation/HostTitleLocation.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
  libs/journeys/ui/src/components/TextField/TextField.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
  libs/journeys/ui/src/components/Typography/Typography.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
Labels: type: test, effort: 2, priority: soon

#1996 fix: resolve reference to user from firebase
  apps/api-users/src/app/modules/user/user.resolver.spec.ts
  apps/api-users/src/app/modules/user/user.resolver.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1788 fix: video drawer spacing
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
Labels: type: fix, priority: soon, effort: 1

#1982 fix: template card cleanup
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.spec.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/NavButton/NavButton.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.tsx
  apps/journeys-admin/src/components/ThemeProvider/admin/tokens/typography.stories.tsx
  apps/journeys-admin/src/components/ThemeProvider/admin/tokens/typography.ts
Labels: type: fix, effort: 3, priority: soon

#2000 fix: journey duplicate journeys tags
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: type: fix, priority: now, effort: 1, on stage

#2001 chore: bump nx 17.2
  .eslintignore
  .gitignore
  .prettierignore
  apps/api-journeys/project.json
  apps/api-languages/project.json
  apps/api-media/project.json
  apps/api-tags/project.json
  apps/api-users/project.json
  apps/api-videos/project.json
  apps/docs/project.json
  apps/journeys-admin/project.json
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys/project.json
  apps/watch/project.json
  libs/journeys/ui/project.json
  libs/nest/common/project.json
  libs/nest/decorators/project.json
  libs/nest/gqlAuthGuard/project.json
  libs/nest/health/project.json
  libs/nest/powerBi/project.json
  libs/shared/ui/project.json
  nx.json
  package-lock.json
  package.json
Labels: priority: soon, effort: 1, type: chore

#1991 fix: filter by language text
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/LanguageFilter.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/LanguageFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1
