Repository JesusFilm/core, pull requests merged in 2023-04, with the labels that each got.

#1426 feat: template panel
  apps/journeys-admin/__generated__/CreateJourney.ts
  apps/journeys-admin/__generated__/GetOnboardingTemplate.ts
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.spec.tsx
  apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.spec.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.tsx
  apps/journeys-admin/src/components/MediaListItem/MediaListItem.spec.tsx
  apps/journeys-admin/src/components/MediaListItem/MediaListItem.tsx
  apps/journeys-admin/src/components/NewPageWrapper/SidePanel/SidePanel.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/OnboardingPanelContent.spec.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/OnboardingPanelContent.stories.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/OnboardingPanelContent.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/data.ts
  apps/journeys-admin/src/components/OnboardingPanelContent/index.ts
  apps/journeys-admin/src/libs/useJourneyCreate/index.ts
  apps/journeys-admin/src/libs/useJourneyCreate/useJourneyCreate.spec.tsx
  apps/journeys-admin/src/libs/useJourneyCreate/useJourneyCreate.ts
  libs/locales/en/apps-journeys-admin.json
Labels: priority: 2day, effort: 3, type: feat

#1458 fix: show selected typography variant when editing block
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Variant/Variant.tsx
Labels: type: fix, priority: soon, effort: 1

#1462 fix: remove text response block in factorfiction card 1
  apps/api-journeys/db/seed.ts
  apps/api-journeys/db/seeds/nua1.ts
Labels: type: fix, priority: now, effort: 1

#1465 chore: skip flakey test
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
Labels: type: fix, priority: now, effort: 1

#1467 feat: add apollo cache hints
  apps/api-gateway/schema.graphql
  apps/api-languages/schema.graphql
  apps/api-languages/src/app/__generated__/graphql.ts
  apps/api-languages/src/app/app.graphql
  apps/api-languages/src/app/app.module.ts
  apps/api-languages/src/app/modules/country/country.graphql
  apps/api-languages/src/app/modules/language/language.graphql
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/app.graphql
  apps/api-videos/src/app/app.module.ts
  apps/api-videos/src/app/modules/video/video.graphql
  package-lock.json
  package.json
Labels: effort: 3, priority: now, type: feat, on stage

#1469 fix: increase max sockets when connecting to arango
  libs/nest/database/src/lib/DatabaseModule.ts
Labels: type: fix, priority: now, effort: 1

#1470 feat: reduce max sockets
  libs/nest/database/src/lib/DatabaseModule.ts
Labels: priority: now, type: feat, effort: 1

#1471 chore: add datadog to router
  .devcontainer/post-create-command.sh
  apps/api-gateway/Dockerfile
  apps/api-gateway/router.prod.yaml
Labels: priority: now, effort: 1, type: chore

#1472 fix: hide children on video content
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
Labels: type: fix, priority: now, effort: 1

#1473 feat: video cache
  apps/api-videos/src/app/modules/video/video.module.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
  package-lock.json
  package.json
Labels: effort: 5, priority: now, type: feat, on stage

#1474 fix: show children on video content
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
Labels: priority: now, effort: 1, type: revert

#1464 fix: dependency cycle
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsList.tsx
Labels: effort: 2, type: fix, priority: soon

#1476 fix: subtitle timing out test
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
Labels: type: fix, priority: now, effort: 1

#1437 feat: extend visitor type
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/button/button.graphql
  apps/api-journeys/src/app/modules/event/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/button/button.resolver.ts
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.ts
  apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.ts
  apps/api-journeys/src/app/modules/event/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/step/step.resolver.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.ts
  apps/api-journeys/src/app/modules/event/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/video/video.resolver.ts
  apps/api-journeys/src/app/modules/visitor/visitor.graphql
  apps/api-journeys/src/app/modules/visitor/visitor.service.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#1478 fix: custom upload state
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomImage.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
Labels: type: fix, priority: soon, effort: 1

#1484 fix: no link action issue
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.tsx
Labels: type: fix, priority: now, effort: 1

#1453 feat: visitors list
  apps/journeys-admin/__generated__/GetVisitors.ts
  apps/journeys-admin/pages/reports/journeys.tsx
  apps/journeys-admin/pages/reports/visitors.tsx
  apps/journeys-admin/pages/reports/visitors/[visitorId].tsx
  apps/journeys-admin/src/components/ReportsNavigation/NavigationButton/NavigationButton.spec.tsx
  apps/journeys-admin/src/components/ReportsNavigation/NavigationButton/NavigationButton.stories.tsx
  apps/journeys-admin/src/components/ReportsNavigation/NavigationButton/NavigationButton.tsx
  apps/journeys-admin/src/components/ReportsNavigation/NavigationButton/index.ts
  apps/journeys-admin/src/components/ReportsNavigation/ReportsNavigation.spec.tsx
  apps/journeys-admin/src/components/ReportsNavigation/ReportsNavigation.stories.tsx
  apps/journeys-admin/src/components/ReportsNavigation/ReportsNavigation.tsx
  apps/journeys-admin/src/components/ReportsNavigation/index.ts
  apps/journeys-admin/src/components/VisitorsList/VisitorList.spec.tsx
  apps/journeys-admin/src/components/VisitorsList/VisitorsList.stories.tsx
  apps/journeys-admin/src/components/VisitorsList/VisitorsList.tsx
  apps/journeys-admin/src/components/VisitorsList/index.ts
  apps/journeys-admin/src/components/VisitorsList/utils/getColDefs/getColDefs.tsx
  apps/journeys-admin/src/components/VisitorsList/utils/getColDefs/index.ts
  apps/journeys-admin/src/components/VisitorsList/utils/getVisitorRows/getVisitorRows.spec.ts
  apps/journeys-admin/src/components/VisitorsList/utils/getVisitorRows/getVisitorRows.ts
  apps/journeys-admin/src/components/VisitorsList/utils/getVisitorRows/index.ts
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Button/utils/findChatPlatform/findChatPlatform.spec.ts
  libs/journeys/ui/src/components/Button/utils/findChatPlatform/findChatPlatform.ts
  libs/journeys/ui/src/components/Button/utils/findChatPlatform/index.ts
  libs/journeys/ui/src/components/Button/utils/getActionLabel/getActionLabel.spec.ts
  libs/journeys/ui/src/components/Button/utils/getActionLabel/getActionLabel.ts
  libs/journeys/ui/src/components/Button/utils/getActionLabel/index.ts
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/journeys-admin.json
Labels: effort: 5, priority: soon, type: feat

#1480 feat: use single query cache for many
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#1459 refactor: components to use journey create hook
  apps/journeys-admin/__generated__/JourneyCreate.ts
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/AddJourneyButton/AddJourneyButton.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/AddJourneyButton/AddJourneyButton.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/AddJourneyButton/index.ts
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.spec.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.stories.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyFab/AddJourneyFab.spec.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyFab/AddJourneyFab.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyFab/index.ts
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
Labels: effort: 2, priority: soon, type: refactor

#1432 feat: api tags
  .github/workflows/api-deploy-prod.yml
  .github/workflows/api-deploy-stage.yml
  .github/workflows/api-deploy-worker.yml
  .github/workflows/main.yml
  .vscode/settings.json
  Procfile
  apps/api-gateway/schema.graphql
  apps/api-gateway/supergraph.yml
  apps/api-tags/.eslintrc.json
  apps/api-tags/.prisma-generate.env
  apps/api-tags/Dockerfile
  apps/api-tags/db/Dockerfile
  apps/api-tags/db/migrations/20230323202415_/migration.sql
  apps/api-tags/db/migrations/migration_lock.toml
  apps/api-tags/db/schema.prisma
  apps/api-tags/db/seed.ts
  apps/api-tags/infrastructure/locals.tf
  apps/api-tags/infrastructure/main.tf
  apps/api-tags/infrastructure/variables.tf
  apps/api-tags/jest.config.js
  apps/api-tags/project.json
  apps/api-tags/schema.graphql
  apps/api-tags/src/app/__generated__/graphql.ts
  apps/api-tags/src/app/app.module.ts
  apps/api-tags/src/app/lib/prisma.service.ts
  apps/api-tags/src/app/modules/tag/tag.graphql
  apps/api-tags/src/app/modules/tag/tag.module.ts
  apps/api-tags/src/app/modules/tag/tag.resolver.spec.ts
  apps/api-tags/src/app/modules/tag/tag.resolver.ts
  apps/api-tags/src/assets/.gitkeep
  apps/api-tags/src/environments/environment.prod.ts
  apps/api-tags/src/environments/environment.ts
  apps/api-tags/src/main.ts
  apps/api-tags/tsconfig.app.json
  apps/api-tags/tsconfig.json
  apps/api-tags/tsconfig.spec.json
  infrastructure/.terraform.lock.hcl
  infrastructure/data.tf
  infrastructure/environments/prod/data.tf
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/data.tf
  infrastructure/environments/stage/main.tf
  infrastructure/modules/aws/aurora/data.tf
  infrastructure/modules/aws/aurora/main.tf
  infrastructure/modules/aws/aurora/terraform.tf
  infrastructure/modules/aws/aurora/variables.tf
  infrastructure/modules/aws/main.tf
  infrastructure/modules/aws/outputs.tf
  infrastructure/modules/aws/vpc/main.tf
  infrastructure/modules/aws/vpc/outputs.tf
  tools/scripts/generate-graphql.sh
  workspace.json
Labels: effort: 8, priority: now, type: feat, on stage

#1492 fix: image search keyword
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashCollections/UnsplashCollections.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashCollections/UnsplashCollections.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashGallery.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashGallery.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashSearch/UnsplashSearch.tsx
Labels: type: fix, effort: 3, priority: soon

#1481 ci: deploy vercel projects using github actions
  .github/deploy_preview_comment_template.md
  .github/workflows/main.yml
  .github/workflows/vercel-deploy.yml
  .gitignore
  apps/docs/.eslintrc.json
  apps/docs/project.json
  apps/docs/src/components/FeatureList/FeatureList.tsx
  apps/docs/src/pages/index.tsx
  apps/journeys-admin/next-i18next.config.js
  apps/journeys-admin/next.config.js
  apps/journeys-admin/project.json
  apps/journeys/next-i18next.config.js
  apps/journeys/next.config.js
  apps/journeys/project.json
  apps/watch/next.config.js
  apps/watch/project.json
  package-lock.json
  package.json
  tools/scripts/generate-deploy-preview-comment.sh
  vercel.json
Labels: priority: now, effort: 1, type: ci

#1494 fix: add vercel token to prod
  apps/docs/project.json
  apps/journeys-admin/project.json
  apps/journeys/project.json
  apps/watch/project.json
Labels: type: fix, priority: now, effort: 1

#1495 fix: add prod arg to vercel build
  apps/docs/project.json
  apps/journeys-admin/project.json
  apps/journeys/project.json
  apps/watch/project.json
Labels: type: fix, priority: now, effort: 1

#1497 fix: vercel builds for stage and feature branches
  .github/deployment_comment_template.md
  .github/workflows/app-deploy.yml
  .gitignore
  apps/journeys/pages/_app.tsx
  libs/locales/en/apps-journeys.json
  tools/scripts/generate-deployment-comment.sh
Labels: type: fix, priority: now, effort: 1, on stage

#1505 fix: sample rate reduction
  apps/journeys-admin/pages/_app.tsx
  apps/journeys/pages/_app.tsx
  apps/watch/pages/_app.tsx
Labels: type: fix, priority: now, effort: 1

#1506 fix: deploy comments when main or stage
  .github/workflows/app-deploy.yml
Labels: type: fix, priority: now, effort: 1, on stage

#1486 fix: journey duplicate primary image
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: type: fix, effort: 3, priority: soon, on stage

#1510 fix: watch serve to use underscore build
  apps/watch/project.json
Labels: type: fix, priority: now, effort: 1

#1507 fix: youtube recommended
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.handlers.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/YouTubeDetails/YouTubeDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoListItem/VideoListItem.tsx
Labels: type: fix, effort: 3, priority: soon

#1512 revert: fix youtube recommended
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.handlers.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/YouTubeDetails/YouTubeDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoListItem/VideoListItem.tsx
Labels: priority: now, effort: 1, type: revert

#1489 fix: journeys performance
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/GetTemplate.ts
  apps/journeys-admin/__generated__/GridContainerFields.ts
  apps/journeys-admin/__generated__/GridItemFields.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/GridContainerFields.ts
  apps/journeys/__generated__/GridItemFields.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/pages/_document.tsx
  apps/watch-admin/__generated__/BlockFields.ts
  apps/watch-admin/__generated__/GridContainerFields.ts
  apps/watch-admin/__generated__/GridItemFields.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/GridContainerFields.ts
  apps/watch/__generated__/GridItemFields.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
  libs/journeys/ui/src/components/GridContainer/GridContainer.spec.tsx
  libs/journeys/ui/src/components/GridContainer/GridContainer.stories.tsx
  libs/journeys/ui/src/components/GridContainer/GridContainer.tsx
  libs/journeys/ui/src/components/GridContainer/__generated__/GridContainerFields.ts
  libs/journeys/ui/src/components/GridContainer/gridContainerFields.ts
  libs/journeys/ui/src/components/GridContainer/index.ts
  libs/journeys/ui/src/components/GridItem/GridItem.spec.tsx
  libs/journeys/ui/src/components/GridItem/GridItem.stories.tsx
  libs/journeys/ui/src/components/GridItem/GridItem.tsx
  libs/journeys/ui/src/components/GridItem/__generated__/GridItemFields.ts
  libs/journeys/ui/src/components/GridItem/gridItemFields.ts
  libs/journeys/ui/src/components/GridItem/index.ts
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
  libs/journeys/ui/src/libs/block/blockFields.ts
Labels: effort: 2, type: fix, priority: soon

#1513 fix: embed journeys change shadow color
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
Labels: effort: 8, type: fix, priority: soon
