Repository JesusFilm/core, pull requests merged in 2023-03, with the labels that each got.

#1374 fix: arangodb etl
  apps/arangodb-bigquery-etl/Dockerfile
  apps/arangodb-bigquery-etl/bqexport.sh
  apps/arangodb-bigquery-etl/infrastructure/main.tf
  infrastructure/modules/aws/ecs-scheduled-task/main.tf
Labels: priority: 2day, type: fix, effort: 13

#1380 refactor: sort by popup in journeys admin
  apps/journeys-admin/src/components/JourneyList/JourneySort/JourneySort.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneySort/JourneySort.tsx
Labels: priority: soon, effort: 1, type: refactor

#1385 fix: redirect bin to api on watch
  apps/watch/next.config.js
  apps/watch/pages/api/jf/watch.html/[videoId]/[languageId].ts
Labels: effort: 2, type: fix, priority: now

#1373 feat: unsplash collection chips
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomImage.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashCollections/UnsplashCollections.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashCollections/UnsplashCollections.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashCollections/index.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashGallery.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashGallery.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashGallery.tsx
Labels: effort: 3, priority: soon, type: feat

#1353 fix: update admin typography tokens, typography variants use correct theme
  .storybook/preview-head.html
  apps/journeys-admin/pages/_document.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Variant/Variant.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Variant/Variant.tsx
  apps/journeys-admin/src/components/ThemeProvider/admin/tokens/typography.stories.tsx
  apps/journeys-admin/src/components/ThemeProvider/admin/tokens/typography.ts
Labels: priority: 2day, effort: 2, type: fix

#1362 refactor: update resolver to not throw error
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.ts
Labels: priority: soon, effort: 1, type: refactor, on stage

#1363 fix: new journey badge
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/src/libs/useUserJourneyOpen/index.ts
  apps/journeys-admin/src/libs/useUserJourneyOpen/useUserJourneyOpen.spec.tsx
  apps/journeys-admin/src/libs/useUserJourneyOpen/useUserJourneyOpen.ts
Labels: type: fix, priority: soon, effort: 1

#1384 feat: extend arangodb etl
  apps/arangodb-bigquery-etl/Dockerfile
  apps/arangodb-bigquery-etl/README.md
  apps/arangodb-bigquery-etl/blocks
  apps/arangodb-bigquery-etl/bqexport.sh
Labels: effort: 5, priority: soon, type: feat

#1390 fix: open user journey mutation
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1386 fix: image upload feedback
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashCollections/UnsplashCollections.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
Labels: effort: 2, type: fix, priority: soon

#1387 refactor: poll block
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewRadioQuestionButton/NewRadioQuestionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewRadioQuestionButton/NewRadioQuestionButton.tsx
Labels: effort: 2, priority: soon, type: refactor

#1356 fix: edit text and button block on create
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/useOnClickOutside/useOnClickOutside.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/useOnClickOutside/useOnClickOutside.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/MoveBlockButtons/MoveBlockButtons.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/ToggleButtonGroup/ToggleButtonGroup.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Variant/Variant.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewTypographyButton/NewTypographyButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewTypographyButton/NewTypographyButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Button/Button.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, type: fix, priority: soon

#1393 fix: keep consistent target for input
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
Labels: priority: 2day, type: fix, effort: 1

#1397 feat: journey editor content switcher
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Button/Button.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Image.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/RadioOption/RadioOption.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Video.spec.tsx
  apps/journeys-admin/src/components/Editor/JourneyEdit/JourneyEdit.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
  libs/journeys/ui/src/libs/EditorProvider/index.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#1399 fix: 500 from members index
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: effort: 2, type: fix, priority: soon, on stage

#1398 feat: create seed for onboarding journey
  apps/api-journeys/db/seed.ts
  apps/api-journeys/db/seeds/onboarding.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#1394 feat: helpScout Beacon
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/index.ts
Labels: effort: 2, priority: soon, type: feat

#1400 fix: title of journey from template
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: effort: 2, type: fix, priority: soon, on stage

#1402 fix: alb 502
  apps/api-journeys/src/main.ts
  apps/api-languages/src/main.ts
  apps/api-media/src/main.ts
  apps/api-users/src/main.ts
  apps/api-videos/src/main.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#1405 feat: add mui data grid
  package-lock.json
  package.json
Labels: priority: soon, type: feat, effort: 1

#1408 fix: tls timeout in ssr
  apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
  apps/journeys/src/libs/apolloClient/apolloClient.ts
  apps/watch-admin/src/libs/apolloClient/apolloClient.ts
  apps/watch/src/libs/apolloClient/apolloClient.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1407 feat: initial robots.txt
  apps/journeys-admin/public/robots.txt
  apps/journeys/public/robots.txt
  apps/watch-admin/public/robots.txt
  apps/watch/public/robots.txt
Labels: priority: now, type: feat, effort: 1, on stage

#1410 fix: badge disappears when visiting edit and report pages
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
Labels: priority: 2day, type: fix, effort: 1

#1411 fix: ecs alb 502
  apps/api-journeys/src/main.ts
  apps/api-languages/src/main.ts
  apps/api-media/src/main.ts
  apps/api-users/src/main.ts
  apps/api-videos/src/main.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1404 fix: let embed code work
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.tsx
Labels: effort: 2, type: fix, priority: soon

#1403 feat: create analytics events
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
Labels: effort: 2, priority: soon, type: feat

#1413 feat: watch robots disallow all
  apps/watch/public/robots.txt
Labels: priority: now, type: feat, effort: 1, on stage

#1416 feat: journey edit view update
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToBlockAction/NavigateToBlockAction.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Cards/Cards.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
  apps/journeys-admin/src/components/Editor/Editor.tsx
  apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.tsx
Labels: effort: 3, priority: soon, type: feat, on stage

#1417 feat: media list item
  apps/journeys-admin/src/components/MediaListItem/MediaListItem.spec.tsx
  apps/journeys-admin/src/components/MediaListItem/MediaListItem.stories.tsx
  apps/journeys-admin/src/components/MediaListItem/MediaListItem.tsx
  apps/journeys-admin/src/components/MediaListItem/index.ts
Labels: effort: 2, priority: soon, type: feat

#1424 feat: seed onboarding templates
  apps/api-journeys/db/seed.ts
  apps/api-journeys/db/seeds/onboardingTemplates.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#1420 fix: view update route
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.tsx
Labels: type: fix, priority: soon, effort: 1, on stage

#1412 refactor: page wrapper
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
  apps/journeys-admin/src/components/NewPageWrapper/AppHeader/AppHeader.tsx
  apps/journeys-admin/src/components/NewPageWrapper/AppHeader/index.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelBody/MainPanelBody.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelBody/MainPanelBody.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelBody/index.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelHeader/MainPanelHeader.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelHeader/MainPanelHeader.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelHeader/index.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.tsx
  apps/journeys-admin/src/components/NewPageWrapper/SidePanel/SidePanel.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/SidePanel/SidePanel.tsx
  apps/journeys-admin/src/components/NewPageWrapper/SidePanel/index.tsx
  apps/journeys-admin/src/components/NewPageWrapper/SidePanelContainer/SidePanelContainer.tsx
  apps/journeys-admin/src/components/NewPageWrapper/SidePanelContainer/index.tsx
  apps/journeys-admin/src/components/NewPageWrapper/index.tsx
  apps/journeys-admin/src/components/NewPageWrapper/utils/usePageWrapperStyles/index.ts
  apps/journeys-admin/src/components/NewPageWrapper/utils/usePageWrapperStyles/usePageWrapperStyles.ts
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
  apps/journeys-admin/src/components/StatusTabPanel/StatusTabPanel.tsx
  apps/journeys-admin/src/libs/PageWrapperProvider/PageWrapperProvider.spec.tsx
  apps/journeys-admin/src/libs/PageWrapperProvider/PageWrapperProvider.tsx
  apps/journeys-admin/src/libs/PageWrapperProvider/index.ts
Labels: effort: 5, type: fix, priority: soon, type: refactor

#1422 fix: debounce datalayer
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
Labels: type: fix, priority: soon, effort: 1

#1388 chore: update devcontainer feature syntax
  .devcontainer/devcontainer.json
Labels: effort: 2, priority: soon, type: chore

#1401 feat: onboarding journey creation
  apps/journeys-admin/src/components/JourneyView/Menu/CreateTemplateMenuItem/CreateTemplateMenuItem.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/CreateTemplateMenuItem/CreateTemplateMenuItem.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.spec.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.tsx
  apps/journeys-admin/src/libs/useJourneyDuplicate/index.ts
  apps/journeys-admin/src/libs/useJourneyDuplicate/useJourneyDuplicate.spec.tsx
  apps/journeys-admin/src/libs/useJourneyDuplicate/useJourneyDuplicate.ts
Labels: effort: 3, priority: soon, type: feat

#1429 fix: add flag provider to terms and condition story
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.stories.tsx
Labels: priority: 2day, type: fix, effort: 1

#1396 feat: embed discovery journeys
  apps/journeys-admin/src/components/DiscoveryJourneys/DiscoveryJourneys.spec.tsx
  apps/journeys-admin/src/components/DiscoveryJourneys/DiscoveryJourneys.stories.tsx
  apps/journeys-admin/src/components/DiscoveryJourneys/DiscoveryJourneys.tsx
  apps/journeys-admin/src/components/DiscoveryJourneys/EmbedJourney/EmbedJourney.tsx
  apps/journeys-admin/src/components/DiscoveryJourneys/EmbedJourney/index.ts
  apps/journeys-admin/src/components/DiscoveryJourneys/index.ts
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.tsx
Labels: effort: 2, priority: soon, type: feat

#1418 fix: visitor creation id
  apps/api-journeys/src/app/modules/visitor/visitor.service.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.service.ts
Labels: type: fix, effort: 3, priority: soon, on stage

#1431 fix: query visitor by key
  apps/api-journeys/src/app/modules/visitor/visitor.service.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.service.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#1391 feat: ecs seed jobs
  .github/workflows/api-deploy-prod.yml
  .github/workflows/api-deploy-stage.yml
  .github/workflows/api-deploy-worker.yml
  apps/api-journeys/db/Dockerfile
  apps/api-journeys/db/seed.ts
  apps/api-journeys/infrastructure/main.tf
  apps/api-languages/db/Dockerfile
  apps/api-languages/db/seed.ts
  apps/api-languages/infrastructure/main.tf
  apps/api-media/db/Dockerfile
  apps/api-media/db/seed.ts
  apps/api-media/infrastructure/main.tf
  apps/api-users/db/Dockerfile
  apps/api-users/db/seed.ts
  apps/api-users/infrastructure/main.tf
  apps/api-videos/db/Dockerfile
  apps/api-videos/db/seed.ts
  apps/api-videos/infrastructure/main.tf
  infrastructure/main.tf
  infrastructure/modules/aws/ecs-task-job/data.tf
  infrastructure/modules/aws/ecs-task-job/locals.tf
  infrastructure/modules/aws/ecs-task-job/main.tf
  infrastructure/modules/aws/ecs-task-job/terraform.tf
  infrastructure/modules/aws/ecs-task-job/variables.tf
Labels: priority: 2day, effort: 13, type: feat, on stage

#1434 fix: update gtm
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
Labels: type: fix, priority: soon, effort: 1

#1423 feat: action details
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionCards/ActionCards.spec.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionCards/ActionCards.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionDetails.stories.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionDetails.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/data.ts
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsList.spec.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsList.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Drawer.tsx
Labels: effort: 3, priority: soon, type: feat, on stage

#1439 fix: visitor pagination
  apps/api-journeys/src/app/modules/visitor/visitor.service.ts
Labels: type: fix, priority: soon, effort: 1

#1444 fix: handle variable variant language id
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
Labels: effort: 8, type: fix, priority: now, on stage

#1443 fix: embed code respects language
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.tsx
Labels: type: fix, priority: now, effort: 1

#1445 fix: set node env to production
  .github/workflows/api-deploy-worker.yml
  .github/workflows/codeql-analysis.yml
  apps/api-journeys/project.json
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/modules/event/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-languages/project.json
  apps/api-languages/src/app/app.module.ts
  apps/api-media/project.json
  apps/api-media/src/app/__generated__/graphql.ts
  apps/api-media/src/app/app.module.ts
  apps/api-users/project.json
  apps/api-users/src/app/__generated__/graphql.ts
  apps/api-users/src/app/app.module.ts
  apps/api-videos/project.json
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/app.module.ts
  apps/api-videos/src/app/modules/video/video.graphql
  infrastructure/modules/aws/ecs-scheduled-task/main.tf
  infrastructure/modules/aws/ecs-task-job/main.tf
  infrastructure/modules/aws/ecs-task/main.tf
  libs/nest/common/src/lib/TranslationModule/translation.graphql
  libs/nest/common/src/lib/TranslationModule/translation.module.ts
  tools/scripts/generate-graphql.sh
Labels: type: fix, priority: now, effort: 1, on stage

#1446 fix: ignore health check logs
  apps/api-journeys/src/app/app.module.ts
  apps/api-languages/src/app/app.module.ts
  apps/api-media/src/app/app.module.ts
  apps/api-users/src/app/app.module.ts
  apps/api-videos/src/app/app.module.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1447 fix: remove watch prefix
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
Labels: effort: 2, type: fix, priority: now

#1421 feat: common icon button
  apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.spec.tsx
  apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.stories.tsx
  apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
  apps/journeys-admin/src/components/ContainedIconButton/index.ts
Labels: effort: 3, priority: soon, type: feat

#1451 fix: journey list fixed width
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
Labels: type: fix, priority: now, effort: 1

#1452 fix: sidescroll
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
Labels: type: fix, priority: now, effort: 1

#1425 feat: actions table
  apps/journeys-admin/public/goal.svg
  apps/journeys-admin/src/components/DuplicateBlock/DuplicateBlock.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionDetails.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionInformation/ActionInformation.spec.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionInformation/ActionInformation.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionInformation/index.ts
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsBanner/ActionsBanner.spec.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsBanner/ActionsBanner.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsList.spec.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsList.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsListView/ActionsListView.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsListView/index.ts
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.spec.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.stories.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/JourneyEdit/JourneyEdit.tsx
  libs/journeys/ui/src/components/Button/findChatPlatform/findChatPlatform.spec.ts
  libs/journeys/ui/src/components/Button/findChatPlatform/findChatPlatform.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#1454 feat: update to es2020
  tsconfig.base.json
Labels: priority: soon, type: feat, effort: 1

#1449 fix: language filter refactor
  apps/watch/src/components/FilterContainer/FilterContainer.stories.tsx
  apps/watch/src/components/FilterContainer/FilterContainer.tsx
  apps/watch/src/components/VideosPage/CurrentFilters/CurrentFilters.spec.tsx
  apps/watch/src/components/VideosPage/CurrentFilters/CurrentFilters.stories.tsx
  apps/watch/src/components/VideosPage/CurrentFilters/CurrentFilters.tsx
  apps/watch/src/components/VideosPage/CurrentFilters/index.ts
  apps/watch/src/components/VideosPage/FilterList/FilterList.stories.tsx
  apps/watch/src/components/VideosPage/FilterList/FilterList.tsx
  apps/watch/src/components/VideosPage/FilterList/LanguagesFilter/LanguagesFilter.spec.tsx
  apps/watch/src/components/VideosPage/FilterList/LanguagesFilter/LanguagesFilter.stories.tsx
  apps/watch/src/components/VideosPage/FilterList/LanguagesFilter/LanguagesFilter.tsx
  apps/watch/src/components/VideosPage/FilterList/LanguagesFilter/index.ts
  apps/watch/src/components/VideosPage/FilterList/index.ts
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
  apps/watch/src/libs/videoChildFields.ts
Labels: priority: soon, effort: 1, type: chore

#1450 feat: add video start event remove init pause
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
Labels: priority: soon, type: feat, effort: 1
