Repository JesusFilm/core, pull requests merged in 2023-05, with the labels that each got.

#1515 test: disable video loop snapshot
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.stories.tsx
Labels: type: test, priority: now, effort: 1

#1516 fix: change bg color for single action
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.tsx
Labels: type: fix, effort: 3, priority: soon

#1521 feat: add github actions for feature branch
  .github/workflows/main.yml
Labels: priority: soon, type: feat, effort: 1

#1500 fix: publishers not being able to import
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
Labels: type: fix, priority: soon, effort: 1

#1522 fix: goals styling
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionCards/ActionCards.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionDetails.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionInformation/ActionInformation.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsBanner/ActionsBanner.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsList.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsListView/ActionsListView.tsx
  apps/journeys-admin/src/components/Editor/JourneyEdit/JourneyEdit.tsx
Labels: type: fix, priority: soon, effort: 1

#1496 feat: prisma update
  .gitattributes
  apps/api-tags/Dockerfile
  apps/api-tags/db/Dockerfile
  apps/api-tags/project.json
  package-lock.json
  package.json
Labels: priority: soon, type: feat, effort: 1, on stage

#1498 feat: add journey visitors page
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#1490 refactor: navigation drawer use router
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/publisher/[journeyId].tsx
  apps/journeys-admin/pages/publisher/[journeyId]/edit.tsx
  apps/journeys-admin/pages/publisher/index.tsx
  apps/journeys-admin/pages/reports/visitors/[visitorId].tsx
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
Labels: priority: soon, effort: 1, type: refactor

#1414 feat: social share
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/public/swiper-pagination-override.css
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
  apps/journeys-admin/src/components/CardPreview/NavigationCard/NavigationCard.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Drawer.stories.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/DescriptionEdit/DescriptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.stories.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/TitleEdit/TitleEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/TitleEdit/TitleEdit.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.tsx
  apps/journeys-admin/src/components/Editor/JourneyEdit/JourneyEdit.tsx
  apps/journeys-admin/src/components/Editor/SocialPreview/Message/SocialPreviewMessage.spec.tsx
  apps/journeys-admin/src/components/Editor/SocialPreview/Message/SocialPreviewMessage.tsx
  apps/journeys-admin/src/components/Editor/SocialPreview/Post/SocialPreviewPost.spec.tsx
  apps/journeys-admin/src/components/Editor/SocialPreview/Post/SocialPreviewPost.tsx
  apps/journeys-admin/src/components/Editor/SocialPreview/SocialPreview.spec.tsx
  apps/journeys-admin/src/components/Editor/SocialPreview/SocialPreview.tsx
  apps/journeys-admin/src/components/Editor/SocialPreview/index.ts
  apps/journeys-admin/src/components/Editor/SocialProvider.tsx
  apps/journeys-admin/src/components/JourneyView/CardView/CardView.spec.tsx
  apps/journeys-admin/tsconfig.json
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: priority: 2day, effort: 13, type: feat, on stage

#1525 fix: social preview margins
  apps/journeys-admin/src/components/Editor/JourneyEdit/JourneyEdit.tsx
Labels: type: fix, priority: now, effort: 1

#1526 refactor: remove redundant margin logic
  apps/journeys-admin/src/components/Editor/JourneyEdit/JourneyEdit.tsx
Labels: priority: now, effort: 1, type: refactor

#1517 fix: youtube featured videos
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.handlers.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/YouTubeDetails/YouTubeDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoListItem/VideoListItem.tsx
Labels: type: fix, priority: now, effort: 1

#1529 fix: change wording for email invite
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/AddUserSection.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: priority: 2day, good first issue, type: fix, effort: 1

#1531 fix: blurhash not updating
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
Labels: type: fix, priority: soon, effort: 1

#1536 feat: datastream whitelist
  infrastructure/modules/aws/locals.tf
  infrastructure/modules/aws/main.tf
Labels: priority: 2day, type: feat, effort: 1

#1532 feat: geolocation vercel
  apps/journeys/pages/api/geolocation.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#1534 fix: mobile goals detail
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsList.tsx
Labels: type: fix, priority: now, effort: 1

#1502 fix: better url recognition
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionDetails.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsList.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/LinkAction/LinkAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/LinkAction/LinkAction.tsx
Labels: effort: 5, type: fix, priority: soon

#1538 fix: remove navigation on template view
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
Labels: type: fix, priority: soon, effort: 1

#1520 fix: disable fab & blocks tab when video block selected
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
Labels: type: fix, effort: 13, priority: soon

#1524 fix: redirect user on invalid journey id
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/pages/publisher/[journeyId].tsx
  apps/journeys-admin/pages/publisher/[journeyId]/edit.tsx
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/src/libs/useInvalidJourneyRedirect/index.ts
  apps/journeys-admin/src/libs/useInvalidJourneyRedirect/useInvalidJourneyRedirect.spec.tsx
  apps/journeys-admin/src/libs/useInvalidJourneyRedirect/useInvalidJourneyRedirect.ts
Labels: type: fix, effort: 3, priority: soon

#1543 fix: mobile side panel
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Editor.tsx
Labels: type: fix, effort: 3, priority: soon

#1546 fix: shrink label journey link
  libs/shared/ui/src/components/CopyTextField/CopyTextField.tsx
Labels: type: fix, priority: soon, effort: 1

#1533 refactor: cloudflare upload key
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomUrl/CustomUrl.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomUrl/CustomUrl.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.tsx
  apps/journeys-admin/src/components/Editor/ImageSource/ImageSource.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
Labels: type: fix, priority: soon, effort: 1

#1544 fix: video drawer select button visibility
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDescription/VideoDescription.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDescription/VideoDescription.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDescription/index.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.handlers.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/YouTubeDetails/YouTubeDetails.tsx
Labels: effort: 8, type: fix, priority: soon

#1551 fix: color picker
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
Labels: type: fix, priority: soon, effort: 1

#1552 fix: control panel scroll
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
Labels: type: fix, effort: 3, priority: soon

#1549 fix: youtube video start frame
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: priority: 2day, effort: 2, type: fix

#1530 fix: delete youtube image
  apps/journeys-admin/__generated__/BlockDeleteForCoverImage.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoList.spec.tsx
Labels: effort: 5, type: fix, priority: now

#1557 feat: new cloudflare stream api
  apps/api-gateway/schema.graphql
  apps/api-journeys/infrastructure/locals.tf
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/video/video.graphql
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
  apps/api-media/db/seed.ts
  apps/api-media/infrastructure/locals.tf
  apps/api-media/schema.graphql
  apps/api-media/src/app/__generated__/graphql.ts
  apps/api-media/src/app/app.module.ts
  apps/api-media/src/app/modules/cloudflare/video/video.graphql
  apps/api-media/src/app/modules/cloudflare/video/video.module.ts
  apps/api-media/src/app/modules/cloudflare/video/video.resolver.spec.ts
  apps/api-media/src/app/modules/cloudflare/video/video.resolver.ts
  apps/api-media/src/app/modules/cloudflare/video/video.service.spec.ts
  apps/api-media/src/app/modules/cloudflare/video/video.service.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.tsx
  apps/journeys-admin/src/components/VisitorInfo/videoBlockSourceToLabel.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
Labels: priority: now, effort: 13, type: feat, on stage

#1545 feat: display owner first
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.spec.tsx
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.tsx
Labels: effort: 5, priority: soon, type: feat

#1559 fix: api gateway schema
  apps/api-gateway/schema.graphql
Labels: type: fix, priority: now, effort: 1

#1561 fix: fetch video id from input instead of block
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1562 fix: broken story
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.stories.tsx
Labels: type: fix, priority: now, effort: 1

#1491 refactor: visitor details layout
  apps/journeys-admin/pages/reports/visitors/[visitorId].tsx
  apps/journeys-admin/src/components/VisitorInfo/DetailsForm/ChatButton/ChatButton.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/DetailsForm/ChatButton/ChatButton.tsx
  apps/journeys-admin/src/components/VisitorInfo/DetailsForm/ChatButton/index.ts
  apps/journeys-admin/src/components/VisitorInfo/DetailsForm/DetailsForm.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/DetailsForm/DetailsForm.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/DetailsForm/DetailsForm.tsx
  apps/journeys-admin/src/components/VisitorInfo/DetailsForm/DetailsFormData.ts
  apps/journeys-admin/src/components/VisitorInfo/DetailsForm/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetail.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetail.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetailForm/VisitorDetailForm.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/VisitorDetailForm/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetail/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorInfo.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorInfo.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorInfo.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorInfoProvider/VisitorInfoProvider.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorInfoProvider/VisitorInfoProvider.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorInfoProvider/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyDrawer/VisitorJourneyDrawer.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyDrawer/VisitorJourneyDrawer.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyDrawer/VisitorJourneyDrawer.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyDrawer/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimeline.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimeline.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimeline.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimelineItem/GenericEvent/GenericEvent.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimelineItem/GenericEvent/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimelineItem/VisitorJourneyTimelineItem.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimelineItem/VisitorJourneyTimelineItem.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimelineItem/VisitorJourneyTimelineItem.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/VisitorJourneyTimelineItem/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneyTimeline/index.ts
  apps/journeys-admin/src/components/VisitorInfo/messagePlatformToLabel.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/messagePlatformToLabel.ts
  apps/journeys-admin/src/components/VisitorInfo/transformVisitorEvents.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/transformVisitorEvents.ts
  apps/journeys-admin/src/components/VisitorInfo/videoBlockSourceToLabel.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/videoBlockSourceToLabel.ts
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: effort: 5, priority: soon, type: refactor

#1564 feat: serverless v2
  infrastructure/modules/aws/aurora/main.tf
Labels: priority: now, type: feat, effort: 1

#1565 feat: cloudflare check ready to stream
  apps/api-gateway/schema.graphql
  apps/api-media/schema.graphql
  apps/api-media/src/app/__generated__/graphql.ts
  apps/api-media/src/app/modules/cloudflare/video/video.graphql
  apps/api-media/src/app/modules/cloudflare/video/video.resolver.spec.ts
  apps/api-media/src/app/modules/cloudflare/video/video.resolver.ts
  apps/api-media/src/app/modules/cloudflare/video/video.service.spec.ts
  apps/api-media/src/app/modules/cloudflare/video/video.service.ts
Labels: priority: now, type: feat, effort: 1

#1566 fix: change get cf video to query
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
  apps/api-media/schema.graphql
  apps/api-media/src/app/__generated__/graphql.ts
  apps/api-media/src/app/modules/cloudflare/video/video.graphql
  apps/api-media/src/app/modules/cloudflare/video/video.resolver.spec.ts
  apps/api-media/src/app/modules/cloudflare/video/video.resolver.ts
Labels: type: fix, priority: now, effort: 1

#1554 feat: journey report navigation
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/reports/journeys.tsx
  apps/journeys-admin/src/components/ReportsNavigation/ReportsNavigation.spec.tsx
  apps/journeys-admin/src/components/ReportsNavigation/ReportsNavigation.tsx
Labels: priority: soon, type: feat, effort: 1

#1567 fix: video start time validation
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.spec.tsx
Labels: effort: 2, type: fix, priority: soon

#1528 feat: user data
  apps/journeys-admin/__generated__/GetVisitorForDetails.ts
  apps/journeys-admin/__generated__/GetVisitorForForm.ts
  apps/journeys-admin/pages/reports/visitors/[visitorId].tsx
  apps/journeys-admin/src/components/VisitorInfo/DetailsForm/ChatButton/ChatButton.tsx
  apps/journeys-admin/src/components/VisitorInfo/DetailsForm/DetailsForm.tsx
  apps/journeys-admin/src/components/VisitorInfo/DetailsForm/DetailsFormData.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetails/VisitorDetails.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetails/VisitorDetails.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetails/VisitorDetails.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetails/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorInfo.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: effort: 2, priority: soon, type: feat

#1558 feat: video upload on journeys admin
  apps/journeys-admin/__generated__/CreateCloudflareVideoUploadByFileMutation.ts
  apps/journeys-admin/__generated__/CreateCloudflareVideoUploadByUrl.ts
  apps/journeys-admin/__generated__/GetMyCloudflareVideoQuery.ts
  apps/journeys-admin/next.config.js
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/SourceFromCloudflare/SourceFromCloudflare.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/SourceFromCloudflare/index.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByFile/TestHttpStack.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByFile/index.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByFile/testFile.mp4
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByUrl/AddByUrl.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByUrl/AddByUrl.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByUrl/index.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/CloudflareDetails/CloudflareDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/CloudflareDetails/CloudflareDetails.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/CloudflareDetails/CloudflareDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/CloudflareDetails/index.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/VideoFromCloudflare.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/VideoFromCloudflare.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/VideoFromCloudflare.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/index.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/VisitorInfo/videoBlockSourceToLabel.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/videoBlockSourceToLabel.ts
  apps/journeys/next.config.js
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/FlagsProvider/FlagsProvider.spec.tsx
  libs/shared/ui/src/components/FlagsProvider/FlagsProvider.tsx
  package-lock.json
  package.json
Labels: priority: now, effort: 13, type: feat

#1535 refactor: events style
  apps/journeys-admin/__generated__/GetVisitorEvents.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetails/VisitorDetails.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorDetails/VisitorDetails.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/CompactEvent/CompactEvent.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/EventsCard.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/EventsCard.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/EventsCard.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/GenericEvent/GenericEvent.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/GenericEvent/GenericEvent.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/GenericEvent/GenericEvent.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/TimelineEvent/TimelineEvent.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/TimelineEvent/TimelineEvent.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/TimelineEvent/TimelineEvent.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/VisitorJourneysList.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/data.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/getButtonLabel/getButtonLabel.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/getButtonLabel/getButtonLabel.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/getButtonLabel/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/getEventVariant/getEventVariant.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/getEventVariant/getEventVariant.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/getEventVariant/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/transformEvents/transformEvents.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/transformEvents/transformEvents.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/videoPositionToLabel/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/videoPositionToLabel/videoPositionToLabel.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/videoPositionToLabel/videoPositionToLabel.ts
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: effort: 3, priority: soon, type: refactor

#1570 feat: revert rds subnet vpn
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/data.tf
  infrastructure/environments/stage/main.tf
  infrastructure/modules/aws/aurora/main.tf
  infrastructure/modules/aws/ec2-bastion/data.tf
  infrastructure/modules/aws/ec2-bastion/main.tf
  infrastructure/modules/aws/ec2-bastion/variables.tf
  infrastructure/modules/aws/main.tf
  infrastructure/modules/aws/outputs.tf
  infrastructure/modules/aws/variables.tf
Labels: effort: 3, priority: now, type: feat

#1541 feat: visitor journey list
  apps/api-journeys/db/migrations/20230525000033_20230525000031/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.resolver.ts
  apps/api-journeys/src/app/modules/visitor/visitor.service.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.service.ts
  apps/api-tags/db/Dockerfile
  apps/api-tags/db/seed.ts
  apps/journeys-admin/__generated__/GetJourneyVisitors.ts
  apps/journeys-admin/__generated__/GetJourneyVisitorsCount.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/public/VisitorsPlaceholder.svg
  apps/journeys-admin/src/components/JourneyVisitorsList/JourneyVisitorsList.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/JourneyVisitorsList.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/JourneyVisitorsList.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardDetails/VisitorCardDetails.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardDetails/VisitorCardDetails.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardDetails/index.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardHeader/VisitorCardHeader.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardHeader/VisitorCardHeader.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardHeader/index.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/index.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/utils/getStatusIcon/getStatusIcon.spec.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/utils/getStatusIcon/getStatusIcon.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/utils/getStatusIcon/index.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/utils/index.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/utils/transformDuration/index.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/utils/transformDuration/transformDuration.spec.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/utils/transformDuration/transformDuration.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/index.ts
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelHeader/MainPanelHeader.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 8, priority: soon, type: feat

#1547 feat: visitor journey report drawer
  apps/journeys-admin/__generated__/GetJourneyVisitors.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/ClearAllButton/ClearAllButton.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/ClearAllButton/ClearAllButton.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/ClearAllButton/index.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/JourneyVisitorsList.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorToolbar/VisitorToolbar.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorToolbar/VisitorToolbar.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorToolbar/VisitorToolbar.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorToolbar/index.ts
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.tsx
  apps/journeys-admin/src/components/NewPageWrapper/SidePanel/SidePanel.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: soon, type: feat

#1555 fix: visitor report back navigation
  apps/journeys-admin/pages/reports/visitors/[visitorId].tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/JourneyVisitorsList.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelHeader/MainPanelHeader.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelHeader/MainPanelHeader.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.tsx
Labels: effort: 5, type: fix, priority: soon

#1563 feat: journey geolocation
  apps/journeys/__generated__/VisitorUpdateForCurrentUser.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/src/components/Conductor/Conductor.tsx
Labels: effort: 2, priority: soon, type: feat

#1574 fix: change submit button mobile
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashSearch/UnsplashSearch.tsx
Labels: type: fix, effort: 3, priority: soon

#1542 feat: visitor by journey endpoints
  .vscode/settings.json
  apps/api-gateway/schema.graphql
  apps/api-journeys/.prisma-generate.env
  apps/api-journeys/Dockerfile
  apps/api-journeys/db/Dockerfile
  apps/api-journeys/db/migrations/20230510235254_20230510235251/migration.sql
  apps/api-journeys/db/migrations/20230511022807_20230511022805/migration.sql
  apps/api-journeys/db/migrations/20230515212432_20230515212429/migration.sql
  apps/api-journeys/db/migrations/20230515212636_20230515212633/migration.sql
  apps/api-journeys/db/migrations/20230525000033_20230525000031/migration.sql
  apps/api-journeys/db/migrations/migration_lock.toml
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/db/seed.ts
  apps/api-journeys/db/seeds/psMigrate.ts
  apps/api-journeys/project.json
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/lib/prisma.service.ts
  apps/api-journeys/src/app/modules/event/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/button/button.resolver.ts
  apps/api-journeys/src/app/modules/event/event.module.ts
  apps/api-journeys/src/app/modules/event/event.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/event.resolver.ts
  apps/api-journeys/src/app/modules/event/event.service.spec.ts
  apps/api-journeys/src/app/modules/event/event.service.ts
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.ts
  apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.ts
  apps/api-journeys/src/app/modules/event/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/step/step.resolver.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.ts
  apps/api-journeys/src/app/modules/event/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/video/video.resolver.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.graphql
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.module.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.resolver.spec.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.resolver.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.service.spec.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.service.ts
  apps/api-journeys/src/app/modules/visitor/visitor.graphql
  apps/api-journeys/src/app/modules/visitor/visitor.module.ts
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.ts
  apps/api-journeys/src/app/modules/visitor/visitor.service.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.service.ts
  apps/api-tags/db/Dockerfile
  apps/api-tags/db/seed.ts
  apps/arangodb-bigquery-etl/bqexport.sh
  apps/journeys-admin/__generated__/globalTypes.ts
  libs/nest/decorators/src/lib/FromPostgresql/FromPostgresql.ts
  libs/nest/decorators/src/lib/FromPostgresql/index.ts
  libs/nest/decorators/src/lib/ToPostgresql/ToPostgresql.ts
  libs/nest/decorators/src/lib/ToPostgresql/index.ts
Labels: effort: 8, priority: soon, type: feat, on stage

#1583 feat: chatstarted activity
  .devcontainer/docker-compose.yml
  apps/api-journeys/db/seeds/psMigrate.ts
  apps/api-journeys/src/app/modules/event/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/button/button.resolver.ts
Labels: priority: now, type: feat, effort: 1, on stage

#1580 fix: visitor details back nav
  apps/journeys-admin/pages/reports/visitors/[visitorId].tsx
Labels: type: fix, priority: soon, effort: 1

#1587 fix: nua journey teamid
  apps/api-journeys/db/seed.ts
  apps/api-journeys/db/seeds/nua1.ts
  apps/api-journeys/db/seeds/nua2.ts
  apps/api-journeys/db/seeds/nua8.ts
  apps/api-journeys/db/seeds/nua9.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#1588 fix: ignore case sensitive emails
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.tsx
Labels: type: fix, effort: 3, priority: now

#1585 fix: journey visitor country code
  apps/journeys-admin/__generated__/GetJourneyVisitors.ts
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/JourneyVisitorsList.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/JourneyVisitorsList.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.tsx
Labels: type: fix, priority: soon, effort: 1

#1579 fix: visitor journey card style
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardDetails/VisitorCardDetails.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardDetails/VisitorCardDetails.tsx
Labels: type: fix, priority: soon, effort: 1

#1590 fix: member check and add
  apps/api-journeys/src/app/modules/userJourney/userJourney.service.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.service.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#1573 feat: journey visitors list
  apps/journeys-admin/__generated__/GetJourneyVisitors.ts
  apps/journeys-admin/__generated__/GetJourneyVisitorsCount.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/pages/reports/journeys.tsx
  apps/journeys-admin/public/VisitorsPlaceholder.svg
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/ClearAllButton/ClearAllButton.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/ClearAllButton/ClearAllButton.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/ClearAllButton/index.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/JourneyVisitorsList.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/JourneyVisitorsList.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/JourneyVisitorsList.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardDetails/VisitorCardDetails.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardDetails/VisitorCardDetails.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardDetails/index.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardHeader/VisitorCardHeader.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardHeader/VisitorCardHeader.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardHeader/index.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/index.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/utils/getStatusIcon/getStatusIcon.spec.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/utils/getStatusIcon/getStatusIcon.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/utils/getStatusIcon/index.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/utils/index.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/utils/transformDuration/index.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/utils/transformDuration/transformDuration.spec.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/utils/transformDuration/transformDuration.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorToolbar/VisitorToolbar.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorToolbar/VisitorToolbar.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorToolbar/VisitorToolbar.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorToolbar/index.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/index.ts
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelHeader/MainPanelHeader.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelHeader/MainPanelHeader.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.tsx
  apps/journeys-admin/src/components/NewPageWrapper/SidePanel/SidePanel.tsx
  apps/journeys-admin/src/components/ReportsNavigation/ReportsNavigation.spec.tsx
  apps/journeys-admin/src/components/ReportsNavigation/ReportsNavigation.tsx
  apps/journeys/__generated__/VisitorUpdateForCurrentUser.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  infrastructure/modules/aws/aurora/main.tf
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 13, priority: soon, type: feat

#1596 chore: remove redundant templates flag
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/TemplateList/TemplateList.stories.tsx
Labels: effort: 2, priority: soon, type: chore

#1577 fix: timeline styling
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/CompactEvent/CompactEvent.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/EventsCard.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/GenericEvent/GenericEvent.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/VisitorJourneysList.tsx
Labels: type: fix, priority: soon, effort: 1

#1591 feat: 20 min duration
  apps/api-journeys/db/seed.ts
  apps/api-journeys/db/seeds/psMigrate.ts
  apps/api-journeys/src/app/modules/event/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/step/step.resolver.ts
Labels: effort: 2, priority: soon, type: feat, on stage
