Repository JesusFilm/core, pull requests merged in 2023-09, with the labels that each got.

#1852 fix: update npm ver
  .devcontainer/Dockerfile
Labels: type: fix, priority: now, effort: 1

#1853 fix: trying to read id from null variant
  apps/api-journeys/db/seeds/onboardingTemplates.ts
  apps/journeys/src/libs/apolloClient/cache/cache.ts
Labels: type: fix, priority: now, effort: 1

#1854 fix: handle journey with no blocks
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
Labels: type: fix, priority: now, effort: 1

#1779 fix: time resets on language change
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
Labels: type: fix, priority: soon, effort: 1

#1857 fix: deploy backend using old affected command
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-prod-worker.yml
  .github/workflows/api-gateway-stage-worker.yml
  .github/workflows/app-deploy.yml
  tools/scripts/affected-apps.ts
  tools/scripts/ignore-vercel-build.sh
Labels: type: fix, priority: now, effort: 1, on stage

#1858 fix: when matrix arg is empty then do not run deploy
  .github/workflows/app-deploy.yml
Labels: type: fix, priority: now, effort: 1

#1859 fix: new page wrapper header children and main body padding
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelBody/MainPanelBody.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelHeader/MainPanelHeader.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelHeader/MainPanelHeader.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.tsx
Labels: effort: 2, type: fix, priority: soon

#1865 fix: upload video polling not calling on complete
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.tsx
Labels: type: fix, priority: now, effort: 1

#1860 fix: black loading squares for embedded videos
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
Labels: type: fix, effort: 3, priority: soon

#1841 fix: chromatic action affected
  .github/workflows/main.yml
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelBody/MainPanelBody.tsx
Labels: priority: 2day, effort: 2, type: fix

#1825 feat: remove arango resources
  infrastructure/resources/arangodb/.terraform.lock.hcl
  infrastructure/resources/arangodb/README.md
  infrastructure/resources/arangodb/data.tf
  infrastructure/resources/arangodb/main.tf
  infrastructure/resources/arangodb/terraform.tf
Labels: priority: 2day, type: feat, effort: 1

#1861 feat: ecs job seed refactor
  infrastructure/modules/aws/ecs-scheduled-task/locals.tf
  infrastructure/modules/aws/ecs-scheduled-task/main.tf
  infrastructure/modules/aws/ecs-task-job/outputs.tf
Labels: priority: 2day, type: feat, effort: 1

#1869 fix: get auth token from firebase
  apps/journeys-admin/src/libs/apolloClient/apolloClient.spec.ts
  apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
Labels: type: fix, priority: now, effort: 1

#1819 fix: journey menu toolbar
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/CopyMenuItem/CopyMenuItem.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/CopyMenuItem/CopyMenuItem.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/CopyMenuItem/index.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/CreateTemplateMenuItem/CreateTemplateMenuItem.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/CreateTemplateMenuItem/CreateTemplateMenuItem.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/CreateTemplateMenuItem/index.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/DescriptionDialog/DescriptionDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/DescriptionDialog/DescriptionDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/DescriptionDialog/DescriptionDialog.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/DescriptionDialog/index.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageDialog/LanguageDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageDialog/LanguageDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageDialog/LanguageDialog.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageDialog/index.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageMenuItem.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageMenuItem.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/index.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/ReportMenuItem/ReportMenuItem.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/ReportMenuItem/ReportMenuItem.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/ReportMenuItem/index.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TitleDialog/TitleDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TitleDialog/TitleDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TitleDialog/TitleDialog.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TitleDialog/index.ts
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/Language/Language.tsx
Labels: effort: 5, type: fix, priority: soon

#1851 feat: add segmind ai as image provider
  apps/api-gateway/schema.graphql
  apps/api-media/infrastructure/locals.tf
  apps/api-media/schema.graphql
  apps/api-media/src/app/__generated__/graphql.ts
  apps/api-media/src/app/app.module.ts
  apps/api-media/src/app/modules/cloudflare/image/image.service.ts
  apps/api-media/src/app/modules/segmind/segmind.graphql
  apps/api-media/src/app/modules/segmind/segmind.module.ts
  apps/api-media/src/app/modules/segmind/segmind.resolver.spec.ts
  apps/api-media/src/app/modules/segmind/segmind.resolver.ts
  apps/api-media/src/app/modules/segmind/segmind.service.spec.ts
  apps/api-media/src/app/modules/segmind/segmind.service.ts
  apps/journeys-admin/__generated__/CreateAiImage.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostAvatarsButton/HostAvatarsButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/AIGallery/AIGallery.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/AIGallery/AIGallery.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/AIGallery/AIGallery.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/AIGallery/AIPrompt/AIPrompt.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/AIGallery/AIPrompt/AIPrompt.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/AIGallery/AIPrompt/index.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/AIGallery/index.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 5, priority: soon, type: feat, on stage

#1864 chore: outdated dependencies simple
  .eslintignore
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-prod-worker.yml
  .github/workflows/api-gateway-stage-worker.yml
  .github/workflows/app-deploy.yml
  .storybook/static/mockServiceWorker.js
  apps/api-journeys/Dockerfile
  apps/api-journeys/db/Dockerfile
  apps/api-languages/Dockerfile
  apps/api-languages/db/Dockerfile
  apps/api-media/Dockerfile
  apps/api-tags/Dockerfile
  apps/api-tags/db/Dockerfile
  apps/api-users/Dockerfile
  apps/api-videos/Dockerfile
  apps/api-videos/db/Dockerfile
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/Label/Label.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageDialog/LanguageDialog.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyLink/SlugDialog/SlugDialog.tsx
  apps/journeys-admin/src/components/TextFieldForm/TextFieldForm.tsx
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.tsx
  apps/watch/src/components/DownloadDialog/DownloadDialog.tsx
  apps/watch/src/components/VideosPage/FilterList/FilterList.tsx
  libs/journeys/ui/src/libs/blurImage/blurImage.spec.ts
  package-lock.json
  package.json
  tools/scripts/affected-apps.ts
Labels: priority: 2day, effort: 3, type: chore, on stage

#1874 fix: geolocation
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
Labels: type: fix, priority: soon, effort: 1

#1876 feat: add public title to team
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20230914053518_20230914053516/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/team/team.graphql
  apps/api-journeys/src/app/modules/team/team.resolver.spec.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Team/TeamCreateForm/TeamCreateForm.tsx
Labels: priority: now, type: feat, effort: 1, on stage

#1855 test: add test ids to watch components
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.tsx
  apps/watch/src/components/DownloadDialog/DownloadDialog.tsx
  apps/watch/src/components/DownloadDialog/TermsOfUseDialog/TermsOfUseDialog.tsx
  apps/watch/src/components/Footer/Footer.tsx
  apps/watch/src/components/Footer/FooterLink/FooterLink.tsx
  apps/watch/src/components/Footer/FooterLinks/FooterLinks.tsx
  apps/watch/src/components/Footer/FooterLogos/FooterLogos.tsx
  apps/watch/src/components/Footer/FooterSocials/FooterSocials.tsx
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx
  apps/watch/src/components/HomePage/HomeHero/HomeHero.tsx
  apps/watch/src/components/HomePage/HomePage.tsx
  apps/watch/src/components/HomePage/SeeAllVideos/SeeAllVideos.spec.tsx
  apps/watch/src/components/HomePage/SeeAllVideos/SeeAllVideos.tsx
  apps/watch/src/components/PageWrapper/PageWrapper.tsx
  apps/watch/src/components/ShareButton/ShareButton.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.tsx
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideoCarousel/NavButton/NavButton.tsx
  apps/watch/src/components/VideoCarousel/VideoCarousel.tsx
  apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
  apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.tsx
  apps/watch/src/components/VideoContentPage/DownloadButton/DownloadButton.tsx
  apps/watch/src/components/VideoContentPage/VideoContent/VideoContent.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  apps/watch/src/components/VideoContentPage/VideoHeading/VideoHeading.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
  apps/watch/src/components/VideoGrid/VideoGrid.spec.tsx
  apps/watch/src/components/VideoGrid/VideoGrid.tsx
  apps/watch/src/components/VideosPage/FilterList/FilterList.tsx
  apps/watch/src/components/VideosPage/FilterList/LanguagesFilter/LanguagesFilter.tsx
  apps/watch/src/components/VideosPage/Hero/VideosHero.tsx
  apps/watch/src/components/VideosPage/SubHero/VideosSubHero.tsx
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
  libs/shared/ui/src/components/Dialog/Dialog.tsx
Labels: type: test, priority: 2day, effort: 2

#1882 fix: background media story
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
Labels: type: fix, priority: soon, effort: 1

#1881 feat: update featuredAt to wipe on duplicate
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#1803 fix: bg video no cover image
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.spec.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
Labels: type: fix, priority: soon, effort: 1

#1883 feat: add tag ids on journeys
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20230919003743_20230919003742/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/host/host.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: priority: 2day, effort: 3, type: feat, on stage

#1886 feat: tags codegen frontend
  apps/journeys-admin/__generated__/GetJourneys.ts
  apps/journeys-admin/src/libs/useJourneysQuery/useJourneysQuery.spec.tsx
  apps/journeys-admin/src/libs/useJourneysQuery/useJourneysQuery.ts
Labels: priority: 2day, effort: 2, type: feat

#1872 fix: remove journey details page
  apps/journeys-admin/next.config.js
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: effort: 2, type: fix, priority: soon

#1889 feat: template details page
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/src/components/TemplateView/TempateView.tsx
  apps/journeys-admin/src/components/TemplateView/index.ts
Labels: effort: 2, priority: soon, type: feat

#1885 feat: basic template gallery page
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
  apps/journeys-admin/src/components/TemplateGallery/index.ts
Labels: priority: soon, type: feat, effort: 1

#1890 fix: journey featured
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#1867 test: add visual regression tests
  .github/workflows/app-deploy.yml
  apps/docs-e2e/playwright.config.ts
  apps/docs-e2e/project.json
  apps/docs-e2e/src/e2e/docs.spec.ts
  apps/docs-e2e/src/e2e/docs.spec.ts-snapshots/home-page-chrome-desktop-linux.png
  apps/docs-e2e/src/e2e/docs.spec.ts-snapshots/home-page-chrome-mobile-linux.png
  apps/journeys-admin-e2e/playwright.config.ts
  apps/journeys-admin-e2e/project.json
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts-snapshots/home-page-chrome-desktop-linux.png
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts-snapshots/home-page-chrome-mobile-linux.png
  apps/journeys-e2e/playwright.config.ts
  apps/journeys-e2e/project.json
  apps/journeys-e2e/src/e2e/journeys.spec.ts
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/can-we-trust-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/can-we-trust-chrome-mobile-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/jesus-history-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/jesus-history-chrome-mobile-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/who-was-jesus-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/who-was-jesus-chrome-mobile-linux.png
  apps/watch-e2e/playwright.config.ts
  apps/watch-e2e/project.json
  apps/watch-e2e/src/e2e/watch.spec.ts
  apps/watch-e2e/src/e2e/watch.spec.ts-snapshots/after-video-chrome-desktop-linux.png
  apps/watch-e2e/src/e2e/watch.spec.ts-snapshots/after-video-chrome-mobile-linux.png
  apps/watch-e2e/src/e2e/watch.spec.ts-snapshots/before-video-chrome-desktop-linux.png
  apps/watch-e2e/src/e2e/watch.spec.ts-snapshots/before-video-chrome-mobile-linux.png
  apps/watch-e2e/src/e2e/watch.spec.ts-snapshots/home-page-chrome-desktop-linux.png
  apps/watch-e2e/src/e2e/watch.spec.ts-snapshots/home-page-chrome-mobile-linux.png
Labels: type: test, priority: 2day, effort: 8

#1894 fix: journeys call
  apps/journeys/pages/index.tsx
Labels: type: fix, priority: soon, effort: 1

#1880 feat: add strategy slug to journeys
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20230918221525_20230918221523/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/host/host.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: priority: soon, type: feat, effort: 1

#1884 fix: card preview matches theme
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
Labels: type: fix, priority: soon, effort: 1

#1898 fix: template gallery message
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
Labels: type: fix, priority: soon, effort: 1

#1895 feat: featured checkbox
  apps/journeys-admin/__generated__/GetJourneys.ts
  apps/journeys-admin/__generated__/JourneyFeature.ts
  apps/journeys-admin/src/components/TemplateView/FeaturedCheckbox/FeaturedCheckbox.spec.tsx
  apps/journeys-admin/src/components/TemplateView/FeaturedCheckbox/FeaturedCheckbox.stories.tsx
  apps/journeys-admin/src/components/TemplateView/FeaturedCheckbox/FeaturedCheckbox.tsx
  apps/journeys-admin/src/components/TemplateView/FeaturedCheckbox/index.ts
  apps/journeys-admin/src/libs/useJourneysQuery/useJourneysQuery.ts
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#1901 fix: unsplash flakey test
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashGallery.spec.tsx
Labels: type: fix, priority: soon, effort: 1

#1903 feat: add limit and order by recent in journeys
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: priority: now, type: feat, effort: 1

#1906 test: update journeys-e2e visual regression snapshots as per stage env
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/can-we-trust-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/can-we-trust-chrome-mobile-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/jesus-history-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/jesus-history-chrome-mobile-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/who-was-jesus-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/who-was-jesus-chrome-mobile-linux.png
Labels: type: test, effort: 2, priority: now

#1900 fix: signup editor select
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
Labels: effort: 2, type: fix, priority: now

#1902 fix: textresponse editor select
  libs/journeys/ui/src/components/TextResponse/TextResponse.spec.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
Labels: effort: 2, type: fix, priority: now

#1899 fix: generate types for strategySlug
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/GetTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/src/components/Editor/ActionDetails/data.ts
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.stories.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/data.ts
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/watch/__generated__/JourneyFields.ts
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.spec.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.spec.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.stories.tsx
  libs/journeys/ui/src/components/StepFooter/HostTitleLocation/HostTitleLocation.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.stories.tsx
  libs/journeys/ui/src/libs/JourneyProvider/JourneyProvider.spec.tsx
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/journeyFields.tsx
  libs/journeys/ui/src/libs/rtl/rtl.spec.tsx
Labels: type: fix, priority: soon, effort: 1

#1909 fix: featured filter false logic
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#1911 test: test ids for ns journeys components
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.spec.tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
  apps/journeys/src/components/EmbeddedPreview/ButtonWrapper/ButtonWrapper.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
  apps/journeys/src/components/EmbeddedPreview/RadioOptionWrapper/RadioOptionWrapper.tsx
  apps/journeys/src/components/EmbeddedPreview/VideoWrapper/VideoWrapper.spec.tsx
  apps/journeys/src/components/EmbeddedPreview/VideoWrapper/VideoWrapper.tsx
Labels: type: test, priority: soon, effort: 1

#1914 feat: make template pages public
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.spec.tsx
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.ts
Labels: effort: 3, priority: soon, type: feat

#1896 feat: featured and new section
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
  apps/journeys-admin/src/components/TemplateSections/FeaturedAndNewTemplates/FeaturedAndNewTemplates.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/FeaturedAndNewTemplates/FeaturedAndNewTemplates.tsx
  apps/journeys-admin/src/components/TemplateSections/FeaturedAndNewTemplates/index.ts
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/index.ts
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.stories.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
  apps/journeys-admin/src/components/TemplateSections/index.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: soon, type: feat, on stage

#1915 fix: truncate and normalize email invite string
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.tsx
  apps/journeys-admin/src/components/Team/UserTeamInviteForm/UserTeamInviteForm.tsx
Labels: type: fix, priority: soon, effort: 1

#1917 feat: add formiumform
  libs/shared/ui/src/components/FormiumForm/Button/Button.tsx
  libs/shared/ui/src/components/FormiumForm/Button/index.ts
  libs/shared/ui/src/components/FormiumForm/Checkbox/Checkbox.tsx
  libs/shared/ui/src/components/FormiumForm/Checkbox/index.ts
  libs/shared/ui/src/components/FormiumForm/ElementsWrapper/ElementsWrapper.tsx
  libs/shared/ui/src/components/FormiumForm/ElementsWrapper/index.ts
  libs/shared/ui/src/components/FormiumForm/FooterWrapper/FooterWrapper.tsx
  libs/shared/ui/src/components/FormiumForm/FooterWrapper/index.ts
  libs/shared/ui/src/components/FormiumForm/FormControl/FormControl.tsx
  libs/shared/ui/src/components/FormiumForm/FormControl/index.ts
  libs/shared/ui/src/components/FormiumForm/FormiumForm.stories.tsx
  libs/shared/ui/src/components/FormiumForm/FormiumForm.tsx
  libs/shared/ui/src/components/FormiumForm/Header/Header.tsx
  libs/shared/ui/src/components/FormiumForm/Header/index.ts
  libs/shared/ui/src/components/FormiumForm/PageWrapper/PageWrapper.tsx
  libs/shared/ui/src/components/FormiumForm/PageWrapper/index.ts
  libs/shared/ui/src/components/FormiumForm/RadioGroup/RadioGroup.tsx
  libs/shared/ui/src/components/FormiumForm/RadioGroup/index.ts
  libs/shared/ui/src/components/FormiumForm/TextInput/TextInput.tsx
  libs/shared/ui/src/components/FormiumForm/TextInput/index.ts
  libs/shared/ui/src/components/FormiumForm/Textarea/Textarea.tsx
  libs/shared/ui/src/components/FormiumForm/Textarea/index.ts
  libs/shared/ui/src/components/FormiumForm/index.ts
  libs/shared/ui/src/libs/formiumClient/formiumClient.ts
  libs/shared/ui/src/libs/formiumClient/index.ts
  package-lock.json
  package.json
Labels: effort: 5, priority: soon, type: feat

#1910 feat: add featured checkbox to dialog
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/GetTemplate.ts
  apps/journeys-admin/__generated__/JourneyFeature.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/src/components/Editor/ActionDetails/data.ts
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.stories.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/FeaturedCheckbox/FeaturedCheckbox.spec.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/FeaturedCheckbox/FeaturedCheckbox.stories.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/FeaturedCheckbox/FeaturedCheckbox.tsx
  apps/journeys-admin/src/components/JourneyView/TitleDescription/FeaturedCheckbox/index.ts
  apps/journeys-admin/src/components/JourneyView/TitleDescription/TitleDescriptionDialog/TitleDescriptionDialog.tsx
  apps/journeys-admin/src/components/JourneyView/data.ts
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/watch/__generated__/JourneyFields.ts
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.spec.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.spec.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.stories.tsx
  libs/journeys/ui/src/components/StepFooter/HostTitleLocation/HostTitleLocation.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.stories.tsx
  libs/journeys/ui/src/libs/JourneyProvider/JourneyProvider.spec.tsx
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/journeyFields.tsx
  libs/journeys/ui/src/libs/rtl/rtl.spec.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: soon, type: feat

#1922 feat: template tags parameters
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
Labels: priority: soon, type: feat, effort: 1

#1907 test: add new workflow that can be run on demand to run tests or to update-snapshots
  .github/workflows/e2e-tests.yml
Labels: type: test, priority: 2day, effort: 2, type: ci

#1921 fix: add service field to tags
  apps/api-gateway/schema.graphql
  apps/api-tags/db/migrations/20230928010218_20230928010217/migration.sql
  apps/api-tags/db/schema.prisma
  apps/api-tags/project.json
  apps/api-tags/schema.graphql
  apps/api-tags/src/app/__generated__/graphql.ts
  apps/api-tags/src/app/modules/tag/tag.graphql
  apps/api-tags/src/app/modules/tag/tag.resolver.spec.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#1927 feat: aurora enhanced monitoring
  infrastructure/modules/aws/aurora/main.tf
Labels: priority: soon, type: feat, effort: 1

#1928 fix: show journey on public template page
  apps/journeys-admin/__generated__/GetAdminJourney.ts
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/src/components/TemplateView/TempateView.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  apps/journeys-admin/src/components/TemplateView/index.ts
  apps/journeys-admin/src/libs/useJourneyQuery/index.ts
  apps/journeys-admin/src/libs/useJourneyQuery/useJourneyQuery.spec.tsx
  apps/journeys-admin/src/libs/useJourneyQuery/useJourneyQuery.ts
  libs/journeys/ui/src/libs/JourneyProvider/journeyFields.tsx
Labels: priority: 2day, type: fix, effort: 3
