Repository JesusFilm/core, pull requests merged in 2023-02, with the labels that each got.

#1286 feat: add viewed at to userjourneys
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.graphql
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#1287 23 01 gw feat title search
  .devcontainer/docker-compose.yml
  apps/watch/pages/videos.tsx
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
Labels: effort: 3

#1301 feat: api-media cloudflare extension
  apps/api-gateway/schema.graphql
  apps/api-media/db/seed.ts
  apps/api-media/schema.graphql
  apps/api-media/src/app/__generated__/graphql.ts
  apps/api-media/src/app/app.module.ts
  apps/api-media/src/app/modules/cloudflare/image/image.graphql
  apps/api-media/src/app/modules/cloudflare/image/image.module.ts
  apps/api-media/src/app/modules/cloudflare/image/image.resolver.spec.ts
  apps/api-media/src/app/modules/cloudflare/image/image.resolver.ts
  apps/api-media/src/app/modules/cloudflare/image/image.service.spec.ts
  apps/api-media/src/app/modules/cloudflare/image/image.service.ts
Labels: effort: 5, priority: soon, type: feat, on stage

#1307 fix: update earliest good commit
  .github/workflows/main.yml
Labels: type: fix, priority: now, effort: 1

#1279 feat: add user invite api
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/seed.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/modules/userInvite/userInvite.graphql
  apps/api-journeys/src/app/modules/userInvite/userInvite.module.ts
  apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.spec.ts
  apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
  apps/api-journeys/src/app/modules/userInvite/userInvite.service.spec.ts
  apps/api-journeys/src/app/modules/userInvite/userInvite.service.ts
  libs/nest/common/src/lib/firebaseClient/firebaseClient.ts
  libs/nest/common/src/lib/firebaseClient/index.ts
  libs/nest/decorators/src/lib/CurrentUser/CurrentUser.ts
  libs/nest/decorators/src/lib/CurrentUser/index.ts
Labels: priority: 2day, effort: 3, type: feat, on stage

#1293 feat: approve invited user on journey related pages
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
Labels: effort: 2, priority: soon, type: feat

#1306 feat: image selection component
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx
Labels: effort: 3, priority: soon, type: feat

#1311 chore: update router cors to match domains and be cacheable
  .devcontainer/post-create-command.sh
  apps/api-gateway/Dockerfile
  apps/api-gateway/router.prod.yaml
  apps/api-gateway/router.yaml
  apps/api-gateway/routerSchema.json
Labels: priority: soon, effort: 1, type: chore, on stage

#1304 feat: limit subtitle count
  apps/watch/src/components/VideosPage/LanguagesFilter/LanguagesFilter.spec.tsx
  apps/watch/src/components/VideosPage/LanguagesFilter/LanguagesFilter.tsx
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.tsx
Labels: effort: 2, priority: now, type: feat

#1313 fix: render custom dialog action component
  libs/shared/ui/src/components/Dialog/Dialog.spec.tsx
  libs/shared/ui/src/components/Dialog/Dialog.stories.tsx
  libs/shared/ui/src/components/Dialog/Dialog.tsx
Labels: priority: 2day, effort: 2, type: fix

#1312 feat: api-media unsplash schema update
  apps/api-gateway/schema.graphql
  apps/api-media/schema.graphql
  apps/api-media/src/app/__generated__/graphql.ts
  apps/api-media/src/app/modules/unsplash/image/image.graphql
Labels: priority: now, type: feat, effort: 1, on stage

#1294 feat: user journey openat on journey view
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/GetTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/UserJourneyOpen.ts
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/src/components/JourneyView/data.ts
  apps/journeys-admin/src/libs/useUserJourneyOpen/index.ts
  apps/journeys-admin/src/libs/useUserJourneyOpen/useUserJourneyOpen.spec.tsx
  apps/journeys-admin/src/libs/useUserJourneyOpen/useUserJourneyOpen.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/journeyFields.tsx
Labels: effort: 2, priority: soon, type: feat

#1299 feat: multiple filter UI
  .vscode/settings.json
  apps/watch/src/components/FilterContainer/FilterContainer.stories.tsx
  apps/watch/src/components/FilterContainer/FilterContainer.tsx
Labels: effort: 2, priority: soon, type: feat

#1295 feat: add journeyProfile table
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/seed.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.graphql
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.module.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.spec.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.service.spec.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.service.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#1318 chore: add datadog and gtm to watch
  apps/watch/pages/_app.tsx
Labels: priority: now, effort: 1, type: chore

#1322 chore: add base path to watch
  apps/watch/next.config.js
  apps/watch/pages/_document.tsx
  apps/watch/public/fonts/fonts.css
  apps/watch/public/loading-blurhash.png
  apps/watch/public/site.webmanifest
  apps/watch/src/components/Footer/FooterLink/FooterLink.spec.tsx
  apps/watch/src/components/Footer/FooterLogos/FooterLogos.tsx
  apps/watch/src/components/Footer/FooterLogos/assets/cru.svg
  apps/watch/src/components/Footer/FooterLogos/assets/jesus-film.svg
  apps/watch/src/components/Footer/FooterSocials/FooterSocials.tsx
  apps/watch/src/components/Footer/FooterSocials/assets/facebook.svg
  apps/watch/src/components/Footer/FooterSocials/assets/instagram.svg
  apps/watch/src/components/Footer/FooterSocials/assets/twitter.svg
  apps/watch/src/components/Footer/FooterSocials/assets/youtube.svg
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx
  apps/watch/src/components/Header/assets/logo.svg
  apps/watch/src/components/HeroOverlay/HeroOverlay.tsx
  apps/watch/src/components/HeroOverlay/assets/overlay.svg
  apps/watch/src/components/HomePage/HomeHero/HomeHero.spec.tsx
  apps/watch/src/components/HomePage/HomeHero/HomeHero.tsx
  apps/watch/src/components/HomePage/HomeHero/assets/jesus.jpg
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideosPage/Hero/VideosHero.tsx
  apps/watch/src/components/VideosPage/Hero/assets/background.png
Labels: effort: 3, priority: now, type: chore

#1324 refactor: rename user journey list and item
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserList/UserList.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserList.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/ApproveUser/ApproveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/ApproveUser/ApproveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/ApproveUser/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/PromoteUser/PromoteUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/PromoteUser/PromoteUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/PromoteUser/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/RemoveUser/RemoveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/RemoveUser/RemoveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/RemoveUser/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/UserListItem.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/UserListItem.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserList/index.ts
Labels: priority: 2day, effort: 1, type: refactor

#1315 feat: remove axios dependency
  apps/api-journeys/src/app/modules/block/image/image.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/image/image.resolver.ts
  package-lock.json
  package.json
Labels: effort: 3, priority: soon, type: feat, on stage

#1321 feat: hide unsplash via launch darkly
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/index.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#1317 feat: cf upload complete api
  apps/api-gateway/schema.graphql
  apps/api-media/schema.graphql
  apps/api-media/src/app/__generated__/graphql.ts
  apps/api-media/src/app/modules/cloudflare/image/image.graphql
  apps/api-media/src/app/modules/cloudflare/image/image.resolver.spec.ts
  apps/api-media/src/app/modules/cloudflare/image/image.resolver.ts
  apps/api-media/src/app/modules/cloudflare/image/image.service.spec.ts
  apps/api-media/src/app/modules/cloudflare/image/image.service.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#1326 fix: loader sort order according to ids
  libs/nest/database/src/lib/BaseService.spec.ts
  libs/nest/database/src/lib/BaseService.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1328 fix: keep collection when changing language
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.spec.tsx
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.tsx
Labels: type: fix, priority: now, effort: 1

#1320 feat: add useCurrentUser hook
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/libs/useCurrentUser/index.ts
  apps/journeys-admin/src/libs/useCurrentUser/useCurrentUser.spec.tsx
  apps/journeys-admin/src/libs/useCurrentUser/useCurrentUser.ts
Labels: priority: 2day, effort: 2, type: fix, type: feat

#1329 chore: unsplash nullable
  apps/api-gateway/schema.graphql
  apps/api-media/schema.graphql
  apps/api-media/src/app/__generated__/graphql.ts
  apps/api-media/src/app/modules/unsplash/image/image.graphql
Labels: priority: now, effort: 1, type: chore, on stage

#1330 chore: cloudflare api changes
  apps/api-gateway/schema.graphql
  apps/api-media/schema.graphql
  apps/api-media/src/app/__generated__/graphql.ts
  apps/api-media/src/app/modules/cloudflare/image/image.graphql
  apps/api-media/src/app/modules/cloudflare/image/image.resolver.spec.ts
  apps/api-media/src/app/modules/cloudflare/image/image.resolver.ts
  apps/api-media/src/app/modules/cloudflare/image/image.service.spec.ts
  apps/api-media/src/app/modules/cloudflare/image/image.service.ts
Labels: effort: 3, priority: soon, type: chore, on stage

#1297 feat: integrate unsplash gallery to journeys admin
  apps/journeys-admin/__generated__/ListUnsplashCollectionPhotos.ts
  apps/journeys-admin/__generated__/SearchUnsplashPhotos.ts
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/UnsplashGallery.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/UnsplashGallery.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/UnsplashGallery.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/UnsplashList/UnsplashList.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/UnsplashList/UnsplashList.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/UnsplashList/index.ts
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/UnsplashSearch/UnsplashSearch.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/UnsplashSearch/UnsplashSearch.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/UnsplashSearch/index.ts
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/data.ts
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/index.ts
  apps/journeys-admin/src/libs/apolloClient/cache.ts
Labels: effort: 3, priority: soon, type: feat

#1325 feat: custom url upload to cloudflare
  apps/journeys-admin/__generated__/CreateCloudflareUploadByUrl.ts
  apps/journeys-admin/next.config.js
  apps/journeys-admin/src/components/Editor/ImageLibrary/CustomImage/CustomImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/CustomImage/CustomImage.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/CustomImage/CustomUrl/CustomUrl.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/CustomImage/CustomUrl/CustomUrl.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/CustomImage/CustomUrl/index.ts
  apps/journeys-admin/src/components/Editor/ImageLibrary/CustomImage/index.ts
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx
  apps/journeys/next.config.js
Labels: effort: 5, priority: soon, type: feat

#1332 fix: set pages to no index no follow
  apps/watch/pages/_app.tsx
Labels: type: fix, priority: now, effort: 1

#1300 feat: manage access button
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.spec.tsx
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.stories.tsx
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.tsx
  apps/journeys-admin/src/components/AccessAvatars/ManageAccessAvatar/ManageAccessAvatar.tsx
  apps/journeys-admin/src/components/AccessAvatars/ManageAccessAvatar/index.ts
  apps/journeys-admin/src/components/JourneyView/Properties/AccessControl/AccessControl.tsx
  apps/journeys-admin/src/components/JourneyView/Properties/Properties.tsx
Labels: priority: soon, type: feat, effort: 1

#1334 feat: skip blurhash processing
  apps/api-journeys/src/app/modules/block/image/image.graphql
  apps/api-journeys/src/app/modules/block/image/image.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/image/image.resolver.ts
Labels: priority: now, type: feat, effort: 1, on stage

#1331 feat: load children for container or video in async
  .devcontainer/devcontainer.json
  .storybook/main.js
  .storybook/preview-head.html
  .vscode/extensions.json
  .vscode/settings.json
  apps/watch/__generated__/GetHomeVideos.ts
  apps/watch/__generated__/GetVideoChildren.ts
  apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
  apps/watch/__generated__/GetVideoContent.ts
  apps/watch/__generated__/GetVideos.ts
  apps/watch/__generated__/GetVideosForTestData.ts
  apps/watch/__generated__/VideoChildFields.ts
  apps/watch/__generated__/VideoContentFields.ts
  apps/watch/pages/_app.tsx
  apps/watch/public/styles/swiper-js.css
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideoCarousel/NavButton/NavButton.stories.tsx
  apps/watch/src/components/VideoCarousel/NavButton/NavButton.tsx
  apps/watch/src/components/VideoCarousel/NavButton/index.ts
  apps/watch/src/components/VideoCarousel/VideoCarousel.spec.tsx
  apps/watch/src/components/VideoCarousel/VideoCarousel.stories.tsx
  apps/watch/src/components/VideoCarousel/VideoCarousel.tsx
  apps/watch/src/components/VideoCarousel/index.ts
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.spec.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.stories.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
  apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.tsx
  apps/watch/src/components/VideoContentPage/VideoContentCarousel/index.ts
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  apps/watch/src/components/VideoContentPage/VideoHeading/VideoHeading.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHeading/VideoHeading.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoHeading/VideoHeading.tsx
  apps/watch/src/components/VideoContentPage/VideoHeading/index.ts
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
  apps/watch/src/components/Videos/__generated__/testData.ts
  apps/watch/src/components/VideosCarousel/VideosCarousel.spec.tsx
  apps/watch/src/components/VideosCarousel/VideosCarousel.stories.tsx
  apps/watch/src/components/VideosCarousel/VideosCarousel.tsx
  apps/watch/src/components/VideosCarousel/VideosCarouselNavButton/VideosCarouselNavButton.stories.tsx
  apps/watch/src/components/VideosCarousel/VideosCarouselNavButton/VideosCarouselNavButton.tsx
  apps/watch/src/components/VideosCarousel/index.ts
  apps/watch/src/libs/useVideoChildren/getVideoChildrenMock.ts
  apps/watch/src/libs/useVideoChildren/index.ts
  apps/watch/src/libs/useVideoChildren/useVideoChildren.ts
  apps/watch/src/libs/videoChildFields.ts
  apps/watch/src/libs/videoContentFields.ts
  apps/watch/src/libs/videoContext/VideoContext.spec.tsx
Labels: effort: 5, priority: now, type: feat

#1337 fix: change children language when selected
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  apps/watch/src/libs/useVideoChildren/getVideoChildrenMock.ts
  apps/watch/src/libs/useVideoChildren/useVideoChildren.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1340 feat: upload image
  apps/journeys-admin/__generated__/CreateCloudflareUploadByFile.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/CustomImage/CustomImage.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/CustomImage/ImageUpload/ImageUpload.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/CustomImage/ImageUpload/ImageUpload.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/CustomImage/ImageUpload/ImageUpload.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/CustomImage/ImageUpload/index.ts
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx
  package-lock.json
  package.json
Labels: effort: 5, priority: now, type: feat

#1342 chore: add loaders to language dialog
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.stories.tsx
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.stories.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.tsx
Labels: priority: now, type: feat, effort: 1

#1339 fix: header and footer links opening in window or new window
  apps/watch/src/components/Footer/FooterLink/FooterLink.spec.tsx
  apps/watch/src/components/Footer/FooterLink/FooterLink.tsx
  apps/watch/src/components/Footer/FooterLinks/FooterLinks.spec.tsx
  apps/watch/src/components/Footer/FooterLinks/FooterLinks.tsx
  apps/watch/src/components/Footer/FooterLogos/FooterLogos.spec.tsx
  apps/watch/src/components/Footer/FooterLogos/FooterLogos.tsx
  apps/watch/src/components/Footer/FooterSocials/FooterSocials.spec.tsx
  apps/watch/src/components/Footer/FooterSocials/FooterSocials.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.spec.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx
Labels: type: fix, priority: now, effort: 1

#1341 fix: forward root to base path on watch
  apps/watch/next.config.js
Labels: type: fix, priority: now, effort: 1

#1344 fix: terms dialog uncheck download agree when cancelling
  apps/watch/src/components/DownloadDialog/DownloadDialog.spec.tsx
  apps/watch/src/components/DownloadDialog/DownloadDialog.tsx
  apps/watch/src/components/DownloadDialog/TermsOfUseDialog/TermsOfUseDialog.stories.tsx
  apps/watch/src/components/DownloadDialog/TermsOfUseDialog/TermsOfUseDialog.tsx
  apps/watch/src/components/DownloadDialog/TermsOfUseDialog/index.ts
  apps/watch/src/components/DownloadDialog/TermsOfUseModal/TermsOfUseModal.stories.tsx
Labels: type: fix, priority: now, effort: 1

#1310 feat: avatar status
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.spec.tsx
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.stories.tsx
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.tsx
  apps/journeys-admin/src/components/AccessAvatars/ManageAccessAvatar/ManageAccessAvatar.tsx
  apps/journeys-admin/src/components/AccessAvatars/data.ts
  apps/journeys-admin/src/components/Avatar/Avatar.spec.tsx
  apps/journeys-admin/src/components/Avatar/Avatar.stories.tsx
  apps/journeys-admin/src/components/Avatar/Avatar.tsx
  apps/journeys-admin/src/components/Avatar/index.ts
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardInfo/JourneyCardInfo.spec.tsx
Labels: effort: 5, priority: soon, type: feat

#1345 fix: hide player loader and mute button on hero
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.tsx
Labels: type: fix, priority: now, effort: 1

#1327 fix: update userJourney and userInvite resolvers
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/action/action.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/card/card.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/gridContainer/gridContainer.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/gridItem/gridItem.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/icon/icon.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/image/image.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/typography/typography.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/videoTrigger/videoTrigger.resolver.spec.ts
  apps/api-journeys/src/app/modules/userInvite/userInvite.graphql
  apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.spec.ts
  apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.service.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.service.ts
Labels: priority: 2day, type: fix, effort: 3, on stage

#1346 fix: remove start icon from CopyLinkField
  libs/shared/ui/src/components/CopyTextField/CopyTextField.tsx
Labels: priority: 2day, type: fix, effort: 1

#1316 feat: terms and conditions
  apps/journeys-admin/__generated__/GetJourneyProfile.ts
  apps/journeys-admin/__generated__/JourneyProfileCreate.ts
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/publisher/[journeyId].tsx
  apps/journeys-admin/pages/publisher/[journeyId]/edit.tsx
  apps/journeys-admin/pages/publisher/index.tsx
  apps/journeys-admin/pages/reports/journeys.tsx
  apps/journeys-admin/pages/reports/visitors.tsx
  apps/journeys-admin/pages/reports/visitors/[visitorId].tsx
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/pages/users/terms-and-conditions.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.spec.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.stories.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsListItem/TermsListItem.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsListItem/index.tsx
  apps/journeys-admin/src/components/TermsAndConditions/index.tsx
  apps/journeys-admin/src/libs/useTermsRedirect/index.ts
  apps/journeys-admin/src/libs/useTermsRedirect/useTermsRedirect.spec.tsx
  apps/journeys-admin/src/libs/useTermsRedirect/useTermsRedirect.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: soon, type: feat

#1323 feat: journey builder invite by email
  apps/journeys-admin/__generated__/GetUserInvites.ts
  apps/journeys-admin/__generated__/NewUserInvite.ts
  apps/journeys-admin/__generated__/UserInviteCreate.ts
  apps/journeys-admin/__generated__/UserInviteRemove.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/AddUserSection.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/AddUserSection.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/AddUserSection.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserList/UserList.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserList.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/ApproveUser/ApproveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/ApproveUser/ApproveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/PromoteUser/PromoteUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/RemoveUser/RemoveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/RemoveUser/RemoveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/UserListItem.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/UserListItem.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.spec.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
  package-lock.json
Labels: effort: 5, priority: soon, type: feat

#1348 test: remove commented tests
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/CustomImage/CustomUrl/CustomUrl.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/CustomImage/CustomUrl/data.ts
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
Labels: type: test, effort: 3, priority: soon

#1343 fix: update unsplash gallery design
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/UnsplashGallery.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/UnsplashSearch/UnsplashSearch.tsx
Labels: type: fix, priority: soon, effort: 1

#1335 feat: access denied redesign
  apps/journeys-admin/src/components/AccessDenied/AccessDenied.spec.tsx
  apps/journeys-admin/src/components/AccessDenied/AccessDenied.tsx
  apps/journeys-admin/src/components/AccessDenied/AccessDeniedCard/AccessDeniedCard.tsx
  apps/journeys-admin/src/components/AccessDenied/AccessDeniedListItem/AccessDeniedListItem.tsx
  apps/journeys-admin/src/components/AccessDenied/AccessDeniedListItem/index.tsx
  apps/journeys-admin/src/components/JourneyInvite/JourneyInvite.spec.tsx
  apps/journeys-admin/src/components/JourneyInvite/JourneyInvite.tsx
  apps/journeys-admin/src/components/PublisherInvite/PublisherInvite.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: effort: 2, priority: soon, type: feat

#1308 feat: next steps permissions
  apps/journeys-admin/__generated__/GetUserInvites.ts
  apps/journeys-admin/__generated__/NewUserInvite.ts
  apps/journeys-admin/__generated__/UserInviteAcceptAll.ts
  apps/journeys-admin/__generated__/UserInviteCreate.ts
  apps/journeys-admin/__generated__/UserInviteRemove.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/AddUserSection.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/AddUserSection.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/AddUserSection.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/index.ts
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/ApproveUser/ApproveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/ApproveUser/ApproveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/RemoveUser/RemoveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/RemoveUser/RemoveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/UserJourneyItem.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/UserJourneyItem.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyItem/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyList.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/UserJourneyList.tsx
  apps/journeys-admin/src/components/AccessDialog/UserJourneyList/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserList/UserList.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserList.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/ApproveUser/ApproveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/ApproveUser/ApproveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/ApproveUser/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/PromoteUser/PromoteUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/PromoteUser/PromoteUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/PromoteUser/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/RemoveUser/RemoveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/RemoveUser/RemoveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/RemoveUser/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/UserListItem.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/UserListItem.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/index.ts
  apps/journeys-admin/src/components/AccessDialog/UserList/index.ts
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.spec.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
  package-lock.json
Labels: effort: 8, priority: soon, type: feat

#1349 fix: number of watch related quick fixes
  apps/watch/src/components/Footer/Footer.tsx
  apps/watch/src/components/Footer/FooterLogos/FooterLogos.tsx
  apps/watch/src/components/Footer/FooterLogos/assets/jesus-film.svg
  apps/watch/src/components/Footer/FooterSocials/FooterSocials.tsx
  apps/watch/src/components/HeroOverlay/HeroOverlay.tsx
  apps/watch/src/components/HomePage/HomeHero/HomeHero.tsx
  apps/watch/src/components/VideoContentPage/VideoHeading/VideoHeading.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
  apps/watch/src/components/VideosPage/Hero/VideosHero.tsx
Labels: type: fix, effort: 3, priority: now

#1314 feat: filter new journeys
  apps/journeys-admin/__generated__/GetActiveJourneys.ts
  apps/journeys-admin/__generated__/GetActivePublisherTemplates.ts
  apps/journeys-admin/__generated__/GetArchivedJourneys.ts
  apps/journeys-admin/__generated__/GetArchivedPublisherTemplates.ts
  apps/journeys-admin/__generated__/GetJourneys.ts
  apps/journeys-admin/__generated__/GetPublishedTemplates.ts
  apps/journeys-admin/__generated__/GetTrashedJourneys.ts
  apps/journeys-admin/__generated__/GetTrashedPublisherTemplates.ts
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/AccessAvatars/data.ts
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActiveJourneyListData.ts
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActivePriorityList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActivePriorityList.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/index.ts
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/journeyListData.ts
  apps/journeys-admin/src/components/TemplateList/ActiveTemplates/ActiveTemplates.tsx
  apps/journeys-admin/src/components/TemplateList/ArchivedTemplates/ArchivedTemplates.tsx
  apps/journeys-admin/src/components/TemplateList/TrashedTemplates/TrashedTemplates.tsx
Labels: effort: 2, priority: soon, type: feat

#1336 feat: add badge to journey nav
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActivePriorityList.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.tsx
  apps/journeys-admin/src/components/PageWrapper/utils/getJourneyTooltip/getJourneyTooltip.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/utils/getJourneyTooltip/getJourneyTooltip.ts
  apps/journeys-admin/src/components/PageWrapper/utils/getJourneyTooltip/index.ts
  apps/journeys-admin/src/libs/useActiveJourneys/index.ts
  apps/journeys-admin/src/libs/useActiveJourneys/useActiveJourneys.spec.tsx
  apps/journeys-admin/src/libs/useActiveJourneys/useActiveJourneys.ts
  apps/journeys-admin/src/libs/useJourneys/index.ts
  apps/journeys-admin/src/libs/useJourneys/useJourneys.spec.tsx
  apps/journeys-admin/src/libs/useJourneys/useJourneys.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: soon, type: feat

#1351 fix: unsplash author redirect
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/UnsplashGallery.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/UnsplashList/UnsplashList.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/index.ts
Labels: type: fix, priority: now, effort: 1

#1338 fix: image library folder structure and update few designs
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Image.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Image.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomImage.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomImage.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomUrl/CustomUrl.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomUrl/CustomUrl.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomUrl/data.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomUrl/index.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/index.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/index.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx
  apps/journeys-admin/src/components/Editor/ImageSource/ImageSource.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageSource/ImageSource.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageSource/ImageSource.tsx
  apps/journeys-admin/src/components/Editor/ImageSource/index.ts
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.spec.tsx
Labels: type: fix, priority: soon, effort: 1

#1352 fix: opened at mutation call
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
Labels: type: fix, priority: soon, effort: 1

#1291 feat: cloudflare image upload
  apps/journeys-admin/__generated__/BlockDeleteForBackgroundVideo.ts
  apps/journeys-admin/__generated__/CardBlockBackgroundVideoUpdate.ts
  apps/journeys-admin/__generated__/CreateCloudflareUploadByFile.ts
  apps/journeys-admin/__generated__/CreateCloudflareUploadByUrl.ts
  apps/journeys-admin/next.config.js
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Image.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Image.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomImage.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomImage.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomUrl/CustomUrl.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomUrl/CustomUrl.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomUrl/data.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomUrl/index.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/index.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/index.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/index.ts
  apps/journeys-admin/src/components/Editor/ImageSource/ImageSource.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageSource/ImageSource.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageSource/ImageSource.tsx
  apps/journeys-admin/src/components/Editor/ImageSource/index.ts
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/index.ts
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/index.ts
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
  apps/journeys/next.config.js
  package-lock.json
  package.json
Labels: effort: 8, priority: soon, type: feat, on stage

#1333 feat: integrate filter container to video page
  apps/watch/src/components/FilterContainer/FilterContainer.stories.tsx
  apps/watch/src/components/FilterContainer/FilterContainer.tsx
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
Labels: effort: 2, priority: soon, type: feat

#1350 feat: add default jfm collection to videos page
  apps/watch/pages/videos.tsx
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.stories.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
Labels: effort: 2, priority: soon, type: feat

#1355 fix: big divider render logic
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActivePriorityList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActivePriorityList.tsx
Labels: type: fix, priority: soon, effort: 1

#1358 fix: bad schema
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1359 fix: api-media force rebuild
  apps/api-media/src/app/modules/cloudflare/image/image.resolver.ts
Labels: type: fix, priority: now, effort: 1

#1360 fix: api media
  apps/api-media/src/app/modules/cloudflare/image/image.resolver.ts
  package-lock.json
  package.json
Labels: type: fix, priority: now, effort: 1, on stage

#1361 fix: api-media
  apps/api-media/Dockerfile
Labels: type: fix, priority: now, effort: 1, on stage

#1364 feat: api-media unsplash dl
  apps/api-gateway/schema.graphql
  apps/api-media/schema.graphql
  apps/api-media/src/app/__generated__/graphql.ts
  apps/api-media/src/app/modules/unsplash/image/image.graphql
  apps/api-media/src/app/modules/unsplash/image/image.resolver.spec.ts
  apps/api-media/src/app/modules/unsplash/image/image.resolver.ts
  apps/api-media/src/app/modules/unsplash/image/image.service.spec.ts
  apps/api-media/src/app/modules/unsplash/image/image.service.ts
Labels: priority: now, type: feat, effort: 1, on stage

#1365 feat: use query params
  apps/watch/src/components/FilterContainer/FilterContainer.stories.tsx
  apps/watch/src/components/FilterContainer/FilterContainer.tsx
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
Labels: effort: 3, priority: now, type: feat

#1354 fix: remove medias from videos page
  apps/watch/src/components/Footer/Footer.tsx
  apps/watch/src/components/VideosPage/SubHero/VideosSubHero.tsx
Labels: type: fix, priority: soon, effort: 1

#1368 feat: hide report with flag
  apps/journeys-admin/src/components/JourneyList/JourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
Labels: priority: soon, type: feat, effort: 1

#1290 test: remove duplicate test
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
Labels: type: test, priority: soon, effort: 1

#1372 fix: rework button and info
  apps/watch/src/components/HomePage/SeeAllVideos/SeeAllVideos.spec.tsx
  apps/watch/src/components/HomePage/SeeAllVideos/SeeAllVideos.tsx
Labels: priority: 2day, effort: 2, type: fix

#1244 fix: card selection panel
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
Labels: type: fix, priority: soon, effort: 1

#1369 fix: background media selection
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
Labels: type: fix, priority: soon, effort: 1

#1377 fix: unsplash schema
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/image/image.graphql
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: type: fix, priority: now, effort: 1

#1292 feat: unsplash gallery
  apps/journeys-admin/__generated__/ListUnsplashCollectionPhotos.ts
  apps/journeys-admin/__generated__/SearchUnsplashPhotos.ts
  apps/journeys-admin/__generated__/TriggerUnsplashDownload.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashGallery.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashGallery.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashGallery.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashList/UnsplashList.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashList/UnsplashList.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashList/index.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashSearch/UnsplashSearch.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashSearch/UnsplashSearch.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/UnsplashSearch/index.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/data.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/UnsplashGallery/index.ts
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/index.tsx
  apps/journeys-admin/src/libs/apolloClient/cache.ts
Labels: effort: 8, priority: soon, type: feat, on stage

#1371 feat: hide app permissions
  apps/journeys-admin/src/components/JourneyList/JourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
  apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.spec.tsx
  apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.stories.tsx
  apps/journeys-admin/src/components/TemplateLibrary/TemplateLibrary.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#1378 feat: jesusfilm whitelist
  apps/api-gateway/router.prod.yaml
Labels: priority: now, type: feat, effort: 1

#1357 fix: image upload error state
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomImage.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomImage.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx
  apps/journeys-admin/src/components/Editor/ImageSource/ImageSource.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.tsx
Labels: type: fix, priority: soon, effort: 1

#1379 feat: remove seo blocking
  apps/watch/pages/_app.tsx
Labels: priority: now, type: feat, effort: 1

#1376 fix: access denied edit report
  apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
Labels: type: fix, priority: soon, effort: 1

#1375 feat: add tooltip for new journey badge
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardText/JourneyCardText.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardText/JourneyCardText.tsx
Labels: priority: soon, type: feat, effort: 1

#1383 fix: watch links to use proper extensions
  apps/watch/pages/[part1]/[part2].tsx
  apps/watch/pages/[part1]/[part2]/[part3].tsx
  apps/watch/src/components/VideoCard/VideoCard.spec.tsx
  apps/watch/src/components/VideoCard/VideoCard.tsx
Labels: type: fix, priority: now, effort: 1
