Repository JesusFilm/core, pull requests merged in 2023-11, with the labels that each got.

#1821 fix: resize journey card icons
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/can-we-trust-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/can-we-trust-chrome-mobile-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/jesus-history-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/jesus-history-chrome-mobile-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/who-was-jesus-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/who-was-jesus-chrome-mobile-linux.png
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/FooterButtonList.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ReactionButton/ReactionButton.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareButton.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/StyledFooterButton/StyledFooterButton.tsx
Labels: type: fix, priority: soon, effort: 1

#2005 fix: add icons to admin forms
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/CategoriesTabPanel/CategoriesTabPanel.spec.tsx
  apps/journeys-admin/src/components/JourneyView/TemplateSettings/TemplateSettingsDialog/CategoriesTabPanel/CategoriesTabPanel.tsx
  apps/journeys-admin/src/components/ParentTagIcon/ParentTagIcon.spec.tsx
  apps/journeys-admin/src/components/ParentTagIcon/ParentTagIcon.tsx
  apps/journeys-admin/src/components/ParentTagIcon/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TemplateTags.tsx
Labels: type: fix, priority: soon, effort: 1

#2016 feat: add creator fields to api-journeys
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20231030032756_20231030032747/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/image/image.graphql
  apps/api-journeys/src/app/modules/host/host.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: priority: now, type: feat, effort: 1, on stage

#2017 fix: add mousewheel horizontal scroll
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.tsx
Labels: type: fix, priority: soon, effort: 1

#2013 refactor: ga4 events enhancements
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/src/components/DiscoveryJourneys/EmbedJourney/EmbedJourney.tsx
  apps/journeys-admin/src/components/Team/TeamProvider/TeamProvider.spec.tsx
  apps/journeys-admin/src/components/Team/TeamProvider/TeamProvider.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/shared/ui/src/components/FormiumForm/formComponents/Header/Header.tsx
Labels: priority: soon, effort: 1, type: refactor

#2008 fix: collections filter tray
  apps/journeys-admin/src/components/TemplateGallery/TagsFilter/TagsFilter.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagsFilter/TagsFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.tsx
Labels: effort: 5, type: fix, priority: soon

#2019 feat: outboundgoal events
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.spec.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.tsx
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Button/utils/findChatPlatform/findChatPlatform.ts
  libs/journeys/ui/src/components/Button/utils/findChatPlatform/index.ts
  libs/journeys/ui/src/components/Button/utils/getLinkActionGoal/getLinkActionGoal.spec.ts
  libs/journeys/ui/src/components/Button/utils/getLinkActionGoal/getLinkActionGoal.ts
  libs/journeys/ui/src/components/Button/utils/getLinkActionGoal/index.ts
  libs/locales/en/journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#2020 refactor: admin report tweak
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/pages/reports/journeys.tsx
  apps/journeys-admin/pages/reports/visitors.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/ReportMenuItem/ReportMenuItem.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/ReportMenuItem/ReportMenuItem.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: priority: soon, effort: 1, type: refactor

#2011 fix: video audio when paging
  apps/journeys/src/components/Conductor/Conductor.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: type: fix, priority: soon, effort: 1

#2004 test: add lighthouse to test suite and add one test to journeys-admin
  apps/journeys-admin-e2e/playwright.config.ts
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts-snapshots/home-page-chromium-linux.png
  apps/journeys-admin-e2e/src/e2e/lighthouse/homepage.spec.ts
  apps/watch-e2e/src/e2e/chapter.spec.ts-snapshots/after-video-firefox-linux.png
  apps/watch-e2e/src/e2e/feature-film.spec.ts-snapshots/after-video-firefox-linux.png
  package-lock.json
  package.json
Labels: type: test, priority: 2day, effort: 8

#2009 feat: tag carousel on templates gallery page
  apps/journeys-admin/next.config.js
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/index.ts
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/index.ts
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/acceptance.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/depression.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/fearAnxiety.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/forgiveness.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/hope.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/jesusFilm.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/loneliness.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/love.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/nua.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/security.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/significance.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/index.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/NavButton/NavButton.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/NavButton/index.ts
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/index.ts
  apps/journeys-admin/src/components/TemplateGallery/data.ts
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.spec.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.stories.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/TemplateSection.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSection/index.ts
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.stories.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  apps/journeys/next.config.js
  package-lock.json
  package.json
Labels: priority: 2day, effort: 5, type: feat

#2021 feat: template dialog settings forms
  apps/journeys-admin/__generated__/JourneySettingsUpdate.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TemplateSettingsDialog/MetadataTabPanel/MetadataTabPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TemplateSettingsDialog/MetadataTabPanel/MetadataTabPanel.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TemplateSettingsDialog/TemplateSettingsDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TemplateSettingsDialog/TemplateSettingsDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TemplateSettingsDialog/TemplateSettingsDialog.tsx
  apps/journeys-admin/src/libs/useJourneyUpdateMutation/useJourneyUpdateMutation.spec.tsx
  apps/journeys-admin/src/libs/useJourneyUpdateMutation/useJourneyUpdateMutation.ts
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.spec.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.tsx
Labels: effort: 2, type: fix, priority: soon

#2023 test: increase test timeout and no. of retries
  apps/docs-e2e/playwright.config.ts
  apps/journeys-admin-e2e/playwright.config.ts
  apps/journeys-e2e/playwright.config.ts
  apps/watch-e2e/playwright.config.ts
Labels: type: test, priority: now, effort: 1

#2018 docs: add how to update reference snapshots loom video
  apps/docs/docs/03-basics/04-e2e-testing/05-update-ref-snaps.mdx
Labels: type: test, type: docs, priority: soon, effort: 1

#2026 feat: languages filter by ids
  apps/api-gateway/schema.graphql
  apps/api-languages/schema.graphql
  apps/api-languages/src/app/__generated__/graphql.ts
  apps/api-languages/src/app/modules/language/language.graphql
  apps/api-languages/src/app/modules/language/language.resolver.spec.ts
  apps/api-languages/src/app/modules/language/language.resolver.ts
Labels: priority: now, type: feat, effort: 1, on stage

#2025 feat: view templates creator details
  apps/journeys-admin/src/components/JourneyView/SocialImage/SocialImage.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateCreatorDetails/TemplateCreatorDetails.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateCreatorDetails/TemplateCreatorDetails.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateCreatorDetails/TemplateCreatorDetails.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateCreatorDetails/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.tsx
Labels: effort: 3, priority: soon, type: feat

#2010 feat: multiple language select
  apps/journeys-admin/__generated__/GetLanguages.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/setupTests.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.tsx
  apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamCreateForm/TeamCreateForm.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/LanguageFilterDialog/LanguageFilterDialog.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/LanguageFilterDialog/LanguageFilterDialog.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/LanguageFilterDialog/index.ts
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/convertLanguagesToOptions/convertLanguagesToOptions.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/convertLanguagesToOptions/convertLanguagesToOptions.ts
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/convertLanguagesToOptions/index.ts
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/index.ts
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/LanguageFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/LanguageFilterDialog/LanguageFilterDialog.tsx
  apps/journeys-admin/src/components/TemplateGallery/LanguageFilter/index.ts
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
  apps/journeys-admin/src/components/TemplateGallery/data.ts
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.spec.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.stories.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/getButtonLabel/getButtonLabel.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/getButtonLabel/getButtonLabel.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/messagePlatformToLabel/messagePlatformToLabel.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/messagePlatformToLabel/messagePlatformToLabel.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/videoBlockSourceToLabel/videoBlockSourceToLabel.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/videoBlockSourceToLabel/videoBlockSourceToLabel.ts
  apps/journeys-admin/src/libs/useLanguagesQuery/useLanguagesQuery.spec.tsx
  apps/journeys-admin/src/libs/useLanguagesQuery/useLanguagesQuery.ts
  apps/journeys-admin/test/i18n.ts
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/can-we-trust-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/can-we-trust-chrome-mobile-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/jesus-history-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/jesus-history-chrome-mobile-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/who-was-jesus-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/who-was-jesus-chrome-mobile-linux.png
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/MultipleLanguageAutocomplete/MultipleLanguageAutocomplete.spec.tsx
  libs/shared/ui/src/components/MultipleLanguageAutocomplete/MultipleLanguageAutocomplete.stories.tsx
  libs/shared/ui/src/components/MultipleLanguageAutocomplete/MultipleLanguageAutocomplete.tsx
  libs/shared/ui/src/components/MultipleLanguageAutocomplete/index.ts
  package-lock.json
  package.json
Labels: effort: 2, priority: soon, type: feat

#2032 fix: template card image hover
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
Labels: type: fix, priority: soon, effort: 1

#2037 feat: enable merge queues
  .github/workflows/app-deploy.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/danger.yml
  .github/workflows/main.yml
Labels: priority: now, type: feat, effort: 1

#2033 fix: onboarding template import
  .github/workflows/danger.yml
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/src/components/MediaListItem/MediaListItem.spec.tsx
  apps/journeys-admin/src/components/MediaListItem/MediaListItem.stories.tsx
  apps/journeys-admin/src/components/MediaListItem/MediaListItem.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/OnboardingPanelContent.spec.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/OnboardingPanelContent.stories.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/OnboardingPanelContent.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/data.ts
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.spec.tsx
  dangerfile.ts
Labels: type: fix, priority: now, effort: 1

#2035 test: enable checkly disable github actions for monitoring
  .github/workflows/journeys-admin-monitoring.yml
  .github/workflows/journeys-monitoring.yml
  .github/workflows/watch-monitoring.yml
  apps/journeys-admin-e2e/src/monitoring/journeys-admin.monitor.ts
  apps/journeys-e2e/src/monitoring/journeys.monitor.ts
  apps/watch-e2e/src/monitoring/watch.monitor.ts
  checkly.config.ts
  package-lock.json
  package.json
Labels: type: test, effort: 3, priority: soon, type: ci

#2022 feat: step prev event
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20231107225058_20231107225056/migration.sql
  apps/api-journeys/db/migrations/20231113230906_20231113230905/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/event.module.ts
  apps/api-journeys/src/app/modules/event/step/step.graphql
  apps/api-journeys/src/app/modules/event/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/step/step.resolver.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.resolver.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.spec.ts
  apps/journeys-admin/__generated__/GetJourneyVisitors.ts
  apps/journeys-admin/__generated__/GetVisitorEvents.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#2041 fix: reduce worker size by removing swc and esbuild dependencies
  apps/journeys-admin/next.config.js
Labels: type: fix, priority: now, effort: 1

#1800 chore: add storybook linting
  .eslintrc.json
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostListItem/HostListItem.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.stories.tsx
Labels: priority: now, effort: 1, type: chore

#2040 ci: jest sharding
  .github/workflows/main.yml
  jest.preset.js
Labels: priority: now, effort: 1, type: ci

#2036 fix: improve nav buttons disappearing
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/NavButton/NavButton.tsx
Labels: type: fix, priority: soon, effort: 1

#1848 fix: hide downloads if no downloads
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
Labels: type: fix, priority: soon, effort: 1

#2034 fix: keep selected tags and language ids on back click
  apps/journeys-admin/pages/templates/[journeyId].tsx
Labels: type: fix, priority: soon, effort: 1

#1992 refactor: tidy template details UI
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.spec.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateFooter/TemplateFooter.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TemplateTags.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateEditButton/TemplateEditButton.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, effort: 1, type: refactor

#2007 feat: apollo dev debugging
  apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
  apps/journeys/src/libs/apolloClient/apolloClient.ts
  apps/watch/src/libs/apolloClient/apolloClient.ts
Labels: priority: now, type: feat, effort: 1

#2047 fix: remove dd from ssr
  apps/journeys-admin/next.config.js
  apps/journeys-admin/pages/_app.tsx
  apps/journeys/pages/_app.tsx
  apps/watch/pages/_app.tsx
  package-lock.json
  package.json
Labels: type: fix, priority: now, effort: 1

#2050 fix: remove node crypto
  apps/journeys-admin/src/libs/firebaseClient/initAuth.ts
  libs/shared/ui/src/libs/getFirebasePrivateKey/getFirebasePrivateKey.spec.ts
  libs/shared/ui/src/libs/getFirebasePrivateKey/getFirebasePrivateKey.ts
  libs/shared/ui/src/libs/getFirebasePrivateKey/index.ts
Labels: breaking, type: fix, priority: now, effort: 1

#2052 fix: add quotes to journeys admin env file
  apps/journeys-admin/project.json
Labels: type: fix, priority: now, effort: 1

#2039 fix: darken background on hover
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
Labels: type: fix, effort: 3, priority: soon

#2051 feat: next bundle analyzer
  apps/journeys-admin/next.config.js
  apps/journeys-admin/project.json
  package-lock.json
  package.json
Labels: effort: 2, priority: soon, type: feat

#2046 fix: incorrect margin between filter and carousel
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
Labels: type: fix, priority: soon, effort: 1

#2056 feat: updated better health check
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/modules/health/health.controller.ts
  apps/api-journeys/src/app/modules/health/health.module.ts
  apps/api-languages/src/app/app.module.ts
  apps/api-languages/src/app/modules/health/health.controller.ts
  apps/api-languages/src/app/modules/health/health.module.ts
  apps/api-media/src/app/app.module.ts
  apps/api-media/src/app/modules/health/health.controller.ts
  apps/api-media/src/app/modules/health/health.module.ts
  apps/api-tags/src/app/app.module.ts
  apps/api-tags/src/app/modules/health/health.controller.ts
  apps/api-tags/src/app/modules/health/health.module.ts
  apps/api-users/src/app/app.module.ts
  apps/api-users/src/app/modules/health/health.controller.ts
  apps/api-users/src/app/modules/health/health.module.ts
  apps/api-videos/src/app/app.module.ts
  apps/api-videos/src/app/modules/health/health.controller.ts
  apps/api-videos/src/app/modules/health/health.module.ts
  libs/nest/health/.eslintrc.json
  libs/nest/health/README.md
  libs/nest/health/jest.config.ts
  libs/nest/health/project.json
  libs/nest/health/src/index.ts
  libs/nest/health/src/lib/nest-health.controller.ts
  libs/nest/health/src/lib/nest-health.module.ts
  libs/nest/health/tsconfig.json
  libs/nest/health/tsconfig.lib.json
  libs/nest/health/tsconfig.spec.json
  tsconfig.base.json
Labels: effort: 2, priority: soon, type: feat

#1997 fix: close help scout dialog
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
Labels: type: fix, priority: soon, effort: 1

#2054 chore: videojs bump
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.spec.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.tsx
  libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
  package-lock.json
  package.json
Labels: priority: 2day, effort: 2, type: chore

#2060 fix: failing test strategy should not fail fast
  .github/workflows/main.yml
  jest.preset.js
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
  libs/journeys/ui/src/components/BlockRenderer/index.ts
  libs/journeys/ui/src/components/Card/index.ts
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/RadioQuestion/index.ts
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/components/Step/index.ts
Labels: type: fix, priority: now, effort: 1

#2055 fix: remove launchdarkly
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/pages/onboarding-form.tsx
  apps/journeys-admin/pages/publisher/[journeyId].tsx
  apps/journeys-admin/pages/publisher/index.tsx
  apps/journeys-admin/pages/reports/journeys.tsx
  apps/journeys-admin/pages/reports/visitors.tsx
  apps/journeys-admin/pages/reports/visitors/[visitorId].tsx
  apps/journeys-admin/pages/teams/new.tsx
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/pages/users/terms-and-conditions.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/ImageSource/ImageSource.spec.tsx
  apps/journeys-admin/src/components/Editor/Properties/Properties.spec.tsx
  apps/journeys-admin/src/components/Editor/Properties/Properties.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/AddJourneyButton/AddJourneyButton.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/AddJourneyButton/AddJourneyButton.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyFab/AddJourneyFab.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.stories.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.spec.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.spec.tsx
  apps/journeys-admin/src/components/TemplateList/TemplatesList.spec.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.stories.tsx
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.spec.tsx
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.ts
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.spec.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.stories.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.stories.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
  libs/shared/ui/src/components/FlagsProvider/FlagsProvider.spec.tsx
  libs/shared/ui/src/components/FlagsProvider/FlagsProvider.tsx
  libs/shared/ui/src/components/FlagsProvider/index.ts
  libs/shared/ui/src/libs/getLaunchDarklyClient/getLaunchDarklyClient.ts
  libs/shared/ui/src/libs/getLaunchDarklyClient/index.ts
  package-lock.json
  package.json
Labels: type: fix, priority: now, effort: 1

#2062 fix: reduce image size
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/assets/jesusFilm.jpg
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/assets/nua.jpg
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/assets/acceptance.jpg
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/assets/depression.jpg
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/assets/fearAnxiety.jpg
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/assets/forgiveness.jpg
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/assets/hope.jpg
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/assets/loneliness.jpg
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/assets/love.jpg
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/assets/security.jpg
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/assets/significance.jpg
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/acceptance.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/depression.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/fearAnxiety.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/forgiveness.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/hope.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/jesusFilm.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/loneliness.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/love.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/nua.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/security.png
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/assets/significance.png
Labels: type: fix, priority: now, effort: 1

#2002 feat: templates view video carousel
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPlayer.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPlayer/TemplateVideoPlayer.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPlayer/TemplateVideoPlayer.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPlayer/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPreview.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPreview.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/data.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 5, priority: soon, type: feat

#2057 fix: template view and gallery containers
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelBody/MainPanelBody.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelBody/MainPanelBody.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelHeader/MainPanelHeader.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.tsx
  apps/journeys-admin/src/components/NewPageWrapper/SidePanel/SidePanel.tsx
  apps/journeys-admin/src/components/NewPageWrapper/utils/usePageWrapperStyles/usePageWrapperStyles.ts
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
Labels: type: fix, effort: 3, priority: soon

#1877 fix: use newpagewrapper edit journeys
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/publisher/[journeyId].tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/ToggleOption/ToggleOption.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostForm.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostForm.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostSidePanel.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Drawer.tsx
  apps/journeys-admin/src/components/Editor/Drawer/index.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/JourneyEdit/JourneyEdit.tsx
  apps/journeys-admin/src/components/Editor/Properties/Properties.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.tsx
  apps/journeys-admin/src/components/NewPageWrapper/SidePanel/SidePanel.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/SidePanel/SidePanel.tsx
  apps/journeys-admin/src/components/NewPageWrapper/utils/usePageWrapperStyles/usePageWrapperStyles.ts
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/index.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/UserMenu.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/UserMenu.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/UserMenu.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserMenu/index.ts
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/index.ts
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
  apps/journeys-admin/src/components/PageWrapper/index.tsx
  apps/journeys-admin/src/components/PageWrapper/utils/getJourneyTooltip/getJourneyTooltip.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/utils/getJourneyTooltip/getJourneyTooltip.ts
  apps/journeys-admin/src/components/PageWrapper/utils/getJourneyTooltip/index.ts
  apps/journeys-admin/src/components/TemplateView/TemplateView.stories.tsx
Labels: priority: 2day, type: fix, effort: 3, type: refactor

#2064 fix: reduce embed weight
  .github/workflows/app-deploy.yml
  apps/docs-e2e/playwright.config.ts
  apps/journeys-admin-e2e/playwright.config.ts
  apps/journeys-admin/__generated__/GetDiscoveryJourneys.ts
  apps/journeys-admin/src/components/DiscoveryJourneys/DiscoveryJourneys.spec.tsx
  apps/journeys-admin/src/components/DiscoveryJourneys/DiscoveryJourneys.stories.tsx
  apps/journeys-admin/src/components/DiscoveryJourneys/DiscoveryJourneys.tsx
  apps/journeys-admin/src/components/DiscoveryJourneys/EmbedJourney/EmbedJourney.spec.tsx
  apps/journeys-admin/src/components/DiscoveryJourneys/EmbedJourney/EmbedJourney.tsx
  apps/journeys-admin/src/components/DiscoveryJourneys/data.ts
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
  apps/journeys-e2e/playwright.config.ts
  apps/journeys-e2e/src/e2e/journeys.spec.ts
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/can-we-trust-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/can-we-trust-chrome-mobile-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/jesus-history-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/jesus-history-chrome-mobile-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/who-was-jesus-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/who-was-jesus-chrome-mobile-linux.png
  apps/journeys/next.config.js
  apps/watch-e2e/playwright.config.ts
  apps/watch/next.config.js
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: now, effort: 1

#2063 fix: load menu in ssr
  apps/journeys-admin/setupTests.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/NewPageWrapper/PageWrapper.spec.tsx
  apps/journeys/setupTests.ts
  apps/watch/setupTests.tsx
  libs/journeys/ui/setupTests.ts
  libs/shared/ui/setupTests.ts
Labels: type: fix, priority: now, effort: 1

#2069 fix: beacon facade
  .github/workflows/app-deploy.yml
  apps/journeys-admin-e2e/playwright.config.ts
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts-snapshots/home-page-chrome-desktop-linux.png
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts-snapshots/home-page-chrome-mobile-linux.png
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts-snapshots/home-page-chromium-linux.png
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
Labels: type: fix, priority: now, effort: 1

#2070 fix: remove iframe from discover journeys
  apps/journeys-admin/src/components/DiscoveryJourneys/DiscoveryJourneys.tsx
  apps/journeys-admin/src/components/DiscoveryJourneys/EmbedJourney/EmbedJourney.spec.tsx
  apps/journeys-admin/src/components/DiscoveryJourneys/EmbedJourney/EmbedJourney.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.spec.tsx
Labels: type: fix, priority: now, effort: 1

#2071 fix: hide info button
  apps/journeys/src/components/Conductor/Conductor.tsx
Labels: priority: 2day, type: fix, effort: 1

#2061 fix: loading state template gallery
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
Labels: type: fix, priority: soon, effort: 1

#2058 fix: language selector embed
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/LanguagesFilterPopper/LanguagesFilterPopper.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/LanguagesFilterPopper/LanguagesFilterPopper.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/LanguagesFilterPopper/index.ts
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.spec.tsx
  libs/shared/ui/src/components/MultipleLanguageAutocomplete/MultipleLanguageAutocomplete.spec.tsx
  libs/shared/ui/src/components/MultipleLanguageAutocomplete/MultipleLanguageAutocomplete.tsx
Labels: effort: 2, type: fix, priority: soon

#2075 chore: update next
  package-lock.json
  package.json
Labels: priority: now, effort: 1, type: chore, dependencies, on stage

#2065 fix: felt needs improvements
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
Labels: effort: 2, type: fix, priority: soon

#2076 fix: load active journey list once on load
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
  apps/journeys-admin/src/components/Team/TeamProvider/TeamProvider.tsx
  apps/journeys-admin/src/libs/useAdminJourneysLazyQuery/index.ts
  apps/journeys-admin/src/libs/useAdminJourneysLazyQuery/useAdminJourneysLazyQuery.spec.tsx
  apps/journeys-admin/src/libs/useAdminJourneysLazyQuery/useAdminJourneysLazyQuery.ts
Labels: type: fix, priority: now, effort: 1

#2077 fix: load team invite list after active team load
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.stories.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageWrapper/TeamManageWrapper.spec.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageWrapper/TeamManageWrapper.tsx
  apps/journeys-admin/src/libs/useUserTeamsAndInvitesLazyQuery/index.ts
  apps/journeys-admin/src/libs/useUserTeamsAndInvitesLazyQuery/useUserTeamsAndInvitesLazyQuery.spec.tsx
  apps/journeys-admin/src/libs/useUserTeamsAndInvitesLazyQuery/useUserTeamsAndInvitesLazyQuery.ts
Labels: type: fix, priority: now, effort: 1, on stage

#2078 feat: add preconnect to api
  apps/journeys-admin/pages/_app.tsx
Labels: priority: now, type: feat, effort: 1

#2059 fix: enlarge template gallery carousel cards for larger breakpoints
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
Labels: type: fix, priority: soon, effort: 1

#2027 feat: step events frontend
  apps/api-journeys/src/app/modules/event/step/step.resolver.spec.ts
  apps/journeys-admin/__generated__/StepNextEventCreate.ts
  apps/journeys-admin/__generated__/StepPreviousEventCreate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/StepNextEventCreate.ts
  apps/journeys/__generated__/StepPreviousEventCreate.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.spec.tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
  apps/watch/__generated__/StepNextEventCreate.ts
  apps/watch/__generated__/StepPreviousEventCreate.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Card/__generated__/StepNextEventCreate.ts
  libs/journeys/ui/src/components/Card/__generated__/StepPreviousEventCreate.ts
  libs/journeys/ui/src/libs/block/block.spec.ts
  libs/journeys/ui/src/libs/block/block.ts
  libs/journeys/ui/src/libs/block/index.ts
Labels: effort: 3, priority: soon, type: feat

#2079 fix: add crossorigin to preload
  apps/journeys-admin/pages/_app.tsx
Labels: type: fix, priority: now, effort: 1

#2080 feat: add batching to router
  .devcontainer/post-create-command.sh
  apps/api-gateway/Dockerfile
  apps/api-gateway/router.prod.yaml
  apps/api-gateway/router.yaml
  apps/api-gateway/routerSchema.json
Labels: priority: now, type: feat, effort: 1, dependencies, on stage

#2082 fix: parallelize invite accept
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/pages/users/terms-and-conditions.tsx
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.spec.tsx
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.ts
Labels: type: fix, priority: now, effort: 1

#2083 fix: disable prefetch until pages can be sped up
  apps/journeys-admin/src/components/AccessDenied/AccessDenied.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/ReportMenuItem/ReportMenuItem.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.tsx
  apps/journeys-admin/src/components/MediaListItem/MediaListItem.tsx
  apps/journeys-admin/src/components/MultipleSummaryReport/MultipleSummaryReport.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/OnboardingPanelContent.tsx
  apps/journeys-admin/src/components/PageWrapper/MainPanelHeader/MainPanelHeader.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.tsx
  apps/journeys-admin/src/components/PublisherInvite/PublisherInvite.tsx
  apps/journeys-admin/src/components/ReportsNavigation/NavigationButton/NavigationButton.tsx
  apps/journeys-admin/src/components/TemplateCard/TemplateCard.tsx
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateEditButton/TemplateEditButton.tsx
Labels: type: fix, priority: now, effort: 1

#2084 fix: add new loading state
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
Labels: type: fix, priority: soon, effort: 1

#2085 feat: add use last active team id to api
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: effort: 2, priority: now, type: feat, on stage

#2087 fix: reduce cls
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.tsx
Labels: type: fix, priority: soon, effort: 1

#2053 fix: simplify tags
  apps/api-tags/db/seed.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#2090 chore: terraform cleanup
  apps/api-gateway/infrastructure/variables.tf
  apps/api-journeys/infrastructure/variables.tf
  apps/api-languages/infrastructure/variables.tf
  apps/api-media/infrastructure/variables.tf
  apps/api-tags/infrastructure/variables.tf
  apps/api-users/infrastructure/variables.tf
  apps/api-videos/infrastructure/variables.tf
  infrastructure/modules/aws/aurora/main.tf
  infrastructure/modules/aws/datadog/main.tf
  infrastructure/modules/aws/ecs-task/data.tf
  infrastructure/modules/aws/ecs-task/main.tf
  infrastructure/modules/aws/main.tf
Labels: priority: soon, effort: 1, type: chore

#2091 feat: cors ecs next
  apps/api-gateway/router.prod.yaml
Labels: priority: now, type: feat, effort: 1, on stage

#2093 fix: felt needs and collection on change event
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.tsx
Labels: type: fix, priority: soon, effort: 1

#2094 fix: remove description menu item
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#2095 fix: align carousels
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGalleryCarousel/TemplateGalleryCarousel.tsx
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
Labels: type: fix, priority: soon, effort: 1

#2088 fix: video shows as muted even when theres sound
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
Labels: type: fix, priority: soon, effort: 1

#2074 fix: loading template view
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TemplateTags.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/SocialImage/SocialImage.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.tsx
Labels: type: fix, effort: 3, priority: soon
