Repository JesusFilm/core, pull requests merged in 2023-06, with the labels that each got.

#1598 fix: nextstep action greyed out
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/data.ts
Labels: type: fix, effort: 3, priority: now

#1581 feat: mailto link action
  apps/journeys-admin/__generated__/EmailActionUpdate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/EmailAction/EmailAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/EmailAction/EmailAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/EmailAction/EmailAction.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/EmailAction/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/LinkAction/LinkAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/data.ts
  apps/journeys-admin/src/libs/apolloClient/cache.ts
  apps/journeys/src/libs/apolloClient/cache/cache.ts
  libs/journeys/ui/src/libs/action/action.spec.ts
  libs/journeys/ui/src/libs/action/action.ts
Labels: effort: 13, priority: soon, type: feat

#1582 fix: journeys card layout
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.tsx
  apps/journeys/pages/embed/[journeySlug].tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
  apps/journeys/src/components/EmbeddedPreview/VideoWrapper/VideoWrapper.tsx
  apps/journeys/src/components/Footer/Footer.spec.tsx
  apps/journeys/src/components/Footer/Footer.tsx
  apps/journeys/src/components/Footer/index.ts
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/index.ts
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.spec.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContentOverlay/ContentOverlay.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContentOverlay/index.ts
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.spec.tsx
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.tsx
  libs/journeys/ui/src/components/Card/OverlayContent/OverlayContent.tsx
  libs/journeys/ui/src/components/Card/OverlayContent/index.ts
  libs/journeys/ui/src/components/Card/index.ts
  libs/journeys/ui/src/components/StepHeader/StepHeader.spec.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
  libs/journeys/ui/src/components/StepHeader/index.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/libs/getStepTheme/getStepTheme.spec.ts
  libs/journeys/ui/src/libs/getStepTheme/getStepTheme.ts
  libs/journeys/ui/src/libs/getStepTheme/index.ts
  libs/locales/en/apps-journeys-admin_old.json
  libs/locales/en/apps-journeys.json
  libs/locales/en/libs-journeys-ui.json
  libs/shared/ui/src/components/NextImage/NextImage.tsx
  libs/shared/ui/src/libs/themes/base/tokens/colors.ts
  libs/shared/ui/src/libs/themes/base/tokens/components.ts
Labels: effort: 5, type: fix, priority: soon

#1488 feat: api users postgres
  apps/api-tags/db/Dockerfile
  apps/api-users/.prisma-generate.env
  apps/api-users/Dockerfile
  apps/api-users/db/Dockerfile
  apps/api-users/db/migrations/20221109011457_/migration.sql
  apps/api-users/db/migrations/20230531192512_20230531192505/migration.sql
  apps/api-users/db/migrations/migration_lock.toml
  apps/api-users/db/schema.prisma
  apps/api-users/db/seed.ts
  apps/api-users/index.ts
  apps/api-users/infrastructure/locals.tf
  apps/api-users/infrastructure/main.tf
  apps/api-users/infrastructure/variables.tf
  apps/api-users/project.json
  apps/api-users/src/app/.gitkeep
  apps/api-users/src/app/lib/.gitkeep
  apps/api-users/src/app/lib/prisma.service.ts
  apps/api-users/src/app/modules/user/user.module.ts
  apps/api-users/src/app/modules/user/user.resolver.spec.ts
  apps/api-users/src/app/modules/user/user.resolver.ts
  apps/api-users/src/app/modules/user/user.service.spec.ts
  apps/api-users/src/app/modules/user/user.service.ts
  apps/api-users/src/main.ts
  apps/arangodb-bigquery-etl/bqexport.sh
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/main.tf
  infrastructure/modules/aws/aurora/main.tf
  infrastructure/modules/aws/main.tf
Labels: effort: 13, priority: soon, type: feat, on stage

#1575 fix: add real children
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
Labels: type: fix, priority: soon, effort: 1

#1597 fix: noindex nofollow journeys
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/pages/embed/[journeySlug].tsx
  apps/journeys/pages/index.tsx
Labels: type: fix, priority: now, effort: 1

#1602 fix: remove edit icon from textfield
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.tsx
Labels: type: fix, priority: soon, effort: 1

#1609 fix: remove network mode line
  .devcontainer/docker-compose.yml
Labels: type: fix, priority: now, effort: 1

#1608 refactor: migrate user team to postgres
  apps/api-journeys/db/migrations/20230607050721_20230607050720/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/db/seed.ts
  apps/api-journeys/db/seeds/jfpTeam.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/modules/action/action.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/emailAction/emailAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/card/card.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/gridContainer/gridContainer.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/gridItem/gridItem.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/icon/icon.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/image/image.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/typography/typography.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/videoTrigger/videoTrigger.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.module.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.resolver.spec.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.resolver.ts
  apps/api-journeys/src/app/modules/member/member.module.ts
  apps/api-journeys/src/app/modules/member/member.service.spec.ts
  apps/api-journeys/src/app/modules/member/member.service.ts
  apps/api-journeys/src/app/modules/team/team.module.ts
  apps/api-journeys/src/app/modules/team/team.service.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.module.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.service.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.service.ts
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.ts
Labels: effort: 3, priority: now, type: refactor, on stage

#1611 docs: update microservices setup
  apps/docs/docs/02-getting-started/03-microservice-databases.mdx
Labels: type: docs, priority: soon, effort: 1

#1606 feat: basic step footer
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.stories.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.stories.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.stories.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
  libs/journeys/ui/src/components/StepFooter/index.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: effort: 3, priority: soon, type: feat

#1578 feat: text field form
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/EmailAction/EmailAction.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/LinkAction/LinkAction.tsx
  apps/journeys-admin/src/components/TextFieldForm/TextFieldForm.spec.tsx
  apps/journeys-admin/src/components/TextFieldForm/TextFieldForm.stories.tsx
  apps/journeys-admin/src/components/TextFieldForm/TextFieldForm.tsx
  apps/journeys-admin/src/components/TextFieldForm/index.ts
Labels: priority: soon, type: feat, effort: 1

#1603 feat: prisma update
  apps/api-journeys/Dockerfile
  apps/api-journeys/db/Dockerfile
  apps/api-tags/Dockerfile
  apps/api-tags/db/Dockerfile
  apps/api-users/Dockerfile
  apps/api-users/db/Dockerfile
  package-lock.json
  package.json
Labels: priority: 2day, type: feat, effort: 1, on stage

#1605 feat: chat buttons field
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20230612220844_20230612220842/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/lib/roleGuard/roleGuard.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/chatButton/chatButton.graphql
  apps/api-journeys/src/app/modules/chatButton/chatButton.resolver.spec.ts
  apps/api-journeys/src/app/modules/chatButton/chatButton.resolver.ts
  apps/api-journeys/src/app/modules/journey/journey.module.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.service.spec.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#1604 feat: hosted by create host model backend
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20230612205756_20230612205755/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/modules/host/host.graphql
  apps/api-journeys/src/app/modules/host/host.module.ts
  apps/api-journeys/src/app/modules/host/host.resolver.spec.ts
  apps/api-journeys/src/app/modules/host/host.resolver.ts
Labels: effort: 13, priority: soon, type: feat

#1613 feat: step footer selection
  apps/journeys-admin/src/components/DuplicateBlock/DuplicateBlock.spec.tsx
  apps/journeys-admin/src/components/DuplicateBlock/DuplicateBlock.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.tsx
  apps/journeys-admin/src/components/NewPageWrapper/MainPanelBody/MainPanelBody.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: effort: 3, priority: soon, type: feat

#1620 fix: remove trailing space from affected
  .github/workflows/app-deploy.yml
Labels: type: fix, priority: now, effort: 1

#1621 feat: chat button icons
  libs/shared/ui/src/components/icons/Facebook.tsx
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/Instagram.tsx
  libs/shared/ui/src/components/icons/Line.tsx
  libs/shared/ui/src/components/icons/Skype.tsx
  libs/shared/ui/src/components/icons/Snapchat.tsx
  libs/shared/ui/src/components/icons/Telegram.tsx
  libs/shared/ui/src/components/icons/Tiktok.tsx
  libs/shared/ui/src/components/icons/Viber.tsx
  libs/shared/ui/src/components/icons/Vk.tsx
  libs/shared/ui/src/components/icons/WhatsApp.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: effort: 3, priority: now, type: feat

#1610 feat: create hostid prop in journeys backend
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: effort: 13, priority: soon, type: feat

#1618 feat: prisma update
  apps/api-journeys/Dockerfile
  apps/api-journeys/db/Dockerfile
  apps/api-tags/Dockerfile
  apps/api-tags/db/Dockerfile
  apps/api-users/Dockerfile
  apps/api-users/db/Dockerfile
  package-lock.json
  package.json
Labels: priority: soon, type: feat, effort: 1

#1623 fix: prettier vscode
  .vscode/settings.json
Labels: type: fix, priority: now, effort: 1

#1624 fix: prisma shutdownhooks
  apps/api-journeys/src/main.ts
Labels: type: fix, priority: now, effort: 1

#1625 feat: prisma studio
  apps/api-journeys/project.json
  apps/api-tags/project.json
  apps/api-users/project.json
Labels: priority: 2day, type: feat, effort: 1

#1622 feat: chat
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.tsx
Labels: priority: soon, type: feat, effort: 1

#1627 fix: adjust host model avatar props deprecation pr
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20230615223656_20230615223654/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/host/host.graphql
  apps/api-journeys/src/app/modules/host/host.resolver.spec.ts
Labels: priority: 2day, effort: 5, type: fix

#1628 fix: adjust host model remove deprecation directives and props
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20230615233217_20230615233215/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/host/host.graphql
  apps/api-journeys/src/app/modules/host/host.resolver.spec.ts
Labels: priority: 2day, effort: 5, type: fix

#1629 fix: add host types in apps
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/GetTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/src/components/Editor/ActionDetails/data.ts
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.stories.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/data.ts
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch/__generated__/JourneyFields.ts
  libs/journeys/ui/src/components/StepFooter/StepFooter.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.stories.tsx
  libs/journeys/ui/src/libs/JourneyProvider/JourneyProvider.spec.tsx
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/journeyFields.tsx
  libs/journeys/ui/src/libs/rtl/rtl.spec.tsx
Labels: priority: 2day, effort: 2, type: fix

#1626 feat: add new teams endpoints
  apps/api-gateway/schema.graphql
  apps/api-journeys/project.json
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/lib/casl/__generated__/prismaSubjects.ts
  apps/api-journeys/src/app/lib/casl/caslFactory.ts
  apps/api-journeys/src/app/lib/casl/caslPrisma.ts
  apps/api-journeys/src/app/lib/casl/caslPrismaGenerator.ts
  apps/api-journeys/src/app/modules/team/team.graphql
  apps/api-journeys/src/app/modules/team/team.module.ts
  apps/api-journeys/src/app/modules/team/team.resolver.spec.ts
  apps/api-journeys/src/app/modules/team/team.resolver.ts
  libs/nest/common/src/lib/CaslAuthModule/caslAuth.module.ts
  libs/nest/common/src/lib/CaslAuthModule/caslFactory.ts
  libs/nest/common/src/lib/CaslAuthModule/caslGuard.ts
  libs/nest/common/src/lib/CaslAuthModule/decorators/caslAbility.ts
  libs/nest/common/src/lib/CaslAuthModule/decorators/caslAccessible.ts
  libs/nest/common/src/lib/CaslAuthModule/decorators/caslPolicy.ts
  libs/nest/common/src/lib/CaslAuthModule/index.ts
  libs/nest/gqlAuthGuard/src/lib/GqlAuthGuard/GqlAuthGuard.ts
  package-lock.json
  package.json
Labels: priority: now, effort: 13, type: feat, on stage

#1619 feat: chat buttons
  apps/journeys-admin/__generated__/ChatButtonEventCreate.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/GetTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/ActionDetails/data.ts
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.stories.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyView.spec.tsx
  apps/journeys-admin/src/components/JourneyView/data.ts
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys/__generated__/ChatButtonEventCreate.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/watch-admin/__generated__/ChatButtonEventCreate.ts
  apps/watch-admin/__generated__/JourneyFields.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/ChatButtonEventCreate.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.spec.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.stories.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/__generated__/ChatButtonEventCreate.ts
  libs/journeys/ui/src/components/StepFooter/ChatButtons/index.ts
  libs/journeys/ui/src/components/StepFooter/HostTitleLocation/HostTitleLocation.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.stories.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
  libs/journeys/ui/src/libs/JourneyProvider/JourneyProvider.spec.tsx
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/journeyFields.tsx
  libs/journeys/ui/src/libs/rtl/rtl.spec.tsx
Labels: effort: 3, priority: soon, type: feat

#1615 feat: avatar component
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.spec.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.stories.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/index.tsx
Labels: effort: 13, priority: soon, type: feat

#1634 feat: attribute button hosted by
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: soon, type: feat

#1638 feat: add new user teams endpoints
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/lib/casl/caslFactory.ts
  apps/api-journeys/src/app/modules/userTeam/userTeam.graphql
  apps/api-journeys/src/app/modules/userTeam/userTeam.module.ts
  apps/api-journeys/src/app/modules/userTeam/userTeam.resolver.spec.ts
  apps/api-journeys/src/app/modules/userTeam/userTeam.resolver.ts
Labels: effort: 3, priority: now, type: feat

#1633 fix: remove-add-video-by-url
  apps/journeys-admin/__generated__/CreateCloudflareVideoUploadByUrl.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByUrl/AddByUrl.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByUrl/AddByUrl.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByUrl/index.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/VideoFromCloudflare.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/VideoFromCloudflare.tsx
Labels: type: fix, priority: soon, effort: 1

#1632 feat: add duration and validate end at
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/video/video.graphql
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
  apps/api-media/src/app/modules/cloudflare/video/video.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.spec.tsx
Labels: effort: 2, type: fix, priority: soon

#1635 fix: chat properties and avatar
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.spec.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#1631 feat: host details in step footer
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.tsx
  libs/journeys/ui/src/components/StepFooter/HostTitleLocation/HostTitleLocation.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.stories.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
Labels: priority: 2day, effort: 3, type: feat

#1642 fix: pin tflint
  .devcontainer/devcontainer.json
Labels: priority: 2day, type: fix, effort: 1, on stage

#1641 fix: custom chat platform
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20230620213244_20230620213242/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/chatButton/chatButton.graphql
  apps/api-journeys/src/app/modules/chatButton/chatButton.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/button/button.graphql
  apps/api-journeys/src/app/modules/event/button/button.resolver.spec.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/messagePlatformToLabel/messagePlatformToLabel.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/messagePlatformToLabel/messagePlatformToLabel.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.tsx
Labels: effort: 2, type: fix, priority: now, on stage

#1614 feat: chat widget admin
  apps/journeys-admin/__generated__/JourneyChatButtonCreate.ts
  apps/journeys-admin/__generated__/JourneyChatButtonRemove.ts
  apps/journeys-admin/__generated__/JourneyChatButtonUpdate.ts
  apps/journeys-admin/__generated__/NewChatButton.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/Chat.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/Chat.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/Chat.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/ChatOption.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/ChatOption.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/ChatOption.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Details/Details.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Details/Details.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Details/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Summary/Summary.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Summary/Summary.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Summary/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: effort: 5, priority: soon, type: feat

#1639 refactor: move affected logic into typescript
  .github/workflows/app-deploy.yml
  tools/scripts/affected-frontend-apps.ts
Labels: priority: now, effort: 1, type: refactor

#1637 fix: update host delete mutation
  apps/api-journeys/src/app/lib/casl/caslFactory.ts
  apps/api-journeys/src/app/modules/host/host.module.ts
  apps/api-journeys/src/app/modules/host/host.resolver.spec.ts
  apps/api-journeys/src/app/modules/host/host.resolver.ts
  apps/api-journeys/src/app/modules/journey/journey.service.ts
Labels: effort: 8, type: fix, priority: soon, on stage

#1640 feat: add file error handling to video upload
  apps/api-media/src/app/modules/cloudflare/video/video.service.ts
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/AddByFile/testFile.png
Labels: effort: 3, priority: soon, type: feat

#1647 fix: text form field errors
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/EmailAction/EmailAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/EmailAction/EmailAction.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/LinkAction/LinkAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/LinkAction/LinkAction.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Details/Details.tsx
  apps/journeys-admin/src/components/TextFieldForm/TextFieldForm.spec.tsx
  apps/journeys-admin/src/components/TextFieldForm/TextFieldForm.stories.tsx
  apps/journeys-admin/src/components/TextFieldForm/TextFieldForm.tsx
Labels: priority: 2day, type: fix, effort: 3

#1646 fix: select footer issues
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: type: fix, priority: soon, effort: 1

#1652 fix: chat behaviour under spam clicking
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Summary/Summary.tsx
Labels: type: fix, priority: soon, effort: 1

#1651 refactor: controlled accordion
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/ChatOption.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/ChatOption.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Summary/Summary.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Summary/Summary.tsx
Labels: priority: soon, effort: 1, type: refactor

#1648 feat: host avatar and host location edit components
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostAvatarsButton/HostAvatarsButton.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostAvatarsButton/HostAvatarsButton.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostAvatarsButton/HostAvatarsButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostAvatarsButton/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostLocationFieldForm/HostLocationFieldForm.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostLocationFieldForm/HostLocationFieldForm.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostLocationFieldForm/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostTitleFieldForm/HostTitleFieldForm.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostTitleFieldForm/HostTitleFieldForm.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostTitleFieldForm/index.ts
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx
  apps/journeys-admin/src/components/TextFieldForm/TextFieldForm.tsx
Labels: priority: 2day, effort: 3, type: feat

#1657 refactor: footer flag
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/Chat.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/apps-journeys-admin_old.json
Labels: priority: soon, effort: 1, type: refactor

#1656 feat: add mcid and langid and seconds to analytics
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
Labels: priority: soon, type: feat, effort: 1

#1662 fix: tidy up journeys home page
  apps/journeys/pages/index.tsx
  apps/journeys/public/logo.svg
  libs/locales/en/journeys.json
Labels: type: fix, priority: now, effort: 1, on stage

#1664 fix: update userTeams input variable type
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/userTeam/userTeam.graphql
Labels: type: fix, priority: now, effort: 1, on stage

#1665 fix: api-videos existing slugs
  apps/api-videos/db/seed.ts
  apps/api-videos/src/libs/arclight/arclight.spec.ts
  apps/api-videos/src/libs/arclight/arclight.ts
  apps/api-videos/src/libs/slugify/slugify.spec.ts
  apps/api-videos/src/libs/slugify/slugify.ts
Labels: effort: 2, type: fix, priority: now

#1661 feat: videojs update
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/CloudflareDetails/CloudflareDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromCloudflare/CloudflareDetails/CloudflareDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/YouTubeDetails/YouTubeDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/YouTubeDetails/YouTubeDetails.tsx
  apps/journeys/src/components/EmbeddedPreview/VideoWrapper/VideoWrapper.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.spec.tsx
  apps/watch/src/components/SubtitleDialog/SubtitleDialog.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoPlayer.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.spec.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.tsx
  libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
  package-lock.json
  package.json
Labels: effort: 2, priority: soon, type: feat, on stage
