Repository JesusFilm/core, pull requests merged in 2023-08, with the labels that each got.

#1756 fix: update commit hash to latest good commit to main
  .github/workflows/main.yml
Labels: type: fix, priority: now, effort: 1

#1753 fix: updated embedded seed
  apps/api-journeys/db/seed.ts
  apps/api-journeys/db/seeds/discoveryAdminCenter.ts
  apps/api-journeys/db/seeds/discoveryAdminLeft.ts
  apps/api-journeys/db/seeds/discoveryAdminRight.ts
  apps/api-journeys/db/seeds/feedback.ts
  apps/api-journeys/db/seeds/howTo.ts
  apps/api-journeys/db/seeds/vision.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1758 fix: revert dynamic loading of video block
  .github/workflows/main.yml
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
Labels: priority: 2day, type: fix, effort: 1

#1759 fix: visitor apis teams
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.graphql
  apps/api-journeys/src/app/modules/visitor/visitor.graphql
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.resolver.ts
Labels: type: fix, effort: 3, priority: now

#1757 feat: teams select onboarding popover
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.spec.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.stories.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, type: feat, effort: 1

#1761 fix: ensure pr title is shorter than 100 characters otherwise fail to merge the pr
  dangerfile.ts
Labels: type: fix, priority: now, effort: 1

#1653 feat: host side panel
  apps/journeys-admin/__generated__/DeleteHost.ts
  apps/journeys-admin/__generated__/Hosts.ts
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostAvatarsButton/HostAvatarsButton.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostAvatarsButton/HostAvatarsButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostForm.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostForm.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostTitleFieldForm/HostTitleFieldForm.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostTitleFieldForm/HostTitleFieldForm.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostList/HostList.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostList/HostList.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostList/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostListItem/HostListItem.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostSidePanel.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostSidePanel.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/index.ts
  apps/journeys-admin/src/components/NewPageWrapper/SidePanel/SidePanel.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.tsx
  libs/journeys/ui/src/components/StepFooter/HostTitleLocation/HostTitleLocation.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.stories.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/icons/AlertCircle.tsx
  libs/shared/ui/src/components/icons/InformationCircleContained.tsx
  libs/shared/ui/src/components/icons/UserProfile3.tsx
  libs/shared/ui/src/components/icons/UserProfileAdd.tsx
  libs/shared/ui/src/components/icons/UserProfileCircle.tsx
  libs/shared/ui/src/components/icons/UsersProfiles2.tsx
Labels: effort: 3, priority: soon, type: feat

#1722 fix: update team id prop for hosts and visitors
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/src/components/VisitorsList/VisitorList.spec.tsx
  apps/journeys-admin/src/components/VisitorsList/VisitorsList.tsx
Labels: effort: 5, type: fix, priority: soon

#1747 feat: visitors teams legal information
  libs/journeys/ui/src/components/StepHeader/StepHeader.spec.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
  libs/locales/en/libs-journeys-ui.json
Labels: effort: 3, priority: soon, type: feat

#1755 feat: add last team active
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20230731213625_20230731213623/migration.sql
  apps/api-journeys/db/migrations/20230731214906_20230731214905/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.graphql
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.module.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.spec.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.ts
Labels: priority: now, type: feat, effort: 1, on stage

#1728 feat: remove old vpn keys
  .github/vpn/main.ovpn
  .github/vpn/stage.ovpn
Labels: priority: 2day, type: feat, effort: 1

#1764 fix: reorder optional params to end
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.graphql
Labels: type: fix, priority: now, effort: 1

#1766 fix: card list height
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
  apps/journeys-admin/src/components/CardPreview/NavigationCard/NavigationCard.spec.tsx
  apps/journeys-admin/src/components/CardPreview/NavigationCard/NavigationCard.stories.tsx
  apps/journeys-admin/src/components/CardPreview/NavigationCard/NavigationCard.tsx
  apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: now, effort: 1

#1763 feat: show last team active
  apps/journeys-admin/__generated__/GetLastActiveTeamIdAndTeams.ts
  apps/journeys-admin/__generated__/GetTeams.ts
  apps/journeys-admin/__generated__/UpdateLastActiveTeamId.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/AddJourneyButton/AddJourneyButton.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.spec.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyViewFab/JourneyViewFab.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/OnboardingPanelContent/OnboardingPanelContent.spec.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamDialog/CopyToTeamDialog.spec.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamDialog/CopyToTeamDialog.stories.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.spec.tsx
  apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamCreateForm/TeamCreateForm.spec.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageDialog.stories.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageWrapper/TeamManageWrapper.spec.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.spec.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.stories.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.spec.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.stories.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
  apps/journeys-admin/src/components/Team/TeamProvider/TeamProvider.spec.tsx
  apps/journeys-admin/src/components/Team/TeamProvider/TeamProvider.tsx
  apps/journeys-admin/src/components/Team/TeamProvider/index.ts
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.spec.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.stories.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.tsx
  apps/journeys-admin/src/components/Team/TeamUpdateDialog/TeamUpdateDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamUpdateDialog/TeamUpdateDialog.stories.tsx
  apps/journeys-admin/src/components/Team/UserTeamInviteForm/UserTeamInviteForm.spec.tsx
  apps/journeys-admin/src/components/VisitorsList/VisitorList.spec.tsx
Labels: effort: 3, priority: now, type: feat

#1765 fix: access dialog show
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserList.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/UserListItem.tsx
Labels: effort: 5, type: fix, priority: soon

#1767 fix: disable email field
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageWrapper/TeamManageWrapper.tsx
  apps/journeys-admin/src/components/Team/UserTeamInviteForm/UserTeamInviteForm.spec.tsx
  apps/journeys-admin/src/components/Team/UserTeamInviteForm/UserTeamInviteForm.stories.tsx
  apps/journeys-admin/src/components/Team/UserTeamInviteForm/UserTeamInviteForm.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, effort: 3, priority: soon

#1769 fix: open permissions dialog on team create
  apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.stories.tsx
  apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.tsx
Labels: type: fix, effort: 3, priority: now

#1768 fix: nextstep action
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateAction/NavigateAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateAction/NavigateAction.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/utils/getNextStep/getNextStep.spec.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/utils/getNextStep/getNextStep.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/utils/getNextStep/index.ts
Labels: type: fix, priority: soon, effort: 1

#1772 fix: discovery admin migrations
  apps/api-journeys/db/seed.ts
  apps/api-journeys/db/seeds/discoveryAdminCenter.ts
  apps/api-journeys/db/seeds/discoveryAdminLeft.ts
  apps/api-journeys/db/seeds/discoveryAdminRight.ts
Labels: type: fix, priority: now, effort: 1

#1770 fix: allow duplicate when teams flag is false
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyViewFab/JourneyViewFab.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyViewFab/JourneyViewFab.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyViewFab/JourneyViewFab.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
Labels: type: fix, priority: now, effort: 1

#1771 fix: add invites accept in terms
  apps/journeys-admin/pages/users/terms-and-conditions.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.tsx
Labels: type: fix, priority: now, effort: 1

#1773 feat: remove nx-plus
  apps/docs/project.json
  package-lock.json
  package.json
Labels: priority: 2day, type: feat, effort: 1

#1775 fix: video controls blocked by navigation button
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
Labels: type: fix, priority: now, effort: 1

#1778 fix: add user team to team api
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/team/team.graphql
  apps/api-journeys/src/app/modules/team/team.resolver.spec.ts
  apps/api-journeys/src/app/modules/team/team.resolver.ts
Labels: priority: now, type: feat, effort: 1, on stage

#1600 feat: aspect ratio display changes
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: effort: 3, priority: soon, type: feat

#1780 fix: custom error page
  apps/journeys/pages/500.tsx
Labels: type: fix, priority: soon, effort: 1

#1787 fix: publisher can edit template field
  apps/api-journeys/src/app/modules/journey/journey.acl.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.acl.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1784 fix: remove old api teams
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/host/host.acl.spec.ts
  apps/api-journeys/src/app/modules/host/host.acl.ts
  apps/api-journeys/src/app/modules/journey/journey.acl.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.acl.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.graphql
  apps/journeys-admin/__generated__/CreateJourney.ts
  apps/journeys-admin/__generated__/JourneyDuplicate.ts
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyViewFab/JourneyViewFab.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
  apps/journeys-admin/src/libs/useJourneyCreate/useJourneyCreate.ts
  apps/journeys-admin/src/libs/useJourneyDuplicateMutation/useJourneyDuplicateMutation.ts
Labels: type: fix, priority: now, effort: 1

#1785 chore: remove teams flag todos
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyViewFab/JourneyViewFab.spec.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyViewFab/JourneyViewFab.stories.tsx
  apps/journeys-admin/src/components/JourneyView/JourneyViewFab/JourneyViewFab.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
Labels: priority: soon, effort: 1, type: chore

#1791 fix: stop logging health checks
  apps/api-media/src/app/app.module.ts
  apps/api-videos/src/app/app.module.ts
  libs/nest/common/src/lib/tracer/tracer.ts
Labels: type: fix, priority: now, effort: 1

#1782 fix: properly handle journeys 404
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetJourneyWithUserJourneys.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/GetTemplate.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/pages/embed/[journeySlug].tsx
Labels: type: fix, priority: now, effort: 1

#1798 fix: update icons
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageDialog.stories.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/UserTeamDeleteMenuItem/UserTeamDeleteMenuItem.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/UserTeamInviteRemoveMenuItem/UserTeamInviteRemoveMenuItem.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/UserTeamList/UserTeamListItem/UserTeamListItem.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.tsx
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/UsersProfiles3.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: type: fix, priority: soon, effort: 1

#1802 fix: allow user to be upserted
  apps/api-users/src/app/modules/user/user.resolver.spec.ts
  apps/api-users/src/app/modules/user/user.resolver.ts
Labels: type: fix, priority: now, effort: 1

#1804 fix: team select to match design
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.tsx
Labels: type: fix, priority: now, effort: 1

#1789 feat: teams avatars
  apps/journeys-admin/__generated__/GetLastActiveTeamIdAndTeams.ts
  apps/journeys-admin/__generated__/TeamCreate.ts
  apps/journeys-admin/src/components/Avatar/Avatar.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.spec.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamDialog/CopyToTeamDialog.spec.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamDialog/CopyToTeamDialog.stories.tsx
  apps/journeys-admin/src/components/Team/TeamAvatars/TeamAvatars.spec.tsx
  apps/journeys-admin/src/components/Team/TeamAvatars/TeamAvatars.stories.tsx
  apps/journeys-admin/src/components/Team/TeamAvatars/TeamAvatars.tsx
  apps/journeys-admin/src/components/Team/TeamAvatars/index.ts
  apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.stories.tsx
  apps/journeys-admin/src/components/Team/TeamCreateForm/TeamCreateForm.spec.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageWrapper/TeamManageWrapper.spec.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.spec.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.stories.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.spec.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.stories.tsx
  apps/journeys-admin/src/components/Team/TeamProvider/TeamProvider.spec.tsx
  apps/journeys-admin/src/components/Team/TeamProvider/TeamProvider.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.spec.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.stories.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.tsx
  apps/journeys-admin/src/components/Team/TeamUpdateDialog/TeamUpdateDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamUpdateDialog/TeamUpdateDialog.stories.tsx
  apps/journeys-admin/src/components/Team/UserTeamInviteForm/UserTeamInviteForm.spec.tsx
  apps/journeys-admin/src/components/VisitorsList/VisitorList.spec.tsx
  apps/journeys-admin/src/libs/useTeamCreateMutation/useTeamCreateMutation.tsx
Labels: priority: 2day, effort: 8, type: feat

#1801 fix: use only title when duplicating from template
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: effort: 2, type: fix, priority: soon, on stage

#1808 docs: update seed command
  apps/docs/docs/02-getting-started/03-microservice-databases.mdx
Labels: priority: now, type: docs, effort: 1

#1813 ci: upload sourcemaps to datadog
  .github/workflows/app-deploy.yml
  apps/journeys-admin/project.json
  apps/journeys/project.json
  apps/watch/project.json
Labels: priority: now, effort: 1, type: ci

#1815 ci: upload sourcemaps to datadog in prod
  .github/workflows/app-deploy.yml
Labels: type: fix, priority: now, effort: 1

#1809 fix: reduce line height in step header and remove privacy policy
  libs/journeys/ui/src/components/StepHeader/StepHeader.spec.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
  libs/locales/en/libs-journeys-ui.json
Labels: type: fix, priority: soon, effort: 1

#1814 feat: disable duplicate for video block
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
Labels: priority: soon, type: feat, effort: 1

#1715 feat: background color iphone
  apps/journeys-admin/src/components/DiscoveryJourneys/EmbedJourney/EmbedJourney.spec.tsx
  apps/journeys-admin/src/components/DiscoveryJourneys/EmbedJourney/EmbedJourney.tsx
  apps/journeys/pages/_app.tsx
  apps/journeys/pages/_document.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.tsx
  libs/journeys/ui/src/components/Card/OverlayContent/OverlayContent.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
Labels: effort: 3, priority: soon, type: feat

#1807 fix: add loader icons
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamDialog/CopyToTeamDialog.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.tsx
  libs/shared/ui/src/components/Dialog/Dialog.spec.tsx
  libs/shared/ui/src/components/Dialog/Dialog.stories.tsx
  libs/shared/ui/src/components/Dialog/Dialog.tsx
Labels: type: fix, priority: soon, effort: 1

#1818 fix: refine video progress display
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
Labels: priority: 2day, type: fix, effort: 1

#1816 feat: always display preview icon
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
Labels: effort: 5, priority: now, type: feat

#1811 fix: disable edit host in side panel if not in journey team
  apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.spec.tsx
  apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostSidePanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostSidePanel.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostSidePanel.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: 2day, type: fix, effort: 3

#1824 fix: preview icon broken story
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
Labels: effort: 2, type: fix, priority: now

#1827 fix: use higher quality poster image
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: type: fix, priority: soon, effort: 1

#1828 fix: variant languageid specificity
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
  apps/watch/src/libs/videoContentFields.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1830 fix: journeys variant language
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
Labels: type: fix, effort: 3, priority: now, on stage

#1806 fix: enable skip button teams onboarding
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
Labels: type: fix, priority: soon, effort: 1

#1829 fix: make journeys published by default
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: priority: 2day, effort: 2, type: fix, on stage

#1792 fix: custom url use text field form
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomUrl/CustomUrl.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/CustomImage/CustomUrl/CustomUrl.tsx
  apps/journeys-admin/src/components/TextFieldForm/TextFieldForm.spec.tsx
  apps/journeys-admin/src/components/TextFieldForm/TextFieldForm.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#1817 refactor: unify selection border style
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: priority: soon, type: feat, effort: 1

#1820 feat: remove published state
  apps/journeys-admin/__generated__/JourneyPublish.ts
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardInfo/JourneyCardInfo.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.stories.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
  apps/journeys-admin/src/components/JourneyView/Menu/index.ts
  apps/journeys-admin/src/components/JourneyView/Properties/JourneyDetails/JourneyDetails.tsx
  apps/journeys-admin/src/components/TemplateCard/TemplateCard.tsx
  apps/journeys-admin/src/components/TemplateList/ActiveTemplates/ActiveTemplates.spec.tsx
  apps/journeys-admin/src/components/TemplateList/ArchivedTemplates/ArchivedTemplates.spec.tsx
  apps/journeys-admin/src/components/TemplateList/TrashedTemplates/TrashedTemplates.spec.tsx
Labels: effort: 5, priority: now, type: refactor

#1790 fix: show selected language on dropdown
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
Labels: type: fix, priority: soon, effort: 1

#1793 fix: add hover only on devices which support hover
  libs/shared/ui/src/libs/themes/base/tokens/colors.ts
  libs/shared/ui/src/libs/themes/base/tokens/components.ts
Labels: effort: 2, type: fix, priority: soon

#1836 fix: hide users from journeys
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/team/team.resolver.spec.ts
  apps/api-journeys/src/app/modules/team/team.resolver.ts
Labels: type: fix, effort: 13, priority: soon, on stage

#1799 test: set up playwright to export report for each project
  .github/workflows/app-deploy.yml
Labels: type: test, priority: 2day, effort: 2, type: ci

#1839 fix: permission error
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/team/team.resolver.spec.ts
  apps/api-journeys/src/app/modules/team/team.resolver.ts
  apps/journeys-admin/project.json
  apps/journeys/project.json
  apps/watch/project.json
  libs/nest/common/src/lib/CaslAuthModule/decorators/caslAbility.ts
Labels: type: fix, priority: now, effort: 1, on stage

#1845 fix: make all VR dry run
  .github/workflows/main.yml
Labels: type: fix, priority: now, effort: 1

#1812 refactor: mobile landscape uses desktop layout
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.tsx
  libs/journeys/ui/src/components/Card/OverlayContent/OverlayContent.tsx
Labels: priority: soon, effort: 1, type: refactor

#1822 feat: show team members in access dialog
  apps/journeys-admin/__generated__/GetJourneyWithPermissions.ts
  apps/journeys-admin/__generated__/GetJourneyWithUserJourneys.ts
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.stories.tsx
  apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/AddUserSection.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/AddUserSection.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserList.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserList.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/ApproveUser/ApproveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/ApproveUser/ApproveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/PromoteUser/PromoteUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/PromoteUser/PromoteUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/RemoveUser/RemoveUser.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/RemoveUser/RemoveUser.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/UserListItem.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/UserList/UserListItem/UserListItem.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/UserTeamList/UserTeamList.spec.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/UserTeamList/UserTeamList.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/UserTeamList/UserTeamListItem/UserTeamListItem.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 5, priority: soon, type: feat
