Repository JesusFilm/core, pull requests merged in 2024-04, with the labels that each got.

#2540 feat: video block node stories
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/VideoBlockNode/VideoBlockNode.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#2541 feat: add stories for RadioOptionBlockNode
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/RadioOptionBlockNode/RadioOptionBlockNode.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#2542 feat: add stories for SignUpBlockNode
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SignUpBlockNode/SignUpBlockNode.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#2543 feat: form block node stories
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/FormBlockNode/FormBlockNode.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#2544 feat: add stories for ButtonBlockNode
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ButtonBlockNode/ButtonBlockNode.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#2545 feat: text response block node stories
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/TextResponseBlockNode/TextResponseBlockNode.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#2391 fix: watch duration and theme color
  apps/watch-e2e/src/e2e/chapter.spec.ts-snapshots/after-video-firefox-linux.png
  apps/watch-e2e/src/e2e/feature-film.spec.ts-snapshots/after-video-firefox-linux.png
  apps/watch/pages/_app.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
Labels: type: fix, priority: now, effort: 1

#2514 feat: properties form stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Credentials/ApiTokenTextField/ApiTokenTextField.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Credentials/Credentials.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Credentials/Credentials.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Credentials/Credentials.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Credentials/FormSlugSelect/FormSlug.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Credentials/ProjectIdSelect/ProjectdSelect.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Form.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Form.tsx
Labels: effort: 3, priority: soon, type: feat

#2507 feat: menu stories
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.stories.tsx
Labels: effort: 2, priority: soon, type: feat

#2509 feat: footer chat stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Chat/Chat.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Chat/ChatOption/ChatOption.stories.tsx
Labels: effort: 2, priority: soon, type: feat

#2512 feat: properties card stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundColor/BackgroundColor.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/Card.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardLayout/CardLayout.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardStyling/CardStyling.stories.tsx
Labels: effort: 3, priority: soon, type: feat

#2555 feat: vercel domain error handling
  apps/api-journeys/src/app/modules/customDomain/customDomain.service.spec.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.service.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#2537 feat: properties blocks radio option stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioOption/RadioOption.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioOption/RadioOption.tsx
Labels: effort: 2, priority: soon, type: feat

#2556 test: story add block
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/FormBlockNode/FormBlockNode.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/Button/Button.stories.tsx
Labels: effort: 2, priority: soon, type: feat

#2568 fix: language switcher fingerprint
  apps/journeys-admin/middleware.ts
  apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.tsx
Labels: type: fix, priority: now, effort: 1

#2564 feat: update ToggleButtonGroup story path
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/ToggleButtonGroup/ToggleButtonGroup.stories.tsx
Labels: priority: soon, effort: 1, type: refactor

#2571 fix: redirect value null initially
  apps/journeys-admin/pages/users/verify.tsx
Labels: type: fix, priority: now, effort: 1

#2572 chore: update gateway
  .devcontainer/post-create-command.sh
  apps/api-gateway/Dockerfile
  apps/api-gateway/router.prod.yaml
  apps/api-gateway/routerSchema.json
  apps/api-gateway/schema.graphql
Labels: priority: now, effort: 1, type: chore, dependencies, on stage

#2533 feat: properties blocks image stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Image.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Image.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Options/ImageOptions.stories.tsx
Labels: effort: 3, priority: soon, type: feat

#2538 feat: properties blocks signup stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/SignUp/SignUp.stories.tsx
Labels: effort: 2, priority: soon, type: feat

#2576 fix: lint
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
Labels: type: fix, priority: now, effort: 1

#2530 feat: fix prisma alpine openssl
  apps/api-journeys/Dockerfile
  apps/api-journeys/db/Dockerfile
  apps/api-journeys/db/schema.prisma
  apps/api-languages/Dockerfile
  apps/api-languages/db/Dockerfile
  apps/api-languages/db/schema.prisma
  apps/api-media/Dockerfile
  apps/api-media/db/schema.prisma
  apps/api-tags/Dockerfile
  apps/api-tags/db/Dockerfile
  apps/api-tags/db/schema.prisma
  apps/api-users/Dockerfile
  apps/api-users/db/schema.prisma
  apps/api-videos/Dockerfile
  apps/api-videos/db/Dockerfile
  apps/api-videos/db/schema.prisma
Labels: priority: 2day, effort: 3, type: feat, on stage

#2548 feat: properties blocks step stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/NextCard.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/Step.stories.tsx
Labels: effort: 2, priority: soon, type: feat

#2574 fix: new create journey button
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.tsx
Labels: type: fix, priority: now, effort: 1

#2578 fix: dialog styling
  apps/journeys-admin/src/components/TemplateView/AccountCheckDialog/AccountCheckDialog.tsx
Labels: type: fix, priority: now, effort: 1

#2565 feat: sign in tabs
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.tsx
  apps/journeys-admin/src/components/SignIn/EmailUsedPage/EmailUsedPage.spec.tsx
  apps/journeys-admin/src/components/SignIn/HomePage/HomePage.spec.tsx
  apps/journeys-admin/src/components/SignIn/HomePage/HomePage.tsx
  apps/journeys-admin/src/components/SignIn/SignIn.spec.tsx
  apps/journeys-admin/src/components/SignIn/SignInServiceButton/SignInServiceButton.spec.tsx
  apps/journeys-admin/src/components/SignIn/SignInServiceButton/SignInServiceButton.tsx
  apps/journeys-admin/src/components/SignIn/SignInTabs/SignInTabs.spec.tsx
  apps/journeys-admin/src/components/SignIn/SignInTabs/SignInTabs.stories.tsx
  apps/journeys-admin/src/components/SignIn/SignInTabs/SignInTabs.tsx
  apps/journeys-admin/src/components/SignIn/SignInTabs/index.ts
  apps/journeys-admin/src/components/TemplateView/AccountCheckDialog/AccountCheckDialog.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.spec.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: now, type: feat

#2581 feat: add email auth provider
  apps/nexus-admin/pages/resources/import-youtube-template.tsx
  apps/nexus-admin/src/components/ChannelsTable/ChannelsTable.tsx
  apps/nexus-admin/src/components/Login/Login.tsx
  apps/nexus-admin/utils/getOrigin.ts
Labels: on stage

#2577 fix: action stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/EmailAction/EmailAction.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/LinkAction/LinkAction.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateAction/NavigateAction.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateToBlockAction/NavigateToBlockAction.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
Labels: type: fix, priority: now, effort: 1

#2579 fix: editor stories
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
Labels: type: fix, priority: now, effort: 1

#2575 test: editor fab story
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/Fab/Fab.stories.tsx
Labels: type: test, priority: soon, effort: 1

#2551 feat: properties blocks textresponse stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/TextResponseFields.stories.tsx
Labels: effort: 2, priority: soon, type: feat

#2573 docs: docker update issues
  apps/docs/docs/02-getting-started/01-development-environment.mdx
  apps/docs/docs/02-getting-started/03-microservice-databases.mdx
Labels: type: docs, priority: soon, effort: 1

#2569 fix: swipe not being blocked on slider
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.spec.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
Labels: type: fix, priority: soon, effort: 1

#2583 fix: card padding
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.tsx
Labels: type: fix, priority: now, effort: 1

#2580 fix: verification long loading time
  apps/journeys-admin/pages/users/verify.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.tsx
Labels: type: fix, priority: now, effort: 1

#2582 feat: limit one video block per parent
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#2584 fix: codeql security issue
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
Labels: type: fix, priority: now, effort: 1

#2589 feat: disable erd on client
  apps/api-journeys/db/schema.prisma
  apps/api-languages/db/schema.prisma
  apps/api-media/db/schema.prisma
  apps/api-tags/db/schema.prisma
  apps/api-users/db/schema.prisma
  apps/api-videos/db/schema.prisma
Labels: priority: now, type: feat, effort: 1

#2590 fix: sanitize url
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.spec.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
  apps/journeys-admin/src/libs/useRedirectNewAccount/useHandleNewAccountRedirect.spec.tsx
  apps/journeys-admin/src/libs/useRedirectNewAccount/useHandleNewAccountRedirect.ts
Labels: type: fix, priority: now, effort: 1

#2593 chore: update checkout
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-prod-worker.yml
  .github/workflows/api-gateway-stage-worker.yml
  .github/workflows/app-deploy.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/crowdin.yml
  .github/workflows/danger.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/ecs-frontend-deploy-prod-worker.yml
  .github/workflows/ecs-frontend-deploy-stage-worker.yml
  .github/workflows/main.yml
Labels: priority: soon, effort: 1, type: chore, on stage

#2595 chore: actions cache update
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-prod-worker.yml
  .github/workflows/api-gateway-stage-worker.yml
  .github/workflows/app-deploy.yml
  .github/workflows/danger.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/ecs-frontend-deploy-prod-worker.yml
  .github/workflows/ecs-frontend-deploy-stage-worker.yml
  .github/workflows/main.yml
Labels: priority: soon, effort: 1, type: chore

#2596 chore: action update
  .github/workflows/api-deploy-worker.yml
  .github/workflows/main.yml
Labels: priority: soon, effort: 1, type: chore

#2597 fix: redirect new account
  apps/journeys-admin/src/libs/useRedirectNewAccount/useHandleNewAccountRedirect.spec.tsx
  apps/journeys-admin/src/libs/useRedirectNewAccount/useHandleNewAccountRedirect.ts
Labels: type: fix, priority: now, effort: 1

#2598 fix: custom domain verification
  apps/api-journeys/src/app/modules/customDomain/customDomain.service.spec.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.service.ts
Labels: type: fix, priority: now, effort: 1, on stage

#2599 refactor: change nexus list page to transitional page
  apps/nexus-admin/__generated__/Nexuses.ts
  apps/nexus-admin/__generated__/globalTypes.ts
  apps/nexus-admin/pages/index.tsx
  apps/nexus-admin/src/components/CreateNexusModal/CreateNexusModal.tsx
  libs/locales/en/apps-nexus-admin.json
Labels: on stage

#2600 feat: add upload consent modal
  apps/nexus-admin/__generated__/ResourceFromGoogleDrive.ts
  apps/nexus-admin/__generated__/globalTypes.ts
  apps/nexus-admin/pages/channels/index.tsx
  apps/nexus-admin/pages/resources/import-youtube-template.tsx
  apps/nexus-admin/pages/resources/index.tsx
  apps/nexus-admin/src/components/CreateChannelModal/CreateChannelModal.spec.tsx
  apps/nexus-admin/src/components/CreateChannelModal/CreateChannelModal.tsx
  apps/nexus-admin/src/components/UploadConfirmationModal/UploadConfirmationModal.tsx
  apps/nexus-admin/src/components/UploadConfirmationModal/index.ts
  libs/locales/en/apps-nexus-admin.json
Labels: on stage

#2601 docs: adding mock files to hooks
  apps/docs/docs/03-basics/03-frontend/06-custom-hooks/index.md
  apps/docs/docs/03-basics/03-frontend/06-custom-hooks/mock-ts-directory-add.png
Labels: type: docs, priority: soon, effort: 1

#2603 test: add slider stories
  apps/journeys-admin/src/components/Editor/Slider/Slider.stories.tsx
Labels: type: test, priority: soon, effort: 1

#2602 test: slider settings stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/Settings.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#2470 fix: hash sum mismach
  .devcontainer/Dockerfile
Labels: effort: 8, type: fix, priority: soon

#2587 refactor: color display icon story
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/ColorDisplayIcon/ColorDisplayIcon.stories.tsx
Labels: priority: soon, effort: 1, type: refactor

#2586 refactor: canvas detail icon story
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Icon/Icon.stories.tsx
Labels: priority: soon, effort: 1, type: refactor

#2566 feat: toggle option stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/ToggleOption/ToggleOption.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/ToggleOption/ToggleOption.tsx
Labels: priority: soon, effort: 1, type: refactor

#2606 feat: temp fix
  apps/api-nexus/src/app/modules/bullMQ/listener/jobListener.ts
  apps/nexus-admin/project.json
Labels: on stage

#2608 chore: update terraform to match
  apps/api-nexus/infrastructure/locals.tf
  infrastructure/modules/aws/aurora/main.tf
Labels: priority: now, effort: 1, type: chore

#2611 feat: update terraform scheduled
  infrastructure/modules/aws/ecs-scheduled-task/locals.tf
  infrastructure/modules/aws/ecs-scheduled-task/main.tf
  infrastructure/modules/aws/ecs-scheduled-task/variables.tf
Labels: priority: 2day, type: feat, effort: 1

#2567 fix: video on second card being muted
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.spec.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.tsx
Labels: type: fix, priority: soon, effort: 1

#2591 feat: video race condition
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Labels: priority: soon, type: feat, effort: 1

#2613 fix: show felt needs button without images
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.tsx
Labels: type: fix, priority: now, effort: 1

#2612 fix: close menu on dialog open
  apps/journeys-admin/src/components/Editor/Toolbar/Items/AccessItem/AccessItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/AccessItem/AccessItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DescriptionItem/DescriptionItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DescriptionItem/DescriptionItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/LanguageItem/LanguageItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/LanguageItem/LanguageItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TemplateSettingsItem/TemplateSettingsItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TemplateSettingsItem/TemplateSettingsItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TitleItem/TitleItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TitleItem/TitleItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.tsx
Labels: type: fix, priority: soon, effort: 1

#2609 fix: inline edit wrapper saves on outside click
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/useOnClickOutside/useOnClickOutside.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/useOnClickOutside/useOnClickOutside.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/ColorDisplayIcon/ColorDisplayIcon.stories.tsx
Labels: type: fix, effort: 3, priority: soon

#2615 feat: example email
  apps/api-users/infrastructure/locals.tf
  apps/api-users/src/app/modules/user/user.service.spec.ts
  apps/api-users/src/app/modules/user/user.service.ts
Labels: effort: 2, priority: soon, type: feat

#2553 feat: image block editor stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/AIGallery/AIGallery.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/CustomImage/CustomImage.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/ImageBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/UnsplashGallery.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockHeader/ImageBlockHeader.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockThumbnail/ImageBlockThumbnail.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageLibrary/ImageLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageSource/ImageSource.stories.tsx
Labels: effort: 2, priority: soon, type: feat

#2617 fix: canvas stories
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/MoveBlock/MoveBlock.stories.tsx
Labels: type: fix, priority: soon, effort: 1

#2563 feat: step block node stories
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#2621 test: video property stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Video.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Video.tsx
Labels: type: fix, priority: soon, effort: 1

#2622 fix: typography stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Typography.stories.tsx
Labels: type: fix, effort: 3, priority: soon

#2620 feat: social preview stories
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.tsx
Labels: effort: 3, priority: soon, type: feat

#2619 fix: move icon panel
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/QuickControls.tsx
Labels: type: fix, priority: soon, effort: 1

#2624 feat: new mutaion to get spreadsheet data
  apps/api-nexus/src/app/modules/resource/resource.graphql
  apps/api-nexus/src/app/modules/resource/resource.resolver.ts
Labels: on stage

#2627 fix: add frameref to iframe
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
Labels: type: fix, priority: soon, effort: 1

#2629 fix: cors localhost for api-gateway
  apps/api-gateway/router.prod.yaml
Labels: type: fix, priority: now, effort: 1, on stage

#2616 fix: onboarding style alignment
  apps/journeys-admin/public/landing-description.png
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingLandingDrawer/OnboardingLandingDrawer.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingLandingDrawer/OnboardingLandingDrawer.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingLandingDrawer/index.ts
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingStepper/OnboardingStepper.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingTemplateCard/OnboardingTemplateCard.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.stories.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.tsx
Labels: effort: 8, type: fix, priority: soon

#2486 feat: algolia seed logic
  apps/api-videos/Dockerfile
  apps/api-videos/infrastructure/locals.tf
  apps/api-videos/src/app/app.module.ts
  apps/api-videos/src/app/modules/algolia/algolia.consumer.spec.ts
  apps/api-videos/src/app/modules/algolia/algolia.consumer.ts
  apps/api-videos/src/app/modules/algolia/algolia.module.ts
  apps/api-videos/src/app/modules/algolia/algolia.queue.spec.ts
  apps/api-videos/src/app/modules/algolia/algolia.queue.ts
  apps/api-videos/src/app/modules/algolia/algolia.service.spec.ts
  apps/api-videos/src/app/modules/algolia/algolia.service.ts
Labels: effort: 5, priority: soon, type: feat, on stage, keep

#2498 feat: watch search enhancement
  apps/watch-e2e/src/e2e/filters.spec.ts-snapshots/see-all-landing-firefox-linux.png
  apps/watch/pages/videos.tsx
  apps/watch/src/components/VideoGrid/VideoGrid.tsx
  apps/watch/src/components/VideosPage/FilterList/FilterList.tsx
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.stories.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
  apps/watch/src/components/VideosPage/utils/checkFilterApplied/checkFilterApplied.ts
  apps/watch/src/components/VideosPage/utils/checkFilterApplied/index.ts
  apps/watch/src/components/VideosPage/utils/getQueryParameters/getQueryParameters.ts
  apps/watch/src/components/VideosPage/utils/getQueryParameters/index.ts
  apps/watch/src/components/VideosPage/utils/transformAlgoliaVideos/index.ts
  apps/watch/src/components/VideosPage/utils/transformAlgoliaVideos/transformAlgoliaVideos.ts
  apps/watch/src/components/VideosPage/utils/useVideoSearch/index.ts
  apps/watch/src/components/VideosPage/utils/useVideoSearch/useVideoSearch.ts
  libs/locales/en/apps-watch.json
  package-lock.json
  package.json
Labels: effort: 13, priority: soon, type: feat, keep

#2628 fix: handle long team name
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.tsx
Labels: type: fix, priority: soon, effort: 1

#2634 fix: overflow y auto
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.tsx
Labels: type: fix, priority: now, effort: 1

#2635 fix: pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
  dangerfile.ts
Labels: type: fix, priority: now, effort: 1

#2630 fix: disable custom domain form autocomplete
  apps/journeys-admin/src/components/Team/CustomDomainDialog/DomainNameForm/DomainNameForm.tsx
Labels: type: fix, priority: soon, effort: 1

#2633 fix: localhost cors
  apps/api-gateway/router.prod.yaml
Labels: type: fix, priority: soon, effort: 1

#2631 feat: stg dev environments for frontends without a backend
  apps/docs/docs/02-getting-started/02-environment-variables.mdx
  apps/journeys-admin/project.json
  apps/journeys/project.json
  apps/watch/project.json
Labels: priority: now, type: feat, effort: 1

#2636 docs: add algolia search
  .github/pull_request_template.md
  .github/workflows/ecs-frontend-deploy-prod-worker.yml
  .github/workflows/ecs-frontend-deploy-prod.yml
  .github/workflows/ecs-frontend-deploy-stage-worker.yml
  .github/workflows/ecs-frontend-deploy-stage.yml
  .github/workflows/main.yml
  apps/docs/docusaurus.config.js
  apps/docs/project.json
  dangerfile.ts
Labels: priority: now, type: docs, effort: 1

#2638 refactor: commit template
  .github/pull_request_template.md
Labels: priority: soon, effort: 1, type: refactor

#2623 fix: paths
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostList/HostListItem/HostListItem.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Align/Align.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Color/Color.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Typography.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Variant/Variant.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.stories.tsx
Labels: type: fix, effort: 3, priority: soon

#2626 fix: quick select event handling
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DeleteBlock/DeleteBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DeleteBlock/DeleteBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DuplicateBlock/DuplicateBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DuplicateBlock/DuplicateBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/MoveBlock/MoveBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/MoveBlock/MoveBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.tsx
Labels: effort: 5, type: fix, priority: soon

#2522 chore: new crowdin translations
  libs/locales/am-ET/apps-journeys-admin.json
  libs/locales/am-ET/apps-journeys.json
  libs/locales/am-ET/apps-watch.json
  libs/locales/ar-SA/apps-journeys-admin.json
  libs/locales/ar-SA/apps-journeys.json
  libs/locales/ar-SA/apps-watch.json
  libs/locales/bn-BD/apps-journeys-admin.json
  libs/locales/bn-BD/apps-journeys.json
  libs/locales/bn-BD/apps-watch.json
  libs/locales/es-ES/apps-journeys-admin.json
  libs/locales/es-ES/apps-journeys.json
  libs/locales/es-ES/apps-watch.json
  libs/locales/fr-FR/apps-journeys-admin.json
  libs/locales/fr-FR/apps-journeys.json
  libs/locales/fr-FR/apps-watch.json
  libs/locales/hi-IN/apps-journeys-admin.json
  libs/locales/hi-IN/apps-journeys.json
  libs/locales/hi-IN/apps-watch.json
  libs/locales/id-ID/apps-journeys-admin.json
  libs/locales/id-ID/apps-journeys.json
  libs/locales/id-ID/apps-watch.json
  libs/locales/ja-JP/apps-journeys-admin.json
  libs/locales/ja-JP/apps-journeys.json
  libs/locales/ja-JP/apps-watch.json
  libs/locales/my-MM/apps-journeys-admin.json
  libs/locales/my-MM/apps-journeys.json
  libs/locales/my-MM/apps-watch.json
  libs/locales/ru-RU/apps-journeys-admin.json
  libs/locales/ru-RU/apps-journeys.json
  libs/locales/ru-RU/apps-watch.json
  libs/locales/th-TH/apps-journeys-admin.json
  libs/locales/th-TH/apps-journeys.json
  libs/locales/th-TH/apps-watch.json
  libs/locales/tl-PH/apps-journeys-admin.json
  libs/locales/tl-PH/apps-journeys.json
  libs/locales/tl-PH/apps-watch.json
  libs/locales/tr-TR/apps-journeys-admin.json
  libs/locales/tr-TR/apps-journeys.json
  libs/locales/tr-TR/apps-watch.json
  libs/locales/ur-PK/apps-journeys-admin.json
  libs/locales/ur-PK/apps-journeys.json
  libs/locales/ur-PK/apps-watch.json
  libs/locales/vi-VN/apps-journeys-admin.json
  libs/locales/vi-VN/apps-journeys.json
  libs/locales/vi-VN/apps-watch.json
  libs/locales/zh-Hans-CN/apps-journeys-admin.json
  libs/locales/zh-Hans-CN/apps-journeys.json
  libs/locales/zh-Hans-CN/apps-watch.json
  libs/locales/zh-Hant-TW/apps-journeys-admin.json
  libs/locales/zh-Hant-TW/apps-journeys.json
  libs/locales/zh-Hant-TW/apps-watch.json
Labels: priority: soon, effort: 1, type: chore

#2647 fix: change language text
  apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.spec.tsx
  apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#2644 fix: add id to langauge search
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.tsx
Labels: type: fix, effort: 3, priority: soon

#2632 fix: video delete
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DuplicateBlock/DuplicateBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/QuickControls.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/QuickControls.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/QuickControls.tsx
Labels: type: fix, priority: soon, effort: 1

#2639 fix: image or video library closing on outside click
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostAvatarsButton/HostAvatarsButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/Drawer.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/Drawer.tsx
Labels: type: fix, priority: soon, effort: 1

#2641 feat: add poll block property text
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioQuestion/RadioQuestion.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioQuestion/RadioQuestion.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioQuestion/RadioQuestion.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioQuestion/index.ts
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#2640 fix: added share menu item on mobile
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.tsx
Labels: type: fix, effort: 3, priority: soon

#2649 build: changed cors settings
  apps/api-gateway/router.yaml
Labels: priority: now, effort: 1, type: build

#2653 fix: sync english to algolia on stg and dev
  apps/api-videos/src/app/modules/algolia/algolia.service.spec.ts
  apps/api-videos/src/app/modules/algolia/algolia.service.ts
Labels: type: fix, priority: now, effort: 1

#2648 fix: single click to add card on journey flow(PC/Android)
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
Labels: type: fix, effort: 3, priority: now

#2655 feat: arclight project
  .github/workflows/app-deploy.yml
  .github/workflows/ecs-frontend-deploy-prod-worker.yml
  .github/workflows/ecs-frontend-deploy-prod.yml
  .github/workflows/ecs-frontend-deploy-stage-worker.yml
  .github/workflows/ecs-frontend-deploy-stage.yml
  .github/workflows/main.yml
  .gitignore
  .vscode/settings.json
  apps/arclight/.eslintrc.json
  apps/arclight/__generated__/graphql-env.d.ts
  apps/arclight/index.d.ts
  apps/arclight/jest.config.ts
  apps/arclight/next-env.d.ts
  apps/arclight/next.config.js
  apps/arclight/project.json
  apps/arclight/public/.gitkeep
  apps/arclight/public/arclight.png
  apps/arclight/public/favicon.ico
  apps/arclight/src/app/layout.tsx
  apps/arclight/src/app/page.tsx
  apps/arclight/src/app/v2/media-components/route.ts
  apps/arclight/src/lib/apolloClient/apolloClient.ts
  apps/arclight/src/lib/apolloClient/cache.ts
  apps/arclight/src/lib/apolloClient/index.ts
  apps/arclight/tsconfig.json
  apps/arclight/tsconfig.spec.json
  apps/docs/docs/06-quick-links.md
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
  nx.json
  package-lock.json
  package.json
Labels: priority: 2day, effort: 13, type: feat, on stage

#2659 feat: arclight expansion
  apps/arclight-e2e/.eslintrc.json
  apps/arclight-e2e/playwright.config.ts
  apps/arclight-e2e/project.json
  apps/arclight-e2e/src/e2e/docs.spec.ts
  apps/arclight-e2e/tsconfig.e2e.json
  apps/arclight-e2e/tsconfig.json
  apps/arclight/__generated__/graphql-env.d.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/[languageId]/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/route.ts
  apps/arclight/src/app/v2/media-components/route.ts
  apps/arclight/src/app/v2/media-countries/route.ts
  apps/arclight/src/app/v2/media-languages/route.ts
  apps/arclight/src/lib/paramsToRecord.ts
Labels: priority: 2day, effort: 5, type: feat

#2662 revert: e2e tests from running
  .github/workflows/app-deploy.yml
Labels: priority: now, effort: 1, type: revert

#2650 fix: remove hover icon
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/Button/Button.tsx
Labels: type: fix, effort: 3, priority: soon

#2663 fix: image and video panel scroll
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageLibrary/ImageLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.tsx
Labels: effort: 2, type: fix, priority: soon

#2660 fix: image and video thumbnails not displaying on node
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/getCardMetadata/getCardMetadata.ts
Labels: type: fix, effort: 3, priority: soon

#2652 fix: hide template filters with no background
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/data.ts
Labels: effort: 2, type: fix, priority: now

#2667 test: enable e2e tests(disable snapshot tests). retry only twice
  .github/workflows/app-deploy.yml
  apps/arclight-e2e/playwright.config.ts
  apps/docs-e2e/playwright.config.ts
  apps/journeys-admin-e2e/src/e2e/lighthouse/homepage.spec.ts
  apps/journeys-e2e/playwright.config.ts
  apps/nexus-admin-e2e/playwright.config.ts
  apps/watch-e2e/playwright.config.ts
  apps/watch-e2e/src/e2e/chapter.spec.ts
Labels: type: test, priority: soon, effort: 1, type: ci

#2664 feat: api-videos new fields part 1
  apps/api-videos/db/migrations/20240423211912_20240423211910/migration.sql
  apps/api-videos/db/schema.prisma
  apps/api-videos/db/seed.ts
  apps/api-videos/project.json
  apps/api-videos/src/app/modules/algolia/algolia.service.spec.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/libs/arclight/arclight.spec.ts
  apps/api-videos/src/libs/arclight/arclight.ts
  apps/api-videos/src/libs/postgresql/__mocks__/postgresql.ts
  apps/api-videos/src/libs/postgresql/postgresql.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#2672 feat: arclight media-component-links
  apps/arclight/src/app/v2/media-component-links/route.ts
Labels: priority: 2day, effort: 2, type: feat

#2675 feat: arclight metadata-language-tags
  apps/arclight/src/app/v2/metadata-language-tags/route.ts
Labels: priority: 2day, effort: 2, type: feat

#2673 feat: arclight media-components language
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/route.ts
Labels: priority: 2day, effort: 2, type: feat

#2677 feat: arclight media-component-links single
  apps/arclight/src/app/v2/media-component-links/[mediaComponentId]/route.ts
Labels: priority: 2day, effort: 2, type: feat

#2665 feat: establish extract iterator pattern from bq
  apps/api-videos/project.json
  apps/api-videos/src/app/app.module.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.console.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.spec.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.module.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.service.spec.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.service.ts
  package-lock.json
  package.json
Labels: effort: 8, type: fix, priority: soon

#2671 feat: api videos new fields p2
  apps/api-videos/db/migrations/20240425003457_20240425003450/migration.sql
  apps/api-videos/db/schema.prisma
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/algolia/algolia.service.spec.ts
  apps/api-videos/src/app/modules/algolia/algolia.service.ts
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/libs/arclight/arclight.spec.ts
  apps/api-videos/src/libs/arclight/arclight.ts
  apps/api-videos/src/libs/postgresql/postgresql.ts
Labels: effort: 3, priority: soon, type: feat

#2669 fix: reset canvas focus when slider to journey flow
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: effort: 2, type: fix, priority: soon

#2658 fix: card resize and zoom issues
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/utils/calculateDimensions/calculateDimensions.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/utils/calculateDimensions/index.ts
Labels: type: fix, priority: soon, effort: 1

#2680 refactor: bq videos importer
  apps/api-gateway/schema.graphql
  apps/api-videos/db/migrations/20240426052218_20240426052217/migration.sql
  apps/api-videos/db/schema.prisma
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.spec.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.module.ts
  apps/api-videos/src/app/modules/importer/importer.module.ts
  apps/api-videos/src/app/modules/importer/importer.service.ts
  apps/api-videos/src/app/modules/importer/videos/videos.service.spec.ts
  apps/api-videos/src/app/modules/importer/videos/videos.service.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
  apps/watch/src/libs/utils/getLabelDetails/getLabelDetails.ts
Labels: priority: now, effort: 1, type: refactor

#2654 fix: active content to be social if from social
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: type: fix, priority: soon, effort: 1
