Repository JesusFilm/core, pull requests merged in 2024-07, with the labels that each got.

#2974 feat: integration button team menu
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.spec.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/PackagePlus.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#2970 feat: chat platform icons
  libs/shared/ui/src/components/icons/Home3.tsx
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/MessageChat2.tsx
  libs/shared/ui/src/components/icons/MessageNotifyCircle.tsx
  libs/shared/ui/src/components/icons/MessageNotifySquare.tsx
  libs/shared/ui/src/components/icons/MessageSquare.tsx
  libs/shared/ui/src/components/icons/MessageText2.tsx
  libs/shared/ui/src/components/icons/Send2.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: priority: 2day, good first issue, effort: 2, type: feat

#2978 test: skip the failed tests for now
  apps/journeys-admin-e2e/src/e2e/discover/active-archived-trash.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/journey-level-actions.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/teams.spec.ts
  apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
Labels: type: test, priority: now, effort: 1

#2964 test: deploy the app then run related e2e tests when just e2e tests are updated
  .github/workflows/app-deploy.yml
  tools/scripts/deploy-apps.ts
Labels: type: test, effort: 3, priority: soon, type: ci

#2971 feat: filter stats by all time
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsOverlaySwitch/AnalyticsOverlaySwitch.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsOverlaySwitch/AnalyticsOverlaySwitch.tsx
Labels: priority: soon, type: feat, effort: 1

#2980 fix: alb ssl forward
  infrastructure/modules/aws/locals.tf
  infrastructure/modules/aws/main.tf
Labels: type: fix, priority: now, effort: 1

#2957 feat: add keyword schema
  apps/api-videos/db/migrations/20240625154813_20240625154812/migration.sql
  apps/api-videos/db/schema.prisma
Labels: effort: 2, priority: soon, type: feat

#2932 feat: make watch header transparent at top of page
  apps/watch/src/components/Header/Header.tsx
Labels: priority: soon, type: feat, effort: 1

#2919 feat: growth space backend
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20240627035348_20240627035346/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/gql.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/lib/casl/__generated__/prismaSubjects.ts
  apps/api-journeys/src/app/lib/casl/caslFactory/caslFactory.spec.ts
  apps/api-journeys/src/app/lib/casl/caslFactory/caslFactory.ts
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.graphql
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.ts
  apps/api-journeys/src/app/modules/event/event.module.ts
  apps/api-journeys/src/app/modules/event/event.service.spec.ts
  apps/api-journeys/src/app/modules/event/event.service.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.ts
  apps/api-journeys/src/app/modules/integration/growthSpaces/growthSpaces.graphql
  apps/api-journeys/src/app/modules/integration/growthSpaces/growthSpaces.resolver.spec.ts
  apps/api-journeys/src/app/modules/integration/growthSpaces/growthSpaces.resolver.ts
  apps/api-journeys/src/app/modules/integration/growthSpaces/growthSpaces.service.spec.ts
  apps/api-journeys/src/app/modules/integration/growthSpaces/growthSpaces.service.ts
  apps/api-journeys/src/app/modules/integration/integration.acl.spec.ts
  apps/api-journeys/src/app/modules/integration/integration.acl.ts
  apps/api-journeys/src/app/modules/integration/integration.graphql
  apps/api-journeys/src/app/modules/integration/integration.module.ts
  apps/api-journeys/src/app/modules/integration/integration.resolver.spec.ts
  apps/api-journeys/src/app/modules/integration/integration.resolver.ts
  apps/api-journeys/src/app/modules/team/team.graphql
  apps/api-journeys/src/app/modules/team/team.resolver.spec.ts
  apps/api-journeys/src/app/modules/team/team.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  libs/nest/common/src/lib/crypto/crypto.spec.ts
  libs/nest/common/src/lib/crypto/crypto.ts
  libs/nest/common/src/lib/crypto/index.ts
Labels: effort: 5, type: fix, priority: soon, on stage

#2925 feat: integrations component
  apps/journeys-admin-e2e/src/pages/journey-page.ts
  apps/journeys-admin/__generated__/GetIntegration.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/teams/[teamId]/integrations/index.tsx
  apps/journeys-admin/pages/teams/[teamId]/integrations/new/index.tsx
  apps/journeys-admin/public/growth-spaces-logo.png
  apps/journeys-admin/src/components/Team/BreadcrumbNavigation/BreadcrumbNavigation.spec.tsx
  apps/journeys-admin/src/components/Team/BreadcrumbNavigation/BreadcrumbNavigation.tsx
  apps/journeys-admin/src/components/Team/BreadcrumbNavigation/index.ts
  apps/journeys-admin/src/components/Team/Integrations/Integrations.spec.tsx
  apps/journeys-admin/src/components/Team/Integrations/Integrations.tsx
  apps/journeys-admin/src/components/Team/Integrations/IntegrationsButton/IntegrationsButton.spec.tsx
  apps/journeys-admin/src/components/Team/Integrations/IntegrationsButton/IntegrationsButton.tsx
  apps/journeys-admin/src/components/Team/Integrations/IntegrationsButton/index.ts
  apps/journeys-admin/src/components/Team/Integrations/index.ts
  apps/journeys-admin/src/components/Team/TeamIntegrations/TeamIntegrations.spec.tsx
  apps/journeys-admin/src/components/Team/TeamIntegrations/TeamIntegrations.stories.tsx
  apps/journeys-admin/src/components/Team/TeamIntegrations/TeamIntegrations.tsx
  apps/journeys-admin/src/components/Team/TeamIntegrations/index.ts
  apps/journeys-admin/src/libs/useIntegrationQuery/index.ts
  apps/journeys-admin/src/libs/useIntegrationQuery/useIntegrationQuery.mock.tsx
  apps/journeys-admin/src/libs/useIntegrationQuery/useIntegrationQuery.spec.tsx
  apps/journeys-admin/src/libs/useIntegrationQuery/useIntegrationQuery.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#2959 feat: text response properties udpates
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/CardFormCreate.ts
  apps/journeys-admin/__generated__/GetAdminJourney.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/TextResponseBlockCreate.ts
  apps/journeys-admin/__generated__/TextResponseFields.ts
  apps/journeys-admin/__generated__/TextResponseIntegrationUpdate.ts
  apps/journeys-admin/__generated__/TextResponseRouteUpdate.ts
  apps/journeys-admin/__generated__/TextResponseTypeUpdate.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/getPriorityBlock/getPriorityBlock.spec.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/GrowthSpacesIntegrations/GrowthSpacesIntegrations.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/GrowthSpacesIntegrations/GrowthSpacesIntegrations.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/GrowthSpacesIntegrations/Integrations/Integrations.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/GrowthSpacesIntegrations/Integrations/Integrations.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/GrowthSpacesIntegrations/Integrations/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/GrowthSpacesIntegrations/Route/Route.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/GrowthSpacesIntegrations/Route/Route.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/GrowthSpacesIntegrations/Route/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/GrowthSpacesIntegrations/Select/Select.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/GrowthSpacesIntegrations/Select/Select.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/GrowthSpacesIntegrations/Select/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/GrowthSpacesIntegrations/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Hint/Hint.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Label/Label.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/MinRows/MinRows.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/TextResponseFields.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Type/Type.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Type/Type.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Type/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardForm/CardForm.spec.tsx
  apps/journeys-admin/src/libs/useIntegrationQuery/useIntegrationQuery.mock.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/TextResponseFields.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/src/libs/testData/storyData.ts
  apps/nexus-admin/__generated__/BlockFields.ts
  apps/nexus-admin/__generated__/JourneyFields.ts
  apps/nexus-admin/__generated__/TextResponseFields.ts
  apps/nexus-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/TextResponseFields.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/TextResponse/TextResponse.spec.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.stories.tsx
  libs/journeys/ui/src/components/TextResponse/__generated__/TextResponseFields.ts
  libs/journeys/ui/src/components/TextResponse/textResponseFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: soon, type: feat

#2929 feat: growth spaces settings
  apps/journeys-admin/__generated__/IntegrationGrowthSpacesCreate.ts
  apps/journeys-admin/__generated__/IntegrationGrowthSpacesDelete.ts
  apps/journeys-admin/__generated__/IntegrationGrowthSpacesUpdate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/teams/[teamId]/integrations/[integrationId].tsx
  apps/journeys-admin/pages/teams/[teamId]/integrations/new/growth-spaces.tsx
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesCreateIntegration/GrowthSpacesCreateIntegration.spec.tsx
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesCreateIntegration/GrowthSpacesCreateIntegration.tsx
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesCreateIntegration/index.ts
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesIntegrationDetails/GrowthSpacesIntegrationDetails.spec.tsx
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesIntegrationDetails/GrowthSpacesIntegrationDetails.tsx
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesIntegrationDetails/index.ts
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesSettings/ConfigField/ConfigField.spec.tsx
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesSettings/ConfigField/ConfigField.tsx
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesSettings/ConfigField/index.ts
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesSettings/GrowthSpacesSettings.spec.tsx
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesSettings/GrowthSpacesSettings.stories.tsx
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesSettings/GrowthSpacesSettings.tsx
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesSettings/index.ts
  apps/journeys-admin/src/components/GrowthSpaces/index.ts
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#2949 fix: update domain links to remote pattern
  apps/journeys-admin/next.config.js
Labels: priority: 2day, effort: 1, type: chore

#2985 fix: use query params from template url
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.spec.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.tsx
Labels: effort: 2, type: fix, priority: now

#2977 feat: add message platform options
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20240703025040_20240703025039/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/button/button.graphql
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Chat/ChatOption/Details/Details.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/messagePlatformToLabel/messagePlatformToLabel.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/messagePlatformToLabel/messagePlatformToLabel.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/nexus-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/libs/MessageChatIcon/MessageChatIcon.spec.tsx
  libs/journeys/ui/src/libs/MessageChatIcon/MessageChatIcon.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: now, type: feat, on stage

#2947 style: auto fix lint api languages
  apps/api-languages/db/seed.ts
Labels: priority: 2day, good first issue, effort: 1, type: style

#2915 style: auto fix lint watch
  apps/watch/src/components/DownloadDialog/DownloadDialog.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
  apps/watch/src/libs/apolloClient/apolloClient.ts
Labels: priority: 2day, good first issue, effort: 1, type: style

#2987 fix: stage env gs
  apps/api-journeys/infrastructure/locals.tf
  apps/api-journeys/src/app/modules/integration/growthSpaces/growthSpaces.resolver.spec.ts
  apps/api-journeys/src/app/modules/integration/growthSpaces/growthSpaces.service.spec.ts
  apps/api-journeys/src/app/modules/integration/growthSpaces/growthSpaces.service.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#2914 style: auto fix lint journeys ui
  libs/journeys/ui/src/components/TemplateView/data.ts
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
Labels: priority: 2day, good first issue, effort: 1, type: style

#2913 style: auto fix lint journeys admin
  apps/journeys-admin/middleware.ts
  apps/journeys-admin/src/libs/parseISO8601Duration/parseISO8601Duration.ts
  apps/journeys-admin/test/mockReactFlow.ts
Labels: priority: 2day, good first issue, effort: 1, type: style

#2992 feat: add language farsi
  apps/journeys-admin/pages/templates/index.tsx
  libs/journeys/ui/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
  libs/journeys/ui/src/components/TemplateGallery/data.ts
Labels: priority: now, type: feat, effort: 1

#2994 fix: text input properties
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Label/Label.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Type/Type.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Type/Type.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#2961 feat: disable buttons while loading
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/Button/Button.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewButtonButton/NewButtonButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewButtonButton/NewButtonButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewFormButton/NewFormButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewFormButton/NewFormButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewImageButton/NewImageButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewImageButton/NewImageButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewRadioQuestionButton/NewRadioQuestionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewRadioQuestionButton/NewRadioQuestionButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewSignUpButton/NewSignUpButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewSignUpButton/NewSignUpButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewTextResponseButton/NewTextResponseButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewTextResponseButton/NewTextResponseButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewTypographyButton/NewTypographyButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewTypographyButton/NewTypographyButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewVideoButton/NewVideoButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewVideoButton/NewVideoButton.tsx
Labels: priority: 2day, good first issue, effort: 2, type: feat

#2997 test: wait for 60seconds
  apps/journeys-admin-e2e/src/pages/card-level-actions.ts
  apps/journeys-admin-e2e/src/pages/journey-page.ts
Labels: type: test, priority: now, effort: 1

#2819 fix: embed disable fullscreen
  apps/journeys/pages/[hostname]/embed/[journeySlug].tsx
  apps/journeys/pages/home/embed/[journeySlug].tsx
  apps/journeys/src/components/EmbeddedPreview/ClickableCard/ClickableCard.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
Labels: type: fix, priority: now, effort: 1

#3000 fix: use forwarded headers on k8s ingress
  infrastructure/kube/ingress/deploy.yaml
Labels: type: fix, priority: now, effort: 1

#2984 feat: image block details on node
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/getCardMetadata/getCardMetadata.spec.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/getCardMetadata/getCardMetadata.ts
Labels: priority: soon, type: feat, effort: 1

#3009 test: run 2 tests in parallel to reduce load on env so tests can be reliable
  apps/journeys-admin-e2e/playwright.config.ts
  apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
Labels: type: test, priority: now, effort: 1

#2993 fix: template language ui
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.stories.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.tsx
  libs/locales/en/libs-journeys-ui.json
Labels: type: fix, priority: now, effort: 1

#2998 feat: properties panel ui changes
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/Drawer.tsx
Labels: effort: 2, priority: soon, type: feat

#3008 feat: add more icons for buttons
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/icon/icon.graphql
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Icon/Icon.tsx
  apps/journeys/__generated__/globalTypes.ts
  apps/nexus-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/Icon/Icon.stories.tsx
  libs/journeys/ui/src/components/Icon/Icon.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#3011 test: make journeys-admin monitoring robust and upgrade checkly
  apps/journeys-admin-e2e/src/monitoring/journeys-admin.monitor.ts
  package-lock.json
  package.json
Labels: type: test, priority: soon, effort: 1

#3018 test: add 60seconds wait for element to be visible
  apps/journeys-admin-e2e/src/pages/card-level-actions.ts
  apps/journeys-admin-e2e/src/pages/template-page.ts
Labels: type: test, effort: 2, priority: soon

#3003 fix: visitor details back button front end
  apps/journeys-admin/pages/reports/visitors/[visitorId].tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.tsx
Labels: type: fix, priority: soon, effort: 1

#3004 ci: run vr test when chromatic label set
  .github/workflows/main.yml
  .github/workflows/visual-test.yml
  apps/docs/docs/03-basics/03-frontend/05-visual-testing/chromatic-label.png
  apps/docs/docs/03-basics/03-frontend/05-visual-testing/index.md
Labels: priority: soon, effort: 1, type: ci, chromatic

#3024 ci: update visual test run condition
  .github/workflows/visual-test.yml
Labels: priority: now, effort: 1, type: ci, chromatic

#2999 feat: change stroke of outlined buttons in journeys admin to 2px
  libs/shared/ui/src/libs/themes/journeysAdmin/tokens/components.ts
Labels: priority: soon, type: feat, effort: 1, chromatic

#3012 fix: onboarding template preview
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingTemplateCard/OnboardingTemplateCard.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingTemplateCard/OnboardingTemplateCard.tsx
Labels: type: fix, priority: soon, effort: 1, on stage, chromatic

#2989 refactor: journey analytics styles
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyAnalyticsCard/JourneyAnalyticsCard.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyAnalyticsCard/JourneyAnalyticsCardStat/JourneyAnalyticsCardStat.tsx
Labels: priority: soon, effort: 1, type: refactor, chromatic

#2988 refactor: step analytics typography styles
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsDataPoint/AnalyticsDataPoint.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
Labels: priority: soon, effort: 1, type: refactor, chromatic

#2990 refactor: remove hover styles in analytics mode
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNodeAnalytics/LinkNodeAnalytics.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.tsx
Labels: priority: soon, effort: 1, type: refactor, chromatic

#2991 refactor: card analytic styles
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CanvasFooter.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CardAnalytics/CardAnalytics.tsx
Labels: priority: soon, effort: 1, type: refactor, chromatic

#2983 fix: referrer styles
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/OtherReferrer/OtherReferrer.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerNode.tsx
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.spec.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformReferrers/transformReferrers.spec.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformReferrers/transformReferrers.ts
Labels: type: fix, priority: soon, effort: 1, type: refactor, chromatic

#2878 feat: use alt string parsing for ai prompts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/AIGallery/AIGallery.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/AIGallery/AIPrompt/AIPrompt.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/AIGallery/AIPrompt/AIPrompt.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/ImageBlockEditor.tsx
Labels: priority: soon, type: feat, effort: 1, chromatic

#2834 feat: default filled team names
  apps/journeys-admin/pages/teams/new.tsx
  apps/journeys-admin/src/components/Team/TeamCreateForm/TeamCreateForm.spec.tsx
  apps/journeys-admin/src/components/Team/TeamCreateForm/TeamCreateForm.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.spec.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.stories.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1, chromatic

#3025 feat: search bar ui
  apps/watch/src/components/SearchBar/SearchBar.spec.tsx
  apps/watch/src/components/SearchBar/SearchBar.stories.tsx
  apps/watch/src/components/SearchBar/SearchBar.tsx
  libs/locales/en/apps-watch.json
Labels: priority: 2day, effort: 3, type: feat, chromatic

#3033 docs: update visual test
  apps/docs/docs/03-basics/03-frontend/05-visual-testing/index.md
Labels: priority: now, type: docs, effort: 1, chromatic

#3034 refactor: templategallerycarousel to contentcarousel
  libs/journeys/ui/src/components/TemplateGallery/TagCarousels/TagCarousels.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGalleryCarousel/index.ts
  libs/journeys/ui/src/components/TemplateGalleryCard/TemplateGalleryCard.spec.tsx
  libs/journeys/ui/src/components/TemplateSections/TemplateSections.tsx
  libs/journeys/ui/src/components/TemplateView/TemplateView.tsx
  libs/shared/ui/jest.config.ts
  libs/shared/ui/src/components/ContentCarousel/ContentCarousel.spec.tsx
  libs/shared/ui/src/components/ContentCarousel/ContentCarousel.stories.tsx
  libs/shared/ui/src/components/ContentCarousel/ContentCarousel.tsx
  libs/shared/ui/src/components/ContentCarousel/NavButton/NavButton.tsx
  libs/shared/ui/src/components/ContentCarousel/NavButton/index.ts
  libs/shared/ui/src/components/ContentCarousel/index.ts
Labels: effort: 3, priority: now, type: refactor

#3036 fix: default english templates
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.tsx
Labels: type: fix, priority: soon, effort: 1, chromatic

#3002 refactor: other referrers
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/OtherReferrer/OtherReferrer.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/OtherReferrer/OtherReferrer.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerNode.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerValue/ReferrerValue.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerValue/ReferrerValue.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerValue/ReferrerValue.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerValue/index.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformReferrers/transformReferrers.spec.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformReferrers/transformReferrers.ts
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, effort: 1, type: refactor, chromatic

#3030 feat: command provider
  libs/journeys/ui/src/libs/CommandProvider/CommandProvider.spec.tsx
  libs/journeys/ui/src/libs/CommandProvider/CommandProvider.tsx
  libs/journeys/ui/src/libs/CommandProvider/index.ts
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
  validate-branch-name.config.js
Labels: priority: now, type: feat, effort: 1, chromatic

#3028 feat: add info message when unmuting autoplay videos
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/VideoBlockEditor.stories.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1, chromatic

#3019 refactor: soft delete blocks
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20240708013215_20240708013213/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/block.graphql
  apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.resolver.ts
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: effort: 5, type: fix, priority: soon, chromatic

#3042 fix: running command should immediately dispatch
  libs/journeys/ui/src/libs/CommandProvider/CommandProvider.tsx
Labels: type: fix, priority: now, effort: 1, chromatic

#3044 feat: capture undo and redo hotkeys
  apps/journeys-admin/src/components/Editor/Editor.tsx
  apps/journeys-admin/src/components/Editor/Hotkeys/Hotkeys.spec.tsx
  apps/journeys-admin/src/components/Editor/Hotkeys/Hotkeys.tsx
  apps/journeys-admin/src/components/Editor/Hotkeys/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/CommandRedoItem/ComandRedoItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/CommandRedoItem/CommandRedoItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/CommandRedoItem/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/CommandUndoItem/CommandUndoItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/CommandUndoItem/CommandUndoItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/CommandUndoItem/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/Item/Item.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/Items.tsx
  libs/locales/en/apps-journeys-admin.json
  package-lock.json
  package.json
Labels: effort: 5, priority: now, type: feat, chromatic

#3046 fix: capture the undo inside iframe
  apps/journeys-admin/src/components/Editor/Hotkeys/Hotkeys.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  libs/journeys/ui/src/components/FramePortal/FramePortal.tsx
Labels: effort: 2, type: fix, priority: now, chromatic

#3043 feat: languages audio preview
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/db/migrations/20240712025324_20240712025322/migration.sql
  apps/api-languages/db/schema.prisma
  apps/api-languages/schema.graphql
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-languages/src/__generated__/pothos-types.ts
  apps/api-languages/src/schema/language/language.mock.ts
  apps/api-languages/src/schema/language/language.spec.ts
  apps/api-languages/src/schema/language/language.ts
  apps/api-languages/src/schema/schema.ts
  apps/api-languages/src/schema/translation/index.ts
  apps/arclight/__generated__/graphql-env.d.ts
  biome.json
Labels: effort: 3, priority: soon, type: feat, on stage

#3052 feat: allow parent block to be returned from action
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/action/action.graphql
  apps/api-journeys/src/app/modules/action/action.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/action.resolver.ts
  apps/api-journeys/src/app/modules/action/emailAction/emailAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/emailAction/emailAction.resolver.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts
  apps/api-languages/schema.graphql
Labels: priority: now, type: feat, effort: 1, chromatic

#3029 feat: create node on mobile drag
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
Labels: priority: soon, type: feat, effort: 1, chromatic

#3053 chore: generate package json on prod only
  .vscode/settings.json
  apps/api-analytics/project.json
  apps/api-journeys/project.json
  apps/api-media/project.json
  apps/api-tags/project.json
  apps/api-users/project.json
  apps/api-videos/project.json
Labels: priority: now, effort: 1, type: chore, on stage, chromatic

#3055 chore: make journey id optional on action mutations
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/action/action.graphql
Labels: priority: now, effort: 1, type: chore, chromatic

#3054 feat: languages audio importer
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/db/migrations/20240713034153_20240713034151/migration.sql
  apps/api-languages/db/schema.prisma
  apps/api-languages/infrastructure/locals.tf
  apps/api-languages/project.json
  apps/api-languages/schema.graphql
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-languages/src/__generated__/pothos-types.ts
  apps/api-languages/src/bigquery/__mocks__/@google-cloud/bigquery.ts
  apps/api-languages/src/bigquery/__mocks__/bullmq.ts
  apps/api-languages/src/bigquery/console.spec.ts
  apps/api-languages/src/bigquery/console.ts
  apps/api-languages/src/bigquery/importer.spec.ts
  apps/api-languages/src/bigquery/importer.ts
  apps/api-languages/src/bigquery/importers/audioPreviews/audioPreviews.spec.ts
  apps/api-languages/src/bigquery/importers/audioPreviews/audioPreviews.ts
  apps/api-languages/src/bigquery/importers/languages/langauge.spec.ts
  apps/api-languages/src/bigquery/importers/languages/languages.ts
  apps/api-languages/src/bigquery/index.spec.ts
  apps/api-languages/src/bigquery/index.ts
  apps/api-languages/src/bigquery/queue.spec.ts
  apps/api-languages/src/bigquery/queue.ts
  apps/api-languages/src/bigquery/worker.spec.ts
  apps/api-languages/src/bigquery/worker.ts
  apps/api-languages/src/index.ts
  apps/api-languages/src/schema/language/language.mock.ts
  apps/api-languages/src/schema/language/language.spec.ts
  apps/api-languages/src/schema/language/language.ts
  package-lock.json
  package.json
Labels: effort: 8, priority: soon, type: feat, on stage

#3045 chore: nx bump
  biome.json
  package-lock.json
  package.json
Labels: priority: now, effort: 1, type: chore

#3062 fix: bad prisma migration
  apps/api-languages/db/migrations/20240713034153_20240713034151/migration.sql
Labels: type: fix, priority: now, effort: 1, on stage

#3059 fix: card preview not displaying on firefox
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
Labels: priority: 2day, type: fix, effort: 1, chromatic

#3066 fix: add key for background color
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/Card.tsx
Labels: type: fix, priority: now, effort: 1, chromatic

#3067 feat: properties editor state function
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: type: fix, priority: soon, effort: 1, chromatic

#3068 ci: remove chromatic
  .github/workflows/visual-test.yml
Labels: priority: soon, effort: 1, type: ci

#3026 fix: search bots crawl
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/Conductor/DynamicCardList/DynamicCardList.spec.tsx
  apps/journeys/src/components/Conductor/DynamicCardList/DynamicCardList.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
Labels: type: fix, priority: soon, effort: 1, chromatic

#3050 fix: team initial select
  apps/journeys-admin/pages/index.tsx
Labels: type: fix, priority: soon, effort: 1

#2982 fix: plausible stats collection
  apps/journeys/pages/[hostname]/[journeySlug].tsx
  apps/journeys/pages/[hostname]/embed/[journeySlug].tsx
  apps/journeys/pages/home/[journeySlug].tsx
  apps/journeys/pages/home/embed/[journeySlug].tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.spec.tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.spec.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
  apps/journeys/src/components/JourneyPageWrapper/JourneyPageWrapper.spec.tsx
  apps/journeys/src/components/JourneyPageWrapper/JourneyPageWrapper.tsx
  apps/journeys/src/components/JourneyPageWrapper/index.ts
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.spec.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.spec.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.tsx
  libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.spec.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.ts
Labels: type: fix, effort: 3, priority: soon

#3077 feat: add set editor focus to editor provider
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: priority: now, type: feat, effort: 1

#3020 feat: strategies page ui
  apps/watch/next.config.js
  apps/watch/pages/_app.tsx
  apps/watch/pages/strategies/index.tsx
  apps/watch/src/components/StrategySections/StrategyCard/StrategyCard.spec.tsx
  apps/watch/src/components/StrategySections/StrategyCard/StrategyCard.stories.tsx
  apps/watch/src/components/StrategySections/StrategyCard/StrategyCard.tsx
  apps/watch/src/components/StrategySections/StrategyCard/index.ts
  apps/watch/src/components/StrategySections/StrategySection/StrategySection.spec.tsx
  apps/watch/src/components/StrategySections/StrategySection/StrategySection.tsx
  apps/watch/src/components/StrategySections/StrategySection/data.ts
  apps/watch/src/components/StrategySections/StrategySection/index.ts
  apps/watch/src/components/StrategySections/StrategySections.spec.tsx
  apps/watch/src/components/StrategySections/StrategySections.tsx
  apps/watch/src/components/StrategySections/index.ts
  libs/journeys/ui/test/mocks/InstantSearchMockWrapper.tsx
  libs/journeys/ui/test/mocks/createAPIResponse.ts
  libs/journeys/ui/test/mocks/createAlgoliaSearchClient.ts
  libs/journeys/ui/test/mocks/createSearchClient.ts
  libs/locales/en/apps-watch.json
  tsconfig.base.json
Labels: effort: 3, priority: soon, type: feat

#3081 fix: plausible site creation
  apps/api-analytics/src/schema/site/siteCreate.mutation.spec.ts
  apps/api-analytics/src/schema/site/siteCreate.mutation.ts
  apps/api-journeys/src/app/modules/plausible/plausible.service.ts
Labels: effort: 2, type: fix, priority: now, on stage

#3082 ci: add autofix ci
  .github/workflows/autofix.ci.yml
  .github/workflows/main.yml
  apps/api-videos/src/libs/postgresql/postgresql.ts
  libs/nest/decorators/src/lib/TranslationField/TranslationField.ts
  libs/shared/ui/src/libs/timeFormat/timeFormat.spec.ts
  tools/scripts/check-git-status.sh
  validate-branch-name.config.js
Labels: priority: now, effort: 1, type: ci

#3001 fix: dynamic robots
  apps/journeys/next.config.js
  apps/journeys/pages/api/robots.ts
  apps/journeys/public/robots.txt
Labels: type: fix, priority: now, effort: 1, on stage

#3084 feat: use mutation link
  apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
  package-lock.json
  package.json
Labels: priority: now, type: feat, effort: 1

#3076 fix: duplicate journey error
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: priority: 2day, type: fix, effort: 1, on stage

#3069 fix: video block error
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Labels: type: fix, priority: now, effort: 1, on stage

#3048 chore: new crowdin translations
  libs/locales/am-ET/apps-journeys-admin.json
  libs/locales/am-ET/journeys-admin.json
  libs/locales/am-ET/libs-journeys-ui.json
  libs/locales/ar-SA/apps-journeys-admin.json
  libs/locales/ar-SA/apps-watch.json
  libs/locales/ar-SA/journeys-admin.json
  libs/locales/ar-SA/libs-journeys-ui.json
  libs/locales/bn-BD/apps-journeys-admin.json
  libs/locales/bn-BD/journeys-admin.json
  libs/locales/bn-BD/libs-journeys-ui.json
  libs/locales/es-ES/apps-journeys-admin.json
  libs/locales/es-ES/journeys-admin.json
  libs/locales/es-ES/libs-journeys-ui.json
  libs/locales/fr-FR/apps-journeys-admin.json
  libs/locales/fr-FR/journeys-admin.json
  libs/locales/fr-FR/libs-journeys-ui.json
  libs/locales/hi-IN/apps-journeys-admin.json
  libs/locales/hi-IN/journeys-admin.json
  libs/locales/hi-IN/libs-journeys-ui.json
  libs/locales/id-ID/apps-journeys-admin.json
  libs/locales/id-ID/journeys-admin.json
  libs/locales/id-ID/libs-journeys-ui.json
  libs/locales/ja-JP/apps-journeys-admin.json
  libs/locales/ja-JP/journeys-admin.json
  libs/locales/ja-JP/libs-journeys-ui.json
  libs/locales/my-MM/apps-journeys-admin.json
  libs/locales/my-MM/journeys-admin.json
  libs/locales/my-MM/libs-journeys-ui.json
  libs/locales/ru-RU/apps-journeys-admin.json
  libs/locales/ru-RU/journeys-admin.json
  libs/locales/ru-RU/libs-journeys-ui.json
  libs/locales/th-TH/apps-docs.json
  libs/locales/th-TH/apps-journeys-admin.json
  libs/locales/th-TH/apps-journeys.json
  libs/locales/th-TH/apps-nexus-admin.json
  libs/locales/th-TH/apps-watch.json
  libs/locales/th-TH/journeys-admin.json
  libs/locales/th-TH/libs-journeys-ui.json
  libs/locales/tl-PH/apps-journeys-admin.json
  libs/locales/tl-PH/journeys-admin.json
  libs/locales/tl-PH/libs-journeys-ui.json
  libs/locales/tr-TR/apps-journeys-admin.json
  libs/locales/tr-TR/journeys-admin.json
  libs/locales/tr-TR/libs-journeys-ui.json
  libs/locales/ur-PK/apps-journeys-admin.json
  libs/locales/ur-PK/journeys-admin.json
  libs/locales/ur-PK/libs-journeys-ui.json
  libs/locales/vi-VN/apps-journeys-admin.json
  libs/locales/vi-VN/journeys-admin.json
  libs/locales/vi-VN/libs-journeys-ui.json
  libs/locales/zh-Hans-CN/apps-journeys-admin.json
  libs/locales/zh-Hans-CN/journeys-admin.json
  libs/locales/zh-Hans-CN/libs-journeys-ui.json
  libs/locales/zh-Hant-TW/apps-journeys-admin.json
  libs/locales/zh-Hant-TW/journeys-admin.json
  libs/locales/zh-Hant-TW/libs-journeys-ui.json
Labels: priority: soon, effort: 1, type: chore, chromatic

#3086 fix: biome linter rules
  apps/__mocks__/swiper/react.tsx
  apps/api-journeys/src/app/modules/block/block.resolver.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
  apps/api-journeys/src/app/modules/event/video/video.resolver.spec.ts
  apps/api-languages/src/bigquery/importer.spec.ts
  apps/docs/src/components/FeatureList/FeatureList.tsx
  apps/docs/src/pages/index.tsx
  apps/journeys-admin-e2e/src/e2e/discover/card-level-actions.spec.ts
  apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
  apps/journeys-admin-e2e/src/pages/publisher-and-templates-page.ts
  apps/journeys-admin-e2e/src/pages/teams-page.ts
  apps/journeys-admin/pages/teams/[teamId]/integrations/new/growth-spaces.tsx
  apps/journeys-admin/pages/teams/[teamId]/integrations/new/index.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyAnalyticsCard/JourneyAnalyticsCard.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoDescription/VideoDescription.spec.tsx
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesCreateIntegration/GrowthSpacesCreateIntegration.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsChat/JourneyQuickSettingsChat.tsx
  apps/journeys-admin/src/components/Team/BreadcrumbNavigation/BreadcrumbNavigation.tsx
  apps/journeys/src/components/Conductor/HotkeyNavigation/HotkeyNavigation.spec.tsx
  apps/journeys/src/components/JourneyPageWrapper/JourneyPageWrapper.tsx
  apps/watch/src/components/Header/Header.stories.tsx
  biome.json
  dangerfile.ts
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ReactionButton/ReactionButton.spec.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareButton.spec.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.spec.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.stories.tsx
  libs/journeys/ui/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPreview.tsx
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/useJourneyAnalyticsQuery.ts
Labels: type: fix, priority: soon, effort: 1

#3090 fix: prevent same value submission
  libs/journeys/ui/src/components/TextResponse/TextResponse.spec.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
Labels: type: fix, priority: now, effort: 1

#3085 feat: thai translation
  apps/journeys-admin/middleware.ts
  apps/journeys-admin/next-i18next.config.js
  apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.spec.tsx
  apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.tsx
Labels: priority: soon, type: feat, effort: 1

#3091 fix: udpate env plausible variable name
  apps/journeys-admin/next.config.js
Labels: type: fix, priority: now, effort: 1

#3035 feat: block delete undo redo
  apps/journeys-admin-e2e/src/e2e/discover/card-level-actions.spec.ts
  apps/journeys-admin-e2e/src/pages/card-level-actions.ts
  apps/journeys-admin/__generated__/BlockRestore.ts
  apps/journeys-admin/__generated__/RestoredBlock.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DeleteBlock/DeleteBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DeleteBlock/DeleteBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteOnKeyPress/useDeleteOnKeyPress.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteOnKeyPress/useDeleteOnKeyPress.ts
  apps/journeys-admin/src/components/Editor/utils/useBlockDeleteCommand/index.ts
  apps/journeys-admin/src/components/Editor/utils/useBlockDeleteCommand/setBlockRestoreEditorState/index.ts
  apps/journeys-admin/src/components/Editor/utils/useBlockDeleteCommand/setBlockRestoreEditorState/setBlockRestoreEditorState.spec.ts
  apps/journeys-admin/src/components/Editor/utils/useBlockDeleteCommand/setBlockRestoreEditorState/setBlockRestoreEditorState.ts
  apps/journeys-admin/src/components/Editor/utils/useBlockDeleteCommand/useBlockDeleteCommand.spec.tsx
  apps/journeys-admin/src/components/Editor/utils/useBlockDeleteCommand/useBlockDeleteCommand.tsx
  apps/journeys-admin/src/libs/useBlockDeleteMutation/useBlockDeleteMutation.mock.ts
  apps/journeys-admin/src/libs/useBlockRestoreMutation/index.ts
  apps/journeys-admin/src/libs/useBlockRestoreMutation/useBlockRestoreMutation.mock.ts
  apps/journeys-admin/src/libs/useBlockRestoreMutation/useBlockRestoreMutation.spec.tsx
  apps/journeys-admin/src/libs/useBlockRestoreMutation/useBlockRestoreMutation.tsx
  libs/journeys/ui/src/libs/EditorProvider/index.ts
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: now, effort: 1

#3027 fix: swiper drawer resize position
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Fab/Fab.spec.tsx
  apps/journeys-admin/src/components/Editor/Fab/Fab.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CanvasFooter.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CardWrapper/CardWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Content.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/CardTemplates.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardCta/CardCta.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardForm/CardForm.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardIntro/CardIntro.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardPoll/CardPoll.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardQuote/CardQuote.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardVideo/CardVideo.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/Drawer.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageLibrary/ImageLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
Labels: type: fix, priority: soon, effort: 1, chromatic

#3092 refactor: remove bounce rate
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, effort: 1, type: refactor

#3087 feat: journeys search bar
  apps/journeys-admin-e2e/src/pages/template-page.ts
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewButtonButton/NewButtonButton.spec.tsx
  apps/watch/pages/journeys/index.tsx
  apps/watch/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.stories.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
  libs/journeys/ui/src/components/SearchBar/index.ts
  libs/journeys/ui/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.spec.tsx
  libs/journeys/ui/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.tsx
  libs/journeys/ui/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.spec.tsx
  libs/journeys/ui/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.tsx
  libs/journeys/ui/src/components/TemplateGallery/TagCarousels/TagCarousels.spec.tsx
  libs/journeys/ui/src/components/TemplateGallery/TagCarousels/TagCarousels.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.spec.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.tsx
  libs/journeys/ui/src/components/TemplateGallery/data.ts
  libs/journeys/ui/src/components/TemplateGalleryCard/TemplateGalleryCard.spec.tsx
  libs/journeys/ui/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
  libs/journeys/ui/src/components/TemplateSections/TemplateSections.spec.tsx
  libs/journeys/ui/src/components/TemplateSections/TemplateSections.stories.tsx
  libs/journeys/ui/src/components/TemplateSections/TemplateSections.tsx
  libs/journeys/ui/src/libs/algolia/algoliaJourneyUtils/algoliaJourneyUtils.spec.ts
  libs/journeys/ui/src/libs/algolia/algoliaJourneyUtils/algoliaJourneyUtils.ts
  libs/journeys/ui/src/libs/algolia/algoliaJourneyUtils/index.ts
  libs/journeys/ui/src/libs/algolia/useAlgoliaJourneys/data.ts
  libs/journeys/ui/src/libs/algolia/useAlgoliaJourneys/index.ts
  libs/journeys/ui/src/libs/algolia/useAlgoliaJourneys/useAlgoliaJourneys.spec.ts
  libs/journeys/ui/src/libs/algolia/useAlgoliaJourneys/useAlgoliaJourneys.ts
  libs/locales/en/apps-watch.json
  libs/locales/en/libs-journeys-ui.json
  libs/shared/ui/src/libs/storybook/config.tsx
  libs/shared/ui/src/libs/storybook/index.ts
Labels: effort: 5, priority: soon, type: feat

#3038 feat: typography block properties undo
  apps/journeys-admin/__generated__/TypographyBlockUpdateAlign.ts
  apps/journeys-admin/__generated__/TypographyBlockUpdateColor.ts
  apps/journeys-admin/__generated__/TypographyBlockUpdateVariant.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Align/Align.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Align/Align.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Color/Color.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Color/Color.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Variant/Variant.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Variant/Variant.tsx
Labels: priority: now, type: feat, effort: 1, chromatic

#3073 feat: add undo radio option text label
  apps/journeys-admin/__generated__/RadioOptionBlockUpdateContent.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.tsx
Labels: priority: soon, type: feat, effort: 1

#3095 feat: add searchbar to strategies page, create resourceheading component
  apps/watch/pages/strategies/index.tsx
  apps/watch/src/components/ResourceHeading/ResourceHeading.spec.tsx
  apps/watch/src/components/ResourceHeading/ResourceHeading.stories.tsx
  apps/watch/src/components/ResourceHeading/ResourceHeading.tsx
  apps/watch/src/components/ResourceHeading/index.ts
  apps/watch/src/components/StrategiesView/StrategiesView.spec.tsx
  apps/watch/src/components/StrategiesView/StrategiesView.tsx
  apps/watch/src/components/StrategiesView/index.ts
  apps/watch/src/components/StrategySections/StrategySection/StrategySection.spec.tsx
  apps/watch/src/components/StrategySections/StrategySection/StrategySection.tsx
  apps/watch/src/components/StrategySections/StrategySections.spec.tsx
  apps/watch/src/components/StrategySections/StrategySections.tsx
  libs/locales/en/apps-watch.json
Labels: effort: 3, priority: soon, type: feat

#3060 feat: new videos subtitles importer
  apps/api-videos/db/migrations/20240716202927_20240716202925/migration.sql
  apps/api-videos/db/schema.prisma
  apps/api-videos/src/app/modules/bigQuery/bigQuery.console.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.spec.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.module.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.queue.spec.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.queue.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.service.spec.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.service.ts
  apps/api-videos/src/app/modules/importer/importer.module.ts
  apps/api-videos/src/app/modules/importer/importer.service.ts
  apps/api-videos/src/app/modules/importer/importerVideoSubtitle/importerVideoSubtitle.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerVideoSubtitle/importerVideoSubtitle.service.ts
  apps/api-videos/src/app/modules/importer/importerVideoVariants/importerVideoVariants.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerVideoVariants/importerVideoVariants.service.ts
  apps/api-videos/src/app/modules/importer/importerVideos/importerVideos.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerVideos/importerVideos.service.ts
  apps/api-videos/src/app/modules/importer/videos/videos.service.spec.ts
  apps/api-videos/src/app/modules/importer/videos/videos.service.ts
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/libs/arclight/arclight.spec.ts
  apps/api-videos/src/libs/arclight/arclight.ts
  apps/api-videos/src/libs/postgresql/postgresql.ts
  apps/api-videos/src/libs/slugify/slugify.ts
Labels: effort: 8, priority: soon, type: feat, on stage

#3104 fix: resize image used for blurhash
  apps/api-journeys/src/app/modules/block/image/transformInput.spec.ts
  apps/api-journeys/src/app/modules/block/image/transformInput.ts
Labels: type: fix, priority: now, effort: 1

#3109 fix: sourcemap uploading
  .github/workflows/app-deploy.yml
  .github/workflows/ecs-frontend-deploy-prod-worker.yml
  .github/workflows/ecs-frontend-deploy-stage-worker.yml
  apps/arclight/project.json
  apps/journeys-admin/project.json
  apps/journeys/project.json
  apps/nexus-admin/project.json
  apps/watch/project.json
Labels: type: fix, priority: now, effort: 1

#3063 feat: bible citation importer
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.spec.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.ts
  apps/api-videos/src/app/modules/importer/importer.module.ts
  apps/api-videos/src/app/modules/importer/importer.service.ts
  apps/api-videos/src/app/modules/importer/importerBibleBookNames/importerBibleBookNames.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerBibleBookNames/importerBibleBookNames.service.ts
  apps/api-videos/src/app/modules/importer/importerBibleBooks/importerBibleBooks.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerBibleBooks/importerBibleBooks.service.ts
  apps/api-videos/src/app/modules/importer/importerBibleCitations/importerBibleCitations.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerBibleCitations/importerBibleCitations.service.ts
Labels: priority: 2day, effort: 5, type: feat, on stage

#3108 feat: use journeys hook
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.spec.tsx
  libs/journeys/ui/src/libs/algolia/useAlgoliaJourneys/data.ts
  libs/journeys/ui/src/libs/algolia/useAlgoliaJourneys/useAlgoliaJourneys.spec.ts
  libs/journeys/ui/src/libs/algolia/useAlgoliaJourneys/useAlgoliaJourneys.ts
Labels: priority: soon, type: feat, effort: 1

#3111 fix: apollo cache changes
  apps/journeys-admin/__generated__/BlockRestore.ts
  apps/journeys-admin/src/components/Editor/utils/useBlockDeleteCommand/useBlockDeleteCommand.tsx
  apps/journeys-admin/src/libs/useBlockRestoreMutation/useBlockRestoreMutation.mock.ts
  apps/journeys-admin/src/libs/useBlockRestoreMutation/useBlockRestoreMutation.spec.tsx
  apps/journeys-admin/src/libs/useBlockRestoreMutation/useBlockRestoreMutation.tsx
Labels: type: fix, priority: soon, effort: 1, chromatic

#3083 feat: card properties undo part1
  apps/journeys-admin/__generated__/CardBlockBackgroundColorUpdate.ts
  apps/journeys-admin/__generated__/CardBlockLayoutUpdate.ts
  apps/journeys-admin/__generated__/CardBlockThemeModeUpdate.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundColor/BackgroundColor.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundColor/DebouncedHexColorPicker/DebouncedHexColorPicker.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundColor/DebouncedHexColorPicker/DebouncedHexColorPicker.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundColor/DebouncedHexColorPicker/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardLayout/CardLayout.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardLayout/CardLayout.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardStyling/CardStyling.tsx
Labels: effort: 2, priority: soon, type: feat

#3100 fix: template initial filter
  libs/journeys/ui/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.spec.tsx
  libs/journeys/ui/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.spec.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.tsx
Labels: priority: soon, type: feat, effort: 1

#3102 refactor: flow bg color
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
Labels: priority: soon, effort: 1, type: refactor

#3107 feat: add style for button small variant
  apps/journeys-admin/src/components/OnboardingPanel/OnboardingPanel.tsx
  libs/shared/ui/src/libs/themes/journeysAdmin/tokens/components.ts
Labels: priority: soon, type: feat, effort: 1

#3106 feat: bible citation endpoints
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/app.module.ts
  apps/api-videos/src/app/modules/bibleBook/bibleBook.graphql
  apps/api-videos/src/app/modules/bibleBook/bibleBook.module.ts
  apps/api-videos/src/app/modules/bibleBook/bibleBook.resolver.spec.ts
  apps/api-videos/src/app/modules/bibleBook/bibleBook.resolver.ts
  apps/api-videos/src/app/modules/bibleCitation/bibleCitation.graphql
  apps/api-videos/src/app/modules/bibleCitation/bibleCitation.module.ts
  apps/api-videos/src/app/modules/bibleCitation/bibleCitation.resolver.spec.ts
  apps/api-videos/src/app/modules/bibleCitation/bibleCitation.resolver.ts
  apps/api-videos/src/app/modules/importer/importerBibleBookNames/importerBibleBookNamess.service.spec.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
Labels: effort: 5, priority: soon, type: feat, on stage

#3120 fix: video subtitle primary field
  apps/api-videos/src/app/modules/importer/importerVideoSubtitle/importerVideoSubtitle.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerVideoSubtitle/importerVideoSubtitle.service.ts
Labels: type: fix, priority: now, effort: 1

#3121 refactor: plausible env
  apps/journeys-admin/next.config.js
Labels: priority: now, effort: 1, type: refactor

#3117 feat: bigquery videos infrastructure
  apps/api-videos/infrastructure/locals.tf
Labels: priority: now, type: feat, effort: 1

#3112 feat: testing algolia
  apps/watch/src/components/StrategiesView/StrategiesView.spec.tsx
  apps/watch/src/components/StrategiesView/StrategiesView.tsx
  apps/watch/src/components/StrategySections/StrategySections.spec.tsx
  apps/watch/src/components/StrategySections/StrategySections.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.stories.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.stories.tsx
  libs/journeys/ui/src/components/TemplateSections/TemplateSections.stories.tsx
  libs/journeys/ui/src/libs/algolia/InstantSearchWrapper.tsx
  libs/journeys/ui/test/mocks/InstantSearchMockWrapper.tsx
  libs/journeys/ui/test/mocks/createAPIResponse.ts
  libs/journeys/ui/test/mocks/createAlgoliaSearchClient.ts
  libs/journeys/ui/test/mocks/createSearchClient.ts
  libs/shared/ui/src/libs/storybook/config.tsx
Labels: type: test, priority: 2day, effort: 2

#3110 feat: email thumbnail clickable
  apps/api-journeys/src/app/emails/templates/JourneyAccessRequest/JourneyAccessRequest.tsx
  apps/api-journeys/src/app/emails/templates/JourneyShared/JourneyShared.tsx
  apps/api-journeys/src/app/emails/templates/JourneyShared/JourneySharedNoAccount/JourneySharedNoAccount.tsx
  libs/nest/common/src/lib/email/components/ActionCard/ActionJourneyView/ActionJourneyView.tsx
Labels: priority: soon, type: feat, effort: 1, on stage

#3114 fix: team refetch
  apps/journeys-admin/pages/index.tsx
  libs/journeys/ui/src/components/TeamProvider/TeamProvider.spec.tsx
  libs/journeys/ui/src/components/TeamProvider/TeamProvider.tsx
Labels: type: fix, priority: soon, effort: 1

#3118 feat: emptysearch component
  apps/watch/src/components/StrategySections/StrategySection/StrategySection.spec.tsx
  apps/watch/src/components/StrategySections/StrategySection/StrategySection.tsx
  apps/watch/src/components/StrategySections/StrategySections.spec.tsx
  apps/watch/src/components/StrategySections/StrategySections.tsx
  libs/journeys/ui/src/components/EmptySearch/EmptySearch.spec.tsx
  libs/journeys/ui/src/components/EmptySearch/EmptySearch.stories.tsx
  libs/journeys/ui/src/components/EmptySearch/EmptySearch.tsx
  libs/journeys/ui/src/components/EmptySearch/index.ts
  libs/journeys/ui/src/components/TemplateSections/TemplateSections.spec.tsx
  libs/journeys/ui/src/components/TemplateSections/TemplateSections.tsx
  libs/locales/en/libs-journeys-ui.json
Labels: effort: 3, priority: soon, type: feat

#3078 fix: mobile typography saves clicking away to canvas
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/useOnClickOutside/useOnClickOutside.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/useOnClickOutside/useOnClickOutside.tsx
Labels: priority: 2day, type: fix, effort: 1

#3124 refactor: instant search test wrapper
  libs/journeys/ui/src/components/SearchBar/SearchBar.stories.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.stories.tsx
  libs/journeys/ui/src/components/TemplateSections/TemplateSections.stories.tsx
  libs/journeys/ui/src/libs/algolia/InstantSearchTestWrapper.tsx
Labels: priority: soon, effort: 1, type: refactor

#3131 fix: rename labels
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyAnalyticsCard/JourneyAnalyticsCard.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyAnalyticsCard/JourneyAnalyticsCard.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1, chromatic

#3125 fix: linear branch name change
  validate-branch-name.config.js
Labels: type: fix, priority: now, effort: 1, chromatic

#3088 feat: plausible embed dashboard
  apps/journeys-admin/__generated__/GetAdminJourneyWithPlausibleToken.ts
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/pages/reports/journeys.tsx
  apps/journeys-admin/pages/reports/visitors.tsx
  apps/journeys-admin/public/plausible.css
  apps/journeys-admin/src/components/PlausibleEmbedDashboard/PlausibleEmbedDashboard.spec.tsx
  apps/journeys-admin/src/components/PlausibleEmbedDashboard/PlausibleEmbedDashboard.stories.tsx
  apps/journeys-admin/src/components/PlausibleEmbedDashboard/PlausibleEmbedDashboard.tsx
  apps/journeys-admin/src/components/PlausibleEmbedDashboard/index.ts
  apps/journeys-admin/src/components/ReportsNavigation/NavigationButton/NavigationButton.spec.tsx
  apps/journeys-admin/src/components/ReportsNavigation/NavigationButton/NavigationButton.stories.tsx
  apps/journeys-admin/src/components/ReportsNavigation/NavigationButton/NavigationButton.tsx
  apps/journeys-admin/src/components/ReportsNavigation/NavigationButton/index.ts
  apps/journeys-admin/src/components/ReportsNavigation/ReportsNavigation.spec.tsx
  apps/journeys-admin/src/components/ReportsNavigation/ReportsNavigation.stories.tsx
  apps/journeys-admin/src/components/ReportsNavigation/ReportsNavigation.tsx
Labels: effort: 3, priority: soon, type: feat

#3135 fix: ecs frontend deploy
  .github/workflows/ecs-frontend-deploy-prod-worker.yml
  .github/workflows/ecs-frontend-deploy-prod.yml
  .github/workflows/ecs-frontend-deploy-stage-worker.yml
  .github/workflows/ecs-frontend-deploy-stage.yml
Labels: type: fix, priority: now, effort: 1, on stage

#3129 fix: signup count
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.spec.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.ts
Labels: type: fix, priority: soon, effort: 1

#2835 fix: remove edit and done states in fab
  apps/journeys-admin/src/components/Editor/Fab/Fab.spec.tsx
  apps/journeys-admin/src/components/Editor/Fab/Fab.stories.tsx
  apps/journeys-admin/src/components/Editor/Fab/Fab.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CanvasFooter.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsList.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsListItem/GoalListItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewButtonButton/NewButtonButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewFormButton/NewFormButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewTypographyButton/NewTypographyButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Credentials/Credentials.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/Step.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/ActionCards/ActionCards.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/GoalDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Slider.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/StrategyItem/StrategyItem.spec.tsx
  apps/journeys-admin/src/components/Editor/utils/useBlockDeleteCommand/useBlockDeleteCommand.tsx
  apps/journeys-admin/src/libs/TestEditorState/TestEditorState.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
  libs/journeys/ui/src/libs/EditorProvider/index.ts
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#3137 fix: custom journey url showing everywhere
  apps/journeys-admin/src/components/Editor/Slider/Content/Content.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/Message/Message.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/Message/Message.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/EmbedJourneyDialog/EmbedJourneyDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/EmbedJourneyDialog/EmbedJourneyDialog.tsx
Labels: priority: 2day, type: fix, effort: 1

#3119 feat: videos new subtitle logic
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.ts
  apps/api-videos/src/app/modules/importer/importerVideoVariants/importerVideoVariants.service.ts
  apps/api-videos/src/app/modules/video/video.graphql
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
  apps/api-videos/src/app/modules/videoVariant/videoVariant.resolver.spec.ts
  apps/api-videos/src/app/modules/videoVariant/videoVariant.resolver.ts
Labels: effort: 5, priority: soon, type: feat, on stage

#3138 feat: videos seed temporary
  apps/api-videos/db/seed.ts
  apps/api-videos/src/libs/arclight/arclight.ts
  apps/api-videos/src/libs/postgresql/postgresql.ts
Labels: priority: soon, type: feat, effort: 1

#3139 feat: new ingest docs
  apps/docs/docs/02-getting-started/03-microservice-databases.mdx
Labels: priority: soon, type: feat, effort: 1

#3134 feat: new editor state
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
  libs/journeys/ui/src/libs/searchBlocks/searchBlocks.spec.ts
  libs/journeys/ui/src/libs/searchBlocks/searchBlocks.ts
Labels: type: fix, priority: now, effort: 1

#3141 fix: algolia journey language
  apps/watch/src/components/StrategiesView/StrategiesView.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.spec.tsx
  libs/journeys/ui/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.spec.tsx
  libs/journeys/ui/src/components/TemplateGallery/TagCarousels/TagCarousels.spec.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.spec.tsx
  libs/journeys/ui/src/components/TemplateGalleryCard/TemplateGalleryCard.spec.tsx
  libs/journeys/ui/src/components/TemplateSections/TemplateSections.spec.tsx
  libs/journeys/ui/src/libs/algolia/algoliaJourneyUtils/algoliaJourneyUtils.spec.ts
  libs/journeys/ui/src/libs/algolia/useAlgoliaJourneys/data.ts
  libs/journeys/ui/src/libs/algolia/useAlgoliaJourneys/useAlgoliaJourneys.mock.ts
  libs/journeys/ui/src/libs/algolia/useAlgoliaJourneys/useAlgoliaJourneys.spec.ts
  libs/journeys/ui/src/libs/algolia/useAlgoliaJourneys/useAlgoliaJourneys.spec.tsx
  libs/journeys/ui/src/libs/algolia/useAlgoliaJourneys/useAlgoliaJourneys.ts
  libs/journeys/ui/src/libs/useLanguagesQuery/useLanguageQuery.mock.ts
  libs/journeys/ui/src/libs/useLanguagesQuery/useLanguagesQuery.spec.tsx
Labels: type: fix, effort: 3, priority: soon

#3140 feat: video source undo
  apps/journeys-admin/__generated__/BlockDeleteForPosterImage.ts
  apps/journeys-admin/__generated__/ListUnsplashCollectionPhotos.ts
  apps/journeys-admin/__generated__/PosterImageBlockCreate.ts
  apps/journeys-admin/__generated__/PosterImageBlockDelete.ts
  apps/journeys-admin/__generated__/PosterImageBlockRestore.ts
  apps/journeys-admin/__generated__/PosterImageBlockUpdate.ts
  apps/journeys-admin/__generated__/SearchUnsplashPhotos.ts
  apps/journeys-admin/__generated__/UpdateVideoBlockNextStep.ts
  apps/journeys-admin/__generated__/VideoBlockPosterImageUpdate.ts
  apps/journeys-admin/__generated__/VideoBlockUpdate.ts
  apps/journeys-admin/src/components/Editor/Hotkeys/Hotkeys.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/AIGallery/AIGallery.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/AIGallery/AIGallery.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/CustomImage/CustomImage.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/CustomImage/CustomUrl/CustomUrl.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/CustomImage/CustomUrl/CustomUrl.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/ImageBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/ImageBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/UnsplashCollections/UnsplashCollections.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/UnsplashCollections/UnsplashCollections.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/UnsplashGallery.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/UnsplashGallery.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/UnsplashGallery.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/UnsplashList/UnsplashList.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/UnsplashList/UnsplashList.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/UnsplashSearch/UnsplashSearch.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/UnsplashSearch/UnsplashSearch.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/data.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockHeader/ImageBlockHeader.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockHeader/ImageBlockHeader.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockHeader/ImageBlockHeader.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockThumbnail/ImageBlockThumbnail.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockThumbnail/ImageBlockThumbnail.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageEdit/ImageEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageLibrary/ImageLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageLibrary/ImageLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageLibrary/ImageLibrary.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageSource/ImageSource.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageSource/ImageSource.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.spec.tsx
  apps/journeys-admin/src/components/ThemeProvider/ThemeProvider.tsx
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.ts
  apps/journeys-admin/src/libs/useBlockRestoreMutation/index.ts
  apps/journeys-admin/src/libs/useBlockRestoreMutation/useBlockRestoreMutation.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, type: feat, effort: 1

#3142 feat: image source undo
  apps/journeys-admin/__generated__/ImageBlockUpdate.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Options/ImageOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Options/ImageOptions.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Options/index.ts
Labels: priority: now, type: feat, effort: 1

#3145 refactor: consolidate all action resolvers into one
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/action/action.graphql
  apps/api-journeys/src/app/modules/action/action.module.ts
  apps/api-journeys/src/app/modules/action/action.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/action.resolver.ts
  apps/api-journeys/src/app/modules/action/action.service.spec.ts
  apps/api-journeys/src/app/modules/action/action.service.ts
  apps/api-journeys/src/app/modules/action/emailAction/emailAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/emailAction/emailAction.resolver.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts
Labels: effort: 2, priority: soon, type: refactor, on stage

#3122 feat: search bar background
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.tsx
Labels: priority: 2day, type: fix, effort: 1

#3149 feat: gateway stdout logging
  apps/api-gateway/router.prod.yaml
Labels: priority: now, type: feat, effort: 1, on stage

#3146 feat: allow cover block id on card block update
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/card/card.graphql
  apps/api-journeys/src/app/modules/block/card/card.resolver.spec.ts
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: priority: now, type: feat, effort: 1

#3151 fix: social media crawl
  apps/journeys/pages/api/robots.ts
Labels: type: fix, priority: now, effort: 1

#3093 feat: bounce rate threshold
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsDataPoint/AnalyticsDataPoint.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 5, type: fix, priority: soon

#3021 feat: social preview analytic styles
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
Labels: priority: soon, type: feat, effort: 1, chromatic

#3155 feat: algolia insights
  apps/watch/src/components/StrategySections/StrategyCard/StrategyCard.spec.tsx
  apps/watch/src/components/StrategySections/StrategyCard/StrategyCard.tsx
  apps/watch/src/components/StrategySections/StrategySection/StrategySection.tsx
Labels: priority: 2day, type: feat, effort: 1

#3158 chore: update router
  .devcontainer/post-create-command.sh
  apps/api-gateway/Dockerfile
  apps/api-gateway/router.prod.yaml
  apps/api-gateway/router.yaml
  apps/api-gateway/routerSchema.json
Labels: priority: now, effort: 1, type: chore, on stage

#3039 refactor: redirect to templates
  apps/journeys-admin/pages/templates/[journeyId].tsx
Labels: priority: soon, effort: 1, type: refactor

#3126 feat: languages bq import
  apps/api-languages/db/Dockerfile
  apps/api-languages/db/migrations/20240726202219_20240726202217/migration.sql
  apps/api-languages/db/schema.prisma
  apps/api-languages/db/seed.ts
  apps/api-languages/infrastructure/main.tf
  apps/api-languages/project.json
  apps/api-languages/schema.graphql
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-languages/src/__generated__/pothos-types.ts
  apps/api-languages/src/bigquery/importers/countries/countries.spec.ts
  apps/api-languages/src/bigquery/importers/countries/countries.ts
  apps/api-languages/src/bigquery/importers/countryLanguages/countryLanguages.spec.ts
  apps/api-languages/src/bigquery/importers/countryLanguages/countryLanguages.ts
  apps/api-languages/src/bigquery/importers/countryNames/countryNames.spec.ts
  apps/api-languages/src/bigquery/importers/countryNames/countryNames.ts
  apps/api-languages/src/bigquery/importers/languageNames/languageNames.spec.ts
  apps/api-languages/src/bigquery/importers/languageNames/languageNames.ts
  apps/api-languages/src/bigquery/importers/languages/langauge.spec.ts
  apps/api-languages/src/bigquery/importers/languages/languages.ts
  apps/api-languages/src/bigquery/worker.spec.ts
  apps/api-languages/src/bigquery/worker.ts
  apps/api-languages/src/schema/continent/continent.ts
  apps/api-languages/src/schema/continent/index.ts
  apps/api-languages/src/schema/country/countries.spec.ts
  apps/api-languages/src/schema/country/country.mock.ts
  apps/api-languages/src/schema/country/country.spec.ts
  apps/api-languages/src/schema/country/country.ts
  apps/api-languages/src/schema/countryLanguage/countryLanguage.ts
  apps/api-languages/src/schema/countryLanguage/index.ts
  apps/api-languages/src/schema/language/language.mock.ts
  apps/api-languages/src/schema/language/language.spec.ts
  apps/api-languages/src/schema/language/language.ts
  apps/api-languages/src/schema/language/languages.spec.ts
  apps/api-languages/src/schema/schema.ts
  apps/api-languages/src/schema/translation/index.ts
  infrastructure/modules/aws/eks/main.tf
Labels: priority: 2day, effort: 8, type: feat, on stage

#3157 feat: insights watch
  apps/watch/pages/watch/[part1]/[part2].tsx
  apps/watch/src/components/VideoCard/VideoCard.spec.tsx
  apps/watch/src/components/VideoCard/VideoCard.tsx
Labels: priority: 2day, type: feat, effort: 1

#3115 feat: add importer keywords service
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.spec.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.ts
  apps/api-videos/src/app/modules/importer/importer.module.ts
  apps/api-videos/src/app/modules/importer/importerKeywords/importerKeywords.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerKeywords/importerKeywords.service.ts
Labels: effort: 3, priority: soon, type: feat

#3160 feat: renovate
  renovate.json
Labels: priority: soon, type: feat, effort: 1

#3162 fix: restore resolver should also return siblings
  apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.resolver.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#3170 fix: language name for selector
  apps/api-languages/src/bigquery/importers/languageNames/languageNames.ts
  apps/api-languages/src/schema/language/language.spec.ts
  apps/api-languages/src/schema/language/language.ts
  apps/api-languages/src/schema/language/languages.spec.ts
Labels: effort: 2, type: fix, priority: now, on stage
