Repository JesusFilm/core, pull requests merged in 2024-11, with the labels that each got.

#3924 feat: eng 1189 slow host creation and editing
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Host/HostForm/HostForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Host/HostForm/HostForm.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Host/HostForm/HostLocationFieldForm/HostLocationFieldForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Host/HostForm/HostLocationFieldForm/HostLocationFieldForm.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Host/HostForm/HostTitleFieldForm/HostTitleFieldForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Host/HostForm/HostTitleFieldForm/HostTitleFieldForm.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsChat/JourneyQuickSettingsChat.tsx
  apps/journeys-admin/src/libs/useHostCreate/index.ts
  apps/journeys-admin/src/libs/useHostCreate/useHostCreate.mocks.ts
  apps/journeys-admin/src/libs/useHostCreate/useHostCreate.spec.tsx
  apps/journeys-admin/src/libs/useHostCreate/useHostCreate.ts
  apps/journeys-admin/src/libs/useUpdateJourneyHostMutation/useUpdateJourneyHostMutation.mock.ts
  libs/journeys/ui/src/libs/JourneyProvider/JourneyProvider.mock.ts
  libs/journeys/ui/src/libs/JourneyProvider/JourneyProvider.spec.tsx
Labels: priority: 2day, good first issue, effort: 3, type: feat

#3942 chore: nx update 20.0.7
  jest.config.ts
  nx.json
  package-lock.json
  package.json
Labels: priority: 2day, effort: 1, type: chore

#3986 chore: new crowdin translations
  libs/locales/ru-RU/apps-journeys-admin.json
Labels: priority: soon, effort: 1, type: chore

#3946 chore: add korean to journeys admin
  apps/journeys-admin/middleware.ts
  apps/journeys-admin/next-i18next.config.js
Labels: priority: 2day, effort: 1, type: chore

#3993 fix: custom domain journey query
  apps/journeys/pages/[hostname]/[journeySlug]/[stepSlug].tsx
Labels: type: fix, priority: soon, effort: 1, on stage, Bug

#4032 refactor: increase flow min zoom
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
Labels: priority: now, effort: 1, type: refactor

#3934 feat: color hex validation
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundColor/BackgroundColor.tsx
  apps/journeys-admin/src/components/TextFieldForm/TextFieldForm.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#3992 fix: remove non host filter
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: type: fix, priority: soon, effort: 1, on stage, Bug

#4105 fix: pass jwt to backend
  apps/videos-admin/src/app/[locale]/_ApolloProvider/ApolloProvider.tsx
  apps/videos-admin/src/app/[locale]/layout.tsx
Labels: type: fix, effort: 3, priority: soon, Bug

#4007 chore: new crowdin translations
  libs/locales/am-ET/apps-journeys-admin.json
  libs/locales/ar-SA/apps-journeys-admin.json
  libs/locales/bn-BD/apps-journeys-admin.json
  libs/locales/es-ES/apps-journeys-admin.json
  libs/locales/fr-FR/apps-journeys-admin.json
  libs/locales/hi-IN/apps-journeys-admin.json
  libs/locales/id-ID/apps-journeys-admin.json
  libs/locales/ja-JP/apps-journeys-admin.json
  libs/locales/ko-KR/apps-journeys-admin.json
  libs/locales/my-MM/apps-journeys-admin.json
  libs/locales/ru-RU/apps-journeys-admin.json
  libs/locales/ru-RU/apps-journeys.json
  libs/locales/ru-RU/apps-videos-admin.json
  libs/locales/ru-RU/apps-watch.json
  libs/locales/ru-RU/journeys-admin.json
  libs/locales/ru-RU/libs-journeys-ui.json
  libs/locales/th-TH/apps-journeys-admin.json
  libs/locales/tl-PH/apps-journeys-admin.json
  libs/locales/tr-TR/apps-journeys-admin.json
  libs/locales/ur-PK/apps-journeys-admin.json
  libs/locales/vi-VN/apps-journeys-admin.json
  libs/locales/zh-Hans-CN/apps-journeys-admin.json
  libs/locales/zh-Hant-TW/apps-journeys-admin.json
Labels: priority: soon, effort: 1, type: chore

#4226 fix: update i18n base parser config
  i18next-parser.config.base.js
Labels: type: fix, priority: now, effort: 1

#4233 chore: drop dnd
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/edit/Section/Section.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/edit/Tabs/TabContainer/TabContainer.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/edit/Variants/Downloads/Downloads.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/edit/Variants/VariantCard/VariantCard.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/edit/Variants/VariantCard/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/edit/Variants/VariantModal/VariantModal.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/edit/Variants/VariantModal/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/edit/Variants/Variants.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoList.tsx
  apps/videos-admin/src/libs/useAdminVideo/index.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.tsx
Labels: priority: soon, effort: 1, type: chore

#3918 fix: two posters for youtube video
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/YouTubeDetails/YouTubeDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/YouTubeDetails/YouTubeDetails.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: type: fix, priority: now, effort: 1

#4247 feat: increased zoom out
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
Labels: priority: soon, type: feat, effort: 1

#4255 fix: padding and sizing of link nodes
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/sizes.ts
Labels: type: fix, priority: soon, effort: 1, chromatic

#4254 fix: video poster image size
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/YouTubeDetails/YouTubeDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/YouTubeDetails/YouTubeDetails.tsx
Labels: type: fix, priority: now, effort: 1

#4257 fix: disable journey card after click
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
Labels: type: fix, priority: now, effort: 1

#4249 fix: add loading state when deleting a journey
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DeleteJourneyDialog/DeleteJourneyDialog.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/TrashJourneyDialog/TrashJourneyDialog.tsx
Labels: type: fix, priority: now, effort: 1

#3919 fix: add menu icon button select improvements
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Menu/MenuIconSelect/MenuIconSelect.tsx
Labels: type: fix, priority: soon, effort: 1, chromatic

#4277 fix: seo issues on videos page
  apps/watch/pages/watch/[part1]/[part2].tsx
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideoGrid/AlgoliaVideoGrid/AlgoliaVideoGrid.tsx
  apps/watch/src/components/VideoGrid/VideoGrid.tsx
Labels: effort: 2, type: fix, priority: now

#4265 feat: parameters for media components
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/[languageId]/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/route.ts
  apps/arclight/src/app/v2/media-components/route.ts
  apps/arclight/src/lib/stringsForArclight/webEmbedStrings.ts
Labels: effort: 3, priority: soon, type: feat

#4284 fix: update study questions UI on dnd
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/Metadata.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestions/StudyQuestions.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestions/StudyQuestions.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestions/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestionsList/StudyQuestionsList.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestionsList/StudyQuestionsList.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestionsList/StudyQuestionsList.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestionsList/data.mock.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestionsList/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/OrderedItem/OrderedItem.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/OrderedList/OrderedList.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/Actions/Actions.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/Actions/index.ts
  apps/videos-admin/src/components/OrderedList/OrderedItem/DropDown/DropDown.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/DropDown/index.ts
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.spec.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.stories.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/index.ts
  apps/videos-admin/src/components/OrderedList/OrderedList.spec.tsx
  apps/videos-admin/src/components/OrderedList/OrderedList.stories.tsx
  apps/videos-admin/src/components/OrderedList/OrderedList.tsx
  apps/videos-admin/src/components/OrderedList/index.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.tsx
  package-lock.json
Labels: effort: 2, type: fix, priority: soon

#3948 docs: translation process modern
  apps/docs/docs/04-engineering-practices/03-internationalization/02-implementation/02-supported-languages.md
  apps/docs/docs/04-engineering-practices/03-internationalization/02-implementation/crowdin-translations.png
  apps/docs/docs/04-engineering-practices/03-internationalization/02-implementation/index.md
  apps/docs/docs/04-engineering-practices/03-internationalization/03-translations-tag.md
  apps/docs/docs/04-engineering-practices/03-internationalization/04-crowdin-translation-workflow.md
  apps/docs/docs/04-engineering-practices/03-internationalization/index.md
  apps/docs/docs/04-engineering-practices/03-internationalization/translation-process.md
Labels: effort: 2, type: docs, priority: soon

#4221 chore: move arclight to aws
  .github/workflows/ecs-frontend-deploy-prod.yml
  .github/workflows/ecs-frontend-deploy-stage.yml
  apps/arclight/Dockerfile
  apps/arclight/infrastructure/locals.tf
  apps/arclight/infrastructure/main.tf
  apps/arclight/infrastructure/variables.tf
  apps/arclight/next.config.js
  infrastructure/data.tf
  infrastructure/environments/prod/data.tf
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/data.tf
  infrastructure/environments/stage/main.tf
  infrastructure/modules/aws/data.tf
  infrastructure/modules/aws/main.tf
Labels: effort: 5, priority: soon, type: chore, on stage

#3667 feat: background image focal point
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/FocalPoint/FocalPoint.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/FocalPoint/FocalPoint.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/FocalPoint/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/FocalPoint/utils/calculatePoint/calculatePoint.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/FocalPoint/utils/calculatePoint/calculatePoint.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/FocalPoint/utils/calculatePoint/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/FocalPoint/utils/clampPosition/clampPosition.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/FocalPoint/utils/clampPosition/clampPosition.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/FocalPoint/utils/clampPosition/index.ts
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: soon, type: feat

#4300 feat: add edit provider to get isedit value
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/EditProvider.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/EditProvider.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/TestEditProvider/TestEditProvider.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/TestEditProvider/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/layout.tsx
Labels: type: fix, priority: soon, effort: 1

#4285 feat: add params mediacountries
  apps/arclight/src/app/v2/media-countries/[countryId]/route.ts
  apps/arclight/src/app/v2/media-countries/route.ts
  apps/arclight/src/app/v2/media-country-links/route.ts
Labels: priority: soon, type: feat, effort: 1

#4305 fix: disable study questions when not in edit mode
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestionsList/StudyQuestionsList.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/Actions/Actions.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/DropDown/DropDown.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.tsx
  apps/videos-admin/src/components/OrderedList/OrderedList.tsx
Labels: type: fix, priority: soon, effort: 1

#4075 chore: eslint-love 84
  apps/api-journeys/eslint.config.js
  apps/api-media/src/schema/cloudflare/r2/asset.ts
  apps/api-media/src/workers/algolia/service/service.ts
  apps/journeys-admin-e2e/src/pages/card-level-actions.ts
  apps/journeys-admin/eslint.config.js
  apps/journeys-admin/test/i18n.ts
  apps/journeys/eslint.config.js
  eslint.config.js
  libs/journeys/ui/eslint.config.js
  libs/journeys/ui/test/i18n.ts
  libs/nest/decorators/eslint.config.js
  libs/shared/ui/eslint.config.js
  package-lock.json
  package.json
Labels: priority: soon, effort: 1, type: chore

#4312 feat: api-journeys mux videoblock
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/db/migrations/20241113210242_20241113210240/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/infrastructure/locals.tf
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/video/video.graphql
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
Labels: effort: 5, priority: soon, type: feat, on stage

#4318 fix: convert to video information component
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/EditProvider.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/Metadata.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInfomation.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInformation.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInformation.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
  apps/videos-admin/src/components/SaveButton/SaveButton.spec.tsx
  apps/videos-admin/src/components/SaveButton/SaveButton.stories.tsx
  apps/videos-admin/src/components/SaveButton/SaveButton.tsx
  apps/videos-admin/src/components/SaveButton/index.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts
  apps/videos-admin/src/theme/customizations/inputs.tsx
  libs/locales/en/apps-videos-admin.json
Labels: type: fix, effort: 3, priority: soon

#4307 feat: add parameters to media component links
  apps/arclight/src/app/v2/media-component-links/[mediaComponentId]/route.ts
  apps/arclight/src/app/v2/media-component-links/route.ts
  apps/arclight/src/lib/getLanguageIdsFromTags.ts
Labels: priority: soon, type: feat, effort: 1

#4334 fix: save video snippet
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/Metadata.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/VideoSnippet.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/VideoSnippet.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/VideoSnippet.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/index.ts
  apps/videos-admin/src/components/ResizableTextField/ResizableTextField.spec.tsx
  apps/videos-admin/src/components/ResizableTextField/ResizableTextField.stories.tsx
  apps/videos-admin/src/components/ResizableTextField/ResizableTextField.tsx
  apps/videos-admin/src/components/ResizableTextField/index.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts
Labels: type: fix, effort: 3, priority: soon

#4335 feat: allow publishers to delete media items
  apps/api-media/src/schema/cloudflare/image/image.spec.ts
  apps/api-media/src/schema/cloudflare/image/image.ts
  apps/api-media/src/schema/cloudflare/video/video.spec.ts
  apps/api-media/src/schema/cloudflare/video/video.ts
  apps/api-media/src/schema/mux/video/video.spec.ts
  apps/api-media/src/schema/mux/video/video.ts
Labels: effort: 3, priority: soon, type: feat

#4328 docs: algolia wordpress integration
  apps/docs/docs/03-basics/03-frontend/07-algolia/02-algolia-wordpress-plugin.md
Labels: type: docs, priority: soon, effort: 1

#4336 fix: save button for video description
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/Metadata.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoDescription/VideoDescription.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoDescription/VideoDescription.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoDescription/VideoDescription.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoDescription/index.ts
  apps/videos-admin/src/components/ResizableTextField/ResizableTextField.tsx
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts
Labels: type: fix, priority: soon, effort: 1

#4412 test: add tests for tab label
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Tabs/TabLabel/TabLabel.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Tabs/TabLabel/TabLabel.stories.tsx
Labels: type: test, priority: soon, effort: 1

#4413 test: add tests for tab container
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Tabs/TabContainer/TabContainer.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Tabs/TabContainer/TabContainer.stories.tsx
Labels: type: test, priority: soon, effort: 1

#4414 test: add test for section fallback
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/EditProvider.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImageAlt/VideoImageAlt.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInformation.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/VideoSnippet.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Section/Section.spec.tsx
Labels: type: test, priority: soon, effort: 1

#4415 test: add tests for settings
  apps/videos-admin/src/app/[locale]/(dashboard)/settings/_Settings/Settings.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/settings/_Settings/Settings.stories.tsx
  apps/videos-admin/src/libs/storybookConfig/videosAdminConfig.tsx
Labels: type: test, priority: soon, effort: 1

#4416 test: add tests for dashboard
  apps/videos-admin/src/app/[locale]/(dashboard)/_Dashboard/Dashboard.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/_Dashboard/Dashboard.stories.tsx
Labels: type: test, priority: soon, effort: 1

#4434 fix: arclight aws deploy
  apps/arclight/project.json
Labels: type: fix, priority: soon, effort: 1, on stage

#4429 feat: upload image show loading progress and close dialog
  apps/api-media/src/yoga.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImage/FileUpload/FileUpload.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImage/FileUpload/FileUpload.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImage/VideoImage.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImage/VideoImage.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImage/VideoImageUpload/VideoImageUpload.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImage/VideoImageUpload/VideoImageUpload.tsx
  apps/videos-admin/src/app/[locale]/layout.tsx
  apps/videos-admin/src/libs/SnackbarProvider/SnackbarProvider.tsx
  apps/videos-admin/src/libs/SnackbarProvider/index.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.tsx
Labels: effort: 3, priority: soon, type: feat

#4453 test: add tests for video view
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/EditProvider.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/Metadata.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/Metadata.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoDescription/VideoDescription.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoDescription/VideoDescription.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoDescription/VideoDescription.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImageAlt/VideoImageAlt.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImageAlt/VideoImageAlt.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImageAlt/VideoImageAlt.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInfomation.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInformation.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInformation.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/VideoSnippet.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/VideoSnippet.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/VideoSnippet.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/data.mock.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.tsx
Labels: type: test, effort: 2, priority: soon

#4449 feat: use navigation state
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.spec.tsx
  libs/journeys/ui/src/libs/useNavigationState/index.ts
  libs/journeys/ui/src/libs/useNavigationState/useNavigationState.spec.tsx
  libs/journeys/ui/src/libs/useNavigationState/useNavigationState.tsx
Labels: priority: soon, type: feat, effort: 1

#4454 fix: remove variant view
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/[variantId]/_VariantView/VariantView.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/[variantId]/_VariantView/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/[variantId]/page.tsx
Labels: type: fix, priority: soon, effort: 1

#4456 test: add tests for variants
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.stories.tsx
Labels: type: test, priority: soon, effort: 1

#4482 test: add tests for downloads
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Downloads/Downloads.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Downloads/Downloads.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Downloads/Downloads.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Downloads/utils/bytesToSize.spec.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Downloads/utils/bytesToSize.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.tsx
Labels: type: test, priority: soon, effort: 1

#4448 perf: children card drag
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/DraggableRow/DraggableRow.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/DraggableRow/OrderSelect.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/DraggableRow/RowImage.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/DraggableRow/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestionsList/StudyQuestionsList.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestionsList/StudyQuestionsList.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestionsList/data.mock.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Section/Section.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/Actions/index.ts
  apps/videos-admin/src/components/OrderedList/OrderedItem/DropDown/DropDown.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/DropDown/index.ts
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.spec.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.stories.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItemIcons/OrderedItemIcons.spec.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItemIcons/OrderedItemIcons.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItemIcons/index.ts
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItemMenu/OrderedItemMenu.spec.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItemMenu/OrderedItemMenu.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItemMenu/index.ts
  apps/videos-admin/src/components/OrderedList/OrderedList.spec.tsx
  apps/videos-admin/src/components/OrderedList/OrderedList.stories.tsx
  apps/videos-admin/src/components/OrderedList/OrderedList.tsx
  apps/videos-admin/src/libs/createFilledContext/createFilledContext.ts
  apps/videos-admin/src/libs/createFilledContext/index.ts
  apps/videos-admin/src/libs/createRequiredContext/createRequiredContext.ts
  apps/videos-admin/src/libs/createRequiredContext/index.ts
  apps/videos-admin/src/libs/useAdminVideo/index.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.tsx
Labels: effort: 2, priority: soon, type: perf

#4329 test: add more journeys-admin-e2e tests
  apps/journeys-admin-e2e/playwright.config.ts
  apps/journeys-admin-e2e/src/e2e/discover/active-archived-trash.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/analytics.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/card-level-actions.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/custom-journey.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/journey-level-actions.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/journey-sorting.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/members.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/teams.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/templated-journey.spec.ts
  apps/journeys-admin-e2e/src/e2e/profile/profile.spec.ts
  apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
  apps/journeys-admin-e2e/src/pages/card-level-actions.ts
  apps/journeys-admin-e2e/src/pages/journey-level-actions-page.ts
  apps/journeys-admin-e2e/src/pages/journey-page.ts
  apps/journeys-admin-e2e/src/pages/landing-page.ts
  apps/journeys-admin-e2e/src/pages/left-nav.ts
  apps/journeys-admin-e2e/src/pages/login-page.ts
  apps/journeys-admin-e2e/src/pages/profile-page.ts
  apps/journeys-admin-e2e/src/pages/publisher-and-templates-page.ts
  apps/journeys-admin-e2e/src/pages/publisher-page.ts
  apps/journeys-admin-e2e/src/pages/register-Page.ts
  apps/journeys-admin-e2e/src/pages/teams-page.ts
  apps/journeys-admin-e2e/src/pages/template-page.ts
  apps/journeys-admin-e2e/src/utils/testData.json
  apps/journeys-admin-e2e/src/utils/testResource/Flower.jpg
  apps/journeys-admin-e2e/src/utils/testResource/SampleVideo.mp4
Labels: type: test, priority: 2day, effort: 13

#4484 feat: add short link nextjs service
  .github/workflows/app-deploy.yml
  .github/workflows/main.yml
  apps/short-links-e2e/.eslintrc.json
  apps/short-links-e2e/playwright.config.ts
  apps/short-links-e2e/project.json
  apps/short-links-e2e/src/e2e/redirect.spec.ts
  apps/short-links-e2e/tsconfig.e2e.json
  apps/short-links-e2e/tsconfig.json
  apps/short-links/eslint.config.js
  apps/short-links/index.d.ts
  apps/short-links/jest.config.ts
  apps/short-links/next-env.d.ts
  apps/short-links/next.config.js
  apps/short-links/project.json
  apps/short-links/public/.gitkeep
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/short-links/src/app/[hostname]/[...pathname]/getShortLinkQuery.ts
  apps/short-links/src/app/[hostname]/[...pathname]/not-found.tsx
  apps/short-links/src/app/[hostname]/[...pathname]/page.test.ts
  apps/short-links/src/app/[hostname]/[...pathname]/page.ts
  apps/short-links/src/app/layout.tsx
  apps/short-links/src/lib/apolloClient/apolloClient.ts
  apps/short-links/src/lib/apolloClient/index.ts
  apps/short-links/src/middleware.ts
  apps/short-links/tsconfig.json
  apps/short-links/tsconfig.spec.json
Labels: effort: 2, priority: now, type: feat, on stage

#4502 feat: refactor metadata language tags handling no qa
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/[languageId]/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/route.ts
  apps/arclight/src/app/v2/media-components/route.ts
  apps/arclight/src/app/v2/media-countries/[countryId]/route.ts
  apps/arclight/src/app/v2/media-countries/route.ts
  apps/arclight/src/app/v2/media-languages/[languageId]/route.ts
  apps/arclight/src/app/v2/media-languages/route.ts
Labels: effort: 2, type: fix, priority: soon

#4327 fix: selecting template multiple clicks
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.spec.tsx
  libs/journeys/ui/src/components/TemplateGalleryCard/TemplateGalleryCard.spec.tsx
  libs/journeys/ui/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
Labels: effort: 2, type: fix, priority: soon

#4516 chore: add env to stage and prod
  apps/api-media/infrastructure/locals.tf
Labels: priority: now, effort: 1, type: chore

#4481 fix: disable see all journeys button when navigating
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Labels: type: fix, priority: soon, effort: 1
