Repository JesusFilm/core, pull requests merged in 2024-03, with the labels that each got.

#2403 fix: interop ip check
  apps/api-users/src/app/modules/user/user.resolver.spec.ts
  apps/api-users/src/app/modules/user/user.resolver.ts
Labels: type: fix, priority: now, effort: 1, on stage

#2405 refactor: remove admin changes
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
Labels: priority: now, effort: 1, type: refactor

#2404 refactor: remove superfluous changes for card swiping
  apps/journeys-admin/src/components/CardPreview/CardList/CardWrapper/CardWrapper.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardList/CardWrapper/CardWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/Conductor/DynamicCardList/DynamicCardList.spec.tsx
  apps/journeys/src/components/Conductor/DynamicCardList/DynamicCardList.tsx
  apps/journeys/src/components/Conductor/DynamicCardList/index.ts
  apps/journeys/src/components/Conductor/JourneyRenderer/index.ts
  apps/journeys/src/components/VideoWrapperPaused/VideoWrapperPaused.spec.tsx
  apps/journeys/src/components/VideoWrapperPaused/VideoWrapperPaused.tsx
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/Bullet/Bullet.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.spec.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.spec.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, effort: 1, type: refactor

#2293 feat: card swiping
  apps/journeys/pages/_document.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/Conductor/DynamicCardList/DynamicCardList.spec.tsx
  apps/journeys/src/components/Conductor/DynamicCardList/DynamicCardList.tsx
  apps/journeys/src/components/Conductor/DynamicCardList/index.ts
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.spec.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/index.ts
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/Bullet/Bullet.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/Bullet/index.ts
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.spec.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.stories.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/index.ts
  libs/journeys/ui/src/components/StepHeader/StepHeader.spec.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.spec.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/index.ts
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/VideoControls/DesktopControls/DesktopControls.tsx
  libs/journeys/ui/src/components/Video/VideoControls/DesktopControls/index.ts
  libs/journeys/ui/src/components/Video/VideoControls/MobileControls/MobileControls.tsx
  libs/journeys/ui/src/components/Video/VideoControls/MobileControls/index.ts
  libs/journeys/ui/src/components/Video/VideoControls/PlaybackIcon/PlaybackIcon.tsx
  libs/journeys/ui/src/components/Video/VideoControls/PlaybackIcon/index.ts
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.spec.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/Video/VideoControls/utils/playbackReducer/index.ts
  libs/journeys/ui/src/components/Video/VideoControls/utils/playbackReducer/playbackReducer.ts
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.spec.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.tsx
  libs/journeys/ui/src/libs/getStepTheme/getStepTheme.ts
  package-lock.json
  package.json
Labels: effort: 13, priority: soon, type: feat

#2407 fix: add height and width params to segmind request
  apps/api-media/src/app/modules/segmind/segmind.service.ts
Labels: type: fix, priority: now, effort: 1

#2409 fix: templates email not verified
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/pages/users/verify.tsx
Labels: type: fix, priority: now, effort: 1

#2408 fix: overflow caused by inactive card height
  apps/journeys/src/components/Conductor/DynamicCardList/DynamicCardList.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
Labels: type: fix, priority: soon, effort: 1

#2415 fix: broken build dependency
  package-lock.json
  package.json
Labels: type: fix, priority: now, effort: 1, on stage

#2410 feat: email redirect backend
  apps/api-gateway/schema.graphql
  apps/api-users/schema.graphql
  apps/api-users/src/app/__generated__/graphql.ts
  apps/api-users/src/app/modules/email/email.consumer.ts
  apps/api-users/src/app/modules/user/user.graphql
  apps/api-users/src/app/modules/user/user.resolver.spec.ts
  apps/api-users/src/app/modules/user/user.resolver.ts
  apps/api-users/src/app/modules/user/user.service.spec.ts
  apps/api-users/src/app/modules/user/user.service.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#2419 fix: translation import
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewVideoButton/NewVideoButton.tsx
Labels: type: fix, priority: now, effort: 1

#2417 fix: remove invite teams in onboarding
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.spec.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.stories.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: now, effort: 1

#2428 feat: onboarding side bar - desktop view
  apps/journeys-admin/pages/users/sign-in.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingSideBar/OnboardingSideBar.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingSideBar/index.ts
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingTemplateCard/OnboardingTemplateCard.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingTemplateCard/index.ts
  apps/journeys-admin/src/components/SignIn/PasswordPage/PasswordPage.tsx
  apps/journeys-admin/src/components/SignIn/RegisterPage/RegisterPage.tsx
  apps/journeys-admin/src/components/SignIn/SignIn.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: soon, type: feat

#2429 feat: account check dialog
  apps/journeys-admin/src/components/TemplateView/AccountCheckDialog/AccountCheckDialog.stories.tsx
  apps/journeys-admin/src/components/TemplateView/AccountCheckDialog/AccountCheckDialog.tsx
  apps/journeys-admin/src/components/TemplateView/AccountCheckDialog/index.ts
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, type: feat, effort: 1

#2431 feat: onboarding stepper
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingSideBar/OnboardingSideBar.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingStepper/OnboardingStepper.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingStepper/index.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: now, type: feat

#2421 test: add tests for base node
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx
  apps/journeys-admin/test/mockReactFlow.ts
Labels: type: test, effort: 2, priority: soon

#2438 fix: update account check dialog design
  apps/journeys-admin/src/components/TemplateView/AccountCheckDialog/AccountCheckDialog.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, type: fix, priority: now

#2437 fix: journeys admin logging
  apps/journeys-admin/Dockerfile
  apps/journeys-admin/next-logger.config.js
  package-lock.json
  package.json
Labels: type: fix, priority: now, effort: 1, on stage

#2436 fix: onboarding page design
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/index.ts
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingSideBar/OnboardingSideBar.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingSideBar/index.ts
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingStepper/OnboardingStepper.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingTemplateCard/OnboardingTemplateCard.tsx
  apps/journeys-admin/src/components/SignIn/SignIn.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
Labels: type: fix, priority: soon, effort: 1

#2439 fix: mobile stepper design
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingStepper/OnboardingStepper.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, effort: 3, priority: soon

#2441 fix: mobile dialog design
  apps/journeys-admin/src/components/TemplateView/AccountCheckDialog/AccountCheckDialog.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, type: fix, priority: now

#2443 fix: onboarding page wrapper design
  apps/journeys-admin/pages/onboarding-form.tsx
  apps/journeys-admin/pages/teams/new.tsx
  apps/journeys-admin/pages/users/sign-in.tsx
  apps/journeys-admin/pages/users/terms-and-conditions.tsx
  apps/journeys-admin/pages/users/verify.tsx
  apps/journeys-admin/src/components/OnboardingForm/OnboardingForm.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingTemplateCard/OnboardingTemplateCard.tsx
  apps/journeys-admin/src/components/SignIn/SignIn.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/FormiumForm/FormiumForm.tsx
Labels: type: fix, effort: 3, priority: soon

#2426 test: button block node
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ButtonBlockNode/ButtonBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ButtonBlockNode/ButtonBlockNode.tsx
Labels: type: test, priority: soon, effort: 1

#2433 test: add tests for FormBlockNode
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/FormBlockNode/FormBlockNode.spec.tsx
Labels: type: test, priority: soon, effort: 1

#2434 test: radio option block node
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/RadioOptionBlockNode/RadioOptionBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/RadioOptionBlockNode/RadioOptionBlockNode.tsx
Labels: type: test, priority: soon, effort: 1

#2435 test: sign up block node
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SignUpBlockNode/SignUpBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SignUpBlockNode/SignUpBlockNode.tsx
Labels: type: test, priority: soon, effort: 1

#2446 feat: api-nexus infrastructure
  apps/api-nexus/infrastructure/locals.tf
  apps/api-nexus/infrastructure/main.tf
  apps/api-nexus/infrastructure/outputs.tf
  apps/api-nexus/infrastructure/variables.tf
  infrastructure/.terraform.lock.hcl
  infrastructure/environments/prod/data.tf
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/data.tf
  infrastructure/environments/stage/main.tf
  infrastructure/modules/aws/datadog/main.tf
Labels: priority: now, type: feat, effort: 1

#2449 feat: mailchimp env vars
  apps/api-journeys/infrastructure/locals.tf
  atlantis.yaml
Labels: type: fix, priority: soon, effort: 1

#2440 feat: add new nextsteps admin to mailchimp audience
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.module.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.spec.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.ts
  apps/api-journeys/src/app/modules/mailChimp/mailChimp.module.ts
  apps/api-journeys/src/app/modules/mailChimp/mailChimp.service.spec.ts
  apps/api-journeys/src/app/modules/mailChimp/mailChimp.service.ts
  apps/api-users/src/app/modules/user/user.service.spec.ts
  apps/api-users/src/app/modules/user/user.service.ts
  package-lock.json
  package.json
Labels: type: fix, effort: 3, priority: soon, on stage

#2450 feat: email redirect front-end
  apps/journeys-admin/__generated__/CreateVerificationRequest.ts
  apps/journeys-admin/__generated__/GetMe.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/users/verify.tsx
  apps/journeys-admin/src/components/EmailVerification/EmailVerification.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserNavigation.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserNavigation.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/SignIn/PasswordPage/PasswordPage.spec.tsx
  apps/journeys-admin/src/components/SignIn/PasswordPage/PasswordPage.tsx
  apps/journeys-admin/src/components/SignIn/RegisterPage/RegisterPage.spec.tsx
  apps/journeys-admin/src/components/SignIn/RegisterPage/RegisterPage.tsx
  apps/journeys-admin/src/components/SignIn/SignInServiceButton/SignInServiceButton.spec.tsx
  apps/journeys-admin/src/components/SignIn/SignInServiceButton/SignInServiceButton.tsx
  apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.ts
Labels: priority: soon, type: feat, effort: 1

#2451 test: account check dialog
  apps/journeys-admin/src/components/TemplateView/AccountCheckDialog/AccoutCheckDialog.spec.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.spec.tsx
Labels: type: test, priority: soon, effort: 1

#2454 fix: logging level on datadog
  apps/journeys-admin/next-logger.config.js
Labels: type: fix, priority: now, effort: 1, on stage

#2453 fix: onboarding stepper logic
  apps/journeys-admin/pages/onboarding-form.tsx
  apps/journeys-admin/pages/teams/new.tsx
  apps/journeys-admin/pages/users/terms-and-conditions.tsx
  apps/journeys-admin/pages/users/verify.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingStepper/OnboardingStepper.tsx
  apps/journeys-admin/src/components/SignIn/RegisterPage/RegisterPage.tsx
  apps/journeys-admin/src/libs/useRedirectNewAccount/index.ts
  apps/journeys-admin/src/libs/useRedirectNewAccount/useHandleNewAccountRedirect.ts
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, effort: 3, priority: now

#2455 test: onboarding template card
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingTemplateCard/OnboardingTemplateCard.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingTemplateCard/OnboardingTemplateCard.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: test, priority: now, effort: 1

#2458 fix: sign in redirect issue
  apps/journeys-admin/src/components/SignIn/PasswordPage/PasswordPage.tsx
Labels: type: fix, priority: now, effort: 1

#2460 feat: onboarding stepper icon
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingStepper/OnboardingStepper.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingStepper/OnboardingStepper.tsx
Labels: effort: 3, priority: now, type: feat

#2457 test: onboarding page wrapper
  apps/journeys-admin/pages/users/verify.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.stories.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingTemplateCard/OnboardingTemplateCard.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingTemplateCard/OnboardingTemplateCard.tsx
  apps/journeys-admin/src/components/SignIn/SignIn.spec.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/FormiumForm/wrappers/PageWrapper/PageWrapper.tsx
Labels: type: test, priority: now, effort: 1

#2456 test: onboarding drawer
  apps/journeys-admin/pages/users/verify.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.stories.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingStepper/OnboardingStepper.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingStepper/OnboardingStepper.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingStepper/index.ts
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingTemplateCard/OnboardingTemplateCard.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingTemplateCard/OnboardingTemplateCard.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingTemplateCard/index.ts
  apps/journeys-admin/src/components/SignIn/PasswordPage/PasswordPage.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: test, priority: soon, effort: 1

#2463 test: test for cancel button
  apps/journeys-admin/src/components/SignIn/RegisterPage/RegisterPage.spec.tsx
  apps/journeys-admin/src/components/SignIn/RegisterPage/RegisterPage.tsx
Labels: type: fix, priority: soon, effort: 1

#2459 feat: generate erd for prisma
  .devcontainer/Dockerfile
  .devcontainer/docker-compose.yml
  .github/workflows/api-deploy-worker.yml
  .github/workflows/main.yml
  apps/api-journeys/db/ERD.svg
  apps/api-journeys/db/schema.prisma
  apps/api-languages/db/ERD.svg
  apps/api-languages/db/schema.prisma
  apps/api-media/db/ERD.svg
  apps/api-media/db/schema.prisma
  apps/api-tags/db/ERD.svg
  apps/api-tags/db/schema.prisma
  apps/api-users/db/ERD.svg
  apps/api-users/db/schema.prisma
  apps/api-videos/db/ERD.svg
  apps/api-videos/db/schema.prisma
  apps/docs/docs/03-basics/02-backend/04-databases.md
  package-lock.json
  package.json
Labels: priority: now, type: feat, effort: 1

#2464 feat: add xy to step block
  apps/api-gateway/schema.graphql
  apps/api-journeys/Dockerfile
  apps/api-journeys/db/Dockerfile
  apps/api-journeys/db/migrations/20240313235947_20240313235945/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/step/step.graphql
  apps/api-journeys/src/app/modules/block/step/step.resolver.spec.ts
  apps/api-languages/Dockerfile
  apps/api-languages/db/Dockerfile
  apps/api-media/Dockerfile
  apps/api-tags/Dockerfile
  apps/api-tags/db/Dockerfile
  apps/api-users/Dockerfile
  apps/api-videos/Dockerfile
  apps/api-videos/db/Dockerfile
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: priority: now, type: feat, effort: 1, on stage

#2445 test: video block node
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/VideoBlockNode/VideoBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/VideoBlockNode/VideoBlockNode.tsx
Labels: type: test, priority: soon, effort: 1

#2425 test: action node
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ActionNode/ActionNode.spec.tsx
Labels: type: test, priority: soon, effort: 1

#2444 test: text response block node
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/TextResponseBlockNode/TextResponseBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/TextResponseBlockNode/TextResponseBlockNode.tsx
Labels: type: test, priority: soon, effort: 1

#2447 test: social preview node
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx
Labels: type: test, priority: soon, effort: 1

#2465 test: redirect handle new user
  apps/journeys-admin/src/libs/useRedirectNewAccount/useHandleNewAccountRedirect.spec.tsx
Labels: type: test, effort: 3, priority: soon

#2462 fix: undo templates redirect check
  apps/journeys-admin/pages/templates/index.tsx
Labels: type: fix, priority: now, effort: 1

#2466 feat: landing page design
  apps/journeys-admin/public/landing-description-mobile.png
  apps/journeys-admin/public/landing-description.png
  apps/journeys-admin/public/landing-illustration.png
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.stories.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingStepper/OnboardingStepper.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingStepper/OnboardingStepper.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingTemplateCard/OnboardingTemplateCard.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingTemplateCard/OnboardingTemplateCard.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: now, type: feat

#2469 fix: add template dialog
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.spec.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateFooter/TemplateFooter.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateFooter/TemplateFooter.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateFooter/TemplateFooter.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.tsx
Labels: type: fix, effort: 3, priority: now

#2473 fix: empty index file
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingTemplateCard/index.ts
Labels: type: fix, priority: now, effort: 1

#2471 test: canvas properties
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Button/Button.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/Card.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Form.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Image.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Options/ImageOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioOption/RadioOption.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/SignUp/SignUp.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/Step.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Typography.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Video.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/CardTemplateDrawer.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/Drawer.tsx
Labels: type: test, priority: soon, effort: 1

#2472 feat: blocks query
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/ERD.svg
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/lib/casl/caslFactory/caslFactory.ts
  apps/api-journeys/src/app/modules/block/block.acl.spec.ts
  apps/api-journeys/src/app/modules/block/block.acl.ts
  apps/api-journeys/src/app/modules/block/block.graphql
  apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.resolver.ts
Labels: priority: now, type: feat, effort: 1, on stage

#2475 fix: landing illustration size
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.tsx
Labels: type: fix, priority: now, effort: 1

#2474 test: fix card preview test
  apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx
Labels: type: test, priority: soon, effort: 1

#2479 fix: design update
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingStepper/OnboardingStepper.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingTemplateCard/OnboardingTemplateCard.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.tsx
Labels: type: fix, priority: now, effort: 1

#2424 test: toolbar test
  apps/journeys-admin/src/components/Editor/Toolbar/Items/Items.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Labels: type: test, effort: 2, priority: now

#2480 fix: update url redirect
  apps/api-users/src/app/modules/email/email.consumer.spec.ts
  apps/api-users/src/app/modules/email/email.consumer.ts
Labels: type: fix, priority: now, effort: 1, on stage

#2432 chore: new crowdin translations
  libs/locales/ar-SA/apps-docs.json
  libs/locales/ar-SA/apps-journeys-admin.json
  libs/locales/ar-SA/apps-journeys.json
  libs/locales/ar-SA/apps-nexus-admin.json
  libs/locales/ar-SA/apps-watch.json
  libs/locales/ar-SA/libs-journeys-ui.json
Labels: priority: soon, effort: 1, type: chore

#2481 fix: template card design
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingTemplateCard/OnboardingTemplateCard.tsx
Labels: type: fix, priority: now, effort: 1

#2468 test: social preview
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.spec.tsx
Labels: type: test, priority: soon, effort: 1

#2412 feat: context menu on cards
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DeleteBlock/DeleteBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DeleteBlock/DeleteBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DuplicateBlock/DuplicateBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DuplicateBlock/DuplicateBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/StepBlockNodeMenu.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/StepBlockNodeMenu.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/StepBlockNodeMenu.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/index.ts
Labels: effort: 5, priority: now, type: feat

#2485 test: contained icon button
  apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.spec.tsx
Labels: type: test, priority: soon, effort: 1

#2484 fix: redirect issue
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.spec.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
  apps/journeys-admin/src/libs/useRedirectNewAccount/useHandleNewAccountRedirect.spec.tsx
  apps/journeys-admin/src/libs/useRedirectNewAccount/useHandleNewAccountRedirect.ts
Labels: type: fix, priority: now, effort: 1

#2488 test: refactor and update tests for Settings
  apps/journeys-admin/src/components/Editor/Slider/Settings/Settings.spec.tsx
Labels: type: test, priority: soon, effort: 1

#2489 test: canvas details
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/CanvasDetails.spec.tsx
Labels: type: test, priority: soon

#2490 test: add tests for editor Content
  apps/journeys-admin/src/components/Editor/Slider/Content/Content.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/Goals.tsx
Labels: type: test, priority: soon, effort: 1

#2452 test: fab
  apps/journeys-admin/src/components/Editor/Fab/Fab.spec.tsx
  apps/journeys-admin/src/components/Editor/Fab/Fab.tsx
  apps/journeys-admin/src/libs/TestEditorState/TestEditorState.tsx
Labels: type: test, effort: 2, priority: soon

#2491 fix: editor provider tests
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
Labels: type: test, priority: soon, effort: 1

#2422 test: toolbar menu tests
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.tsx
Labels: type: test, effort: 2, priority: now

#2487 fix: host avatars
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.spec.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.stories.tsx
Labels: type: test, priority: soon, effort: 1

#2494 test: remove teamName check from response time check
  apps/journeys-admin-e2e/src/e2e/response-time.spec.ts
Labels: type: test, priority: soon, effort: 1

#2492 fix: add dd-source to ecs task
  apps/journeys-admin/infrastructure/main.tf
  infrastructure/modules/aws/ecs-task/main.tf
  infrastructure/modules/aws/ecs-task/variables.tf
Labels: type: fix, priority: now, effort: 1

#2384 feat: move hosted by functionality from drawers into hosted by tab
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostDrawer/HostDrawer.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostDrawer/HostDrawer.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostDrawer/HostDrawer.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostDrawer/HostFormDrawer/HostFormDrawer.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostDrawer/HostFormDrawer/HostFormDrawer.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostDrawer/HostFormDrawer/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostDrawer/HostInfoDrawer/HostInfoDrawer.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostDrawer/HostInfoDrawer/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostDrawer/HostList/HostList.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostDrawer/HostList/HostList.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostDrawer/HostListDrawer/HostListDrawer.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostDrawer/HostListDrawer/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostDrawer/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostAvatarsButton/HostAvatarsButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostAvatarsButton/HostAvatarsButton.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostAvatarsButton/HostAvatarsButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostAvatarsButton/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostForm.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostForm.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostLocationFieldForm/HostLocationFieldForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostLocationFieldForm/HostLocationFieldForm.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostLocationFieldForm/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostTitleFieldForm/HostTitleFieldForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostTitleFieldForm/HostTitleFieldForm.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostTitleFieldForm/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostInfo/HostInfo.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostInfo/HostInfo.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostInfo/HostInfo.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostInfo/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostList/HostList.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostList/HostList.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostList/HostList.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostList/HostListItem/HostListItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostList/HostListItem/HostListItem.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostList/HostListItem/HostListItem.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostList/HostListItem/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostList/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostSelection/HostSelection.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostSelection/HostSelection.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostSelection/HostSelection.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostSelection/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostTab.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostTab.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostTab.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/index.ts
Labels: effort: 5, priority: now, type: feat

#2495 fix: include logging level config
  apps/journeys-admin/project.json
Labels: type: fix, priority: now, effort: 1, on stage

#2496 fix: api logging level
  apps/api-journeys/src/app/app.module.ts
  apps/api-languages/src/app/app.module.ts
  apps/api-media/src/app/app.module.ts
  apps/api-tags/src/app/app.module.ts
  apps/api-users/src/app/app.module.ts
  apps/api-videos/src/app/app.module.ts
Labels: type: fix, priority: now, effort: 1, on stage

#2483 test: canvas details footer
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Chat/Chat.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.spec.tsx
Labels: type: test, priority: soon, effort: 1

#2493 test: editor
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Labels: type: test, priority: soon, effort: 1

#2427 test: toolbar items test
  apps/journeys-admin/src/components/Editor/Toolbar/Items/AccessItem/AccessItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/AnalyticsItem/AnalyticsItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/CopyLinkItem/CopyLinkItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/CopyLinkItem/CopyMenuItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/CreateTemplateItem/CreateTemplateItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DescriptionItem/DescriptionItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/Item/Item.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/Items.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/LanguageItem/LanguageItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/PreviewItem/PreviewItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/StrategyItem/StrategyItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/StrategyItem/StrategyItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TemplateSettingsItem/TemplateSettingsDialog/TemplateSettingsDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TemplateSettingsItem/TemplateSettingsItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TitleItem/TitleItem.tsx
Labels: type: test, effort: 2, priority: now

#2482 feat: add tests for addblock
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.spec.tsx
Labels: type: test, priority: soon, effort: 1

#2499 test: fix hostlocationfieldform tests
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostLocationFieldForm/HostLocationFieldForm.spec.tsx
Labels: type: test, effort: 2, priority: soon

#2502 feat: proxy client side graphql requests via rewrite
  apps/journeys/next.config.js
  apps/journeys/src/libs/apolloClient/apolloClient.ts
Labels: priority: now, type: feat, effort: 1, on stage

#2505 fix: embedded videos playing when not activeStep
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
Labels: type: fix, priority: now, effort: 1, on stage

#2506 feat: custom domain infrastructure
  apps/api-journeys/infrastructure/locals.tf
  infrastructure/.terraform.lock.hcl
Labels: priority: now, type: feat, effort: 1

#2511 chore: add journeys-stage app
  .github/workflows/app-deploy.yml
  apps/journeys/pages/index.tsx
Labels: effort: 3, priority: now, type: chore, on stage

#2476 feat: custom domain backend
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/ERD.svg
  apps/api-journeys/db/migrations/20240324223654_20240324223653/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/lib/casl/__generated__/prismaSubjects.ts
  apps/api-journeys/src/app/lib/casl/caslFactory/caslFactory.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.acl.spec.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.acl.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.graphql
  apps/api-journeys/src/app/modules/customDomain/customDomain.module.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.resolver.spec.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.resolver.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.service.spec.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.service.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/journeyCollection/journeyCollection.acl.spec.ts
  apps/api-journeys/src/app/modules/journeyCollection/journeyCollection.acl.ts
  apps/api-journeys/src/app/modules/journeyCollection/journeyCollection.graphql
  apps/api-journeys/src/app/modules/journeyCollection/journeyCollection.module.ts
  apps/api-journeys/src/app/modules/journeyCollection/journeyCollection.resolver.spec.ts
  apps/api-journeys/src/app/modules/journeyCollection/journeyCollection.resolver.ts
  apps/api-journeys/src/app/modules/team/team.graphql
  apps/api-journeys/src/app/modules/team/team.resolver.spec.ts
  apps/api-journeys/src/app/modules/team/team.resolver.ts
Labels: effort: 13, priority: soon, type: feat, on stage

#2513 chore: allow facebook to connect
  apps/journeys-admin/public/robots.txt
Labels: priority: now, effort: 1, type: chore

#2516 fix: no redirect for languages when same url
  apps/journeys-admin/middleware.spec.ts
  apps/journeys-admin/middleware.ts
Labels: type: fix, priority: now, effort: 1

#2504 test: goals tests fixes
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/Goals.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsList.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsList.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/GoalDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/GoalDetails.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: test, effort: 3, priority: soon

#2442 feat: custom domain support on journeys visitor frontend
  .github/workflows/app-deploy.yml
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/GetJourneys.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/middleware.ts
  apps/journeys/next.config.js
  apps/journeys/pages/[hostname]/[journeySlug].tsx
  apps/journeys/pages/[hostname]/embed/[journeySlug].tsx
  apps/journeys/pages/[hostname]/index.tsx
  apps/journeys/pages/[journeySlug]/[stepId].tsx
  apps/journeys/pages/api/oembed.ts
  apps/journeys/pages/api/revalidate.ts
  apps/journeys/pages/home/[journeySlug].tsx
  apps/journeys/pages/home/embed/[journeySlug].tsx
  apps/journeys/pages/home/embed/test/[journeySlug].tsx
  apps/journeys/pages/home/index.tsx
Labels: priority: now, type: feat, effort: 1, on stage

#2518 fix: use templates slide
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplatePreviewTabs.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#2520 fix: editor tests and lint
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CardWrapper/CardWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CardWrapper/CardWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/VideoWrapper/VideoWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsBanner/GoalsBanner.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsListItem/GoalsListItem.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/Post/Post.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/ButtonEdge.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ActionNode/ActionNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ButtonBlockNode/ButtonBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/FormBlockNode/FormBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/FormBlockNode/FormBlockNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/RadioOptionBlockNode/RadioOptionBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SignUpBlockNode/SignUpBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/TextResponseBlockNode/TextResponseBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/VideoBlockNode/VideoBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/Button/Button.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/Button/Button.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Settings.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/SocialDetails.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.stories.tsx
Labels: type: fix, priority: soon, effort: 1

#2528 feat: custom domain name validation
  apps/api-journeys/src/app/modules/customDomain/customDomain.resolver.spec.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.resolver.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.service.spec.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.service.ts
Labels: priority: soon, type: feat, effort: 1

#2519 feat: default journey for hostname
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/journeys/__generated__/globalTypes.ts
Labels: priority: soon, type: feat, effort: 1

#2529 fix: page title
  libs/journeys/ui/src/components/Step/Step.tsx
Labels: type: fix, priority: now, effort: 1

#2521 feat: on custom domain only show default journeys
  .github/workflows/app-deploy.yml
  apps/journeys/__generated__/GetJourneySlugs.ts
  apps/journeys/pages/[hostname]/[journeySlug].tsx
  apps/journeys/pages/[hostname]/embed/[journeySlug].tsx
  apps/journeys/pages/[hostname]/index.tsx
  apps/journeys/pages/home/[journeySlug].tsx
  apps/journeys/pages/home/embed/[journeySlug].tsx
  apps/watch-e2e/src/e2e/filters.spec.ts-snapshots/see-all-landing-firefox-linux.png
  libs/locales/en/apps-journeys.json
Labels: priority: now, type: feat, effort: 1, on stage

#2531 fix: add thai language to templates
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/data.ts
Labels: priority: 2day, type: fix, effort: 1

#2527 test: editor slider
  apps/journeys-admin/src/components/Editor/Slider/Content/Content.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/Slider.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
Labels: type: test, priority: soon, effort: 1

#2532 fix: validate of get me
  apps/journeys-admin/pages/templates/index.tsx
Labels: type: fix, priority: now, effort: 1

#2534 refactor: dispatch tests
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsList.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsListItem/GoalListItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ActionNode/ActionNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Credentials/Credentials.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/GoalDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/StrategyItem/StrategyItem.spec.tsx
  apps/journeys-admin/src/libs/TestEditorState/TestEditorState.tsx
Labels: effort: 2, priority: soon, type: refactor

#2503 feat: toolbar stories
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.stories.tsx
Labels: effort: 2, priority: soon, type: feat

#2500 feat: footer stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostAvatarsButton/HostAvatarsButton.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#2536 fix: update goal details story
  apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/GoalDetails.stories.tsx
Labels: type: fix, priority: soon, effort: 1

#2554 fix: domain validation
  apps/api-journeys/src/app/modules/customDomain/customDomain.service.spec.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.service.ts
Labels: type: fix, priority: now, effort: 1

#2546 feat: social preview node stories
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.stories.tsx
Labels: priority: now, type: feat, effort: 1

#2547 feat: social details story
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/SocialDetails.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#2549 feat: card template drawer story
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CardWrapper/CardWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/CardTemplates.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/CardTemplates.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/CardTemplates.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/index.ts
Labels: priority: soon, type: feat, effort: 1

#2552 feat: goal stories
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/Goals.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsBanner/GoalsBanner.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsList.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsListItem/GoalsListItem.stories.tsx
Labels: effort: 2, type: fix, priority: soon

#2550 feat: drawer stories
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/Drawer.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#2559 fix: generated graphql scheme
  apps/api-nexus/schema.graphql
Labels: on stage
