Repository JesusFilm/core, pull requests merged in 2024-01, with the labels that each got.

#2183 fix: broken test year
  apps/docs-e2e/src/e2e/docs.spec.ts-snapshots/home-page-chrome-desktop-linux.png
  apps/docs-e2e/src/e2e/docs.spec.ts-snapshots/home-page-chrome-mobile-linux.png
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TemplateSettingsDialog/MetadataTabPanel/MetadataTabPanel.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardText/JourneyCardText.spec.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/journeyListData.ts
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
  apps/journeys-admin/src/components/TemplateList/ActiveTemplateList/ActiveTemplateList.spec.tsx
  apps/journeys-admin/src/components/TemplateList/ArchivedTemplateList/ArchivedTemplateList.spec.tsx
  apps/journeys-admin/src/components/TemplateList/TemplateListItem/TemplateListItem.tsx
  apps/journeys-admin/src/components/TemplateList/TrashedTemplateList/TrashedTemplateList.spec.tsx
  apps/journeys-admin/src/components/TemplateList/data.ts
  apps/watch-e2e/src/e2e/chapter.spec.ts-snapshots/after-video-firefox-linux.png
  apps/watch-e2e/src/e2e/chapter.spec.ts-snapshots/before-video-firefox-linux.png
  apps/watch-e2e/src/e2e/chapter.spec.ts-snapshots/home-page-firefox-linux.png
  apps/watch-e2e/src/e2e/feature-film.spec.ts-snapshots/before-video-firefox-linux.png
  apps/watch-e2e/src/e2e/feature-film.spec.ts-snapshots/ff-landing-page-firefox-linux.png
  apps/watch-e2e/src/e2e/feature-film.spec.ts-snapshots/ff-navigated-page-firefox-linux.png
  apps/watch-e2e/src/e2e/filters.spec.ts-snapshots/see-all-landing-firefox-linux.png
Labels: type: fix, priority: now, effort: 1

#2175 fix: alpine missing openssl11 compat
  apps/api-journeys/Dockerfile
  apps/api-journeys/db/Dockerfile
  apps/api-languages/Dockerfile
  apps/api-languages/db/Dockerfile
  apps/api-media/Dockerfile
  apps/api-tags/Dockerfile
  apps/api-tags/db/Dockerfile
  apps/api-users/Dockerfile
  apps/api-videos/Dockerfile
  apps/api-videos/db/Dockerfile
Labels: type: fix, priority: now, effort: 1

#2181 feat: reduce watcher memory
  apps/api-journeys/project.json
  apps/api-languages/project.json
  apps/api-media/project.json
  apps/api-tags/project.json
  apps/api-users/project.json
  apps/api-videos/project.json
Labels: priority: 2day, type: feat, effort: 1

#2178 chore: node & npm bump
  .devcontainer/Dockerfile
Labels: priority: 2day, effort: 1, type: chore

#2163 fix: templates langauge select
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/LanguagesFilterPopper/LanguagesFilterPopper.tsx
Labels: type: fix, priority: soon, effort: 1

#2185 docs: update watch info
  apps/docs/docs/01-welcome.md
Labels: type: docs, priority: soon, effort: 1

#2190 refactor: move facebook google icons to shared ui folder
  apps/journeys-admin/src/components/SignIn/FacebookButton/FacebookButton.tsx
  apps/journeys-admin/src/components/SignIn/GoogleButton/GoogleButton.tsx
  apps/journeys-admin/src/components/SignIn/GoogleButton/GoogleIcon.tsx
  libs/shared/ui/src/components/icons/FacebookIcon.tsx
  libs/shared/ui/src/components/icons/GoogleIcon.tsx
Labels: priority: now, effort: 1

#2179 chore: nx bump
  .eslintrc.json
  apps/api-journeys/project.json
  apps/api-journeys/webpack.config.js
  apps/api-languages/project.json
  apps/api-languages/webpack.config.js
  apps/api-media/project.json
  apps/api-media/webpack.config.js
  apps/api-tags/project.json
  apps/api-tags/webpack.config.js
  apps/api-users/project.json
  apps/api-users/webpack.config.js
  apps/api-videos/project.json
  apps/api-videos/webpack.config.js
  apps/docs/.eslintrc.json
  apps/docs/project.json
  apps/journeys-admin/.eslintrc.json
  apps/journeys-admin/project.json
  apps/journeys/.eslintrc.json
  apps/journeys/project.json
  apps/nexus-admin/.eslintrc.json
  apps/nexus-admin/project.json
  apps/watch-e2e/src/e2e/chapter.spec.ts-snapshots/after-video-firefox-linux.png
  apps/watch-e2e/src/e2e/feature-film.spec.ts-snapshots/after-video-firefox-linux.png
  apps/watch/.eslintrc.json
  apps/watch/project.json
  libs/journeys/ui/.eslintrc.json
  libs/journeys/ui/project.json
  libs/nest/common/project.json
  libs/nest/decorators/project.json
  libs/nest/gqlAuthGuard/project.json
  libs/nest/powerBi/project.json
  libs/shared/ui-dynamic/.eslintrc.json
  libs/shared/ui-dynamic/project.json
  libs/shared/ui/.eslintrc.json
  libs/shared/ui/project.json
  libs/shared/ui/src/components/ThemeDecorator/ThemeDecorator.tsx
  libs/shared/ui/src/libs/sharedUiConfig/sharedUiConfig.tsx
  nx.json
  package-lock.json
  package.json
  tsconfig.base.json
Labels: priority: 2day, effort: 2, type: chore

#2172 feat: separate postgres env vars intermediate - part 1
  apps/api-journeys/.prisma-generate.env
  apps/api-journeys/infrastructure/locals.tf
  apps/api-journeys/infrastructure/main.tf
  apps/api-languages/.prisma-generate.env
  apps/api-languages/infrastructure/locals.tf
  apps/api-languages/infrastructure/main.tf
  apps/api-media/.prisma-generate.env
  apps/api-media/infrastructure/locals.tf
  apps/api-media/infrastructure/main.tf
  apps/api-tags/.prisma-generate.env
  apps/api-tags/infrastructure/locals.tf
  apps/api-tags/infrastructure/main.tf
  apps/api-users/.prisma-generate.env
  apps/api-users/infrastructure/locals.tf
  apps/api-users/infrastructure/main.tf
  apps/api-videos/.prisma-generate.env
  apps/api-videos/infrastructure/locals.tf
  apps/api-videos/infrastructure/main.tf
  infrastructure/modules/aws/aurora/main.tf
  infrastructure/modules/aws/aurora/variables.tf
Labels: priority: 2day, effort: 3, type: feat

#2167 fix: image gallery scrollbar
  apps/journeys-admin/src/components/Editor/Drawer/Drawer.tsx
Labels: type: fix, priority: soon, effort: 1

#2173 fix: duplicate on shared with me
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, type: fix, priority: soon

#2195 refactor: simplify editor
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/publisher/[journeyId].tsx
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/DescriptionEdit/DescriptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/TitleEdit/TitleEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/TitleEdit/TitleEdit.tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/Editor.tsx
  apps/journeys-admin/src/components/Editor/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/JourneyEdit/JourneyEdit.tsx
  apps/journeys-admin/src/components/Editor/JourneyEdit/index.ts
  apps/journeys-admin/src/components/Editor/SocialPreview/Message/SocialPreviewMessage.spec.tsx
  apps/journeys-admin/src/components/Editor/SocialPreview/Message/SocialPreviewMessage.tsx
  apps/journeys-admin/src/components/Editor/SocialPreview/Post/SocialPreviewPost.spec.tsx
  apps/journeys-admin/src/components/Editor/SocialPreview/Post/SocialPreviewPost.tsx
  apps/journeys-admin/src/components/Editor/SocialPreview/SocialPreview.tsx
  apps/journeys-admin/src/components/Editor/SocialProvider.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: priority: now, effort: 1, type: refactor

#2201 feat: new tags
  apps/api-tags/db/seed.ts
Labels: priority: soon, type: feat, effort: 1

#2174 feat: separate postgres env vars intermediate - part 2
  apps/api-journeys/.prisma-generate.env
  apps/api-journeys/Dockerfile
  apps/api-journeys/db/Dockerfile
  apps/api-journeys/db/schema.prisma
  apps/api-languages/.prisma-generate.env
  apps/api-languages/Dockerfile
  apps/api-languages/db/Dockerfile
  apps/api-languages/db/schema.prisma
  apps/api-media/.prisma-generate.env
  apps/api-media/Dockerfile
  apps/api-media/db/schema.prisma
  apps/api-tags/.prisma-generate.env
  apps/api-tags/Dockerfile
  apps/api-tags/db/Dockerfile
  apps/api-tags/db/schema.prisma
  apps/api-users/.prisma-generate.env
  apps/api-users/Dockerfile
  apps/api-users/db/schema.prisma
  apps/api-videos/.prisma-generate.env
  apps/api-videos/Dockerfile
  apps/api-videos/db/Dockerfile
  apps/api-videos/db/schema.prisma
Labels: priority: 2day, type: feat, effort: 1

#2205 feat: helpscout button can be clicked when language filter is open
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/LanguagesFilterPopper/LanguagesFilterPopper.tsx
Labels: type: fix, priority: soon, effort: 1

#2208 fix: copy to teams templates
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.spec.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.tsx
Labels: type: fix, effort: 3, priority: soon

#2209 fix: conditional helpscout theme for login
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
Labels: priority: 2day, type: fix, effort: 1

#2202 fix: shallow route help scout query params
  apps/journeys-admin/__generated__/GetLastActiveTeamIdAndTeams.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageMenuItem.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/LanguageMenuItem/LanguageMenuItem.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/Properties/JourneyLink/JourneyLink.spec.tsx
  apps/journeys-admin/src/components/Editor/Properties/JourneyLink/JourneyLink.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/AddJourneyButton/AddJourneyButton.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.tsx
  apps/journeys-admin/src/components/OnboardingPanel/data.ts
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.spec.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamDialog/CopyToTeamDialog.stories.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.spec.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.tsx
  apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamCreateForm/TeamCreateForm.spec.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamManageDialog/TeamManageWrapper/TeamManageWrapper.spec.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.spec.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.stories.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.spec.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.stories.tsx
  apps/journeys-admin/src/components/Team/TeamProvider/TeamProvider.spec.tsx
  apps/journeys-admin/src/components/Team/TeamProvider/TeamProvider.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.spec.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.stories.tsx
  apps/journeys-admin/src/components/Team/TeamUpdateDialog/TeamUpdateDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamUpdateDialog/TeamUpdateDialog.stories.tsx
  apps/journeys-admin/src/components/Team/UserTeamInviteForm/UserTeamInviteForm.spec.tsx
  apps/journeys-admin/src/components/VisitorsList/VisitorList.spec.tsx
Labels: type: fix, priority: soon, effort: 1

#2212 chore: trigger redeploy
  apps/api-journeys/db/seed.ts
  apps/api-languages/db/seed.ts
  apps/api-videos/db/seed.ts
Labels: priority: now, effort: 1, type: chore

#2197 fix: card theme
  apps/journeys/src/components/Conductor/Conductor.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
  libs/journeys/ui/src/libs/getStepTheme/getStepTheme.ts
Labels: type: fix, priority: soon, effort: 1

#2217 chore: redeploy api-journeys
  apps/api-journeys/db/seed.ts
Labels: priority: now, effort: 1, type: chore

#2210 fix: clear photo author
  apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
Labels: type: fix, priority: soon, effort: 1

#2213 feat: oembed fullscreen
  apps/journeys-admin/src/components/Editor/Properties/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Properties/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.tsx
  apps/journeys/pages/api/oembed.ts
  apps/journeys/pages/embed/test/[journeySlug].tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
Labels: effort: 2, priority: soon, type: feat

#2216 feat: substring matching for journey links
  libs/journeys/ui/src/libs/action/action.spec.ts
  libs/journeys/ui/src/libs/action/action.ts
Labels: type: fix, priority: now, effort: 1

#2220 fix: skip new team creation screen if new user is invited
  apps/journeys-admin/pages/onboarding-form.tsx
  apps/journeys-admin/pages/teams/new.tsx
  apps/journeys-admin/pages/users/terms-and-conditions.tsx
Labels: effort: 2, type: fix, priority: now

#2223 fix: remove discovery journeys
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
Labels: type: fix, priority: soon, effort: 1

#2214 fix: align icons vertically
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyListMenu/JourneyListMenu.tsx
Labels: type: fix, priority: soon, effort: 1

#2219 fix: card aspect ratio
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
Labels: effort: 2, type: fix, priority: soon

#2211 fix: access denied 500 error
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/src/components/AccessDenied/AccessDenied.spec.tsx
  apps/journeys-admin/src/components/AccessDenied/AccessDenied.stories.tsx
  apps/journeys-admin/src/components/AccessDenied/AccessDenied.tsx
  apps/journeys-admin/src/components/JourneyInvite/JourneyInvite.spec.tsx
  apps/journeys-admin/src/components/JourneyInvite/JourneyInvite.stories.tsx
  apps/journeys-admin/src/components/JourneyInvite/JourneyInvite.tsx
  apps/journeys-admin/src/components/JourneyInvite/index.ts
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#2224 fix: text block selection
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.tsx
  apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
Labels: type: fix, effort: 13, priority: soon

#2230 fix: hide most relevant with one tag
  apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
Labels: type: fix, priority: soon, effort: 1

#2225 fix: helpscout button scroll overlap
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts-snapshots/home-page-chrome-desktop-linux.png
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostSidePanel.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Drawer.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
  apps/journeys-admin/src/components/PageWrapper/SidePanel/SidePanel.tsx
Labels: effort: 2, type: fix, priority: now

#2232 feat: user team message queue
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.module.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.resolver.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.service.spec.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.service.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.spec.ts
Labels: effort: 2, priority: soon, type: feat

#2234 fix: zindex for video details drawer
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostForm.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLanguage/VideoLanguage.tsx
Labels: type: fix, priority: now, effort: 1

#2235 feat: user journeys email
  apps/api-journeys/src/app/emails/JourneyInvite.tsx
  apps/api-journeys/src/app/modules/userInvite/userInvite.service.spec.ts
  apps/api-journeys/src/app/modules/userInvite/userInvite.service.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.service.ts
  apps/api-journeys/tsconfig.app.json
  apps/api-users/src/app/modules/email/email.consumer.spec.ts
  apps/api-users/src/app/modules/email/email.consumer.ts
  apps/api-users/src/app/modules/email/email.module.ts
Labels: priority: soon, type: feat, effort: 1

#2244 fix: load more button on video library state
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromLocal/VideoFromLocal.tsx
Labels: type: fix, effort: 3, priority: soon

#2245 ci: update crowdin translations pr
  crowdin.yml
Labels: priority: soon, effort: 1, type: ci

#2250 ci: add missing env
  crowdin.yml
Labels: priority: now, effort: 1, type: ci

#2176 feat: separate postgres env vars intermediate - part 3
  apps/api-journeys/infrastructure/locals.tf
  apps/api-journeys/infrastructure/main.tf
  apps/api-languages/infrastructure/locals.tf
  apps/api-languages/infrastructure/main.tf
  apps/api-media/infrastructure/locals.tf
  apps/api-tags/infrastructure/locals.tf
  apps/api-tags/infrastructure/main.tf
  apps/api-users/infrastructure/locals.tf
  apps/api-videos/infrastructure/locals.tf
  apps/api-videos/infrastructure/main.tf
  infrastructure/modules/aws/aurora/main.tf
Labels: priority: 2day, effort: 2, type: feat

#2255 ci: update language code
  crowdin.yml
Labels: priority: now, effort: 1, type: ci

#2258 ci: crowdin add pr assignee and skip untranslated files
  crowdin.yml
Labels: priority: now, effort: 1, type: ci

#2262 chore: new crowdin translations
  libs/locales/ru-RU/apps-docs.json
  libs/locales/ru-RU/apps-journeys-admin.json
  libs/locales/ru-RU/apps-journeys.json
  libs/locales/ru-RU/apps-nexus-admin.json
  libs/locales/ru-RU/apps-watch.json
  libs/locales/ru-RU/common.json
  libs/locales/ru-RU/libs-journeys-ui.json
  libs/locales/tl-PH/apps-docs.json
  libs/locales/tl-PH/apps-journeys-admin.json
  libs/locales/tl-PH/apps-journeys.json
  libs/locales/tl-PH/apps-nexus-admin.json
  libs/locales/tl-PH/apps-watch.json
  libs/locales/tl-PH/common.json
  libs/locales/tl-PH/libs-journeys-ui.json
  libs/locales/zh-CN/apps-docs.json
  libs/locales/zh-CN/apps-journeys-admin.json
  libs/locales/zh-CN/apps-journeys.json
  libs/locales/zh-CN/apps-nexus-admin.json
  libs/locales/zh-CN/apps-watch.json
  libs/locales/zh-CN/common.json
  libs/locales/zh-CN/libs-journeys-ui.json
  libs/locales/zh-TW/apps-docs.json
  libs/locales/zh-TW/apps-journeys-admin.json
  libs/locales/zh-TW/apps-journeys.json
  libs/locales/zh-TW/apps-nexus-admin.json
  libs/locales/zh-TW/apps-watch.json
  libs/locales/zh-TW/common.json
  libs/locales/zh-TW/libs-journeys-ui.json
Labels: priority: soon, effort: 1, type: chore
