Repository JesusFilm/core, pull requests merged in 2024-09, with the labels that each got.

#3352 feat: videos count endpoint
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/__generated__/graphql-env.d.ts
  apps/api-videos/src/schema/video/video.spec.ts
  apps/api-videos/src/schema/video/video.ts
Labels: priority: soon, type: feat, effort: 1

#3345 fix: language selection and folder structure
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/LanguageContinentRefinements/LanguageContinentRefinements.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/LanguageContinentRefinements/LanguageContinentRefinements.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/LanguageContinentRefinements/RefinementGroup/RefinementGroup.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/LanguageContinentRefinements/RefinementGroup/RefinementGroup.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/LanguageContinentRefinements/RefinementGroup/index.ts
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/LanguageContinentRefinements/index.ts
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroup/RefinementGroup.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
Labels: effort: 2, type: fix, priority: soon

#3276 fix: add env variables to terraform
  apps/journeys-admin/infrastructure/locals.tf
Labels: type: fix, priority: now, effort: 1

#3339 feat: website mode api
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20240902005533_20240902005527/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/lib/fetchEmailDetails/fetchEmailDetails.spec.ts
  apps/api-journeys/src/app/lib/processUserIds/processUserIds.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
  apps/api-journeys/src/app/modules/block/image/image.graphql
  apps/api-journeys/src/app/modules/block/step/step.graphql
  apps/api-journeys/src/app/modules/email/emailEvents/emailEvents.consumer.spec.ts
  apps/api-journeys/src/app/modules/host/host.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/plausible/plausible.resolver.spec.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.tsx
Labels: effort: 3, priority: soon, type: feat, on stage

#3354 fix: update name to relation instead of prisma field
  apps/api-languages/src/schema/language/language.mock.ts
  apps/api-languages/src/schema/language/language.spec.ts
  apps/api-languages/src/schema/language/language.ts
  apps/api-languages/src/schema/language/languages.spec.ts
Labels: effort: 2, type: fix, priority: now, on stage

#3360 chore: migrate tags db into api-media
  apps/api-media/db/migrations/20240903021350_20240903021348/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/src/__generated__/pothos-types.ts
Labels: priority: now, effort: 1, type: chore, on stage

#3362 chore: migrate tags gql into api-media
  apps/api-gateway/schema.graphql
  apps/api-media/project.json
  apps/api-media/schema.graphql
  apps/api-media/src/schema/schema.ts
  apps/api-media/src/schema/tag/enums/index.ts
  apps/api-media/src/schema/tag/enums/service.ts
  apps/api-media/src/schema/tag/index.ts
  apps/api-media/src/schema/tag/objects/index.ts
  apps/api-media/src/schema/tag/objects/tagName.ts
  apps/api-media/src/schema/tag/tag.spec.ts
  apps/api-media/src/schema/tag/tag.ts
  apps/api-media/src/workers/cli.ts
  apps/api-media/src/workers/seed/config.ts
  apps/api-media/src/workers/seed/index.ts
  apps/api-media/src/workers/seed/service/index.ts
  apps/api-media/src/workers/seed/service/service.ts
  apps/api-media/src/workers/server.ts
  apps/api-tags/schema.graphql
  apps/api-tags/src/schema/builder.ts
  apps/api-tags/src/schema/language/index.ts
  apps/api-tags/src/schema/language/language.ts
  apps/api-tags/src/schema/schema.ts
  apps/docs/docs/02-getting-started/03-microservice-databases.mdx
Labels: priority: now, effort: 1, type: chore, on stage

#3335 feat: add chat buttons to drawer
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.tsx
Labels: priority: soon, type: feat, effort: 1

#3316 feat: api videos authentication
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/db/migrations/20240903172925_20240903172923/migration.sql
  apps/api-media/db/migrations/20240904011305_20240904011300/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/infrastructure/locals.tf
  apps/api-media/project.json
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/__generated__/pothos-types.ts
  apps/api-media/src/auth.ts
  apps/api-media/src/lib/graphql/gatewayGraphql.ts
  apps/api-media/src/lib/graphql/subgraphGraphql.ts
  apps/api-media/src/schema/bibleBook/bibleBook.spec.ts
  apps/api-media/src/schema/bibleCitation/bibleCitation.spec.ts
  apps/api-media/src/schema/builder.ts
  apps/api-media/src/schema/cloudflare/image/image.spec.ts
  apps/api-media/src/schema/cloudflare/video/video.spec.ts
  apps/api-media/src/schema/keyword/keyword.spec.ts
  apps/api-media/src/schema/schema.ts
  apps/api-media/src/schema/segmind/segmind.spec.ts
  apps/api-media/src/schema/tag/tag.spec.ts
  apps/api-media/src/schema/unsplash/unsplash.spec.ts
  apps/api-media/src/schema/user/enums/index.ts
  apps/api-media/src/schema/user/enums/mediaRole.ts
  apps/api-media/src/schema/user/index.ts
  apps/api-media/src/schema/user/user.spec.ts
  apps/api-media/src/schema/user/user.ts
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/videoVariant/videoVariant.spec.ts
  apps/api-media/src/workers/algolia/service/service.ts
  apps/api-media/src/workers/bigQuery/importers/languageSlugs/languageSlugs.ts
  apps/api-media/src/yoga.ts
  apps/api-media/tsconfig.json
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  libs/yoga/.babelrc
  libs/yoga/.eslintrc.json
  libs/yoga/README.md
  libs/yoga/jest.config.ts
  libs/yoga/project.json
  libs/yoga/src/firebaseClient/firebaseClient.ts
  libs/yoga/src/firebaseClient/index.ts
  libs/yoga/tsconfig.json
  libs/yoga/tsconfig.lib.json
  libs/yoga/tsconfig.spec.json
  tsconfig.base.json
Labels: effort: 5, priority: soon, type: feat, on stage

#3333 feat: display title and footer text
  apps/journeys-admin/__generated__/JourneySettingsUpdate.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/DisplayTitle/DisplayTitle.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/DisplayTitle/DisplayTitle.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/DisplayTitle/DisplayTitle.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/DisplayTitle/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.tsx
  apps/journeys-admin/src/libs/useJourneyUpdateMutation/useJourneyUpdateMutation.spec.tsx
  apps/journeys-admin/src/libs/useJourneyUpdateMutation/useJourneyUpdateMutation.ts
  libs/journeys/ui/src/components/StepFooter/StepFooter.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: soon, type: feat, on stage

#3370 fix: update strategies indexes
  apps/watch/src/components/StrategiesView/StrategySections/StrategySections.tsx
Labels: type: fix, priority: now, effort: 1

#3357 feat: eng 700 searchbar suggestions
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.stories.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/Suggestions/Suggestion/Suggestion.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/Suggestions/Suggestion/Suggestion.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/Suggestions/Suggestion/index.ts
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/Suggestions/Suggestions.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/Suggestions/Suggestions.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/Suggestions/index.ts
Labels: priority: 2day, effort: 3, type: feat

#3375 fix: api-gateway schema
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: type: fix, priority: soon, effort: 1

#3340 feat: multiple language selected
  apps/watch/src/components/StrategiesView/StrategiesView.spec.tsx
  libs/journeys/ui/src/components/SearchBar/LanguageButton/LanguageButton.tsx
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButton/LanguageButton.spec.tsx
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButton/LanguageButton.tsx
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButton/index.ts
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButtons.spec.tsx
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButtons.stories.tsx
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButtons.tsx
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/index.ts
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
Labels: priority: soon, type: feat, effort: 1

#3364 feat: eng 576 see all button on dropdown
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/LanguageContinentRefinements/LanguageContinentRefinements.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/LanguageContinentRefinements/LanguageContinentRefinements.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/LanguageContinentRefinements/RefinementGroup/RefinementGroup.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
Labels: priority: 2day, effort: 2, type: feat

#3371 fix: step slug slugify
  apps/api-journeys/src/app/modules/block/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/step/step.resolver.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#3361 refactor: journey rendering
  apps/journeys/pages/[hostname]/[journeySlug].tsx
  apps/journeys/pages/[hostname]/embed/[journeySlug].tsx
  apps/journeys/pages/home/[journeySlug].tsx
  apps/journeys/pages/home/embed/[journeySlug].tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
  apps/journeys/src/components/JourneyRenderer/JourneyRenderer.spec.tsx
  apps/journeys/src/components/JourneyRenderer/JourneyRenderer.tsx
  apps/journeys/src/components/JourneyRenderer/index.ts
  apps/journeys/src/components/WebView/WebView.spec.tsx
  apps/journeys/src/components/WebView/WebView.stories.tsx
  apps/journeys/src/components/WebView/WebView.tsx
  apps/journeys/src/components/WebView/index.ts
Labels: effort: 2, priority: soon, type: refactor, on stage

#3374 feat: step header display title
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.spec.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.stories.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
Labels: priority: soon, type: feat, effort: 1

#3365 chore: upgrade to mui v6
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.spec.tsx
  apps/journeys-admin/src/components/AccessDialog/NotificationSwitch/NotificationSwitch.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Chat/ChatOption/ChatOption.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Chat/ChatOption/Details/Details.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Credentials/Credentials.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Credentials/FormSlugSelect/FormSlugSelect.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Credentials/ProjectIdSelect/ProjectIdSelect.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/GrowthSpacesIntegrations/App/App.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/GrowthSpacesIntegrations/Route/Route.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/GrowthSpacesIntegrations/Select/Select.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/Action.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Icon/Icon.spec.tsx
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesIntegrationDetails/GrowthSpacesIntegrationDetails.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardText/JourneyCardText.spec.tsx
  apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.spec.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/DetailsForm/DetailsForm.spec.tsx
  apps/watch/src/components/DownloadDialog/DownloadDialog.spec.tsx
  libs/journeys/ui/src/components/CopyToTeamDialog/CopyToTeamDialog.spec.tsx
  libs/journeys/ui/src/components/CopyToTeamDialog/CopyToTeamDialog.tsx
  libs/journeys/ui/src/components/StepHeader/InformationButton/InformationButton.tsx
  libs/journeys/ui/src/components/Typography/Typography.tsx
  libs/shared/ui/src/components/ThemeProvider/ThemeProvider.spec.tsx
  libs/shared/ui/src/libs/themes/base/tokens/breakpoints.ts
  package-lock.json
  package.json
Labels: priority: now, effort: 1, type: chore

#3359 fix: video upload fetch ready to stream
  apps/api-media/src/schema/cloudflare/video/service.spec.ts
  apps/api-media/src/schema/cloudflare/video/service.ts
  apps/api-media/src/schema/cloudflare/video/video.spec.ts
  apps/api-media/src/schema/cloudflare/video/video.ts
  apps/api-media/src/yoga.ts
Labels: type: fix, priority: now, effort: 1, on stage

#3338 fix: social media title matches journey admin title upon journey
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/TitleEdit/TitleEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/TitleEdit/TitleEdit.tsx
  apps/journeys/pages/home/embed/[journeySlug].tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareButton.tsx
Labels: type: fix, priority: soon, effort: 1

#3377 feat: eng 705 searchbar dropdown tabs
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/Suggestions/Suggestions.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/Suggestions/Suggestions.tsx
Labels: effort: 2, priority: soon, type: feat

#3382 feat: add more languages
  apps/api-media/src/workers/algolia/service/languages.ts
  apps/api-media/src/workers/algolia/service/service.spec.ts
  apps/api-media/src/workers/algolia/service/service.ts
Labels: priority: 2day, effort: 1, type: chore, on stage

#3383 fix: apollo pagination cache for videos admin
  apps/videos-admin/src/libs/apollo/cache.ts
Labels: type: fix, priority: soon, effort: 1

#3387 perf: eng 843 lazy load all languages
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
Labels: priority: 2day, effort: 2, type: perf

#3413 feat: eng 849 language name in query
  apps/watch/src/components/StrategiesView/StrategiesView.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/LanguageContinentRefinements/LanguageContinentRefinements.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/LanguageContinentRefinements/RefinementGroup/RefinementGroup.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/LanguageContinentRefinements/RefinementGroup/RefinementGroup.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.spec.tsx
  libs/journeys/ui/src/libs/algolia/normalizeLanguage/index.ts
  libs/journeys/ui/src/libs/algolia/normalizeLanguage/normalizeLanguage.spec.ts
  libs/journeys/ui/src/libs/algolia/normalizeLanguage/normalizeLanguage.ts
  package-lock.json
  package.json
Labels: effort: 3, priority: soon, type: feat

#3384 feat: eng 844 dynamically show search query
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/Suggestions/Suggestions.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/Suggestions/Suggestions.tsx
Labels: priority: soon, type: feat, effort: 1

#3394 fix: remove api-videos generated file
  apps/api-videos/src/app/__generated__/graphql-env.d.ts
Labels: priority: 2day, type: fix, effort: 1

#3396 chore: remove deprecated subtitle table
  apps/api-media/db/migrations/20240906221011_20240906221009/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/src/__generated__/pothos-types.ts
  apps/api-media/src/schema/video/lib/videosFilter/videosFilter.spec.ts
  apps/api-media/src/schema/video/lib/videosFilter/videosFilter.ts
Labels: effort: 3, priority: soon, type: chore, on stage

#3432 fix: add unit tests for videos admin
  apps/videos-admin/src/components/AppNavbar/AppNavBar.spec.tsx
  apps/videos-admin/src/components/AppNavbar/AppNavbar.tsx
  apps/videos-admin/src/components/CenterPage/CenterPage.tsx
  apps/videos-admin/src/components/CenterPage/Centerpage.spec.tsx
  apps/videos-admin/src/components/Header/Header.spec.tsx
  apps/videos-admin/src/components/MenuButton/MenuButton.spec.tsx
  apps/videos-admin/src/components/MenuButton/MenuButton.tsx
  apps/videos-admin/src/components/MenuContent/MenuContent.spec.tsx
  apps/videos-admin/src/components/MenuContent/MenuContent.tsx
  apps/videos-admin/src/components/NavbarBreadcrumbs/NavbarBreadcrumbs.spec.tsx
  apps/videos-admin/src/components/NavbarBreadcrumbs/NavbarBreadcrumbs.tsx
  apps/videos-admin/src/components/OptionsMenu/OptionsMenu.spec.tsx
  apps/videos-admin/src/components/OptionsMenu/OptionsMenu.tsx
  apps/videos-admin/src/components/SideMenu/SideMenu.spec.tsx
  apps/videos-admin/src/components/SideMenuMobile/SIdeMenuMobile.spec.tsx
  apps/videos-admin/src/components/SideMenuMobile/SideMenuMobile.tsx
  apps/videos-admin/src/components/ToggleColorMode/ToggleColorMode.spec.tsx
  apps/videos-admin/src/components/ToggleColorMode/ToggleColorMode.tsx
Labels: type: fix, priority: soon, effort: 1

#3372 feat: eng 760 contain language selection in continent
  apps/watch/pages/watch/index.tsx
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButtons.spec.tsx
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButtons.stories.tsx
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButtons.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/LanguageContinentRefinements/index.ts
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroup/RefinementGroup.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroup/RefinementGroup.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroup/index.ts
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/index.ts
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
  libs/journeys/ui/src/libs/algolia/SearchBarProvider/SearchBarProvider.spec.tsx
  libs/journeys/ui/src/libs/algolia/SearchBarProvider/SearchBarProvider.tsx
  libs/journeys/ui/src/libs/algolia/SearchBarProvider/index.ts
Labels: type: fix, priority: soon, effort: 1

#3436 fix: extend journey type for menu and logo
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/image/image.graphql
  apps/api-journeys/src/app/modules/block/step/step.graphql
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/BlockActionDelete.ts
  apps/journeys-admin/__generated__/BlockDeleteForCoverImage.ts
  apps/journeys-admin/__generated__/BlockOrderUpdate.ts
  apps/journeys-admin/__generated__/CardCtaDelete.ts
  apps/journeys-admin/__generated__/CardFormDelete.ts
  apps/journeys-admin/__generated__/CardIntroDelete.ts
  apps/journeys-admin/__generated__/CardPollDelete.ts
  apps/journeys-admin/__generated__/CardQuoteDelete.ts
  apps/journeys-admin/__generated__/CardVideoDelete.ts
  apps/journeys-admin/__generated__/CardVideoRestore.ts
  apps/journeys-admin/__generated__/CoverBlockDelete.ts
  apps/journeys-admin/__generated__/CoverBlockRestore.ts
  apps/journeys-admin/__generated__/DuplicatedBlock.ts
  apps/journeys-admin/__generated__/GetFormBlock.ts
  apps/journeys-admin/__generated__/JourneyImageBlockDelete.ts
  apps/journeys-admin/__generated__/NewBlock.ts
  apps/journeys-admin/__generated__/PosterImageBlockDelete.ts
  apps/journeys-admin/__generated__/PosterImageBlockRestore.ts
  apps/journeys-admin/__generated__/RestoredBlock.ts
  apps/journeys-admin/__generated__/StepBlockCreateFromAction.ts
  apps/journeys-admin/__generated__/StepBlockCreateFromSocialPreview.ts
  apps/journeys-admin/__generated__/StepBlockDeleteFromAction.ts
  apps/journeys-admin/__generated__/StepBlockDeleteFromActionWithoutAction.ts
  apps/journeys-admin/__generated__/StepBlockDeleteFromSocialPreview.ts
  apps/journeys-admin/__generated__/StepBlockRestoreFromAction.ts
  apps/journeys-admin/__generated__/StepBlockRestoreFromSocialPreview.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: type: fix, priority: now, effort: 1, on stage

#3422 feat: remove menuStepBlock filter
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: priority: soon, type: feat, effort: 1, on stage

#3437 feat: eng 872 refinements count
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButton/LanguageButton.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
  libs/journeys/ui/src/libs/algolia/SearchBarProvider/SearchBarProvider.tsx
Labels: priority: soon, type: feat, effort: 1

#3379 fix: website toggle
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/WebsiteToggle/WebsiteToggle.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/WebsiteToggle/WebsiteToggle.tsx
Labels: type: fix, priority: soon, effort: 1

#3386 fix: card duplicate
  apps/api-journeys/src/app/modules/block/block.service.ts
Labels: type: fix, priority: soon, effort: 1

#3429 feat: arclight facade media components calls
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/db/migrations/20240910181459_20240910181456/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/video/video.ts
  apps/api-media/src/schema/videoVariant/videoVariant.ts
  apps/api-media/src/workers/bigQuery/importers/videoVariantDownloads/videoVariantDownloads.spec.ts
  apps/api-media/src/workers/bigQuery/importers/videoVariantDownloads/videoVariantDownloads.ts
  apps/api-media/src/workers/bigQuery/importers/videoVariants/videoVariants.spec.ts
  apps/api-media/src/workers/bigQuery/importers/videoVariants/videoVariants.ts
  apps/api-media/src/workers/bigQuery/importers/videos/videos.spec.ts
  apps/api-media/src/workers/bigQuery/importers/videos/videos.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/[languageId]/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/route.ts
  apps/arclight/src/app/v2/media-components/route.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 5, priority: soon, type: feat, on stage

#3440 fix: refinement groups to be using grid
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.tsx
Labels: type: fix, priority: now, effort: 1

#3369 feat: website navigation
  apps/journeys/pages/[hostname]/[journeySlug]/[stepSlug].tsx
  apps/journeys/pages/home/[journeySlug]/[stepSlug].tsx
  apps/journeys/src/components/JourneyRenderer/JourneyRenderer.tsx
  apps/journeys/src/components/WebView/WebView.spec.tsx
  apps/journeys/src/components/WebView/WebView.stories.tsx
  apps/journeys/src/components/WebView/WebView.tsx
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Form/Form.tsx
  libs/journeys/ui/src/components/RadioOption/RadioOption.spec.tsx
  libs/journeys/ui/src/components/RadioOption/RadioOption.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
  libs/journeys/ui/src/libs/action/action.ts
  libs/journeys/ui/src/libs/getNextStepSlug/getNextStepSlug.spec.tsx
  libs/journeys/ui/src/libs/getNextStepSlug/getNextStepSlug.ts
  libs/journeys/ui/src/libs/getNextStepSlug/index.ts
Labels: priority: soon, type: feat, effort: 1

#3443 fix: remove dependencies that triggers default selection
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
Labels: type: fix, priority: now, effort: 1

#3435 feat: website footer
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/WebsiteToggle/WebsiteToggle.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
  libs/journeys/ui/src/components/StepHeader/InformationButton/InformationButton.tsx
Labels: effort: 2, priority: soon, type: feat

#3446 feat: watch middleware
  apps/watch/middleware.spec.ts
  apps/watch/middleware.ts
  apps/watch/setupTests.tsx
Labels: priority: soon, type: feat, effort: 1

#3453 feat: use country query
  apps/journeys-admin/__generated__/GetCountry.ts
  apps/journeys/__generated__/GetCountry.ts
  apps/watch/__generated__/GetCountry.ts
  libs/journeys/ui/src/libs/useCountryQuery/__generated__/GetCountry.ts
  libs/journeys/ui/src/libs/useCountryQuery/data.ts
  libs/journeys/ui/src/libs/useCountryQuery/index.ts
  libs/journeys/ui/src/libs/useCountryQuery/useCountryQuery.mock.ts
  libs/journeys/ui/src/libs/useCountryQuery/useCountryQuery.spec.tsx
  libs/journeys/ui/src/libs/useCountryQuery/useCountryQuery.ts
Labels: priority: now, type: feat, effort: 1

#3456 feat: get top spoken languages
  libs/journeys/ui/src/libs/algolia/getTopSpokenLanguages/getTopSpokenLanguages.spec.ts
  libs/journeys/ui/src/libs/algolia/getTopSpokenLanguages/getTopSpokenLanguages.ts
  libs/journeys/ui/src/libs/algolia/getTopSpokenLanguages/index.ts
Labels: priority: soon, type: feat, effort: 1

#3457 fix: disable add block fab for video block steps
  apps/journeys-admin/src/components/Editor/Fab/Fab.tsx
Labels: type: fix, priority: soon, effort: 1

#3458 fix: journey builder formatting issues
  libs/journeys/ui/src/components/Typography/Typography.tsx
Labels: type: fix, priority: now, effort: 1

#3461 fix: github danger workflow
  .github/workflows/danger.yml
Labels: type: fix, priority: now, effort: 1

#3449 feat: cloudflare video images
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/db/migrations/20240910213703_20240910213701/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/__generated__/pothos-types.ts
  apps/api-media/src/schema/cloudflare/image/enums/imageAspectRatio.ts
  apps/api-media/src/schema/cloudflare/image/enums/index.ts
  apps/api-media/src/schema/cloudflare/image/image.spec.ts
  apps/api-media/src/schema/cloudflare/image/image.ts
  apps/api-media/src/schema/cloudflare/image/index.ts
  apps/api-media/src/schema/cloudflare/image/inputs/imageInput.ts
  apps/api-media/src/schema/cloudflare/image/inputs/index.ts
  apps/api-media/src/schema/segmind/segmind.spec.ts
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/video/video.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: 2day, effort: 5, type: feat

#3452 feat: add a loading state to languages dropdown
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.tsx
Labels: effort: 2, priority: soon, type: feat

#3385 feat: eng 827 clear all
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.spec.tsx
Labels: priority: 2day, effort: 2, type: feat

#3465 chore: add stories to videos admin
  .storybook/main.ts
  apps/videos-admin/.eslintrc.json
  apps/videos-admin/src/app/[locale]/(dashboard)/_DashboardLayout/DashboardLayout.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoList.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoList.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoList.tsx
  apps/videos-admin/src/components/AppNavbar/AppNavBar.stories.tsx
  apps/videos-admin/src/components/AppNavbar/AppNavbar.tsx
  apps/videos-admin/src/components/CenterPage/CenterPage.stories.tsx
  apps/videos-admin/src/components/Header/Header.stories.tsx
  apps/videos-admin/src/components/MenuButton/MenuButton.stories.tsx
  apps/videos-admin/src/components/MenuContent/MenuContent.stories.tsx
  apps/videos-admin/src/components/MenuContent/MenuContent.tsx
  apps/videos-admin/src/components/NavbarBreadcrumbs/NavBarBreadcrumbs.stories.tsx
  apps/videos-admin/src/components/NavbarBreadcrumbs/NavbarBreadcrumbs.tsx
  apps/videos-admin/src/components/OptionsMenu/OptionsMenu.stories.tsx
  apps/videos-admin/src/components/SideMenu/SideMenu.stories.tsx
  apps/videos-admin/src/components/SideMenuMobile/SideMenuMobile.stories.tsx
  apps/videos-admin/src/components/ToggleColorMode/ToggleColorMode.stories.tsx
  apps/videos-admin/src/libs/storybookConfig/index.ts
  apps/videos-admin/src/libs/storybookConfig/videosAdminConfig.tsx
Labels: type: fix, effort: 3, priority: soon, chromatic

#3467 fix: language buttons hydration error
  apps/watch/next-env.d.ts
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButtons.tsx
Labels: type: fix, priority: now, effort: 1

#3466 feat: enter key closes the dropdown
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
Labels: priority: soon, type: feat, effort: 1

#3472 feat: grab all the languages from algolia
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.tsx
Labels: type: fix, priority: now, effort: 1

#3433 feat: eng 871 dynamically update language suggestions
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroup/RefinementGroup.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/Suggestions/Suggestions.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/Suggestions/Suggestions.tsx
  libs/journeys/ui/src/libs/algolia/SearchBarProvider/SearchBarProvider.spec.tsx
  libs/journeys/ui/src/libs/algolia/SearchBarProvider/SearchBarProvider.tsx
  libs/journeys/ui/src/libs/algolia/languageUtils/index.ts
  libs/journeys/ui/src/libs/algolia/languageUtils/languageUtils.spec.ts
  libs/journeys/ui/src/libs/algolia/languageUtils/languageUtils.ts
  libs/journeys/ui/src/libs/algolia/normalizeLanguage/index.ts
  libs/journeys/ui/src/libs/algolia/normalizeLanguage/normalizeLanguage.spec.ts
  libs/journeys/ui/src/libs/algolia/normalizeLanguage/normalizeLanguage.ts
Labels: priority: 2day, effort: 2, type: feat

#3476 feat: cloudflare image importer
  apps/api-media/schema.graphql
  apps/api-media/src/schema/cloudflare/image/service.ts
  apps/api-media/src/workers/bigQuery/importers/index.ts
  apps/api-media/src/workers/bigQuery/importers/videoImages/index.ts
  apps/api-media/src/workers/bigQuery/importers/videoImages/videoImages.spec.ts
  apps/api-media/src/workers/bigQuery/importers/videoImages/videoImages.ts
  apps/api-media/src/workers/bigQuery/service/service.spec.ts
  apps/api-media/src/workers/bigQuery/service/service.ts
Labels: effort: 13, priority: soon, type: feat, on stage

#3489 fix: plausible token ability
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: type: fix, priority: now, effort: 1, on stage

#3493 fix: swap analytics chat widget icon order
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CardAnalytics/CardAnalytics.tsx
Labels: type: fix, priority: soon, effort: 1

#3492 chore: add analytics button clicked field
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20240916014534_20240916014532/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.graphql
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.spec.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
Labels: priority: soon, effort: 1, type: chore, on stage

#3475 feat: display logo
  apps/journeys/next-env.d.ts
  libs/journeys/ui/src/components/StepHeader/Logo/Logo.spec.tsx
  libs/journeys/ui/src/components/StepHeader/Logo/Logo.stories.tsx
  libs/journeys/ui/src/components/StepHeader/Logo/Logo.tsx
  libs/journeys/ui/src/components/StepHeader/Logo/index.ts
  libs/journeys/ui/src/components/StepHeader/StepHeader.spec.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.stories.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
Labels: effort: 2, priority: soon, type: feat

#3445 feat: country language selector
  apps/journeys-admin/__generated__/GetCountry.ts
  apps/journeys/__generated__/GetCountry.ts
  apps/watch/__generated__/GetCountry.ts
  apps/watch/middleware.ts
  apps/watch/next.config.js
  libs/journeys/ui/src/components/SearchBar/SearchBar.stories.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/CountryLanguageSelector.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/CountryLanguageSelector.stories.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/CountryLanguageSelector.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/data.ts
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/index.ts
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
  libs/journeys/ui/src/libs/algolia/getTopSpokenLanguages/getTopSpokenLanguages.spec.ts
  libs/journeys/ui/src/libs/algolia/getTopSpokenLanguages/getTopSpokenLanguages.ts
  libs/journeys/ui/src/libs/useCountryQuery/__generated__/GetCountry.ts
  libs/journeys/ui/src/libs/useCountryQuery/data.ts
  libs/journeys/ui/src/libs/useCountryQuery/useCountryQuery.ts
Labels: priority: soon, type: feat, effort: 1

#3504 fix: update strategies to consume excerpt
  apps/watch/next-env.d.ts
  apps/watch/src/components/StrategiesView/StrategySections/StrategySection/data.ts
  apps/watch/src/libs/algolia/useAlgoliaStrategies/useAlgoliaStrategies.spec.ts
  apps/watch/src/libs/algolia/useAlgoliaStrategies/useAlgoliaStrategies.ts
Labels: type: fix, priority: now, effort: 1

#3495 fix: add helpscout message pop up on first view
  apps/journeys-admin/__generated__/GetPlausibleDashboardViewed.ts
  apps/journeys-admin/__generated__/GetPlausibleJourneyFlowViewed.ts
  apps/journeys-admin/__generated__/UpdatePlausibleDashboardViewed.ts
  apps/journeys-admin/__generated__/UpdatePlausibleJourneyFlowViewed.ts
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Labels: type: fix, priority: soon, effort: 1

#3490 fix: language row horizontal alignment
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroup/RefinementGroup.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroup/RefinementGroup.tsx
Labels: type: fix, priority: now, effort: 1

#3507 fix: embed journey layout
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/EmbedJourneyDialog/EmbedJourneyDialog.tsx
Labels: type: fix, priority: soon, effort: 1

#3506 fix: move labels inside textfield
  apps/journeys-admin/src/components/Editor/Toolbar/TitleDescriptionDialog/TitleDescriptionDialog.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#3470 feat: step header button
  apps/journeys-admin-e2e/src/e2e/discover/card-level-actions.spec.ts
  libs/journeys/ui/src/components/StepHeader/StepHeader.spec.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeaderMenu/StepHeaderMenu.spec.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeaderMenu/StepHeaderMenu.stories.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeaderMenu/StepHeaderMenu.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeaderMenu/index.ts
  libs/journeys/ui/src/components/StepHeader/utils/getMenuIcon.ts
Labels: priority: soon, type: feat, effort: 1

#3487 fix: allow sliding on mobile when analytics enabled
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
Labels: type: fix, priority: soon, effort: 1

#3510 feat: videojs image improvements
  libs/shared/ui/src/libs/defaultVideoJsOptions/defaultVideoJsOptions.spec.ts
  libs/shared/ui/src/libs/defaultVideoJsOptions/defaultVideoJsOptions.ts
  package-lock.json
  package.json
Labels: effort: 5, priority: soon, type: feat

#3514 fix: update country detector
  apps/watch/middleware.spec.ts
  apps/watch/middleware.ts
  apps/watch/pages/api/jf/watch.html/geolocation.ts
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/CountryLanguageSelector.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/CountryLanguageSelector.stories.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/CountryLanguageSelector.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/data.ts
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.spec.tsx
Labels: type: fix, priority: now, effort: 1, on stage

#3518 fix: move country detector to searchbar
  apps/watch/src/components/StrategiesView/StrategiesView.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/CountryLanguageSelector.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/CountryLanguageSelector.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/data.ts
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
  libs/journeys/ui/src/components/SearchBar/data.ts
Labels: type: fix, priority: now, effort: 1

#3520 fix: next steps logo navigates to journey list
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Labels: type: fix, priority: soon, effort: 1

#3477 fix: tidy up top bar on mobile
  apps/journeys-admin-e2e/src/pages/journey-page.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DetailsItem/DetailsItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DetailsItem/DetailsItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DetailsItem/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/Item/Item.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/JourneyDetails/JourneyDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/JourneyDetails/JourneyDetails.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/JourneyDetails/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, type: fix, priority: soon

#3505 fix: nextjs custom domain rewrite
  apps/journeys/pages/[hostname]/[journeySlug].tsx
  apps/journeys/pages/[hostname]/index.tsx
Labels: type: fix, priority: soon, effort: 1, on stage

#3508 refactor: admin pagination bullets
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.spec.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.tsx
Labels: priority: soon, effort: 1, type: refactor

#3521 fix: move geolocation to api root folder
  apps/watch/pages/api/geolocation.ts
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
Labels: type: fix, priority: now, effort: 1

#3523 fix: page title verify email
  apps/journeys-admin/pages/users/verify.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#3473 feat: set displayTitle to empty string
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/DisplayTitle/DisplayTitle.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/DisplayTitle/DisplayTitle.tsx
Labels: priority: soon, type: feat, effort: 1

#3526 fix: drop dev indices strategy sections
  apps/watch/next.config.js
  apps/watch/src/components/StrategiesView/StrategySections/StrategySections.tsx
Labels: type: fix, priority: now, effort: 1, on stage

#3500 refactor: eng 927 instant search provider refactor
  apps/watch/pages/_app.tsx
  apps/watch/pages/strategies/index.tsx
  apps/watch/pages/watch/[part1]/[part2].tsx
  apps/watch/pages/watch/[part1]/[part2]/[part3].tsx
  apps/watch/pages/watch/index.tsx
  apps/watch/pages/watch/videos.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/data.ts
  libs/journeys/ui/src/libs/algolia/InstantSearchProvider/InstantSearchProvider.spec.tsx
  libs/journeys/ui/src/libs/algolia/InstantSearchProvider/InstantSearchProvider.tsx
  libs/journeys/ui/src/libs/algolia/InstantSearchProvider/index.ts
Labels: priority: 2day, effort: 2, type: refactor

#3532 feat: increase analytics resiliency
  .kube/config
  apps/api-analytics/infrastructure/deploy-stage.sh
  apps/api-analytics/infrastructure/deploy.sh
  apps/api-analytics/infrastructure/snapscheduler.yaml
  apps/api-analytics/infrastructure/snapshot-class.yaml
  apps/api-analytics/infrastructure/storage-class.yaml
  apps/api-analytics/infrastructure/values-prod.yaml
  apps/api-analytics/infrastructure/values-stage.yaml
  apps/api-analytics/infrastructure/volume-snapshot.yaml
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/main.tf
  infrastructure/kube/snapscheduler/deploy.sh
  infrastructure/kube/storage/deploy-prod.sh
  infrastructure/kube/storage/deploy-stage.sh
  infrastructure/modules/aws/eks/main.tf
  infrastructure/modules/aws/eks/variables.tf
Labels: effort: 13, priority: soon, type: feat

#3491 perf: eng 913 lazy load dropdown
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
  libs/journeys/ui/src/libs/algolia/SearchBarProvider/SearchBarProvider.tsx
  libs/journeys/ui/src/libs/algolia/SearchBarProvider/index.ts
  libs/journeys/ui/src/libs/useLanguagesContinentsQuery/index.ts
  libs/journeys/ui/src/libs/useLanguagesContinentsQuery/sortLanguageContinents/data.ts
  libs/journeys/ui/src/libs/useLanguagesContinentsQuery/sortLanguageContinents/index.ts
  libs/journeys/ui/src/libs/useLanguagesContinentsQuery/sortLanguageContinents/sortLanguageContinents.spec.tsx
  libs/journeys/ui/src/libs/useLanguagesContinentsQuery/sortLanguageContinents/sortLanguageContinents.tsx
  libs/journeys/ui/src/libs/useLanguagesContinentsQuery/useLanguagesContinentsQuery.ts
Labels: effort: 5, priority: soon, type: perf

#3528 fix: text overflow on small devices
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/Suggestions/Suggestion/Suggestion.tsx
Labels: type: fix, priority: now, effort: 1

#3544 refactor: info button spacing
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
  libs/journeys/ui/src/components/StepHeader/InformationButton/InformationButton.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
Labels: priority: soon, effort: 1, type: refactor

#3543 fix: support cf country header
  apps/watch/pages/api/geolocation.ts
Labels: type: fix, priority: now, effort: 1, on stage

#3525 fix: text rendering
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
Labels: type: fix, priority: soon, effort: 1

#3530 refactor: migrate from react gtm module to next third parties
  apps/journeys-admin/pages/_app.tsx
  apps/journeys/pages/_app.tsx
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/Conductor/HotkeyNavigation/HotkeyNavigation.spec.tsx
  apps/journeys/src/components/Conductor/HotkeyNavigation/HotkeyNavigation.tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.spec.tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.spec.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
  apps/journeys/src/components/WebView/WebView.spec.tsx
  apps/journeys/src/components/WebView/WebView.tsx
  apps/watch/pages/_app.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/components/TeamProvider/TeamProvider.spec.tsx
  libs/journeys/ui/src/components/TeamProvider/TeamProvider.tsx
  libs/journeys/ui/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.spec.tsx
  libs/journeys/ui/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.spec.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.spec.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.tsx
  package-lock.json
  package.json
Labels: priority: soon, effort: 1, type: refactor

#3536 fix: video description carriage return code
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoDescription/VideoDescription.tsx
Labels: type: fix, priority: soon, effort: 1

#3542 fix: enable journey map draggable in analytics mode
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
Labels: type: fix, priority: soon, effort: 1

#3529 fix: handle authorization better on custom domains front end
  apps/journeys-admin/__generated__/GetLastActiveTeamIdAndTeams.ts
  apps/journeys-admin/__generated__/TeamCreate.ts
  apps/journeys-admin/src/components/Team/CustomDomainDialog/CustomDomainDialog.spec.tsx
  apps/journeys-admin/src/components/Team/CustomDomainDialog/CustomDomainDialog.tsx
  apps/journeys-admin/src/components/Team/CustomDomainDialog/DefaultJourneyForm/DefaultJourneyForm.spec.tsx
  apps/journeys-admin/src/components/Team/CustomDomainDialog/DefaultJourneyForm/DefaultJourneyForm.tsx
  apps/journeys-admin/src/components/Team/CustomDomainDialog/DomainNameForm/DomainNameForm.spec.tsx
  apps/journeys-admin/src/components/Team/CustomDomainDialog/DomainNameForm/DomainNameForm.tsx
  apps/journeys-admin/src/components/Team/TeamAvatars/TeamAvatars.spec.tsx
  apps/journeys-admin/src/components/Team/TeamAvatars/TeamAvatars.stories.tsx
  apps/journeys-admin/src/components/Team/TeamUpdateDialog/TeamUpdateDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamUpdateDialog/TeamUpdateDialog.tsx
  apps/journeys-admin/src/libs/useCurrentUserLazyQuery/useCurrentUserLazyQuery.mock.ts
  apps/journeys-admin/src/libs/useTeamCreateMutation/useTeamCreateMutation.tsx
  apps/journeys/__generated__/GetLastActiveTeamIdAndTeams.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch/__generated__/GetLastActiveTeamIdAndTeams.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/TeamProvider/TeamProvider.mock.ts
  libs/journeys/ui/src/components/TeamProvider/TeamProvider.tsx
  libs/journeys/ui/src/components/TeamProvider/__generated__/GetLastActiveTeamIdAndTeams.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, type: fix, priority: soon

#3496 fix: slider style
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Logo/Logo.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Logo/Logo.tsx
Labels: priority: soon, effort: 1, type: refactor

#3551 fix: image url quality and optimization
  apps/watch/src/components/ResourcesView/ResourceSections/ResourceCard/ResourceCard.spec.tsx
  apps/watch/src/components/ResourcesView/ResourceSections/ResourceCard/ResourceCard.tsx
  libs/journeys/ui/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
Labels: type: fix, priority: soon, effort: 1

#3545 fix: add block button being cut off on safari
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
Labels: type: fix, priority: soon, effort: 1

#3555 fix: disable page side scroll
  apps/watch/src/components/PageWrapper/PageWrapper.tsx
Labels: type: fix, priority: soon, effort: 1

#3569 Revert "fix(deps): update dependency @nestjs/graphql to v12.2.0"
  package-lock.json
Labels: type: fix, priority: now, effort: 1

#3547 fix: browser back navigation
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
Labels: type: fix, priority: soon, effort: 1, on stage

#3570 fix: apollo cache rehydration
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/Drawer.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
  apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
  apps/journeys-admin/src/libs/apolloClient/cache.ts
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: now, effort: 1

#3560 fix: eng 961 empty search doesnt reset the list in strategies
  apps/watch/pages/resources/index.tsx
  apps/watch/src/components/ResourcesView/ResourceSections/ResourceSections.tsx
Labels: type: fix, priority: soon, effort: 1

#3546 refactor: eng 908 searchbar provider refactor
  apps/watch/src/components/ResourcesView/ResourcesView.spec.tsx
  apps/watch/src/components/ResourcesView/ResourcesView.tsx
  apps/watch/src/components/WatchHomePage/WatchHomePage.tsx
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButtons.spec.tsx
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButtons.stories.tsx
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButtons.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/CountryLanguageSelector.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/CountryLanguageSelector.stories.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/CountryLanguageSelector/CountryLanguageSelector.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroup/RefinementGroup.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroup/RefinementGroup.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
  libs/journeys/ui/src/libs/algolia/SearchBarProvider/SearchBarProvider.spec.tsx
  libs/journeys/ui/src/libs/algolia/SearchBarProvider/SearchBarProvider.tsx
  libs/journeys/ui/src/libs/algolia/SearchBarProvider/index.ts
  libs/journeys/ui/src/libs/useSortLanguageContinents/useSortLanguageContinents.spec.tsx
Labels: effort: 8, priority: soon, type: refactor

#3563 refactor: videos index segment
  apps/watch/pages/watch/videos.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
  apps/watch/src/components/WatchHomePage/WatchHomePage.tsx
Labels: priority: 2day, effort: 1, type: refactor

#3474 feat: disable style for default next step
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
Labels: priority: soon, type: feat, effort: 1

#3559 fix: add ability to change language from top bar
  apps/journeys-admin-e2e/src/e2e/discover/card-level-actions.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/custom-journey.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/journey-level-actions.spec.ts
  apps/journeys-admin-e2e/src/pages/card-level-actions.ts
  apps/journeys-admin-e2e/src/pages/journey-page.ts
  apps/journeys-admin/__generated__/JourneyDescUpdate.ts
  apps/journeys-admin/__generated__/JourneyLanguageUpdate.ts
  apps/journeys-admin/__generated__/JourneySettingsUpdate.ts
  apps/journeys-admin/__generated__/JourneyTitleUpdate.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DescriptionItem/DescriptionDialog/DescriptionDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DescriptionItem/DescriptionDialog/DescriptionDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DescriptionItem/DescriptionDialog/DescriptionDialog.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DescriptionItem/DescriptionDialog/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DescriptionItem/DescriptionItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DescriptionItem/DescriptionItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DescriptionItem/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DetailsItem/DetailsItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DetailsItem/DetailsItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/LanguageItem/LanguageDialog/LanguageDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/LanguageItem/LanguageDialog/LanguageDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/LanguageItem/LanguageDialog/LanguageDialog.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/LanguageItem/LanguageDialog/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/LanguageItem/LanguageItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/LanguageItem/LanguageItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/LanguageItem/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TitleItem/TitleDialog/TitleDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TitleItem/TitleDialog/TitleDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TitleItem/TitleDialog/TitleDialog.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TitleItem/TitleDialog/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TitleItem/TitleItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TitleItem/TitleItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TitleItem/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetailsDialog/JourneyDetailsDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetailsDialog/JourneyDetailsDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetailsDialog/JourneyDetailsDialog.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetailsDialog/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/TitleDescriptionDialog/TitleDescriptionDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/TitleDescriptionDialog/TitleDescriptionDialog.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/TitleDescriptionDialog/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
  apps/journeys-admin/src/libs/useJourneyUpdateMutation/useJourneyUpdateMutation.spec.tsx
  apps/journeys-admin/src/libs/useJourneyUpdateMutation/useJourneyUpdateMutation.ts
  libs/journeys/ui/src/libs/useLanguagesQuery/useLanguagesQuery.mock.ts
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.tsx
Labels: effort: 5, type: fix, priority: soon

#3552 feat: add formblock deletes to seed
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/seed.ts
  apps/api-journeys/db/seeds/formBlocksDelete.ts
  apps/api-journeys/db/seeds/playwrightUserAccess.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.graphql
Labels: effort: 2, priority: soon, type: refactor, on stage

#3561 feat: eng 957 resources url
  apps/watch/pages/resources/index.tsx
  apps/watch/pages/watch/index.tsx
  apps/watch/src/libs/algolia/instantSearchRouter/instantSearchRouter.spec.ts
  apps/watch/src/libs/algolia/instantSearchRouter/instantSearchRouter.ts
Labels: priority: soon, type: feat, effort: 1

#3554 fix: replace width with min width on language button
  libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButton/LanguageButton.tsx
Labels: type: fix, priority: soon, effort: 1

#3571 fix: next button on terms and conditions page
  apps/journeys-admin-e2e/src/pages/register-Page.ts
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.spec.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.tsx
Labels: type: fix, priority: soon, effort: 1

#3574 fix: select options not displaying
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
Labels: type: fix, priority: now, effort: 1

#3381 feat: top panel add an icon for responds
  apps/journeys-admin/__generated__/GetJourneyVisitorsCountWithTextResponses.ts
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/Items.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/Items.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ResponsesItem/ResponsesItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ResponsesItem/ResponsesItem.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ResponsesItem/ResponsesItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ResponsesItem/index.ts
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/Inbox2.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: priority: soon, type: feat, effort: 1, chromatic

#3553 feat: menu card content
  apps/journeys-admin/__generated__/MenuBlockCreate.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Menu/MenuActionButton/MenuActionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Menu/MenuActionButton/MenuActionButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Menu/MenuActionButton/data.ts
  apps/journeys-admin/src/libs/useMenuBlockCreateMutation/useMenuBlockCreateMutation.mock.ts
  apps/journeys-admin/src/libs/useMenuBlockCreateMutation/useMenuBlockCreateMutation.spec.tsx
  apps/journeys-admin/src/libs/useMenuBlockCreateMutation/useMenuBlockCreateMutation.ts
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#3581 feat: swap apollo router for hive gateway
  .devcontainer/post-create-command.sh
  .github/workflows/api-deploy-prod.yml
  .github/workflows/api-deploy-stage.yml
  .github/workflows/api-deploy-worker.yml
  .github/workflows/autofix.ci.yml
  .vscode/settings.json
  Procfile
  apps/api-analytics/project.json
  apps/api-analytics/schema.graphql
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-analytics/src/schema/index.ts
  apps/api-analytics/src/schema/schema.ts
  apps/api-gateway/Dockerfile
  apps/api-gateway/gateway.config.ts
  apps/api-gateway/gateway.prod.config.ts
  apps/api-gateway/infrastructure/locals.tf
  apps/api-gateway/project.json
  apps/api-gateway/router.prod.yaml
  apps/api-gateway/router.yaml
  apps/api-gateway/routerSchema.json
  apps/api-gateway/schema.graphql
  apps/api-gateway/supergraph.yml
  apps/api-journeys/project.json
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/project.json
  apps/api-languages/schema.graphql
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-languages/src/schema/index.ts
  apps/api-languages/src/schema/schema.ts
  apps/api-media/project.json
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/schema/index.ts
  apps/api-media/src/schema/schema.ts
  apps/api-users/project.json
  apps/api-users/schema.graphql
  apps/api-users/src/schema/index.ts
  apps/api-users/src/schema/schema.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/main.tf
  package-lock.json
  package.json
  tools/scripts/generate-graphql.sh
Labels: priority: now, effort: 13, type: feat, on stage

#3562 refactor: drop form fields from prisma
  apps/api-journeys/db/migrations/20240925032256_20240925032254/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/db/seeds/formBlocksDelete.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.spec.ts
Labels: priority: soon, effort: 1, type: refactor, on stage

#3524 feat: default journey accessible form the root domain
  apps/journeys/pages/[hostname]/[journeySlug].tsx
  apps/journeys/pages/[hostname]/index.tsx
  libs/locales/en/apps-journeys.json
Labels: priority: soon, type: feat, effort: 1, on stage

#3577 fix: add visitors count next to the analytics icon
  apps/journeys-admin/__generated__/GetJourneyPlausibleVisitors.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsOverlaySwitch/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/AnalyticsItem/AnalyticsItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/AnalyticsItem/AnalyticsItem.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/AnalyticsItem/AnalyticsItem.tsx
Labels: type: fix, priority: soon, effort: 1

#3585 fix: use name instead of namelanguage in slug filter
  apps/api-languages/src/workers/bigQuery/importers/languageSlugs/languageSlugs.ts
Labels: type: fix, effort: 3, priority: soon
