Repository JesusFilm/core, pull requests merged in 2024-02, with the labels that each got.

#2237 fix: node branching styling
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.tsx
  apps/journeys-admin/src/components/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/JourneyFlow/edges/ButtonEdge.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/BaseNode.tsx
Labels: type: fix, effort: 3, priority: soon

#2162 test: playwright admin tests
  .github/workflows/app-deploy.yml
  .gitignore
  apps/journeys-admin-e2e/playwright.config.ts
  apps/journeys-admin-e2e/src/e2e/existing-user.spec.ts
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts
  apps/journeys-admin-e2e/src/e2e/response-time.spec.ts
  apps/journeys-admin-e2e/src/e2e/user-creation.spec.ts
  apps/journeys-admin-e2e/src/framework/actions.ts
  apps/journeys-admin-e2e/src/framework/helpers.ts
  apps/journeys-admin-e2e/src/pages/home-page.ts
  apps/journeys-admin-e2e/src/pages/journey-page.ts
  apps/journeys-admin-e2e/src/pages/landing-page.ts
  apps/journeys-admin-e2e/src/pages/left-nav.ts
  apps/journeys-admin-e2e/src/pages/login-page.ts
  apps/journeys-admin-e2e/src/pages/onboarding-pages.ts
  apps/journeys-admin-e2e/src/pages/template-page.ts
  apps/journeys-admin-e2e/src/pages/top-nav.ts
  apps/journeys-admin-e2e/tsconfig.e2e.json
Labels: type: test, priority: 2day, effort: 8

#2266 fix: missing segmind graphql
  apps/api-media/src/app/__generated__/graphql.ts
  apps/api-media/src/app/modules/segmind/segmind.graphql
  apps/api-media/src/app/modules/segmind/segmind.service.ts
Labels: type: fix, priority: now, effort: 1

#2267 test: update onboarding question as per current
  apps/journeys-admin-e2e/src/pages/onboarding-pages.ts
Labels: type: test, effort: 2, priority: now

#2249 feat: refactor emails
  apps/api-gateway/router.prod.yaml
  apps/api-gateway/router.yaml
  apps/api-gateway/schema.graphql
  apps/api-journeys/.eslintrc.json
  apps/api-journeys/infrastructure/locals.tf
  apps/api-journeys/src/app/modules/email/email.consumer.spec.ts
  apps/api-journeys/src/app/modules/email/email.consumer.ts
  apps/api-journeys/src/app/modules/userInvite/userInvite.service.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.service.ts
  apps/api-journeys/tsconfig.app.json
  apps/api-users/infrastructure/locals.tf
  apps/api-users/schema.graphql
  apps/api-users/src/app/__generated__/graphql.ts
  apps/api-users/src/app/modules/user/user.graphql
  apps/api-users/src/app/modules/user/user.resolver.ts
Labels: effort: 3, priority: now, type: feat

#2247 feat: email template storybook
  .storybook/main.js
  apps/api-journeys/project.json
  apps/api-journeys/src/app/emails/JourneyInvite.tsx
  apps/api-journeys/src/app/emails/TeamInvite.tsx
  apps/api-journeys/src/app/emails/stories/JourneyInvite.stories.tsx
  apps/api-journeys/src/app/emails/stories/TeamInvite.stories.tsx
  apps/api-journeys/src/app/emails/templates/EmailLogo/EmailLogo.tsx
  apps/api-journeys/src/app/emails/templates/EmailLogo/index.ts
  apps/api-journeys/src/app/emails/templates/JourneyInvite/JourneyInvite.tsx
  apps/api-journeys/src/app/emails/templates/JourneyInvite/index.ts
  apps/api-journeys/src/app/emails/templates/TeamInvite/TeamInvite.tsx
  apps/api-journeys/src/app/emails/templates/TeamInvite/index.ts
  apps/api-journeys/src/app/lib/apiJourneysConfig/apiJourneysConfig.tsx
  apps/api-journeys/src/app/modules/email/email.consumer.spec.ts
  apps/api-journeys/src/app/modules/email/email.consumer.ts
  apps/api-journeys/src/app/modules/userInvite/userInvite.service.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.service.spec.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.resolver.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.service.spec.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.service.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.spec.ts
  apps/api-journeys/tsconfig.json
  apps/api-users/src/app/modules/email/email.consumer.spec.ts
  libs/shared/storybook/project.json
Labels: effort: 5, priority: soon, type: feat

#2231 fix: close menu after duplication
  apps/journeys-admin/src/components/Editor/EditToolbar/DuplicateBlock/DuplicateBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/DuplicateBlock/DuplicateBlock.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
Labels: type: fix, priority: soon, effort: 1

#2271 feat: properties panel refactor
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Accordion/Accordion.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Icon/Icon.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/ToggleButtonGroup/ToggleButtonGroup.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/PaletteColorPicker/PaletteColorPicker.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Form/Credentials/Credentials.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Cards/Cards.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Conditions/Conditions.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/Hint/Hint.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/TextResponse/TextResponseFields/Label/Label.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Drawer.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/index.ts
  apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLanguage/VideoLanguage.tsx
  apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/Editor/constants.ts
Labels: effort: 8, priority: now, type: feat

#2272 feat: add blocks toolbar
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/AddBlockToolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/AddBlockToolbar.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/AddBlockToolbar.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/Button/Button.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/Button/Button.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/Button/Button.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/Button/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewButtonButton/NewButtonButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewButtonButton/NewButtonButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewButtonButton/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewFormButton/NewFormButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewFormButton/NewFormButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewFormButton/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewImageButton/NewImageButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewImageButton/NewImageButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewImageButton/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewRadioQuestionButton/NewRadioQuestionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewRadioQuestionButton/NewRadioQuestionButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewRadioQuestionButton/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewSignUpButton/NewSignUpButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewSignUpButton/NewSignUpButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewSignUpButton/index.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewTextResponseButton/NewTextResponseButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewTextResponseButton/NewTextResponseButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewTextResponseButton/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewTypographyButton/NewTypographyButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewTypographyButton/NewTypographyButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewTypographyButton/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewVideoButton/NewVideoButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewVideoButton/NewVideoButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/NewVideoButton/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attribute/Attribute.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/BlocksTab.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/BlocksTab.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Button/Button.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Button/Button.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
Labels: priority: 2day, effort: 3, type: feat

#2275 test: fix login test and load env vars with dotenv
  apps/journeys-admin-e2e/src/framework/helpers.ts
  apps/journeys-admin-e2e/src/pages/landing-page.ts
Labels: type: test, effort: 2, priority: soon

#2068 fix: duplicate journey visitors
  apps/api-journeys/db/migrations/20231122013754_20231122013746/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/src/app/modules/event/event.service.spec.ts
  apps/api-journeys/src/app/modules/event/event.service.ts
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/visitor/visitor.service.spec.ts
  apps/api-journeys/src/app/modules/visitor/visitor.service.ts
Labels: type: fix, priority: now, effort: 1, on stage

#2278 feat: journeyview request approved
  apps/api-journeys/src/app/emails/stories/JourneyInvite.stories.tsx
  apps/api-journeys/src/app/emails/stories/JourneyShared.stories.tsx
  apps/api-journeys/src/app/emails/templates/JourneyInvite/JourneyInvite.tsx
  apps/api-journeys/src/app/emails/templates/JourneyInvite/index.ts
  apps/api-journeys/src/app/emails/templates/JourneyShared/JourneyShared.tsx
  apps/api-journeys/src/app/emails/templates/JourneyShared/index.ts
  apps/api-journeys/src/app/modules/email/email.consumer.spec.ts
  apps/api-journeys/src/app/modules/email/email.consumer.ts
  apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.spec.ts
  apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
  apps/api-journeys/src/app/modules/userInvite/userInvite.service.spec.ts
  apps/api-journeys/src/app/modules/userInvite/userInvite.service.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.module.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.service.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.service.ts
  apps/api-users/src/app/modules/user/user.resolver.ts
Labels: effort: 3, priority: soon, type: feat

#2221 feat: journeys ui theme
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-e2e/src/e2e/journeys.spec.ts
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/can-we-trust-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/can-we-trust-chrome-mobile-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/jesus-history-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/jesus-history-chrome-mobile-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/who-was-jesus-chrome-desktop-linux.png
  apps/journeys-e2e/src/e2e/journeys.spec.ts-snapshots/who-was-jesus-chrome-mobile-linux.png
  apps/journeys/pages/embed/[journeySlug].tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.stories.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
  libs/journeys/ui/src/components/StepFooter/HostTitleLocation/HostTitleLocation.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
  libs/shared/ui/src/libs/themes/index.ts
  libs/shared/ui/src/libs/themes/journeyUi/theme.ts
  libs/shared/ui/src/libs/themes/journeyUi/tokens/breakpoints.ts
  libs/shared/ui/src/libs/themes/journeyUi/tokens/colors.stories.tsx
  libs/shared/ui/src/libs/themes/journeyUi/tokens/colors.ts
  libs/shared/ui/src/libs/themes/journeyUi/tokens/components.stories.tsx
  libs/shared/ui/src/libs/themes/journeyUi/tokens/components.ts
  libs/shared/ui/src/libs/themes/journeyUi/tokens/spacing.ts
  libs/shared/ui/src/libs/themes/journeyUi/tokens/typography.stories.tsx
  libs/shared/ui/src/libs/themes/journeyUi/tokens/typography.ts
Labels: priority: soon, type: feat, effort: 1

#2282 fix: embed styling
  apps/journeys-admin/src/components/Editor/Properties/JourneyLink/EmbedJourneyDialog/EmbedCardPreview/EmbedCardPreview.tsx
  apps/journeys-admin/src/components/Editor/Properties/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Properties/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.tsx
  apps/journeys/pages/api/oembed.ts
  apps/journeys/pages/embed/test/[journeySlug].tsx
  apps/journeys/pages/index.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: now, effort: 1

#2290 feat: add branch icon
  libs/shared/ui/src/components/icons/GitBranch.tsx
Labels: priority: 2day, type: feat, effort: 1

#2072 feat: no animation swipe
  apps/journeys-admin/src/components/CardPreview/CardList/CardWrapper/CardWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.tsx
  apps/journeys/pages/_document.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRender.spec.tsx
  apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRenderer.tsx
  apps/journeys/src/components/Conductor/JourneyRenderer/index.ts
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.spec.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/index.ts
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx
  apps/journeys/src/components/VideoWrapperPaused/VideoWrapperPaused.tsx
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.spec.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/index.ts
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.spec.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.spec.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.tsx
  libs/journeys/ui/src/libs/getStepTheme/getStepTheme.ts
Labels: effort: 3, priority: soon, type: feat

#2287 feat: goals page canvas
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsBanner/ActionsBanner.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/Attributes.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.tsx
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: effort: 5, priority: now, type: feat

#2297 refactor: swipe
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRenderer.tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  package-lock.json
  package.json
Labels: effort: 2, priority: soon, type: refactor

#2299 feat: email infrastructure
  .devcontainer/Dockerfile
  .devcontainer/docker-compose.yml
  .gitignore
  apps/api-gateway/router.prod.yaml
  apps/api-gateway/router.yaml
  apps/api-journeys/infrastructure/locals.tf
  apps/api-users/infrastructure/locals.tf
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/main.tf
  infrastructure/modules/aws/elasticache/main.tf
  infrastructure/modules/aws/elasticache/variables.tf
  infrastructure/modules/aws/locals.tf
  infrastructure/modules/aws/main.tf
  infrastructure/modules/aws/outputs.tf
Labels: priority: soon, type: feat, effort: 1

#2295 test: swipe nav
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.spec.tsx
Labels: type: test, effort: 2, priority: soon

#2277 fix: ecs frontend deploy
  .github/workflows/ecs-frontend-deploy-prod-worker.yml
  .github/workflows/ecs-frontend-deploy-prod.yml
  .github/workflows/ecs-frontend-deploy-stage-worker.yml
  .github/workflows/ecs-frontend-deploy-stage.yml
Labels: type: fix, priority: now, effort: 1, on stage

#2302 feat: initial email
  .eslintrc.json
  apps/api-journeys/.eslintrc.json
  apps/api-journeys/jest.config.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/lib/apiJourneysConfig/apiJourneysConfig.tsx
  apps/api-journeys/src/app/modules/email/email.module.ts
  apps/api-journeys/tsconfig.app.json
  apps/api-journeys/tsconfig.json
  apps/api-journeys/tsconfig.spec.json
  apps/api-users/.eslintrc.json
  apps/api-users/jest.config.ts
  apps/api-users/src/app/app.module.ts
  apps/api-users/src/app/lib/apiUsersConfig/apiUsersConfig.tsx
  apps/api-users/src/app/modules/email/email.module.ts
  apps/api-users/tsconfig.app.json
  apps/api-users/tsconfig.json
  apps/api-users/tsconfig.spec.json
  apps/journeys-admin-e2e/src/e2e/user-creation.spec.ts
  libs/nest/common/.eslintrc.json
  libs/nest/common/jest.config.ts
  libs/nest/common/src/lib/email/emailService/email.service.spec.ts
  libs/nest/common/src/lib/email/emailService/email.service.ts
  libs/nest/common/src/lib/email/emailService/index.ts
  libs/nest/common/tsconfig.json
  libs/nest/common/tsconfig.lib.json
  libs/nest/common/tsconfig.spec.json
  package-lock.json
  package.json
Labels: effort: 3, priority: soon, type: feat

#2306 chore: email logo in journeys public
  apps/journeys/public/LogoHorizontal.png
Labels: priority: 2day, effort: 1, type: chore

#2304 test: journeyrenderer
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRender.spec.tsx
  apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRenderer.tsx
Labels: type: test, effort: 2, priority: soon

#2307 feat: email verified backend initial
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.spec.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.spec.ts
  apps/api-users/db/migrations/20240206211109_20240206211108/migration.sql
  apps/api-users/db/schema.prisma
  apps/api-users/schema.graphql
  apps/api-users/src/app/__generated__/graphql.ts
  apps/api-users/src/app/modules/user/user.graphql
  apps/api-users/src/app/modules/user/user.resolver.spec.ts
  apps/api-users/src/app/modules/user/user.resolver.ts
  libs/nest/common/src/lib/firebaseClient/firebaseClient.ts
Labels: effort: 3, priority: soon, type: feat

#2303 chore: host logo image
  apps/api-journeys/src/app/lib/apiJourneysConfig/apiJourneysConfig.tsx
  libs/nest/common/src/lib/email/components/EmailLogo/EmailLogo.tsx
Labels: priority: soon, effort: 1, type: chore

#2310 feat: email verification frontend initial
  .gitignore
  apps/journeys-admin/__generated__/GetMe.ts
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserNavigation.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserNavigation.tsx
Labels: priority: soon, type: feat, effort: 1

#2312 feat: bulb icon
  libs/shared/ui/src/components/icons/Bulb.tsx
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: priority: now, type: feat, effort: 1

#2291 style: step node redesign
  apps/journeys-admin/src/components/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/JourneyFlow/edges/ButtonEdge.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/ActionNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/ActionNode/ActionNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/ActionNode/index.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/BaseNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/BaseNode/BaseNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/BaseNode/index.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/ButtonBlockNode/ButtonBlockNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/ButtonBlockNode/index.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/FormBlockNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/FormBlockNode/FormBlockNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/FormBlockNode/index.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/RadioOptionBlockNode/RadioOptionBlockNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/RadioOptionBlockNode/index.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/SignUpBlockNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/SignUpBlockNode/SignUpBlockNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/SignUpBlockNode/index.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/SocialPreviewNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/SocialPreviewNode/index.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/StepBlockNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/StepBlockNode/StepBlockNodeIcon/StepBlockNodeIcon.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/StepBlockNode/StepBlockNodeIcon/index.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/StepBlockNode/index.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/StepBlockNode/libs/getBackgroundImage/getBackgroundImage.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/StepBlockNode/libs/getBackgroundImage/index.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/StepBlockNode/libs/getCardHeadings/getCardHeadings.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/StepBlockNode/libs/getCardHeadings/index.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/StepBlockNode/libs/getCardMetadata/getCardMetadata.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/StepBlockNode/libs/getCardMetadata/index.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/StepBlockNode/libs/getPriorityBlock/getPriorityBlock.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/StepBlockNode/libs/getPriorityBlock/index.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/TextResponseBlockNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/TextResponseBlockNode/TextResponseBlockNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/TextResponseBlockNode/index.ts
  apps/journeys-admin/src/components/JourneyFlow/nodes/VideoBlockNode/VideoBlockNode.tsx
  apps/journeys-admin/src/components/JourneyFlow/nodes/VideoBlockNode/index.ts
  libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
  libs/journeys/ui/src/libs/getStepHeading/index.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: soon, type: feat

#2298 feat: edit toolbar redesign
  apps/journeys-admin/src/components/Editor/CardTemplateDrawer/CardTemplateDrawer.tsx
  apps/journeys-admin/src/components/Editor/CardTemplateDrawer/Templates/CardCta/CardCta.spec.tsx
  apps/journeys-admin/src/components/Editor/CardTemplateDrawer/Templates/CardCta/CardCta.tsx
  apps/journeys-admin/src/components/Editor/CardTemplateDrawer/Templates/CardForm/CardForm.spec.tsx
  apps/journeys-admin/src/components/Editor/CardTemplateDrawer/Templates/CardForm/CardForm.tsx
  apps/journeys-admin/src/components/Editor/CardTemplateDrawer/Templates/CardIntro/CardIntro.spec.tsx
  apps/journeys-admin/src/components/Editor/CardTemplateDrawer/Templates/CardIntro/CardIntro.tsx
  apps/journeys-admin/src/components/Editor/CardTemplateDrawer/Templates/CardPoll/CardPoll.spec.tsx
  apps/journeys-admin/src/components/Editor/CardTemplateDrawer/Templates/CardPoll/CardPoll.tsx
  apps/journeys-admin/src/components/Editor/CardTemplateDrawer/Templates/CardQuote/CardQuote.spec.tsx
  apps/journeys-admin/src/components/Editor/CardTemplateDrawer/Templates/CardQuote/CardQuote.tsx
  apps/journeys-admin/src/components/Editor/CardTemplateDrawer/Templates/CardVideo/CardVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/CardTemplateDrawer/Templates/CardVideo/CardVideo.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/CopyMenuItem/CopyMenuItem.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/ShareButton/EmbedJourneyDialog/EmbedCardPreview/EmbedCardPreview.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/ShareButton/EmbedJourneyDialog/EmbedCardPreview/index.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/ShareButton/EmbedJourneyDialog/EmbedJourneyDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/ShareButton/EmbedJourneyDialog/EmbedJourneyDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/ShareButton/EmbedJourneyDialog/EmbedJourneyDialog.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/ShareButton/EmbedJourneyDialog/index.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/ShareButton/ShareButton.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/ShareButton/ShareButton.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/ShareButton/ShareButton.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/ShareButton/SlugDialog/SlugDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/ShareButton/SlugDialog/SlugDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/ShareButton/SlugDialog/SlugDialog.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/ShareButton/SlugDialog/index.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/ShareButton/index.ts
  apps/journeys-admin/src/components/Editor/EditToolbar/Strategy/Strategy.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Strategy/index.ts
  apps/journeys-admin/src/components/Editor/Editor.tsx
  apps/journeys-admin/src/components/Editor/Properties/AccessControl/AccessControl.spec.tsx
  apps/journeys-admin/src/components/Editor/Properties/AccessControl/AccessControl.tsx
  apps/journeys-admin/src/components/Editor/Properties/AccessControl/index.ts
  apps/journeys-admin/src/components/Editor/Properties/JourneyDetails/JourneyDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/Properties/JourneyDetails/JourneyDetails.stories.tsx
  apps/journeys-admin/src/components/Editor/Properties/JourneyDetails/JourneyDetails.tsx
  apps/journeys-admin/src/components/Editor/Properties/JourneyDetails/Language/Language.spec.tsx
  apps/journeys-admin/src/components/Editor/Properties/JourneyDetails/Language/Language.stories.tsx
  apps/journeys-admin/src/components/Editor/Properties/JourneyDetails/Language/Language.tsx
  apps/journeys-admin/src/components/Editor/Properties/JourneyDetails/Language/index.ts
  apps/journeys-admin/src/components/Editor/Properties/JourneyDetails/index.ts
  apps/journeys-admin/src/components/Editor/Properties/JourneyLink/JourneyLink.tsx
  apps/journeys-admin/src/components/Editor/Properties/JourneyLink/index.ts
  apps/journeys-admin/src/components/Editor/Properties/Properties.spec.tsx
  apps/journeys-admin/src/components/Editor/Properties/Properties.stories.tsx
  apps/journeys-admin/src/components/Editor/Properties/Properties.tsx
  apps/journeys-admin/src/components/Editor/Properties/index.ts
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/icons/Bulb.tsx
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: effort: 5, priority: now, type: feat

#2311 feat: goals details drawer
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionDetails.stories.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionDetails.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsList.spec.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsList.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsListView/ActionsListView.tsx
  apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/Attributes.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 5, priority: now, type: feat

#2309 feat: add blocks
  apps/journeys-admin/src/components/Editor/AddBlock/AddBlock.tsx
  apps/journeys-admin/src/components/Editor/AddBlock/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/AddBlockToolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/AddBlockToolbar.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/AddBlockToolbar.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/Button/Button.tsx
  apps/journeys-admin/src/components/Editor/Canvas/AddBlockToolbar/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/Button/Button.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/Button.stories.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/Button.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewButtonButton/NewButtonButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewButtonButton/NewButtonButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewButtonButton/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewFormButton/NewFormButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewFormButton/NewFormButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewFormButton/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewImageButton/NewImageButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewImageButton/NewImageButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewImageButton/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewRadioQuestionButton/NewRadioQuestionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewRadioQuestionButton/NewRadioQuestionButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewRadioQuestionButton/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewSignUpButton/NewSignUpButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewSignUpButton/NewSignUpButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewSignUpButton/index.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewTextResponseButton/NewTextResponseButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewTextResponseButton/NewTextResponseButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewTextResponseButton/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewTypographyButton/NewTypographyButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewTypographyButton/NewTypographyButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewTypographyButton/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewVideoButton/NewVideoButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewVideoButton/NewVideoButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Button/NewVideoButton/index.ts
  apps/journeys-admin/src/components/Editor/Canvas/Button/index.ts
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/Attributes.tsx
  apps/journeys-admin/src/components/Editor/Editor.tsx
  apps/journeys-admin/src/components/Editor/Fab/Fab.tsx
  apps/journeys-admin/src/components/Editor/Fab/index.ts
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 5, priority: now, type: feat

#2289 feat: footer properties panel
  apps/journeys-admin/__generated__/GetAllTeamHosts.ts
  apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.tsx
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/Footer.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/Footer.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostDrawer.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostDrawer.stories.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostDrawer.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostFormDrawer/HostAvatarsButton/HostAvatarsButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostFormDrawer/HostAvatarsButton/HostAvatarsButton.stories.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostFormDrawer/HostAvatarsButton/HostAvatarsButton.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostFormDrawer/HostAvatarsButton/index.ts
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostFormDrawer/HostFormDrawer.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostFormDrawer/HostFormDrawer.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostFormDrawer/HostLocationFieldForm/HostLocationFieldForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostFormDrawer/HostLocationFieldForm/HostLocationFieldForm.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostFormDrawer/HostLocationFieldForm/index.ts
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostFormDrawer/HostTitleFieldForm/HostTitleFieldForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostFormDrawer/HostTitleFieldForm/HostTitleFieldForm.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostFormDrawer/HostTitleFieldForm/index.ts
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostFormDrawer/index.ts
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostInfoDrawer/HostInfoDrawer.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostInfoDrawer/index.ts
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostList/HostList.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostList/HostList.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostList/index.ts
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostListDrawer/HostListDrawer.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostListDrawer/index.ts
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostListItem/HostListItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostListItem/HostListItem.stories.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostListItem/HostListItem.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/HostListItem/index.ts
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostDrawer/index.ts
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostSidePanel/HostForm/index.ts
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostSidePanel/HostSidePanel.tsx
  apps/journeys-admin/src/components/Editor/Drawer/Attributes/blocks/Footer/HostSidePanel/index.ts
  apps/journeys-admin/src/libs/useUpdateJourneyHostMutation/index.ts
  apps/journeys-admin/src/libs/useUpdateJourneyHostMutation/useUpdateJourneyHostMutation.ts
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: now, type: feat

#2305 test: video events
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.spec.tsx
Labels: type: test, priority: soon, effort: 1

#2316 fix: dialog wording change
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.tsx
  apps/journeys-admin/src/components/Team/UserTeamInviteForm/UserTeamInviteForm.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#2318 feat: notification refactor
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20240215000113_20240215000111/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/email/email.consumer.spec.ts
  apps/api-journeys/src/app/modules/email/email.consumer.ts
  apps/api-journeys/src/app/modules/journeysEmailPreference/journeysEmailPreference.graphql
  apps/api-journeys/src/app/modules/journeysEmailPreference/journeysEmailPreference.resolver.spec.ts
  apps/api-journeys/src/app/modules/journeysEmailPreference/journeysEmailPreference.resolver.ts
  apps/journeys-admin/__generated__/FindOrCreateJourneysEmailPreference.ts
  apps/journeys-admin/__generated__/UpdateJourneysEmailPreference.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/email-preferences/[email].tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: now, type: feat

#2320 fix: remove prisma imports from libs
  apps/api-journeys/src/app/emails/templates/JourneyAccessRequest/JourneyAccessRequest.tsx
  apps/api-journeys/src/app/emails/templates/JourneyShared/JourneyShared.tsx
  apps/api-journeys/src/app/emails/templates/JourneyShared/JourneySharedNoAccount/JourneySharedNoAccount.tsx
  libs/nest/common/src/lib/email/components/ActionCard/ActionCard.tsx
  libs/nest/common/src/lib/email/components/BodyWrapper/BodyWrapper.tsx
  libs/nest/common/src/lib/email/types/types.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#2314 test: radio question
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
Labels: type: test, priority: soon, effort: 1

#2308 test: initandplay
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx
  apps/journeys/src/components/VideoWrapperPaused/VideoWrapperPaused.spec.tsx
  apps/journeys/src/components/VideoWrapperPaused/VideoWrapperPaused.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.spec.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
Labels: type: test, effort: 3, priority: soon

#2327 feat: verify page
  apps/api-journeys/src/app/emails/templates/TeamInvite/TeamInvite.tsx
  apps/api-journeys/src/app/lib/apiJourneysConfig/apiJourneysConfig.tsx
  apps/api-users/src/app/emails/templates/EmailVerify/EmailVerify.tsx
  apps/api-users/src/app/lib/apiUsersConfig/apiUsersConfig.tsx
  apps/journeys-admin/pages/users/verify.tsx
Labels: type: fix, priority: soon, effort: 1

#2328 fix: email verified null
  apps/api-users/src/app/modules/user/user.resolver.spec.ts
  apps/api-users/src/app/modules/user/user.resolver.ts
Labels: type: fix, priority: soon, effort: 1

#2257 feat: add pagination bullets
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/Bullet/Bullet.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/Bullet/index.ts
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.spec.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.stories.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/index.ts
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
Labels: effort: 5, priority: soon, type: feat

#2331 feat: fab design changes
  apps/journeys-admin/src/components/Editor/Editor.tsx
  apps/journeys-admin/src/components/Editor/Fab/Fab.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/Goals.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/Goals.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: now, type: feat

#2329 test: disable visual regression tests for now
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts
  apps/journeys-e2e/src/e2e/journeys.spec.ts
Labels: type: test, priority: now, effort: 1

#2332 feat: email pref refactor
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20240216210658_20240216210656/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journeysEmailPreference/journeysEmailPreference.graphql
  apps/api-journeys/src/app/modules/journeysEmailPreference/journeysEmailPreference.resolver.spec.ts
  apps/api-journeys/src/app/modules/journeysEmailPreference/journeysEmailPreference.resolver.ts
  apps/journeys-admin/__generated__/FindOrCreateJourneysEmailPreference.ts
  apps/journeys-admin/__generated__/JourneysEmailPreference.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/email-preferences/[email].tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: now, type: feat

#2333 fix: email alias allow
  apps/api-users/src/app/modules/email/email.consumer.spec.ts
  apps/api-users/src/app/modules/email/email.consumer.ts
Labels: type: fix, priority: soon, effort: 1

#2334 fix: update email logo
  apps/journeys/public/LogoHorizontal.png
Labels: type: fix, priority: soon, effort: 1

#2337 chore: new crowdin translations
  libs/locales/am-ET/apps-journeys-admin.json
  libs/locales/ar-SA/apps-journeys-admin.json
  libs/locales/bn-BD/apps-journeys-admin.json
  libs/locales/es-ES/apps-journeys-admin.json
  libs/locales/fr-FR/apps-journeys-admin.json
  libs/locales/hi-IN/apps-journeys-admin.json
  libs/locales/id-ID/apps-journeys-admin.json
  libs/locales/ja-JP/apps-journeys-admin.json
  libs/locales/my-MM/apps-journeys-admin.json
  libs/locales/ru-RU/apps-journeys-admin.json
  libs/locales/th-TH/apps-journeys-admin.json
  libs/locales/tl-PH/apps-journeys-admin.json
  libs/locales/tr-TR/apps-journeys-admin.json
  libs/locales/ur-PK/apps-journeys-admin.json
  libs/locales/vi-VN/apps-journeys-admin.json
  libs/locales/zh-CN/apps-journeys-admin.json
  libs/locales/zh-TW/apps-journeys-admin.json
Labels: priority: soon, effort: 1, type: chore

#2339 feat: email unsubscribe backend
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20240214232440_20240214232438/migration.sql
  apps/api-journeys/db/migrations/20240215000113_20240215000111/migration.sql
  apps/api-journeys/db/migrations/20240216210658_20240216210656/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/lib/casl/__generated__/prismaSubjects.ts
  apps/api-journeys/src/app/modules/journeysEmailPreference/journeysEmailPreference.graphql
  apps/api-journeys/src/app/modules/journeysEmailPreference/journeysEmailPreference.module.ts
  apps/api-journeys/src/app/modules/journeysEmailPreference/journeysEmailPreference.resolver.spec.ts
  apps/api-journeys/src/app/modules/journeysEmailPreference/journeysEmailPreference.resolver.ts
Labels: effort: 5, priority: soon, type: feat

#2340 feat: email unsubscribe frontend
  apps/journeys-admin/__generated__/JourneysEmailPreference.ts
  apps/journeys-admin/__generated__/UpdateJourneysEmailPreference.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/email-preferences/[email].tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: now, type: feat

#2296 feat: add info message when unmuting autoplay videos
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx
  apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.stories.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#2319 test: step updates
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
Labels: type: test, effort: 2, priority: soon

#2280 feat: admin language switcher
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts-snapshots/home-page-chrome-desktop-linux.png
  apps/journeys-admin-e2e/src/pages/left-nav.ts
  apps/journeys-admin/middleware.spec.ts
  apps/journeys-admin/middleware.ts
  apps/journeys-admin/next-i18next.config.js
  apps/journeys-admin/setupTests.tsx
  apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.spec.tsx
  apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.stories.tsx
  apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.tsx
  apps/journeys-admin/src/components/LanguageSwitcher/index.ts
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserNavigation.tsx
  apps/journeys-admin/src/components/SignIn/SignIn.tsx
  apps/journeys-admin/src/libs/getLocaleLanguage/getLocaleLanguage.ts
  apps/journeys-admin/src/libs/getLocaleLanguage/index.ts
  libs/locales/en/apps-journeys-admin.json
  libs/locales/zh-CN/apps-journeys-admin.json
  package-lock.json
  package.json
Labels: effort: 3, priority: soon, type: feat, on stage

#2343 feat: api-users email
  apps/api-gateway/schema.graphql
  apps/api-users/schema.graphql
  apps/api-users/src/app/__generated__/graphql.ts
  apps/api-users/src/app/modules/email/email.consumer.ts
  apps/api-users/src/app/modules/user/user.graphql
  apps/api-users/src/app/modules/user/user.module.ts
  apps/api-users/src/app/modules/user/user.resolver.spec.ts
  apps/api-users/src/app/modules/user/user.resolver.ts
  apps/api-users/src/app/modules/user/user.service.spec.ts
  apps/api-users/src/app/modules/user/user.service.ts
Labels: effort: 2, priority: now, type: feat

#2345 fix: one verification token
  apps/api-users/src/app/modules/user/user.service.spec.ts
  apps/api-users/src/app/modules/user/user.service.ts
  apps/journeys-admin/pages/users/verify.tsx
Labels: effort: 2, type: fix, priority: soon

#2349 feat: api-users backend emails
  .storybook/main.js
  apps/api-users/project.json
  apps/api-users/src/app/emails/stories/EmailVerify.stories.tsx
  apps/api-users/src/app/emails/templates/EmailVerify/EmailVerify.tsx
  apps/api-users/src/app/emails/templates/EmailVerify/index.ts
  apps/api-users/src/app/lib/apiUsersConfig/apiUsersConfig.tsx
  apps/api-users/src/app/modules/email/email.consumer.spec.ts
  apps/api-users/src/app/modules/email/email.consumer.ts
  apps/api-users/src/app/modules/email/email.module.ts
  apps/api-users/src/app/modules/user/user.resolver.ts
  apps/api-users/src/app/modules/user/user.service.spec.ts
  apps/api-users/src/app/modules/user/user.service.ts
  apps/journeys/public/LogoHorizontal.png
  libs/shared/storybook/project.json
Labels: effort: 2, priority: now, type: feat

#2351 feat: journeys admin email verify
  apps/journeys-admin/__generated__/CreateVerificationRequest.ts
  apps/journeys-admin/__generated__/ValidateEmail.ts
  apps/journeys-admin/pages/users/verify.tsx
  apps/journeys-admin/src/components/AccessDialog/AddUserSection/EmailInviteForm/EmailInviteForm.tsx
  apps/journeys-admin/src/components/EmailVerification/EmailVerification.tsx
  apps/journeys-admin/src/components/Team/UserTeamInviteForm/UserTeamInviteForm.tsx
  apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.spec.tsx
  apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.ts
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: now, type: feat

#2243 feat: transactional emails
  libs/nest/common/src/lib/CaslAuthModule/caslGuard.ts
Labels: priority: 2day, effort: 13, type: feat, on stage

#2347 refactor: language switcher
  apps/journeys-admin/middleware.ts
  apps/journeys-admin/next-i18next.config.js
  apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.spec.tsx
  apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.stories.tsx
  apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.spec.tsx
  apps/journeys-admin/src/libs/getLocaleLanguage/getLocaleLanguage.ts
  apps/journeys-admin/src/libs/getLocaleLanguage/index.ts
  package-lock.json
  package.json
Labels: priority: now, effort: 1, type: refactor

#2353 fix: journey editor loading
  apps/journeys-admin/src/components/OnboardingPanel/CreateJourneyButton/CreateJourneyButton.tsx
  apps/journeys-admin/src/components/OnboardingPanel/OnboardingPanel.spec.tsx
Labels: type: fix, priority: soon, effort: 1

#2354 fix: email preferences page
  apps/journeys-admin/pages/email-preferences/[email].tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#2358 revert "feat: transactional emails (#2243)"
  libs/nest/common/src/lib/CaslAuthModule/caslGuard.ts
Labels: priority: now, effort: 1, type: revert

#2359 fix: tag typo
  apps/api-tags/db/seed.ts
Labels: priority: 2day, type: fix, effort: 1

#2188 fix: alignment of avatar group with other elements
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.tsx
Labels: type: fix, priority: soon, effort: 1

#2362 fix: strategy link update
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TemplateSettingsDialog/AboutTabPanel/AboutTabPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TemplateSettingsDialog/TemplateSettingsDialog.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
Labels: priority: soon, effort: 1, type: chore

#2325 fix: video quality
  apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRenderer.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.spec.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: effort: 2, type: fix, priority: soon

#2357 feat: ellipsis icon
  libs/shared/ui/src/components/icons/Ellipsis.tsx
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: priority: now, type: feat, effort: 1

#2361 fix: show header footer
  apps/journeys/src/components/Conductor/Conductor.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.spec.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
Labels: type: fix, effort: 3, priority: soon

#2360 chore: adjust styling email templates
  apps/api-users/src/app/emails/templates/EmailVerify/EmailVerify.tsx
  libs/nest/common/src/lib/email/components/ActionCard/ActionCard.tsx
  libs/nest/common/src/lib/email/components/EmailContainer/EmailContainer.tsx
  libs/nest/common/src/lib/email/components/Footer/Footer.tsx
  libs/nest/common/src/lib/email/components/UnsubscribeLink/UnsubscribeLink.tsx
Labels: priority: soon, effort: 1, type: chore, on stage

#2365 fix: email preferences logo
  apps/journeys-admin/pages/email-preferences/[email].tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#2368 chore: new crowdin translations
  libs/locales/am-ET/apps-journeys-admin.json
  libs/locales/ar-SA/apps-journeys-admin.json
  libs/locales/bn-BD/apps-journeys-admin.json
  libs/locales/es-ES/apps-journeys-admin.json
  libs/locales/fr-FR/apps-journeys-admin.json
  libs/locales/hi-IN/apps-journeys-admin.json
  libs/locales/id-ID/apps-journeys-admin.json
  libs/locales/ja-JP/apps-journeys-admin.json
  libs/locales/my-MM/apps-journeys-admin.json
  libs/locales/ru-RU/apps-journeys-admin.json
  libs/locales/th-TH/apps-journeys-admin.json
  libs/locales/tl-PH/apps-journeys-admin.json
  libs/locales/tr-TR/apps-journeys-admin.json
  libs/locales/ur-PK/apps-journeys-admin.json
  libs/locales/vi-VN/apps-journeys-admin.json
  libs/locales/zh-hans-CN/apps-docs.json
  libs/locales/zh-hans-CN/apps-journeys-admin.json
  libs/locales/zh-hans-CN/apps-journeys.json
  libs/locales/zh-hans-CN/apps-nexus-admin.json
  libs/locales/zh-hans-CN/apps-watch.json
  libs/locales/zh-hans-CN/common.json
  libs/locales/zh-hans-CN/libs-journeys-ui.json
  libs/locales/zh-hant-TW/apps-docs.json
  libs/locales/zh-hant-TW/apps-journeys-admin.json
  libs/locales/zh-hant-TW/apps-journeys.json
  libs/locales/zh-hant-TW/apps-nexus-admin.json
  libs/locales/zh-hant-TW/apps-watch.json
  libs/locales/zh-hant-TW/common.json
  libs/locales/zh-hant-TW/libs-journeys-ui.json
Labels: priority: soon, effort: 1, type: chore

#2364 fix: hide more info
  apps/journeys/src/components/Conductor/Conductor.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.spec.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
Labels: type: fix, priority: soon, effort: 1

#2370 fix: embed opening
  apps/journeys/pages/embed/[journeySlug].tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/EmbeddedPreview/ButtonWrapper/ButtonWrapper.tsx
  apps/journeys/src/components/EmbeddedPreview/ClickableCard/ClickableCard.tsx
  apps/journeys/src/components/EmbeddedPreview/ClickableCard/index.ts
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.stories.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.tsx
  apps/journeys/src/components/EmbeddedPreview/RadioOptionWrapper/RadioOptionWrapper.tsx
  apps/journeys/src/components/EmbeddedPreview/VideoWrapper/VideoWrapper.spec.tsx
  apps/journeys/src/components/EmbeddedPreview/VideoWrapper/VideoWrapper.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.spec.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
Labels: type: fix, priority: now, effort: 1

#2369 chore: new crowdin translations
  libs/locales/zh-Hans-CN/apps-docs.json
  libs/locales/zh-Hans-CN/apps-journeys-admin.json
  libs/locales/zh-Hans-CN/apps-journeys.json
  libs/locales/zh-Hans-CN/apps-nexus-admin.json
  libs/locales/zh-Hans-CN/apps-watch.json
  libs/locales/zh-Hans-CN/common.json
  libs/locales/zh-Hans-CN/libs-journeys-ui.json
  libs/locales/zh-Hant-TW/apps-docs.json
  libs/locales/zh-Hant-TW/apps-journeys-admin.json
  libs/locales/zh-Hant-TW/apps-journeys.json
  libs/locales/zh-Hant-TW/apps-nexus-admin.json
  libs/locales/zh-Hant-TW/apps-watch.json
  libs/locales/zh-Hant-TW/common.json
  libs/locales/zh-Hant-TW/libs-journeys-ui.json
Labels: priority: soon, effort: 1, type: chore

#2132 feat: all new login page
  apps/journeys-admin-e2e/src/e2e/existing-user.spec.ts
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts-snapshots/home-page-chrome-desktop-linux.png
  apps/journeys-admin-e2e/src/e2e/response-time.spec.ts
  apps/journeys-admin-e2e/src/e2e/user-creation.spec.ts
  apps/journeys-admin-e2e/src/pages/landing-page.ts
  apps/journeys-admin-e2e/src/pages/login-page.ts
  apps/journeys-admin/public/logo.svg
  apps/journeys-admin/src/components/SignIn/EmailUsedPage/EmailUsedPage.spec.tsx
  apps/journeys-admin/src/components/SignIn/EmailUsedPage/EmailUsedPage.tsx
  apps/journeys-admin/src/components/SignIn/EmailUsedPage/index.ts
  apps/journeys-admin/src/components/SignIn/HomePage/HomePage.spec.tsx
  apps/journeys-admin/src/components/SignIn/HomePage/HomePage.tsx
  apps/journeys-admin/src/components/SignIn/HomePage/index.ts
  apps/journeys-admin/src/components/SignIn/PasswordPage/PasswordPage.spec.tsx
  apps/journeys-admin/src/components/SignIn/PasswordPage/PasswordPage.tsx
  apps/journeys-admin/src/components/SignIn/PasswordPage/index.ts
  apps/journeys-admin/src/components/SignIn/PasswordResetPage/PasswordResetPage.spec.tsx
  apps/journeys-admin/src/components/SignIn/PasswordResetPage/PasswordResetPage.tsx
  apps/journeys-admin/src/components/SignIn/PasswordResetPage/index.ts
  apps/journeys-admin/src/components/SignIn/RegisterPage/RegisterPage.spec.tsx
  apps/journeys-admin/src/components/SignIn/RegisterPage/RegisterPage.tsx
  apps/journeys-admin/src/components/SignIn/RegisterPage/index.ts
  apps/journeys-admin/src/components/SignIn/ResetPasswordSentPage/ResetPasswordSentPage.spec.tsx
  apps/journeys-admin/src/components/SignIn/ResetPasswordSentPage/ResetPasswordSentPage.tsx
  apps/journeys-admin/src/components/SignIn/ResetPasswordSentPage/index.ts
  apps/journeys-admin/src/components/SignIn/SignIn.spec.tsx
  apps/journeys-admin/src/components/SignIn/SignIn.stories.tsx
  apps/journeys-admin/src/components/SignIn/SignIn.tsx
  apps/journeys-admin/src/components/SignIn/SignInServiceButton/SignInServiceButton.spec.tsx
  apps/journeys-admin/src/components/SignIn/SignInServiceButton/SignInServiceButton.stories.tsx
  apps/journeys-admin/src/components/SignIn/SignInServiceButton/SignInServiceButton.tsx
  apps/journeys-admin/src/components/SignIn/SignInServiceButton/index.ts
  apps/journeys-admin/src/components/SignIn/types.ts
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/icons/FacebookIcon.tsx
  libs/shared/ui/src/components/icons/GoogleIcon.tsx
Labels: effort: 8, priority: soon, type: perf

#2371 fix: spacing
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
Labels: type: fix, priority: soon, effort: 1

#2363 test: misc fixes
  apps/journeys-admin/src/components/CardPreview/CardList/CardWrapper/CardWrapper.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardList/CardWrapper/CardWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.test.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.tsx
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRenderer.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.spec.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#2372 fix: allow fullscreen video on ios
  apps/journeys/pages/embed/test/[journeySlug].tsx
  apps/journeys/src/components/EmbeddedPreview/ClickableCard/ClickableCard.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
Labels: type: fix, priority: now, effort: 1

#2366 fix: language switcher options
  apps/journeys-admin/middleware.spec.ts
  apps/journeys-admin/middleware.ts
  apps/journeys-admin/next-i18next.config.js
  apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.spec.tsx
  apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.tsx
  libs/locales/zh-CN/apps-docs.json
  libs/locales/zh-CN/apps-journeys-admin.json
  libs/locales/zh-CN/apps-journeys.json
  libs/locales/zh-CN/apps-nexus-admin.json
  libs/locales/zh-CN/apps-watch.json
  libs/locales/zh-CN/common.json
  libs/locales/zh-CN/libs-journeys-ui.json
  libs/locales/zh-TW/apps-docs.json
  libs/locales/zh-TW/apps-journeys-admin.json
  libs/locales/zh-TW/apps-journeys.json
  libs/locales/zh-TW/apps-nexus-admin.json
  libs/locales/zh-TW/apps-watch.json
  libs/locales/zh-TW/common.json
  libs/locales/zh-TW/libs-journeys-ui.json
  libs/locales/zh-hans-CN/apps-docs.json
  libs/locales/zh-hans-CN/apps-journeys-admin.json
  libs/locales/zh-hans-CN/apps-journeys.json
  libs/locales/zh-hans-CN/apps-nexus-admin.json
  libs/locales/zh-hans-CN/apps-watch.json
  libs/locales/zh-hans-CN/common.json
  libs/locales/zh-hans-CN/libs-journeys-ui.json
  libs/locales/zh-hant-TW/apps-docs.json
  libs/locales/zh-hant-TW/apps-journeys-admin.json
  libs/locales/zh-hant-TW/apps-journeys.json
  libs/locales/zh-hant-TW/apps-nexus-admin.json
  libs/locales/zh-hant-TW/apps-watch.json
  libs/locales/zh-hant-TW/common.json
  libs/locales/zh-hant-TW/libs-journeys-ui.json
Labels: type: fix, priority: soon, effort: 1

#2376 test: update ns admin monitor after page modification
  apps/journeys-admin-e2e/src/monitoring/journeys-admin.monitor.ts
Labels: type: test, priority: now, effort: 1

#2379 feat: redirect to invited team backend
  apps/api-journeys/src/app/modules/email/email.consumer.spec.ts
  apps/api-journeys/src/app/modules/email/email.consumer.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.service.spec.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.service.ts
Labels: priority: soon, type: feat, effort: 1, on stage

#2338 test: update card tests
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
Labels: type: test, priority: soon, effort: 1

#2381 fix: cardwrapper tests
  apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.spec.tsx
Labels: type: fix, priority: soon, effort: 1

#2323 docs: update internationalization
  apps/docs/docs/04-engineering-practices/03-internationalization/crowdin-translations.png
  apps/docs/docs/04-engineering-practices/03-internationalization/index.md
  apps/docs/docs/04-engineering-practices/03-internationalization/language-translated.png
  apps/docs/docs/04-engineering-practices/03-internationalization/translation-process.md
  apps/docs/docs/04-engineering-practices/03-internationalization/translations-tag.md
Labels: type: docs, priority: soon, effort: 1

#2385 refactor: action card
  apps/api-journeys/src/app/emails/templates/JourneyAccessRequest/JourneyAccessRequest.tsx
  apps/api-journeys/src/app/emails/templates/JourneyShared/JourneyShared.tsx
  apps/api-journeys/src/app/emails/templates/JourneyShared/JourneySharedNoAccount/JourneySharedNoAccount.tsx
  apps/api-journeys/src/app/emails/templates/TeamInvite/TeamInvite.tsx
  apps/api-journeys/src/app/emails/templates/TeamInvite/TeamInviteNoAccount/TeamInviteNoAccount.tsx
  apps/api-journeys/src/app/emails/templates/TeamInviteAccepted/TeamInviteAccepted.tsx
  apps/api-journeys/src/app/emails/templates/TeamRemoved/TeamRemoved.tsx
  apps/api-users/src/app/emails/templates/EmailVerify/EmailVerify.tsx
  libs/nest/common/src/lib/email/components/ActionCard/ActionButton/ActionButton.tsx
  libs/nest/common/src/lib/email/components/ActionCard/ActionButton/index.ts
  libs/nest/common/src/lib/email/components/ActionCard/ActionCard.tsx
  libs/nest/common/src/lib/email/components/ActionCard/ActionJourneyView/ActionJourneyView.tsx
  libs/nest/common/src/lib/email/components/ActionCard/ActionJourneyView/index.ts
  libs/nest/common/src/lib/email/components/ActionCard/ActionSender/ActionSender.tsx
  libs/nest/common/src/lib/email/components/ActionCard/ActionSender/index.ts
  libs/nest/common/src/lib/email/components/index.ts
Labels: priority: soon, effort: 1, type: refactor, on stage

#2388 fix: remove unused vars in user service
  apps/api-users/src/app/modules/user/user.service.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#2383 fix: missing logout translation
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.tsx
Labels: type: fix, priority: now, effort: 1

#2378 fix: create journey button redirect
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/AddJourneyButton/AddJourneyButton.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/AddJourneyButton/AddJourneyButton.tsx
Labels: type: fix, priority: soon, effort: 1

#2380 feat: redirect to invited team frontend
  apps/journeys-admin/pages/index.tsx
Labels: type: fix, priority: soon, effort: 1

#2168 fix: helpscout text field on mobile
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
Labels: type: fix, priority: now, effort: 1

#2373 chore: new crowdin translations
  libs/locales/am-ET/apps-journeys-admin.json
  libs/locales/ar-SA/apps-journeys-admin.json
  libs/locales/bn-BD/apps-journeys-admin.json
  libs/locales/es-ES/apps-journeys-admin.json
  libs/locales/fr-FR/apps-journeys-admin.json
  libs/locales/hi-IN/apps-journeys-admin.json
  libs/locales/id-ID/apps-journeys-admin.json
  libs/locales/ja-JP/apps-journeys-admin.json
  libs/locales/my-MM/apps-journeys-admin.json
  libs/locales/ru-RU/apps-journeys-admin.json
  libs/locales/th-TH/apps-journeys-admin.json
  libs/locales/tl-PH/apps-journeys-admin.json
  libs/locales/tr-TR/apps-journeys-admin.json
  libs/locales/ur-PK/apps-journeys-admin.json
  libs/locales/vi-VN/apps-journeys-admin.json
  libs/locales/zh-Hans-CN/apps-journeys-admin.json
  libs/locales/zh-Hant-TW/apps-journeys-admin.json
Labels: priority: soon, effort: 1, type: chore

#2377 chore: nx & next bump
  apps/api-tags/db/seed.ts
  apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.tsx
  nx.json
  package-lock.json
  package.json
Labels: priority: 2day, effort: 1, type: chore

#2265 chore: rover bump
  .devcontainer/post-create-command.sh
  .github/workflows/api-deploy-worker.yml
  .github/workflows/main.yml
Labels: priority: 2day, effort: 1, type: chore, on stage

#2352 fix: add languages to template options
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/data.ts
Labels: type: fix, priority: now, effort: 1

#2390 fix: empty slug journey build
  apps/journeys/pages/[journeySlug].tsx
  apps/journeys/pages/embed/[journeySlug].tsx
Labels: type: fix, priority: soon, effort: 1

#2392 docs: transactional emails edit
  apps/docs/docs/03-basics/02-backend/03-transactional-emails.md
Labels: type: fix, priority: soon, effort: 1

#2393 fix: cloudflare initial video quality
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: type: fix, priority: soon, effort: 1

#2344 test: properties block tests
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DuplicateBlock/DuplicateBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Chat/ChatOption/ChatOption.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Accordion/Accordion.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Button/Button.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/Card.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Form.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Image.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioOption/RadioOption.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/SignUp/SignUp.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/Step.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Typography.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Video.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
Labels: type: test, effort: 5, priority: now

#2395 fix: link action event bubbling
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/Post/Post.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Accordion/Accordion.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Accordion/Accordion.tsx
Labels: effort: 2, type: fix, priority: soon

#2374 fix: empty bracket use translations
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TemplateSettingsDialog/AboutTabPanel/AboutTabPanel.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TemplateSettingsDialog/CategoriesTabPanel/CategoriesTabPanel.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TemplateSettingsDialog/MetadataTabPanel/MetadataTabPanel.tsx
  apps/journeys-admin/src/components/Editor/EditToolbar/Menu/TemplateSettingsDialog/TemplateSettingsDialog.tsx
  apps/journeys-admin/src/components/SignIn/EmailUsedPage/EmailUsedPage.tsx
  apps/journeys-admin/src/components/SignIn/HomePage/HomePage.tsx
  apps/journeys-admin/src/components/SignIn/PasswordPage/PasswordPage.tsx
  apps/journeys-admin/src/components/SignIn/PasswordResetPage/PasswordResetPage.tsx
  apps/journeys-admin/src/components/SignIn/RegisterPage/RegisterPage.tsx
  apps/journeys-admin/src/components/SignIn/ResetPasswordSentPage/ResetPasswordSentPage.tsx
  apps/journeys-admin/src/components/SignIn/SignInServiceButton/SignInServiceButton.tsx
  apps/journeys-admin/src/components/StrategySection/StrategySection.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateViewHeader/TemplateEditButton/TemplateEditButton.tsx
Labels: type: fix, priority: now, effort: 1

#2398 fix: journey title dialog input
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/AccessItem/AccessItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/AnalyticsItem/AnalyticsItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DescriptionItem/DescriptionItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/PreviewItem/PreviewItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/StrategyItem/StrategyItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TemplateSettingsItem/TemplateSettingsDialog/TemplateSettingsDialog.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TemplateSettingsItem/TemplateSettingsItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TemplateSettingsItem/TemplateSettingsItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TitleItem/TitleDialog/TitleDialog.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TitleItem/TitleItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TitleItem/TitleItem.tsx
Labels: type: fix, priority: soon, effort: 1

#2387 feat: more prominent unmute button
  libs/journeys/ui/src/components/Video/Video.stories.tsx
  libs/journeys/ui/src/components/Video/VideoControls/DesktopControls/DesktopControls.tsx
  libs/journeys/ui/src/components/Video/VideoControls/DesktopControls/index.ts
  libs/journeys/ui/src/components/Video/VideoControls/MobileControls/MobileControls.tsx
  libs/journeys/ui/src/components/Video/VideoControls/MobileControls/index.ts
  libs/journeys/ui/src/components/Video/VideoControls/PlaybackIcon/PlaybackIcon.tsx
  libs/journeys/ui/src/components/Video/VideoControls/PlaybackIcon/index.ts
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.spec.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/Video/VideoControls/utils/playbackReducer/index.ts
  libs/journeys/ui/src/components/Video/VideoControls/utils/playbackReducer/playbackReducer.ts
Labels: effort: 3, priority: soon, type: feat

#2397 fix: button no longer opens on admin
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: priority: 2day, type: fix, effort: 1

#2396 feat: center navigation button to viewport
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
Labels: priority: soon, type: feat, effort: 1

#2400 fix: final tidy up
  apps/journeys-admin/src/components/CardPreview/CardList/CardWrapper/CardWrapper.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardList/CardWrapper/CardWrapper.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
  apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.tsx
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRenderer.spec.tsx
  apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRenderer.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.spec.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/Bullet/Bullet.tsx
  libs/journeys/ui/src/components/Video/VideoControls/PlaybackIcon/PlaybackIcon.tsx
Labels: priority: now, effort: 1, type: refactor
