Repository JesusFilm/core, pull requests merged in 2024-10, with the labels that each got.

#3587 feat: api-media published & adminVideo queries
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/db/migrations/20240930190802_20240930190752/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/video/video.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#3444 feat: algolia search in video library
  apps/journeys-admin/__generated__/GetVideos.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/data.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/VideoFromYouTube.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/VideoFromYouTube.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.handlers.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoSearch/VideoSearch.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoSearch/VideoSearch.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoSearch/VideoSearch.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/data.ts
  apps/watch/src/components/VideoCard/VideoCard.spec.tsx
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideoCarousel/VideoCarousel.spec.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoGrid/AlgoliaVideoGrid/AlgoliaVideoGrid.spec.tsx
  apps/watch/src/components/VideoGrid/AlgoliaVideoGrid/AlgoliaVideoGrid.tsx
  apps/watch/src/components/VideoGrid/AlgoliaVideoGrid/index.ts
  apps/watch/src/components/VideoGrid/VideoGrid.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.handlers.ts
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
  apps/watch/src/components/WatchHomePage/WatchHomePage.tsx
  apps/watch/src/libs/algolia/transformAlgoliaVideos/index.ts
  apps/watch/src/libs/algolia/transformAlgoliaVideos/transformAlgoliaVideos.spec.tsx
  apps/watch/src/libs/algolia/transformAlgoliaVideos/transformAlgoliaVideos.ts
  apps/watch/src/libs/algolia/useAlgoliaVideos/index.ts
  apps/watch/src/libs/algolia/useAlgoliaVideos/useAlgoliaVideos.spec.ts
  apps/watch/src/libs/algolia/useAlgoliaVideos/useAlgoliaVideos.ts
  libs/journeys/ui/src/libs/algolia/useAlgoliaVideos/data.ts
  libs/journeys/ui/src/libs/algolia/useAlgoliaVideos/index.ts
  libs/journeys/ui/src/libs/algolia/useAlgoliaVideos/useAlgoliaVideos.spec.tsx
  libs/journeys/ui/src/libs/algolia/useAlgoliaVideos/useAlgoliaVideos.ts
Labels: priority: soon, type: feat, effort: 1, on stage

#3590 feat: video images url field
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/infrastructure/locals.tf
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/cloudflare/image/image.spec.ts
  apps/api-media/src/schema/cloudflare/image/image.ts
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/video/video.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 2, priority: soon, type: feat

#3594 feat: add hmac signing to gateway
  apps/api-gateway/gateway.config.ts
  apps/api-gateway/gateway.prod.config.ts
  apps/api-gateway/infrastructure/locals.tf
  apps/api-gateway/project.json
  package-lock.json
  package.json
Labels: priority: now, type: feat, effort: 1, on stage

#3596 fix: video resolver not handling part3 query
  apps/api-media/src/schema/video/video.ts
Labels: effort: 5, type: fix, priority: soon

#3599 fix: remove dot for no description
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Labels: type: fix, priority: soon, effort: 1

#3595 chore: add hmac signing to subgraphs
  apps/api-analytics/Dockerfile
  apps/api-analytics/infrastructure/locals.tf
  apps/api-analytics/src/yoga.ts
  apps/api-journeys-modern/Dockerfile
  apps/api-journeys-modern/infrastructure/locals.tf
  apps/api-journeys-modern/src/yoga.ts
  apps/api-journeys/Dockerfile
  apps/api-languages/Dockerfile
  apps/api-languages/infrastructure/locals.tf
  apps/api-languages/src/yoga.ts
  apps/api-media/Dockerfile
  apps/api-media/infrastructure/locals.tf
  apps/api-media/src/yoga.ts
  apps/api-users/Dockerfile
  apps/api-users/infrastructure/locals.tf
  apps/api-users/src/yoga.ts
  infrastructure/modules/aws/ecs-task/main.tf
Labels: priority: now, type: feat, effort: 1, on stage

#3601 fix: failing test for toolbar
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Labels: type: fix, priority: now, effort: 1

#3591 fix: append https to link without protocol
  apps/watch/src/components/TextFormatter/TextFormatter.spec.tsx
  apps/watch/src/components/TextFormatter/TextFormatter.tsx
Labels: type: fix, priority: soon, effort: 1

#3603 fix: video language graphql info
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/video/video.ts
Labels: type: fix, effort: 3, priority: now, on stage

#3605 feat: add jwt validation to gateway
  apps/api-gateway/.eslintrc.json
  apps/api-gateway/gateway.config.ts
  apps/api-gateway/gateway.prod.config.ts
  apps/api-gateway/project.json
  apps/api-gateway/tsconfig.app.json
  apps/api-gateway/tsconfig.json
  apps/api-media/src/yoga.ts
  apps/api-users/src/yoga.ts
  libs/nest/common/src/lib/firebaseClient/firebaseClient.ts
  libs/yoga/src/firebaseClient/firebaseClient.ts
Labels: priority: now, type: feat, effort: 1, on stage

#3579 fix: eng 987 empty search doesnt reset videos in see all videos
  apps/watch/src/components/VideosPage/FilterList/FilterList.spec.tsx
  apps/watch/src/components/VideosPage/FilterList/FilterList.tsx
  apps/watch/src/components/VideosPage/FilterList/data.ts
  apps/watch/src/libs/algolia/useAlgoliaRouter/index.ts
  apps/watch/src/libs/algolia/useAlgoliaRouter/useAlgoliaRouter.ts
Labels: type: fix, priority: soon, effort: 1

#3606 chore: add jwt to authorization header
  apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
  apps/journeys/src/libs/apolloClient/apolloClient.ts
  apps/videos-admin/src/app/[locale]/_ApolloProvider/ApolloProvider.tsx
  apps/videos-admin/src/app/[locale]/users/unauthorized/page.tsx
  apps/videos-admin/src/libs/apollo/apolloClient.ts
  apps/videos-admin/src/middleware.ts
  apps/watch/src/libs/apolloClient/apolloClient.ts
Labels: priority: now, effort: 1, type: chore

#3572 docs: algolia docs
  apps/docs/docs/03-basics/02-backend/05-algolia.md
  apps/docs/docs/03-basics/02-backend/algolia.png
  apps/docs/docs/03-basics/03-frontend/07-algolia/index.md
Labels: priority: 2day, effort: 2, type: docs

#3608 chore: remove basecamp check
  dangerfile.ts
Labels: priority: soon, effort: 1, type: chore

#3602 fix: disable preview button if no href
  apps/journeys-admin-e2e/src/pages/journey-page.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/Item/Item.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/Item/Item.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/PreviewItem/PreviewItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/PreviewItem/PreviewItem.tsx
Labels: priority: 2day, effort: 2, type: fix

#3597 feat: add admin videos count to video schema
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/video/video.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: soon, type: feat, effort: 1

#3609 chore: remove auth header from subgraphs
  apps/api-analytics/src/yoga.ts
  apps/api-gateway/gateway.config.ts
  apps/api-gateway/gateway.prod.config.ts
  apps/api-media/src/schema/builder.ts
  apps/api-media/src/schema/cloudflare/image/image.ts
  apps/api-media/src/schema/cloudflare/video/video.ts
  apps/api-media/src/schema/segmind/segmind.ts
  apps/api-media/src/schema/user/user.spec.ts
  apps/api-media/src/yoga.ts
  apps/api-users/src/schema/builder.ts
  apps/api-users/src/schema/user/user.spec.ts
  apps/api-users/src/yoga.ts
  libs/nest/common/src/lib/CaslAuthModule/caslGuard.ts
  libs/nest/common/src/lib/firebaseClient/firebaseClient.ts
  libs/nest/decorators/src/lib/CurrentUser/CurrentUser.ts
  libs/nest/decorators/src/lib/CurrentUserId/CurrentUserId.ts
  libs/nest/gqlAuthGuard/src/lib/GqlAuthGuard/GqlAuthGuard.ts
  libs/yoga/src/firebaseClient/firebaseClient.ts
  libs/yoga/src/firebaseClient/index.ts
Labels: priority: now, effort: 1, type: chore, on stage

#3615 fix: pic needs to be nullish
  libs/nest/common/src/lib/firebaseClient/firebaseClient.ts
  libs/yoga/src/firebaseClient/firebaseClient.ts
Labels: type: fix, priority: now, effort: 1, on stage

#3589 fix: regex pattern for youtube video ids
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/VideoFromYouTube.tsx
Labels: type: fix, priority: soon, effort: 1

#3624 revert: regex pattern for youtube video ids
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/VideoFromYouTube.tsx
Labels: priority: now, effort: 1, type: revert

#3626 fix: mui package issue
  apps/journeys-admin/Dockerfile
Labels: type: fix, priority: now, effort: 1, on stage

#3628 revert: regex pattern for youtube video ids
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/VideoFromYouTube.tsx
Labels: priority: soon, effort: 1, type: revert

#3629 Revert "fix: force prod rebuild"
  apps/journeys-admin/pages/_app.tsx
Labels: priority: 2day, effort: 1, type: revert

#3631 fix: nullish email address
  apps/api-journeys/src/app/emails/templates/JourneyAccessRequest/JourneyAccessRequest.tsx
  apps/api-journeys/src/app/emails/templates/JourneyShared/JourneyShared.tsx
  apps/api-journeys/src/app/emails/templates/TeamInvite/TeamInvite.tsx
  apps/api-journeys/src/app/emails/templates/TeamInviteAccepted/TeamInviteAccepted.tsx
  apps/api-journeys/src/app/emails/templates/TeamRemoved/TeamRemoved.tsx
  apps/api-journeys/src/app/emails/templates/VisitorInteraction/VisitorInteraction.tsx
  apps/api-journeys/src/app/modules/mailChimp/mailChimp.service.ts
  apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
  apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.resolver.ts
  apps/api-users/src/schema/user/user.ts
  libs/nest/common/src/lib/firebaseClient/firebaseClient.ts
  libs/yoga/src/firebaseClient/firebaseClient.ts
Labels: type: fix, priority: now, effort: 1, on stage

#3630 fix: clear cache on logout
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.tsx
Labels: type: fix, priority: soon, effort: 1

#3634 feat: arclight cloudflare images
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/route.ts
  apps/arclight/src/app/v2/media-components/route.ts
Labels: effort: 2, priority: soon, type: feat

#3622 test: add all playwright secrets to on-demand e2e actions file
  .github/workflows/e2e-tests.yml
Labels: priority: 2day, effort: 1, type: ci

#3625 feat: arclight facade media countries
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/schema.graphql
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-languages/src/schema/country/country.spec.ts
  apps/api-languages/src/schema/country/country.ts
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/arclight/src/app/v2/media-countries/[countryId]/route.ts
  apps/arclight/src/app/v2/media-countries/route.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 3, priority: soon, type: feat

#3627 feat: arclight-facade-media-component-links
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/video/video.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/arclight/src/app/v2/media-component-links/[mediaComponentId]/route.ts
  apps/arclight/src/app/v2/media-component-links/route.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 3, priority: soon, type: feat

#3638 feat: swap watch to cloudflare images no qa
  apps/api-media/src/schema/video/video.ts
  apps/watch/__generated__/GetHomeVideos.ts
  apps/watch/__generated__/GetVideoChildren.ts
  apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
  apps/watch/__generated__/GetVideoContent.ts
  apps/watch/__generated__/GetVideos.ts
  apps/watch/__generated__/GetVideosForTestData.ts
  apps/watch/__generated__/VideoChildFields.ts
  apps/watch/__generated__/VideoContentFields.ts
  apps/watch/src/components/DownloadDialog/DownloadDialog.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.tsx
  apps/watch/src/components/VideoCard/VideoCard.spec.tsx
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.spec.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.tsx
  apps/watch/src/components/VideoGrid/AlgoliaVideoGrid/AlgoliaVideoGrid.spec.tsx
  apps/watch/src/components/Videos/__generated__/testData.ts
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/libs/algolia/transformAlgoliaVideos/transformAlgoliaVideos.spec.tsx
  apps/watch/src/libs/algolia/transformAlgoliaVideos/transformAlgoliaVideos.ts
  apps/watch/src/libs/videoChildFields.ts
  apps/watch/src/libs/videoContentFields.ts
  apps/watch/src/libs/videoContext/VideoContext.spec.tsx
Labels: priority: 2day, effort: 8, type: feat

#3639 feat: deprecate image fields on video
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-media/schema.graphql
  apps/api-media/src/schema/video/video.ts
Labels: priority: 2day, type: feat, effort: 1

#3632 chore: add tracing to yoga apis
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-prod-worker.yml
  .github/workflows/api-gateway-stage-worker.yml
  .github/workflows/ecs-frontend-deploy-prod-worker.yml
  .github/workflows/ecs-frontend-deploy-stage-worker.yml
  apps/api-analytics/Dockerfile
  apps/api-analytics/db/schema.prisma
  apps/api-analytics/infrastructure/main.tf
  apps/api-analytics/src/schema/builder.ts
  apps/api-analytics/src/yoga.ts
  apps/api-gateway/Dockerfile
  apps/api-gateway/gateway.prod.config.ts
  apps/api-gateway/infrastructure/main.tf
  apps/api-journeys-modern/Dockerfile
  apps/api-journeys-modern/db/schema.prisma
  apps/api-journeys-modern/infrastructure/main.tf
  apps/api-journeys-modern/src/schema/builder.ts
  apps/api-journeys-modern/src/yoga.ts
  apps/api-journeys/Dockerfile
  apps/api-journeys/infrastructure/main.tf
  apps/api-languages/Dockerfile
  apps/api-languages/db/schema.prisma
  apps/api-languages/infrastructure/main.tf
  apps/api-languages/src/schema/builder.ts
  apps/api-languages/src/yoga.ts
  apps/api-media/Dockerfile
  apps/api-media/db/schema.prisma
  apps/api-media/infrastructure/main.tf
  apps/api-media/src/schema/builder.ts
  apps/api-media/src/yoga.ts
  apps/api-users/Dockerfile
  apps/api-users/db/schema.prisma
  apps/api-users/infrastructure/main.tf
  apps/api-users/src/schema/builder.ts
  apps/api-users/src/yoga.ts
  apps/journeys-admin/Dockerfile
  apps/journeys-admin/infrastructure/main.tf
  infrastructure/modules/aws/ecs-task/data.tf
  infrastructure/modules/aws/ecs-task/main.tf
  infrastructure/modules/aws/ecs/main.tf
  libs/yoga/src/tracer/index.ts
  libs/yoga/src/tracer/tracer.ts
  package-lock.json
  package.json
Labels: priority: now, effort: 1, type: chore, on stage

#3648 fix: tidy up spacing for toolbar
  apps/journeys-admin/src/components/Editor/Toolbar/Items/AnalyticsItem/AnalyticsItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/Item/Item.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Labels: type: fix, priority: soon, effort: 1

#3643 feat: deprecate video image prisma fields
  apps/api-media/db/schema.prisma
Labels: priority: soon, type: feat, effort: 1

#3653 feat: add mux keys to infra
  apps/api-media/infrastructure/locals.tf
Labels: priority: soon, type: feat, effort: 1, on stage

#3598 feat: replace usage of video endpoints with adminvideo
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_tests/page.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoList.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoList.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoList.tsx
  apps/videos-admin/src/components/PublishedChip/PublishedChip.spec.tsx
  apps/videos-admin/src/components/PublishedChip/PublishedChip.stories.tsx
  apps/videos-admin/src/components/PublishedChip/PublishedChip.tsx
  apps/videos-admin/src/components/PublishedChip/index.ts
  apps/videos-admin/src/libs/useAdminVideo/index.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.spec.tsx
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.tsx
  apps/videos-admin/src/theme/customizations/dataDisplay.tsx
  libs/locales/en/apps-videos-admin.json
Labels: priority: soon, type: feat, effort: 1

#3658 revert: "chore(deps): update ghcr.io/ardatan/hive-gateway docker tag to v1.0.9"
  apps/api-gateway/Dockerfile
  package-lock.json
  package.json
Labels: priority: now, effort: 1, type: revert, on stage

#3494 fix: add updatedAt field for journey
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#3669 feat: add expiration to completed bullmq jobs-no-qa
  apps/api-journeys/src/app/modules/event/event.service.spec.ts
  apps/api-journeys/src/app/modules/event/event.service.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/plausible/plausible.service.ts
  apps/api-media/src/workers/server.ts
Labels: effort: 2, priority: now, type: feat

#3670 fix: set subgraph name properly
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/gateway.config.ts
  apps/api-gateway/gateway.prod.config.ts
  apps/api-gateway/project.json
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: type: fix, priority: now, effort: 1, on stage

#3671 feat: add env to graphiql page title
  apps/api-gateway/gateway.config.ts
  apps/api-gateway/gateway.prod.config.ts
  apps/api-gateway/src/common.config.ts
  infrastructure/modules/aws/ecs-task/main.tf
Labels: priority: now, type: feat, effort: 1, on stage

#3664 fix: generate graphql kakaoTalk
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/button/button.graphql
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/messagePlatformToLabel/messagePlatformToLabel.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/messagePlatformToLabel/messagePlatformToLabel.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/libs/MessageChatIcon/MessageChatIcon.spec.tsx
  libs/journeys/ui/src/libs/MessageChatIcon/MessageChatIcon.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/KakaoTalk.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: type: fix, priority: now, effort: 1, on stage

#3618 refactor: get footer elements
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.tsx
  libs/journeys/ui/src/components/Card/OverlayContent/OverlayContent.tsx
  libs/journeys/ui/src/components/Card/utils/getFooterElements/getFooterElements.spec.ts
  libs/journeys/ui/src/components/Card/utils/getFooterElements/getFooterElements.ts
  libs/journeys/ui/src/components/Card/utils/getFooterElements/index.ts
  libs/journeys/ui/src/components/StepFooter/StepFooter.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
Labels: effort: 3, priority: soon, type: refactor, on stage

#3650 chore: bq video image fields to cf
  apps/api-media/src/workers/bigQuery/importers/videoImages/videoImages.spec.ts
  apps/api-media/src/workers/bigQuery/importers/videoImages/videoImages.ts
Labels: priority: 2day, effort: 2, type: chore, on stage

#3662 fix: poll options reorder
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/MoveBlock/MoveBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.tsx
Labels: effort: 5, type: fix, priority: soon

#3668 feat: eng 1142 arclight facade media country links no qa
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/db/migrations/20241015182830_20241015182828/migration.sql
  apps/api-languages/db/schema.prisma
  apps/api-languages/schema.graphql
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-languages/src/schema/country/country.spec.ts
  apps/api-languages/src/schema/countryLanguage/countryLanguage.ts
  apps/api-languages/src/schema/language/language.spec.ts
  apps/api-languages/src/workers/bigQuery/importers/countryLanguages/countryLanguages.spec.ts
  apps/api-languages/src/workers/bigQuery/importers/countryLanguages/countryLanguages.ts
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/arclight/src/app/v2/media-country-links/route.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#3678 fix: catch error when no video found
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/video/video.ts
Labels: type: fix, priority: now, effort: 1, on stage

#3641 fix: add kakao talk to chat options
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Chat/ChatOption/Details/Details.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1, on stage

#3655 chore: remove uniqueness on order for studyquestion
  apps/api-media/src/schema/video/videoStudyQuestion/inputs/videoStudyQuestionUpdate.ts
  apps/api-media/src/schema/video/videoStudyQuestion/updateOrder.spec.ts
  apps/api-media/src/schema/video/videoStudyQuestion/updateOrder.ts
  apps/api-media/src/schema/video/videoStudyQuestion/videoStudyQuestion.spec.ts
  apps/api-media/src/schema/video/videoStudyQuestion/videoStudyQuestion.ts
Labels: priority: soon, effort: 1, type: chore

#3680 feat: add focal top and left to image block
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/db/migrations/20241017022316_20241017022314/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/image/image.graphql
  apps/api-journeys/src/app/modules/block/image/image.resolver.spec.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: soon, type: feat, effort: 1, on stage

#3687 chore: remove jsondiffpatch
  package-lock.json
  package.json
Labels: priority: 2day, effort: 1, type: chore

#3697 fix: codegen
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: type: fix, priority: now, effort: 1

#3681 fix: node action reorder
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
Labels: effort: 2, type: fix, priority: soon

#3692 feat: add name and version to apollo client
  apps/api-journeys/src/app/modules/email/email.consumer.ts
  apps/api-journeys/src/app/modules/email/emailEvents/emailEvents.consumer.ts
  apps/api-journeys/src/app/modules/integration/growthSpaces/growthSpaces.service.ts
  apps/api-journeys/src/app/modules/plausible/plausible.service.ts
  apps/api-media/src/workers/algolia/service/service.ts
  apps/api-media/src/workers/bigQuery/importers/languageSlugs/languageSlugs.ts
  apps/arclight/src/lib/apolloClient/apolloClient.ts
  apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
  apps/journeys-admin/test/ApolloLoadingProvider.tsx
  apps/journeys/src/libs/apolloClient/apolloClient.ts
  apps/videos-admin/src/app/[locale]/_ApolloProvider/ApolloProvider.tsx
  apps/videos-admin/src/libs/apollo/makeClient.ts
  apps/watch/src/libs/apolloClient/apolloClient.ts
  libs/journeys/ui/test/ApolloLoadingProvider.tsx
Labels: priority: now, type: feat, effort: 1, on stage

#3675 fix: email notifications being submitted
  apps/api-users/src/schema/user/user.mock.ts
  apps/api-users/src/schema/user/user.spec.ts
  apps/api-users/src/schema/user/user.ts
Labels: type: fix, priority: now, effort: 1, on stage

#3702 fix: update vercel environment variables for deployments
  .github/workflows/app-deploy.yml
  .github/workflows/ecs-frontend-deploy-prod-worker.yml
  .github/workflows/ecs-frontend-deploy-stage-worker.yml
  apps/arclight/project.json
  apps/docs/project.json
  apps/journeys-admin/project.json
  apps/journeys-admin/src/libs/firebaseClient/initAuth.ts
  apps/journeys/project.json
  apps/videos-admin/project.json
  apps/watch/project.json
Labels: type: fix, priority: now, effort: 1, on stage

#3710 chore: update to hive gateway 1-2-0
  apps/api-gateway/Dockerfile
  package-lock.json
  package.json
Labels: type: fix, priority: now, effort: 1, on stage

#3719 test: run watch monitoring redirect test separately
  apps/watch-e2e/src/monitoring/watch-redirection.monitor.ts
  apps/watch-e2e/src/monitoring/watch.monitor.ts
  package-lock.json
  package.json
Labels: type: test, priority: soon, effort: 1

#3724 feat: fake cloudflare video images in dev
  apps/api-media/src/workers/bigQuery/importers/videoImages/videoImages.ts
Labels: priority: soon, type: feat, effort: 1

#3715 fix: part3 container error on watch
  apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
  apps/watch/pages/watch/[part1]/[part2]/[part3].tsx
Labels: type: fix, priority: now, effort: 1

#3757 fix: split container and content fetching
  apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
  apps/watch/__generated__/GetVideoContainerPart2.ts
  apps/watch/__generated__/GetVideoContentPart3.ts
  apps/watch/pages/watch/[part1]/[part2].tsx
  apps/watch/pages/watch/[part1]/[part2]/[part3].tsx
Labels: type: fix, priority: now, effort: 1, on stage

#3752 fix: ses transport setup at init instead of maildev in prod
  apps/api-journeys/src/app/modules/email/email.module.ts
  libs/nest/common/src/lib/email/emailService/email.service.spec.ts
  libs/nest/common/src/lib/email/emailService/email.service.ts
  libs/nest/common/src/lib/tracer/tracer.ts
  package-lock.json
  package.json
Labels: type: fix, priority: now, effort: 1, on stage

#3673 fix: show the language in the three dots menu
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DetailsItem/DetailsItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetails/JourneyDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetails/JourneyDetails.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetails/JourneyDetails.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetails/JourneyDetailsDialog/JourneyDetailsDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetails/JourneyDetailsDialog/JourneyDetailsDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetails/JourneyDetailsDialog/JourneyDetailsDialog.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetails/JourneyDetailsDialog/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetails/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/JourneyDetails/JourneyDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/JourneyDetails/JourneyDetails.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Labels: type: fix, effort: 3, priority: soon

#3759 fix: rtl gradient direction
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
Labels: type: fix, priority: soon, effort: 1

#3728 fix: really fix studyQuestion sort order
  apps/api-media/src/schema/video/videoStudyQuestion/updateOrder.spec.ts
  apps/api-media/src/schema/video/videoStudyQuestion/updateOrder.ts
Labels: type: fix, effort: 3, priority: soon

#3600 fix: mobile card selection experience
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/StepBlockNodeMenu.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/StepBlockNodeMenu.tsx
  libs/shared/ui/src/libs/deviceUtils/deviceUtils.spec.ts
  libs/shared/ui/src/libs/deviceUtils/deviceUtils.ts
  libs/shared/ui/src/libs/deviceUtils/index.ts
Labels: type: fix, priority: soon, effort: 1

#3730 chore: remove unused type dependencies
  package-lock.json
  package.json
Labels: priority: 2day, effort: 1, type: chore

#3503 refactor: chat buttons shadow style
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.stories.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.tsx
Labels: priority: soon, effort: 1, type: refactor

#3797 fix: detect step not found on ssr
  apps/journeys/pages/[hostname]/[journeySlug]/[stepSlug].tsx
  apps/journeys/pages/home/[journeySlug]/[stepSlug].tsx
Labels: type: fix, priority: now, effort: 1, on stage

#3649 fix: eng 1091 upload video error
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromCloudflare/AddByFile/data.ts
Labels: priority: 2day, type: fix, effort: 1

#3663 feat: display video block properties by default instead of card properties
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/CardTemplates.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardVideo/CardVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardVideo/CardVideo.tsx
  apps/journeys-admin/src/libs/TestEditorState/TestEditorState.tsx
Labels: effort: 2, priority: soon, type: feat

#3755 fix: disable add video button if card has background image or video
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/Button/Button.tsx
Labels: type: fix, priority: soon, effort: 1

#3783 feat: initial prisma table and seed for editions
  apps/api-media/db/migrations/20241021182357_20241021182355/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/src/__generated__/pothos-types.ts
  apps/api-media/src/workers/seed/service/edition/edition.spec.ts
  apps/api-media/src/workers/seed/service/edition/edition.ts
  apps/api-media/src/workers/seed/service/edition/index.ts
  apps/api-media/src/workers/seed/service/service.spec.ts
  apps/api-media/src/workers/seed/service/service.ts
  apps/api-media/src/workers/seed/service/tag/index.ts
  apps/api-media/src/workers/seed/service/tag/tag.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#3693 feat: metadata language tag routes
  apps/arclight/src/app/v2/metadata-language-tags/[metadataLanguageTag]/route.ts
  apps/arclight/src/app/v2/metadata-language-tags/route.ts
Labels: effort: 2, priority: soon, type: feat

#3784 fix: layout issues when previewing journeys
  apps/journeys/src/components/Conductor/Conductor.tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
Labels: type: fix, effort: 3, priority: soon, on stage

#3801 fix: prevent zoom when editing blocks on ios safari
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/InlineEditInput/InlineEditInput.tsx
Labels: type: fix, priority: soon, effort: 1

#3800 chore: drop graphql authz
  apps/api-analytics/src/lib/rules.ts
  apps/api-analytics/src/schema/builder.ts
  apps/api-analytics/src/schema/site/siteCreate.mutation.ts
  apps/api-analytics/src/yoga.ts
  apps/api-media/src/schema/builder.ts
  apps/api-media/src/schema/cloudflare/image/image.ts
  apps/api-media/src/schema/cloudflare/video/video.ts
  apps/api-media/src/schema/segmind/segmind.ts
  apps/api-media/src/schema/user/user.ts
  apps/api-media/src/schema/video/video.ts
  apps/api-media/src/schema/video/videoDescription/videoDescription.ts
  apps/api-media/src/schema/video/videoImageAlt/videoImageAlt.ts
  apps/api-media/src/schema/video/videoSnippet/videoSnippet.ts
  apps/api-media/src/schema/video/videoStudyQuestion/videoStudyQuestion.ts
  apps/api-media/src/schema/video/videoSubtitle/videoSubtitle.ts
  apps/api-media/src/schema/video/videoTitle/videoTitle.ts
  apps/api-media/src/schema/videoVariant/videoVariant.ts
  apps/api-media/src/schema/videoVariant/videoVariantDownload/videoVariantDownload.ts
  apps/api-users/src/schema/builder.ts
  apps/api-users/src/schema/user/user.ts
  package-lock.json
  package.json
Labels: priority: now, effort: 1, type: chore, on stage

#3819 fix: change email service to use smtp url
  apps/api-journeys-modern/infrastructure/locals.tf
  apps/api-journeys/infrastructure/locals.tf
  apps/api-journeys/src/app/modules/email/email.module.ts
  apps/api-users/infrastructure/locals.tf
  apps/api-users/src/workers/email/service/service.ts
  apps/nexus-admin/__generated__/GetLanguagesContinents.ts
  infrastructure/modules/aws/ecs-task/main.tf
  infrastructure/modules/aws/ecs-task/variables.tf
  libs/nest/common/src/lib/email/emailService/email.service.spec.ts
  libs/nest/common/src/lib/email/emailService/email.service.ts
  libs/yoga/src/email/email.spec.ts
  libs/yoga/src/email/email.ts
  package-lock.json
  package.json
  tsconfig.base.json
Labels: type: fix, priority: now, effort: 1, on stage

#3661 fix: templates page shift feeling
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
Labels: type: fix, priority: soon, effort: 1

#3825 refactor: function for string building
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockThumbnail/ImageBlockThumbnail.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockThumbnail/ImageBlockThumbnail.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Source/SourceFromCloudflare/SourceFromCloudflare.tsx
  apps/journeys-admin/src/components/ImageThumbnail/ImageThumbnail.tsx
Labels: effort: 2, type: fix, priority: soon

#3811 docs: how to deploy localhost on phone or tablet
  apps/docs/docs/02-getting-started/04-running-projects/01-projects-on-local-machine.md
  apps/docs/docs/02-getting-started/04-running-projects/02-projects-on-mobile-device.md
  apps/docs/docs/02-getting-started/04-running-projects/_category_.json
Labels: effort: 2, type: docs, priority: soon

#3785 refactor: include action and journey
  apps/api-journeys/src/app/modules/action/action.resolver.ts
  apps/api-journeys/src/app/modules/action/emailAction/emailAction.resolver.ts
  apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts
  apps/api-journeys/src/app/modules/block/block.resolver.ts
  apps/api-journeys/src/app/modules/block/button/button.resolver.ts
  apps/api-journeys/src/app/modules/block/card/card.resolver.ts
  apps/api-journeys/src/app/modules/block/icon/icon.resolver.ts
  apps/api-journeys/src/app/modules/block/image/image.resolver.ts
  apps/api-journeys/src/app/modules/block/radioOption/radioOption.resolver.ts
  apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.ts
  apps/api-journeys/src/app/modules/block/step/step.resolver.ts
  apps/api-journeys/src/app/modules/block/typography/typography.resolver.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
  apps/api-journeys/src/app/modules/journey/journey.acl.ts
Labels: priority: 2day, good first issue, effort: 1, type: refactor

#3834 feat: improved menu icon selector UI
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Menu/MenuIconSelect/MenuIconSelect.tsx
Labels: priority: soon, type: feat, effort: 1, chromatic

#3839 chore: remove deprecated eslint-plugin-node
  package-lock.json
  package.json
Labels: priority: 2day, effort: 1, type: chore

#3621 test: run 4 tests in parallel (currently running 2 in parallel)
  apps/journeys-admin-e2e/playwright.config.ts
Labels: type: test, priority: 2day, effort: 2

#3846 fix: edition seed
  apps/api-media/src/workers/bigQuery/importers/videoSubtitles/videoSubtitles.spec.ts
  apps/api-media/src/workers/bigQuery/importers/videoSubtitles/videoSubtitles.ts
  apps/api-media/src/workers/bigQuery/importers/videoVariants/videoVariants.spec.ts
  apps/api-media/src/workers/bigQuery/importers/videoVariants/videoVariants.ts
  apps/api-media/src/workers/seed/service/edition/edition.spec.ts
  apps/api-media/src/workers/seed/service/edition/edition.ts
Labels: effort: 2, type: fix, priority: soon, on stage

#3815 feat: create edition relationships in prisma
  apps/api-media/db/migrations/20241022181128_20241022181126/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/src/__generated__/pothos-types.ts
Labels: priority: soon, type: feat, effort: 1, on stage

#3849 feat: extend gql for edition relationship
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/schema.ts
  apps/api-media/src/schema/video/videoSubtitle/videoSubtitle.ts
  apps/api-media/src/schema/videoEdition/index.ts
  apps/api-media/src/schema/videoEdition/videoEdition.ts
  apps/api-media/src/schema/videoVariant/videoVariant.spec.ts
  apps/api-media/src/schema/videoVariant/videoVariant.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 3, priority: soon, type: feat

#3808 fix: reset progress
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromCloudflare/AddByFile/AddByFile.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromCloudflare/AddByFile/utils/addByFileUtils.spec.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromCloudflare/AddByFile/utils/addByFileUtils.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromCloudflare/AddByFile/utils/testFile.mp4
Labels: priority: 2day, good first issue, type: fix, effort: 1

#3802 fix: add protocol check
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Chat/ChatOption/Details/Details.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Chat/ChatOption/Details/Details.tsx
Labels: type: fix, priority: soon, effort: 1

#3863 refactor: host create mutation
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Host/HostForm/HostTitleFieldForm/HostTitleFieldForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Host/HostForm/HostTitleFieldForm/HostTitleFieldForm.tsx
  apps/journeys-admin/src/libs/useHostCreateMutation/index.ts
  apps/journeys-admin/src/libs/useHostCreateMutation/useHostCreateMutation.mock.ts
  apps/journeys-admin/src/libs/useHostCreateMutation/useHostCreateMutation.spec.tsx
  apps/journeys-admin/src/libs/useHostCreateMutation/useHostCreateMutation.ts
Labels: priority: 2day, good first issue, effort: 1, type: refactor

#3860 feat: add gql mutations for edition
  apps/api-media/src/schema/videoEdition/index.ts
  apps/api-media/src/schema/videoEdition/inputs/index.ts
  apps/api-media/src/schema/videoEdition/inputs/videoEditionCreate.ts
  apps/api-media/src/schema/videoEdition/inputs/videoEditionUpdate.ts
  apps/api-media/src/schema/videoEdition/videoEdition.spec.ts
  apps/api-media/src/schema/videoEdition/videoEdition.ts
Labels: effort: 3, priority: soon, type: feat

#3896 feat: add gql queries for editions no qa
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/videoEdition/videoEdition.spec.ts
  apps/api-media/src/schema/videoEdition/videoEdition.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 3, priority: soon, type: feat

#3817 feat: add taxonomies route to arclight Facade
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/db/migrations/20241021180158_20241021180155/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/__generated__/pothos-types.ts
  apps/api-media/src/schema/schema.ts
  apps/api-media/src/schema/taxonomy/index.ts
  apps/api-media/src/schema/taxonomy/taxonomy.spec.ts
  apps/api-media/src/schema/taxonomy/taxonomy.ts
  apps/api-media/src/workers/seed/service/service.spec.ts
  apps/api-media/src/workers/seed/service/service.ts
  apps/api-media/src/workers/seed/service/taxonomy/fields.ts
  apps/api-media/src/workers/seed/service/taxonomy/index.ts
  apps/api-media/src/workers/seed/service/taxonomy/taxonomy.spec.ts
  apps/api-media/src/workers/seed/service/taxonomy/taxonomy.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/arclight/src/app/v2/taxonomies/[category]/route.ts
  apps/arclight/src/app/v2/taxonomies/[taxonomyId]/route.ts
  apps/arclight/src/app/v2/taxonomies/fields.ts
  apps/arclight/src/app/v2/taxonomies/lib.ts
  apps/arclight/src/app/v2/taxonomies/route.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#3900 feat: r2 asset endpoints
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/db/migrations/20241025183517_20241025183515/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/infrastructure/locals.tf
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/__generated__/pothos-types.ts
  apps/api-media/src/schema/cloudflare/index.ts
  apps/api-media/src/schema/cloudflare/r2/asset.spec.ts
  apps/api-media/src/schema/cloudflare/r2/asset.ts
  apps/api-media/src/schema/cloudflare/r2/index.ts
  apps/api-media/src/schema/cloudflare/r2/inputs/cloudflareR2Create.ts
  apps/api-media/src/schema/cloudflare/r2/inputs/cloudflareR2Update.ts
  apps/api-media/src/schema/cloudflare/r2/inputs/index.ts
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/video/video.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  package-lock.json
  package.json
Labels: effort: 8, priority: soon, type: feat, on stage

#3864 feat: virtualize languages autocomplete
  apps/journeys-admin-e2e/src/e2e/discover/journey-level-actions.spec.ts
  apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DetailsItem/DetailsItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DetailsItem/DetailsItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetails/JourneyDetailsDialog/JourneyDetailsDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetails/JourneyDetailsDialog/JourneyDetailsDialog.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.spec.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/OuterElement/OuterElement.spec.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/OuterElement/OuterElement.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/OuterElement/index.ts
  libs/shared/ui/src/components/LanguageAutocomplete/defaultRenderOption/defaultRenderOption.spec.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/defaultRenderOption/defaultRenderOption.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/defaultRenderOption/index.ts
  package-lock.json
  package.json
Labels: effort: 8, priority: soon, type: feat, Performance

#3758 feat: update journey updatedAt on block update
  apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.resolver.ts
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
  apps/api-journeys/src/app/modules/block/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/button/button.resolver.ts
  apps/api-journeys/src/app/modules/block/card/card.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/card/card.resolver.ts
  apps/api-journeys/src/app/modules/block/icon/icon.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/icon/icon.resolver.ts
  apps/api-journeys/src/app/modules/block/image/image.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/image/image.resolver.ts
  apps/api-journeys/src/app/modules/block/radioOption/radioOption.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/radioOption/radioOption.resolver.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.ts
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.ts
  apps/api-journeys/src/app/modules/block/typography/typography.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/typography/typography.resolver.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#3925 feat: multiple node dragging functionality
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
Labels: type: fix, priority: soon, effort: 1

#3911 feat: add mux endpoints similar to cf
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/db/migrations/20241029174127_20241029174125/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/__generated__/pothos-types.ts
  apps/api-media/src/schema/mux/index.ts
  apps/api-media/src/schema/mux/video/index.ts
  apps/api-media/src/schema/mux/video/service.ts
  apps/api-media/src/schema/mux/video/video.spec.ts
  apps/api-media/src/schema/mux/video/video.ts
  apps/api-media/src/schema/schema.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  package-lock.json
  package.json
Labels: priority: 2day, effort: 8, type: feat, on stage

#3933 fix: li components after mui update
  libs/shared/ui/src/components/LanguageAutocomplete/defaultRenderOption/defaultRenderOption.tsx
Labels: type: fix, priority: soon, effort: 1, Bug
