Repository JesusFilm/core, pull requests merged in 2024-06, with the labels that each got.

#2824 chore: add new believer course to watch and videos page
  apps/watch/pages/index.tsx
  apps/watch/pages/videos.tsx
Labels: type: fix, priority: soon, effort: 1

#2825 fix: language switcher encoding for watch
  apps/watch/pages/[part1]/[part2].tsx
Labels: type: fix, effort: 3, priority: now

#2831 fix: team creation updates journey list
  apps/journeys-admin/src/components/Team/TeamCreateForm/TeamCreateForm.tsx
Labels: priority: 2day, type: fix, effort: 1

#2840 fix: failing mock tests
  apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamCreateForm/TeamCreateForm.spec.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.spec.tsx
Labels: type: fix, priority: now, effort: 1

#2823 feat: journey notification management
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20240604232049_20240604232047/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/lib/casl/__generated__/prismaSubjects.ts
  apps/api-journeys/src/app/modules/eventEmailNotifications/evenEmailNotifications.graphql
  apps/api-journeys/src/app/modules/eventEmailNotifications/eventEmailNotifications.module.ts
  apps/api-journeys/src/app/modules/eventEmailNotifications/eventEmailNotifications.resolver.spec.ts
  apps/api-journeys/src/app/modules/eventEmailNotifications/eventEmailNotifications.resolver.ts
Labels: effort: 5, priority: soon, type: feat, on stage

#2844 feat: plausible infrastructure
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .kube/config
  apps/analytics/infrastructure/deploy.sh
  apps/analytics/infrastructure/values.yaml
  infrastructure/environments/prod/data.tf
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/data.tf
  infrastructure/kube/alb/deploy.sh
  infrastructure/kube/alb/iam_policy.json
  infrastructure/kube/aws-auth-cm.yaml
  infrastructure/kube/dashboard/admin-user.yaml
  infrastructure/kube/dashboard/deploy.sh
  infrastructure/kube/dashboard/proxy.sh
  infrastructure/kube/dashboard/token.sh
  infrastructure/kube/datadog/datadog.yaml
  infrastructure/kube/datadog/deploy.sh
  infrastructure/kube/doppler/deploy.sh
  infrastructure/kube/doppler/secrets.yaml
  infrastructure/kube/ingress/deploy.sh
  infrastructure/kube/ingress/deploy.yaml
  infrastructure/kube/ssl/deploy.sh
  infrastructure/kube/ssl/deploy.yaml
  infrastructure/modules/aws/eks/main.tf
  infrastructure/modules/aws/eks/variables.tf
  infrastructure/modules/aws/main.tf
  infrastructure/modules/aws/vpc/main.tf
Labels: effort: 13, priority: soon, type: feat

#2843 fix: reload page after updating url
  libs/journeys/ui/src/libs/action/action.ts
Labels: type: fix, priority: soon, effort: 1

#2852 feat: add plausible env
  apps/api-journeys/infrastructure/locals.tf
Labels: priority: now, type: feat, effort: 1

#2853 feat: watch multi page
  apps/watch/next.config.js
  apps/watch/pages/_app.tsx
  apps/watch/pages/_document.tsx
  apps/watch/pages/watch/[part1]/[part2].tsx
  apps/watch/pages/watch/[part1]/[part2]/[part3].tsx
  apps/watch/pages/watch/index.tsx
  apps/watch/pages/watch/videos.tsx
  apps/watch/public/fonts/fonts.css
  apps/watch/public/site.webmanifest
  apps/watch/public/watch/assets/favicon-180.png
  apps/watch/public/watch/assets/favicon-32.png
  apps/watch/public/watch/assets/fonts/apercu_bold.eot
  apps/watch/public/watch/assets/fonts/apercu_bold.otf
  apps/watch/public/watch/assets/fonts/apercu_bold.svg
  apps/watch/public/watch/assets/fonts/apercu_bold.ttf
  apps/watch/public/watch/assets/fonts/apercu_bold.woff
  apps/watch/public/watch/assets/fonts/apercu_bold.woff2
  apps/watch/public/watch/assets/fonts/apercu_light.eot
  apps/watch/public/watch/assets/fonts/apercu_light.svg
  apps/watch/public/watch/assets/fonts/apercu_light.ttf
  apps/watch/public/watch/assets/fonts/apercu_light.woff
  apps/watch/public/watch/assets/fonts/apercu_light.woff2
  apps/watch/public/watch/assets/fonts/apercu_regular.otf
  apps/watch/public/watch/assets/fonts/apercu_regular.svg
  apps/watch/public/watch/assets/fonts/apercu_regular.ttf
  apps/watch/public/watch/assets/fonts/apercu_regular.woff
  apps/watch/public/watch/assets/fonts/apercu_regular.woff2
  apps/watch/public/watch/assets/fonts/fonts.css
  apps/watch/src/components/HomePage/SeeAllVideos/SeeAllVideos.spec.tsx
  apps/watch/src/components/HomePage/SeeAllVideos/SeeAllVideos.tsx
  apps/watch/src/components/VideoCard/VideoCard.spec.tsx
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
Labels: effort: 5, priority: now, type: feat

#2859 fix: storybook build issues
  .storybook/main.js
Labels: type: fix, priority: soon, effort: 1

#2858 feat: added calendar2 icon
  libs/shared/ui/src/components/icons/Calendar2.tsx
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#2857 feat: added terminal icon
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/Terminal.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#2820 fix: form block update front end
  apps/journeys-admin/__generated__/GetJourneyVisitors.ts
  apps/journeys-admin/__generated__/TextResponseBlockUpdateContent.ts
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/TextResponseEdit/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardDetails/VisitorCardDetails.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardDetails/VisitorCardDetails.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.spec.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.stories.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
  libs/journeys/ui/src/libs/isActionBlock/isActionBlock.ts
Labels: type: fix, priority: soon, effort: 1

#2863 fix: update router push
  apps/watch/pages/watch/[part1]/[part2].tsx
  apps/watch/pages/watch/[part1]/[part2]/[part3].tsx
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.spec.tsx
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.tsx
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
Labels: type: fix, priority: now, effort: 1

#2854 refactor: text response action deprecated
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.graphql
Labels: priority: soon, effort: 1, type: refactor

#2862 feat: add turkish to template language filter
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/data.ts
Labels: priority: soon, type: feat, effort: 1

#2865 feat: event email notification on delete cascade
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20240611215915_20240611215913/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/eventEmailNotifications/evenEmailNotifications.graphql
  apps/api-journeys/src/app/modules/eventEmailNotifications/eventEmailNotifications.resolver.spec.ts
  apps/api-journeys/src/app/modules/eventEmailNotifications/eventEmailNotifications.resolver.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#2861 feat: add tatai to k8s
  apps/analytics/infrastructure/deploy.sh
  apps/analytics/infrastructure/values.yaml
  infrastructure/kube/alb/deploy.sh
  infrastructure/kube/aws-auth-cm.yaml
  infrastructure/kube/dashboard/deploy.sh
  infrastructure/kube/dashboard/proxy.sh
  infrastructure/kube/dashboard/token.sh
  infrastructure/kube/datadog/datadog.yaml
  infrastructure/kube/datadog/deploy.sh
  infrastructure/kube/doppler/deploy.sh
  infrastructure/kube/ingress/deploy.sh
  infrastructure/kube/ssl/deploy.sh
  infrastructure/modules/aws/eks/main.tf
Labels: priority: 2day, type: feat, effort: 1

#2855 refactor: drop action in text response
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/action/canBlockHaveAction/canBlockHaveAction.spec.ts
  apps/api-journeys/src/app/modules/action/canBlockHaveAction/canBlockHaveAction.ts
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.graphql
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.ts
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/CardFormCreate.ts
  apps/journeys-admin/__generated__/GetAdminJourney.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/TextResponseBlockCreate.ts
  apps/journeys-admin/__generated__/TextResponseFields.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/getPriorityBlock/getPriorityBlock.spec.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewTextResponseButton/NewTextResponseButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewTextResponseButton/NewTextResponseButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Hint/Hint.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Label/Label.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/MinRows/MinRows.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardForm/CardForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardForm/CardForm.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/ActionCards/ActionCards.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/ActionCards/ActionCards.tsx
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/TextResponseFields.ts
  apps/journeys/src/libs/testData/storyData.ts
  apps/nexus-admin/__generated__/BlockFields.ts
  apps/nexus-admin/__generated__/JourneyFields.ts
  apps/nexus-admin/__generated__/TextResponseFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/TextResponseFields.ts
  libs/journeys/ui/src/components/TextResponse/TextResponse.spec.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.stories.tsx
  libs/journeys/ui/src/components/TextResponse/__generated__/TextResponseFields.ts
  libs/journeys/ui/src/components/TextResponse/textResponseFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
Labels: priority: soon, effort: 1, type: refactor, on stage

#2866 feat: countries api
  apps/api-languages/db/migrations/20240611223847_20240611223846/migration.sql
  apps/api-languages/db/schema.prisma
  apps/api-languages/db/seed.ts
  apps/api-languages/src/app/app.module.ts
  apps/api-languages/src/app/modules/country/country.graphql
  apps/api-languages/src/app/modules/country/country.module.ts
  apps/api-languages/src/app/modules/country/country.resolver.spec.ts
  apps/api-languages/src/app/modules/country/country.resolver.ts
Labels: priority: 2day, effort: 3, type: feat

#2869 fix: missing graphql schema
  apps/api-gateway/schema.graphql
  apps/api-languages/schema.graphql
  apps/api-languages/src/app/__generated__/graphql.ts
Labels: type: fix, priority: now, effort: 1

#2876 fix: encode contentid on page 3
  apps/watch/pages/watch/[part1]/[part2]/[part3].tsx
Labels: type: fix, priority: soon, effort: 1

#2877 feat: devcontainer updates
  .devcontainer/Dockerfile
  .devcontainer/docker-compose.yml
  .devcontainer/post-create-command.sh
Labels: priority: 2day, effort: 2, type: feat

#2833 refactor: card and video wrappers
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateToBlockAction/CardItem/CardItem.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.tsx
  libs/journeys/ui/src/components/CardWrapper/CardWrapper.spec.tsx
  libs/journeys/ui/src/components/CardWrapper/CardWrapper.tsx
  libs/journeys/ui/src/components/CardWrapper/index.ts
  libs/journeys/ui/src/components/VideoWrapper/VideoWrapper.spec.tsx
  libs/journeys/ui/src/components/VideoWrapper/VideoWrapper.tsx
  libs/journeys/ui/src/components/VideoWrapper/index.ts
Labels: priority: 2day, effort: 1, type: refactor

#2839 refactor: getTags queries
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TemplateSettingsItem/TemplateSettingsDialog/CategoriesTabPanel/CategoriesTabPanel.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TemplateSettingsItem/TemplateSettingsDialog/CategoriesTabPanel/CategoriesTabPanel.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TemplateSettingsItem/TemplateSettingsDialog/TemplateSettingsDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TemplateSettingsItem/TemplateSettingsDialog/TemplateSettingsDialog.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagsFilter/TagsFilter.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagsFilter/TagsFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/data.ts
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TemplateTags.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TemplateTags.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TemplateTags.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.stories.tsx
  apps/journeys-admin/src/libs/useTagsQuery/index.ts
  apps/journeys/__generated__/GetTags.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/nexus-admin/__generated__/GetTags.ts
  apps/nexus-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/GetTags.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/libs/useTagsQuery/__generated__/GetTags.ts
  libs/journeys/ui/src/libs/useTagsQuery/index.ts
  libs/journeys/ui/src/libs/useTagsQuery/useTagsQuery.spec.tsx
  libs/journeys/ui/src/libs/useTagsQuery/useTagsQuery.ts
Labels: priority: 2day, effort: 3, type: refactor

#2879 fix: template languages selected text
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: now, effort: 1

#2867 chore: nx 19.2.3
  .github/workflows/app-deploy.yml
  .gitignore
  .prettierignore
  package-lock.json
  package.json
Labels: priority: soon, effort: 1, type: chore

#2841 feat: get plausible breakdown
  apps/journeys-admin/__generated__/GetJourneyPlausibleStatsBreakdown.ts
  apps/journeys-admin/__generated__/PlausibleJourneyAggregateVisitorsFields.ts
  apps/journeys-admin/__generated__/PlausibleJourneyReferrerFields.ts
  apps/journeys-admin/__generated__/PlausibleJourneyStepsActionsFields.ts
  apps/journeys-admin/__generated__/PlausibleJourneyStepsFields.ts
  apps/journeys-admin/__generated__/PlausibleJourneyVisitorsPageExitsFields.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Editor.tsx
  apps/journeys-admin/src/libs/useJourneyPlausibleStatsBreakdownQuery/index.ts
  apps/journeys-admin/src/libs/useJourneyPlausibleStatsBreakdownQuery/useJourneyPlausibleStatsBreakdownQuery.mock.ts
  apps/journeys-admin/src/libs/useJourneyPlausibleStatsBreakdownQuery/useJourneyPlausibleStatsBreakdownQuery.ts
  apps/journeys/__generated__/PlausibleJourneyAggregateVisitorsFields.ts
  apps/journeys/__generated__/PlausibleJourneyReferrerFields.ts
  apps/journeys/__generated__/PlausibleJourneyStepsActionsFields.ts
  apps/journeys/__generated__/PlausibleJourneyStepsFields.ts
  apps/journeys/__generated__/PlausibleJourneyVisitorsPageExitsFields.ts
  apps/nexus-admin/__generated__/PlausibleJourneyAggregateVisitorsFields.ts
  apps/nexus-admin/__generated__/PlausibleJourneyReferrerFields.ts
  apps/nexus-admin/__generated__/PlausibleJourneyStepsActionsFields.ts
  apps/nexus-admin/__generated__/PlausibleJourneyStepsFields.ts
  apps/nexus-admin/__generated__/PlausibleJourneyVisitorsPageExitsFields.ts
  apps/watch/__generated__/PlausibleJourneyAggregateVisitorsFields.ts
  apps/watch/__generated__/PlausibleJourneyReferrerFields.ts
  apps/watch/__generated__/PlausibleJourneyStepsActionsFields.ts
  apps/watch/__generated__/PlausibleJourneyStepsFields.ts
  apps/watch/__generated__/PlausibleJourneyVisitorsPageExitsFields.ts
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
  libs/journeys/ui/src/libs/plausibleHelpers/index.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/index.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/plausibleFields/__generated__/PlausibleJourneyAggregateVisitorsFields.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/plausibleFields/__generated__/PlausibleJourneyReferrerFields.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/plausibleFields/__generated__/PlausibleJourneyStepsActionsFields.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/plausibleFields/__generated__/PlausibleJourneyStepsFields.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/plausibleFields/__generated__/PlausibleJourneyVisitorsPageExitsFields.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/plausibleFields/index.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/plausibleFields/plausibleJourneyAggregateVisitorsFields.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/plausibleFields/plausibleJourneyReferrerFields.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/plausibleFields/plausibleJourneyStepsActionsFields.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/plausibleFields/plausibleJourneyStepsFields.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/plausibleFields/plausibleJourneyVisitorsPageExitsFields.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/transformPlausibleBreakdown.spec.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/transformPlausibleBreakdown.ts
Labels: effort: 8, priority: soon, type: feat

#2847 refactor: beacon page viewed
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Accordion/Accordion.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageSource/ImageSource.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Source/Source.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/AccessItem/AccessItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DescriptionItem/DescriptionItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/LanguageItem/LanguageItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TemplateSettingsItem/TemplateSettingsItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TitleItem/TitleItem.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
  apps/journeys-admin/src/libs/setBeaconPageViewed/setBeaconPageViewed.ts
  libs/journeys/ui/src/libs/setBeaconPageViewed/index.ts
  libs/journeys/ui/src/libs/setBeaconPageViewed/setBeaconPageViewed.spec.ts
  libs/journeys/ui/src/libs/setBeaconPageViewed/setBeaconPageViewed.ts
Labels: priority: 2day, effort: 1, type: refactor

#2870 refactor: parentTagIcon
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TemplateSettingsItem/TemplateSettingsDialog/CategoriesTabPanel/CategoriesTabPanel.tsx
  apps/journeys-admin/src/components/TemplateGallery/TagsFilter/TagsFilter.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateTags/TemplateTags.tsx
  libs/journeys/ui/src/components/ParentTagIcon/ParentTagIcon.spec.tsx
  libs/journeys/ui/src/components/ParentTagIcon/ParentTagIcon.tsx
  libs/journeys/ui/src/components/ParentTagIcon/index.ts
Labels: priority: 2day, effort: 2, type: refactor

#2872 refactor: journeyDuplicate query
  apps/journeys-admin/src/components/Editor/Toolbar/Items/CreateTemplateItem/CreateTemplateItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/CreateTemplateItem/CreateTemplateItem.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.spec.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.tsx
  apps/journeys/__generated__/DuplicatedJourney.ts
  apps/journeys/__generated__/JourneyDuplicate.ts
  apps/nexus-admin/__generated__/DuplicatedJourney.ts
  apps/nexus-admin/__generated__/JourneyDuplicate.ts
  apps/watch/__generated__/DuplicatedJourney.ts
  apps/watch/__generated__/JourneyDuplicate.ts
  libs/journeys/ui/src/libs/useJourneyDuplicateMutation/__generated__/DuplicatedJourney.ts
  libs/journeys/ui/src/libs/useJourneyDuplicateMutation/__generated__/JourneyDuplicate.ts
  libs/journeys/ui/src/libs/useJourneyDuplicateMutation/index.ts
  libs/journeys/ui/src/libs/useJourneyDuplicateMutation/useJourneyDuplicateMutation.ts
Labels: priority: 2day, effort: 2, type: refactor

#2864 feat: added essentials addon
  .storybook/main.ts
Labels: priority: soon, type: feat, effort: 1

#2849 refactor: frame portal
  apps/arclight/__generated__/graphql-env.d.ts
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateToBlockAction/CardItem/CardItem.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/ActionCards/ActionCards.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/EmbedJourneyDialog/EmbedCardPreview/EmbedCardPreview.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.tsx
  libs/journeys/ui/src/components/FramePortal/FramePortal.spec.tsx
  libs/journeys/ui/src/components/FramePortal/FramePortal.stories.tsx
  libs/journeys/ui/src/components/FramePortal/FramePortal.tsx
  libs/journeys/ui/src/components/FramePortal/index.ts
Labels: priority: 2day, effort: 1, type: refactor

#2873 fix: refactor eventEmailNotifications
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20240613000839_20240613000837/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/lib/casl/__generated__/prismaSubjects.ts
  apps/api-journeys/src/app/lib/casl/caslFactory/caslFactory.spec.ts
  apps/api-journeys/src/app/lib/casl/caslFactory/caslFactory.ts
  apps/api-journeys/src/app/modules/eventEmailNotifications/evenEmailNotifications.graphql
  apps/api-journeys/src/app/modules/eventEmailNotifications/eventEmailNotifications.resolver.spec.ts
  apps/api-journeys/src/app/modules/eventEmailNotifications/eventEmailNotifications.resolver.ts
  apps/api-journeys/src/app/modules/journeyNotification/journeyNotification.acl.spec.ts
  apps/api-journeys/src/app/modules/journeyNotification/journeyNotification.acl.ts
  apps/api-journeys/src/app/modules/journeyNotification/journeyNotification.graphql
  apps/api-journeys/src/app/modules/journeyNotification/journeyNotification.module.ts
  apps/api-journeys/src/app/modules/journeyNotification/journeyNotification.resolver.spec.ts
  apps/api-journeys/src/app/modules/journeyNotification/journeyNotification.resolver.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.ts
  apps/api-journeys/src/app/modules/userTeam/userTeam.resolver.spec.ts
  apps/api-journeys/src/app/modules/userTeam/userTeam.resolver.ts
Labels: effort: 5, priority: soon, type: refactor, on stage

#2880 test: update admin app's monitoring script
  apps/journeys-admin-e2e/src/monitoring/journeys-admin.monitor.ts
  checkly.config.ts
  package-lock.json
  package.json
Labels: type: test, priority: now, effort: 1

#2883 refactor: video 100
  libs/journeys/ui/src/components/Video/Video.tsx
Labels: type: fix, priority: now, effort: 1

#2888 feat: new video subtitle schema
  apps/api-videos/db/migrations/20240614205308_20240614205305/migration.sql
  apps/api-videos/db/schema.prisma
  apps/api-videos/project.json
Labels: effort: 2, priority: soon, type: feat

#2890 fix: resolver field journey notifications
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.spec.ts
  apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#2884 refactor: i18next
  apps/journeys-admin/setupTests.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActivePriorityList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardInfo/JourneyCardInfo.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/JourneyVisitorsList.stories.tsx
  apps/journeys-admin/src/components/Team/TeamUpdateDialog/TeamUpdateDialog.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.stories.tsx
  apps/journeys-admin/src/components/TemplateList/ActiveTemplateList/ActiveTemplateList.stories.tsx
  apps/journeys-admin/src/components/TemplateList/ArchivedTemplateList/ArchivedTemplateList.stories.tsx
  apps/journeys-admin/src/components/TemplateList/TemplateList.stories.tsx
  apps/journeys-admin/src/components/TemplateList/TemplateListItem/TemplateListItem.stories.tsx
  apps/journeys-admin/src/components/TemplateList/TrashedTemplateList/TrashedTemplateList.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/EventsCard.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/EventsCard.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/TimelineEvent/TimelineEvent.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/TimelineEvent/TimelineEvent.stories.tsx
  libs/journeys/ui/test/i18n.ts
  libs/journeys/ui/tsconfig.json
  tsconfig.base.json
Labels: priority: soon, effort: 1, type: refactor

#2871 fix: text response enhancements
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewTextResponseButton/NewTextResponseButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.tsx
  libs/journeys/ui/src/components/TextField/TextField.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#2892 refactor: abbreviate language
  apps/journeys-admin/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
  libs/journeys/ui/src/libs/abbreviateLanguageName/abbreviateLangaugeName.spec.tsx
  libs/journeys/ui/src/libs/abbreviateLanguageName/abbreviateLanguageName.ts
  libs/journeys/ui/src/libs/abbreviateLanguageName/index.ts
Labels: priority: soon, effort: 1, type: refactor

#2889 feat: audio preview schema
  apps/api-languages/db/migrations/20240615005514_20240615005513/migration.sql
  apps/api-languages/db/schema.prisma
Labels: priority: 2day, type: fix, effort: 1

#2897 feat: bible citations schema
  apps/api-videos/db/migrations/20240617201146_20240617201145/migration.sql
  apps/api-videos/db/schema.prisma
Labels: effort: 2, priority: soon, type: feat

#2895 refactor: strategy section
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TemplateSettingsItem/TemplateSettingsDialog/AboutTabPanel/AboutTabPanel.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  libs/journeys/ui/src/components/StrategySection/StrategySection.spec.tsx
  libs/journeys/ui/src/components/StrategySection/StrategySection.stories.tsx
  libs/journeys/ui/src/components/StrategySection/StrategySection.tsx
  libs/journeys/ui/src/components/StrategySection/index.ts
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, effort: 1, type: refactor

#2898 refactor: use user role
  apps/journeys-admin/pages/publisher/index.tsx
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserNavigation.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.stories.tsx
  apps/journeys-admin/src/components/TemplateView/TemplateView.tsx
  apps/journeys-admin/src/libs/useUserRoleQuery/index.ts
  apps/journeys-admin/src/libs/useUserRoleSuspenseQuery/useUserRoleSuspenseQuery.tsx
  apps/journeys/__generated__/GetUserRole.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/nexus-admin/__generated__/GetUserRole.ts
  apps/nexus-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/GetUserRole.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/libs/useUserRoleQuery/__generated__/GetUserRole.ts
  libs/journeys/ui/src/libs/useUserRoleQuery/index.ts
  libs/journeys/ui/src/libs/useUserRoleQuery/useUserRoleQuery.tsx
Labels: priority: soon, effort: 1, type: refactor

#2899 fix: chat button not crashing on click
  biome.json
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.spec.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.tsx
Labels: type: fix, priority: soon, effort: 1, on stage

#2900 refactor: i18next
  apps/journeys-admin/setupTests.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActivePriorityList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.stories.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardInfo/JourneyCardInfo.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/JourneyVisitorsList.stories.tsx
  apps/journeys-admin/src/components/Team/TeamUpdateDialog/TeamUpdateDialog.spec.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.stories.tsx
  apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.stories.tsx
  apps/journeys-admin/src/components/TemplateList/ActiveTemplateList/ActiveTemplateList.stories.tsx
  apps/journeys-admin/src/components/TemplateList/ArchivedTemplateList/ArchivedTemplateList.stories.tsx
  apps/journeys-admin/src/components/TemplateList/TemplateList.stories.tsx
  apps/journeys-admin/src/components/TemplateList/TemplateListItem/TemplateListItem.stories.tsx
  apps/journeys-admin/src/components/TemplateList/TrashedTemplateList/TrashedTemplateList.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/EventsCard.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/EventsCard.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/TimelineEvent/TimelineEvent.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/TimelineEvent/TimelineEvent.stories.tsx
  apps/journeys-admin/test/i18n.ts
  libs/journeys/ui/test/i18n.ts
Labels: priority: now, effort: 1, type: refactor

#2903 refactor: update last active team
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/teams/new.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.spec.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamDialog/CopyToTeamDialog.spec.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamDialog/CopyToTeamDialog.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.spec.tsx
  apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamCreateForm/TeamCreateForm.spec.tsx
  apps/journeys-admin/src/components/Team/TeamCreateForm/TeamCreateForm.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.spec.tsx
  apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.spec.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.tsx
  apps/journeys/__generated__/UpdateLastActiveTeamId.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/nexus-admin/__generated__/UpdateLastActiveTeamId.ts
  apps/nexus-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/UpdateLastActiveTeamId.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/libs/useUpdateLastActiveTeamIdMutation/__generated__/UpdateLastActiveTeamId.ts
  libs/journeys/ui/src/libs/useUpdateLastActiveTeamIdMutation/index.ts
  libs/journeys/ui/src/libs/useUpdateLastActiveTeamIdMutation/useUpdateLastActiveTeamIdMutation.ts
Labels: priority: now, effort: 1, type: refactor

#2809 feat: analytics email service
  apps/api-journeys/src/app/emails/stories/VisitorInteraction.stories.tsx
  apps/api-journeys/src/app/emails/templates/VisitorInteraction/VisitorInteraction.tsx
  apps/api-journeys/src/app/emails/templates/VisitorInteraction/index.ts
  apps/api-journeys/src/app/lib/fetchEmailDetails/fetchEmailDetails.spec.ts
  apps/api-journeys/src/app/lib/fetchEmailDetails/fetchEmailDetails.ts
  apps/api-journeys/src/app/lib/fetchEmailDetails/index.ts
  apps/api-journeys/src/app/lib/processUserIds/index.ts
  apps/api-journeys/src/app/lib/processUserIds/processUserIds.spec.ts
  apps/api-journeys/src/app/lib/processUserIds/processUserIds.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
  apps/api-journeys/src/app/modules/email/email.module.ts
  apps/api-journeys/src/app/modules/email/emailEvents/emailEvents.consumer.spec.ts
  apps/api-journeys/src/app/modules/email/emailEvents/emailEvents.consumer.ts
  apps/api-journeys/src/app/modules/event/button/button.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/button/button.resolver.ts
  apps/api-journeys/src/app/modules/event/event.module.ts
  apps/api-journeys/src/app/modules/event/event.service.spec.ts
  apps/api-journeys/src/app/modules/event/event.service.ts
  apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.ts
  apps/api-journeys/src/app/modules/event/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/video/video.resolver.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  libs/nest/common/src/lib/email/components/ActionCard/ActionCard.tsx
  libs/nest/common/src/lib/email/components/UnsubscribeLink/UnsubscribeLink.tsx
Labels: priority: soon, type: feat, effort: 1, on stage

#2815 feat: resource hub header
  .storybook/main.ts
  apps/watch/pages/_app.tsx
  apps/watch/pages/calendar/index.tsx
  apps/watch/pages/journeys/index.tsx
  apps/watch/pages/products/index.tsx
  apps/watch/pages/strategies/index.tsx
  apps/watch/pages/watch/[part1]/[part2].tsx
  apps/watch/pages/watch/[part1]/[part2]/[part3].tsx
  apps/watch/pages/watch/index.tsx
  apps/watch/pages/watch/videos.tsx
  apps/watch/src/components/Header/Header.spec.tsx
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Header/HeaderTabButtons/HeaderTabButtons.spec.tsx
  apps/watch/src/components/Header/HeaderTabButtons/HeaderTabButtons.tsx
  apps/watch/src/components/Header/HeaderTabButtons/index.ts
  apps/watch/src/components/Header/assets/minimal-logo.png
  apps/watch/src/components/HomePage/index.ts
  apps/watch/src/components/PageWrapper/PageWrapper.spec.tsx
  apps/watch/src/components/PageWrapper/PageWrapper.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.spec.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
  apps/watch/src/components/WatchHomePage/HomeHero/HomeHero.spec.tsx
  apps/watch/src/components/WatchHomePage/HomeHero/HomeHero.stories.tsx
  apps/watch/src/components/WatchHomePage/HomeHero/HomeHero.tsx
  apps/watch/src/components/WatchHomePage/HomeHero/assets/jesus.jpg
  apps/watch/src/components/WatchHomePage/HomeHero/index.ts
  apps/watch/src/components/WatchHomePage/SeeAllVideos/SeeAllVideos.spec.tsx
  apps/watch/src/components/WatchHomePage/SeeAllVideos/SeeAllVideos.stories.tsx
  apps/watch/src/components/WatchHomePage/SeeAllVideos/SeeAllVideos.tsx
  apps/watch/src/components/WatchHomePage/SeeAllVideos/index.ts
  apps/watch/src/components/WatchHomePage/WatchHomePage.stories.tsx
  apps/watch/src/components/WatchHomePage/WatchHomePage.tsx
  apps/watch/src/components/WatchHomePage/index.ts
  apps/watch/src/libs/getFlags/getFlags.tsx
  apps/watch/src/libs/getFlags/index.ts
  libs/locales/en/apps-watch.json
  libs/shared/ui/src/libs/themes/website/tokens/colors.ts
  package-lock.json
  package.json
Labels: effort: 8, priority: soon, type: feat

#2850 feat: plausible stats collection
  apps/journeys-admin/next.config.js
  apps/journeys/middleware.ts
  apps/journeys/next.config.js
  apps/journeys/pages/[hostname]/[journeySlug].tsx
  apps/journeys/pages/home/[journeySlug].tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ReactionButton/ReactionButton.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareButton.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.spec.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.tsx
  libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/plausibleHelpers/index.ts
  libs/journeys/ui/src/libs/plausibleHelpers/plausibleHelpers.ts
  package-lock.json
  package.json
Labels: effort: 3, priority: soon, type: feat

#2837 fix: backwards edge editing not removing old edge
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useUpdateEdge/useUpdateEdge.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useUpdateEdge/useUpdateEdge.ts
Labels: type: fix, priority: soon, effort: 1

#2911 fix: remove header divider on watch
  apps/watch/src/components/Header/Header.tsx
Labels: type: fix, priority: now, effort: 1

#2918 fix: biblebook schema
  apps/api-videos/db/migrations/20240619213007_20240619213005/migration.sql
  apps/api-videos/db/schema.prisma
Labels: type: fix, priority: soon, effort: 1

#2912 refactor: copyToTeamDialog
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.tsx
  apps/journeys-admin/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.tsx
  libs/journeys/ui/src/components/CopyToTeamDialog/CopyToTeamDialog.spec.tsx
  libs/journeys/ui/src/components/CopyToTeamDialog/CopyToTeamDialog.stories.tsx
  libs/journeys/ui/src/components/CopyToTeamDialog/CopyToTeamDialog.tsx
  libs/journeys/ui/src/components/CopyToTeamDialog/index.ts
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, effort: 1, type: refactor

#2922 fix: journeys querys
  apps/journeys-admin/pages/templates/[journeyId].tsx
Labels: effort: 2, type: fix, priority: now

#2923 refactor: remove uws from analytics
  apps/api-analytics/Dockerfile
  apps/api-analytics/src/main.ts
  apps/api-analytics/src/yoga.ts
  package-lock.json
  package.json
Labels: priority: now, effort: 1, type: refactor, on stage

#2924 fix: duplicate empty blocks
  apps/api-journeys/src/app/modules/block/block.service.ts
Labels: effort: 2, type: fix, priority: now, on stage

#2813 feat: plausible backend
  .storybook/static/mockServiceWorker.js
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/gql.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/plausible/plausible.consumer.spec.ts
  apps/api-journeys/src/app/modules/plausible/plausible.graphql
  apps/api-journeys/src/app/modules/plausible/plausible.handlers.ts
  apps/api-journeys/src/app/modules/plausible/plausible.module.ts
  apps/api-journeys/src/app/modules/plausible/plausible.resolver.spec.ts
  apps/api-journeys/src/app/modules/plausible/plausible.resolver.ts
  apps/api-journeys/src/app/modules/plausible/plausible.service.spec.ts
  apps/api-journeys/src/app/modules/plausible/plausible.service.ts
  apps/journeys-admin/jest.config.ts
  apps/journeys-admin/jest.polyfills.js
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/VideoFromYouTube.handlers.ts
  package-lock.json
  package.json
Labels: effort: 5, priority: now, type: feat, on stage

#2896 refactor: background video 100
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.spec.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
Labels: priority: soon, effort: 1, type: refactor

#2910 feat: collect plausible stats
  apps/journeys/middleware.ts
  apps/journeys/next.config.js
  apps/journeys/pages/[hostname]/[journeySlug].tsx
  apps/journeys/pages/home/[journeySlug].tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.spec.tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.spec.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.spec.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ReactionButton/ReactionButton.spec.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ReactionButton/ReactionButton.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareButton.spec.tsx
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareButton.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.spec.tsx
  libs/journeys/ui/src/components/VideoEvents/VideoEvents.tsx
  libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/plausibleHelpers/index.ts
  libs/journeys/ui/src/libs/plausibleHelpers/plausibleHelpers.spec.ts
  libs/journeys/ui/src/libs/plausibleHelpers/plausibleHelpers.ts
  package-lock.json
  package.json
Labels: effort: 5, priority: now, type: feat, on stage

#2927 fix: alignment of logo and menu on watch header
  apps/watch/src/components/Header/Header.tsx
Labels: effort: 2, type: fix, priority: soon

#2921 feat: watch header style changes
  apps/watch/next.config.js
  apps/watch/src/components/Header/Header.spec.tsx
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Header/HeaderTabButtons/HeaderTabButtons.spec.tsx
  apps/watch/src/components/Header/HeaderTabButtons/HeaderTabButtons.tsx
Labels: effort: 2, priority: soon, type: feat

#2930 fix: plausible resolver fragments
  apps/api-journeys/src/app/modules/journey/journey.module.ts
  apps/api-journeys/src/app/modules/plausible/plausible.module.ts
  apps/api-journeys/src/app/modules/plausible/plausible.resolver.spec.ts
  apps/api-journeys/src/app/modules/plausible/plausible.resolver.ts
Labels: type: fix, priority: soon, effort: 1

#2928 feat: watch header and headertabbuttons stories
  apps/watch/src/components/Header/Header.stories.tsx
Labels: effort: 2, priority: now, type: feat

#2886 fix: analytics switch
  apps/journeys-admin/src/components/Editor/Editor.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsOverlaySwitch/AnalyticsOverlaySwitch.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/NewStepButton/NewStepButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/BaseEdge/BaseEdge.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/BaseEdge/BaseEdge.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/CustomEdge/CustomEdge.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteOnKeyPress/useDeleteOnKeyPress.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteOnKeyPress/useDeleteOnKeyPress.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, effort: 3, priority: soon

#2934 refactor: get stats
  apps/journeys-admin/__generated__/GetJourneyPlausibleStatsBreakdown.ts
  apps/journeys-admin/__generated__/PlausibleJourneyActionsSumsFields.ts
  apps/journeys-admin/src/libs/useJourneyPlausibleStatsBreakdownQuery/useJourneyPlausibleStatsBreakdownQuery.mock.ts
  apps/journeys-admin/src/libs/useJourneyPlausibleStatsBreakdownQuery/useJourneyPlausibleStatsBreakdownQuery.ts
  apps/journeys/__generated__/PlausibleJourneyActionsSumsFields.ts
  apps/nexus-admin/__generated__/PlausibleJourneyActionsSumsFields.ts
  apps/watch/__generated__/PlausibleJourneyActionsSumsFields.ts
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/plausibleFields/__generated__/PlausibleJourneyActionsSums.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/plausibleFields/__generated__/PlausibleJourneyActionsSumsFields.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/plausibleFields/index.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/plausibleFields/plausibleJourneyActionsSumsFields.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/transformPlausibleBreakdown.spec.ts
  libs/journeys/ui/src/libs/transformPlausibleBreakdown/transformPlausibleBreakdown.ts
Labels: priority: now, effort: 1, type: refactor

#2938 feat: quick template to journey
  .vscode/settings.json
  apps/api-journeys/src/app/modules/mailChimp/mailChimp.service.spec.ts
  apps/api-journeys/src/app/modules/mailChimp/mailChimp.service.ts
  apps/journeys-admin/__generated__/GetTeams.ts
  apps/journeys-admin/pages/journeys/[journeyId]/quick.tsx
  apps/journeys-admin/pages/templates/[journeyId]/quick.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingStepper/OnboardingStepper.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingStepper/OnboardingStepper.tsx
  apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.spec.tsx
  apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.ts
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.spec.tsx
  apps/journeys-admin/src/libs/initAndAuthApp/initAndAuthApp.ts
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, effort: 13, type: feat, on stage

#2937 feat: journey express setup
  apps/journeys-admin/pages/journeys/[journeyId]/quick.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettings.stories.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettings.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsChat/JourneyQuickSettingsChat.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsChat/index.ts
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsGoals/JourneyQuickSettingsGoals.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsGoals/index.ts
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsTabs/JourneyQuickSettingsTabs.spec.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsTabs/JourneyQuickSettingsTabs.stories.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsTabs/JourneyQuickSettingsTabs.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsTabs/index.ts
  apps/journeys-admin/src/components/JourneyQuickSettings/index.ts
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingDrawer.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingStepper/OnboardingStepper.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingStepper/OnboardingStepper.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingTemplateCard/OnboardingTemplateCard.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: now, type: feat

#2941 feat: hosttitlefieldform props
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostTitleFieldForm/HostTitleFieldForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostForm/HostTitleFieldForm/HostTitleFieldForm.tsx
Labels: effort: 2, priority: now, type: feat

#2942 feat: add quick goals
  apps/journeys-admin/pages/journeys/[journeyId]/quick.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsList.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsListItem/GoalsListItem.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettings.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsGoals/JourneyQuickSettingsGoals.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 5, priority: now, type: feat

#2943 feat: used hosttitlefieldform props on journeyquicksettingschat
  apps/journeys-admin/pages/journeys/[journeyId]/quick.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettings.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsChat/JourneyQuickSettingsChat.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingStepper/OnboardingStepper.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingStepper/OnboardingStepper.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, type: feat, effort: 1

#2945 chore: new crowdin translations
  libs/locales/am-ET/apps-journeys-admin.json
  libs/locales/am-ET/apps-watch.json
  libs/locales/am-ET/libs-journeys-ui.json
  libs/locales/ar-SA/apps-journeys-admin.json
  libs/locales/ar-SA/apps-journeys.json
  libs/locales/ar-SA/apps-watch.json
  libs/locales/ar-SA/libs-journeys-ui.json
  libs/locales/bn-BD/apps-journeys-admin.json
  libs/locales/bn-BD/apps-watch.json
  libs/locales/bn-BD/libs-journeys-ui.json
  libs/locales/es-ES/apps-journeys-admin.json
  libs/locales/es-ES/apps-watch.json
  libs/locales/es-ES/libs-journeys-ui.json
  libs/locales/fr-FR/apps-journeys-admin.json
  libs/locales/fr-FR/apps-watch.json
  libs/locales/fr-FR/libs-journeys-ui.json
  libs/locales/hi-IN/apps-journeys-admin.json
  libs/locales/hi-IN/apps-watch.json
  libs/locales/hi-IN/libs-journeys-ui.json
  libs/locales/id-ID/apps-journeys-admin.json
  libs/locales/id-ID/apps-watch.json
  libs/locales/id-ID/libs-journeys-ui.json
  libs/locales/ja-JP/apps-journeys-admin.json
  libs/locales/ja-JP/apps-watch.json
  libs/locales/ja-JP/libs-journeys-ui.json
  libs/locales/my-MM/apps-journeys-admin.json
  libs/locales/my-MM/apps-watch.json
  libs/locales/my-MM/libs-journeys-ui.json
  libs/locales/ru-RU/apps-journeys-admin.json
  libs/locales/ru-RU/apps-watch.json
  libs/locales/ru-RU/libs-journeys-ui.json
  libs/locales/th-TH/apps-journeys-admin.json
  libs/locales/th-TH/apps-watch.json
  libs/locales/th-TH/libs-journeys-ui.json
  libs/locales/tl-PH/apps-journeys-admin.json
  libs/locales/tl-PH/apps-watch.json
  libs/locales/tl-PH/libs-journeys-ui.json
  libs/locales/tr-TR/apps-journeys-admin.json
  libs/locales/tr-TR/apps-watch.json
  libs/locales/tr-TR/libs-journeys-ui.json
  libs/locales/ur-PK/apps-journeys-admin.json
  libs/locales/ur-PK/apps-watch.json
  libs/locales/ur-PK/libs-journeys-ui.json
  libs/locales/vi-VN/apps-journeys-admin.json
  libs/locales/vi-VN/apps-watch.json
  libs/locales/vi-VN/libs-journeys-ui.json
  libs/locales/zh-Hans-CN/apps-journeys-admin.json
  libs/locales/zh-Hans-CN/apps-watch.json
  libs/locales/zh-Hans-CN/libs-journeys-ui.json
  libs/locales/zh-Hant-TW/apps-journeys-admin.json
  libs/locales/zh-Hant-TW/apps-watch.json
  libs/locales/zh-Hant-TW/libs-journeys-ui.json
Labels: priority: soon, effort: 1, type: chore

#2948 feat: express settings subscribe to journey updates
  apps/journeys-admin/pages/templates/[journeyId]/quick.tsx
Labels: priority: now, type: feat, effort: 1

#2950 fix: static date
  apps/api-journeys/src/app/emails/stories/VisitorInteraction.stories.tsx
Labels: type: fix, priority: now, effort: 1

#2814 feat: plausible 🚀
  apps/journeys-admin/__generated__/GetJourneyAnalytics.ts
  apps/journeys-admin/next.config.js
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsOverlaySwitch/AnalyticsOverlaySwitch.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsOverlaySwitch/AnalyticsOverlaySwitch.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsOverlaySwitch/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/BaseEdge/BaseEdge.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/BaseEdge/BaseEdge.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/CustomEdge/CustomEdge.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteOnKeyPress/useDeleteOnKeyPress.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteOnKeyPress/useDeleteOnKeyPress.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.tsx
  apps/journeys/__generated__/GetJourneyAnalytics.ts
  apps/nexus-admin/__generated__/GetJourneyAnalytics.ts
  apps/watch/__generated__/GetJourneyAnalytics.ts
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/__generated__/GetJourneyAnalytics.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/index.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/index.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.spec.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/useJourneyAnalyticsQuery.mock.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/useJourneyAnalyticsQuery.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 8, priority: now, type: feat

#2868 test: add publisher, template and card related e2e tests
  apps/journeys-admin-e2e/playwright.config.ts
  apps/journeys-admin-e2e/src/e2e/discover/card-level-actions.spec.ts
  apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
  apps/journeys-admin-e2e/src/pages/card-level-actions.ts
  apps/journeys-admin-e2e/src/pages/publisher-and-templates-page.ts
  apps/journeys-admin-e2e/src/pages/template-page.ts
Labels: type: test, effort: 8, priority: now, effort: 13

#2931 feat: journey analytics card
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyAnalyticsCard/JourneyAnalyticsCard.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyAnalyticsCard/JourneyAnalyticsCard.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyAnalyticsCard/JourneyAnalyticsCard.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyAnalyticsCard/JourneyAnalyticsCardStat/JourneyAnalyticsCardStat.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyAnalyticsCard/JourneyAnalyticsCardStat/JourneyAnalyticsCardStat.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyAnalyticsCard/JourneyAnalyticsCardStat/JourneyAnalyticsCardStat.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyAnalyticsCard/JourneyAnalyticsCardStat/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyAnalyticsCard/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: soon, type: feat

#2885 feat: link node analytics
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsDataPoint/AnalyticsDataPoint.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsDataPoint/AnalyticsDataPoint.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsDataPoint/AnalyticsDataPoint.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsDataPoint/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNode.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNodeAnalytics/LinkNodeAnalytics.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNodeAnalytics/LinkNodeAnalytics.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNodeAnalytics/LinkNodeAnalytics.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNodeAnalytics/index.ts
  libs/journeys/ui/src/libs/plausibleHelpers/plausibleHelpers.spec.ts
  libs/journeys/ui/src/libs/plausibleHelpers/plausibleHelpers.ts
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/icons/Cursor4.tsx
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: priority: soon, type: feat, effort: 1

#2935 feat: plausible persistent storage
  .kube/config
  apps/api-analytics/infrastructure/deploy.sh
  apps/api-analytics/infrastructure/values-prod.yaml
  apps/api-analytics/infrastructure/values-stage.yaml
  infrastructure/kube/datadog/deploy.sh
  infrastructure/kube/storage/deploy-prod.sh
  infrastructure/kube/storage/deploy-stage.sh
  infrastructure/kube/storage/deploy.yaml
Labels: effort: 3, priority: soon, type: feat

#2940 fix: alb listeners
  apps/api-analytics/infrastructure/locals.tf
  apps/api-analytics/infrastructure/main.tf
  apps/api-analytics/infrastructure/outputs.tf
  apps/api-analytics/infrastructure/variables.tf
  apps/api-gateway/infrastructure/locals.tf
  apps/api-gateway/infrastructure/main.tf
  apps/api-gateway/infrastructure/variables.tf
  apps/api-journeys/infrastructure/locals.tf
  apps/api-journeys/infrastructure/main.tf
  apps/api-journeys/infrastructure/variables.tf
  apps/api-languages/infrastructure/locals.tf
  apps/api-languages/infrastructure/main.tf
  apps/api-languages/infrastructure/variables.tf
  apps/api-media/infrastructure/locals.tf
  apps/api-media/infrastructure/main.tf
  apps/api-media/infrastructure/variables.tf
  apps/api-nexus/infrastructure/locals.tf
  apps/api-nexus/infrastructure/main.tf
  apps/api-nexus/infrastructure/variables.tf
  apps/api-tags/infrastructure/locals.tf
  apps/api-tags/infrastructure/main.tf
  apps/api-tags/infrastructure/variables.tf
  apps/api-users/infrastructure/locals.tf
  apps/api-users/infrastructure/main.tf
  apps/api-users/infrastructure/variables.tf
  apps/api-videos/infrastructure/locals.tf
  apps/api-videos/infrastructure/main.tf
  apps/api-videos/infrastructure/variables.tf
  apps/journeys-admin/infrastructure/locals.tf
  apps/journeys-admin/infrastructure/main.tf
  apps/journeys-admin/infrastructure/variables.tf
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/main.tf
  infrastructure/modules/aws/alb-listener/main.tf
  infrastructure/modules/aws/alb-listener/outputs.tf
  infrastructure/modules/aws/alb-listener/variables.tf
  infrastructure/modules/aws/alb/main.tf
  infrastructure/modules/aws/alb/outputs.tf
  infrastructure/modules/aws/alb/variables.tf
  infrastructure/modules/aws/data.tf
  infrastructure/modules/aws/ec2-bastion/main.tf
  infrastructure/modules/aws/ec2-bastion/variables.tf
  infrastructure/modules/aws/ecs-task/main.tf
  infrastructure/modules/aws/ecs-task/variables.tf
  infrastructure/modules/aws/elasticache/main.tf
  infrastructure/modules/aws/locals.tf
  infrastructure/modules/aws/main.tf
  infrastructure/modules/aws/outputs.tf
Labels: type: fix, effort: 13, priority: soon

#2956 feat: add new video to watch page
  apps/watch/pages/watch/index.tsx
  apps/watch/pages/watch/videos.tsx
Labels: priority: soon, type: feat, effort: 1

#2958 fix: watch film link
  apps/watch/src/components/VideoContentPage/VideoHeading/VideoHeading.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHeading/VideoHeading.tsx
Labels: type: fix, priority: soon, effort: 1

#2952 fix: use template redirect
  libs/journeys/ui/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.spec.tsx
  libs/journeys/ui/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.tsx
Labels: effort: 2, type: fix, priority: now

#2955 feat: analytics background
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
Labels: priority: soon, type: feat, effort: 1

#2936 feat: step block analytics
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsDataPoint/AnalyticsDataPoint.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/TrendDown1.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: effort: 2, priority: soon, type: feat

#2954 feat: card stats
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CanvasFooter.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CanvasFooter.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CanvasFooter.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CardAnalytics/CanvasAnalytics.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CardAnalytics/CardAnalytics.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CardAnalytics/CardAnalytics.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CardAnalytics/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/index.ts
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.tsx
  libs/journeys/ui/src/libs/MessageChatIcon/MessageChatIcon.spec.tsx
  libs/journeys/ui/src/libs/MessageChatIcon/MessageChatIcon.tsx
  libs/journeys/ui/src/libs/MessageChatIcon/index.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: now, type: feat

#2944 feat: referrer nodes
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsOverlaySwitch/AnalyticsOverlaySwitch.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/BaseEdge/BaseEdge.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/ReferrerEdge/ReferrerEdge.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/ReferrerEdge/ReferrerEdge.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/ReferrerEdge/ReferrerEdge.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/ReferrerEdge/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/OtherReferrer/OtherReferrer.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/OtherReferrer/OtherReferrer.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/OtherReferrer/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerNode.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.spec.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformReferrers/index.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformReferrers/transformReferrers.spec.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformReferrers/transformReferrers.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/useJourneyAnalyticsQuery.ts
Labels: effort: 3, priority: soon, type: feat

#2963 fix: links and chats calc
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsOverlaySwitch/AnalyticsOverlaySwitch.spec.tsx
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.spec.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.ts
Labels: type: fix, priority: now, effort: 1

#2953 fix: watch share link bug
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.tsx
Labels: type: fix, priority: soon, effort: 1

#2967 fix: journeyflow deadspace
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
Labels: type: fix, priority: soon, effort: 1

#2966 fix: site creation
  apps/api-journeys/src/app/modules/journey/journey.module.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: type: fix, priority: now, effort: 1

#2909 feat: resource hub journeys pages
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
  apps/watch/next.config.js
  apps/watch/pages/journeys/[journeyId].tsx
  apps/watch/pages/journeys/index.tsx
  apps/watch/src/libs/apolloClient/cache.ts
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.spec.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGalleryCarousel/NavButton/NavButton.tsx
  libs/journeys/ui/src/components/TemplateGalleryCard/TemplateGalleryCard.spec.tsx
  libs/journeys/ui/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
  libs/journeys/ui/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.spec.tsx
  libs/journeys/ui/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.tsx
  libs/journeys/ui/src/components/TemplateView/TemplateView.tsx
  libs/journeys/ui/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.tsx
  libs/locales/en/apps-watch.json
Labels: effort: 5, priority: now, type: feat

#2972 fix: subtitles bq import
  apps/api-videos/db/migrations/20240629013411_20240629013409/migration.sql
  apps/api-videos/db/schema.prisma
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.spec.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.ts
  apps/api-videos/src/app/modules/importer/importer.module.ts
  apps/api-videos/src/app/modules/importer/importerVideoSubtitle/importerVideoSubtitle.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerVideoSubtitle/importerVideoSubtitle.service.ts
  apps/api-videos/src/app/modules/importer/importerVideoVariantSubtitle/importerVideoVariantSubtitle.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerVideoVariantSubtitle/importerVideovariantSubtitle.service.ts
  apps/api-videos/src/app/modules/importer/importerVideoVariants/importerVideoVariants.service.ts
  infrastructure/kube/dashboard/deploy.sh
  package-lock.json
  package.json
Labels: priority: 2day, effort: 5, type: feat
