Repository JesusFilm/core, pull requests merged in 2024-08, with the labels that each got.

#3172 fix: update arrow icons for undo redo
  apps/journeys-admin/src/components/Editor/Toolbar/Items/CommandRedoItem/CommandRedoItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/CommandUndoItem/CommandUndoItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/Items.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
  libs/shared/ui/src/components/icons/FlipLeft.tsx
  libs/shared/ui/src/components/icons/FlipRight.tsx
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: type: fix, priority: now, effort: 1

#3171 fix: include action in children block restore
  apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.resolver.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#3174 feat: dangerfile dependabot
  dangerfile.ts
Labels: priority: soon, type: feat, effort: 1

#3175 feat: remove outdated nvmrc
  .nvmrc
Labels: priority: soon, type: feat, effort: 1

#3177 revert: fix(deps): update dependency express to v4.19.2 [security]
  package-lock.json
  package.json
Labels: priority: now, effort: 1, type: revert, on stage

#3133 fix: closing addblock drawer action
  apps/journeys-admin/src/components/Editor/Fab/Fab.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: priority: 2day, type: fix, effort: 1

#3179 fix: step block node second line clipped
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.tsx
Labels: priority: 2day, type: fix, effort: 1, chromatic

#3181 feat: renovate validate branch name
  validate-branch-name.config.js
Labels: priority: soon, type: feat, effort: 1

#3113 feat: undo redo step creation
  apps/journeys-admin/__generated__/StepBlockCreateFromAction.ts
  apps/journeys-admin/__generated__/StepBlockCreateFromSocialPreview.ts
  apps/journeys-admin/__generated__/StepBlockCreateFromStep.ts
  apps/journeys-admin/__generated__/StepBlockDeleteFromAction.ts
  apps/journeys-admin/__generated__/StepBlockDeleteFromActionWithoutAction.ts
  apps/journeys-admin/__generated__/StepBlockDeleteFromSocialPreview.ts
  apps/journeys-admin/__generated__/StepBlockDeleteFromStep.ts
  apps/journeys-admin/__generated__/StepBlockRestoreFromAction.ts
  apps/journeys-admin/__generated__/StepBlockRestoreFromSocialPreview.ts
  apps/journeys-admin/__generated__/StepBlockRestoreFromStep.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/NewStepButton/NewStepButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/TestUseCreateStepHooks/TestUseCreateStepHooks.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/TestUseCreateStepHooks/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.mock.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromAction/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromAction/useCreateStepFromAction.mock.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromAction/useCreateStepFromAction.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromAction/useCreateStepFromAction.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromSocialPreview/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromSocialPreview/useCreateStepFromSocialPreview.mock.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromSocialPreview/useCreateStepFromSocialPreview.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromSocialPreview/useCreateStepFromSocialPreview.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromStep/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromStep/useCreateStepFromStep.mock.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromStep/useCreateStepFromStep.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromStep/useCreateStepFromStep.ts
  apps/journeys-admin/src/components/Editor/utils/useBlockDeleteCommand/useBlockDeleteCommand.tsx
  apps/journeys-admin/src/libs/useBlockDeleteMutation/useBlockDeleteMutation.ts
  apps/journeys-admin/src/libs/useStepAndCardBlockCreateMutation/index.ts
  apps/journeys-admin/src/libs/useStepAndCardBlockCreateMutation/useStepAndCardBlockCreateMutation.ts
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: effort: 8, type: fix, priority: soon

#3183 fix: hide onboarding form
  apps/journeys-admin/pages/onboarding-form.tsx
  apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.spec.tsx
  apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.ts
Labels: type: fix, priority: now, effort: 1

#3173 feat: add optimistic responses to block deletes
  apps/journeys-admin-e2e/src/pages/register-Page.ts
  apps/journeys-admin/__generated__/BlockDelete.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DeleteBlock/DeleteBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DeleteBlock/DeleteBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/NewStepButton/NewStepButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/TestUseCreateStepHooks/TestUseCreateStepHooks.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.mock.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromAction/useCreateStepFromAction.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromSocialPreview/useCreateStepFromSocialPreview.mock.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromSocialPreview/useCreateStepFromSocialPreview.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStepFromStep/useCreateStepFromStep.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteEdge/useDeleteEdge.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteOnKeyPress/useDeleteOnKeyPress.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useUpdateEdge/useUpdateEdge.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardLayout/CardLayout.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardStyling/CardStyling.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Options/ImageOptions.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/SelectedCard/SelectedCard.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Align/Align.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Color/Color.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Variant/Variant.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/EmailAction/EmailAction.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/LinkAction/LinkAction.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/CommandRedoItem/ComandRedoItem.spec.tsx
  apps/journeys-admin/src/components/Editor/utils/useActionCommand/useActionCommand.spec.tsx
  apps/journeys-admin/src/components/Editor/utils/useActionCommand/useActionCommand.ts
  apps/journeys-admin/src/components/Editor/utils/useBlockDeleteCommand/setBlockRestoreEditorState/setBlockRestoreEditorState.spec.ts
  apps/journeys-admin/src/components/Editor/utils/useBlockDeleteCommand/setBlockRestoreEditorState/setBlockRestoreEditorState.ts
  apps/journeys-admin/src/components/Editor/utils/useBlockDeleteCommand/useBlockDeleteCommand.spec.tsx
  apps/journeys-admin/src/components/Editor/utils/useBlockDeleteCommand/useBlockDeleteCommand.tsx
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.ts
  apps/journeys-admin/src/libs/useBlockDeleteMutation/useBlockDeleteMutation.mock.ts
  apps/journeys-admin/src/libs/useBlockDeleteMutation/useBlockDeleteMutation.spec.tsx
  apps/journeys-admin/src/libs/useBlockDeleteMutation/useBlockDeleteMutation.ts
  libs/journeys/ui/src/libs/CommandProvider/CommandProvider.spec.tsx
  libs/journeys/ui/src/libs/CommandProvider/CommandProvider.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: type: fix, effort: 3, priority: soon

#3089 feat: add undo and redo for typography and subscribe commands
  apps/journeys-admin-e2e/src/pages/card-level-actions.ts
  apps/journeys-admin/__generated__/IconBlockColorUpdate.ts
  apps/journeys-admin/__generated__/IconBlockNameUpdate.ts
  apps/journeys-admin/__generated__/SignUpBlockUpdateContent.ts
  apps/journeys-admin/__generated__/SignUpBlockUpdateSubmitLabel.ts
  apps/journeys-admin/__generated__/TypographyBlockUpdateColor.ts
  apps/journeys-admin/__generated__/TypographyBlockUpdateContent.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/SignUpEdit/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewTypographyButton/NewTypographyButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Color/Color.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Color/Color.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Icon/Color/Color.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Icon/Color/Color.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Icon/Icon.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Icon/Icon.tsx
  apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
  libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/Typography/Typography.spec.tsx
  libs/journeys/ui/src/components/Typography/Typography.tsx
  libs/journeys/ui/src/libs/CommandProvider/CommandProvider.spec.tsx
  libs/journeys/ui/src/libs/CommandProvider/CommandProvider.tsx
  libs/locales/en/apps-journeys-admin.json
  package-lock.json
  package.json
Labels: effort: 5, priority: soon, type: feat

#3186 fix: shorten social node edge
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.ts
Labels: priority: 2day, type: fix, effort: 1

#3097 feat: create block command undo
  apps/journeys-admin/__generated__/ButtonBlockCreate.ts
  apps/journeys-admin/__generated__/SignUpBlockCreate.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewButtonButton/NewButtonButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewButtonButton/NewButtonButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewFormButton/NewFormButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewFormButton/NewFormButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewImageButton/NewImageButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewImageButton/NewImageButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewRadioQuestionButton/NewRadioQuestionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewRadioQuestionButton/NewRadioQuestionButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewSignUpButton/NewSignUpButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewSignUpButton/NewSignUpButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewTextResponseButton/NewTextResponseButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewTextResponseButton/NewTextResponseButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewTypographyButton/NewTypographyButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewTypographyButton/NewTypographyButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewVideoButton/NewVideoButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewVideoButton/NewVideoButton.tsx
  apps/journeys-admin/src/components/Editor/utils/blockCreateUpdate/blockCreateUpdate.spec.tsx
  apps/journeys-admin/src/components/Editor/utils/blockCreateUpdate/blockCreateUpdate.tsx
  apps/journeys-admin/src/components/Editor/utils/blockCreateUpdate/index.ts
  apps/journeys-admin/src/components/Editor/utils/useBlockCreateCommand/index.ts
  apps/journeys-admin/src/components/Editor/utils/useBlockCreateCommand/useBlockCreateCommand.spec.tsx
  apps/journeys-admin/src/components/Editor/utils/useBlockCreateCommand/useBlockCreateCommand.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: effort: 5, type: fix, priority: soon

#3185 feat: add undo redo for button commands
  apps/journeys-admin/__generated__/ButtonBlockUpdateColor.ts
  apps/journeys-admin/__generated__/ButtonBlockUpdateContent.ts
  apps/journeys-admin/__generated__/ButtonBlockUpdateSize.ts
  apps/journeys-admin/__generated__/ButtonBlockUpdateVariant.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Button/Color/Color.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Button/Color/Color.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Button/Size/Size.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Button/Size/Size.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Button/Variant/Variant.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Button/Variant/Variant.tsx
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/locales/en/libs-journeys-ui.json
Labels: effort: 3, priority: now, type: feat

#3192 test: click on 'Dismiss' dialogue box that comes up for first time user
  apps/journeys-admin-e2e/src/pages/teams-page.ts
Labels: type: test, priority: now, effort: 1

#3153 feat: resource hub strategies page
  apps/watch/next.config.js
  apps/watch/pages/strategies/index.tsx
  apps/watch/src/components/Header/HeaderTabButtons/HeaderTabButtons.spec.tsx
  apps/watch/src/components/Header/HeaderTabButtons/HeaderTabButtons.tsx
  apps/watch/src/components/StrategiesView/StrategiesView.spec.tsx
  apps/watch/src/components/StrategiesView/StrategiesView.stories.tsx
  apps/watch/src/components/StrategiesView/StrategiesView.tsx
  apps/watch/src/components/StrategiesView/index.ts
  apps/watch/src/components/StrategySections/StrategyCard/StrategyCard.spec.tsx
  apps/watch/src/components/StrategySections/StrategyCard/StrategyCard.stories.tsx
  apps/watch/src/components/StrategySections/StrategyCard/StrategyCard.tsx
  apps/watch/src/components/StrategySections/StrategyCard/index.ts
  apps/watch/src/components/StrategySections/StrategySection/StrategySection.handlers.ts
  apps/watch/src/components/StrategySections/StrategySection/StrategySection.spec.tsx
  apps/watch/src/components/StrategySections/StrategySection/StrategySection.stories.tsx
  apps/watch/src/components/StrategySections/StrategySection/StrategySection.tsx
  apps/watch/src/components/StrategySections/StrategySection/data.ts
  apps/watch/src/components/StrategySections/StrategySection/index.ts
  apps/watch/src/components/StrategySections/StrategySections.spec.tsx
  apps/watch/src/components/StrategySections/StrategySections.tsx
  apps/watch/src/components/StrategySections/index.ts
  libs/journeys/ui/src/components/ContentCarousel/ContentCarousel.spec.tsx
  libs/journeys/ui/src/components/ContentCarousel/ContentCarousel.stories.tsx
  libs/journeys/ui/src/components/ContentCarousel/ContentCarousel.tsx
  libs/journeys/ui/src/components/ContentCarousel/NavButton/NavButton.tsx
  libs/journeys/ui/src/components/ContentCarousel/NavButton/index.ts
  libs/journeys/ui/src/components/ContentCarousel/index.ts
  libs/journeys/ui/src/components/EmptySearch/EmptySearch.spec.tsx
  libs/journeys/ui/src/components/EmptySearch/EmptySearch.stories.tsx
  libs/journeys/ui/src/components/EmptySearch/EmptySearch.tsx
  libs/journeys/ui/src/components/EmptySearch/index.ts
  libs/journeys/ui/src/components/ResourceHeading/ResourceHeading.spec.tsx
  libs/journeys/ui/src/components/ResourceHeading/ResourceHeading.stories.tsx
  libs/journeys/ui/src/components/ResourceHeading/ResourceHeading.tsx
  libs/journeys/ui/src/components/ResourceHeading/index.ts
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.stories.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
  libs/journeys/ui/src/components/SearchBar/index.ts
  libs/journeys/ui/src/components/TemplateGallery/TagCarousels/TagCarousels.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGalleryCarousel/index.ts
  libs/journeys/ui/src/components/TemplateGalleryCard/TemplateGalleryCard.spec.tsx
  libs/journeys/ui/src/components/TemplateSections/TemplateSections.tsx
  libs/journeys/ui/src/components/TemplateView/TemplateView.tsx
  libs/journeys/ui/src/libs/algolia/InstantSearchTestWrapper.tsx
  libs/locales/en/apps-watch.json
  libs/locales/en/libs-journeys-ui.json
  libs/shared/ui/src/libs/storybook/config.tsx
  libs/shared/ui/src/libs/storybook/index.ts
  package-lock.json
  package.json
Labels: effort: 8, priority: soon, type: feat

#3195 feat: move block undo and redo
  apps/journeys-admin/__generated__/BlockOrderUpdate.ts
  apps/journeys-admin/__generated__/StepBlockDefaultNextBlockUpdate.ts
  apps/journeys-admin/__generated__/StepBlockLockUpdate.ts
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
  apps/journeys-admin/src/components/CardPreview/CardList/index.ts
  apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
  apps/journeys-admin/src/components/CardPreview/NavigationCard/NavigationCard.spec.tsx
  apps/journeys-admin/src/components/CardPreview/NavigationCard/NavigationCard.stories.tsx
  apps/journeys-admin/src/components/CardPreview/NavigationCard/NavigationCard.tsx
  apps/journeys-admin/src/components/CardPreview/NavigationCard/index.ts
  apps/journeys-admin/src/components/CardPreview/OnSelectProps.ts
  apps/journeys-admin/src/components/CardPreview/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/MoveBlock/MoveBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/MoveBlock/MoveBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useUpdateEdge/useUpdateEdge.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/Cards/Cards.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/Cards/Cards.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/Cards/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/Conditions/Conditions.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/Conditions/Conditions.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/Conditions/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/NextCard.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/NextCard.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/NextCard.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/SelectedCard/SelectedCard.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/SelectedCard/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/NextCard/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/Step.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/Step.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/Step.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/index.ts
  apps/journeys-admin/src/libs/useBlockOrderUpdateMutation/index.ts
  apps/journeys-admin/src/libs/useBlockOrderUpdateMutation/useBlockOrderUpdateMutation.mock.ts
  apps/journeys-admin/src/libs/useBlockOrderUpdateMutation/useBlockOrderUpdateMutation.spec.tsx
  apps/journeys-admin/src/libs/useBlockOrderUpdateMutation/useBlockOrderUpdateMutation.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, type: feat, effort: 1

#3188 fix: allow custom id to be passed in on block duplicate resolver
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/block.graphql
  apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.resolver.ts
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#2795 feat: videos bq importer
  apps/api-videos/db/Dockerfile
  apps/api-videos/db/seed.ts
  apps/api-videos/infrastructure/main.tf
  apps/api-videos/project.json
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.spec.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.service.ts
  apps/api-videos/src/app/modules/importer/importer.module.ts
  apps/api-videos/src/app/modules/importer/importerBibleBooks/importerBibleBooks.service.ts
  apps/api-videos/src/app/modules/importer/importerBibleCitations/importerBibleCitations.service.ts
  apps/api-videos/src/app/modules/importer/importerVideoDescriptions/importerVideoDescriptions.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerVideoDescriptions/importerVideoDescriptions.service.ts
  apps/api-videos/src/app/modules/importer/importerVideoImageAlt/importerVideoImageAlt.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerVideoImageAlt/importerVideoImageAlt.service.ts
  apps/api-videos/src/app/modules/importer/importerVideoSnippets/importerVideoSnippets.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerVideoSnippets/importerVideoSnippets.service.ts
  apps/api-videos/src/app/modules/importer/importerVideoStudyQuestions/importerVideoStudyQuestions.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerVideoStudyQuestions/importerVideoStudyQuestions.service.ts
  apps/api-videos/src/app/modules/importer/importerVideoTitles/importerVideoTitle.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerVideoTitles/importerVideoTitle.service.ts
  apps/api-videos/src/app/modules/importer/importerVideoVariantDownloads/importerVideoVariantDownloads.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerVideoVariantDownloads/importerVideoVariantDownloads.service.ts
  apps/api-videos/src/app/modules/importer/importerVideoVariants/importerVideoVariants.service.ts
  apps/api-videos/src/app/modules/importer/importerVideos/importerVideos.service.ts
  apps/api-videos/src/app/modules/importer/importerVideosChildren/importerVideosChildren.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerVideosChildren/importerVideosChildren.service.ts
  apps/api-videos/src/libs/arclight/__mocks__/arclight.ts
  apps/api-videos/src/libs/arclight/arclight.spec.ts
  apps/api-videos/src/libs/arclight/arclight.ts
  apps/api-videos/src/libs/arclight/index.ts
  apps/api-videos/src/libs/postgresql/__mocks__/postgresql.ts
  apps/api-videos/src/libs/postgresql/index.ts
  apps/api-videos/src/libs/postgresql/postgresql.ts
  infrastructure/kube/dashboard/deploy.sh
Labels: priority: 2day, effort: 13, type: feat, on stage

#3197 fix: radio option debounce
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.tsx
Labels: type: fix, priority: now, effort: 1

#3203 feat: add step block position update mutation
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/step/step.graphql
  apps/api-journeys/src/app/modules/block/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/step/step.resolver.ts
Labels: priority: now, type: feat, effort: 1, on stage

#3204 feat: undo and redo of radio option block
  apps/journeys-admin/__generated__/RadioOptionBlockCreate.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
Labels: type: fix, priority: soon, effort: 1

#3200 feat: duplicate block commands
  apps/journeys-admin/__generated__/BlockDuplicate.ts
  apps/journeys-admin/__generated__/StepDuplicate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DuplicateBlock/DuplicateBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DuplicateBlock/DuplicateBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/DuplicateStep/DuplicateStep.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/DuplicateStep/DuplicateStep.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/sizes.ts
  apps/journeys-admin/src/components/Editor/utils/useBlockDuplicateCommand/index.ts
  apps/journeys-admin/src/components/Editor/utils/useBlockDuplicateCommand/useBlockDuplicateCommand.spec.tsx
  apps/journeys-admin/src/components/Editor/utils/useBlockDuplicateCommand/useBlockDuplicateCommand.tsx
Labels: type: fix, effort: 3, priority: soon

#3205 feat: journey flow commands
  apps/journeys-admin/__generated__/BlockActionNavigateToBlockUpdate.ts
  apps/journeys-admin/__generated__/StepBlockNextBlockUpdate.ts
  apps/journeys-admin/__generated__/StepBlockPositionUpdate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteEdge/useDeleteEdge.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteEdge/useDeleteEdge.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useUpdateEdge/useUpdateEdge.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useUpdateEdge/useUpdateEdge.ts
  apps/journeys-admin/src/components/Editor/utils/useActionCommand/useActionCommand.spec.tsx
  apps/journeys-admin/src/components/Editor/utils/useActionCommand/useActionCommand.ts
  apps/journeys-admin/src/libs/useBlockActionNavigateToBlockUpdateMutation/useBlockActionNavigateToBlockUpdateMutation.mock.ts
  apps/journeys-admin/src/libs/useBlockActionNavigateToBlockUpdateMutation/useBlockActionNavigateToBlockUpdateMutation.ts
  apps/journeys-admin/src/libs/useStepBlockNextBlockUpdateMutation/useStepBlockNextBlockUpdateMutation.mock.ts
  apps/journeys-admin/src/libs/useStepBlockNextBlockUpdateMutation/useStepBlockNextBlockUpdateMutation.ts
  apps/journeys-admin/src/libs/useStepBlockPositionUpdateMutation/useStepBlockPositionUpdateMutation.ts
Labels: effort: 2, priority: now, type: feat

#3206 fix: video trigger when on first step
  libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
Labels: type: fix, priority: now, effort: 1, on stage

#3167 refactor: helpscout beacon
  apps/arclight/__generated__/graphql-env.d.ts
  apps/journeys-admin-e2e/src/pages/journey-level-actions-page.ts
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/pages/email-preferences/[email].tsx
  apps/journeys-admin/pages/index.tsx
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/pages/onboarding-form.tsx
  apps/journeys-admin/pages/publisher/index.tsx
  apps/journeys-admin/pages/reports/journeys.tsx
  apps/journeys-admin/pages/reports/visitors.tsx
  apps/journeys-admin/pages/reports/visitors/[visitorId].tsx
  apps/journeys-admin/pages/teams/[teamId]/integrations/[integrationId].tsx
  apps/journeys-admin/pages/teams/[teamId]/integrations/index.tsx
  apps/journeys-admin/pages/teams/[teamId]/integrations/new/growth-spaces.tsx
  apps/journeys-admin/pages/teams/[teamId]/integrations/new/index.tsx
  apps/journeys-admin/pages/teams/new.tsx
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/pages/users/sign-in.tsx
  apps/journeys-admin/pages/users/terms-and-conditions.tsx
  apps/journeys-admin/pages/users/verify.tsx
  apps/journeys-admin/src/components/Editor/Editor.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/Items.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Menu/Menu.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/BeaconInit/BeaconInit.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/BeaconInit/beaconProperties.ts
  apps/journeys-admin/src/components/HelpScoutBeacon/BeaconInit/index.ts
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.spec.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.stories.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/ClearAllButton/ClearAllButton.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingPageWrapper.tsx
  apps/journeys-admin/src/components/PageWrapper/AppHeader/AppHeader.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
  apps/journeys-admin/src/components/ReportsNavigation/ReportsNavigation.tsx
Labels: effort: 5, priority: soon, type: refactor

#3163 chore: add service name
  apps/api-gateway/router.prod.yaml
  apps/api-gateway/router.yaml
Labels: priority: now, effort: 1, type: chore, on stage

#3210 fix: handle null parentorder on block restore
  apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.resolver.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#3215 fix: limit related templates
  libs/journeys/ui/src/components/TemplateView/TemplateView.spec.tsx
  libs/journeys/ui/src/components/TemplateView/TemplateView.tsx
Labels: type: fix, priority: now, effort: 1

#3207 fix: escape tsquery special characters
  apps/api-videos/src/app/modules/video/video.service.spec.ts
  apps/api-videos/src/app/modules/video/video.service.ts
Labels: effort: 2, type: fix, priority: soon

#3213 feat: remove aws seeds
  .github/workflows/api-deploy-worker.yml
  apps/api-journeys/db/Dockerfile
  apps/api-journeys/infrastructure/main.tf
  apps/api-nexus/infrastructure/main.tf
  apps/api-tags/db/Dockerfile
  apps/api-tags/infrastructure/main.tf
Labels: priority: 2day, type: feat, effort: 1

#3212 feat: keyword endpoints
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/app/__generated__/graphql.ts
  apps/api-videos/src/app/app.module.ts
  apps/api-videos/src/app/modules/keyword/keyword.graphql
  apps/api-videos/src/app/modules/keyword/keyword.module.ts
  apps/api-videos/src/app/modules/keyword/keyword.resolver.spec.ts
  apps/api-videos/src/app/modules/keyword/keyword.resolver.ts
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
  apps/api-videos/src/app/modules/video/video.resolver.ts
Labels: effort: 3, priority: soon, type: feat

#3219 feat: change datadog aurora
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/main.tf
Labels: priority: soon, type: feat, effort: 1

#3223 fix: rely on use effect to populate positions
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
Labels: type: fix, priority: now, effort: 1

#3196 feat: analytics beacon
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Accordion/Accordion.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/ImageBlockEditor.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageSource/ImageSource.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Source/Source.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/AccessItem/AccessItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/DescriptionItem/DescriptionItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/LanguageItem/LanguageItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TemplateSettingsItem/TemplateSettingsItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/TitleItem/TitleItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/BeaconInit/BeaconInit.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/BeaconInit/constants.ts
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.spec.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem/DuplicateJourneyMenuItem.tsx
  apps/journeys-admin/src/components/NotificationPopover/NotificationPopover.spec.tsx
  apps/journeys-admin/src/components/NotificationPopover/NotificationPopover.stories.tsx
  apps/journeys-admin/src/components/NotificationPopover/NotificationPopover.tsx
  apps/journeys-admin/src/components/NotificationPopover/index.ts
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.tsx
  apps/journeys-admin/src/components/Team/TeamSelect/TeamSelect.tsx
  libs/journeys/ui/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
  libs/journeys/ui/src/libs/beaconHooks/beaconHooks.spec.ts
  libs/journeys/ui/src/libs/beaconHooks/beaconHooks.ts
  libs/journeys/ui/src/libs/beaconHooks/index.ts
  libs/journeys/ui/src/libs/setBeaconPageViewed/index.ts
  libs/journeys/ui/src/libs/setBeaconPageViewed/setBeaconPageViewed.spec.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: soon, type: feat

#3214 refactor: events numbers to visitors
  apps/journeys-admin/__generated__/GetJourneyAnalytics.ts
  apps/journeys/__generated__/GetJourneyAnalytics.ts
  apps/nexus-admin/__generated__/GetJourneyAnalytics.ts
  apps/watch/__generated__/GetJourneyAnalytics.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/__generated__/GetJourneyAnalytics.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.spec.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/useJourneyAnalyticsQuery.mock.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/useJourneyAnalyticsQuery.ts
Labels: priority: soon, effort: 1, type: refactor

#3216 feat: add threshold for step analytics duration
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#3164 feat: flag stats threshold
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.tsx
Labels: priority: now, type: feat, effort: 1

#3227 perf: make admin journey query run client side
  apps/journeys-admin/__generated__/GetSSRAdminJourney.ts
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/NewStepButton/NewStepButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/NewStepButton/NewStepButton.tsx
Labels: priority: now, effort: 1, type: perf

#3228 fix: filter invalid root block types
  .eslintrc.json
  .github/workflows/autofix.ci.yml
  .prettierignore
  apps/api-videos/src/app/modules/importer/importerVideos/importerVideos.service.ts
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CanvasFooter.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Options/ImageOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageSource/ImageSource.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.spec.tsx
  apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.spec.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.spec.tsx
  libs/journeys/ui/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.spec.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.spec.tsx
  libs/journeys/ui/src/libs/transformer/transformer.spec.ts
  libs/journeys/ui/src/libs/transformer/transformer.ts
Labels: type: fix, priority: now, effort: 1

#3242 fix: strategies structure and design update
  apps/watch/pages/journeys/index.tsx
  apps/watch/pages/strategies/index.tsx
  apps/watch/src/components/StrategiesView/StrategiesView.spec.tsx
  apps/watch/src/components/StrategiesView/StrategiesView.stories.tsx
  apps/watch/src/components/StrategiesView/StrategiesView.tsx
  apps/watch/src/components/StrategiesView/StrategySections/StrategyCard/StrategyCard.spec.tsx
  apps/watch/src/components/StrategiesView/StrategySections/StrategyCard/StrategyCard.stories.tsx
  apps/watch/src/components/StrategiesView/StrategySections/StrategyCard/StrategyCard.tsx
  apps/watch/src/components/StrategiesView/StrategySections/StrategyCard/index.ts
  apps/watch/src/components/StrategiesView/StrategySections/StrategySection/StrategySection.handlers.ts
  apps/watch/src/components/StrategiesView/StrategySections/StrategySection/StrategySection.spec.tsx
  apps/watch/src/components/StrategiesView/StrategySections/StrategySection/StrategySection.stories.tsx
  apps/watch/src/components/StrategiesView/StrategySections/StrategySection/StrategySection.tsx
  apps/watch/src/components/StrategiesView/StrategySections/StrategySection/data.ts
  apps/watch/src/components/StrategiesView/StrategySections/StrategySection/index.ts
  apps/watch/src/components/StrategiesView/StrategySections/StrategySections.spec.tsx
  apps/watch/src/components/StrategiesView/StrategySections/StrategySections.tsx
  apps/watch/src/components/StrategiesView/StrategySections/index.ts
  apps/watch/src/components/StrategySections/StrategySection/data.ts
  apps/watch/src/libs/algolia/useAlgoliaStrategies/index.ts
  apps/watch/src/libs/algolia/useAlgoliaStrategies/useAlgoliaStrategies.spec.ts
  apps/watch/src/libs/algolia/useAlgoliaStrategies/useAlgoliaStrategies.ts
  libs/journeys/ui/src/components/ContentCarousel/ContentCarousel.tsx
  libs/journeys/ui/src/components/TemplateGallery/TagCarousels/TagCarousels.spec.tsx
  libs/journeys/ui/src/components/TemplateGallery/TagCarousels/TagCarousels.tsx
  libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.tsx
Labels: type: fix, priority: now, effort: 1

#3241 fix: journey flow block positions
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
Labels: type: fix, priority: soon, effort: 1

#3230 fix: goals overflow to scroll
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsList.tsx
Labels: type: fix, priority: soon, effort: 1

#3229 feat: card templates cta optimistic cache updates
  apps/journeys-admin/__generated__/CardCtaDelete.ts
  apps/journeys-admin/__generated__/CardCtaRestore.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardCta/CardCta.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardCta/CardCta.tsx
Labels: type: fix, effort: 3, priority: soon

#3244 feat: card quote form optimistic cache updates
  apps/journeys-admin/__generated__/CardQuoteDelete.ts
  apps/journeys-admin/__generated__/CardQuoteRestore.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardQuote/CardQuote.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardQuote/CardQuote.tsx
Labels: effort: 3, priority: soon, type: feat

#3245 feat: card video template optimistic cache updates
  apps/journeys-admin/__generated__/CardVideoDelete.ts
  apps/journeys-admin/__generated__/CardVideoRestore.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/CardTemplates.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardVideo/CardVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardVideo/CardVideo.tsx
Labels: type: fix, effort: 3, priority: soon

#3243 feat: card template form optimistic cache updates
  apps/journeys-admin/__generated__/CardFormDelete.ts
  apps/journeys-admin/__generated__/CardFormRestore.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardForm/CardForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardForm/CardForm.tsx
Labels: priority: soon, type: feat, effort: 1, chromatic

#3240 feat: card template intro optimistic cache updates
  apps/journeys-admin/__generated__/CardIntroDelete.ts
  apps/journeys-admin/__generated__/CardIntroRestore.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardIntro/CardIntro.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardIntro/CardIntro.tsx
Labels: effort: 3, priority: soon, type: feat

#3248 fix: add api key for build time
  apps/watch/pages/strategies/index.tsx
Labels: type: fix, priority: now, effort: 1

#3249 fix: expanded card video
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
Labels: type: fix, priority: soon, effort: 1

#3251 fix: remove ld flag
  apps/journeys-admin/src/components/Editor/Editor.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Labels: type: fix, priority: soon, effort: 1, on stage

#3222 feat: card templates optimistic cache updates
  apps/journeys-admin/__generated__/CardCtaDelete.ts
  apps/journeys-admin/__generated__/CardCtaRestore.ts
  apps/journeys-admin/__generated__/CardFormDelete.ts
  apps/journeys-admin/__generated__/CardFormRestore.ts
  apps/journeys-admin/__generated__/CardIntroDelete.ts
  apps/journeys-admin/__generated__/CardIntroRestore.ts
  apps/journeys-admin/__generated__/CardPollDelete.ts
  apps/journeys-admin/__generated__/CardPollRestore.ts
  apps/journeys-admin/__generated__/CardQuoteDelete.ts
  apps/journeys-admin/__generated__/CardQuoteRestore.ts
  apps/journeys-admin/__generated__/CardVideoDelete.ts
  apps/journeys-admin/__generated__/CardVideoRestore.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/CardTemplates.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardCta/CardCta.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardCta/CardCta.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardForm/CardForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardForm/CardForm.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardIntro/CardIntro.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardIntro/CardIntro.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardPoll/CardPoll.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardPoll/CardPoll.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardQuote/CardQuote.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardQuote/CardQuote.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardVideo/CardVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardVideo/CardVideo.tsx
Labels: priority: soon, type: feat, effort: 1, chromatic

#3247 fix: editor mobile swipe
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
Labels: type: fix, priority: soon, effort: 1

#3254 feat: language slugs
  .prettierignore
  apps/api-analytics/src/__generated__/graphql.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/db/migrations/20240813204551_20240813204549/migration.sql
  apps/api-languages/db/schema.prisma
  apps/api-languages/schema.graphql
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-languages/src/__generated__/languageSlugs.ts
  apps/api-languages/src/bigquery/importers/languageSlugs/languageSlugs.spec.ts
  apps/api-languages/src/bigquery/importers/languageSlugs/languageSlugs.ts
  apps/api-languages/src/bigquery/worker.spec.ts
  apps/api-languages/src/bigquery/worker.ts
  apps/api-languages/src/lib/slugify/index.ts
  apps/api-languages/src/lib/slugify/slugify.spec.ts
  apps/api-languages/src/lib/slugify/slugify.ts
  apps/api-languages/src/schema/country/countries.spec.ts
  apps/api-languages/src/schema/country/country.spec.ts
  apps/api-languages/src/schema/language/language.mock.ts
  apps/api-languages/src/schema/language/language.spec.ts
  apps/api-languages/src/schema/language/language.ts
  apps/api-languages/src/schema/language/languages.spec.ts
  apps/api-videos/project.json
  apps/api-videos/src/exportExistingLanguageSlugs.ts
Labels: effort: 5, priority: soon, type: feat, on stage

#3258 feat: wrap searchbar in formik for sensible debouncing
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
Labels: priority: 2day, effort: 1, type: perf

#3257 refactor: redirect user to inegrations page after gs create
  apps/journeys-admin/__generated__/Integration.ts
  apps/journeys-admin/__generated__/IntegrationGrowthSpacesCreate.ts
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesCreateIntegration/GrowthSpacesCreateIntegration.spec.tsx
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesCreateIntegration/GrowthSpacesCreateIntegration.tsx
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesIntegrationDetails/GrowthSpacesIntegrationDetails.spec.tsx
  apps/journeys-admin/src/components/GrowthSpaces/GrowthSpacesIntegrationDetails/GrowthSpacesIntegrationDetails.tsx
Labels: priority: soon, effort: 1, type: refactor

#3253 ci: cache eslint
  .github/workflows/autofix.ci.yml
  .gitignore
  apps/api-analytics/project.json
  apps/api-analytics/tsconfig.json
  apps/api-journeys/project.json
  apps/api-journeys/tsconfig.json
  apps/api-languages/project.json
  apps/api-languages/tsconfig.json
  apps/api-media/project.json
  apps/api-media/tsconfig.json
  apps/api-tags/project.json
  apps/api-tags/tsconfig.json
  apps/api-users/project.json
  apps/api-users/tsconfig.json
  apps/api-videos/project.json
  apps/api-videos/tsconfig.json
  apps/arclight-e2e/project.json
  apps/arclight-e2e/tsconfig.json
  apps/arclight/project.json
  apps/arclight/tsconfig.json
  apps/docs-e2e/project.json
  apps/docs-e2e/tsconfig.json
  apps/docs/project.json
  apps/docs/tsconfig.json
  apps/journeys-admin-e2e/project.json
  apps/journeys-admin-e2e/tsconfig.json
  apps/journeys-admin/project.json
  apps/journeys-admin/tsconfig.json
  apps/journeys-e2e/project.json
  apps/journeys-e2e/tsconfig.json
  apps/journeys/project.json
  apps/journeys/tsconfig.json
  apps/nexus-admin-e2e/project.json
  apps/nexus-admin-e2e/tsconfig.json
  apps/nexus-admin/project.json
  apps/nexus-admin/tsconfig.json
  apps/watch-e2e/project.json
  apps/watch-e2e/tsconfig.json
  apps/watch/project.json
  apps/watch/tsconfig.json
  libs/journeys/ui/project.json
  libs/journeys/ui/tsconfig.json
  libs/nest/common/project.json
  libs/nest/common/tsconfig.json
  libs/nest/decorators/project.json
  libs/nest/decorators/tsconfig.json
  libs/nest/gqlAuthGuard/project.json
  libs/nest/gqlAuthGuard/tsconfig.json
  libs/nest/powerBi/project.json
  libs/nest/powerBi/tsconfig.json
  libs/shared/ui-dynamic/project.json
  libs/shared/ui-dynamic/tsconfig.json
  libs/shared/ui/project.json
  libs/shared/ui/tsconfig.json
Labels: effort: 3, priority: soon, type: ci

#3262 feat: video importer language slug
  apps/api-videos/infrastructure/locals.tf
  apps/api-videos/src/app/__generated__/graphql-env.d.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.spec.ts
  apps/api-videos/src/app/modules/bigQuery/bigQuery.consumer.ts
  apps/api-videos/src/app/modules/importer/importer.module.ts
  apps/api-videos/src/app/modules/importer/importerLanguageSlugs/importerLanguageSlugs.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerLanguageSlugs/importerLanguageSlugs.service.ts
  apps/api-videos/src/app/modules/importer/importerVideoVariantDownloads/importerVideoVariantDownloads.service.ts
  apps/api-videos/src/app/modules/importer/importerVideoVariants/importerVideoVariants.service.spec.ts
  apps/api-videos/src/app/modules/importer/importerVideoVariants/importerVideoVariants.service.ts
  apps/api-videos/tsconfig.json
  apps/docs/docs/02-getting-started/03-microservice-databases.mdx
Labels: priority: soon, type: feat, effort: 1, on stage

#3246 feat: algolia search in video library
  apps/journeys-admin/__generated__/GetVideos.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/data.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/VideoFromYouTube.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/VideoFromYouTube.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/VideoFromYouTube.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.handlers.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoSearch/VideoSearch.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoSearch/VideoSearch.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoSearch/VideoSearch.tsx
  libs/journeys/ui/src/libs/algolia/InstantSearchTestWrapper.tsx
Labels: effort: 2, priority: soon, type: feat

#3275 fix: remove console log
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.tsx
Labels: type: fix, priority: now, effort: 1

#3277 fix: revert video library changes
  apps/journeys-admin/__generated__/GetVideos.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/journeys/[journeyId].tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/data.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/VideoFromYouTube.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/VideoFromYouTube.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/VideoFromYouTube.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.handlers.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoSearch/VideoSearch.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoSearch/VideoSearch.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoSearch/VideoSearch.tsx
  libs/journeys/ui/src/libs/algolia/InstantSearchTestWrapper.tsx
Labels: priority: now, effort: 1, type: revert

#3161 feat: watch reload query params
  apps/watch-e2e/src/e2e/filters.spec.ts
  apps/watch/pages/_app.tsx
  apps/watch/pages/watch/[part1]/[part2].tsx
  apps/watch/pages/watch/[part1]/[part2]/[part3].tsx
  apps/watch/pages/watch/index.tsx
  apps/watch/pages/watch/videos.tsx
  apps/watch/src/components/Header/HeaderTabButtons/HeaderTabButtons.tsx
  apps/watch/src/components/StrategiesView/StrategiesView.stories.tsx
  apps/watch/src/components/StrategiesView/StrategySections/StrategyCard/StrategyCard.stories.tsx
  apps/watch/src/components/StrategiesView/StrategySections/StrategySection/StrategySection.stories.tsx
  apps/watch/src/components/VideoCard/VideoCard.spec.tsx
  apps/watch/src/components/VideoCard/VideoCard.stories.tsx
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideoCarousel/VideoCarousel.spec.tsx
  apps/watch/src/components/VideoCarousel/VideoCarousel.stories.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.spec.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.stories.tsx
  apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.spec.tsx
  apps/watch/src/components/VideoGrid/AlgoliaVideoGrid/AlgoliaVideoGrid.spec.tsx
  apps/watch/src/components/VideoGrid/AlgoliaVideoGrid/AlgoliaVideoGrid.tsx
  apps/watch/src/components/VideoGrid/VideoGrid.spec.tsx
  apps/watch/src/components/VideoGrid/VideoGrid.stories.tsx
  apps/watch/src/components/VideoGrid/VideoGrid.tsx
  apps/watch/src/components/VideosPage/FilterList/FilterList.spec.tsx
  apps/watch/src/components/VideosPage/FilterList/FilterList.stories.tsx
  apps/watch/src/components/VideosPage/FilterList/FilterList.tsx
  apps/watch/src/components/VideosPage/VideosPage.handlers.ts
  apps/watch/src/components/VideosPage/VideosPage.spec.tsx
  apps/watch/src/components/VideosPage/VideosPage.stories.tsx
  apps/watch/src/components/VideosPage/VideosPage.tsx
  apps/watch/src/components/VideosPage/data.ts
  apps/watch/src/components/VideosPage/utils/checkFilterApplied/checkFilterApplied.ts
  apps/watch/src/components/VideosPage/utils/checkFilterApplied/index.ts
  apps/watch/src/components/VideosPage/utils/transformAlgoliaVideos/index.ts
  apps/watch/src/components/VideosPage/utils/transformAlgoliaVideos/transformAlgoliaVideos.ts
  apps/watch/src/components/VideosPage/utils/useVideoSearch/index.ts
  apps/watch/src/components/VideosPage/utils/useVideoSearch/useVideoSearch.ts
  apps/watch/src/components/WatchHomePage/WatchHomePage.stories.tsx
  apps/watch/src/components/WatchHomePage/WatchHomePage.tsx
  apps/watch/src/libs/algolia/useAlgoliaRouter/index.ts
  apps/watch/src/libs/algolia/useAlgoliaRouter/useAlgoliaRouter.spec.ts
  apps/watch/src/libs/algolia/useAlgoliaRouter/useAlgoliaRouter.ts
  apps/watch/src/libs/algolia/useAlgoliaVideos/data.ts
  apps/watch/src/libs/algolia/useAlgoliaVideos/index.ts
  apps/watch/src/libs/algolia/useAlgoliaVideos/useAlgoliaVideos.spec.ts
  apps/watch/src/libs/algolia/useAlgoliaVideos/useAlgoliaVideos.ts
  libs/journeys/ui/src/components/SearchBar/SearchBar.stories.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
  libs/journeys/ui/src/libs/algolia/InstantSearchTestWrapper.tsx
Labels: effort: 8, priority: now, type: feat

#3281 refactor: hide popover
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Labels: type: fix, priority: now, effort: 1

#3280 feat: use languages continents query
  apps/journeys-admin/__generated__/GetLanguagesContinents.ts
  apps/journeys/__generated__/GetLanguagesContinents.ts
  apps/nexus-admin/__generated__/GetLanguagesContinents.ts
  apps/watch/__generated__/GetLanguagesContinents.ts
  libs/journeys/ui/src/libs/useLanguagesContinentsQuery/__generated__/GetLanguagesContinents.ts
  libs/journeys/ui/src/libs/useLanguagesContinentsQuery/index.ts
  libs/journeys/ui/src/libs/useLanguagesContinentsQuery/useLanguagesContinentsQuery.mock.ts
  libs/journeys/ui/src/libs/useLanguagesContinentsQuery/useLanguagesContinentsQuery.spec.tsx
  libs/journeys/ui/src/libs/useLanguagesContinentsQuery/useLanguagesContinentsQuery.ts
Labels: priority: now, type: feat, effort: 1

#3284 feat: add language button on searchbar
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.stories.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
Labels: priority: 2day, type: feat, effort: 1

#3278 fix: add edition to the transform
  apps/api-videos/src/app/modules/importer/importerVideoVariants/importerVideoVariants.service.ts
Labels: type: fix, priority: soon, effort: 1

#3288 fix: api-videos test
  apps/api-videos/src/app/modules/importer/importerVideoVariants/importerVideoVariants.service.spec.ts
Labels: type: fix, priority: now, effort: 1

#3283 feat: use sort language continents
  apps/watch/src/libs/algolia/useSortLanguageContinents/index.ts
  apps/watch/src/libs/algolia/useSortLanguageContinents/useSortLanguageContinents.spec.tsx
  apps/watch/src/libs/algolia/useSortLanguageContinents/useSortLanguageContinents.tsx
  libs/journeys/ui/src/libs/useLanguagesContinentsQuery/data.ts
  libs/journeys/ui/src/libs/useLanguagesContinentsQuery/useLanguagesContinentsQuery.mock.ts
  libs/journeys/ui/src/libs/useLanguagesContinentsQuery/useLanguagesContinentsQuery.ts
Labels: priority: soon, type: feat, effort: 1

#3290 feat: autocomplete dropdown
  apps/watch/src/components/VideosPage/FilterList/FilterList.spec.tsx
  apps/watch/src/components/WatchHomePage/WatchHomePage.tsx
  libs/journeys/ui/src/components/RefinementGroup/RefinementGroup.spec.tsx
  libs/journeys/ui/src/components/RefinementGroup/RefinementGroup.tsx
  libs/journeys/ui/src/components/RefinementGroup/index.ts
  libs/journeys/ui/src/components/SearchBar/SearchBar.handlers.ts
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.stories.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
  libs/journeys/ui/src/components/SearchBar/data.ts
Labels: priority: 2day, effort: 2, type: feat

#3299 fix: add manual ranking field to algolia object
  apps/api-videos/src/app/modules/algolia/algolia.service.spec.ts
  apps/api-videos/src/app/modules/algolia/algolia.service.ts
Labels: type: fix, priority: now, effort: 1, on stage

#3287 refactor: plausible threshold 10
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.tsx
Labels: priority: now, effort: 1, type: refactor

#3302 test: skip the test for now
  apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
Labels: type: test, priority: now, effort: 1

#3293 feat: add fields for step footer changes
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20240822213027_20240822213025/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/lib/fetchEmailDetails/fetchEmailDetails.spec.ts
  apps/api-journeys/src/app/lib/processUserIds/processUserIds.spec.ts
  apps/api-journeys/src/app/modules/email/emailEvents/emailEvents.consumer.spec.ts
  apps/api-journeys/src/app/modules/host/host.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.graphql
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/plausible/plausible.resolver.spec.ts
  apps/journeys-admin/__generated__/CreateCustomDomain.ts
  apps/journeys-admin/__generated__/CreateJourney.ts
  apps/journeys-admin/__generated__/CreateJourneyCollection.ts
  apps/journeys-admin/__generated__/GetAdminJourney.ts
  apps/journeys-admin/__generated__/GetAdminJourneyWithPlausibleToken.ts
  apps/journeys-admin/__generated__/GetAdminJourneys.ts
  apps/journeys-admin/__generated__/GetCustomDomains.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetJourneys.ts
  apps/journeys-admin/__generated__/GetOnboardingJourneys.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/JourneySeoTitleUpdate.ts
  apps/journeys-admin/__generated__/JourneySettingsUpdate.ts
  apps/journeys-admin/__generated__/JourneyTitleUpdate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/GetJourneys.ts
  apps/journeys/__generated__/GetJourneysSummary.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/watch/__generated__/GetJourney.ts
  apps/watch/__generated__/GetJourneys.ts
  apps/watch/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/useJourneyQuery/__generated__/GetJourney.ts
  libs/journeys/ui/src/libs/useJourneysQuery/__generated__/GetJourneys.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#3285 feat: add a new variant to custom accordion
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Accordion/Accordion.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Accordion/Accordion.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Accordion/Accordion.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioOption/RadioOption.tsx
Labels: priority: soon, type: feat, effort: 1

#3303 refactor: step header
  libs/journeys/ui/src/components/StepHeader/InformationButton/InformationButton.spec.tsx
  libs/journeys/ui/src/components/StepHeader/InformationButton/InformationButton.stories.tsx
  libs/journeys/ui/src/components/StepHeader/InformationButton/InformationButton.tsx
  libs/journeys/ui/src/components/StepHeader/InformationButton/index.ts
  libs/journeys/ui/src/components/StepHeader/StepHeader.spec.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.stories.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
Labels: effort: 2, priority: soon, type: refactor

#3311 fix: missing primary language id
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/schema/video/video.ts
Labels: type: fix, priority: now, effort: 1, on stage

#3312 fix: video match right language
  apps/api-videos/src/schema/video/video.ts
Labels: type: fix, priority: now, effort: 1, on stage

#3304 chore: add new journey footer properties
  apps/journeys-admin/__generated__/GetAdminJourney.ts
  apps/journeys-admin/__generated__/GetAdminJourneyWithPlausibleToken.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/src/components/Editor/Editor.spec.tsx
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/Goals.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardLayout/CardLayout.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardLayout/CardLayout.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardStyling/CardStyling.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/CardStyling/CardStyling.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/SocialDetails.stories.tsx
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/src/components/Conductor/Conductor.spec.tsx
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.stories.tsx
  apps/watch/__generated__/GetJourney.ts
  apps/watch/__generated__/JourneyFields.ts
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.spec.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.spec.tsx
  libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.stories.tsx
  libs/journeys/ui/src/components/StepFooter/HostTitleLocation/HostTitleLocation.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.spec.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.stories.tsx
  libs/journeys/ui/src/components/StepHeader/InformationButton/InformationButton.spec.tsx
  libs/journeys/ui/src/components/StepHeader/InformationButton/InformationButton.stories.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.stories.tsx
  libs/journeys/ui/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.spec.tsx
  libs/journeys/ui/src/components/TemplateView/TemplateFooter/data.ts
  libs/journeys/ui/src/components/TemplateView/data.ts
  libs/journeys/ui/src/libs/JourneyProvider/JourneyProvider.spec.tsx
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/journeyFields.tsx
  libs/journeys/ui/src/libs/rtl/rtl.spec.tsx
  libs/journeys/ui/src/libs/useJourneyQuery/__generated__/GetJourney.ts
  libs/journeys/ui/src/libs/useJourneyQuery/useJourneyQuery.spec.tsx
Labels: priority: soon, effort: 1, type: chore

#3298 fix: card delete resetting flow
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/DuplicateStep/DuplicateStep.tsx
  apps/journeys-admin/src/components/Editor/utils/useBlockDeleteCommand/setBlockRestoreEditorState/setBlockRestoreEditorState.spec.ts
  apps/journeys-admin/src/libs/useBlockRestoreMutation/useBlockRestoreMutation.mock.ts
  apps/journeys-admin/src/libs/useBlockRestoreMutation/useBlockRestoreMutation.spec.tsx
  apps/journeys-admin/src/libs/useBlockRestoreMutation/useBlockRestoreMutation.tsx
Labels: type: fix, priority: now, effort: 1

#3310 feat: editable step header
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.spec.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.spec.tsx
  libs/journeys/ui/src/components/StepHeader/StepHeader.tsx
Labels: effort: 2, priority: soon, type: refactor

#3306 feat: convert footer drawer to journey appearance drawer
  apps/journeys-admin-e2e/src/e2e/discover/card-level-actions.spec.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/CanvasDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Chat/Chat.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Chat/Chat.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Chat/ChatOption/ChatOption.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Chat/ChatOption/ChatOption.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Chat/ChatOption/ChatOption.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Chat/ChatOption/Details/Details.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Chat/ChatOption/Summary/Summary.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Chat/ChatOption/Summary/Summary.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/Host.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/Host.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/Host.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostForm/HostAvatarsButton/HostAvatarsButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostForm/HostAvatarsButton/HostAvatarsButton.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostForm/HostAvatarsButton/HostAvatarsButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostForm/HostAvatarsButton/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostForm/HostForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostForm/HostForm.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostForm/HostForm.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostForm/HostLocationFieldForm/HostLocationFieldForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostForm/HostLocationFieldForm/HostLocationFieldForm.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostForm/HostLocationFieldForm/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostForm/HostTitleFieldForm/HostTitleFieldForm.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostForm/HostTitleFieldForm/HostTitleFieldForm.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostForm/HostTitleFieldForm/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostForm/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostInfo/HostInfo.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostInfo/HostInfo.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostInfo/HostInfo.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostInfo/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostList/HostList.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostList/HostList.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostList/HostList.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostList/HostListItem/HostListItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostList/HostListItem/HostListItem.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostList/HostListItem/HostListItem.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostList/HostListItem/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostList/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostSelection/HostSelection.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostSelection/HostSelection.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostSelection/HostSelection.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/HostSelection/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Host/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Settings.spec.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsChat/JourneyQuickSettingsChat.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, effort: 1, type: refactor

#3301 feat: searchbar dropdown
  apps/watch/pages/strategies/index.tsx
  apps/watch/pages/watch/index.tsx
  apps/watch/src/components/StrategiesView/StrategiesView.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.handlers.ts
  libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.stories.tsx
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroup/RefinementGroup.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroup/RefinementGroup.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroup/index.ts
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/index.ts
  libs/journeys/ui/src/libs/useLanguagesContinentsQuery/data.ts
  libs/journeys/ui/src/libs/useSortLanguageContinents/index.ts
  libs/journeys/ui/src/libs/useSortLanguageContinents/useSortLanguageContinents.spec.tsx
  libs/journeys/ui/src/libs/useSortLanguageContinents/useSortLanguageContinents.tsx
Labels: priority: soon, type: feat, effort: 1

#3319 fix: order video children
  apps/api-videos/src/schema/video/video.spec.ts
  apps/api-videos/src/schema/video/video.ts
Labels: type: fix, priority: now, effort: 1

#3326 fix: redirect users to new slugs
  apps/api-videos/src/__generated__/graphql-env.d.ts
  apps/watch/pages/watch/[part1]/[part2].tsx
  apps/watch/pages/watch/[part1]/[part2]/[part3].tsx
  apps/watch/src/libs/slugMap.ts
Labels: type: fix, priority: now, effort: 1

#3324 feat: add env redis port
  apps/api-journeys/infrastructure/locals.tf
  apps/api-journeys/src/app/app.module.ts
  apps/api-languages/infrastructure/locals.tf
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-languages/src/workers/lib/connection.ts
  apps/api-users/infrastructure/locals.tf
  apps/api-users/src/app/app.module.ts
  apps/api-videos/infrastructure/locals.tf
  apps/api-videos/src/workers/lib/connection.ts
Labels: effort: 2, priority: now, type: feat

#3318 feat: language button styling
  libs/journeys/ui/src/components/SearchBar/LanguageButton/LanguageButton.tsx
  libs/journeys/ui/src/components/SearchBar/LanguageButton/index.ts
  libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
Labels: priority: soon, type: feat, effort: 1

#3328 fix: support new subtitle shape
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-videos/schema.graphql
  apps/api-videos/src/__generated__/graphql-env.d.ts
  apps/api-videos/src/schema/video/objects/videoSubtitle.ts
  apps/api-videos/src/schema/video/video.spec.ts
  apps/api-videos/src/schema/videoVariant/videoVariant.spec.ts
  apps/api-videos/src/schema/videoVariant/videoVariant.ts
  apps/api-videos/src/workers/algolia/service/service.spec.ts
  apps/api-videos/src/workers/algolia/service/service.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  apps/watch/__generated__/GetSubtitles.ts
Labels: type: fix, priority: now, effort: 1, on stage

#3313 feat: website switcher
  apps/journeys-admin/__generated__/JourneySettingsUpdate.ts
  apps/journeys-admin/pages/publisher/[journeyId].tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/WebsiteToggle/WebsiteToggle.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/WebsiteToggle/WebsiteToggle.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/WebsiteToggle/WebsiteToggle.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/WebsiteToggle/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/TitleDescriptionDialog/TitleDescriptionDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/TitleDescriptionDialog/TitleDescriptionDialog.tsx
  apps/journeys-admin/src/libs/useJourneyUpdateMutation/useJourneyUpdateMutation.spec.tsx
  apps/journeys-admin/src/libs/useJourneyUpdateMutation/useJourneyUpdateMutation.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: soon, type: feat

#3336 fix: encode carriage return
  apps/watch/src/components/TextFormatter/TextFormatter.spec.tsx
  apps/watch/src/components/TextFormatter/TextFormatter.tsx
  apps/watch/src/components/TextFormatter/index.ts
  apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.tsx
  apps/watch/src/components/VideoContentPage/VideoContent/VideoContent.tsx
Labels: type: fix, priority: now, effort: 1

#3342 test: reduce pwa to 40
  apps/journeys-admin-e2e/src/e2e/lighthouse/homepage.spec.ts
Labels: type: test, priority: now, effort: 1

#3314 refactor: import crowdIn translations with pothos pattern
  apps/api-videos/project.json
  apps/api-videos/src/__generated__/graphql-env.d.ts
  apps/api-videos/src/workers/bigQuery/importers/videoStudyQuestions/videoStudyQuestions.spec.ts
  apps/api-videos/src/workers/bigQuery/importers/videoStudyQuestions/videoStudyQuestions.ts
  apps/api-videos/src/workers/cli.ts
  apps/api-videos/src/workers/crowdin/config.ts
  apps/api-videos/src/workers/crowdin/index.ts
  apps/api-videos/src/workers/crowdin/service/index.ts
  apps/api-videos/src/workers/crowdin/service/service.spec.ts
  apps/api-videos/src/workers/crowdin/service/service.ts
  apps/api-videos/src/workers/server.ts
  package-lock.json
  package.json
Labels: effort: 3, priority: soon, type: feat, on stage
