Repository JesusFilm/core, pull requests merged in 2024-12, with the labels that each got.

#4517 feat: add video to variant dialog
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/VariantDialog.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/VariantDialog.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/VariantDialog.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantModal/VariantModal.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantModal/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
Labels: effort: 2, priority: soon, type: feat

#4323 feat: add audio language button to PageContainerHero
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Header/HeaderTabButtons/HeaderTabButtons.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.spec.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.tsx
  apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.tsx
Labels: priority: soon, type: feat, effort: 1

#4561 refactor: drop edit provider
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/EditProvider.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/EditProvider.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/TestEditProvider/TestEditProvider.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/TestEditProvider/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/Metadata.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/Metadata.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestionsList/StudyQuestionsList.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestionsList/StudyQuestionsList.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoDescription/VideoDescription.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoDescription/VideoDescription.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoDescription/VideoDescription.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImage/VideoImage.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImage/VideoImage.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImageAlt/VideoImageAlt.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImageAlt/VideoImageAlt.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImageAlt/VideoImageAlt.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInfomation.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInformation.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInformation.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/VideoSnippet.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/VideoSnippet.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/VideoSnippet.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Downloads/Downloads.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Downloads/Downloads.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_tests/page.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/layout.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.spec.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.stories.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItemMenu/OrderedItemMenu.spec.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItemMenu/OrderedItemMenu.tsx
  apps/videos-admin/src/components/OrderedList/OrderedList.spec.tsx
  apps/videos-admin/src/components/OrderedList/OrderedList.stories.tsx
  apps/videos-admin/src/components/OrderedList/OrderedList.tsx
  libs/locales/en/apps-videos-admin.json
Labels: priority: soon, effort: 1, type: chore, Refactor

#4570 chore: nest federation v2
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/federation.graphql
  apps/api-journeys/src/app/modules/visitor/visitor.graphql
Labels: effort: 2, priority: soon, type: chore, on stage

#4571 fix: center tabs and drop editions tab
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/Editions.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInfomation.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Tabs/TabLabel/TabLabel.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
  libs/locales/en/apps-videos-admin.json
Labels: type: fix, priority: now, effort: 1

#4539 fix: appearance of variants
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/Downloads/Downloads.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/Downloads/Downloads.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/Downloads/Downloads.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/Downloads/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/Downloads/utils/bytesToSize.spec.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/Downloads/utils/bytesToSize.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/VariantDialog.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/VariantDialog.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
Labels: type: fix, priority: soon, effort: 1

#4566 fix: button and placeholder ui
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
  apps/videos-admin/src/components/SaveButton/SaveButton.tsx
  libs/locales/en/apps-videos-admin.json
Labels: type: fix, priority: soon, effort: 1

#4573 fix: change components to list items and clean up children
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.tsx
  apps/videos-admin/src/components/OrderedList/OrderedList.stories.tsx
  apps/videos-admin/src/components/OrderedList/OrderedList.tsx
Labels: effort: 2, type: fix, priority: soon

#4572 fix: spacing between editing and title
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
  libs/locales/en/apps-videos-admin.json
Labels: type: fix, priority: now, effort: 1

#4574 fix: section styling
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/Metadata.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestionsList/StudyQuestionsList.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoDescription/VideoDescription.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImage/VideoImage.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImage/VideoImage.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImageAlt/VideoImageAlt.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInfomation.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/VideoSnippet.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Section/Section.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Section/Section.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.tsx
  libs/locales/en/apps-videos-admin.json
Labels: type: fix, priority: soon, effort: 1

#4588 fix: make save button smaller
  apps/videos-admin/src/components/SaveButton/SaveButton.tsx
Labels: type: fix, priority: soon, effort: 1

#4583 fix: change children and variants to outlined variant
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
Labels: type: fix, priority: soon, effort: 1

#4586 fix: icon sizing
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
  apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.tsx
  apps/videos-admin/src/components/OrderedList/OrderedList.tsx
Labels: type: fix, priority: soon, effort: 1

#4593 fix: change slug to url
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInfomation.tsx
  libs/locales/en/apps-videos-admin.json
Labels: type: fix, priority: soon, effort: 1

#4585 fix: remove editing label
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
  libs/locales/en/apps-videos-admin.json
Labels: type: fix, priority: soon, effort: 1

#4538 fix: sort variants by languageId
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/video/video.ts
Labels: type: fix, effort: 3, priority: soon, on stage

#4599 fix: variant cards styles
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
Labels: type: fix, priority: soon, effort: 1

#4594 chore: add nullable fields to editions
  apps/api-media/db/migrations/20241204012317_20241204012216/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/src/__generated__/pothos-types.ts
  apps/api-media/src/schema/videoEdition/videoEdition.spec.ts
  apps/api-media/src/workers/seed/service/edition/edition.spec.ts
Labels: priority: soon, effort: 1, type: chore, on stage

#4602 fix: expose videoId for video variant
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/videoVariant/videoVariant.spec.ts
  apps/api-media/src/schema/videoVariant/videoVariant.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.tsx
Labels: type: fix, priority: now, effort: 1, on stage

#4609 fix: remove no index
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInfomation.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInformation.spec.tsx
  libs/locales/en/apps-videos-admin.json
Labels: type: fix, priority: soon, effort: 1

#4587 test: journeyquicksettingschat
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Host/HostForm/HostForm.spec.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsChat/JourneyQuickSettingsChat.spec.tsx
  apps/journeys-admin/src/libs/useHostCreate/useHostCreate.mocks.ts
Labels: type: test, effort: 3, priority: soon

#4616 fix: change draft label
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInfomation.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInformation.spec.tsx
  apps/videos-admin/src/components/PublishedChip/PublishedChip.spec.tsx
  apps/videos-admin/src/components/PublishedChip/PublishedChip.tsx
  libs/locales/en/apps-videos-admin.json
Labels: type: fix, priority: soon, effort: 1

#4619 fix: change hero location
  apps/watch/src/components/WatchHomePage/HomeHero/HomeHero.tsx
Labels: type: fix, priority: now, effort: 1

#3856 fix: ios touch bug
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/utils/useStepAndBlockSelection/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/utils/useStepAndBlockSelection/useStepAndBlockSelection.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/utils/useStepAndBlockSelection/useStepAndBlockSelection.tsx
Labels: effort: 5, type: fix, priority: soon

#4613 fix: change segment to clip
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInfomation.tsx
Labels: type: fix, priority: soon, effort: 1

#4615 fix: change snippets label
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/Metadata.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/Metadata.tsx
  libs/locales/en/apps-videos-admin.json
Labels: type: fix, priority: soon, effort: 1

#4617 fix: variant modal changes
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/VariantDialog.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/VariantDialog.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
  libs/locales/en/apps-videos-admin.json
Labels: type: fix, priority: soon, effort: 1

#4634 fix: change or hide children tab panel label depending on video
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoChildren/VideoChildren.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoChildren/VideoChildren.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoChildren/VideoChildren.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoChildren/getVideoChildrenLabel/getVideoChildrenLabel.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoChildren/getVideoChildrenLabel/getVideoChildrenLabel.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoChildren/getVideoChildrenLabel/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoChildren/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
  libs/locales/en/apps-videos-admin.json
Labels: type: fix, priority: soon, effort: 1

#4643 fix: video variants not displaying properly
  .storybook/static/mockServiceWorker.js
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
Labels: type: fix, priority: soon, effort: 1, Bug

#4595 test: journeyquicksettingsgoals
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsGoals/JourneyQuickSettingsGoals.spec.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsGoals/JourneyQuickSettingsGoals.tsx
Labels: type: test, effort: 3, priority: soon

#4648 chore: union api media
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/cloudflare/video/video.spec.ts
  apps/api-media/src/schema/cloudflare/video/video.ts
  apps/api-media/src/schema/mux/video/video.spec.ts
  apps/api-media/src/schema/mux/video/video.ts
  apps/api-media/src/schema/schema.ts
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/video/video.ts
  apps/api-media/src/schema/videoSource/index.ts
  apps/api-media/src/schema/videoSource/videoSource.ts
  apps/api-media/src/schema/youtube/index.ts
  apps/api-media/src/schema/youtube/youtube.spec.ts
  apps/api-media/src/schema/youtube/youtube.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 3, priority: soon, type: chore, on stage

#4625 chore: create media union object
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/db/schema.prisma
  apps/api-journeys-modern/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys-modern/src/schema/mediaVideo/enums/index.ts
  apps/api-journeys-modern/src/schema/mediaVideo/enums/videoSource.ts
  apps/api-journeys-modern/src/schema/mediaVideo/index.ts
  apps/api-journeys-modern/src/schema/mediaVideo/mediaVideo.ts
  apps/api-journeys-modern/src/schema/schema.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: 2day, effort: 3, type: chore, on stage

#4506 chore: update mux backend calls
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/gql.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/db/migrations/20241126184414_20241126184404/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/infrastructure/locals.tf
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/mux/video/service.ts
  apps/api-media/src/schema/mux/video/video.spec.ts
  apps/api-media/src/schema/mux/video/video.ts
  apps/api-media/src/yoga.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 3, priority: soon, type: chore, on stage

#4112 refactor: send one journey view per day
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/db/migrations/20241110222638_20241110222636/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/event.service.ts
  apps/api-journeys/src/app/modules/event/journey/journey.graphql
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/event/journey/journey.resolver.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys/__generated__/JourneyViewEventCreate.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 2, type: fix, priority: soon

#4658 feat: video variant modal language picker initial
  apps/journeys-admin/__generated__/GetLanguages.ts
  apps/journeys-admin/__generated__/GetVideo.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoDetails/VideoDetails.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLanguage/VideoLanguage.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLanguage/VideoLanguage.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetails/JourneyDetails.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetails/JourneyDetailsDialog/JourneyDetailsDialog.stories.tsx
  apps/journeys/__generated__/GetLanguages.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/VariantDialog.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantDialog/VariantDialog.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/Downloads/Downloads.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/Downloads/Downloads.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/Downloads/Downloads.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/Downloads/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/Downloads/utils/bytesToSize.spec.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/Downloads/utils/bytesToSize.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/VariantDialog.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/VariantDialog.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/VariantDialog.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantVideo/VariantVideo.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantVideo/VariantVideo.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantVideo/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.tsx
  apps/watch/__generated__/GetLanguages.ts
  apps/watch/__generated__/GetLanguagesSlug.ts
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.tsx
  apps/watch/src/components/VideosPage/FilterList/LanguagesFilter/LanguagesFilter.spec.tsx
  apps/watch/src/components/VideosPage/FilterList/LanguagesFilter/LanguagesFilter.stories.tsx
  apps/watch/src/components/VideosPage/data.ts
  libs/journeys/ui/src/components/TemplateGallery/data.ts
  libs/journeys/ui/src/libs/useLanguagesQuery/__generated__/GetLanguages.ts
  libs/journeys/ui/src/libs/useLanguagesQuery/useLanguagesQuery.mock.ts
  libs/journeys/ui/src/libs/useLanguagesQuery/useLanguagesQuery.spec.tsx
  libs/journeys/ui/src/libs/useLanguagesQuery/useLanguagesQuery.ts
  libs/locales/en/apps-videos-admin.json
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.spec.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.stories.tsx
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.tsx
  libs/shared/ui/src/libs/themes/base/tokens/components.stories.tsx
  libs/shared/ui/src/libs/themes/journeyUi/tokens/components.stories.tsx
  libs/shared/ui/src/libs/themes/website/tokens/components.stories.tsx
Labels: effort: 2, priority: soon, type: feat

#4681 chore: swap journeys UI to mediavideo
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.spec.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/CardWrapper/CardWrapper.spec.tsx
  libs/journeys/ui/src/components/CardWrapper/CardWrapper.tsx
  libs/journeys/ui/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPreview.tsx
  libs/journeys/ui/src/components/TemplateView/TemplatePreviewTabs/data.ts
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/VideoWrapper/VideoWrapper.spec.tsx
  libs/journeys/ui/src/components/VideoWrapper/VideoWrapper.tsx
Labels: effort: 2, priority: soon, type: chore

#4690 Revert "chore: swap journeys UI to mediavideo "
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.spec.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/CardWrapper/CardWrapper.spec.tsx
  libs/journeys/ui/src/components/CardWrapper/CardWrapper.tsx
  libs/journeys/ui/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPreview.tsx
  libs/journeys/ui/src/components/TemplateView/TemplatePreviewTabs/data.ts
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/src/components/VideoWrapper/VideoWrapper.spec.tsx
  libs/journeys/ui/src/components/VideoWrapper/VideoWrapper.tsx
Labels: priority: now, effort: 1, type: revert

#4697 fix: mediaunion new video
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/schema.graphql
  apps/api-journeys-modern/src/schema/mediaVideo/mediaVideo.ts
Labels: effort: 2, type: fix, priority: soon, on stage

#4598 feat: arclight facade backend updates
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/db/migrations/20241211184517_20241211184514/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/bibleCitation/bibleCitation.ts
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/video/video.ts
  apps/api-media/src/schema/videoVariant/inputs/videoVariantCreate.ts
  apps/api-media/src/schema/videoVariant/inputs/videoVariantUpdate.ts
  apps/api-media/src/schema/videoVariant/videoVariant.spec.ts
  apps/api-media/src/schema/videoVariant/videoVariant.ts
  apps/api-media/src/workers/bigQuery/importers/bibleCitations/bibleCitations.ts
  apps/api-media/src/workers/bigQuery/importers/videoDescriptions/videoDescriptions.ts
  apps/api-media/src/workers/bigQuery/importers/videoSnippets/videoSnippets.ts
  apps/api-media/src/workers/bigQuery/importers/videoVariants/videoVariants.spec.ts
  apps/api-media/src/workers/bigQuery/importers/videoVariants/videoVariants.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: type: fix, priority: soon, effort: 1

#4706 fix: prisma in docker
  apps/api-analytics/Dockerfile
  apps/api-journeys-modern/Dockerfile
  apps/api-journeys/Dockerfile
  apps/api-languages/Dockerfile
  apps/api-media/Dockerfile
  apps/api-users/Dockerfile
Labels: type: fix, effort: 3, priority: now, on stage

#4719 chore: new video editions for future migration
  apps/api-media/project.json
  apps/api-media/src/workers/seed/migrations/editions/editions.ts
Labels: effort: 2, type: fix, priority: soon

#4748 fix: wrong prisma version
  apps/api-analytics/Dockerfile
  apps/api-journeys-modern/Dockerfile
  apps/api-journeys/Dockerfile
  apps/api-languages/Dockerfile
  apps/api-media/Dockerfile
  apps/api-users/Dockerfile
Labels: effort: 2, type: fix, priority: now, on stage

#4738 fix: skip failing playwright tests
  apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
  apps/journeys-admin-e2e/src/e2e/users/existing-user.spec.ts
Labels: type: fix, priority: now, effort: 1

#4720 fix: default icon text for button icon property
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Icon/Icon.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Icon/Icon.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: now, type: feat, effort: 1, chromatic

#4639 test: journeyquicksettings
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettings.spec.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsChat/JourneyQuickSettingsChat.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsTabs/JourneyQuickSettingsTabs.spec.tsx
  apps/journeys-admin/src/components/JourneyQuickSettings/JourneyQuickSettingsTabs/JourneyQuickSettingsTabs.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingTemplateCard/OnboardingTemplateCard.tsx
Labels: type: test, effort: 2, priority: soon

#4727 fix: turn off share button display for journey creation
  apps/api-journeys/db/schema.prisma
Labels: priority: 2day, type: fix, effort: 1

#4750 fix: skip failing playwright test
  apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
Labels: type: fix, priority: now, effort: 1

#4752 fix: skip playwright test
  apps/journeys-e2e/src/e2e/journeys.spec.ts
Labels: type: fix, priority: now, effort: 1

#4751 feat: footer ui improvements
  libs/journeys/ui/src/components/Card/utils/getFooterElements/getFooterElements.ts
  libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
Labels: priority: now, type: feat, effort: 1, chromatic

#4740 fix: point subtitles and variants to nullable fields
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/db/migrations/20241217200243_20241217200239/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/__generated__/pothos-types.ts
  apps/api-media/src/schema/video/videoSubtitle/videoSubtitle.ts
  apps/api-media/src/schema/videoVariant/videoVariant.ts
  apps/api-media/src/workers/bigQuery/importers/videoSubtitles/videoSubtitles.spec.ts
  apps/api-media/src/workers/bigQuery/importers/videoSubtitles/videoSubtitles.ts
  apps/api-media/src/workers/bigQuery/importers/videoVariants/videoVariants.spec.ts
  apps/api-media/src/workers/bigQuery/importers/videoVariants/videoVariants.ts
  apps/api-media/src/workers/seed/service/edition/edition.spec.ts
  apps/api-media/src/workers/seed/service/edition/edition.ts
  apps/api-media/src/workers/seed/service/edition/index.ts
  apps/api-media/src/workers/seed/service/service.spec.ts
  apps/api-media/src/workers/seed/service/service.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: soon, effort: 1, type: chore, on stage

#4756 fix: bad syntax and semantics
  libs/journeys/ui/src/components/Card/utils/getFooterElements/getFooterElements.ts
Labels: type: fix, priority: now, effort: 1, chromatic

#3837 feat: resized onboarding list fonts
  apps/journeys-admin/src/components/MediaListItem/MediaListItem.tsx
Labels: type: fix, priority: soon, effort: 1

#4760 fix: set description text to block
  apps/journeys-admin/src/components/MediaListItem/MediaListItem.tsx
Labels: type: fix, priority: now, effort: 1, chromatic

#4293 docs: update UI change documentation
  apps/docs/docs/03-basics/03-frontend/05-visual-testing/index.md
Labels: type: docs, priority: soon, effort: 1

#4736 fix: menu click brings up canvas
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/StepBlockNodeMenu.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/StepBlockNodeMenu.tsx
Labels: effort: 2, type: fix, priority: now

#4545 feat: arclight media components e2e tests
  apps/arclight-e2e/src/e2e/docs.spec.ts
  apps/arclight-e2e/src/e2e/media-component-links/media-component-links.spec.ts
  apps/arclight-e2e/src/e2e/media-components/media-component-language.spec.ts
  apps/arclight-e2e/src/e2e/media-components/media-component-languages.spec.ts
  apps/arclight-e2e/src/e2e/media-components/media-component.spec.ts
  apps/arclight-e2e/src/e2e/media-components/media-components.spec.ts
  apps/arclight-e2e/src/e2e/media-languages/media-language.spec.ts
  apps/arclight-e2e/src/e2e/media-languages/media-languages.spec.ts
  apps/arclight-e2e/src/framework/helpers.ts
  apps/arclight-e2e/src/utils/media-component-utils.ts
  apps/arclight-e2e/src/utils/testData.json
  apps/arclight-e2e/tsconfig.e2e.json
  apps/arclight/src/app/v2/media-component-links/[mediaComponentId]/route.ts
  apps/arclight/src/app/v2/media-component-links/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/[languageId]/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/route.ts
  apps/arclight/src/app/v2/media-components/route.ts
  apps/arclight/src/app/v2/media-country-links/route.ts
  apps/arclight/src/app/v2/media-languages/[languageId]/route.ts
  apps/arclight/src/app/v2/media-languages/route.ts
  apps/arclight/src/app/v2/metadata-language-tags/[metadataLanguageTag]/route.ts
  apps/arclight/src/app/v2/metadata-language-tags/route.ts
  apps/arclight/src/app/v2/resources/route.ts
  apps/arclight/src/app/v2/taxonomies/[category]/route.ts
  apps/arclight/src/app/v2/taxonomies/route.ts
Labels: effort: 3, priority: soon, type: feat
