Repository JesusFilm/core, pull requests merged in 2024-05, with the labels that each got.

#2676 fix: mobile empty card text
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CardWrapper/CardWrapper.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, type: fix, priority: soon

#2681 fix: unsplash duplication issue
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/UnsplashGallery.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, effort: 3, priority: soon

#2692 test: get background image
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/getBackgroundImage/getBackgroundImage.spec.ts
Labels: type: test, priority: soon, effort: 1

#2695 fix: admin empty team dropdown
  apps/journeys-admin/pages/index.tsx
Labels: type: fix, priority: now, effort: 1

#2697 fix: admin-template-teams
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/index.tsx
Labels: type: fix, priority: now, effort: 1

#2651 fix: video detail drawer
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsListItem/GoalsListItem.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/UnsplashGallery.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Source/Source.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Source/Source.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoList/VideoListItem/VideoListItem.tsx
  apps/journeys-admin/test/mockReactFlow.ts
Labels: type: fix, priority: soon, effort: 1

#2693 test: get priority block
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/getPriorityBlock/getPriorityBlock.spec.ts
Labels: type: test, priority: now, effort: 1

#2679 fix: remove hover state on mobile
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
Labels: type: fix, effort: 3, priority: soon

#2643 feat: open card properties on selected card second click
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
Labels: effort: 3, priority: soon, type: feat

#2702 refactor: duplicate step block positions
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/block.graphql
  apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/block.resolver.ts
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
Labels: priority: now, effort: 1, type: refactor, on stage

#2704 refactor: change chat platform to message platform
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/ERD.svg
  apps/api-journeys/db/migrations/20240503165006_20240503165004/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/chatButton/chatButton.graphql
  apps/api-journeys/src/app/modules/chatButton/chatButton.resolver.spec.ts
  apps/journeys-admin/__generated__/GetAdminJourney.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/JourneyChatButtonCreate.ts
  apps/journeys-admin/__generated__/JourneyChatButtonUpdate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/Chat.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/Chat.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/ChatOption.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/ChatOption.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/ChatOption.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Details/Details.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Details/Details.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Summary/Summary.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Chat/ChatOption/Summary/Summary.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/Footer.tsx
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/journeys/src/components/Conductor/Conductor.stories.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx
  apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.stories.tsx
  apps/nexus-admin/__generated__/JourneyFields.ts
  apps/nexus-admin/__generated__/globalTypes.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/journeys/ui/src/components/Button/Button.tsx
  libs/journeys/ui/src/components/Button/utils/findChatPlatform/index.ts
  libs/journeys/ui/src/components/Button/utils/findMessagePlatform/findMessagePlatform.spec.ts
  libs/journeys/ui/src/components/Button/utils/findMessagePlatform/findMessagePlatform.ts
  libs/journeys/ui/src/components/Button/utils/findMessagePlatform/index.ts
  libs/journeys/ui/src/components/Button/utils/getLinkActionGoal/getLinkActionGoal.ts
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.spec.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.stories.tsx
  libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.tsx
  libs/journeys/ui/src/components/StepFooter/StepFooter.stories.tsx
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
Labels: breaking, priority: now, effort: 1, type: refactor, on stage

#2703 fix: fix encoding bug with share urls
  apps/watch/pages/api/jf/watch.html/[videoId]/[languageId].ts
Labels: effort: 2, type: fix, priority: soon

#2701 test: getCardHeading and getCardMetadata
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/getCardHeadings/getCardHeadings.spec.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/getCardHeadings/getCardHeadings.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/getCardMetadata/getCardMetadata.spec.ts
Labels: type: fix, priority: soon, effort: 1

#2708 test: transform steps
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.ts
Labels: type: test, priority: soon, effort: 1

#2709 test: stepBlockNodeIcon
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeIcon/StepBlockNodeIcon.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeIcon/StepBlockNodeIcon.stories.tsx
Labels: type: test, priority: soon, type: feat, effort: 1

#2710 test: block delete update
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
Labels: type: test, priority: soon, effort: 1

#2706 test: filterActionBlocks test
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/filterActionBlocks/filterActionBlocks.spec.ts
Labels: type: test, effort: 2, priority: soon

#2656 chore: node 20
  .devcontainer/Dockerfile
  .devcontainer/docker-compose.yml
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-prod-worker.yml
  .github/workflows/api-gateway-stage-worker.yml
  .github/workflows/app-deploy.yml
  .github/workflows/danger.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/ecs-frontend-deploy-prod-worker.yml
  .github/workflows/ecs-frontend-deploy-stage-worker.yml
  .github/workflows/main.yml
  apps/api-journeys/Dockerfile
  apps/api-journeys/db/Dockerfile
  apps/api-languages/Dockerfile
  apps/api-languages/db/Dockerfile
  apps/api-media/Dockerfile
  apps/api-tags/Dockerfile
  apps/api-tags/db/Dockerfile
  apps/api-users/Dockerfile
  apps/api-videos/Dockerfile
  apps/api-videos/db/Dockerfile
  apps/journeys-admin/Dockerfile
  package-lock.json
  package.json
Labels: priority: 2day, effort: 1, type: chore

#2711 fix: node 20
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  apps/api-journeys/db/Dockerfile
Labels: type: fix, priority: now, effort: 1

#2700 test: arrange steps
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/arrangeSteps/arrangeSteps.spec.ts
Labels: type: test, priority: soon, effort: 1

#2712 chore: nexus-admin storybook config
  .storybook/main.js
  apps/nexus-admin/.eslintrc.json
  apps/nexus-admin/src/libs/storybook/config.tsx
  apps/nexus-admin/src/libs/storybook/index.tsx
  libs/shared/storybook/project.json
Labels: effort: 2, priority: now, type: chore

#2684 feat: arclight media-languages single
  apps/arclight/src/app/v2/media-languages/[languageId]/route.ts
Labels: priority: 2day, effort: 2, type: feat

#2699 fix: text block deleting
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DeleteBlock/DeleteBlock.tsx
  apps/journeys/src/components/EmbeddedPreview/ClickableCard/ClickableCard.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
  libs/shared/ui/src/libs/deviceUtils/deviceUtils.spec.ts
  libs/shared/ui/src/libs/deviceUtils/deviceUtils.ts
  libs/shared/ui/src/libs/deviceUtils/index.ts
Labels: priority: 2day, effort: 2, type: fix

#2718 test: duplicate block cache update tests
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DuplicateBlock/DuplicateBlock.spec.tsx
Labels: type: test, effort: 3, priority: soon

#2715 chore: nx 19
  apps/journeys-admin/setupTests.tsx
  package-lock.json
  package.json
Labels: priority: 2day, effort: 1, type: chore

#2716 fix: node menu style
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/StepBlockNodeMenu.tsx
Labels: priority: 2day, effort: 1, type: style

#2720 feat: close icon on settings panel
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Button/Button.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/Card.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Form.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Image.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Options/ImageOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioOption/RadioOption.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioQuestion/RadioQuestion.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/SignUp/SignUp.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Typography.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Video.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/GoalDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/GoalDetails.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/SocialDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/SocialDetails.tsx
Labels: effort: 2, priority: soon, type: feat

#2725 feat: video edition schema
  apps/api-videos/db/migrations/20240508225808_20240508225807/migration.sql
  apps/api-videos/db/schema.prisma
  apps/api-videos/src/app/modules/video/video.resolver.spec.ts
Labels: priority: soon, type: feat, effort: 1

#2724 feat: add label for video nodes
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockCreate.ts
  apps/journeys-admin/__generated__/CardBlockVideoBlockUpdate.ts
  apps/journeys-admin/__generated__/CardIntroCreate.ts
  apps/journeys-admin/__generated__/CardVideoCreate.ts
  apps/journeys-admin/__generated__/GetAdminJourney.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/VideoBlockCreate.ts
  apps/journeys-admin/__generated__/VideoBlockUpdate.ts
  apps/journeys-admin/__generated__/VideoFields.ts
  apps/journeys-admin/src/components/CardPreview/CardList/CardList.spec.tsx
  apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/getBackgroundImage/getBackgroundImage.spec.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/getCardMetadata/getCardMetadata.spec.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/getCardMetadata/getCardMetadata.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/getPriorityBlock/getPriorityBlock.spec.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/BackgroundMedia.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/Card.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Video.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardIntro/CardIntro.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Settings/Poster/VideoBlockEditorSettingsPoster.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/VideoBlockEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/VideoBlockEditor.stories.tsx
  apps/journeys-admin/src/components/Editor/data.ts
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/data.ts
  apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/VideoFields.ts
  apps/nexus-admin/__generated__/BlockFields.ts
  apps/nexus-admin/__generated__/JourneyFields.ts
  apps/nexus-admin/__generated__/VideoFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.spec.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.stories.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.spec.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.spec.tsx
  libs/journeys/ui/src/components/Video/Video.spec.tsx
  libs/journeys/ui/src/components/Video/__generated__/VideoFields.ts
  libs/journeys/ui/src/components/Video/videoFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
Labels: effort: 2, priority: soon, type: feat

#2719 fix: add back button tooltip
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Labels: priority: 2day, type: fix, effort: 1

#2728 ci: add helpful message git status check
  tools/scripts/check-git-status.sh
Labels: priority: 2day, effort: 1, type: build

#2732 fix: stop playing local video after drawer closes
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
Labels: effort: 2, type: fix, priority: soon

#2735 fix: canvas size on journeymap
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/utils/calculateDimensions/calculateDimensions.ts
Labels: effort: 2, type: fix, priority: soon

#2739 feat: languages bq import support part 1
  apps/api-languages/db/migrations/20240510220947_20240510220946/migration.sql
  apps/api-languages/db/schema.prisma
  apps/api-languages/db/seed.ts
Labels: effort: 2, priority: soon, type: feat

#2745 feat: languages bq import support part 2
  apps/api-languages/db/migrations/20240514002827_20240514002819/migration.sql
  apps/api-languages/db/schema.prisma
  apps/api-languages/db/seed.ts
  apps/api-languages/project.json
  apps/api-languages/schema.graphql
  apps/api-languages/src/app/modules/language/language.graphql
  apps/api-languages/src/app/modules/language/language.resolver.spec.ts
  apps/api-languages/src/app/modules/language/language.resolver.ts
Labels: effort: 3, priority: soon, type: feat, on stage

#2746 fix: google translate error on form blocks
  libs/journeys/ui/src/components/SignUp/SignUp.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
Labels: type: fix, priority: soon, effort: 1

#2753 fix: video not found error
  apps/watch/pages/[part1]/[part2].tsx
  apps/watch/pages/[part1]/[part2]/[part3].tsx
Labels: type: fix, priority: now, effort: 1

#2752 fix: catch firebase decode error
  libs/nest/common/src/lib/firebaseClient/firebaseClient.ts
Labels: type: fix, priority: now, effort: 1

#2754 fix: casl permissions update
  apps/api-journeys/src/app/modules/customDomain/customDomain.acl.spec.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.acl.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.resolver.spec.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.resolver.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#2748 feat: added journeyFlowBackButtonClicked to JourneyProfile
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/migrations/20240513223637_20240513223633/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.graphql
  apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.spec.ts
  apps/journeys-admin/__generated__/globalTypes.ts
Labels: priority: now, type: feat, effort: 1, on stage

#2729 fix: add stop propagation
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.tsx
Labels: type: fix, priority: soon, effort: 1

#2760 fix: add more languages to templates
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
  apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/LanguagesFilterPopper/LanguagesFilterPopper.tsx
  apps/journeys-admin/src/components/TemplateGallery/data.ts
Labels: effort: 2, type: fix, priority: now

#2743 refactor: remove NavigateToJourneyAction from frontend
  apps/journeys-admin/__generated__/GetJourneyNames.ts
  apps/journeys-admin/__generated__/NavigateToJourneyActionUpdate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.spec.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.tsx
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/index.ts
  apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/data.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/TimelineEvent/TimelineEvent.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/TimelineEvent/TimelineEvent.stories.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/data.ts
  libs/locales/en/apps-journeys-admin.json
Labels: priority: 2day, effort: 2, type: refactor

#2758 fix: add icons after actions
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
Labels: type: fix, priority: now, effort: 1

#2742 feat: edge hover
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/BaseEdge/BaseEdge.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/CustomEdge/CustomEdge.tsx
Labels: effort: 3, priority: soon, type: feat

#2740 refactor: mark NavigateToJourneyAction for deprecation
  apps/api-gateway/schema.graphql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/modules/action/action.graphql
  apps/api-journeys/src/app/modules/event/button/button.graphql
  apps/journeys-admin/__generated__/GetVisitorEvents.ts
Labels: priority: 2day, effort: 2, type: refactor, on stage

#2755 build: ignore history folders
  .gitignore
Labels: priority: 2day, effort: 1, type: build

#2756 feat: back to map admin changes
  apps/journeys-admin/__generated__/UpdateJourneyFlowBackButtonClicked.ts
  apps/journeys-admin/__generated__/getJourneyFlowBackButtonClicked.ts
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: now, type: feat

#2738 feat: delete nodes and edges on keypress
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DeleteBlock/DeleteBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DeleteBlock/DeleteBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteOnKeyPress/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteOnKeyPress/useDeleteOnKeyPress.ts
  apps/journeys-admin/src/libs/useBlockDeleteMutation/index.ts
  apps/journeys-admin/src/libs/useBlockDeleteMutation/useBlockDeleteMutation.mock.ts
  apps/journeys-admin/src/libs/useBlockDeleteMutation/useBlockDeleteMutation.spec.tsx
  apps/journeys-admin/src/libs/useBlockDeleteMutation/useBlockDeleteMutation.ts
Labels: effort: 2, priority: soon, type: feat

#2714 feat: update property drawer styles
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/Drawer.tsx
Labels: priority: soon, type: feat, effort: 1

#2769 fix: action cache
  apps/journeys-admin/__generated__/EmailActionUpdate.ts
  apps/journeys-admin/__generated__/LinkActionUpdate.ts
  apps/journeys-admin/__generated__/MultipleLinkActionUpdate.ts
  apps/journeys-admin/__generated__/NavigateActionUpdate.ts
  apps/journeys-admin/__generated__/UpdateVideoBlockNextStep.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/Action.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/EmailAction/EmailAction.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/EmailAction/EmailAction.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/LinkAction/LinkAction.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/LinkAction/LinkAction.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/ActionEditor/ActionEditor.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/ActionEditor/ActionEditor.tsx
  apps/journeys-admin/src/libs/apolloClient/cache.ts
Labels: type: fix, priority: soon, effort: 1

#2768 refactor: selected card
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/Action.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/EmailAction/EmailAction.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/LinkAction/LinkAction.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateAction/NavigateAction.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateToBlockAction/CardItem/CardItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateToBlockAction/CardItem/CardItem.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateToBlockAction/CardItem/CardItem.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateToBlockAction/NavigateToBlockAction.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateToBlockAction/NavigateToBlockAction.tsx
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: soon, type: refactor

#2762 chore: new crowdin translations
  libs/locales/am-ET/apps-journeys-admin.json
  libs/locales/ar-SA/apps-journeys-admin.json
  libs/locales/bn-BD/apps-journeys-admin.json
  libs/locales/es-ES/apps-journeys-admin.json
  libs/locales/fr-FR/apps-journeys-admin.json
  libs/locales/hi-IN/apps-journeys-admin.json
  libs/locales/id-ID/apps-journeys-admin.json
  libs/locales/ja-JP/apps-journeys-admin.json
  libs/locales/my-MM/apps-journeys-admin.json
  libs/locales/ru-RU/apps-journeys-admin.json
  libs/locales/th-TH/apps-journeys-admin.json
  libs/locales/tl-PH/apps-journeys-admin.json
  libs/locales/tr-TR/apps-journeys-admin.json
  libs/locales/ur-PK/apps-journeys-admin.json
  libs/locales/vi-VN/apps-journeys-admin.json
  libs/locales/zh-Hans-CN/apps-journeys-admin.json
  libs/locales/zh-Hant-TW/apps-journeys-admin.json
Labels: priority: soon, effort: 1, type: chore

#2727 fix: drop navigate action dropdown and null next block advancing
  apps/journeys-admin/__generated__/NavigateActionUpdate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/Action.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/Action.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/Action.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateAction/NavigateAction.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateAction/NavigateAction.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateAction/NavigateAction.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateAction/index.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/TimelineEvent/TimelineEvent.spec.tsx
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/getButtonLabel/getButtonLabel.spec.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/getButtonLabel/getButtonLabel.ts
  apps/journeys-admin/src/libs/apolloClient/cache.ts
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.spec.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/libs/action/action.spec.ts
  libs/journeys/ui/src/libs/action/action.ts
  libs/journeys/ui/src/libs/block/block.spec.ts
  libs/journeys/ui/src/libs/block/block.ts
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#2772 fix: navigation ending connections logic
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
Labels: effort: 2, type: fix, priority: now

#2775 fix: next step text
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#2773 fix: update edges immediately
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
Labels: type: fix, priority: soon, effort: 1

#2777 fix: remove ld flag
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.spec.tsx
  apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.tsx
Labels: type: fix, priority: soon, effort: 1

#2778 feat: hide self connecting edges
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.ts
Labels: priority: soon, type: feat, effort: 1

#2774 fix: card templates close icon
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
Labels: effort: 2, type: fix, priority: soon

#2558 test: add playwright e2e tests
  .github/workflows/app-deploy.yml
  apps/arclight-e2e/playwright.config.ts
  apps/docs-e2e/playwright.config.ts
  apps/journeys-admin-e2e/playwright.config.ts
  apps/journeys-admin-e2e/src/e2e/discover/active-archived-trash.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/journey-level-actions.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/members.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/teams.spec.ts
  apps/journeys-admin-e2e/src/e2e/journeys-admin.spec.ts
  apps/journeys-admin-e2e/src/e2e/lighthouse/homepage.spec.ts
  apps/journeys-admin-e2e/src/e2e/profile/profile.spec.ts
  apps/journeys-admin-e2e/src/e2e/un-auth/un-auth.spec.ts
  apps/journeys-admin-e2e/src/e2e/user-creation.spec.ts
  apps/journeys-admin-e2e/src/e2e/users/existing-user.spec.ts
  apps/journeys-admin-e2e/src/framework/helpers.ts
  apps/journeys-admin-e2e/src/pages/journey-level-actions-page.ts
  apps/journeys-admin-e2e/src/pages/journey-page.ts
  apps/journeys-admin-e2e/src/pages/landing-page.ts
  apps/journeys-admin-e2e/src/pages/left-nav.ts
  apps/journeys-admin-e2e/src/pages/login-page.ts
  apps/journeys-admin-e2e/src/pages/profile-page.ts
  apps/journeys-admin-e2e/src/pages/publisher-page.ts
  apps/journeys-admin-e2e/src/pages/register-Page.ts
  apps/journeys-admin-e2e/src/pages/teams-page.ts
  apps/journeys-admin-e2e/src/utils/testData.json
  apps/journeys-e2e/playwright.config.ts
  apps/nexus-admin-e2e/playwright.config.ts
  apps/watch-e2e/playwright.config.ts
  apps/watch-e2e/src/e2e/chapter.spec.ts-snapshots/after-video-firefox-linux.png
  apps/watch-e2e/src/e2e/filters.spec.ts-snapshots/see-all-landing-firefox-linux.png
  package-lock.json
  package.json
Labels: type: test, priority: 2day, effort: 8, effort: 13

#2783 fix: edge arrow color
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.ts
Labels: type: fix, priority: now, effort: 1

#2785 test: new step button
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/NewStepButton/NewStepButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/NewStepButton/NewStepButton.stories.tsx
  apps/journeys-admin/src/libs/useStepAndCardBlockCreateMutation/useStepAndCardBlockCreateMutation.mock.ts
Labels: type: test, priority: soon, type: feat, effort: 1

#2787 test: stepblocknode
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/DuplicateStep/DuplicateStep.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/DuplicateStep/DuplicateStep.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/sizes.ts
Labels: type: test, effort: 3, priority: soon

#2788 test: useDeleteEdge
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteEdge/useDeleteEdge.spec.tsx
  apps/journeys-admin/src/libs/useBlockActionDeleteMutation/useBlockActionDeleteMutation.mock.ts
  apps/journeys-admin/src/libs/useStepBlockNextBlockUpdateMutation/useStepBlockNextBlockUpdateMutation.mock.ts
Labels: type: test, priority: soon, effort: 1

#2734 fix: action same block id error message
  apps/api-journeys/src/app/modules/action/action.module.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.spec.ts
  apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts
  apps/api-journeys/src/app/modules/block/block.service.spec.ts
  apps/api-journeys/src/app/modules/block/block.service.ts
  apps/api-journeys/src/app/modules/block/step/step.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/step/step.resolver.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#2793 test: active slide dispatch
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.spec.tsx
Labels: type: test, priority: soon, effort: 1

#2791 test: stepblock node card
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.tsx
Labels: type: test, priority: soon, effort: 1

#2794 chore: host dark mode logo image
  apps/journeys/public/LogoHoriztonalDark.png
Labels: priority: soon, effort: 1, type: chore

#2799 test: use update edge
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useUpdateEdge/useUpdateEdge.spec.tsx
  apps/journeys-admin/src/libs/useNavigateToBlockActionUpdateMutation/useNavigateToBlockActionUpdate.mock.ts
Labels: type: test, priority: soon, effort: 1

#2779 test: edge tests and stories
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/BaseEdge/BaseEdge.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/BaseEdge/BaseEdge.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/CustomEdge/CustomEdge.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/CustomEdge/CustomEdge.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/CustomEdge/CustomEdge.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/StartEdge/StartEdge.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/edges/StartEdge/StartEdge.stories.tsx
Labels: type: test, effort: 3, priority: soon

#2800 feat: hide step button and controls
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
Labels: priority: soon, type: feat, effort: 1

#2797 fix: share button url - custom domains
  libs/journeys/ui/src/components/StepFooter/FooterButtonList/ShareButton/ShareButton.tsx
Labels: type: fix, priority: soon, effort: 1, on stage

#2802 test: add hook tests
  apps/journeys-admin/src/libs/useBlockActionDeleteMutation/useBlockActionDeleteMutation.spec.tsx
  apps/journeys-admin/src/libs/useNavigateToBlockActionUpdateMutation/useNavigateToBlockActionUpdateMutation.spec.tsx
  apps/journeys-admin/src/libs/useStepAndCardBlockCreateMutation/useStepAndCardBlockCreateMutation.spec.tsx
Labels: type: test, effort: 2, priority: soon

#2786 refactor: pagination bullets branching
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/arrangeSteps/arrangeSteps.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
  apps/journeys/src/components/Conductor/Conductor.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.spec.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.stories.tsx
  libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.tsx
  libs/journeys/ui/src/libs/filterActionBlocks/filterActionBlocks.spec.ts
  libs/journeys/ui/src/libs/filterActionBlocks/filterActionBlocks.ts
  libs/journeys/ui/src/libs/filterActionBlocks/index.ts
  libs/journeys/ui/src/libs/isActionBlock/index.ts
  libs/journeys/ui/src/libs/isActionBlock/isActionBlock.spec.tsx
  libs/journeys/ui/src/libs/isActionBlock/isActionBlock.ts
Labels: type: fix, effort: 3, priority: soon

#2801 fix: slow delete block
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DeleteBlock/DeleteBlock.tsx
Labels: type: fix, effort: 3, priority: soon

#2803 test: useCreateStep
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.spec.tsx
Labels: type: test, priority: soon, effort: 1

#2806 test: slider back button text
  apps/journeys-admin/__generated__/UpdateJourneyFlowBackButtonClicked.ts
  apps/journeys-admin/src/components/Editor/Slider/Slider.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
Labels: type: test, priority: soon, effort: 1

#2808 test: journeyflow
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
  apps/journeys-admin/src/components/Editor/data.ts
Labels: type: test, effort: 3, priority: soon

#2811 fix: form block update back end
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/event/textResponse/textResponse.graphql
Labels: type: fix, priority: soon, effort: 1, on stage

#2807 chore: nx 19.1
  .eslintrc.json
  apps/api-videos/db/seed.ts
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.spec.tsx
  apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.spec.tsx
  apps/journeys-admin/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.spec.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.spec.tsx
  package-lock.json
  package.json
Labels: priority: 2day, effort: 1, type: chore, dependencies

#2780 feat: link node
  apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsListItem/GoalsListItem.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/arrangeSteps/arrangeSteps.spec.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/arrangeSteps/arrangeSteps.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNode.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/libs/sizes.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/ActionEditor/ActionEditor.tsx
  libs/journeys/ui/src/components/Button/utils/getLinkActionGoal/getLinkActionGoal.spec.ts
  libs/journeys/ui/src/components/Button/utils/getLinkActionGoal/getLinkActionGoal.ts
  libs/journeys/ui/src/libs/getGoalDetails/getGoalDetails.spec.tsx
  libs/journeys/ui/src/libs/getGoalDetails/getGoalDetails.tsx
  libs/journeys/ui/src/libs/getGoalDetails/index.ts
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/libs-journeys-ui.json
Labels: effort: 3, priority: soon, type: feat

#2818 feat: branch analytics toggle
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsOverlaySwitch/AnalyticsOverlaySwitch.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsOverlaySwitch/index.ts
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/NewStepButton/NewStepButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: soon, type: feat
