Repository JesusFilm/core, pull requests merged in 2025-06, with the labels that each got.

#6777 chore: update Docker build process in workflows to use Buildx and str…
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-prod-worker.yml
  .github/workflows/api-gateway-stage-worker.yml
  .github/workflows/ecs-frontend-deploy-prod-worker.yml
  .github/workflows/ecs-frontend-deploy-stage-worker.yml
  .github/workflows/task-deploy-worker.yml
Labels: on stage

#6760 feat: trash all journeys before creating one to fix Checkly size limit issue and skip video
  apps/journeys-admin-e2e/src/e2e/discover/card-level-actions.spec.ts
  apps/journeys-admin-e2e/src/monitoring/journeys-admin.monitor.ts
  apps/journeys-admin-e2e/src/pages/card-level-actions.ts
Labels: effort: 5, priority: soon, Testing

#6797 fix: comment out algolia mass import
  apis/api-media/src/workers/server.ts
Labels: on stage

#6794 feat: 3 dot menu button mobile styles
  apps/journeys-admin-e2e/src/pages/journey-level-actions-page.ts
  apps/journeys-admin-e2e/src/pages/journey-page.ts
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.tsx
Labels: type: feat

#6793 feat: new design of template list
  apps/journeys-admin/pages/publisher/index.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
  apps/journeys-admin/src/components/TemplateList/ActiveTemplateList/ActiveTemplateList.spec.tsx
  apps/journeys-admin/src/components/TemplateList/ActiveTemplateList/ActiveTemplateList.tsx
  apps/journeys-admin/src/components/TemplateList/ArchivedTemplateList/ArchivedTemplateList.spec.tsx
  apps/journeys-admin/src/components/TemplateList/ArchivedTemplateList/ArchivedTemplateList.tsx
  apps/journeys-admin/src/components/TemplateList/LoadingTemplateList/LoadingTemplateList.tsx
  apps/journeys-admin/src/components/TemplateList/LoadingTemplateList/index.ts
  apps/journeys-admin/src/components/TemplateList/TemplateList.tsx
  apps/journeys-admin/src/components/TemplateList/TemplateListItem/TemplateListItem.spec.tsx
  apps/journeys-admin/src/components/TemplateList/TemplateListItem/TemplateListItem.stories.tsx
  apps/journeys-admin/src/components/TemplateList/TemplateListItem/TemplateListItem.tsx
  apps/journeys-admin/src/components/TemplateList/TemplateListItem/index.ts
  apps/journeys-admin/src/components/TemplateList/TrashedTemplateList/TrashedTemplateList.spec.tsx
  apps/journeys-admin/src/components/TemplateList/TrashedTemplateList/TrashedTemplateList.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: soon, type: feat

#6805 feat: add style property to various block types for CSS customization
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/db/schema.prisma
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys-modern/src/schema/block/button/button.ts
  apis/api-journeys-modern/src/schema/block/card/card.ts
  apis/api-journeys-modern/src/schema/block/icon/icon.ts
  apis/api-journeys-modern/src/schema/block/image/image.ts
  apis/api-journeys-modern/src/schema/block/radioOption/radioOption.ts
  apis/api-journeys-modern/src/schema/block/signUp/signUp.ts
  apis/api-journeys-modern/src/schema/block/spacer/spacer.ts
  apis/api-journeys-modern/src/schema/block/textResponse/textResponse.ts
  apis/api-journeys-modern/src/schema/block/typography/typography.ts
  apis/api-journeys-modern/src/schema/block/video/video.ts
  apis/api-journeys/db/migrations/20250611193849_20250611193846/migration.sql
  apis/api-journeys/db/schema.prisma
  apis/api-journeys/project.json
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/lib/tailwind/cn.ts
  apis/api-journeys/src/app/lib/tailwind/index.ts
  apis/api-journeys/src/app/lib/tailwind/sanitizeClassNames.ts
  apis/api-journeys/src/app/modules/block/block.service.spec.ts
  apis/api-journeys/src/app/modules/block/block.service.ts
  apis/api-journeys/src/app/modules/block/button/button.graphql
  apis/api-journeys/src/app/modules/block/button/button.resolver.ts
  apis/api-journeys/src/app/modules/block/card/card.graphql
  apis/api-journeys/src/app/modules/block/card/card.resolver.ts
  apis/api-journeys/src/app/modules/block/icon/icon.graphql
  apis/api-journeys/src/app/modules/block/icon/icon.resolver.ts
  apis/api-journeys/src/app/modules/block/image/image.graphql
  apis/api-journeys/src/app/modules/block/image/image.resolver.ts
  apis/api-journeys/src/app/modules/block/radioOption/radioOption.graphql
  apis/api-journeys/src/app/modules/block/radioOption/radioOption.resolver.ts
  apis/api-journeys/src/app/modules/block/signUp/signUp.graphql
  apis/api-journeys/src/app/modules/block/signUp/signUp.resolver.ts
  apis/api-journeys/src/app/modules/block/spacer/spacer.graphql
  apis/api-journeys/src/app/modules/block/spacer/spacer.resolver.ts
  apis/api-journeys/src/app/modules/block/textResponse/textResponse.graphql
  apis/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.ts
  apis/api-journeys/src/app/modules/block/typography/typography.graphql
  apis/api-journeys/src/app/modules/block/typography/typography.resolver.ts
  apis/api-journeys/src/app/modules/block/video/video.graphql
  apis/api-journeys/src/app/modules/block/video/video.resolver.ts
  apis/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apis/api-journeys/src/app/modules/journey/journey.resolver.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  package-lock.json
  package.json
Labels: on stage

#6825 feat: add 'outlined' variant to ButtonVariant - back end
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys-modern/src/schema/block/button/enums/buttonVariant.ts
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/block/button/button.graphql
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
Labels: on stage

#6842 feat: introduce restrictDownloadPlatforms
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-gateway/src/common.config.ts
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/db/migrations/20250619222628_20250619222627/migration.sql
  apis/api-media/db/schema.prisma
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/builder.ts
  apis/api-media/src/schema/video/enums/index.ts
  apis/api-media/src/schema/video/enums/platform.ts
  apis/api-media/src/schema/video/inputs/videoUpdate.ts
  apis/api-media/src/schema/video/video.spec.ts
  apis/api-media/src/schema/video/video.ts
  apis/api-media/src/schema/videoVariant/videoVariant.spec.ts
  apis/api-media/src/schema/videoVariant/videoVariant.ts
  apis/api-media/src/workers/crowdin/importers/videoTitles/videoTitles.spec.ts
  apis/api-media/src/yoga.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#6839 feat: add videoOrigins query and originId field to video creation inputs
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/video/inputs/videoCreate.ts
  apis/api-media/src/schema/video/video.spec.ts
  apis/api-media/src/schema/video/videoOrigin/videoOrigin.spec.ts
  apis/api-media/src/schema/video/videoOrigin/videoOrigin.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/app/(dashboard)/videos/_VideoCreateForm/VideoCreateForm.spec.tsx
  apps/videos-admin/src/app/(dashboard)/videos/_VideoCreateForm/VideoCreateForm.tsx
Labels: on stage

#6844 feat: add restrictViewPlatforms to Video and update related inputs an…
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/db/schema.prisma
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/db/migrations/20250620000523_20250620000521/migration.sql
  apis/api-media/db/migrations/20250623234052_20250623234044/migration.sql
  apis/api-media/db/schema.prisma
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/video/inputs/videoUpdate.ts
  apis/api-media/src/schema/video/video.spec.ts
  apis/api-media/src/schema/video/video.ts
  apis/api-media/src/schema/videoVariant/videoVariant.spec.ts
  apis/api-media/src/workers/crowdin/importers/videoTitles/videoTitles.spec.ts
  apps/arclight/project.json
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#6827 feat: add zoom on background image
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/FocalPoint/FocalPoint.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/ZoomImage/ZoomImage.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/ZoomImage/ZoomImage.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/ZoomImage/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/controls/PropertiesSlider.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/controls/index.ts
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.tsx
Labels: effort: 3, priority: soon, type: feat

#6828 feat: add journey theme model
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/db/schema.prisma
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys-modern/src/__generated__/pothos-types.ts
  apis/api-journeys/db/migrations/20250618225635_20250618225633/migration.sql
  apis/api-journeys/db/schema.prisma
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/app.module.ts
  apis/api-journeys/src/app/lib/casl/__generated__/prismaSubjects.ts
  apis/api-journeys/src/app/lib/casl/caslFactory/caslFactory.ts
  apis/api-journeys/src/app/modules/journey/journey.resolver.ts
  apis/api-journeys/src/app/modules/journeyTheme/journeyTheme.acl.ts
  apis/api-journeys/src/app/modules/journeyTheme/journeyTheme.graphql
  apis/api-journeys/src/app/modules/journeyTheme/journeyTheme.module.ts
  apis/api-journeys/src/app/modules/journeyTheme/journeyTheme.resolver.spec.ts
  apis/api-journeys/src/app/modules/journeyTheme/journeyTheme.resolver.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#6857 feat: add algolia index updates
  apis/api-media/src/schema/video/video.ts
  apis/api-media/src/schema/videoVariant/videoVariant.ts
  apis/api-media/src/workers/algolia/service/algoliaClient.ts
  apis/api-media/src/workers/algolia/service/algoliaVideoUpdate/algoliaVideoUpdate.spec.ts
  apis/api-media/src/workers/algolia/service/algoliaVideoUpdate/algoliaVideoUpdate.ts
  apis/api-media/src/workers/algolia/service/algoliaVideoUpdate/index.ts
  apis/api-media/src/workers/algolia/service/algoliaVideoVariantUpdate/algoliaVideoVariantUpdate.spec.ts
  apis/api-media/src/workers/algolia/service/algoliaVideoVariantUpdate/algoliaVideoVariantUpdate.ts
  apis/api-media/src/workers/algolia/service/algoliaVideoVariantUpdate/index.ts
  apis/api-media/src/workers/algolia/service/index.ts
  apis/api-media/src/workers/algolia/service/languages/getLanguages.ts
  apis/api-media/src/workers/algolia/service/languages/index.ts
  apis/api-media/src/workers/algolia/service/languages/languageLists.ts
Labels: on stage

#6807 fix: editorprovider set selected step and block ids on setstepsaction
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: type: fix

#6803 feat(nes-415): add AI context field to Journey templates
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/db/schema.prisma
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys-modern/src/workers/emailEvents/service/fetchEmailDetails.spec.ts
  apis/api-journeys-modern/src/workers/emailEvents/service/processUserIds.spec.ts
  apis/api-journeys-modern/src/workers/emailEvents/service/service.spec.ts
  apis/api-journeys/db/migrations/20250609214837_20250609214835/migration.sql
  apis/api-journeys/db/schema.prisma
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/host/host.resolver.spec.ts
  apis/api-journeys/src/app/modules/journey/journey.graphql
  apis/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apis/api-journeys/src/app/modules/journey/journey.resolver.ts
  apis/api-journeys/src/app/modules/journeyTheme/journeyTheme.resolver.spec.ts
  apis/api-journeys/src/app/modules/plausible/plausible.resolver.spec.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  prds/ai-powered-journey-personalization/NES-415-prd.md
Labels: on stage

#6870 fix: child create modal isnt closing
  apps/videos-admin/src/app/(dashboard)/videos/_VideoCreateForm/VideoCreateForm.tsx
Labels: on stage

#6804 chore: add shadcn
  apps/watch/src/components/Button/Button.tsx
  apps/watch/src/components/Button/index.ts
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/BibleQuotesCarousel/BibleQuotesCarouselHeader/BibleQuotesCarouselHeader.tsx
  apps/watch/src/components/Dialog/Dialog.tsx
  apps/watch/src/components/Dialog/index.ts
  apps/watch/src/libs/cn/cn.ts
  apps/watch/src/libs/cn/index.ts
  libs/locales/en/apps-watch.json
  package-lock.json
  package.json
Labels: effort: 3, priority: soon, type: feat, Chore

#6880 test: updated monitoring test to focus on verifying user login and dashboard visibility
  apps/journeys-admin-e2e/src/monitoring/journeys-admin.monitor.ts
Labels: type: test, effort: 1
