Repository JesusFilm/core, pull requests merged in 2025-08, with the labels that each got.

#7309 fix: remove deprecated prop for radio option
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/db/schema.prisma
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/__generated__/pothos-types.ts
  apis/api-journeys-modern/src/schema/block/radioOption/radioOption.ts
  apis/api-journeys/db/migrations/20250801020152_20250801020149/migration.sql
  apis/api-journeys/db/schema.prisma
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/block/block.service.spec.ts
  apis/api-journeys/src/app/modules/block/block.service.ts
  apis/api-journeys/src/app/modules/block/radioOption/radioOption.graphql
  apis/api-journeys/src/app/modules/block/radioOption/radioOption.resolver.spec.ts
  apis/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/journeys-admin/__generated__/BlockDuplicate.ts
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/BlockRestore.ts
  apps/journeys-admin/__generated__/CardCtaRestore.ts
  apps/journeys-admin/__generated__/CardFormRestore.ts
  apps/journeys-admin/__generated__/CardIntroRestore.ts
  apps/journeys-admin/__generated__/CardPollCreate.ts
  apps/journeys-admin/__generated__/CardPollRestore.ts
  apps/journeys-admin/__generated__/CardQuoteRestore.ts
  apps/journeys-admin/__generated__/GetAdminJourney.ts
  apps/journeys-admin/__generated__/GetAdminJourneyWithPlausibleToken.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/MenuBlockRestore.ts
  apps/journeys-admin/__generated__/RadioOptionBlockCreate.ts
  apps/journeys-admin/__generated__/RadioOptionFields.ts
  apps/journeys-admin/__generated__/RadioQuestionBlockCreate.ts
  apps/journeys-admin/__generated__/StepBlockRestoreFromAction.ts
  apps/journeys-admin/__generated__/StepBlockRestoreFromSocialPreview.ts
  apps/journeys-admin/__generated__/StepBlockRestoreFromStep.ts
  apps/journeys-admin/__generated__/StepDuplicate.ts
  apps/journeys-admin/__generated__/TextResponseWithButtonRestore.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/RadioOptionFields.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/GetJourney.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/RadioOptionFields.ts
  libs/journeys/ui/src/components/RadioOption/__generated__/RadioOptionFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
  libs/journeys/ui/src/libs/useJourneyQuery/__generated__/GetJourney.ts
  libs/shared/gql/src/__generated__/graphql-env.d.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#7326 refactor: n1 languages
  apis/api-languages/src/schema/continent/continent.ts
  apis/api-languages/src/schema/country/countries.spec.ts
  apis/api-languages/src/schema/country/country.mock.ts
  apis/api-languages/src/schema/country/country.spec.ts
  apis/api-languages/src/schema/country/country.ts
Labels: on stage

#7324 refactor: resolve n1 video variant fields #5
  apis/api-gateway/schema.graphql
  apis/api-media/schema.graphql
  apis/api-media/src/schema/language/language.spec.ts
  apis/api-media/src/schema/language/language.ts
  apis/api-media/src/schema/video/video.spec.ts
  apis/api-media/src/schema/video/videoSubtitle/index.ts
  apis/api-media/src/schema/video/videoSubtitle/videoSubtitle.ts
  apis/api-media/src/schema/videoVariant/videoVariant.spec.ts
  apis/api-media/src/schema/videoVariant/videoVariant.ts
  apis/api-media/src/schema/videoVariant/videoVariantDownload/index.ts
  apis/api-media/src/schema/videoVariant/videoVariantDownload/videoVariantDownload.ts
Labels: on stage

#7331 fix: subtitle redirect
  apps/videos-admin/src/app/(dashboard)/videos/[videoId]/editions/[editionId]/page.tsx
Labels: on stage

#7229 feat: implement Cloudflare image upload functionality in updateSimpleJourney
  apis/api-journeys-modern/src/schema/journey/simple/updateSimpleJourney.spec.ts
  apis/api-journeys-modern/src/schema/journey/simple/updateSimpleJourney.ts
  apis/api-journeys-modern/src/utils/generateBlurhashAndMetadataFromUrl/generateBlurhashAndMetadataFromUrl.spec.ts
  apis/api-journeys-modern/src/utils/generateBlurhashAndMetadataFromUrl/generateBlurhashAndMetadataFromUrl.ts
  apis/api-journeys-modern/src/utils/generateBlurhashAndMetadataFromUrl/index.ts
  apis/api-media/src/schema/cloudflare/image/image.ts
Labels: type: feat

#7349 chore: main yml nx cloud caching and updates
  .github/workflows/main.yml
  nx.json
Labels: on stage

#7330 feat: add better logging for arclight project (ENG-3083)
  apps/arclight/next-logger.config.js
  apps/arclight/project.json
  apps/arclight/src/lib/cache.ts
  apps/arclight/src/logger.ts
Labels: on stage

#7380 feat: add additional indexes to Language, LanguageName, CountryLangua…
  apis/api-languages/db/migrations/20250807215708_20250807215707/migration.sql
  apis/api-languages/db/schema.prisma
Labels: on stage

#7392 chore: remove arclight canary
  workers/arclight-canary/.gitignore
  workers/arclight-canary/README.md
  workers/arclight-canary/eslint.config.mjs
  workers/arclight-canary/package.json
  workers/arclight-canary/project.json
  workers/arclight-canary/src/assets/.gitkeep
  workers/arclight-canary/src/cloudflare-test.d.ts
  workers/arclight-canary/src/index.spec.ts
  workers/arclight-canary/src/index.ts
  workers/arclight-canary/tsconfig.app.json
  workers/arclight-canary/tsconfig.json
  workers/arclight-canary/tsconfig.spec.json
  workers/arclight-canary/vite.config.ts
  workers/arclight-canary/vitest.config.ts
  workers/arclight-canary/wrangler.toml
Labels: on stage

#7423 refactor: remove max resolution from videos-admin
  apps/videos-admin/src/app/(dashboard)/videos/[videoId]/audio/add/page.spec.tsx
  apps/videos-admin/src/app/(dashboard)/videos/[videoId]/audio/add/page.tsx
  apps/videos-admin/src/app/_UploadVideoVariantProvider/UploadVideoVariantProvider.spec.tsx
  apps/videos-admin/src/app/_UploadVideoVariantProvider/UploadVideoVariantProvider.tsx
Labels: on stage

#7429 fix: add rest
  .github/workflows/housekeeping-label-feature-pr.yml
Labels: type: fix, priority: soon

#7372 feat: e2e nx cloud caching
  .github/workflows/app-deploy.yml
Labels: on stage

#7457 refactor: prisma languages
  apis/api-languages/Dockerfile
  apis/api-languages/project.json
  apis/api-languages/src/lib/prisma.ts
  apis/api-languages/src/schema/builder.ts
  apis/api-languages/src/schema/continent/continent.ts
  apis/api-languages/src/schema/country/countries.spec.ts
  apis/api-languages/src/schema/country/country.spec.ts
  apis/api-languages/src/schema/country/country.ts
  apis/api-languages/src/schema/language/audioPreview/audioPreview.ts
  apis/api-languages/src/schema/language/language.mock.ts
  apis/api-languages/src/schema/language/language.spec.ts
  apis/api-languages/src/schema/language/language.ts
  apis/api-languages/src/schema/user/enums/languageRole.ts
  apis/api-languages/src/schema/user/user.spec.ts
  apis/api-languages/src/schema/user/user.ts
  apis/api-languages/src/scripts/data-import.spec.ts
  apis/api-languages/src/scripts/data-import.ts
  apis/api-languages/src/yoga.ts
  apis/api-languages/test/prismaMock.ts
  apps/docs/docs/03-basics/02-backend/04-databases.md
  libs/prisma/languages/.prisma-generate.env
  libs/prisma/languages/db/ERD.svg
  libs/prisma/languages/db/migrations/20230720001320_20230720001318/migration.sql
  libs/prisma/languages/db/migrations/20240510220947_20240510220946/migration.sql
  libs/prisma/languages/db/migrations/20240514002827_20240514002819/migration.sql
  libs/prisma/languages/db/migrations/20240611223847_20240611223846/migration.sql
  libs/prisma/languages/db/migrations/20240615005514_20240615005513/migration.sql
  libs/prisma/languages/db/migrations/20240712025324_20240712025322/migration.sql
  libs/prisma/languages/db/migrations/20240713034153_20240713034151/migration.sql
  libs/prisma/languages/db/migrations/20240726202219_20240726202217/migration.sql
  libs/prisma/languages/db/migrations/20240813204551_20240813204549/migration.sql
  libs/prisma/languages/db/migrations/20241007154348_20241007154347/migration.sql
  libs/prisma/languages/db/migrations/20241015182830_20241015182828/migration.sql
  libs/prisma/languages/db/migrations/20250101153845_add_unique_constraint_country_language/migration.sql
  libs/prisma/languages/db/migrations/20250213173156_20250213173153/migration.sql
  libs/prisma/languages/db/migrations/20250619152255_20250619152251/migration.sql
  libs/prisma/languages/db/migrations/20250807215708_20250807215707/migration.sql
  libs/prisma/languages/db/migrations/migration_lock.toml
  libs/prisma/languages/db/schema.prisma
  libs/prisma/languages/eslint.config.mjs
  libs/prisma/languages/project.json
  libs/prisma/languages/src/__generated__/languageSlugs.ts
  libs/prisma/languages/src/__generated__/pothos-types.ts
  libs/prisma/languages/src/client.ts
  libs/prisma/languages/tsconfig.json
  libs/prisma/languages/tsconfig.lib.json
  tsconfig.base.json
Labels: on stage

#7459 chore: disable e2e on stage push
  .github/workflows/app-deploy.yml
Labels: on stage

#7474 fix: audio language button in collections
  apps/watch/pages/watch/[part1]/[part2].tsx
  apps/watch/pages/watch/[part1]/[part2]/[part3].tsx
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.spec.tsx
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.stories.tsx
  apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.tsx
  apps/watch/src/components/LanguageSwitchDialog/AudioTrackSelect/AudioTrackSelect.spec.tsx
  apps/watch/src/components/LanguageSwitchDialog/AudioTrackSelect/AudioTrackSelect.tsx
  apps/watch/src/components/NewVideoContentPage/NewVideoContentPage.spec.tsx
  apps/watch/src/components/NewVideoContentPage/NewVideoContentPage.tsx
  apps/watch/src/components/Select/Select.tsx
  apps/watch/src/components/Select/index.ts
  apps/watch/src/components/VideoContainerPage/AudioLanguageSelect/AudioLanguageSelect.spec.tsx
  apps/watch/src/components/VideoContainerPage/AudioLanguageSelect/AudioLanguageSelect.tsx
  apps/watch/src/components/VideoContainerPage/AudioLanguageSelect/AudoLanguageSelectContent/AudoLanguageSelectContent.spec.tsx
  apps/watch/src/components/VideoContainerPage/AudioLanguageSelect/AudoLanguageSelectContent/AudoLanguageSelectContent.tsx
  apps/watch/src/components/VideoContainerPage/AudioLanguageSelect/AudoLanguageSelectContent/index.ts
  apps/watch/src/components/VideoContainerPage/AudioLanguageSelect/index.ts
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.spec.tsx
  apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.stories.tsx
  apps/watch/src/libs/useLanguagesSlugQuery/index.ts
  apps/watch/src/libs/useLanguagesSlugQuery/useLanguagesSlugQuery.mock.ts
  apps/watch/src/libs/useLanguagesSlugQuery/useLanguagesSlugQuery.spec.tsx
  apps/watch/src/libs/useLanguagesSlugQuery/useLanguagesSlugQuery.ts
  package-lock.json
  package.json
Labels: type: fix, priority: soon

#7518 fix: remove excessive caching in e2e
  .github/workflows/e2e-tests.yml
Labels: on stage

#7514 refactor: make refs nullable for next 15
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/useOnClickOutside/useOnClickOutside.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/useOnClickOutside/useOnClickOutside.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/utils/calculateDimensions/calculateDimensions.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Content.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/Message/Message.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/FocalPoint/utils/calculatePoint/calculatePoint.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromMux/MuxDetails/MuxDetails.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/YouTubeDetails/YouTubeDetails.tsx
  apps/videos-admin/src/app/(dashboard)/videos/[videoId]/audio/_VariantVideo/VariantVideo.tsx
  apps/watch/src/components/CollectionsPage/CollectionVideoPlayer/utils/useIsInViewport/useIsInViewport.spec.tsx
  apps/watch/src/components/CollectionsPage/CollectionVideoPlayer/utils/useIsInViewport/useIsInViewport.ts
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.tsx
Labels: on stage

#5378 chore: next 15
  apps/arclight/next-env.d.ts
  apps/arclight/next.config.js
  apps/arclight/src/app/videoPlayerUrl/page.tsx
  apps/journeys-admin/eslint.config.mjs
  apps/journeys-admin/next-env.d.ts
  apps/journeys-admin/next.config.js
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/pages/_document.tsx
  apps/journeys-admin/setupTests.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CardWrapper/CardWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CardWrapper/CardWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoList/VideoList.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetails/JourneyDetails.stories.tsx
  apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.spec.tsx
  apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserNavigation.spec.tsx
  apps/journeys-admin/src/components/Team/CustomDomainDialog/DNSConfigSection/DNSConfigSection.spec.tsx
  apps/journeys-admin/src/components/Team/CustomDomainDialog/DNSConfigSection/DNSConfigSection.tsx
  apps/journeys/next-env.d.ts
  apps/journeys/next.config.js
  apps/journeys/pages/_app.tsx
  apps/journeys/pages/_document.tsx
  apps/journeys/src/components/VideoWrapperPaused/VideoWrapperPaused.spec.tsx
  apps/videos-admin/next.config.js
  apps/videos-admin/src/app/(dashboard)/videos/[videoId]/_RestrictedDownloads/RestrictedDownloads.spec.tsx
  apps/videos-admin/src/app/(dashboard)/videos/[videoId]/_RestrictedViews/RestrictedViews.spec.tsx
  apps/videos-admin/src/app/layout.tsx
  apps/videos-admin/src/libs/apollo/apolloClient.ts
  apps/videos-admin/src/libs/auth/getUser.ts
  apps/watch/next.config.js
  apps/watch/pages/_app.tsx
  apps/watch/pages/_document.tsx
  apps/watch/pages/watch/[part1]/[part2].tsx
  libs/journeys/ui/src/components/CardWrapper/CardWrapper.spec.tsx
  libs/journeys/ui/src/components/CardWrapper/CardWrapper.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/VideoWrapper/VideoWrapper.spec.tsx
  libs/shared/ui/src/libs/createEmotionCache/createEmotionCache.ts
  package-lock.json
  package.json
Labels: on stage

#7526 feat: add react compiler
  apps/arclight/next.config.js
  apps/journeys-admin/next.config.js
  apps/journeys/next.config.js
  apps/short-links/next-env.d.ts
  apps/short-links/tsconfig.json
  apps/videos-admin/next-env.d.ts
  apps/videos-admin/next.config.js
  apps/watch-modern/next-env.d.ts
  apps/watch-modern/next.config.mjs
  apps/watch/next-env.d.ts
  apps/watch/next.config.js
  package-lock.json
  package.json
Labels: on stage

#7556 feat: update Playwright configuration and add smoke test target
  .github/workflows/e2e-tests.yml
  apps/journeys-admin-e2e/playwright.config.ts
  apps/journeys-admin-e2e/project.json
  apps/journeys-admin-e2e/src/fixtures/authenticated.ts
  apps/journeys-admin-e2e/src/framework/helpers.ts
  apps/journeys-admin-e2e/src/global-setup.ts
  apps/journeys-admin-e2e/src/smoke/create-journey.spec.ts
  apps/journeys-admin-e2e/src/smoke/login.spec.ts
Labels: on stage
