Repository JesusFilm/core, pull requests merged in 2025-01, with the labels that each got.

#4767 chore: api journeys migration
  apps/api-journeys/db/migrations/20241225003421_20241225003419/migration.sql
Labels: priority: soon, effort: 1, type: chore

#4777 fix: video-admin child Ids
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoChildren/VideoChildren.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoChildren/VideoChildren.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoChildren/VideoChildren.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
Labels: priority: 2day, effort: 2, type: fix

#4772 feat: arclight e2e media languages
  apps/arclight-e2e/src/e2e/media-languages/media-language.spec.ts
  apps/arclight-e2e/src/e2e/media-languages/media-languages.spec.ts
  apps/arclight-e2e/src/utils/testData.json
  apps/arclight/src/app/v2/media-languages/[languageId]/route.ts
  apps/arclight/src/app/v2/media-languages/route.ts
Labels: effort: 2, priority: soon, type: feat

#4774 fix: e2e media languages backend
  apps/api-gateway/schema.graphql
  apps/api-languages/db/migrations/20250101153845_add_unique_constraint_country_language/migration.sql
  apps/api-languages/db/schema.prisma
  apps/api-languages/schema.graphql
  apps/api-languages/src/schema/language/language.ts
  apps/api-languages/src/workers/bigQuery/importers/countryLanguages/countryLanguages.ts
  apps/arclight-e2e/src/e2e/media-languages/media-language.spec.ts
  apps/arclight-e2e/src/e2e/media-languages/media-languages.spec.ts
  apps/arclight-e2e/src/utils/testData.json
  apps/arclight/src/app/v2/media-languages/[languageId]/route.ts
  apps/arclight/src/app/v2/media-languages/route.ts
Labels: type: fix, priority: soon, effort: 1

#4769 chore: deprecate video field
  apps/api-gateway/schema.graphql
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/video/video.graphql
  apps/journeys/__generated__/JourneyViewEventCreate.ts
Labels: priority: 2day, effort: 1, type: chore, on stage

#4778 chore: remove deprecated video image fields
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/video/video.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: 2day, effort: 1, type: chore, on stage

#4783 fix: mux background api
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#4758 chore: enforce nullability and cleanup
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/db/migrations/20241219013704_20241219013700/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/project.json
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/__generated__/pothos-types.ts
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/video/video.ts
  apps/api-media/src/schema/video/videoSubtitle/videoSubtitle.ts
  apps/api-media/src/schema/videoEdition/inputs/videoEditionCreate.ts
  apps/api-media/src/schema/videoEdition/videoEdition.spec.ts
  apps/api-media/src/schema/videoVariant/videoVariant.ts
  apps/api-media/src/workers/seed/migrations/editions/editions.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: soon, effort: 1, type: chore, on stage

#4780 feat: add token to default context
  apps/videos-admin/src/app/[locale]/_ApolloProvider/ApolloProvider.tsx
Labels: type: fix, priority: soon, effort: 1, Bug

#4796 feat: hide published label while data is loading
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
  apps/videos-admin/src/components/PublishedChip/PublishedChip.tsx
Labels: priority: soon, type: feat, effort: 1

#4776 feat: add published field to video variants
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/db/migrations/20250108001821_20250108001810/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/video/video.spec.ts
  apps/api-media/src/schema/video/video.ts
  apps/api-media/src/schema/videoVariant/inputs/index.ts
  apps/api-media/src/schema/videoVariant/inputs/videoVariantCreate.ts
  apps/api-media/src/schema/videoVariant/inputs/videoVariantFilter.ts
  apps/api-media/src/schema/videoVariant/inputs/videoVariantUpdate.ts
  apps/api-media/src/schema/videoVariant/videoVariant.spec.ts
  apps/api-media/src/schema/videoVariant/videoVariant.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: 2day, effort: 3, type: feat, on stage

#4809 fix: arclight e2e tests backend
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/db/migrations/20250101153845_add_unique_constraint_country_language/migration.sql
  apps/api-languages/db/schema.prisma
  apps/api-languages/schema.graphql
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-languages/src/schema/country/countries.spec.ts
  apps/api-languages/src/schema/country/country.spec.ts
  apps/api-languages/src/schema/country/country.ts
  apps/api-languages/src/schema/language/language.spec.ts
  apps/api-languages/src/schema/language/language.ts
  apps/api-languages/src/workers/bigQuery/importers/countries/countries.spec.ts
  apps/api-languages/src/workers/bigQuery/importers/countries/countries.ts
  apps/api-languages/src/workers/bigQuery/importers/countryLanguages/countryLanguages.spec.ts
  apps/api-languages/src/workers/bigQuery/importers/countryLanguages/countryLanguages.ts
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/arclight/src/app/v2/media-countries/[countryId]/route.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: type: fix, effort: 3, priority: soon, on stage

#3611 feat: add published field to videofilter (api)
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/video/inputs/videosFilter.ts
  apps/api-media/src/schema/video/lib/videosFilter/videosFilter.spec.ts
  apps/api-media/src/schema/video/lib/videosFilter/videosFilter.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  apps/watch/__generated__/globalTypes.ts
Labels: priority: soon, type: feat, effort: 1

#4811 fix: arclight e2e tests facade updates
  apps/arclight/src/app/v2/media-component-links/[mediaComponentId]/route.ts
  apps/arclight/src/app/v2/media-component-links/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/[languageId]/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/route.ts
  apps/arclight/src/app/v2/media-components/route.ts
  apps/arclight/src/app/v2/media-countries/[countryId]/route.ts
  apps/arclight/src/app/v2/media-countries/route.ts
  apps/arclight/src/app/v2/media-country-links/route.ts
  apps/arclight/src/app/v2/media-languages/[languageId]/route.ts
  apps/arclight/src/app/v2/media-languages/route.ts
  apps/arclight/src/app/v2/metadata-language-tags/[metadataLanguageTag]/route.ts
  apps/arclight/src/app/v2/metadata-language-tags/languages.ts
  apps/arclight/src/app/v2/metadata-language-tags/route.ts
  apps/arclight/src/app/v2/resources/route.ts
  apps/arclight/src/app/v2/taxonomies/[category]/route.ts
  apps/arclight/src/app/v2/taxonomies/route.ts
Labels: effort: 2, type: fix, priority: soon

#4818 fix: remove ache slug mapping
  apps/watch/src/libs/slugMap.ts
Labels: type: fix, priority: soon, effort: 1

#4823 chore: add cors origin env
  apps/api-media/infrastructure/locals.tf
Labels: priority: now, effort: 1, type: chore

#4260 feat: get utm campaign
  apps/journeys-admin/__generated__/GetJourneyAnalytics.ts
  apps/journeys/__generated__/GetJourneyAnalytics.ts
  apps/watch/__generated__/GetJourneyAnalytics.ts
  libs/journeys/ui/src/components/Step/Step.spec.tsx
  libs/journeys/ui/src/components/Step/Step.tsx
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/__generated__/GetJourneyAnalytics.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.spec.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/useJourneyAnalyticsQuery.mock.ts
  libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/useJourneyAnalyticsQuery.ts
Labels: priority: soon, type: feat, effort: 1

#4841 fix: bq ingest
  apps/api-media/src/workers/bigQuery/importers/videos/videos.spec.ts
  apps/api-media/src/workers/bigQuery/importers/videos/videos.ts
Labels: type: fix, priority: soon, effort: 1

#4849 fix: social media image not deleting
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageEdit/ImageEdit.tsx
Labels: type: fix, effort: 3, priority: soon

#4844 chore: make couldflare videos downloadable
  apps/api-media/db/migrations/20250110235646_20250110235644/migration.sql
  apps/api-media/db/schema.prisma
  apps/api-media/project.json
  apps/api-media/src/schema/cloudflare/video/video.spec.ts
  apps/api-media/src/workers/cli.ts
  apps/api-media/src/workers/cloudflare/config.ts
  apps/api-media/src/workers/cloudflare/index.ts
  apps/api-media/src/workers/cloudflare/service/index.ts
  apps/api-media/src/workers/cloudflare/service/service.spec.ts
  apps/api-media/src/workers/cloudflare/service/service.ts
  apps/api-media/src/workers/server.ts
Labels: priority: 2day, effort: 3, type: chore, on stage

#4879 chore: add mux file name to videoblock title
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/gql.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
  apps/api-journeys/src/app/modules/block/video/video.resolver.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/mux/video/video.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 2, priority: soon, type: chore, on stage

#4485 feat: api journeys qr codes
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/db/schema.prisma
  apps/api-journeys-modern/infrastructure/locals.tf
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys-modern/src/__generated__/pothos-types.ts
  apps/api-journeys/db/migrations/20241212192424_20241212192422/migration.sql
  apps/api-journeys/db/schema.prisma
  apps/api-journeys/infrastructure/locals.tf
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/gql.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/app.module.ts
  apps/api-journeys/src/app/lib/casl/__generated__/prismaSubjects.ts
  apps/api-journeys/src/app/lib/casl/caslFactory/caslFactory.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.module.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.resolver.spec.ts
  apps/api-journeys/src/app/modules/customDomain/customDomain.resolver.ts
  apps/api-journeys/src/app/modules/journey/journey.module.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.acl.spec.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.acl.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.graphql
  apps/api-journeys/src/app/modules/qrCode/qrCode.module.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.resolver.spec.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.resolver.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.service.spec.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.service.ts
  apps/api-journeys/src/app/modules/team/team.graphql
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 8, priority: soon, type: feat, on stage

#4887 fix: update the toolbar style, update journey flow background
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsOverlaySwitch/AnalyticsOverlaySwitch.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
  apps/journeys-admin/src/components/Editor/constants.ts
Labels: effort: 2, type: fix, priority: soon

#4869 fix: add kr to templates language filter
  apps/journeys-admin/pages/templates/index.tsx
  libs/journeys/ui/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
  libs/journeys/ui/src/components/TemplateGallery/HeaderAndLanguageFilter/LanguagesFilterPopper/LanguagesFilterPopper.tsx
  libs/journeys/ui/src/components/TemplateGallery/data.ts
Labels: type: fix, priority: soon, effort: 1

#4781 feat: e2e tests no qa
  apps/arclight-e2e/src/e2e/docs.spec.ts
  apps/arclight-e2e/src/e2e/media-component-links/[mediaComponentId]/index.spec.ts
  apps/arclight-e2e/src/e2e/media-component-links/index.spec.ts
  apps/arclight-e2e/src/e2e/media-components/[mediaComponentId]/index.spec.ts
  apps/arclight-e2e/src/e2e/media-components/[mediaComponentId]/languages/[languageId]/index.spec.ts
  apps/arclight-e2e/src/e2e/media-components/[mediaComponentId]/languages/index.spec.ts
  apps/arclight-e2e/src/e2e/media-components/index.spec.ts
  apps/arclight-e2e/src/e2e/media-countries/[mediaCountryId]/index.spec.ts
  apps/arclight-e2e/src/e2e/media-countries/index.spec.ts
  apps/arclight-e2e/src/e2e/media-country-links/index.spec.ts
  apps/arclight-e2e/src/e2e/media-languages/[languageId]/index.spec.ts
  apps/arclight-e2e/src/e2e/media-languages/index.spec.ts
  apps/arclight-e2e/src/e2e/metadata-language-tags/[metadataLanguageTag]/index.spec.ts
  apps/arclight-e2e/src/e2e/metadata-language-tags/index.spec.ts
  apps/arclight-e2e/src/e2e/resources/index.spec.ts
  apps/arclight-e2e/src/e2e/taxonomies/[categoryId]/index.spec.ts
  apps/arclight-e2e/src/e2e/taxonomies/index.spec.ts
  apps/arclight-e2e/src/framework/helpers.ts
  apps/arclight-e2e/src/utils/testData.ts
  apps/arclight-e2e/tsconfig.e2e.json
  apps/arclight/src/app/v2/media-component-links/[mediaComponentId]/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/route.ts
  apps/arclight/src/app/v2/media-components/route.ts
  apps/arclight/src/app/v2/media-countries/route.ts
Labels: effort: 2, priority: soon, type: feat

#4047 feat: drag to reorder blocks on canvas
  apps/journeys-admin-e2e/src/pages/card-level-actions.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/DragDropWrapper/DragDropWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/DragDropWrapper/DragDropWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/DragDropWrapper/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/DragItemWrapper/DragItemWrapper.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/DragItemWrapper/DragItemWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/DragItemWrapper/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/QuickControls.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.tsx
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
  libs/journeys/ui/src/components/Video/Video.tsx
  package-lock.json
  package.json
Labels: effort: 8, priority: soon, type: feat, chromatic, Feature

#4929 fix: fix missing mux video type for video templates
  libs/journeys/ui/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPlayer/TemplateVideoPlayer.tsx
  libs/journeys/ui/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPreview.tsx
Labels: effort: 2, type: fix, priority: soon, on stage

#4943 feat: videoplayer endpoint arclight
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/videoVariant/videoVariant.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/arclight/src/app/videoPlayerUrl/VideoPlayer.tsx
  apps/arclight/src/app/videoPlayerUrl/page.tsx
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  package-lock.json
  package.json
Labels: priority: soon, type: feat, effort: 1

#4934 fix: lang attribute for watch pages
  apps/watch/__generated__/GetVideoContainerPart2.ts
  apps/watch/__generated__/GetVideoContent.ts
  apps/watch/__generated__/GetVideoContentPart3.ts
  apps/watch/__generated__/GetVideosForTestData.ts
  apps/watch/__generated__/VideoContentFields.ts
  apps/watch/pages/_document.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
  apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
  apps/watch/src/components/Videos/__generated__/testData.ts
  apps/watch/src/libs/videoContentFields.ts
  apps/watch/src/libs/videoContext/VideoContext.spec.tsx
Labels: priority: soon, effort: 1, type: refactor

#4917 chore: remove mux migration code after migration
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys-modern/src/schema/block/index.ts
  apps/api-journeys-modern/src/schema/block/video/index.ts
  apps/api-journeys-modern/src/schema/block/video/video.ts
  apps/api-journeys-modern/src/schema/builder.ts
  apps/api-journeys-modern/src/schema/schema.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/project.json
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/workers/cli.ts
  apps/api-media/src/workers/cloudflare/config.ts
  apps/api-media/src/workers/cloudflare/index.ts
  apps/api-media/src/workers/cloudflare/service/index.ts
  apps/api-media/src/workers/cloudflare/service/service.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: 2day, effort: 1, type: chore

#5021 fix: core arclight dns
  infrastructure/environments/prod/main.tf
Labels: type: fix, priority: now, effort: 1

#4906 feat: initial seed
  apps/api-media/db/seed.ts
  apps/api-media/db/seeds/shortLinkDomain.ts
  apps/api-media/infrastructure/locals.tf
  apps/api-media/project.json
Labels: priority: soon, type: feat, effort: 1, on stage

#5031 fix: missing crowdin env
  apps/api-media/infrastructure/locals.tf
Labels: type: fix, priority: now, effort: 1

#5048 feat: increase timeout for slow endpoints
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/route.ts
  apps/arclight/src/app/v2/media-components/route.ts
  apps/arclight/src/app/v2/media-languages/route.ts
Labels: type: fix, priority: soon, effort: 1

#5063 revert: algolia
  package-lock.json
Labels: priority: now, effort: 1, type: revert

#5041 feat: add qr code edit dialog
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/ChangeButton/ChangeButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/ChangeButton/ChangeButton.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/ChangeButton/ChangeButton.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/ChangeButton/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/CodeDestination.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/CodeDestination.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/CodeDestination.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/CodeDestinationPopper/CodeDestinationPopper.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/CodeDestinationPopper/CodeDestinationPopper.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/CodeDestinationPopper/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/DownloadQrCode/DownloadQrCode.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/DownloadQrCode/DownloadQrCode.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/DownloadQrCode/DownloadQrCode.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/DownloadQrCode/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/QrCodeDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/QrCodeDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/QrCodeDialog.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/RedirectDialog/RedirectDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/RedirectDialog/RedirectDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/RedirectDialog/RedirectDialog.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/RedirectDialog/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/ScanCount/ScanCount.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/ScanCount/ScanCount.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/ScanCount/ScanCount.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/ScanCount/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.tsx
  libs/locales/en/apps-journeys-admin.json
  package-lock.json
  package.json
Labels: effort: 5, priority: soon, type: feat

#5071 feat: add to journey id
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/schema.graphql
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.graphql
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: now, type: feat, effort: 1, on stage

#5077 chore: remove unused tus-js-client
  package-lock.json
  package.json
Labels: priority: 2day, effort: 1, type: chore
