Repository JesusFilm/core, pull requests merged in 2025-09, with the labels that each got.

#7585 chore: multi step form styling refactor
  apps/journeys-admin/pages/templates/[journeyId].tsx
  apps/journeys-admin/pages/templates/[journeyId]/customize.tsx
  apps/journeys-admin/pages/templates/index.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/MultiStepForm.tsx
Labels: effort: 2, priority: soon, type: feat

#7622 fix: add from template id filter
  apis/api-gateway/schema.graphql
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/journey/journey.graphql
  apis/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apis/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
  libs/shared/gql/src/__generated__/graphql-env.d.ts
Labels: type: fix, priority: soon, on stage

#7583 chore: add styling to progress stepper
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/MultiStepForm.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/ProgressStepper/ProgressStepper.spec.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/ProgressStepper/ProgressStepper.tsx
Labels: effort: 2, priority: soon, type: chore

#7607 feat: add playlist management functionality to media API
  apis/api-gateway/project.json
  apis/api-gateway/schema.graphql
  apis/api-media/schema.graphql
  apis/api-media/src/schema/builder.ts
  apis/api-media/src/schema/cloudflare/image/image.spec.ts
  apis/api-media/src/schema/mux/video/video.spec.ts
  apis/api-media/src/schema/playlist/index.ts
  apis/api-media/src/schema/playlist/inputs/playlistCreate.ts
  apis/api-media/src/schema/playlist/inputs/playlistUpdate.ts
  apis/api-media/src/schema/playlist/playlist.spec.ts
  apis/api-media/src/schema/playlist/playlist.ts
  apis/api-media/src/schema/playlist/playlistItem.spec.ts
  apis/api-media/src/schema/playlist/playlistItem.ts
  apis/api-media/src/schema/schema.ts
  apis/api-media/src/schema/segmind/segmind.spec.ts
  apis/api-media/src/schema/shortLink/shortLink.spec.ts
  apis/api-media/src/schema/shortLink/shortLinkDomain/shortLinkDomain.spec.ts
  apis/api-media/src/schema/user/index.ts
  apis/api-media/src/schema/user/user.ts
  apis/api-media/src/schema/video/video.spec.ts
  apis/api-media/src/schema/videoVariant/videoVariant.spec.ts
  apis/api-media/src/schema/videoVariant/videoVariant.ts
  apis/api-media/src/yoga.ts
  libs/prisma/media/db/migrations/20250903044733_20250903044731/migration.sql
  libs/prisma/media/db/migrations/20250905033045_20250905033038/migration.sql
  libs/prisma/media/db/migrations/20250905033117_20250905033115/migration.sql
  libs/prisma/media/db/schema.prisma
  libs/prisma/media/src/__generated__/pothos-types.ts
  libs/shared/gql/src/__generated__/graphql-env.d.ts
Labels: on stage

#7595 refactor: updatevideoblock modern migration
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/lib/auth/ability.ts
  apis/api-journeys-modern/src/lib/auth/fetchBlockWithJourneyAcl.spec.ts
  apis/api-journeys-modern/src/lib/auth/fetchBlockWithJourneyAcl.ts
  apis/api-journeys-modern/src/lib/auth/fetchJourneyWithAclIncludes.spec.ts
  apis/api-journeys-modern/src/lib/auth/fetchJourneyWithAclIncludes.ts
  apis/api-journeys-modern/src/schema/block/getNextParentOrder.spec.ts
  apis/api-journeys-modern/src/schema/block/getNextParentOrder.ts
  apis/api-journeys-modern/src/schema/block/service.ts
  apis/api-journeys-modern/src/schema/block/video/index.ts
  apis/api-journeys-modern/src/schema/block/video/service.spec.ts
  apis/api-journeys-modern/src/schema/block/video/service.ts
  apis/api-journeys-modern/src/schema/block/video/videoBlockCreate.mutation.spec.ts
  apis/api-journeys-modern/src/schema/block/video/videoBlockCreate.mutation.ts
  apis/api-journeys-modern/src/schema/block/video/videoBlockUpdate.mutation.spec.ts
  apis/api-journeys-modern/src/schema/block/video/videoBlockUpdate.mutation.ts
  apis/api-journeys-modern/src/schema/journey/journey.acl.ts
Labels: on stage

#3128 feat: show step block node fab on hover
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DeleteBlock/DeleteBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/DuplicateStep/DuplicateStep.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/DuplicateStep/DuplicateStep.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/StepBlockNodeMenu.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/StepBlockNodeMenu.tsx
  apps/journeys-admin/src/libs/TestEditorState/TestEditorState.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
  libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Labels: priority: soon, type: feat, effort: 1

#7666 fix: retain parent step id on journey duplicate
  apis/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apis/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: effort: 1

#7663 feat: style done screen and add share functionality
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/DoneScreen/DoneScreen.spec.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/DoneScreen/DoneScreen.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/SocialScreen/SocialScreen.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/TextScreen/TextScreen.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: soon, type: feat

#7677 fix: link screen cards
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/MultiStepForm.spec.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/MultiStepForm.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/LinksScreen/CardsPreview/CardsPreview.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/LinksScreen/LinksScreen.spec.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/LinksScreen/LinksScreen.tsx
Labels: effort: 1

#7668 feat: add styling to link screen
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/LinksScreen/CardsPreview/CardsPreview.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/LinksScreen/LinksForm/LinksForm.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/LinksScreen/LinksScreen.spec.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/LinksScreen/LinksScreen.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/SocialScreen/SocialScreen.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/TextScreen/TextScreen.tsx
  apps/journeys-admin/src/components/TemplateCustomization/utils/sharedStyles/index.ts
  apps/journeys-admin/src/components/TemplateCustomization/utils/sharedStyles/sharedStyles.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: soon, type: feat

#7681 fix: default text for done screen
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/DoneScreen/DoneScreen.spec.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/DoneScreen/DoneScreen.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/DoneScreen/ShareDrawer/ShareDrawer.spec.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/DoneScreen/ShareDrawer/ShareDrawer.tsx
Labels: effort: 1

#7680 fix: playlist item ordering system
  .github/workflows/autofix.ci.yml
  apis/api-gateway/schema.graphql
  apis/api-media/schema.graphql
  apis/api-media/src/schema/playlist/playlistItem.spec.ts
  apis/api-media/src/schema/playlist/playlistItem.ts
  libs/prisma/media/db/migrations/20250916005356_20250916005354/migration.sql
  libs/prisma/media/db/schema.prisma
  libs/shared/gql/src/__generated__/graphql-env.d.ts
  validate-branch-name.config.js
Labels: on stage

#7682 feat: language screen styling
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/LanguageScreen/JourneyCustomizeTeamSelect/JourneyCustomizeTeamSelect.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/LanguageScreen/LanguageScreen.spec.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/LanguageScreen/LanguageScreen.tsx
  libs/locales/en/journeys-ui.json
Labels: effort: 2, priority: soon, type: feat

#7679 feat: add showAssistant field to journey
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/schema/journey/inputs/journeyUpdateInput.ts
  apis/api-journeys-modern/src/schema/journey/journey.ts
  apis/api-journeys-modern/src/workers/emailEvents/service/fetchEmailDetails.spec.ts
  apis/api-journeys-modern/src/workers/emailEvents/service/processUserIds.spec.ts
  apis/api-journeys-modern/src/workers/emailEvents/service/service.spec.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/host/host.resolver.spec.ts
  apis/api-journeys/src/app/modules/journey/journey.graphql
  apis/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apis/api-journeys/src/app/modules/journeyCustomizationField/journeyCustomizationField.resolver.spec.ts
  apis/api-journeys/src/app/modules/journeyTheme/journeyTheme.resolver.spec.ts
  apis/api-journeys/src/app/modules/plausible/plausible.resolver.spec.ts
  libs/prisma/journeys/db/migrations/20250915230856_20250915230854/migration.sql
  libs/prisma/journeys/db/schema.prisma
  libs/shared/gql/src/__generated__/graphql-env.d.ts
Labels: on stage

#7693 feat: truncate long journey descriptions to one line on the done screen
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/DoneScreen/DoneScreen.tsx
Labels: priority: soon, type: feat, effort: 1

#7731 fix: hide edit manually button from language screen
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/MultiStepForm.spec.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/MultiStepForm.tsx
Labels: type: fix, priority: soon, effort: 1, Bug

#7730 fix: show resolved customizable text for response field properties in the editor
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Hint/Hint.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Hint/Hint.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Label/Label.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Label/Label.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Placeholder/Placeholder.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Placeholder/Placeholder.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
  libs/journeys/ui/src/components/TextResponse/utils/getTextResponseValues/getTextResponseValues.spec.ts
  libs/journeys/ui/src/components/TextResponse/utils/getTextResponseValues/getTextResponseValues.ts
Labels: type: fix, effort: 3, priority: soon, Bug

#7760 feat(watch): enrich section video slides with video snapshots
  apps/watch/src/components/SectionVideoCarousel/SectionVideoCarousel.spec.tsx
  apps/watch/src/components/SectionVideoCarousel/SectionVideoCarousel.tsx
  apps/watch/src/components/SectionVideoCarousel/useSectionVideoCollectionCarouselContent.ts
  apps/watch/src/components/SectionVideoGrid/SectionVideoGrid.spec.tsx
  apps/watch/src/components/SectionVideoGrid/SectionVideoGrid.tsx
  prds/watch/work.md
Labels: codex

#7761 refactor: update SectionVideoCarousel import for collection showcase
  apps/watch/src/components/CollectionsPage/collectionShowcaseConfig.ts
Labels: codex

#7741 fix: disable dragging of window when analytics overlay is on
  apps/journeys-admin/src/components/Editor/Fab/Fab.spec.tsx
  apps/journeys-admin/src/components/Editor/Fab/Fab.tsx
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
Labels: Bug

#7702 feat: contact action
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/schema/action/phoneAction/blockUpdatePhoneAction.mutation.spec.ts
  apis/api-journeys-modern/src/schema/action/phoneAction/blockUpdatePhoneAction.mutation.ts
  apis/api-journeys-modern/src/schema/action/phoneAction/enums/contactActionType.ts
  apis/api-journeys-modern/src/schema/action/phoneAction/inputs/phoneActionInput.ts
  apis/api-journeys-modern/src/schema/action/phoneAction/phoneAction.ts
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/action/action.graphql
  apis/api-journeys/src/app/modules/action/action.resolver.spec.ts
  apis/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  libs/prisma/journeys/db/migrations/20250917232944_20250917232943/migration.sql
  libs/prisma/journeys/db/schema.prisma
  libs/shared/gql/src/__generated__/graphql-env.d.ts
Labels: on stage

#7771 fix: enforce break-word wrapping style for text blocks
  libs/journeys/ui/src/components/Typography/Typography.tsx
Labels: type: fix, priority: now, effort: 1

#7513 feat: add caching to media component endpoints
  .github/workflows/app-deploy.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/ecs-frontend-deploy-prod-worker.yml
  .github/workflows/ecs-frontend-deploy-stage-worker.yml
  .github/workflows/ecs-frontend-deploy-stage.yml
  apps/arclight-e2e/src/e2e/media-component-links/index.spec.ts
  apps/arclight-e2e/src/e2e/media-components/[mediaComponentId]/languages/[languageId]/index.spec.ts
  apps/arclight-e2e/src/e2e/media-components/[mediaComponentId]/languages/index.spec.ts
  apps/arclight/Dockerfile
  apps/arclight/infrastructure/locals.tf
  apps/arclight/src/app/[...route]/_dh/index.ts
  apps/arclight/src/app/[...route]/_dl/index.ts
  apps/arclight/src/app/v2/[...route]/_media-component-links/[mediaComponentId]/index.ts
  apps/arclight/src/app/v2/[...route]/_media-components/[mediaComponentId]/index.ts
  apps/arclight/src/app/v2/[...route]/_media-components/[mediaComponentId]/languages/[languageId]/index.ts
  apps/arclight/src/app/v2/[...route]/_media-components/[mediaComponentId]/languages/index.ts
  apps/arclight/src/app/v2/[...route]/_media-components/index.ts
  apps/arclight/src/lib/downloadHelpers.ts
  apps/arclight/src/lib/getLanguageIdsFromTags.ts
  apps/arclight/src/lib/imageHelper.ts
  apps/arclight/src/lib/stringsForArclight/webEmbedStrings.ts
Labels: on stage

#7792 feat: re-style progress stepper look and padding
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/MultiStepForm.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/ProgressStepper/ProgressStepper.tsx
Labels: effort: 2, priority: soon, type: feat

#7865 fix: disable copy button for non original templates
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/MultiStepForm.tsx
  libs/journeys/ui/src/components/CopyToTeamDialog/CopyToTeamDialog.spec.tsx
  libs/journeys/ui/src/components/CopyToTeamDialog/CopyToTeamDialog.tsx
  libs/journeys/ui/src/components/TranslationDialogWrapper/TranslationDialogWrapper.tsx
  libs/locales/en/libs-journeys-ui.json
Labels: type: fix

#7880 feat(watch): add skip control to hero preview
  apps/watch/src/components/NewVideoContentPage/VideoContentHero/HeroVideo/HeroVideo.tsx
  apps/watch/src/components/NewVideoContentPage/VideoContentHero/VideoContentHero.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoTitle/VideoTitle.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoTitle/VideoTitle.tsx
  apps/watch/src/components/WatchHomePage/WatchHero.tsx
  apps/watch/src/components/WatchHomePage/WatchHomePage.tsx
  apps/watch/src/components/WatchHomePage/useWatchHeroCarousel.spec.tsx
  apps/watch/src/components/WatchHomePage/useWatchHeroCarousel.ts
  libs/locales/am-ET/apps-watch.json
  libs/locales/ar-SA/apps-watch.json
  libs/locales/bn-BD/apps-watch.json
  libs/locales/de-DE/apps-watch.json
  libs/locales/en/apps-watch.json
  libs/locales/es-ES/apps-watch.json
  libs/locales/fr-FR/apps-watch.json
  libs/locales/hi-IN/apps-watch.json
  libs/locales/id-ID/apps-watch.json
  libs/locales/ja-JP/apps-watch.json
  libs/locales/ko-KR/apps-watch.json
  libs/locales/my-MM/apps-watch.json
  libs/locales/ne-NP/apps-watch.json
  libs/locales/pt-BR/apps-watch.json
  libs/locales/ru-RU/apps-watch.json
  libs/locales/th-TH/apps-watch.json
  libs/locales/tl-PH/apps-watch.json
  libs/locales/tr-TR/apps-watch.json
  libs/locales/ur-PK/apps-watch.json
  libs/locales/vi-VN/apps-watch.json
  libs/locales/zh-Hans-CN/apps-watch.json
  libs/locales/zh-Hant-TW/apps-watch.json
  prds/watch/work.md
Labels: codex

#7877 feat(watch): add numbered mode to video grid
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideoGrid/VideoGrid.spec.tsx
  apps/watch/src/components/VideoGrid/VideoGrid.tsx
  prds/watch/work.md
Labels: codex
