Repository JesusFilm/core, pull requests merged in 2025-04, with the labels that each got.

#5749 feat(api-journeys-modern): exporting history
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/db/schema.prisma
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys-modern/src/__generated__/pothos-types.ts
  apis/api-journeys-modern/src/lib/graphql/subgraphGraphql.ts
  apis/api-journeys-modern/src/schema/builder.ts
  apis/api-journeys-modern/src/schema/journeyEventsExportLog/enums/eventType.ts
  apis/api-journeys-modern/src/schema/journeyEventsExportLog/enums/index.ts
  apis/api-journeys-modern/src/schema/journeyEventsExportLog/index.ts
  apis/api-journeys-modern/src/schema/journeyEventsExportLog/inputs/JourneyEventsExportLogInput.ts
  apis/api-journeys-modern/src/schema/journeyEventsExportLog/inputs/index.ts
  apis/api-journeys-modern/src/schema/journeyEventsExportLog/journeyEventsExportLog.spec.ts
  apis/api-journeys-modern/src/schema/journeyEventsExportLog/journeyEventsExportLog.ts
  apis/api-journeys-modern/src/schema/schema.ts
  apis/api-journeys/db/migrations/20250318223633_20250318223628/migration.sql
  apis/api-journeys/db/migrations/20250327010915_20250327010913/migration.sql
  apis/api-journeys/db/schema.prisma
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/lib/casl/__generated__/prismaSubjects.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: soon, type: feat, effort: 1

#5879 feat: add phone as a type for Text Input
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Type/Type.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Type/Type.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: soon, type: feat, on stage

#5887 feat: export data button
  apps/journeys-admin/__generated__/CreateEventsExportLog.ts
  apps/journeys-admin/__generated__/GetJourneyEvents.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.tsx
  libs/locales/en/apps-journeys-admin.json
  package-lock.json
  package.json
Labels: effort: 2, priority: soon, type: feat

#6023 fix(watch): update about section
  apps/watch/src/components/Header/Header.spec.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.spec.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/headerLinks.ts
Labels: type: fix, priority: now, effort: 1, on stage

#5949 feat: force submitEnabled field of button block to false when duplicated
  apis/api-journeys/src/app/modules/block/block.resolver.spec.ts
  apis/api-journeys/src/app/modules/block/block.resolver.ts
  apis/api-journeys/src/app/modules/block/block.service.spec.ts
  apis/api-journeys/src/app/modules/block/block.service.ts
  apis/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apis/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: effort: 3, type: feat

#6006 fix: prevent user from setting text input label to be only whitespace
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Label/Label.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/Label/Label.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.spec.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
Labels: effort: 2, type: fix, priority: soon

#6058 fix: remove succesful submission notification
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
Labels: type: fix, priority: soon, effort: 1

#6010 feat: journey events export loading bar api
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.graphql
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.resolver.spec.ts
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.resolver.ts
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.service.spec.ts
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.service.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: soon, type: feat, effort: 1, on stage

#6064 fix: append html to routes
  apps/watch/pages/watch/easter.html/english.html/index.tsx
  apps/watch/pages/watch/easter.html/french.html/index.tsx
  apps/watch/pages/watch/easter.html/index.tsx
  apps/watch/pages/watch/easter.html/portuguese-brazil.html/index.tsx
  apps/watch/pages/watch/easter.html/russian.html/index.tsx
  apps/watch/pages/watch/easter.html/spanish-latin-american.html/index.tsx
Labels: type: fix, priority: now, effort: 1, on stage

#6070 fix: scroll navigation
  apps/watch/pages/_document.tsx
  apps/watch/public/watch/global.css
  apps/watch/src/components/CollectionsPage/CollectionVideoContentCarousel/CollectionVideoContentCarousel.spec.tsx
  apps/watch/src/components/CollectionsPage/CollectionVideoContentCarousel/CollectionVideoContentCarousel.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/CollectionsVideoContent.tsx
  apps/watch/src/components/CollectionsPage/OtherCollectionsCarousel/OtherCollectionsCarousel.spec.tsx
  apps/watch/src/components/CollectionsPage/OtherCollectionsCarousel/OtherCollectionsCarousel.tsx
  apps/watch/src/components/CollectionsPage/languages/en/CollectionsPage.tsx
  apps/watch/src/components/CollectionsPage/languages/es/CollectionsPage.tsx
  apps/watch/src/components/CollectionsPage/languages/fr/CollectionsPage.tsx
  apps/watch/src/components/CollectionsPage/languages/pt/CollectionsPage.tsx
  apps/watch/src/components/CollectionsPage/languages/ru/CollectionsPage.tsx
Labels: type: fix, priority: soon, effort: 1

#6207 fix: swap icons around
  apps/watch/src/components/CollectionsPage/ContainerHero/ContainerHeroMuteButton/ContainerHeroMuteButton.spec.tsx
  apps/watch/src/components/CollectionsPage/ContainerHero/ContainerHeroMuteButton/ContainerHeroMuteButton.tsx
Labels: type: fix, priority: soon, effort: 1

#6209 fix: fix android autoplay
  apps/watch/src/components/CollectionsPage/ContainerHero/ContainerHero.spec.tsx
  apps/watch/src/components/CollectionsPage/ContainerHero/ContainerHero.tsx
  apps/watch/src/components/CollectionsPage/ContainerHeroVideo/ContainerHeroVideo.spec.tsx
  apps/watch/src/components/CollectionsPage/ContainerHeroVideo/ContainerHeroVideo.tsx
Labels: type: fix, priority: soon, effort: 1

#6206 fix: easter date block open on sm up
  apps/watch/src/components/CollectionsPage/CollectionIntroText/EasterDates/EasterDates.tsx
Labels: type: fix, priority: soon, effort: 1

#6205 fix: change intro text
  apps/watch/src/components/CollectionsPage/CollectionIntroText/CollectionIntroText.tsx
  apps/watch/src/components/CollectionsPage/languages/en/CollectionsPage.tsx
  apps/watch/src/components/CollectionsPage/languages/es/CollectionsPage.tsx
  apps/watch/src/components/CollectionsPage/languages/fr/CollectionsPage.tsx
  apps/watch/src/components/CollectionsPage/languages/pt/CollectionsPage.tsx
  apps/watch/src/components/CollectionsPage/languages/ru/CollectionsPage.tsx
Labels: type: fix, priority: soon, effort: 1

#5985 feat: link text input typography label to analytics
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
  libs/journeys/ui/src/components/Card/utils/getTextResponseBlocks/getTextResponseBlocks.ts
  libs/journeys/ui/src/libs/getTextResponseLabel/getTextResponseLabel.spec.ts
  libs/journeys/ui/src/libs/getTextResponseLabel/getTextResponseLabel.ts
  libs/journeys/ui/src/libs/getTextResponseLabel/index.ts
Labels: effort: 3, priority: soon, type: feat

#5975 refactor: journey events performance improvements
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/db/migrations/20250407221425_20250407221420/migration.sql
  apis/api-journeys/db/migrations/migration_lock.toml
  apis/api-journeys/db/schema.prisma
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/event/event.acl.spec.ts
  apis/api-journeys/src/app/modules/event/event.acl.ts
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.graphql
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.resolver.spec.ts
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.resolver.ts
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.service.spec.ts
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.service.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#6213 refactor: remove with from filter labels
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, effort: 1, type: refactor

#6230 fix(journeys-admin): clear all button not working on desktop
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorToolbar/VisitorToolbar.tsx
Labels: type: fix, priority: soon, effort: 1

#6247 chore: update get text response label index file
  libs/journeys/ui/src/libs/getTextResponseLabel/index.ts
Labels: priority: soon, effort: 1, type: chore

#6235 fix: video offset
  apps/watch/src/components/CollectionsPage/CollectionVideoPlayer/CollectionVideoPlayer.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/CollectionsVideoContent.tsx
  apps/watch/src/components/CollectionsPage/languages/en/CollectionsPage.tsx
Labels: type: fix, priority: soon, effort: 1

#6248 fix: add ga4 to button events
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/BibleQuotesCarousel/BibleQuotesCarousel.spec.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/BibleQuotesCarousel/BibleQuotesCarousel.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/BibleQuotesCarousel/BibleQuotesCarouselHeader/BibleQuotesCarouselHeader.spec.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/BibleQuotesCarousel/BibleQuotesCarouselHeader/BibleQuotesCarouselHeader.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/CollectionsVideoContent.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/Questions/Questions.spec.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/Questions/Questions.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/QuizButton/QuizButton.spec.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/QuizButton/QuizButton.tsx
Labels: type: fix, priority: soon, effort: 1

#6249 fix: add ga4 to easter video player
  apps/watch/src/components/CollectionsPage/CollectionVideoPlayer/CollectionVideoPlayer.tsx
Labels: type: fix, priority: soon, effort: 1

#6254 fix: add accessibility and seo
  apps/watch/next.config.js
  apps/watch/pages/watch/easter.html/english.html/index.tsx
  apps/watch/pages/watch/easter.html/french.html/index.tsx
  apps/watch/pages/watch/easter.html/index.tsx
  apps/watch/pages/watch/easter.html/portuguese-brazil.html/index.tsx
  apps/watch/pages/watch/easter.html/russian.html/index.tsx
  apps/watch/pages/watch/easter.html/spanish-latin-american.html/index.tsx
  apps/watch/src/components/CollectionsPage/CollectionNavigationCarousel/CollectionNavigationCarousel.tsx
  apps/watch/src/components/CollectionsPage/CollectionVideoContentCarousel/CollectionVideoContentCarousel.tsx
  apps/watch/src/components/CollectionsPage/CollectionVideoPlayer/CollectionVideoPlayer.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/BibleQuotesCarousel/BibleQuotesCarousel.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/BibleQuotesCarousel/BibleQuotesCarouselHeader/BibleQuotesCarouselHeader.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/Questions/Questions.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/QuizButton/QuizButton.tsx
  apps/watch/src/components/CollectionsPage/OtherCollectionsCarousel/OtherCollectionsCarousel.tsx
Labels: type: fix, priority: soon, effort: 1

#6259 chore: remove deprecated journey event fields
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.graphql
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.service.spec.ts
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.service.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/GetJourneyEvents.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#6264 fix: tests on form field feature branch
  libs/journeys/ui/src/components/TextResponse/TextResponse.spec.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
Labels: type: fix, priority: now, effort: 1

#6271 fix: add ga to autoplay start
  apps/watch/src/components/CollectionsPage/CollectionVideoPlayer/CollectionVideoPlayer.tsx
Labels: type: fix, priority: soon, effort: 1

#6280 feat: add 'order' field to VideoStudyQuestion type across multiple sc…
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/video/videoStudyQuestion/videoStudyQuestion.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#6283 feat: move text response type field to be below hint textbox
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/TextResponseFields.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/TextResponseFields.tsx
Labels: priority: soon, type: feat, effort: 1

#6281 chore: replace subscribe blocks from nua9 journey seed
  apis/api-journeys/db/seeds/nua9.ts
Labels: effort: 2, priority: soon, type: chore

#6260 feat: default text response block minRows value to 1
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/MinRows/MinRows.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponseFields/MinRows/MinRows.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
Labels: effort: 2, priority: soon, type: feat

#6285 fix: disable button submit on admin
  libs/journeys/ui/src/components/Button/Button.spec.tsx
  libs/journeys/ui/src/components/Button/Button.tsx
Labels: effort: 2, type: fix, priority: soon, effort: 1

#6293 fix: hide sign up from add block
  apps/journeys-admin-e2e/src/e2e/discover/card-level-actions.spec.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.tsx
Labels: type: fix, priority: now, effort: 1

#6291 feat: remove whitespaces in text response placeholder
  libs/journeys/ui/src/components/TextResponse/TextResponse.spec.tsx
  libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
Labels: priority: soon, type: feat, effort: 1

#4863 fix: revalidate journey of social media image change
  apps/journeys-admin/pages/api/revalidate.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageEdit/ImageEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/DescriptionEdit/DescriptionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/DescriptionEdit/DescriptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/TitleEdit/TitleEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/TitleEdit/TitleEdit.tsx
  apps/journeys-admin/src/libs/revalidateJourney/index.ts
  apps/journeys-admin/src/libs/revalidateJourney/revalidateJourney.spec.ts
  apps/journeys-admin/src/libs/revalidateJourney/revalidateJourney.ts
  apps/journeys/pages/api/revalidate.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#6315 fix: remove navigation by clicking card
  apps/journeys/src/components/Conductor/HotkeyNavigation/HotkeyNavigation.tsx
  apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
  apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/Card.tsx
Labels: type: fix

#6059 feat: export button for mobile
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/ExportEventsButton/ExportEventsButton.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/ExportEventsButton/ExportEventsButton.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/ExportEventsButton/ExportEventsButton.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/ExportEventsButton/index.ts
Labels: effort: 2, priority: soon, type: feat

#5896 test: add more tests, upgrade playwright and do full parallel
  apps/journeys-admin-e2e/playwright.config.ts
  apps/journeys-admin-e2e/src/e2e/discover/card-level-actions.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/journey-level-actions.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/teams.spec.ts
  apps/journeys-admin-e2e/src/e2e/lighthouse/homepage.spec.ts
  apps/journeys-admin-e2e/src/framework/helpers.ts
  apps/journeys-admin-e2e/src/pages/card-level-actions.ts
  apps/journeys-admin-e2e/src/pages/journey-level-actions-page.ts
  apps/journeys-admin-e2e/src/pages/journey-page.ts
  apps/journeys-admin-e2e/src/pages/teams-page.ts
  apps/journeys-admin-e2e/src/utils/testData.json
  package-lock.json
  package.json
Labels: type: test, effort: 13, priority: soon

#6222 fix: videos admin mux location
  apis/api-gateway/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-media/schema.graphql
  apis/api-media/src/schema/mux/video/service.ts
  apis/api-media/src/schema/mux/video/video.spec.ts
  apis/api-media/src/schema/mux/video/video.ts
Labels: on stage

#6329 fix: remove stack of gray cards
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/EmbedJourneyDialog/EmbedCardPreview/EmbedCardPreview.tsx
  apps/journeys/src/components/EmbeddedPreview/ClickableCard/ClickableCard.tsx
Labels: type: fix, priority: soon, effort: 1

#6318 fix: journey background video playback on safari
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
  libs/shared/ui/src/libs/defaultVideoJsOptions/defaultVideoJsOptions.spec.ts
  libs/shared/ui/src/libs/defaultVideoJsOptions/defaultVideoJsOptions.ts
  libs/shared/ui/src/libs/defaultVideoJsOptions/index.ts
Labels: type: fix, effort: 3, priority: soon

#6313 feat: add caching and compression to arclight
  apps/arclight/infrastructure/locals.tf
  apps/arclight/src/app/v2/[...route]/_media-components/index.ts
  apps/arclight/src/app/v2/[...route]/_media-languages/index.ts
  apps/arclight/src/app/v2/[...route]/_resources/index.ts
  apps/arclight/src/app/v2/[...route]/route.ts
  apps/arclight/src/lib/cache.ts
Labels: on stage

#3983 refactor: linear gradient for OverlayContent
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.tsx
  libs/journeys/ui/src/components/Card/OverlayContent/OverlayContent.tsx
  libs/journeys/ui/src/components/Card/utils/getHeaderElements/getHeaderElements.spec.ts
  libs/journeys/ui/src/components/Card/utils/getHeaderElements/getHeaderElements.ts
  libs/journeys/ui/src/components/Card/utils/getHeaderElements/index.ts
Labels: priority: soon, effort: 1, type: refactor

#6218 feat(journeys-admin): disable export button if the user doesnt have permission to
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/ExportEventsButton/ExportEventsButton.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/ExportEventsButton/ExportEventsButton.stories.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/ExportEventsButton/ExportEventsButton.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.tsx
Labels: priority: soon, type: feat, effort: 1

#6316 fix: force facebook opengraph scrape
  apps/journeys-admin/pages/api/revalidate.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageEdit/ImageEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageEdit/ImageEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/DescriptionEdit/DescriptionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/DescriptionEdit/DescriptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/TitleEdit/TitleEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/TitleEdit/TitleEdit.tsx
  apps/journeys-admin/src/libs/revalidateJourney/index.ts
  apps/journeys-admin/src/libs/revalidateJourney/revalidateJourney.spec.ts
  apps/journeys-admin/src/libs/revalidateJourney/revalidateJourney.ts
  apps/journeys/pages/api/revalidate.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#3123 feat: social media preview updates
  apps/journeys-admin/src/components/Editor/Editor.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/Message/Message.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/Message/Message.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/Message/Message.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/Message/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/Post/Post.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/Post/Post.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/Post/Post.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/Post/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.stories.tsx
  apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageEdit/Large/Large.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/DescriptionEdit/DescriptionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/DescriptionEdit/DescriptionEdit.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/SocialDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/TitleEdit/TitleEdit.tsx
  apps/journeys-admin/src/components/Tooltip/Tooltip.spec.tsx
  apps/journeys-admin/src/components/Tooltip/Tooltip.stories.tsx
  apps/journeys-admin/src/components/Tooltip/Tooltip.tsx
  apps/journeys-admin/src/components/Tooltip/constants.ts
  apps/journeys-admin/src/components/Tooltip/index.ts
  apps/journeys-admin/src/components/Tooltip/utils/getReactflowTooltipOffset.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 3, priority: soon, type: feat

#6378 feat: add 'sd' quality option to VideoVariantDownloadQuality enum acr…
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/db/migrations/20250423230449_20250423230446/migration.sql
  apis/api-media/db/migrations/migration_lock.toml
  apis/api-media/db/schema.prisma
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  apps/watch/__generated__/globalTypes.ts
Labels: on stage

#6387 fix: add '360p' resolution option to video validation logic
  apis/api-media/src/schema/mux/video/video.ts
Labels: on stage

#6376 test: disable fully parallel for now
  apps/journeys-admin-e2e/playwright.config.ts
Labels: type: test, priority: now, effort: 1

#6356 fix: move revalidation to backend
  apis/api-journeys-modern/src/workers/revalidate/config.ts
  apis/api-journeys-modern/src/workers/revalidate/index.ts
  apis/api-journeys-modern/src/workers/revalidate/queue.ts
  apis/api-journeys-modern/src/workers/revalidate/service/index.ts
  apis/api-journeys-modern/src/workers/revalidate/service/service.spec.ts
  apis/api-journeys-modern/src/workers/revalidate/service/service.ts
  apis/api-journeys-modern/src/workers/revalidate/service/types.ts
  apis/api-journeys-modern/src/workers/server.ts
  apis/api-journeys/src/app/lib/prisma.types.ts
  apis/api-journeys/src/app/modules/journey/journey.module.ts
  apis/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
  apis/api-journeys/src/app/modules/journey/journey.resolver.ts
Labels: type: fix, effort: 3, priority: soon

#6393 feat: add bible citation api no qa
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/bibleCitation/bibleCitation.spec.ts
  apis/api-media/src/schema/bibleCitation/bibleCitation.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#6335 refactor: change default values for journey appearance fields
  apis/api-journeys-modern/db/schema.prisma
  apis/api-journeys/db/migrations/20250417001024_20250417001022/migration.sql
  apis/api-journeys/db/schema.prisma
Labels: priority: soon, effort: 1, type: refactor, on stage
