Repository JesusFilm/core, pull requests merged in 2025-05, with the labels that each got.

#6447 test: wait for a while before checking preview page and upgrade checkly
  apps/journeys-admin-e2e/src/e2e/discover/card-level-actions.spec.ts
  apps/journeys-admin-e2e/src/monitoring/journeys-admin.monitor.ts
  apps/journeys-admin-e2e/src/pages/card-level-actions.ts
  apps/journeys-admin-e2e/src/pages/journey-page.ts
  package-lock.json
  package.json
Labels: type: test, priority: soon, effort: 1

#6503 fix: retroactively fix qr codes
  apis/api-journeys-modern/project.json
  apis/api-journeys-modern/src/workers/cli.ts
  apis/api-journeys-modern/src/workers/server.ts
  apis/api-journeys-modern/src/workers/shortlinkUpdater/config.ts
  apis/api-journeys-modern/src/workers/shortlinkUpdater/index.ts
  apis/api-journeys-modern/src/workers/shortlinkUpdater/service/index.ts
  apis/api-journeys-modern/src/workers/shortlinkUpdater/service/service.ts
Labels: on stage

#5586 fix(journeys): background video playback for first card
  libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx
Labels: effort: 2, type: fix, priority: soon

#6485 fix: redirect by convention arc gt
  apps/short-links/src/middleware.ts
Labels: on stage

#6581 feat: possible fix for cors issues
  apps/arclight/src/app/[...route]/route.ts
Labels: on stage

#6591 test: update tests as per face lift changes
  .github/workflows/app-deploy.yml
  apps/journeys-admin-e2e/src/e2e/discover/journey-level-actions.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/teams.spec.ts
  apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
  apps/journeys-admin-e2e/src/framework/helpers.ts
  apps/journeys-admin-e2e/src/pages/journey-level-actions-page.ts
  apps/journeys-admin-e2e/src/pages/journey-page.ts
  apps/journeys-admin-e2e/src/pages/login-page.ts
  apps/journeys-admin-e2e/src/pages/publisher-and-templates-page.ts
  apps/journeys-admin-e2e/src/pages/template-page.ts
Labels: type: test, effort: 13, priority: soon

#6382 feat: new design of journey list
  .github/workflows/app-deploy.yml
  apps/journeys-admin-e2e/src/e2e/discover/journey-level-actions.spec.ts
  apps/journeys-admin-e2e/src/e2e/discover/teams.spec.ts
  apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
  apps/journeys-admin-e2e/src/framework/helpers.ts
  apps/journeys-admin-e2e/src/pages/journey-level-actions-page.ts
  apps/journeys-admin-e2e/src/pages/journey-page.ts
  apps/journeys-admin-e2e/src/pages/login-page.ts
  apps/journeys-admin-e2e/src/pages/publisher-and-templates-page.ts
  apps/journeys-admin-e2e/src/pages/template-page.ts
  apps/journeys-admin/__generated__/GetJourneyWithUserRoles.ts
  apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.spec.tsx
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.stories.tsx
  apps/journeys-admin/src/components/AccessAvatars/AccessAvatars.tsx
  apps/journeys-admin/src/components/AccessAvatars/ManageAccessAvatar/ManageAccessAvatar.tsx
  apps/journeys-admin/src/components/AccessAvatars/ManageAccessAvatar/index.ts
  apps/journeys-admin/src/components/Avatar/Avatar.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/AnalyticsItem/AnalyticsItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/AnalyticsItem/AnalyticsItem.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/Item/Item.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ResponsesItem/ResponsesItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ResponsesItem/ResponsesItem.tsx
  apps/journeys-admin/src/components/HelpScoutBeacon/BeaconInit/constants.ts
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActiveJourneyListData.ts
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActivePriorityList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActivePriorityList.tsx
  apps/journeys-admin/src/components/JourneyList/AddJourneyFab/AddJourneyFab.tsx
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardInfo/JourneyCardInfo.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardInfo/JourneyCardInfo.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardText/JourneyCardText.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardText/JourneyCardText.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardText/LastModifiedDate/LastModifiedDate.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/journeyCardVariant.ts
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/LoadingJourneyList/LoadingJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/journeyListData.ts
  apps/journeys-admin/src/components/PageWrapper/MainPanelBody/MainPanelBody.tsx
  apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
  apps/journeys-admin/src/components/PageWrapper/SidePanel/SidePanel.tsx
  apps/journeys-admin/src/components/StatusTabPanel/StatusTabPanel.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 8, priority: soon, type: feat

#6610 fix: remove extraneous loading skeleton element from journey card
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActivePriorityList.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardInfo/JourneyCardInfo.tsx
Labels: type: fix, priority: now, effort: 1

#6611 feat: add dedicated loading skeleton for journey card social media image
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
Labels: priority: now, type: feat, effort: 1

#6587 feat: add createKeyword mutation and update VideoUpdateInput to inclu…
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/keyword/keyword.spec.ts
  apis/api-media/src/schema/keyword/keyword.ts
  apis/api-media/src/schema/video/inputs/videoUpdate.ts
  apis/api-media/src/schema/video/video.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#6495 feat: content page hero
  apps/watch-e2e/playwright.config.ts
  apps/watch-e2e/src/e2e/chapter.spec.ts
  apps/watch-e2e/src/e2e/feature-film.spec.ts
  apps/watch/pages/watch/[part1]/[part2].tsx
  apps/watch/pages/watch/[part1]/[part2]/[part3].tsx
  apps/watch/src/components/NewContentPage/ContentHero/ContentHeader/ContentHeader.spec.tsx
  apps/watch/src/components/NewContentPage/ContentHero/ContentHeader/ContentHeader.tsx
  apps/watch/src/components/NewContentPage/ContentHero/ContentHeader/index.ts
  apps/watch/src/components/NewContentPage/ContentHero/ContentHero.spec.tsx
  apps/watch/src/components/NewContentPage/ContentHero/ContentHero.tsx
  apps/watch/src/components/NewContentPage/ContentHero/ContentHeroMuteButton/ContentHeroMuteButton.spec.tsx
  apps/watch/src/components/NewContentPage/ContentHero/ContentHeroMuteButton/ContentHeroMuteButton.tsx
  apps/watch/src/components/NewContentPage/ContentHero/ContentHeroMuteButton/index.ts
  apps/watch/src/components/NewContentPage/ContentHero/ContentHeroVideo/ContentHeroVideo.tsx
  apps/watch/src/components/NewContentPage/ContentHero/ContentHeroVideo/index.ts
  apps/watch/src/components/NewContentPage/ContentHero/index.ts
  apps/watch/src/components/NewContentPage/NewContentPage.tsx
  apps/watch/src/components/NewContentPage/index.ts
  apps/watch/src/libs/utils/getWatchUrl/getWatchUrl.spec.tsx
  apps/watch/src/libs/utils/getWatchUrl/getWatchUrl.ts
  apps/watch/src/libs/utils/getWatchUrl/index.ts
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/Volume5.tsx
  libs/shared/ui/src/components/icons/VolumeOff.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: type: feat

#6499 feat(watch): content video player
  apps/watch/src/components/NewContentPage/ContentHero/ContentHero.spec.tsx
  apps/watch/src/components/NewContentPage/ContentHero/ContentHero.tsx
  apps/watch/src/components/NewContentPage/ContentHero/ContentHeroMuteButton/ContentHeroMuteButton.spec.tsx
  apps/watch/src/components/NewContentPage/ContentHero/ContentHeroMuteButton/ContentHeroMuteButton.tsx
  apps/watch/src/components/NewContentPage/ContentHero/ContentHeroMuteButton/index.ts
  apps/watch/src/components/NewContentPage/ContentHero/ContentHeroVideo/ContentHeroVideo.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
Labels: type: feat

#6496 feat(watch): chapter title and description
  apps/watch/src/components/CollectionsPage/CollectionsPageContent/CollectionsPageContent.tsx
  apps/watch/src/components/NewContentPage/ContentHero/ContentHero.tsx
  apps/watch/src/components/NewContentPage/ContentMetadata/ContentMetadata.tsx
  apps/watch/src/components/NewContentPage/ContentMetadata/index.ts
  apps/watch/src/components/NewContentPage/NewContentPage.tsx
Labels: type: feat, effort: 1

#6565 feat(watch): video carousel
  apps/watch/src/components/CollectionsPage/CollectionsPageContent/CollectionsPageContent.tsx
  apps/watch/src/components/NewContentPage/NewContentPage.tsx
  apps/watch/src/components/NewContentPage/VideoCarousel/VideoCard/VideoCard.spec.tsx
  apps/watch/src/components/NewContentPage/VideoCarousel/VideoCard/VideoCard.stories.tsx
  apps/watch/src/components/NewContentPage/VideoCarousel/VideoCard/VideoCard.tsx
  apps/watch/src/components/NewContentPage/VideoCarousel/VideoCard/index.ts
  apps/watch/src/components/NewContentPage/VideoCarousel/VideoCarousel.spec.tsx
  apps/watch/src/components/NewContentPage/VideoCarousel/VideoCarousel.tsx
  apps/watch/src/components/NewContentPage/VideoCarousel/index.ts
Labels: type: feat

#6585 feat: keywords
  apps/videos-admin/src/app/(dashboard)/videos/[videoId]/_VideoInformation/VideoInformation.spec.tsx
  apps/videos-admin/src/app/(dashboard)/videos/[videoId]/_VideoInformation/VideoInformation.tsx
  apps/videos-admin/src/app/(dashboard)/videos/[videoId]/_VideoInformation/VideoKeywords.spec.tsx
  apps/videos-admin/src/app/(dashboard)/videos/[videoId]/_VideoInformation/VideoKeywords.tsx
Labels: on stage

#6626 feat: arclight video control bar
  apps/arclight/src/app/videoPlayerUrl/VideoPlayer.tsx
Labels: on stage

#6572 feat: add button to view public watch page in VideoInformation component
  apps/videos-admin/src/app/(dashboard)/videos/[videoId]/_VideoInformation/VideoInformation.tsx
Labels: on stage

#6541 feat: discussion questions
  apps/watch/src/components/NewContentPage/ContentMetadata/ContentMetadata.tsx
  apps/watch/src/components/NewContentPage/DiscussionQuestions/DiscussionQuestions.spec.tsx
  apps/watch/src/components/NewContentPage/DiscussionQuestions/DiscussionQuestions.stories.tsx
  apps/watch/src/components/NewContentPage/DiscussionQuestions/DiscussionQuestions.tsx
  apps/watch/src/components/NewContentPage/DiscussionQuestions/Question/Question.spec.tsx
  apps/watch/src/components/NewContentPage/DiscussionQuestions/Question/Question.stories.ts
  apps/watch/src/components/NewContentPage/DiscussionQuestions/Question/Question.tsx
  apps/watch/src/components/NewContentPage/DiscussionQuestions/Question/index.ts
  apps/watch/src/components/NewContentPage/DiscussionQuestions/index.ts
  apps/watch/src/components/NewContentPage/NewContentPage.tsx
  apps/watch/src/components/NewContentPage/VideoCarousel/VideoCard/VideoCard.spec.tsx
  apps/watch/src/components/NewContentPage/VideoCarousel/VideoCard/VideoCard.stories.tsx
  libs/locales/en/apps-watch.json
  libs/shared/ui/src/libs/themes/website/tokens/components.tsx
Labels: type: feat

#6656 feat: add placeholder social media image for journey card
  apps/journeys-admin/public/logo-grayscale.svg
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
Labels: effort: 2, priority: soon, type: feat

#6642 test: checkly and video upload test intermittent failure fixes
  apps/journeys-admin-e2e/src/monitoring/journeys-admin.monitor.ts
  apps/journeys-admin-e2e/src/pages/card-level-actions.ts
Labels: type: test, effort: 1, Bug

#6593 feat(watch): share button opens old sharing modal
  apps/watch/src/components/NewContentPage/ContentHero/ContentHero.tsx
  apps/watch/src/components/NewContentPage/ContentMetadata/ContentMetadata.tsx
  apps/watch/src/components/NewContentPage/DiscussionQuestions/DiscussionQuestions.spec.tsx
  apps/watch/src/components/NewContentPage/DiscussionQuestions/DiscussionQuestions.tsx
  apps/watch/src/components/NewContentPage/NewContentPage.spec.tsx
  apps/watch/src/components/NewContentPage/NewContentPage.tsx
Labels: type: feat

#6674 feat: shareable journey fields
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/journey/journey.graphql
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#6614 feat: bible quotes
  apps/watch/__generated__/GetVideoContainerPart2.ts
  apps/watch/__generated__/GetVideoContent.ts
  apps/watch/__generated__/GetVideoContentPart3.ts
  apps/watch/__generated__/GetVideosForTestData.ts
  apps/watch/__generated__/VideoContentFields.ts
  apps/watch/src/components/DownloadDialog/DownloadDialog.spec.tsx
  apps/watch/src/components/NewContentPage/BibleCitations/BibleCitations.spec.tsx
  apps/watch/src/components/NewContentPage/BibleCitations/BibleCitations.tsx
  apps/watch/src/components/NewContentPage/BibleCitations/index.ts
  apps/watch/src/components/NewContentPage/NewContentPage.spec.tsx
  apps/watch/src/components/NewContentPage/NewContentPage.tsx
  apps/watch/src/components/VideoCard/VideoCard.spec.tsx
  apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.spec.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
  apps/watch/src/components/Videos/__generated__/testData.ts
  apps/watch/src/libs/videoContentFields.ts
  apps/watch/src/libs/videoContext/VideoContext.spec.tsx
  libs/locales/en/apps-watch.json
Labels: type: feat

#6691 fix: ai tranlsations filter available languages
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/TranslateJourneyDialog/TranslateJourneyDialog.tsx
  apps/journeys-admin/src/components/Team/CopyToTeamMenuItem/CopyToTeamMenuItem.spec.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#6627 fix: show non-primary journey languages on card
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardText/JourneyCardText.tsx
  apps/journeys-admin/src/libs/useAdminJourneysQuery/useAdminJourneysQuery.ts
  package-lock.json
  package.json
Labels: type: fix, priority: soon, effort: 1

#6733 fix: add cors headers
  apps/arclight/src/app/[...route]/route.ts
Labels: on stage

#6724 feat: invalidate caches on mutation no qa
  apis/api-media/infrastructure/locals.tf
  apis/api-media/src/lib/videoCacheReset.spec.ts
  apis/api-media/src/lib/videoCacheReset.ts
  apis/api-media/src/schema/video/video.ts
  apis/api-media/src/schema/videoVariant/videoVariant.spec.ts
  apis/api-media/src/schema/videoVariant/videoVariant.ts
  apps/watch/pages/api/revalidate.spec.ts
  apps/watch/pages/api/revalidate.ts
Labels: on stage

#6741 fix: mark language field as shareable in journey schema
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/app/modules/journey/journey.graphql
Labels: on stage

#6743 refactor: update Apollo client instantiation and improve memory manag…
  apis/api-media/src/workers/algolia/service/service.spec.ts
  apis/api-media/src/workers/algolia/service/service.ts
Labels: on stage

#6737 refactor: layout for fullscreen video
  apps/watch/src/components/NewContentPage/ContentHero/ContentHero.tsx
  apps/watch/src/components/NewContentPage/ContentHero/ContentHeroVideo/ContentHeroVideo.tsx
  apps/watch/src/components/NewContentPage/NewContentPage.tsx
  apps/watch/src/components/NewContentPage/VideoCarousel/VideoCarousel.tsx
Labels: type: feat

#6745 fix: delete team customisation from onboarding backend
  apis/api-journeys/src/app/modules/mailChimp/mailChimp.service.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#6734 fix: remove team creation from onboarding
  apps/journeys-admin-e2e/src/pages/register-Page.ts
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingStepper/OnboardingStepper.spec.tsx
  apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingStepper/OnboardingStepper.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.spec.tsx
  apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.tsx
Labels: effort: 2, type: fix, priority: soon, on stage

#6676 feat: ai translate backend
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/db/schema.prisma
  apis/api-journeys-modern/infrastructure/locals.tf
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys-modern/src/lib/auth/ability.spec.ts
  apis/api-journeys-modern/src/lib/auth/ability.ts
  apis/api-journeys-modern/src/schema/builder.ts
  apis/api-journeys-modern/src/schema/journey/index.ts
  apis/api-journeys-modern/src/schema/journey/journey.acl.spec.ts
  apis/api-journeys-modern/src/schema/journey/journey.acl.ts
  apis/api-journeys-modern/src/schema/journey/journey.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/getCardBlocksContent/getBlockContent.spec.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/getCardBlocksContent/getBlockContent.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/getCardBlocksContent/getButtonBlockContent.spec.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/getCardBlocksContent/getButtonBlockContent.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/getCardBlocksContent/getCardBlocksContent.spec.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/getCardBlocksContent/getCardBlocksContent.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/getCardBlocksContent/getCoverBlockContent.spec.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/getCardBlocksContent/getCoverBlockContent.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/getCardBlocksContent/getImageBlockContent.spec.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/getCardBlocksContent/getImageBlockContent.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/getCardBlocksContent/getRadioQuestionBlockContent.spec.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/getCardBlocksContent/getRadioQuestionBlockContent.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/getCardBlocksContent/getVideoBlockContent.spec.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/getCardBlocksContent/getVideoBlockContent.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/getCardBlocksContent/index.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/index.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/journeyAiTranslate.spec.ts
  apis/api-journeys-modern/src/schema/journeyAiTranslate/journeyAiTranslate.ts
  apis/api-journeys-modern/src/schema/journeyLanguageAiDetect/index.ts
  apis/api-journeys-modern/src/schema/journeyLanguageAiDetect/journeyLanguageAiDetect.ts
  apis/api-journeys-modern/src/schema/language/index.ts
  apis/api-journeys-modern/src/schema/language/language.ts
  apis/api-journeys-modern/src/schema/schema.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  libs/shared/ai/src/getImageDescription/getImageDescription.ts
  libs/shared/ai/src/getImageDescription/index.ts
  libs/shared/ai/src/prompts/hardeningPrompt/hardenPrompt.spec.ts
  libs/shared/ai/src/prompts/hardeningPrompt/hardenPrompt.ts
  libs/shared/ai/src/prompts/hardeningPrompt/hardeningPrompt.spec.ts
  libs/shared/ai/src/prompts/hardeningPrompt/hardeningPrompt.ts
  libs/shared/ai/src/prompts/hardeningPrompt/index.ts
  libs/shared/ai/src/prompts/index.ts
  libs/shared/ai/src/prompts/preSystemPrompt.spec.ts
  libs/shared/ai/src/prompts/preSystemPrompt.ts
  libs/shared/ai/src/prompts/system.ts
  package-lock.json
  package.json
Labels: on stage

#6762 chore: make api journeys journeys and blocks sharable
  apis/api-gateway/schema.graphql
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/app/modules/block/block.graphql
  apis/api-journeys/src/app/modules/block/button/button.graphql
  apis/api-journeys/src/app/modules/block/card/card.graphql
  apis/api-journeys/src/app/modules/block/gridContainer/gridContainer.graphql
  apis/api-journeys/src/app/modules/block/gridItem/gridItem.graphql
  apis/api-journeys/src/app/modules/block/icon/icon.graphql
  apis/api-journeys/src/app/modules/block/image/image.graphql
  apis/api-journeys/src/app/modules/block/radioOption/radioOption.graphql
  apis/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.graphql
  apis/api-journeys/src/app/modules/block/signUp/signUp.graphql
  apis/api-journeys/src/app/modules/block/spacer/spacer.graphql
  apis/api-journeys/src/app/modules/block/step/step.graphql
  apis/api-journeys/src/app/modules/block/textResponse/textResponse.graphql
  apis/api-journeys/src/app/modules/block/typography/typography.graphql
  apis/api-journeys/src/app/modules/block/video/video.graphql
  apis/api-journeys/src/app/modules/block/videoTrigger/videoTrigger.graphql
Labels: on stage

#6717 fix: hash sum mismatch syntax
  .devcontainer/Dockerfile
Labels: type: fix, priority: now, priority: soon

#6772 fix: enhance schema with new fields and indexes
  apis/api-journeys-modern/db/schema.prisma
  apis/api-journeys-modern/src/__generated__/pothos-types.ts
  apis/api-journeys-modern/src/workers/emailEvents/service/fetchEmailDetails.spec.ts
  apis/api-journeys-modern/src/workers/emailEvents/service/service.spec.ts
Labels: on stage
