Repository JesusFilm/core, pull requests merged in 2025-10, with the labels that each got.

#7890 fix: add algolia provider to publisher edit
  apps/journeys-admin/pages/publisher/[journeyId].tsx
Labels: type: fix, priority: soon, effort: 1

#7899 refactor: remove ButtonClickEventCreateInput and related resolver fro…
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/schema/event/button/inputs/buttonClickEventCreateInput.ts
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/event/button/button.graphql
  apis/api-journeys/src/app/modules/event/button/button.resolver.spec.ts
  apis/api-journeys/src/app/modules/event/button/button.resolver.ts
  apis/api-journeys/src/app/modules/event/event.module.ts
  apps/journeys-admin/__generated__/GetJourneyVisitors.ts
Labels: on stage

#7789 fix: unify customization flow next step button styling
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/CustomizeFlowNextButton/CustomizeFlowNextButton.spec.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/CustomizeFlowNextButton/CustomizeFlowNextButton.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/CustomizeFlowNextButton/index.ts
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/DoneScreen/DoneScreen.spec.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/DoneScreen/DoneScreen.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/LanguageScreen/LanguageScreen.spec.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/LanguageScreen/LanguageScreen.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/LinksScreen/LinksScreen.spec.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/LinksScreen/LinksScreen.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/SocialScreen/SocialScreen.spec.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/SocialScreen/SocialScreen.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/TextScreen/TextScreen.spec.tsx
  apps/journeys-admin/src/components/TemplateCustomization/MultiStepForm/Screens/TextScreen/TextScreen.tsx
  libs/locales/en/apps-journeys-admin.json
  libs/locales/en/journeys-ui.json
Labels: type: fix, priority: soon, effort: 1

#7678 fix: prevent multiple CopyToTeamDialog's from rendering at once
  libs/journeys/ui/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.spec.tsx
  libs/journeys/ui/src/components/TemplateView/CreateJourneyButton/CreateJourneyButton.tsx
  libs/journeys/ui/src/components/TemplateView/TemplateViewHeader/TemplateActionButton/TemplateActionButton.tsx
  libs/journeys/ui/src/components/TemplateView/TemplateViewHeader/TemplateViewHeader.tsx
Labels: Bug

#7922 feat: add journey visitor export with events inline
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/schema/journey/journey.acl.ts
  apis/api-journeys-modern/src/schema/journeyVisitor/index.ts
  apis/api-journeys-modern/src/schema/journeyVisitor/inputs/index.ts
  apis/api-journeys-modern/src/schema/journeyVisitor/inputs/journeyVisitorExportSelect.ts
  apis/api-journeys-modern/src/schema/journeyVisitor/journeyVisitor.spec.ts
  apis/api-journeys-modern/src/schema/journeyVisitor/journeyVisitor.ts
  libs/prisma/journeys/db/migrations/20251006101902_20251006101900/migration.sql
  libs/prisma/journeys/db/schema.prisma
  libs/shared/gql/src/__generated__/graphql-env.d.ts
Labels: on stage

#7915 feat: multiselect analytics backend
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/schema/event/multiselect/multiselectSubmissionEventCreate.mutation.ts
  apis/api-journeys-modern/src/schema/journeyVisitor/journeyVisitor.ts
  apis/api-journeys-modern/src/schema/visitor/inputs/journeyVisitorFilter.ts
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/event/event.graphql
  apis/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.graphql
  apis/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.service.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  libs/prisma/journeys/db/migrations/20251006205738_20251006205737/migration.sql
  libs/prisma/journeys/db/schema.prisma
  libs/shared/gql/src/__generated__/graphql-env.d.ts
Labels: on stage

#7945 feat: add journey visitor export to journeys-admin
  apis/api-journeys-modern/src/schema/journeyVisitor/journeyVisitor.spec.ts
  apis/api-journeys-modern/src/schema/journeyVisitor/journeyVisitor.ts
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/ExportDialog/ContactDataForm/ContactDataForm.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/ExportDialog/ContactDataForm/ContactDataForm.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/ExportDialog/ExportDialog.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/ExportDialog/ExportDialog.tsx
  apps/journeys-admin/src/libs/useJourneyContactsExport/useJourneyContactsExport.tsx
  apps/journeys-admin/src/libs/useJourneyContactsExport/utils/processContactsCsv/index.ts
  apps/journeys-admin/src/libs/useJourneyContactsExport/utils/processContactsCsv/processContactsCsv.spec.ts
  apps/journeys-admin/src/libs/useJourneyContactsExport/utils/processContactsCsv/processContactsCsv.ts
  libs/locales/en/apps-journeys-admin.json
Labels: on stage

#7946 chore: use variants instead of variant in arclight queries
  apps/arclight/src/app/v2/[...route]/_media-component-links/[mediaComponentId]/index.ts
Labels: on stage
