Repository JesusFilm/core, pull requests merged in 2025-07, with the labels that each got.

#6890 chore: mui 7 imports
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/pages/_document.tsx
  apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
  apps/journeys/pages/_app.tsx
  apps/journeys/pages/_document.tsx
  apps/watch/pages/_app.tsx
  apps/watch/pages/_document.tsx
  libs/shared/ui/src/libs/createEmotionCache/createEmotionCache.ts
  package-lock.json
  package.json
Labels: on stage

#6901 fix: add duration and lengthInMilliseconds to video variant data
  apps/videos-admin/src/app/_UploadVideoVariantProvider/UploadVideoVariantProvider.spec.tsx
  apps/videos-admin/src/app/_UploadVideoVariantProvider/UploadVideoVariantProvider.tsx
Labels: on stage

#6831 feat: add tailwind to journeys admin
  .vscode/settings.json
  apps/journeys-admin/eslint.config.mjs
  apps/journeys-admin/pages/_app.tsx
  apps/journeys-admin/pages/globals.css
  apps/journeys-admin/postcss.config.mjs
  apps/journeys-admin/public/swiper-pagination-override.css
  apps/journeys/eslint.config.mjs
  apps/journeys/pages/_app.tsx
  apps/journeys/pages/globals.css
  apps/journeys/postcss.config.mjs
  libs/journeys/ui/eslint.config.mjs
  libs/journeys/ui/postcss.config.mjs
  libs/journeys/ui/src/globals.css
  libs/journeys/ui/tsconfig.lib.json
Labels: on stage

#6812 fix: remove duplicate name label from visitor card details
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCard.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardDetails/VisitorCardDetails.spec.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/VisitorCard/VisitorCardDetails/VisitorCardDetails.tsx
Labels: type: fix, priority: soon, effort: 1

#6920 feat: display subtitles in english and native language
  apps/videos-admin/src/app/(dashboard)/videos/[videoId]/editions/[editionId]/page.tsx
Labels: on stage

#6885 feat: introduced typography block settings type with a color field back end
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys-modern/src/schema/block/typography/typography.ts
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/block/typography/typography.graphql
  apis/api-journeys/src/app/modules/block/typography/typography.resolver.spec.ts
  apis/api-journeys/src/app/modules/block/typography/typography.resolver.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#7146 fix: update resolve field
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys-modern/src/schema/block/typography/typography.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#7149 feat: video delete api
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/video/video.spec.ts
  apis/api-media/src/schema/video/video.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#6814 fix: bible quotes pattern
  apps/watch/src/components/NewVideoContentPage/BibleCitations/BibleCitations.spec.tsx
  apps/watch/src/components/NewVideoContentPage/BibleCitations/BibleCitations.tsx
  apps/watch/src/components/NewVideoContentPage/BibleCitations/BibleCitationsCard/BibleCitationCard.spec.tsx
  apps/watch/src/components/NewVideoContentPage/BibleCitations/BibleCitationsCard/BibleCitationCard.tsx
  apps/watch/src/components/NewVideoContentPage/BibleCitations/BibleCitationsCard/index.ts
  apps/watch/src/components/NewVideoContentPage/BibleCitations/BibleCitationsCard/utils/formatScripture/formatScripture.spec.ts
  apps/watch/src/components/NewVideoContentPage/BibleCitations/BibleCitationsCard/utils/formatScripture/formatScripture.ts
  apps/watch/src/components/NewVideoContentPage/BibleCitations/BibleCitationsCard/utils/formatScripture/index.ts
  apps/watch/src/components/NewVideoContentPage/NewVideoContentPage.spec.tsx
  libs/locales/en/apps-watch.json
Labels: priority: soon, type: feat, effort: 1

#6886 refactor: modal redesign
  apps/watch/public/watch/global.css
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/QuizButton/QuizButton.spec.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/QuizButton/QuizModal/QuizModal.spec.tsx
  apps/watch/src/components/CollectionsPage/CollectionsVideoContent/QuizButton/QuizModal/QuizModal.tsx
  apps/watch/src/components/CollectionsPage/ContainerHeroVideo/ContainerHeroVideo.tsx
  apps/watch/src/components/NewVideoContentPage/VideoContentHero/HeroVideo/HeroVideo.tsx
Labels: type: fix, priority: soon, effort: 1

#7160 fix: variable values
  apis/api-media/src/schema/video/video.spec.ts
  apis/api-media/src/schema/video/video.ts
Labels: type: fix, on stage

#7163 feat: add color to button block settings
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys-modern/src/schema/block/button/button.ts
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/block/button/button.graphql
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#7166 feat: auto generate download api
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/db/migrations/20250707234814_20250707234813/migration.sql
  apis/api-media/db/schema.prisma
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/index.ts
  apis/api-media/src/schema/mux/video/service.spec.ts
  apis/api-media/src/schema/mux/video/service.ts
  apis/api-media/src/schema/mux/video/video.spec.ts
  apis/api-media/src/schema/mux/video/video.ts
  apis/api-media/src/scripts/copy-distro-downloads.ts
  apis/api-media/src/workers/cli.ts
  apis/api-media/src/workers/processVideoDownloads/config.ts
  apis/api-media/src/workers/processVideoDownloads/index.ts
  apis/api-media/src/workers/processVideoDownloads/queue.ts
  apis/api-media/src/workers/processVideoDownloads/service/index.ts
  apis/api-media/src/workers/processVideoDownloads/service/service.spec.ts
  apis/api-media/src/workers/processVideoDownloads/service/service.ts
  apis/api-media/src/workers/processVideoDownloads/worker.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  apps/watch/__generated__/globalTypes.ts
Labels: on stage

#7168 feat: stage env visual cue
  apps/videos-admin/src/app/(dashboard)/_AppNavbar/AppNavbar.tsx
  apps/videos-admin/src/app/(dashboard)/_SideMenu/SideMenu.tsx
  apps/videos-admin/src/app/(dashboard)/layout.tsx
  apps/videos-admin/src/app/layout.tsx
  apps/videos-admin/src/components/EnvironmentBanner/EnvironmentBanner.spec.tsx
  apps/videos-admin/src/components/EnvironmentBanner/EnvironmentBanner.tsx
  apps/videos-admin/src/components/EnvironmentBanner/index.ts
  apps/videos-admin/src/libs/environment.spec.ts
  apps/videos-admin/src/libs/environment.ts
Labels: on stage

#7158 refactor: update typography elements in various components
  apps/watch/public/watch/global.css
  apps/watch/src/components/Accordion/Accordion.tsx
  apps/watch/src/components/Accordion/index.ts
  apps/watch/src/components/NewVideoContentPage/BibleCitations/FreeResourceCard/FreeResourceCard.tsx
  apps/watch/src/components/NewVideoContentPage/ContentMetadata/ContentMetadata.spec.tsx
  apps/watch/src/components/NewVideoContentPage/ContentMetadata/ContentMetadata.tsx
  apps/watch/src/components/NewVideoContentPage/DiscussionQuestions/DiscussionQuestions.tsx
  apps/watch/src/components/NewVideoContentPage/DiscussionQuestions/Question/Question.spec.tsx
  apps/watch/src/components/NewVideoContentPage/DiscussionQuestions/Question/Question.stories.ts
  apps/watch/src/components/NewVideoContentPage/DiscussionQuestions/Question/Question.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoTitle/VideoTitle.tsx
  libs/locales/en/apps-watch.json
  package-lock.json
  package.json
Labels: priority: soon, effort: 1, type: refactor

#7174 refactor: journeySimpleTypes schemas for flexible get
  apis/api-journeys-modern/src/schema/journey/simple/getSimpleJourney.ts
  apis/api-journeys-modern/src/schema/journey/simple/simplifyJourney.ts
  apis/api-journeys-modern/src/schema/journey/simple/updateSimpleJourney.ts
  libs/shared/ai/src/journeySimpleTypes.spec.ts
  libs/shared/ai/src/journeySimpleTypes.ts
Labels: on stage

#7182 feat: add backend for brightcove redirects
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/db/schema.prisma
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/db/migrations/20250711152236_20250711152232/migration.sql
  apis/api-media/db/schema.prisma
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/enums/service.ts
  apis/api-media/src/schema/shortLink/enums/index.ts
  apis/api-media/src/schema/shortLink/enums/redirectType.ts
  apis/api-media/src/schema/shortLink/shortLink.spec.ts
  apis/api-media/src/schema/shortLink/shortLink.ts
  apis/api-media/src/schema/video/video.spec.ts
  apis/api-media/src/schema/videoVariant/inputs/videoVariantCreate.ts
  apis/api-media/src/schema/videoVariant/inputs/videoVariantUpdate.ts
  apis/api-media/src/schema/videoVariant/videoVariant.spec.ts
  apis/api-media/src/schema/videoVariant/videoVariant.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#7176 fix: new believer course thai videos on watch page after changes
  apis/api-gateway/schema.graphql
  apis/api-media/schema.graphql
  apis/api-media/src/schema/video/video.spec.ts
  apis/api-media/src/schema/video/video.ts
  apis/api-media/src/schema/videoVariant/videoVariant.spec.ts
  apis/api-media/src/schema/videoVariant/videoVariant.ts
Labels: on stage

#7183 feat: add brightcove redirect handling to arclight
  apps/arclight/infrastructure/locals.tf
  apps/arclight/src/app/[...route]/_dh/index.ts
  apps/arclight/src/app/[...route]/_dl/index.ts
  apps/arclight/src/app/[...route]/_hls/index.ts
  apps/arclight/src/app/[...route]/_s/index.ts
  apps/arclight/src/app/[...route]/queries.ts
  apps/arclight/src/app/[...route]/route.ts
  apps/arclight/src/app/[keyword]/route.ts
  apps/arclight/src/app/videoPlayerUrl/VideoPlayer.tsx
  apps/arclight/src/lib/brightcove.ts
  apps/arclight/src/lib/redirectUtils.ts
  apps/short-links/src/middleware.ts
Labels: on stage

#7194 chore: add maxresolution to mux mutations
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/mux/video/enums/index.ts
  apis/api-media/src/schema/mux/video/enums/maxResolutionTier.ts
  apis/api-media/src/schema/mux/video/index.ts
  apis/api-media/src/schema/mux/video/service.spec.ts
  apis/api-media/src/schema/mux/video/service.ts
  apis/api-media/src/schema/mux/video/video.spec.ts
  apis/api-media/src/schema/mux/video/video.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#7204 fix: update 01-development-environment.mdx
  apps/docs/docs/02-getting-started/01-development-environment.mdx
Labels: priority: soon, effort: 1

#7171 fix: auto subtitles
  apps/watch/pages/watch/[part1]/[part2].tsx
  apps/watch/pages/watch/[part1]/[part2]/[part3].tsx
  apps/watch/src/components/LanguageSwitchDialog/AudioTrackSelect/AudioTrackSelect.spec.tsx
  apps/watch/src/components/LanguageSwitchDialog/SubtitlesSelect/SubtitlesSelect.spec.tsx
  apps/watch/src/components/LanguageSwitchDialog/SubtitlesSelect/SubtitlesSelect.tsx
  apps/watch/src/components/NewVideoContentPage/NewVideoContentPage.spec.tsx
  apps/watch/src/components/NewVideoContentPage/NewVideoContentPage.tsx
  apps/watch/src/libs/watchContext/WatchContext.spec.tsx
  apps/watch/src/libs/watchContext/WatchContext.tsx
  apps/watch/src/libs/watchContext/initializeVideoLanguages/index.ts
  apps/watch/src/libs/watchContext/initializeVideoLanguages/initializeVideoLanguages.spec.ts
  apps/watch/src/libs/watchContext/initializeVideoLanguages/initializeVideoLanguages.ts
Labels: type: fix, priority: soon, effort: 1

#7220 fix: brightcove redirects cors and all download types
  apps/arclight/src/app/[...route]/_dh/index.ts
  apps/arclight/src/app/[...route]/_dl/index.ts
  apps/arclight/src/app/[...route]/_hls/index.ts
  apps/arclight/src/app/[...route]/_s/index.ts
  apps/arclight/src/app/[keyword]/route.ts
  apps/arclight/src/lib/brightcove.ts
  apps/arclight/tsconfig.json
  apps/short-links/src/middleware.ts
Labels: on stage

#7244 fix: find closest bitrate match for brightcove redirects
  apps/arclight/src/lib/brightcove.ts
Labels: on stage

#7234 feat: poll block enhancements backend
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/db/schema.prisma
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/__generated__/pothos-types.ts
  apis/api-journeys-modern/src/schema/block/radioOption/radioOption.ts
  apis/api-journeys-modern/src/schema/block/radioQuestion/radioQuestion.ts
  apis/api-journeys/db/migrations/20250722230706_20250722230656/migration.sql
  apis/api-journeys/db/schema.prisma
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/block/block.service.spec.ts
  apis/api-journeys/src/app/modules/block/block.service.ts
  apis/api-journeys/src/app/modules/block/radioOption/radioOption.graphql
  apis/api-journeys/src/app/modules/block/radioOption/radioOption.resolver.spec.ts
  apis/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.graphql
  apis/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.spec.ts
  apis/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.ts
  apis/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  libs/shared/gql/src/__generated__/graphql-env.d.ts
Labels: type: fix, priority: soon, type: feat, on stage

#7246 feat: add redirection for core.arc.gt and use redis caching
  apps/arclight/src/lib/brightcove.ts
  apps/arclight/src/lib/cache.ts
  apps/short-links/src/middleware.ts
Labels: on stage

#5454 chore: migrate downloads to r2
  apis/api-media/project.json
  apis/api-media/src/scripts/download-migrate-r2.spec.ts
  apis/api-media/src/scripts/download-migrate-r2.ts
Labels: priority: 2day, effort: 8, type: chore

#7257 [watch-modern] drop jsdoc and constant extraction rules
  .cursor/rules/watch-modern.mdc
  apps/watch-modern/AGENTS.md
Labels: codex

#7203 fix: fix social image thumbnail shape and globe icon alignment
  apps/journeys-admin/src/components/Editor/Toolbar/JourneyDetails/JourneyDetails.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Labels: Bug

#7262 fix: implement poll block styles
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
  libs/journeys/ui/src/components/RadioOption/RadioOption.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
  libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
  libs/journeys/ui/src/components/RadioQuestion/utils/getPollOptionBorderStyles/getPollOptionBorderStyles.spec.ts
  libs/journeys/ui/src/components/RadioQuestion/utils/getPollOptionBorderStyles/getPollOptionBorderStyles.tsx
  libs/journeys/ui/src/components/RadioQuestion/utils/getPollOptionBorderStyles/index.ts
  libs/locales/en/apps-journeys-admin.json
Labels: type: fix, priority: soon, effort: 1

#7248 feat: add modern proxy routing
  apps/watch-modern/src/app/modern-test/page.tsx
  libs/locales/en/apps-watch-modern.json
  libs/locales/fr-FR/apps-watch-modern.json
  workers/jf-proxy/README.md
  workers/jf-proxy/src/index.spec.ts
  workers/jf-proxy/src/index.ts
  workers/jf-proxy/wrangler.toml
Labels: on stage

#7301 fix: deprecate prop poll image id
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/db/schema.prisma
  apis/api-journeys-modern/schema.graphql
  apis/api-journeys-modern/src/__generated__/pothos-types.ts
  apis/api-journeys-modern/src/schema/block/radioOption/radioOption.ts
  apis/api-journeys/db/migrations/20250731042829_20250731042824/migration.sql
  apis/api-journeys/db/schema.prisma
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/block/block.service.spec.ts
  apis/api-journeys/src/app/modules/block/block.service.ts
  apis/api-journeys/src/app/modules/block/radioOption/radioOption.graphql
  apis/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  libs/shared/gql/src/__generated__/graphql-env.d.ts
Labels: type: fix, priority: soon, effort: 1, on stage
