Repository JesusFilm/core, pull requests merged in 2025-03, with the labels that each got.

#5396 chore: migrate cursorroles to new format
  .cursor/rules/apis.mdc
  .cursor/rules/apps.mdc
  .cursor/rules/base.mdc
  .cursor/rules/infrastructure.mdc
  .cursor/rules/kubernetes.mdc
  .cursor/rules/workers.mdc
  .cursorrules
Labels: priority: 2day, effort: 1, type: chore

#5357 fix: improve YouTube video autoplay initialisation
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.tsx
Labels: effort: 2, type: fix, priority: soon, effort: 1, Bug, Performance

#5391 feat: media transcoder
  .devcontainer/Dockerfile
  .github/workflows/task-deploy-prod.yml
  .github/workflows/task-deploy-stage.yml
  .github/workflows/task-deploy-worker.yml
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/infrastructure/locals.tf
  apis/api-media/infrastructure/main.tf
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/index.ts
  apis/api-media/src/schema/cloudflare/r2/index.ts
  apis/api-media/src/schema/cloudflare/r2/inputs/transcodeVideoInput.ts
  apis/api-media/src/schema/cloudflare/r2/transcode.spec.ts
  apis/api-media/src/schema/cloudflare/r2/transcode.ts
  apis/api-media/src/workers/assetTranscode/config.ts
  apis/media-transcoder/Dockerfile
  apis/media-transcoder/infrastructure/main.tf
  apis/media-transcoder/infrastructure/variables.tf
  apis/media-transcoder/jest.config.ts
  apis/media-transcoder/project.json
  apis/media-transcoder/src/main.spec.ts
  apis/media-transcoder/src/main.ts
  apis/media-transcoder/src/types/fluent-ffmpeg.d.ts
  apis/media-transcoder/src/types/fluent-ffmpeg.ts
  apis/media-transcoder/tsconfig.app.json
  apis/media-transcoder/tsconfig.json
  apis/media-transcoder/tsconfig.spec.json
  apis/media-transcoder/webpack.config.js
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  infrastructure/data.tf
  infrastructure/environments/prod/data.tf
  infrastructure/environments/prod/main.tf
  infrastructure/environments/stage/data.tf
  infrastructure/environments/stage/main.tf
  infrastructure/modules/aws/ecs-task/main.tf
  infrastructure/modules/aws/ecs-task/variables.tf
  package-lock.json
  package.json
Labels: priority: 2day, effort: 13, type: feat, on stage

#5416 feat: edition chip
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/VariantDialog.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/VideoEditionChip/VideoEditionChip.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/VideoEditionChip/VideoEditionChip.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/VideoEditionChip/index.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.tsx
  libs/locales/en/apps-videos-admin.json
Labels: type: fix, priority: soon, effort: 1

#5407 feat: create base edition on video create
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionCreate/EditionCreate.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionCreate/EditionCreate.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoCreateForm/VideoCreateForm.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoCreateForm/VideoCreateForm.tsx
  apps/videos-admin/src/libs/useCreateEdition/index.ts
  apps/videos-admin/src/libs/useCreateEdition/useCreateEdition.mock.tsx
  apps/videos-admin/src/libs/useCreateEdition/useCreateEdition.spec.tsx
  apps/videos-admin/src/libs/useCreateEdition/useCreateEdition.tsx
  libs/locales/en/apps-videos-admin.json
Labels: priority: soon, type: feat, effort: 1

#5388 refactor(watch): change header to match jesusfilm.org
  .storybook/main.ts
  apps/watch/pages/_app.tsx
  apps/watch/pages/calendar/index.tsx
  apps/watch/pages/fonts/Apercu-Pro-Bold.woff2
  apps/watch/pages/fonts/Apercu-Pro-BoldItalic.woff2
  apps/watch/pages/fonts/Apercu-Pro-Medium.woff2
  apps/watch/pages/fonts/Apercu-Pro-MediumItalic.woff2
  apps/watch/pages/fonts/Apercu-Pro-Regular.woff2
  apps/watch/pages/products/index.tsx
  apps/watch/public/watch/assets/fonts/apercu_bold.eot
  apps/watch/public/watch/assets/fonts/apercu_bold.otf
  apps/watch/public/watch/assets/fonts/apercu_bold.svg
  apps/watch/public/watch/assets/fonts/apercu_bold.ttf
  apps/watch/public/watch/assets/fonts/apercu_bold.woff
  apps/watch/public/watch/assets/fonts/apercu_bold.woff2
  apps/watch/public/watch/assets/fonts/apercu_light.eot
  apps/watch/public/watch/assets/fonts/apercu_light.svg
  apps/watch/public/watch/assets/fonts/apercu_light.ttf
  apps/watch/public/watch/assets/fonts/apercu_light.woff
  apps/watch/public/watch/assets/fonts/apercu_light.woff2
  apps/watch/public/watch/assets/fonts/apercu_regular.otf
  apps/watch/public/watch/assets/fonts/apercu_regular.svg
  apps/watch/public/watch/assets/fonts/apercu_regular.ttf
  apps/watch/public/watch/assets/fonts/apercu_regular.woff
  apps/watch/public/watch/assets/fonts/apercu_regular.woff2
  apps/watch/public/watch/assets/fonts/fonts.css
  apps/watch/src/components/DownloadDialog/DownloadDialog.tsx
  apps/watch/src/components/Footer/Footer.tsx
  apps/watch/src/components/Footer/FooterLink/FooterLink.tsx
  apps/watch/src/components/Header/BottomAppBar/BottomAppBar.spec.tsx
  apps/watch/src/components/Header/BottomAppBar/BottomAppBar.stories.tsx
  apps/watch/src/components/Header/BottomAppBar/BottomAppBar.tsx
  apps/watch/src/components/Header/BottomAppBar/index.ts
  apps/watch/src/components/Header/Header.spec.tsx
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderLinkAccordion/HeaderLinkAccordion.spec.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderLinkAccordion/HeaderLinkAccordion.stories.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderLinkAccordion/HeaderLinkAccordion.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderLinkAccordion/index.ts
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.spec.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.stories.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/headerLinks.ts
  apps/watch/src/components/Header/HeaderTabButtons/HeaderTabButtons.spec.tsx
  apps/watch/src/components/Header/HeaderTabButtons/HeaderTabButtons.tsx
  apps/watch/src/components/Header/LocalAppBar/LocalAppBar.spec.tsx
  apps/watch/src/components/Header/LocalAppBar/LocalAppBar.tsx
  apps/watch/src/components/Header/LocalAppBar/index.ts
  apps/watch/src/components/VideoCard/VideoCard.tsx
  apps/watch/src/components/VideoContentPage/VideoContent/VideoContent.tsx
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.tsx
  apps/watch/src/components/VideosPage/FilterList/FilterList.tsx
  apps/watch/src/components/VideosPage/FilterList/LanguagesFilter/LanguagesFilter.tsx
  libs/journeys/ui/src/components/EmptySearch/EmptySearch.spec.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
  libs/journeys/ui/src/components/SearchBar/SearchDropdown/Suggestions/Suggestion/Suggestion.tsx
  libs/locales/en/apps-watch.json
  libs/shared/ui/src/libs/themes/website/tokens/colors.ts
  libs/shared/ui/src/libs/themes/website/tokens/components.tsx
  libs/shared/ui/src/libs/themes/website/tokens/typography.ts
Labels: effort: 5, priority: now, type: refactor

#5422 refactor(watch): change watch footer to match jesusfilm.org
  apps/watch/public/watch/assets/footer/facebook.svg
  apps/watch/public/watch/assets/footer/instagram.svg
  apps/watch/public/watch/assets/footer/jesus-film-logo.png
  apps/watch/public/watch/assets/footer/x-twitter.svg
  apps/watch/public/watch/assets/footer/youtube.svg
  apps/watch/src/components/Footer/Footer.spec.tsx
  apps/watch/src/components/Footer/Footer.tsx
  apps/watch/src/components/Footer/FooterLink/FooterLink.spec.tsx
  apps/watch/src/components/Footer/FooterLink/FooterLink.tsx
  apps/watch/src/components/Footer/FooterLinks/FooterLinks.spec.tsx
  apps/watch/src/components/Footer/FooterLinks/FooterLinks.tsx
  apps/watch/src/components/Footer/FooterLinks/index.ts
  apps/watch/src/components/Footer/FooterLogos/FooterLogos.spec.tsx
  apps/watch/src/components/Footer/FooterLogos/FooterLogos.tsx
  apps/watch/src/components/Footer/FooterLogos/assets/cru.svg
  apps/watch/src/components/Footer/FooterLogos/assets/jesus-film.svg
  apps/watch/src/components/Footer/FooterLogos/index.ts
  apps/watch/src/components/Footer/FooterSocials/FooterSocials.spec.tsx
  apps/watch/src/components/Footer/FooterSocials/FooterSocials.tsx
  apps/watch/src/components/Footer/FooterSocials/assets/facebook.svg
  apps/watch/src/components/Footer/FooterSocials/assets/instagram.svg
  apps/watch/src/components/Footer/FooterSocials/assets/twitter.svg
  apps/watch/src/components/Footer/FooterSocials/assets/youtube.svg
  apps/watch/src/components/Footer/FooterSocials/index.ts
  libs/locales/en/apps-watch.json
  prds/A-README.md
  prds/ENG-1939.md
Labels: priority: now, effort: 1, type: refactor, on stage

#5423 refactor: use environment variable for Algolia index prefix
  .github/workflows/crowdin.yml
  apps/watch/src/components/ResourcesView/ResourceSections/ResourceSections.tsx
Labels: priority: now, effort: 1, type: refactor, on stage

#5443 chore: update worker to handle new routes on prod
  workers/jf-proxy/wrangler.toml
Labels: priority: now, effort: 1, type: chore

#5187 chore: remove PR template and update Dangerfile and workflow documentation
  .github/pull_request_template.md
  apps/docs/docs/04-engineering-practices/01-workflow/index.md
  dangerfile.ts
Labels: priority: 2day, effort: 1, type: chore

#5451 fix(watch): mobile tab buttons full width
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderLinkAccordion/HeaderLinkAccordion.tsx
  apps/watch/src/components/Header/HeaderTabButtons/HeaderTabButtons.spec.tsx
  apps/watch/src/components/Header/HeaderTabButtons/HeaderTabButtons.tsx
  libs/shared/ui/src/libs/themes/website/tokens/colors.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#5453 fix(watch): fix close button overlap for side menu
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderLinkAccordion/HeaderLinkAccordion.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx
  apps/watch/src/components/Header/LocalAppBar/LocalAppBar.tsx
Labels: type: fix, priority: now, effort: 1, on stage

#5459 fix: fallback to iso3 if no bcp47
  apps/arclight/src/app/v2/[...route]/_resources/index.ts
Labels: type: fix, priority: soon, effort: 1

#5463 fix(watch): show three lines on desktop
  apps/watch/src/components/ResourcesView/ResourceSections/ResourceCard/ResourceCard.tsx
Labels: type: fix, priority: now, effort: 1, on stage

#5466 fix(watch): give now button position
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx
Labels: type: fix, priority: now, effort: 1, on stage

#5464 feat: create asset relations
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/db/migrations/20250307011005_20250307010956/migration.sql
  apis/api-media/db/schema.prisma
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/__generated__/pothos-types.ts
  apis/api-media/src/schema/video/video.spec.ts
  apis/api-media/src/schema/video/videoSubtitle/inputs/videoSubtitleCreate.ts
  apis/api-media/src/schema/video/videoSubtitle/inputs/videoSubtitleUpdate.ts
  apis/api-media/src/schema/video/videoSubtitle/videoSubtitle.spec.ts
  apis/api-media/src/schema/video/videoSubtitle/videoSubtitle.ts
  apis/api-media/src/schema/videoVariant/inputs/videoVariantCreate.ts
  apis/api-media/src/schema/videoVariant/inputs/videoVariantUpdate.ts
  apis/api-media/src/schema/videoVariant/videoVariant.spec.ts
  apis/api-media/src/schema/videoVariant/videoVariant.ts
  apis/api-media/src/schema/videoVariant/videoVariantDownload/inputs/videoVariantDownloadCreate.ts
  apis/api-media/src/schema/videoVariant/videoVariantDownload/inputs/videoVariantDownloadUpdate.ts
  apis/api-media/src/schema/videoVariant/videoVariantDownload/videoVariantDownload.spec.ts
  apis/api-media/src/schema/videoVariant/videoVariantDownload/videoVariantDownload.ts
  apis/api-media/src/workers/assetTranscode/config.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 5, priority: soon, type: feat, on stage

#5477 fix(watch): video hero height calculation
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
Labels: type: fix, priority: now, effort: 1

#5470 fix(watch): side menu overscroll behaviour
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx
Labels: type: fix, priority: now, effort: 1, on stage

#5480 fix(watch): fade on bottom app bar
  apps/watch/src/components/Header/BottomAppBar/BottomAppBar.stories.tsx
  apps/watch/src/components/Header/BottomAppBar/BottomAppBar.tsx
  apps/watch/src/components/Header/Header.stories.tsx
  apps/watch/src/components/Header/Header.tsx
  apps/watch/src/components/Header/LocalAppBar/LocalAppBar.tsx
Labels: type: fix, effort: 3, priority: now

#5494 chore(deps): update MUI X packages to latest versions
  package-lock.json
  package.json
Labels: on stage

#5324 feat: sorting journeys by when they were last updated
  apps/journeys-admin/__generated__/GetAdminJourneys.ts
  apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActiveJourneyListData.ts
  apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardText/JourneyCardText.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardText/JourneyCardText.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardText/LastModifiedDate/LastModifiedDate.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardText/LastModifiedDate/LastModifiedDate.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardText/LastModifiedDate/index.ts
  apps/journeys-admin/src/components/JourneyList/JourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
  apps/journeys-admin/src/components/JourneyList/JourneySort/JourneySort.spec.tsx
  apps/journeys-admin/src/components/JourneyList/JourneySort/JourneySort.tsx
  apps/journeys-admin/src/components/JourneyList/JourneySort/utils/sortJourneys.spec.ts
  apps/journeys-admin/src/components/JourneyList/JourneySort/utils/sortJourneys.ts
  apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.spec.tsx
  apps/journeys-admin/src/components/JourneyList/journeyListData.ts
  apps/journeys-admin/src/components/TemplateList/ActiveTemplateList/ActiveTemplateList.spec.tsx
  apps/journeys-admin/src/components/TemplateList/ArchivedTemplateList/ArchivedTemplateList.spec.tsx
  apps/journeys-admin/src/components/TemplateList/TemplateListItem/TemplateListItem.spec.tsx
  apps/journeys-admin/src/components/TemplateList/TemplateListItem/TemplateListItem.tsx
  apps/journeys-admin/src/components/TemplateList/TrashedTemplateList/TrashedTemplateList.spec.tsx
  apps/journeys-admin/src/components/TemplateList/data.ts
  apps/journeys-admin/src/libs/useAdminJourneysQuery/useAdminJourneysQuery.ts
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, effort: 5, effort: 3, priority: now, priority: soon, type: feat, chromatic

#5517 refactor: remove prettier render options in email services
  apis/api-journeys-modern/src/workers/email/service/service.ts
  apis/api-journeys-modern/src/workers/emailEvents/service/service.ts
  apis/api-users/src/workers/email/service/service.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/docs/docs/03-basics/02-backend/03-transactional-emails.md
Labels: on stage

#5440 fix(watch): update links in side menu
  apps/watch/src/components/Header/HeaderMenuPanel/headerLinks.ts
Labels: type: fix, priority: soon, effort: 1, on stage

#5514 fix(watch): hide header on fullscreen video
  apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
Labels: type: fix, priority: now, effort: 1

#4853 feat: fix missing messages error for translations that exist
  apps/videos-admin/i18n/request.ts
  apps/videos-admin/src/components/NavbarBreadcrumbs/NavbarBreadcrumbs.tsx
Labels: type: fix, priority: soon, effort: 1

#5382 feat: add VideoStats component for live playback statistics reporting
  libs/journeys/ui/src/components/Video/VideoControls/DesktopControls/DesktopControls.tsx
  libs/journeys/ui/src/components/Video/VideoControls/MobileControls/MobileControls.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoSettings/QualityMenu/QualityMenu.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoSettings/SettingsMenu/SettingsMenu.spec.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoSettings/SettingsMenu/SettingsMenu.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoSettings/VideoSettings.spec.tsx
  libs/journeys/ui/src/components/Video/VideoControls/VideoSettings/VideoSettings.tsx
  libs/journeys/ui/src/components/Video/VideoStats/VideoStats.spec.tsx
  libs/journeys/ui/src/components/Video/VideoStats/VideoStats.tsx
  libs/journeys/ui/src/components/Video/VideoStats/index.ts
  libs/journeys/ui/src/components/Video/utils/videoJsTypes/Html5.ts
  libs/journeys/ui/src/components/Video/utils/videoJsTypes/YoutubeTech.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/calculateHtml5Bitrate/calculateHtml5Bitrate.spec.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/calculateHtml5Bitrate/calculateHtml5Bitrate.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/calculateHtml5Bitrate/index.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/formatTime/formatTime.spec.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/formatTime/formatTime.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/formatTime/index.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/formatTimeRanges/formatTimeRanges.spec.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/formatTimeRanges/formatTimeRanges.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/formatTimeRanges/index.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/getHtml5CurrentQuality/getHtml5CurrentQuality.spec.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/getHtml5CurrentQuality/getHtml5CurrentQuality.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/getHtml5CurrentQuality/index.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/getHtml5FrameRate/getHtml5FrameRate.spec.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/getHtml5FrameRate/getHtml5FrameRate.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/getHtml5FrameRate/index.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/getHtml5Stats/getHtml5Stats.spec.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/getHtml5Stats/getHtml5Stats.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/getHtml5Stats/index.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/getYoutubeStats/getYoutubeStats.spec.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/getYoutubeStats/getYoutubeStats.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/getYoutubeStats/index.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/index.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/isHtml5Tech/index.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/isHtml5Tech/isHtml5Tech.spec.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/isHtml5Tech/isHtml5Tech.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/isYoutubeTech/index.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/isYoutubeTech/isYoutubeTech.spec.ts
  libs/journeys/ui/src/components/Video/utils/videoStatsUtils/isYoutubeTech/isYoutubeTech.ts
  libs/journeys/ui/src/components/Video/utils/youtubeQualityMap/index.ts
  libs/journeys/ui/src/components/Video/utils/youtubeQualityMap/youtubeQualityMap.ts
  libs/locales/en/libs-journeys-ui.json
Labels: effort: 2, type: fix, Performance

#5553 fix: bad type generator for api-journeys
  apis/api-journeys/src/app/__generated__/graphql.ts
  tools/scripts/generate-typings.ts
Labels: on stage

#5359 feat: create video variants
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/AddAudioLanguageDialog/AddAudioLanguageDialog.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/AddAudioLanguageDialog/AddAudioLanguageDialog.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/AddAudioLanguageDialog/AddAudioLanguageDialog.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/AddAudioLanguageDialog/AudioLanguageFileUpload/AudioLanguageFileUpload.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/AddAudioLanguageDialog/AudioLanguageFileUpload/AudioLanguageFileUpload.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/AddAudioLanguageDialog/AudioLanguageFileUpload/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/AddAudioLanguageDialog/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/AddAudioLanguageDialog/utils/getExtension.spec.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/AddAudioLanguageDialog/utils/getExtension.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/VariantDialog.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/VariantDialog.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
  apps/videos-admin/src/app/[locale]/layout.tsx
  apps/videos-admin/src/libs/UploadVideoVariantProvider/UploadVideoVariantProvider.spec.tsx
  apps/videos-admin/src/libs/UploadVideoVariantProvider/UploadVideoVariantProvider.tsx
  apps/videos-admin/src/libs/UploadVideoVariantProvider/index.ts
  apps/videos-admin/src/libs/useAdminVideo/index.ts
  libs/locales/en/apps-videos-admin.json
  libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.tsx
Labels: effort: 2, effort: 5, effort: 3, priority: now, priority: soon, type: feat, effort: 1, on stage

#5419 fix: display proper video variant hls
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/VariantDialog.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantVideo/VariantVideo.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantVideo/VariantVideo.tsx
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.tsx
  libs/locales/en/apps-videos-admin.json
Labels: type: fix, priority: soon, effort: 1

#5556 feat: generate high quality variant download from mux endpoint
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/mux/video/service.ts
  apis/api-media/src/schema/mux/video/video.spec.ts
  apis/api-media/src/schema/mux/video/video.ts
  apps/api-journeys/src/app/__generated__/graphql.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#5404 feat: audio languages delete
  .cursor/rules/apps.mdc
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/DeleteVariantDialog/DeleteVariantDialog.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/DeleteVariantDialog/DeleteVariantDialog.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/DeleteVariantDialog/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
  apps/videos-admin/src/libs/useDeleteVideoVariantMutation/index.ts
  apps/videos-admin/src/libs/useDeleteVideoVariantMutation/useDeleteVideoVariantMutation.spec.tsx
  apps/videos-admin/src/libs/useDeleteVideoVariantMutation/useDeleteVideoVariantMutation.ts
  libs/locales/en/apps-videos-admin.json
Labels: priority: soon, type: feat, effort: 1

#5555 feat: upload video variant download from raw
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/Subtitles/SubtitleDialog/SubtitleCreate/SubtitleCreate.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/Subtitles/SubtitleForm/SubtitleFileUpload/SubtitleFileUpload.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImage/FileUpload/FileUpload.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantCard/VariantCard.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/Downloads/AddVideoVariantDownloadDialog/AddVideoVariantDownloadDialog.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/Downloads/AddVideoVariantDownloadDialog/AddVideoVariantDownloadDialog.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/Downloads/AddVideoVariantDownloadDialog/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/Downloads/ConfirmDeleteDialog/ConfirmDeleteDialog.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/Downloads/ConfirmDeleteDialog/ConfirmDeleteDialog.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/Downloads/ConfirmDeleteDialog/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/Downloads/Downloads.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/Downloads/Downloads.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/Downloads/Downloads.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/VariantDialog.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/VariantDialog/VariantDialog.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts
  apps/videos-admin/src/libs/useCreateR2Asset/index.ts
  apps/videos-admin/src/libs/useCreateR2Asset/uploadAssetFile/index.ts
  apps/videos-admin/src/libs/useCreateR2Asset/uploadAssetFile/uploadAssetFile.spec.tsx
  apps/videos-admin/src/libs/useCreateR2Asset/uploadAssetFile/uploadAssetFile.tsx
  apps/videos-admin/src/libs/useVideoVariantDownloadCreateMutation/index.ts
  apps/videos-admin/src/libs/useVideoVariantDownloadCreateMutation/useVideoVariantDownloadCreateMutation.mock.ts
  apps/videos-admin/src/libs/useVideoVariantDownloadCreateMutation/useVideoVariantDownloadCreateMutation.spec.tsx
  apps/videos-admin/src/libs/useVideoVariantDownloadCreateMutation/useVideoVariantDownloadCreateMutation.tsx
  apps/videos-admin/src/libs/useVideoVariantDownloadDeleteMutation/useVideoVariantDownloadDeleteMutation.mock.ts
  apps/videos-admin/src/libs/useVideoVariantDownloadDeleteMutation/useVideoVariantDownloadDeleteMutation.spec.tsx
  apps/videos-admin/src/libs/useVideoVariantDownloadDeleteMutation/useVideoVariantDownloadDeleteMutation.tsx
  apps/videos-admin/src/libs/useVideoVariantDownloadUpdate/index.ts
  apps/videos-admin/src/libs/useVideoVariantDownloadUpdate/useVideoVariantDownloadUpdate.mock.ts
  apps/videos-admin/src/libs/useVideoVariantDownloadUpdate/useVideoVariantDownloadUpdate.spec.tsx
  apps/videos-admin/src/libs/useVideoVariantDownloadUpdate/useVideoVariantDownloadUpdate.tsx
  libs/locales/en/apps-videos-admin.json
Labels: type: fix, effort: 3, priority: soon

#5716 feat: api languages data exporter
  .gitignore
  apis/api-languages/Dockerfile
  apis/api-languages/infrastructure/locals.tf
  apis/api-languages/project.json
  apis/api-languages/src/workers/cli.spec.ts
  apis/api-languages/src/workers/cli.ts
  apis/api-languages/src/workers/dataExport/config.ts
  apis/api-languages/src/workers/dataExport/index.ts
  apis/api-languages/src/workers/dataExport/service/index.ts
  apis/api-languages/src/workers/dataExport/service/service.spec.ts
  apis/api-languages/src/workers/dataExport/service/service.ts
  apis/api-languages/src/workers/server.ts
Labels: on stage

#5748 fix: disallow duplicates in bible citations
  apis/api-media/db/migrations/20250318152126_update_bible_citation_nulls/migration.sql
  apis/api-media/db/migrations/20250318152127_update_bible_citation_values.sql
  apis/api-media/db/migrations/20250318152249_biblecitation/migration.sql
  apis/api-media/db/schema.prisma
  apis/api-media/src/schema/bibleCitation/bibleCitation.spec.ts
  apis/api-media/src/schema/bibleCitation/bibleCitation.ts
  apis/api-media/src/schema/video/video.spec.ts
  apis/api-media/src/workers/bigQuery/importers/bibleCitations/bibleCitations.spec.ts
  apis/api-media/src/workers/bigQuery/importers/bibleCitations/bibleCitations.ts
Labels: on stage

#5743 feat: add submitEnabled field to ButtonBlock schema
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/db/migrations/20250318224433_20250318224431/migration.sql
  apis/api-journeys/db/migrations/20250318232149_20250318232147/migration.sql
  apis/api-journeys/db/migrations/migration_lock.toml
  apis/api-journeys/db/schema.prisma
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/block/button/button.graphql
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: now, type: feat, on stage

#5753 feat: update textResponse block schema
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/db/migrations/20250318232552_20250318232550/migration.sql
  apis/api-journeys/db/schema.prisma
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/block/textResponse/textResponse.graphql
  apis/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.spec.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  apps/watch/__generated__/globalTypes.ts
  libs/journeys/ui/__generated__/globalTypes.ts
Labels: effort: 5, priority: now, type: feat, on stage

#5775 fix: fix api-languages data-import/export
  apis/api-languages/project.json
  apis/api-languages/src/scripts/README.md
  apis/api-languages/src/scripts/data-import.spec.ts
  apis/api-languages/src/scripts/data-import.ts
  apis/api-languages/src/workers/cli.spec.ts
  apis/api-languages/src/workers/cli.ts
  apis/api-languages/src/workers/dataExport/service/service.spec.ts
  apis/api-languages/src/workers/dataExport/service/service.ts
  apis/api-languages/src/workers/dataImport/config.ts
  apis/api-languages/src/workers/dataImport/index.ts
  apis/api-languages/src/workers/dataImport/service/index.ts
  apis/api-languages/src/workers/dataImport/service/service.spec.ts
  apis/api-languages/src/workers/dataImport/service/service.ts
  apis/api-languages/src/workers/server.ts
  apps/docs/docs/02-getting-started/03-microservice-databases.mdx
Labels: on stage

#5782 feat: add submitEnabled to generated types
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: now, type: feat, effort: 1

#5750 feat: api media data exporter
  apis/api-media/Dockerfile
  apis/api-media/project.json
  apis/api-media/src/workers/cli.ts
  apis/api-media/src/workers/crowdin/service/service.spec.ts
  apis/api-media/src/workers/dataExport/config.ts
  apis/api-media/src/workers/dataExport/index.ts
  apis/api-media/src/workers/dataExport/service/index.ts
  apis/api-media/src/workers/dataExport/service/service.spec.ts
  apis/api-media/src/workers/dataExport/service/service.ts
  apis/api-media/src/workers/server.ts
Labels: on stage

#5784 chore: remove placeholder
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/db/migrations/20250320042159_20250320042156/migration.sql
  apis/api-journeys/db/schema.prisma
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/block/textResponse/textResponse.graphql
  apis/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.spec.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: soon, effort: 1, type: chore, on stage

#5835 feat: enhance data export service to exclude publications and subscri…
  apis/api-languages/src/workers/dataExport/service/service.spec.ts
  apis/api-languages/src/workers/dataExport/service/service.ts
  apis/api-media/src/workers/dataExport/service/service.spec.ts
  apis/api-media/src/workers/dataExport/service/service.ts
Labels: on stage

#5814 chore(deps): remove jsonwebtoken dependency from package.json and pac…
  package-lock.json
  package.json
Labels: on stage

#5818 chore(deps): remove react-is dependency from package.json and package…
  package-lock.json
  package.json
Labels: on stage

#5846 feat: add placeholder to block
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/db/migrations/20250324005642_20250324005640/migration.sql
  apis/api-journeys/db/schema.prisma
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/block/textResponse/textResponse.graphql
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: now, type: feat, effort: 1, on stage

#5853 chore(deps): update next and related packages to version 14.2.25
  package-lock.json
  package.json
Labels: on stage

#5842 feat: add originalFilename field to CloudflareR2 model and update rel…
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/db/migrations/20250324232337_20250324232334/migration.sql
  apis/api-media/db/schema.prisma
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/cloudflare/r2/asset.spec.ts
  apis/api-media/src/schema/cloudflare/r2/asset.ts
  apis/api-media/src/schema/cloudflare/r2/inputs/cloudflareR2Create.ts
  apis/api-media/src/schema/cloudflare/r2/transcode.spec.ts
  apis/api-media/src/schema/video/video.spec.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#5824 chore(deps): remove @apollo/server-plugin-response-cache from depende…
  package-lock.json
  package.json
Labels: on stage

#5828 chore(deps): remove regenerator-runtime from package.json and package…
  package-lock.json
  package.json
Labels: on stage

#5829 feat: journey events endpoint
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/db/migrations/20250324000805_20250324000803/migration.sql
  apis/api-journeys/db/schema.prisma
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/app.module.ts
  apis/api-journeys/src/app/lib/casl/caslFactory/caslFactory.ts
  apis/api-journeys/src/app/modules/event/button/button.resolver.spec.ts
  apis/api-journeys/src/app/modules/event/button/button.resolver.ts
  apis/api-journeys/src/app/modules/event/event.acl.spec.ts
  apis/api-journeys/src/app/modules/event/event.acl.ts
  apis/api-journeys/src/app/modules/event/event.module.ts
  apis/api-journeys/src/app/modules/event/journey/journey.resolver.spec.ts
  apis/api-journeys/src/app/modules/event/journey/journey.resolver.ts
  apis/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.spec.ts
  apis/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.ts
  apis/api-journeys/src/app/modules/event/signUp/signUp.resolver.spec.ts
  apis/api-journeys/src/app/modules/event/signUp/signUp.resolver.ts
  apis/api-journeys/src/app/modules/event/step/step.resolver.spec.ts
  apis/api-journeys/src/app/modules/event/step/step.resolver.ts
  apis/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.ts
  apis/api-journeys/src/app/modules/event/video/video.resolver.spec.ts
  apis/api-journeys/src/app/modules/event/video/video.resolver.ts
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.graphql
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.module.ts
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.resolver.spec.ts
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.resolver.ts
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.service.spec.ts
  apis/api-journeys/src/app/modules/journeyEvent/journeyEvent.service.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/GetJourneyVisitors.ts
  apps/journeys-admin/__generated__/GetVisitorEvents.ts
  apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/utils/transformEvents/transformEvents.spec.tsx
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: on stage

#5884 test: update checkly tests and deps
  apps/journeys-admin-e2e/src/monitoring/journeys-admin.monitor.ts
  apps/journeys-e2e/src/monitoring/journeys.monitor.ts
  apps/watch-e2e/src/monitoring/watch-redirection.monitor.ts
  apps/watch-e2e/src/monitoring/watch.monitor.ts
  checkly.config.ts
  package-lock.json
  package.json
Labels: type: test, effort: 5, priority: soon

#5776 refactor: visitors side panel
  apps/journeys-admin/pages/journeys/[journeyId]/reports/visitors.tsx
  apps/journeys-admin/src/components/JourneyVisitorsList/FilterDrawer/FilterDrawer.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: priority: soon, type: feat, effort: 1

#5886 fix: delete broken migrations
  apis/api-media/db/migrations/20250318152126_update_bible_citation_nulls/migration.sql
  apis/api-media/db/migrations/20250318152127_update_bible_citation_values.sql
  apis/api-media/db/migrations/20250318152249_biblecitation/migration.sql
Labels: on stage

#5908 feat: add importVideoImages to service execution order
  apis/api-media/src/workers/bigQuery/service/service.ts
Labels: on stage

#5916 feat: duplicate button block set to false
  apis/api-journeys/src/app/modules/block/block.service.spec.ts
  apis/api-journeys/src/app/modules/block/block.service.ts
Labels: effort: 2, priority: soon, type: feat, on stage

#5909 fix: and update qr code permissions
  apis/api-journeys/src/app/modules/qrCode/qrCode.acl.spec.ts
  apis/api-journeys/src/app/modules/qrCode/qrCode.acl.ts
Labels: on stage

#5941 fix: bible citation migration
  apis/api-media/db/migrations/20250330162514_20250330162505/migration.sql
  apis/api-media/db/schema.prisma
  apis/api-media/src/schema/bibleCitation/bibleCitation.ts
Labels: on stage

#5942 fix: revert behavior of submit button being set to false during duplication
  apis/api-journeys/src/app/modules/block/block.service.spec.ts
  apis/api-journeys/src/app/modules/block/block.service.ts
Labels: type: fix, priority: now, effort: 1, No QA

#5917 feat: add phone field to Visitor schema
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/db/migrations/20250326232926_20250326232924/migration.sql
  apis/api-journeys/db/schema.prisma
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.spec.ts
  apis/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.ts
  apis/api-journeys/src/app/modules/journeyVisitor/journeyVisitor.resolver.spec.ts
  apis/api-journeys/src/app/modules/visitor/visitor.graphql
  apis/api-journeys/src/app/modules/visitor/visitor.resolver.spec.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys/__generated__/globalTypes.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 2, priority: soon, type: feat, on stage
