Repository JesusFilm/core, pull requests merged in 2025-02, with the labels that each got.

#5079 chore: remove unused react-router-dom
  package-lock.json
  package.json
Labels: priority: 2day, effort: 1, type: chore

#5092 refactor: create shortlink with id input
  apps/api-analytics/src/__generated__/graphql-env.d.ts
  apps/api-gateway/schema.graphql
  apps/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apps/api-journeys/src/__generated__/graphql.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.resolver.spec.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.resolver.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.service.spec.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.service.ts
  apps/api-languages/src/__generated__/graphql-env.d.ts
  apps/api-media/schema.graphql
  apps/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/api-media/src/schema/shortLink/shortLink.spec.ts
  apps/api-media/src/schema/shortLink/shortLink.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: now, effort: 1, type: refactor, on stage

#5115 chore: update node to 22
  .devcontainer/Dockerfile
  nx.json
Labels: priority: now, effort: 1, type: chore

#4424 feat: move resources to use algolia no qa
  apps/api-languages/infrastructure/locals.tf
  apps/api-languages/project.json
  apps/api-languages/src/workers/algolia/config.ts
  apps/api-languages/src/workers/algolia/index.ts
  apps/api-languages/src/workers/algolia/service/index.ts
  apps/api-languages/src/workers/algolia/service/service.spec.ts
  apps/api-languages/src/workers/algolia/service/service.ts
  apps/api-languages/src/workers/cli.ts
  apps/api-languages/src/workers/server.ts
  apps/api-media/infrastructure/locals.tf
  apps/api-media/src/workers/algolia/service/service.spec.ts
  apps/api-media/src/workers/algolia/service/service.ts
  apps/arclight/src/app/v2/resources/route.ts
Labels: priority: soon, type: feat, effort: 1

#5126 chore: update journeys modern api env
  apps/api-journeys-modern/infrastructure/locals.tf
Labels: priority: soon, effort: 1, type: chore, Chore

#5129 fix: dynamic updates
  apps/api-journeys/src/app/modules/customDomain/customDomain.resolver.ts
  apps/api-journeys/src/app/modules/journey/journey.resolver.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.resolver.spec.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.resolver.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.service.spec.ts
  apps/api-journeys/src/app/modules/qrCode/qrCode.service.ts
Labels: type: fix, effort: 3, priority: now, on stage

#5136 feat: github cli
  .devcontainer/devcontainer.json
Labels: priority: now, type: feat, effort: 1

#5134 fix: add arclight vars
  apps/arclight/infrastructure/locals.tf
Labels: type: fix, priority: soon, effort: 1

#5110 feat: create video from frontend
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoCreateForm/VideoCreateForm.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoCreateForm/VideoCreateForm.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoCreateForm/VideoCreateForm.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoCreateForm/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoList.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoListHeader/VideoListHeader.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoListHeader/VideoListHeader.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoListHeader/VideoListHeader.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoListHeader/index.ts
  apps/videos-admin/src/components/FormSelectField/FormSelectField.spec.tsx
  apps/videos-admin/src/components/FormSelectField/FormSelectField.stories.tsx
  apps/videos-admin/src/components/FormSelectField/FormSelectField.tsx
  apps/videos-admin/src/components/FormSelectField/index.ts
  apps/videos-admin/src/components/FormTextField/FormTextField.spec.tsx
  apps/videos-admin/src/components/FormTextField/FormTextField.stories.tsx
  apps/videos-admin/src/components/FormTextField/FormTextField.tsx
  apps/videos-admin/src/components/FormTextField/index.ts
  apps/videos-admin/src/constants.ts
  libs/locales/en/apps-videos-admin.json
Labels: effort: 2, priority: soon, type: feat

#5143 fix: incorrect margins
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/DragItemWrapper/DragItemWrapper.tsx
  apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/utils/calculateDimensions/calculateDimensions.ts
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.tsx
  libs/journeys/ui/src/components/Card/OverlayContent/OverlayContent.tsx
Labels: type: fix, priority: now, effort: 1, chromatic

#5170 fix: make media component endpoint faster
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/db/migrations/20250211141012_20250211141009/migration.sql
  apis/api-media/db/schema.prisma
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/video/video.spec.ts
  apis/api-media/src/schema/video/video.ts
  apis/api-media/src/schema/videoVariant/videoVariant.ts
  apis/api-media/src/workers/bigQuery/importers/videoVariants/videoVariants.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 2, type: fix, effort: 3, priority: soon, type: feat, effort: 1

#5172 refactor: remove hardcoded bandwidth settings in video player options
  libs/shared/ui/src/libs/defaultVideoJsOptions/defaultVideoJsOptions.spec.ts
  libs/shared/ui/src/libs/defaultVideoJsOptions/defaultVideoJsOptions.ts
Labels: priority: 2day, effort: 1, type: refactor

#5176 fix: env vars
  apps/arclight/infrastructure/locals.tf
Labels: type: fix, priority: soon, effort: 1

#5181 chore: remove tracing preview feature and update media schema
  apis/api-analytics/db/schema.prisma
  apis/api-journeys-modern/db/schema.prisma
  apis/api-languages/db/schema.prisma
  apis/api-media/db/migrations/20250211213415_20250211213409/migration.sql
  apis/api-media/db/migrations/migration_lock.toml
  apis/api-media/db/schema.prisma
  apis/api-media/src/schema/video/video.spec.ts
  apis/api-media/src/schema/video/video.ts
  apis/api-users/db/schema.prisma
Labels: effort: 2, type: fix, effort: 3, priority: soon, type: feat, effort: 1, type: chore

#5213 revert: update graphql-hive-gateway monorepo (#5206)
  package-lock.json
Labels: priority: 2day, type: fix, effort: 1

#5203 chore(deps): remove @parcel/watcher dependency
  package-lock.json
  package.json
Labels: priority: 2day, effort: 1, type: chore

#5220 chore(deps): remove canvas dependency
  package-lock.json
  package.json
Labels: priority: 2day, effort: 1, type: chore

#5233 chore(deps): remove @nestjs/bull dependency
  package-lock.json
  package.json
Labels: priority: 2day, effort: 1, type: chore, on stage

#5237 chore(deps): remove supports-color dependency
  package-lock.json
  package.json
Labels: priority: 2day, effort: 1, type: chore

#5229 feat: add update journey updated at for step position updates
  apis/api-journeys/src/app/modules/block/step/step.resolver.spec.ts
  apis/api-journeys/src/app/modules/block/step/step.resolver.ts
Labels: priority: now, type: feat, effort: 1, on stage

#5061 feat: qr code create and edit
  apps/journeys-admin/__generated__/GetJourneyQrCodes.ts
  apps/journeys-admin/__generated__/GetPlausibleJourneyQrCodeScans.ts
  apps/journeys-admin/__generated__/NewQrCode.ts
  apps/journeys-admin/__generated__/QrCodeCreate.ts
  apps/journeys-admin/__generated__/QrCodeFields.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeActionButton/CodeActionButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeActionButton/CodeActionButton.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeActionButton/CodeActionButton.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeActionButton/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeCanvas/CodeCanvas.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeCanvas/CodeCanvas.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeCanvas/CodeCanvas.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeCanvas/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/ChangeButton/ChangeButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/ChangeButton/ChangeButton.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/ChangeButton/ChangeButton.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/ChangeButton/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/CodeDestination.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/CodeDestination.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/CodeDestination.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/CodeDestinationPopper/CodeDestinationPopper.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/CodeDestinationPopper/CodeDestinationPopper.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/CodeDestinationPopper/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/CodeDestination/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/DownloadQrCode/DownloadQrCode.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/DownloadQrCode/DownloadQrCode.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/DownloadQrCode/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/QrCodeDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/QrCodeDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/QrCodeDialog.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/RedirectDialog/RedirectDialog.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/RedirectDialog/RedirectDialog.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/RedirectDialog/RedirectDialog.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/RedirectDialog/index.ts
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/ScanCount/ScanCount.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/ScanCount/ScanCount.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/ScanCount/ScanCount.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/qrCodeFields.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 5, priority: soon, type: feat

#5245 feat: add seed for available languages
  apis/api-media/src/workers/seed/service/service.spec.ts
  apis/api-media/src/workers/seed/service/service.ts
  apis/api-media/src/workers/seed/service/videoLanguage/index.ts
  apis/api-media/src/workers/seed/service/videoLanguage/videoLanguage.ts
Labels: effort: 2, effort: 3, priority: soon, type: feat

#5249 fix: migrations on main
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/db/migrations/20250213173156_20250213173153/migration.sql
  apis/api-languages/db/migrations/migration_lock.toml
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 2, type: fix, effort: 3, priority: soon, effort: 1, type: chore

#4229 chore: new crowdin translations
  libs/locales/am-ET/apps-journeys-admin.json
  libs/locales/am-ET/apps-videos-admin.json
  libs/locales/ar-SA/apps-journeys-admin.json
  libs/locales/ar-SA/apps-videos-admin.json
  libs/locales/ar-SA/apps-watch.json
  libs/locales/ar-SA/libs-journeys-ui.json
  libs/locales/bn-BD/apps-journeys-admin.json
  libs/locales/bn-BD/apps-videos-admin.json
  libs/locales/es-ES/apps-journeys-admin.json
  libs/locales/es-ES/apps-videos-admin.json
  libs/locales/fr-FR/apps-journeys-admin.json
  libs/locales/fr-FR/apps-videos-admin.json
  libs/locales/hi-IN/apps-journeys-admin.json
  libs/locales/hi-IN/apps-videos-admin.json
  libs/locales/id-ID/apps-journeys-admin.json
  libs/locales/id-ID/apps-videos-admin.json
  libs/locales/ja-JP/apps-journeys-admin.json
  libs/locales/ja-JP/apps-videos-admin.json
  libs/locales/ko-KR/apps-journeys-admin.json
  libs/locales/ko-KR/apps-videos-admin.json
  libs/locales/my-MM/apps-journeys-admin.json
  libs/locales/my-MM/apps-videos-admin.json
  libs/locales/ru-RU/apps-journeys-admin.json
  libs/locales/ru-RU/apps-videos-admin.json
  libs/locales/th-TH/apps-journeys-admin.json
  libs/locales/th-TH/apps-videos-admin.json
  libs/locales/tl-PH/apps-journeys-admin.json
  libs/locales/tl-PH/apps-videos-admin.json
  libs/locales/tr-TR/apps-journeys-admin.json
  libs/locales/tr-TR/apps-videos-admin.json
  libs/locales/ur-PK/apps-journeys-admin.json
  libs/locales/ur-PK/apps-videos-admin.json
  libs/locales/vi-VN/apps-journeys-admin.json
  libs/locales/vi-VN/apps-videos-admin.json
  libs/locales/zh-Hans-CN/apps-journeys-admin.json
  libs/locales/zh-Hans-CN/apps-videos-admin.json
  libs/locales/zh-Hant-TW/apps-docs.json
  libs/locales/zh-Hant-TW/apps-journeys-admin.json
  libs/locales/zh-Hant-TW/apps-journeys.json
  libs/locales/zh-Hant-TW/apps-videos-admin.json
  libs/locales/zh-Hant-TW/apps-watch.json
  libs/locales/zh-Hant-TW/libs-journeys-ui.json
Labels: priority: soon, effort: 1, type: chore

#5216 fix: update routes to use normalized languages
  apps/arclight/src/app/v2/media-component-links/[mediaComponentId]/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/[languageId]/route.ts
  apps/arclight/src/app/v2/media-components/[mediaComponentId]/route.ts
  apps/arclight/src/app/v2/media-components/route.ts
Labels: effort: 2, type: fix, priority: soon, effort: 1

#5247 fix: video languages normalization
  apis/api-media/src/workers/bigQuery/importers/videoVariants/videoVariants.spec.ts
  apis/api-media/src/workers/bigQuery/importers/videoVariants/videoVariants.ts
Labels: effort: 2, type: fix, effort: 3, priority: soon, effort: 1

#5258 fix: algolia issues with arclight resources
  apps/arclight-e2e/src/e2e/resources/index.spec.ts
  apps/arclight/src/app/v2/resources/route.ts
Labels: effort: 2, type: fix, priority: soon, effort: 1

#5267 feat: add muxVideo relationship to videoVariant
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/db/migrations/20250214191828_20250214191824/migration.sql
  apis/api-media/db/schema.prisma
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/__generated__/pothos-types.ts
  apis/api-media/src/schema/mux/video/video.spec.ts
  apis/api-media/src/schema/mux/video/video.ts
  apis/api-media/src/schema/video/video.spec.ts
  apis/api-media/src/schema/videoVariant/inputs/videoVariantCreate.ts
  apis/api-media/src/schema/videoVariant/inputs/videoVariantUpdate.ts
  apis/api-media/src/schema/videoVariant/videoVariant.spec.ts
  apis/api-media/src/schema/videoVariant/videoVariant.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: soon, type: feat, effort: 1, on stage

#5271 chore: update cursorrules
  .cursorrules
Labels: priority: 2day, effort: 1, type: chore

#5200 feat: improve image loading performance
  libs/journeys/ui/src/components/Card/Card.spec.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.spec.tsx
  libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
  libs/journeys/ui/src/components/Card/ExpandedCover/ExpandedCover.tsx
  libs/journeys/ui/src/components/Image/Image.tsx
Labels: effort: 2, priority: soon, type: feat, chromatic

#5281 fix: shortlink update
  apps/short-links/src/app/[hostname]/[...pathname]/page.ts
Labels: effort: 2, type: fix, priority: soon, on stage

#5241 feat: schema changes to gridcontaineritem
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/db/migrations/20250213020506_20250213020504/migration.sql
  apis/api-journeys/db/schema.prisma
  apis/api-journeys/schema.graphql
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-journeys/src/app/modules/block/gridContainer/gridContainer.graphql
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: priority: now, priority: soon, type: feat, effort: 1, on stage

#5262 fix: improve speed of media languages
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/language/language.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 2, type: fix, effort: 3, priority: soon, type: feat, effort: 1, type: chore, type: perf

#5290 feat: use the new queries in the route
  apps/arclight/src/app/v2/media-languages/[languageId]/route.ts
  apps/arclight/src/app/v2/media-languages/route.ts
Labels: effort: 2, type: fix, effort: 3, priority: soon, type: feat, effort: 1, type: chore

#5291 chore: add masterurl to video variant no qa
  apis/api-media/db/migrations/20250217191209_20250217191207/migration.sql
  apis/api-media/db/schema.prisma
  apis/api-media/src/schema/video/video.spec.ts
  apis/api-media/src/schema/videoVariant/videoVariant.spec.ts
  apis/api-media/src/workers/bigQuery/importers/index.ts
  apis/api-media/src/workers/bigQuery/importers/masterUrls/index.ts
  apis/api-media/src/workers/bigQuery/importers/masterUrls/masterUrls.spec.ts
  apis/api-media/src/workers/bigQuery/importers/masterUrls/masterUrls.ts
  apis/api-media/src/workers/bigQuery/service/service.spec.ts
  apis/api-media/src/workers/bigQuery/service/service.ts
Labels: effort: 2, type: fix, effort: 3, priority: soon, type: feat, type: chore, on stage

#5199 feat: spacer block
  apps/journeys-admin/__generated__/BlockDuplicate.ts
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/BlockRestore.ts
  apps/journeys-admin/__generated__/CardCtaRestore.ts
  apps/journeys-admin/__generated__/CardFormRestore.ts
  apps/journeys-admin/__generated__/CardIntroRestore.ts
  apps/journeys-admin/__generated__/CardPollRestore.ts
  apps/journeys-admin/__generated__/CardQuoteRestore.ts
  apps/journeys-admin/__generated__/GetAdminJourney.ts
  apps/journeys-admin/__generated__/GetAdminJourneyWithPlausibleToken.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/MenuBlockRestore.ts
  apps/journeys-admin/__generated__/SpacerBlockCreate.ts
  apps/journeys-admin/__generated__/SpacerFields.ts
  apps/journeys-admin/__generated__/SpacerSpacingUpdate.ts
  apps/journeys-admin/__generated__/StepBlockRestoreFromAction.ts
  apps/journeys-admin/__generated__/StepBlockRestoreFromSocialPreview.ts
  apps/journeys-admin/__generated__/StepBlockRestoreFromStep.ts
  apps/journeys-admin/__generated__/StepDuplicate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewSpacerButton/NewSpacerButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewSpacerButton/NewSpacerButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewSpacerButton/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Spacer/Spacer.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Spacer/Spacer.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Spacer/Spacing/Spacing.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Spacer/Spacing/Spacing.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Spacer/Spacing/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Spacer/index.ts
  apps/journeys-admin/src/libs/apolloClient/cache.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/SpacerFields.ts
  apps/journeys/src/libs/apolloClient/cache/cache.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/GetJourney.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/SpacerFields.ts
  apps/watch/src/libs/apolloClient/cache.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
  libs/journeys/ui/src/components/Spacer/Spacer.spec.tsx
  libs/journeys/ui/src/components/Spacer/Spacer.stories.tsx
  libs/journeys/ui/src/components/Spacer/Spacer.tsx
  libs/journeys/ui/src/components/Spacer/__generated__/SpacerFields.ts
  libs/journeys/ui/src/components/Spacer/index.ts
  libs/journeys/ui/src/components/Spacer/spacerFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
  libs/journeys/ui/src/libs/block/blockFields.ts
  libs/journeys/ui/src/libs/useJourneyQuery/__generated__/GetJourney.ts
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/icons/Crop169.tsx
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: effort: 2, effort: 5, effort: 3, priority: now, priority: soon, type: feat, effort: 1, on stage, chromatic

#5299 Revert "feat: spacer block (#5199)"
  apps/journeys-admin/__generated__/BlockDuplicate.ts
  apps/journeys-admin/__generated__/BlockFields.ts
  apps/journeys-admin/__generated__/BlockRestore.ts
  apps/journeys-admin/__generated__/CardCtaRestore.ts
  apps/journeys-admin/__generated__/CardFormRestore.ts
  apps/journeys-admin/__generated__/CardIntroRestore.ts
  apps/journeys-admin/__generated__/CardPollRestore.ts
  apps/journeys-admin/__generated__/CardQuoteRestore.ts
  apps/journeys-admin/__generated__/GetAdminJourney.ts
  apps/journeys-admin/__generated__/GetAdminJourneyWithPlausibleToken.ts
  apps/journeys-admin/__generated__/GetJourney.ts
  apps/journeys-admin/__generated__/GetPublisherTemplate.ts
  apps/journeys-admin/__generated__/JourneyFields.ts
  apps/journeys-admin/__generated__/MenuBlockRestore.ts
  apps/journeys-admin/__generated__/SpacerBlockCreate.ts
  apps/journeys-admin/__generated__/SpacerFields.ts
  apps/journeys-admin/__generated__/SpacerSpacingUpdate.ts
  apps/journeys-admin/__generated__/StepBlockRestoreFromAction.ts
  apps/journeys-admin/__generated__/StepBlockRestoreFromSocialPreview.ts
  apps/journeys-admin/__generated__/StepBlockRestoreFromStep.ts
  apps/journeys-admin/__generated__/StepDuplicate.ts
  apps/journeys-admin/__generated__/globalTypes.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewSpacerButton/NewSpacerButton.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewSpacerButton/NewSpacerButton.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewSpacerButton/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Spacer/Spacer.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Spacer/Spacer.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Spacer/Spacing/Spacing.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Spacer/Spacing/Spacing.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Spacer/Spacing/index.ts
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Spacer/index.ts
  apps/journeys-admin/src/libs/apolloClient/cache.ts
  apps/journeys/__generated__/BlockFields.ts
  apps/journeys/__generated__/GetJourney.ts
  apps/journeys/__generated__/JourneyFields.ts
  apps/journeys/__generated__/SpacerFields.ts
  apps/journeys/src/libs/apolloClient/cache/cache.ts
  apps/watch/__generated__/BlockFields.ts
  apps/watch/__generated__/GetJourney.ts
  apps/watch/__generated__/JourneyFields.ts
  apps/watch/__generated__/SpacerFields.ts
  apps/watch/src/libs/apolloClient/cache.ts
  libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
  libs/journeys/ui/src/components/Spacer/Spacer.spec.tsx
  libs/journeys/ui/src/components/Spacer/Spacer.stories.tsx
  libs/journeys/ui/src/components/Spacer/Spacer.tsx
  libs/journeys/ui/src/components/Spacer/__generated__/SpacerFields.ts
  libs/journeys/ui/src/components/Spacer/index.ts
  libs/journeys/ui/src/components/Spacer/spacerFields.ts
  libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
  libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
  libs/journeys/ui/src/libs/block/blockFields.ts
  libs/journeys/ui/src/libs/useJourneyQuery/__generated__/GetJourney.ts
  libs/locales/en/apps-journeys-admin.json
  libs/shared/ui/src/components/icons/Crop169.tsx
  libs/shared/ui/src/components/icons/Icon.tsx
  libs/shared/ui/src/components/icons/icon.stories.tsx
Labels: breaking, priority: now, effort: 1, type: chore, on stage, chromatic

#5286 chore: remove qrcode flag
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/QrCodeDialog/QrCodeDialog.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.spec.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.stories.tsx
  apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.tsx
  libs/locales/en/apps-journeys-admin.json
Labels: effort: 2, priority: now, priority: soon, effort: 1, type: chore, on stage

#5312 fix: add keywords to algolia videos
  apis/api-media/src/workers/algolia/service/service.ts
Labels: type: fix, priority: now, effort: 1

#5304 feat: add locked to VideosFilter
  apis/api-media/src/schema/video/inputs/videosFilter.ts
  apis/api-media/src/schema/video/lib/videosFilter/videosFilter.spec.ts
  apis/api-media/src/schema/video/lib/videosFilter/videosFilter.ts
Labels: effort: 3, priority: soon, type: feat, effort: 1, on stage

#5314 fix: resources end point
  apps/arclight-e2e/src/e2e/resources/index.spec.ts
  apps/arclight/src/app/v2/[...route]/_resources/index.ts
Labels: effort: 2, type: fix, priority: soon, effort: 1

#5317 fix: use correct query to get series count
  apps/arclight/src/app/v2/[...route]/_media-languages/index.ts
Labels: effort: 2, type: fix, priority: soon, effort: 1

#5293 chore: node 22 github actions
  .github/workflows/api-deploy-worker.yml
  .github/workflows/api-gateway-prod-worker.yml
  .github/workflows/api-gateway-stage-worker.yml
  .github/workflows/app-deploy.yml
  .github/workflows/autofix.ci.yml
  .github/workflows/danger.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/ecs-frontend-deploy-prod-worker.yml
  .github/workflows/ecs-frontend-deploy-stage-worker.yml
  .github/workflows/main.yml
  .github/workflows/visual-test.yml
Labels: priority: now, effort: 1, type: chore

#5332 chore: run main generates
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  apps/watch/__generated__/globalTypes.ts
Labels: effort: 2, type: fix, effort: 3, priority: soon, type: feat, effort: 1, type: chore

#5335 fix: broken test in CI
  libs/journeys/ui/src/libs/blurImage/blurImage.spec.ts
Labels: effort: 2, type: fix, priority: now

#5337 ci: disable broken template e2e
  apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
Labels: type: fix, priority: now, effort: 1

#5323 fix: wait for video to load before select
  apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.spec.tsx
  apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
Labels: type: fix, priority: soon, effort: 1

#5333 feat: add openai swagger zod to hono no qa
  apps/arclight-e2e/src/e2e/resources/index.spec.ts
  apps/arclight/src/app/v2/[...route]/_media-component-links/[mediaComponentId]/index.ts
  apps/arclight/src/app/v2/[...route]/_media-component-links/index.ts
  apps/arclight/src/app/v2/[...route]/_media-components/[mediaComponentId]/index.ts
  apps/arclight/src/app/v2/[...route]/_media-components/[mediaComponentId]/languages/[languageId]/index.ts
  apps/arclight/src/app/v2/[...route]/_media-components/[mediaComponentId]/languages/index.ts
  apps/arclight/src/app/v2/[...route]/_media-components/index.ts
  apps/arclight/src/app/v2/[...route]/_media-countries/[countryId]/index.ts
  apps/arclight/src/app/v2/[...route]/_media-countries/index.ts
  apps/arclight/src/app/v2/[...route]/_media-country-links/index.ts
  apps/arclight/src/app/v2/[...route]/_media-languages/[languageId]/index.ts
  apps/arclight/src/app/v2/[...route]/_media-languages/index.ts
  apps/arclight/src/app/v2/[...route]/_metadata-language-tags/[metadataLanguageTag]/index.ts
  apps/arclight/src/app/v2/[...route]/_metadata-language-tags/index.ts
  apps/arclight/src/app/v2/[...route]/_resources/index.ts
  apps/arclight/src/app/v2/[...route]/links.schema.ts
  apps/arclight/src/app/v2/[...route]/mediaComponent.schema.ts
  apps/arclight/src/app/v2/[...route]/route.ts
  package-lock.json
  package.json
Labels: breaking, effort: 5, effort: 3, priority: now, priority: soon, type: feat, effort: 1

#5350 chore: add jf-proxy worker and deploy workflow
  .github/workflows/worker-deploy.yml
  .gitignore
  apps/short-links-e2e/.eslintrc.json
  apps/short-links-e2e/eslint.config.js
  nx.json
  package-lock.json
  package.json
  vitest.workspace.ts
  workers/jf-proxy/.gitignore
  workers/jf-proxy/eslint.config.js
  workers/jf-proxy/package.json
  workers/jf-proxy/project.json
  workers/jf-proxy/src/assets/.gitkeep
  workers/jf-proxy/src/cloudflare-test.d.ts
  workers/jf-proxy/src/index.spec.ts
  workers/jf-proxy/src/index.ts
  workers/jf-proxy/tsconfig.app.json
  workers/jf-proxy/tsconfig.json
  workers/jf-proxy/tsconfig.spec.json
  workers/jf-proxy/vite.config.ts
  workers/jf-proxy/vitest.config.ts
  workers/jf-proxy/wrangler.toml
Labels: effort: 5, priority: now, type: chore, on stage

#5354 fix: update jf-proxy configuration for production routes and environments
  workers/jf-proxy/project.json
  workers/jf-proxy/src/index.spec.ts
  workers/jf-proxy/src/index.ts
  workers/jf-proxy/wrangler.toml
Labels: type: fix, priority: now, effort: 1, on stage

#5361 fix: validate asset
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/cloudflare/r2/asset.spec.ts
  apis/api-media/src/schema/cloudflare/r2/asset.ts
  apis/api-media/src/schema/cloudflare/r2/inputs/cloudflareR2Create.ts
  apis/api-media/src/schema/cloudflare/r2/inputs/cloudflareR2Update.ts
  apis/api-media/src/schema/cloudflare/r2/inputs/index.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 2, type: fix, effort: 3, priority: soon, type: feat, effort: 1, on stage

#5363 fix: improve media lanugages performance
  apps/arclight/src/app/v2/[...route]/_media-languages/index.ts
Labels: effort: 2, type: fix, effort: 3, priority: soon, type: chore, type: perf

#5379 feat: backend optimizations for arclight media languages no qa
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/builder.ts
  apis/api-media/src/schema/language/language.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/arclight/src/app/v2/[...route]/_media-languages/index.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
  package-lock.json
  package.json
Labels: effort: 2, priority: soon, type: feat, on stage

#5385 fix: limit and page type issue
  apps/arclight-e2e/src/e2e/media-components/index.spec.ts
  apps/arclight-e2e/src/e2e/media-countries/index.spec.ts
  apps/arclight-e2e/src/e2e/media-languages/index.spec.ts
  apps/arclight/src/app/v2/[...route]/_media-components/index.ts
  apps/arclight/src/app/v2/[...route]/_media-countries/index.ts
  apps/arclight/src/app/v2/[...route]/_media-languages/index.ts
Labels: effort: 2, type: fix, effort: 3, priority: soon, effort: 1, type: chore

#5351 feat: add mux metadata
  apps/arclight/infrastructure/locals.tf
  apps/arclight/src/app/videoPlayerUrl/VideoPlayer.tsx
  apps/journeys-admin/infrastructure/locals.tf
  apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoPlayer.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.spec.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/getMuxMetadata/getMuxMetadata.spec.tsx
  libs/journeys/ui/src/components/Video/InitAndPlay/getMuxMetadata/getMuxMetadata.ts
  libs/journeys/ui/src/components/Video/InitAndPlay/getMuxMetadata/index.ts
  libs/journeys/ui/src/components/Video/Video.tsx
  libs/journeys/ui/tsconfig.lib.json
  libs/shared/ui/src/libs/muxMetadataType/index.ts
  libs/shared/ui/src/libs/muxMetadataType/muxMetadataType.ts
Labels: effort: 2, effort: 5, effort: 3, priority: now, priority: soon, type: feat, on stage

#5393 feat: expand cloudflare asset db call
  apis/api-analytics/src/__generated__/graphql-env.d.ts
  apis/api-gateway/schema.graphql
  apis/api-journeys-modern/src/__generated__/graphql-env.d.ts
  apis/api-journeys/src/__generated__/graphql.ts
  apis/api-languages/src/__generated__/graphql-env.d.ts
  apis/api-media/db/migrations/20250228203405_20250228203402/migration.sql
  apis/api-media/db/schema.prisma
  apis/api-media/schema.graphql
  apis/api-media/src/__generated__/graphql-gateway-env.d.ts
  apis/api-media/src/__generated__/graphql-subgraph-env.d.ts
  apis/api-media/src/schema/cloudflare/r2/asset.spec.ts
  apis/api-media/src/schema/cloudflare/r2/asset.ts
  apis/api-media/src/schema/cloudflare/r2/inputs/cloudflareR2Create.ts
  apis/api-media/src/schema/video/video.spec.ts
  apps/arclight/src/__generated__/graphql-env.d.ts
  apps/short-links/src/__generated__/graphql-env.d.ts
  apps/videos-admin/src/__generated__/graphql-env.d.ts
Labels: effort: 2, effort: 3, priority: soon, type: feat, on stage

#5295 feat: edition CRUD
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionCard/EditionCard.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionCard/EditionCard.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionCard/EditionCard.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionCard/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionCreate/EditionCreate.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionCreate/EditionCreate.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionCreate/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionDelete/EditionDelete.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionDelete/EditionDelete.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionDelete/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionDialog.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionDialog.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionDialog.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionEdit/EditionEdit.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionEdit/EditionEdit.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionEdit/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionView/EditionView.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionView/EditionView.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/EditionView/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionDialog/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionForm/EditionForm.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionForm/EditionForm.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionForm/EditionForm.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/EditionForm/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/Editions.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/Editions.stories.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/Editions.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Editions/index.ts
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.spec.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
  apps/videos-admin/src/app/[locale]/(dashboard)/videos/_VideoList/VideoCreateForm/VideoCreateForm.tsx
  apps/videos-admin/src/libs/useAdminVideo/index.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts
  apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.tsx
  apps/videos-admin/src/types/array-types.ts
  libs/locales/en/apps-videos-admin.json
Labels: effort: 5, effort: 3, priority: soon, type: feat, on stage
